### ISSUE TITLE
Missing Datasets? Match emails with user record (from My Datasets)

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#10]
After logging in and if no datasets we'd have a notification like in this wireframe (forget about the GDPR on that screen for now). 

https://jxosix.axshare.com/#g=1&p=my_datasets_-_v1

Then they 'd go through this validation routine.

https://jxosix.axshare.com/#g=1&p=migrate_data_-_v1

I believe what this would switch the current_user to the matching email record and update any information in that user record and remove discarded user record.

**Comment by daisieh** [comment]
Rough draft is posted as https://github.com/CDL-Dryad/stash/pull/12
