### ISSUE TITLE
Please hide two versions of dataset and retain most recent published version (doi:10.6071/M39M2T)

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1018]
**Request:**

For dataset doi: 10.6071/M39M2T

- Hide data files for versions 11-30-2020 and 12-9-2020 
- Retain version 1-5-2021

**Comment by LoriEP** [comment]
Thank you @sfisher. I will rewrite the ticket and take your recommendation.

**Comment by LoriEP** [comment]
@sfisher @dlowenberg updated ticket please let me know if I should do anything else or if anything needs to be clarified

**Comment by sfisher** [comment]
Thanks, Lori.  I've hidden the old versions and it just shows the current one.  https://datadryad.org/stash/dataset/doi:10.6071/M39M2T

Let me know if there are any problems.

**Comment by LoriEP** [comment]
Looks good to me @sfisher thank you for the quick work.
