### ISSUE TITLE
Author reports that they cannot find dataset (doi:10.5061/dryad.2rd20f3) in their dashboard

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1032]
**Request:** Please migrate dataset for author a.edelsparre@utoronto.ca with ORCID 0000-0002-7779-6639 

Dataset appears to be from v1 Dryad and author states they attempted to migrate the dataset

**Comment by ryscher** [comment]
This dataset is owned by the original submitter, Mark Fitzpatrick. I don't believe we have any policies around changing ownership.

@dlowenberg This probably fits in with the discussions about the Corresponding Author feature. How do you want to proceed?

**Comment by dlowenberg** [comment]
@LoriEP - we cannot assume authorship can be transferred per publishing ethics standards. I will take this case over if you can chat me on it in Salesforce so I know which one it is and then @ryscher can you just grab me Mark Fitzpatrick's email that we have saved? Thanks both

**Comment by LoriEP** [comment]
@dlowenberg I could not see in the logs it belonged to another author, my bad. I'l send you the info via slack.

**Comment by ryscher** [comment]
We discussed this at dev standup -- since the original dataset was submitted to the v1 system by one person, but they set the Corresponding Author to another person, we went ahead and made the ownership change.
