### ISSUE TITLE
Dataset (doi:10.5061/dryad.9zw3r22bt) stuck in processing 

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1034]
**Bug description:**
Dataset is stuck 'processing' after the last automatic job of moving dataset from PPR to Submitted 

**Steps to reproduce:**
Navigate to doi **10.5061/dryad.9zw3r22bt**
review activity log 

**Expected behavior:**
Dataset should be in the status of 'Submitted'

**Comment by ryscher** [comment]
Moved to `Submitted`
