### ISSUE TITLE
Please merge accounts for Courtney Murdock (ORCID:0000-0001-5966-1514)

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1035]
**Request:** Please merge following email addresses for user cmurdock@uga.edu and ccm256@cornell.edu

**Comment by sfisher** [comment]
I merged the two accounts.  It looks like there might be a 3rd account also which owns this one dataset at https://datadryad.org/stash/dataset/doi:10.5061/dryad.c6s34 .  That email is ccm15@psu.edu .  Should i merge that one in with the other two, also?

**Comment by sfisher** [comment]
I'm pretty sure this is the same person since the dataset is about malaria which is a subject of their research in the other accounts, so I merged the 3rd account in also.

**Comment by LoriEP** [comment]
Thanks @sfisher I did reach out to the author to confirm. If they say it is not, I will let you know, but her email addresses look very similar.

**Comment by LoriEP** [comment]
Confirmed @sfisher they are the same person!
