### ISSUE TITLE
Dataset (doi:10.5061/dryad.cc2fqz652) stuck in processing 

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1043]
**Bug description:**
Dataset is stuck in 'processing'

**Steps to reproduce:**
Navigate to doi 10.5061/dryad.cc2fqz652, see that dataset is stuck in processing, author previously had it in progress 

**Expected behavior:**

**Comment by sfisher** [comment]
This is fixed.  It seems like somehow the author opened the same version 2 times (exactly the same timestamp).  Not sure how they were able to do it, but they must've been very fast because they are prevented if one already exists.

Anyway, removed the duplicate copy of a version and this is fixed.

**Comment by LoriEP** [comment]
Thank you! They're lightning fast I guess.
