### ISSUE TITLE
Dataset stuck in processing (doi:10.5061/dryad.b2rbnzsbm)

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1055]
**Request:** dataset stuck in processing, please push through

**Comment by sfisher** [comment]
This is fixed now.  There was some kind of creation of two versions of the same dataset at once (luckily the files are the same).  I resubmitted the last one to make the versions between our storage and database match.

I believe everything should be fine, but just take a look to be sure whatever metadata was changed most recently looks correct.

**Comment by LoriEP** [comment]
Thank you, we will make sure the changes are saved
