### ISSUE TITLE
When POSTing a new dataset, do not accept if the request specifies an identifier (doi).

### ISSUE THREAD

**Issue by daisieh** [CDL-Dryad/dryad-product-roadmap#106]
Because identifiers have to be unique, POST will not behave as expected if multiple POST requests with a specified identifier are made. The correct way to create a new resource with a specific identifier is PUT, since presumably we only want to have a single resource with that identifier, and all future requests will be to modify that one and not create more. https://restfulapi.net/rest-put-vs-post/

However, this is not at all an intuitive behavior. Currently, the create method ignores the user's requested identifier and returns a new unique one. This can lead to confusion. I propose that if a user sends a POST request with an identifier specified, a 409: Conflict error should be returned: “This code is only allowed in situations where it is expected that the user might be able to resolve the conflict and resubmit the request. The response body SHOULD include enough information for the user to recognize the source of the conflict.”

**Comment by daisieh** [comment]
Although now that I read some of the comments on the linked blog post, I see that the POST behavior has been updated somewhat (https://tools.ietf.org/html/rfc7231#section-4.3.3): "The POST method requests that the target resource process the representation enclosed in the request according to the resource's own specific semantics."

Both "Creating a new resource that has yet to be identified by the origin server; and...  Appending data to a resource's existing representation(s)" are acceptable responses to a POST request. We could then respond with a 303 if the identifier already exists, and then "If the result of processing a POST would be equivalent to a representation of an existing resource, an origin server MAY redirect the user agent to that resource by sending a 303 (See Other) response with the existing resource's identifier in the Location field.

**Comment by ryscher** [comment]
This was fixed long ago.
