### ISSUE TITLE
UBC datasets information

### ISSUE THREAD

**Issue by tracykteal** [CDL-Dryad/dryad-product-roadmap#1062]
University of British Columbia is interested in their usage. Could I get a report of all the datasets in 2019 and 2020 where there is a UBC author? Thank you so much!

**Comment by ryscher** [comment]
Data for all years is available in https://docs.google.com/spreadsheets/d/1vSM-QLXgt9COYJUM70EgdHmqTmVjEjw8zULGGvNIwb0/edit#gid=0

Note that some datasets are duplicated, because every UBC author is listed.
