### ISSUE TITLE
Import Metadata not working for multiple manuscripts entries 

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1064]
**Bug description:**
We have received reports that the import metadata button is not importing article level metadata. Upon testing a handful of manuscript and publication combinations with acceptance notices, can confirm import is not working.

**Steps to reproduce:**
Navigate to a new dataset, enter in Ornithological Applications, test ms # CONDOR-20-178  with acceptance notice received on 1-14-21. 
Click to import metadata
Receive error ('We could not find metadata to import for this manuscript. Please enter your metadata below.')

Also tested PALA-01-21-4986-OA with journal Palaeontology and additional combinations from Molecular Ecology and Molecular Ecology Resources, and Ornithology all with recent (2 weeks or less) acceptance notices.

**Expected behavior:**
Navigate to new dataset, enter in manuscript number and journal name for integrated journal with valid acceptance notice
click to import button,
metadata is populated into dataset metadata fields

**Comment by ryscher** [comment]
Fixed. When the v1 server ran out of disk space a while ago, it trashed the credentials that allowed it to connect to GMail. Sorry I didn't notice that earlier.

**Comment by LoriEP** [comment]
Thank you for resolving!   Is this something we need to keep an eye on in the future?

**Comment by ryscher** [comment]
No need for you to change anything on your end. We will be moving this processing out of the v1 system soon. As part of that work, we will be adding an automatic system to monitor it.

**Comment by LoriEP** [comment]
Sounds great!
