### ISSUE TITLE
Data file will not download for v1 dataset, error (doi:10.5061/dryad.m25t886)

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1068]
**Request** 
Please fix the following error so that the dataset can be downloaded.

**Note:**
 Dataset cannot be downloaded via 'Download Dataset' (it times out, no processing at all) 
Data file cannot be downloaded via clicking on the individual file, error thrown ("We're sorry, but something went wrong.
If you are the application owner check the logs for more information.")

**Comment by LoriEP** [comment]
Author has dataset in progress, but stated that they have no changes that need to be submitted.

**Comment by sfisher** [comment]
It looks like this is data from old dryad and also it contains an ampersand character.  I believe this is an error we will need to take up with the Merritt team about how they're handling encoding or may be a bigger issue in some of their internal systems.

The URL we're requesting is this one which looks correctly encoded to me.  http://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5b61qpk/4/producer%2FSelz_%26_Seehausen_data_file.xlsx?no_redirect=true

If needed we may be able to work around the problem by submitting another version without the character in the filename and manipulate things to keep the old dates, etc and make that the visible version.

**Comment by LoriEP** [comment]
That would be up to you and Daniella, I am fine with either resolution. If there is an easy way to resolve this for this specific dataset only that would be preferred as it is probably a faster resolution but perhaps we might see more of these from v1 and have to address the merritt team anyway.

**Comment by sfisher** [comment]
I submitted another version with their existing file but changed it to an "and" instead of an ampersand since it's also problematic in (at least old versions) of Windows as a disallowed character in a filename.

I fixed up the dates in the new version so it appears as the original date and tested both downloads work for it.

**Comment by LoriEP** [comment]
Tested, works as expected thank you.
