### ISSUE TITLE
Find filenames with potentially problematic characters and check downloads

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1070]
- [x] Find filenames with potentially problematic filenames (criteria?) definitely &, ?,  (we have a list of some in our code we usually don't allow in the ui).
- [x] Check downloads for them
- [x] Resubmit a version to fix issues in filenames if we find any
- [x] Update data so that we don't show crazy new submission dates for our "correction" versions.

**Comment by ryscher** [comment]
I have looked at many files in our system with various characters in the filename, including &, ?, *. Although there are some truly terrible names in there, every file I tested was able to download properly. I assume the problem that inspired this ticket was truly a one-off, so I am considering this ticket finished.
