### ISSUE TITLE
Merritt UC Collection --> Dryad Migration

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1092]
The tasks that need to be done one the afternoon/evening of migration.  Currently scheduled for Weds, Feb 10th.

- [x] Pause submissions to Merritt 30 minutes ahead
- [x] Get file from David Loy in the format he specified like `doi:10.5072/FK20R9S858|ark:/99999/fk4np2b23p|ark:/99999/fk4cv5xm2w` for every line. `DOI|old ARK|new ARK`
- [x] Make git branch of our latest release and merge in the `uc-mrt-migration` branch which contains our configuration changes to make all tenants use the dryad collection.
- [x] Deploy the new branch with changed configuration to our servers
- [x] Run rake task against the file David provides which will do the database updates for these items to point them at correct ARKs and merritt collections. `RAILS_ENV="production" bundle exec rake dev_ops:download_uri </path/to/davids/file>`
  - [x] Manually fix any that don't update, though we don't expect this to happen.
- [x] Manually test a small number to be sure the download still work from the new Dryad collection.
- [x] Resume normal submission state and re-enqueue any submissions that were held.

**Comment by elopatin-uc3** [comment]
This relates to https://github.com/CDLUC3/mrt-doc/issues/536, https://github.com/CDLUC3/mrt-doc/issues/482
