### ISSUE TITLE
Find out of this Shibboleth change affects us and take action if necessary

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1097]
"I just noticed my shibboleth is going to stop working March 15, 2021"
https://spaces.at.internet2.edu/display/MDQ/migrate-to-mdq

(from brian tingle)

**Comment by dlowenberg** [comment]
Hey @marisastrong is this something that we need to figure out ASAP or will it not affect us?

**Comment by sfisher** [comment]
Brian Riley, Ashley and I met about this on Monday.  It seems like it is something that will affect us.  Brian Tingle had examples of what needed to be changed.

The plan is that Ashley is going to make changes to DMP stage server for testing first.  Then make changes to Dryad dev and stage for our testing.  Then make changes to the production systems.  There is a ticket in pivotal tracker, but we should follow up and be sure this gets done.

From what Brian Tingle said the deadline is March 1st, but they have a cache or keep the old way working servers running until March 15th at which point our logins might abruptly fail.

**Comment by dlowenberg** [comment]
Thanks for the update
