### ISSUE TITLE
Please apply country waiver to dataset doi:(10.5061/dryad.wm37pvmmh)

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1098]
**Request:** Please apply country waiver as affiliation is in Laos (Lao PDR) however affiliation is not in ROR therefore system did not apply waiver automatically.

**Comment by sfisher** [comment]
I think I did what is required for this, but I didn't see documentation so not sure.  (I searched for "fee waiver" and "waiver" and "fee").  I just changed the fee information in stash_engine_identifiers.

@ryscher let me know in the morning.

**Comment by ryscher** [comment]
I added a `payment_id` with the country name. Documentation is in the Troubleshooting doc at https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/server_maintenance/troubleshooting.md. It includes the word "waiver". I will add "fee waiver". Let me know if there is something else that would make it easier to find.
