### ISSUE TITLE
The Auk: Ornithological Advances not populating in auto-complete Journal Name drop down 

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1099]
**Request:** Please identify why The Auk: Ornithological Advances is not appearing in drop down. Have tested that other journal names are working as expected.

**Note** This journal is integrated and sponsors datasets. May want to be sure journal concept is up to date if there is an issue.

**Comment by dlowenberg** [comment]
note: I saw that their other journal "The Condor" isn't appearing in dropdown - I feel like they changed journal names recently but from my last email with them in May those are the names

**Comment by LoriEP** [comment]
Note:I saw this on their website: AOS is excited to announce changes to the names of its two journals. Beginning in 2021, our journals will be published under the new titles Ornithology for Auk and Ornithological Applications for Condor.

I see that Ornithological Applications is UTD in our system via the Journal name drop down.

**Comment by ryscher** [comment]
These names were updated in ticket https://github.com/CDL-Dryad/dryad-product-roadmap/issues/875
