### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#110]
Change Admin Dashboard:
- By dataset
- Search: by title, by DOI, by author
- Filter: by institution, by status
- Sort
- Editable status & pub date
- Link to activity log

http://ux.cdlib.org/jlee/completed/dryad_03oct2018/#g=1&p=admin_dashboard_v2

**Comment by ryscher** [comment]
This was completed long ago
