### ISSUE TITLE
Allow API users to set page size on all calls

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#1101]
I'm not certain whether this is needed, but I'm documenting the issue in case we decide to do it.

Some API calls allow a page size to be set with the parameter `per_page`. Other API calls do not allow the page size to be set.

If we allow `per_page` to be specified for all calls, we need to be careful to define the `paging_hash` correctly in each call, so the number of pages that is listed in the response corresponds to the actual number of pages available.

**Comment by hubgit** [comment]
I've found that although the `api/v2/datasets` endpoint has [a documented `per_page` parameter](https://datadryad.org/api/v2/docs/#/default/get_datasets), this doesn't actually have any effect as it's not passed through to the paginator (there are always 20 items in each page, which is the default page size).

https://github.com/CDL-Dryad/dryad-app/blob/d8b964f4c964eb7a5a5ce1f491024cc6cb9d5bff/stash/stash_api/app/controllers/stash_api/datasets_controller.rb#L266

https://github.com/CDL-Dryad/dryad-app/blob/d8b964f4c964eb7a5a5ce1f491024cc6cb9d5bff/stash/stash_api/app/controllers/stash_api/datasets_controller.rb#L548
