### ISSUE TITLE
Author and Curator made changes at the same time, created conflict, dataset stuck in progress (10.5061/dryad.n5tb2rbts)

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1102]
**Request:** 

Dataset author and curator made changes simultaneously and it seems both have now lost access to editing the dataset.

**Comment by sfisher** [comment]
OK.  This is fixed and is able to be edited again.  I removed the latest version that the author tried to create because it looked like it was in a strange state and the metadata from the previous version had not been duplicated correctly.

**Comment by LoriEP** [comment]
Thank you @sfisher

**Comment by sfisher** [comment]
You're welcome.  👍
