### ISSUE TITLE
v1 dataset will not download, in a state of embargo, but status is Published (doi: 10.5061/dryad.t3v71 )

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1105]
**Bug description:**
Data files cannot be downloaded individually or as a package. Download dataset button inactive, clicking elicits no response. Downloading an individual file produces an error message, "You are not authorized to download this file until it has been published."

**Steps to reproduce:**
Navigate to 10.5061/dryad.t3v71  in an incognito mode, click "Download Dataset"
Next, attempt to download individual files from either version of the dataset
Note the warning message

**Expected behavior:**
Data files should be available by download via Download dataset as package or as individual files

**Comment by ryscher** [comment]
Fixed. The `identifier` object had status `embargoed`, even though the individual resource versions were published.
