### ISSUE TITLE
Author reports that dataset is stuck in processing while in active editing mode, cannot submit (doi:10.5061/dryad.c59zw3r6h)

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1106]
**Request:** Identify why the author might be receiving this message (see attachment) and cannot submit dataset. Data files appear to be small (~96 kb) so not sure why they are receiving this message? 

Dataset activity log shows that the dataset is in progress, but author cannot submit changes.

![image001](https://user-images.githubusercontent.com/11345623/107099510-bb63d680-67c6-11eb-9ad1-c22989229002.jpg)

**Comment by ryscher** [comment]
Fixed. There were two duplicate versions with exactly the same timestamp (see https://github.com/CDL-Dryad/dryad-product-roadmap/issues/1056). I removed one and set the other to "submitted" status.
