### ISSUE TITLE
Create FTP account for Mariah Kenney (mkenney@datadryad.org)

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1109]
**Request:** Mariah will be assisting with FTP, she needs an account. 

Question: Does she need her public SSH key?

**Comment by ryscher** [comment]
@LoriEP Yes, please ask her to send me her public key.

**Comment by LoriEP** [comment]
@ryscher thank you for setting Mariah up!

**Comment by ryscher** [comment]
Mariah confirmed that she has access.
