### ISSUE TITLE
Landing show error

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#1110]
Users sometimes try invalid URLs, which produce uncaught errors. (And these errors cause email to Ryan and Scott.)

A sample invalid URL:
`<dryad_server_name>/stash/landing/show?id=qbv%3N10.506126%2Sqelnq.kq254746qqe`

Find where these are producing an error, and filter out the bad input so it no longer errors.

**Comment by cacods** [comment]
It' seems this is related with the rack webserver interface trying to decode the `qbv%3N10.506126%2Sqelnq.kq254746qqe`. rack uses a method from `ruby.uri.common` tha raises an `ArgumentError` in case of a part of the uri has percent-encode characters not valid. As my debug tentative it seems this check is done before entering in the Dryad routes system. But I'm not certain about that. I started to search in what entry point the email is sent after rack/ruby raises the error, but I couldn't find any So until now I don't devise a way for filtering this kind of uri mess inside the rails application or stash engine. Maybe there is a rack configuration that surpass this kind of exception. Check the code below for the error path.

rack-2.2.3/lib/rack/utils.rb
`
53    def unescape(s, encoding = Encoding::UTF_8)
54      URI.decode_www_form_component(s, encoding)
55   end
`

ruby/2.6.6/uri/common.rb

`
386  def self.decode_www_form_component(str, enc=Encoding::UTF_8)
387    raise ArgumentError, "invalid %-encoding (#{str})" if /%(?!\h\h)/ =~ str
388    str.b.gsub(/\+|%\h\h/, TBLDECWWWCOMP_).force_encoding(enc)
389  end
`

**Comment by ryscher** [comment]
We have caught most of these. New ones will be opened in new tickets.
