### ISSUE TITLE
When author resubmits dataset on accident or decides against resubmission with file changes, deleting files still creates an empty version

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1113]
**Background:**
In some cases, when an author wants to remove a file post-publication, they don't realize they are not truly removing the file, but rather creating a new version with the remaining files that were not selected for deletion. When the author is asked by a curator if they actually want to resubmit duplicate files already archived, or if they recognize they cannot remove the old file, they want to forego resubmission and publication. 

**Issue:** Curators cannot revert back to previously published version, our only option is to leave it in status where the changes won't persist, but that may create other issues for the author or our reporting/submission queue scripts. So therefore, curators delete the files and publish so the dataset is in a stable status. However, the result is an empty file new version of the dataset.

**Request:** When all files are deleted on a resubmission, do not create a new file version with date under Data Files. However, if there is a metadata change that was submitted along with file deletion, allow the metadata change to be submitted and published without creating an empty data file version. 

Screenshot attached:
<img width="407" alt="Screen Shot 2021-02-09 at 2 11 19 PM" src="https://user-images.githubusercontent.com/11345623/107437807-65ec3a00-6ae4-11eb-8bcd-ccd5eb77defe.png">

**Comment by LoriEP** [comment]
If this an easier one off ask whereby devs fix issues on case by case basis, that is fine, please feel free to close ticket and advise.

**Comment by sfisher** [comment]
Hi Lori,

If I understand correctly for a case like this we could just hide January 8th from view after February 9th is published and it would only show one date.  We do have the ability to hide published versions of a dataset and it's technically fairly easy to do so, though it may be more problematic at zenodo, I haven't looked into those details for a little while.

In the case of some especially problematic data (such as private data, copyright takedown notices, etc), we usually remove the entire dataset, just to be sure it's never exposed by us (and that is a PITA that we try to avoid) and then create a new dataset with just sanitized data.

Of course, there are curatorial, provenance and transparency reasons not to hide old data.  Once something is published, other people may already be using the data, writing code or publications against it.  Even if we hide it, it may very well be archived at archive.org or may be saved by anyone on the internet and the genie may already be out of the bottle even if we remove it from our site.  Amending publications or data seems more normal to me in the scholarly world, but 🤷‍♂️ .

**Comment by LoriEP** [comment]
Thanks @sfisher for this thorough explanation. I think this is a rare case and we can handle on a case by case basis. It is mostly so that empty 'versions' as a file placeholder are not created because it looks very strange. But really I could just ask for Feb 9th to be hidden in the future, if there was a case like this again. 

We rarely request a take down of a file unless as you said, there was a significant reason to do so. This was just an author misunderstanding that I had to try and fix.
