### ISSUE TITLE
Consider generating the "our community" list of partners from configuration.

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1115]
Right now we go update the list every time we add a partner institution.

We have the names of configured partners in our configuration and could dynamically create the list based on the configured partners.  That would save us from having to remember to update this list separately from adding new tenants.

**Comment by sfisher** [comment]
?  I still think is is an OK idea, but I feel like others had feedback about why we shouldn't.

**Comment by ryscher** [comment]
I support this. I think we had a couple of partners that requested specific wording, so it might require a field in the tenant config like `name_to_display_for_credit`. But even if it is needed, it would still be a win to keep from one-off edits to the static pages.

**Comment by ahamelers** [comment]
I actually tried to do this when updating the static page designs—I still have my work toward it in a stash—but ended up with a couple of differences between the two lists that I wasn't sure of the best way to resolve:

- The Chan Zuckerberg Initiative is listed under the manual 'Institutional members' list currently, but they are technically a funder, not a tenant
- The manual list contains 'University of California, California Digital Library', but the tenant file is for 'University of California, Office of the President'—which is the preferred name?
- 'Claremont College Services' is included in the tenants but isn't in the manual list. Should it be in the list? Under this name, or a different name for the consortium?

**Comment by ahamelers** [comment]
@sfisher @ryscher Any comments on the above?

**Comment by ryscher** [comment]
I suggest we err on the side of including more items, so 
- include Chan Zuckerberg (probably best to include anything listed in the `funder_exemptions`)
- Include Claremont College Services

For CDL/UCOP, I think we need to keep UCOP to have it displayed correctly on the Shibboleth selection. We want to include UCOP staff that are not part of CDL.

**Comment by sfisher** [comment]
Yes, @ryscher  is right.  I believe there have been a couple instances where someone outside of CDL (at UC Office of the President) used Dryad.  I think it's probably OK to make it UC Office of the President instead.

I believe there are other places in the "about Dryad" that the collaboration with California Digital Library is mentioned, or if not we can add them to give more specifics.

**Comment by ahamelers** [comment]
> (probably best to include anything listed in the funder_exemptions)

Sounds good, I think that shouldn't be a problem

> I believe there are other places in some "about Dryad" kind of page that the collaboration with California Digital Library is mentioned

Yes, it's very prominent in "Collaborations"
