### ISSUE TITLE
Merritt download troubles with some filenames

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1116]
for http://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5kq31dt/1/producer%2FTDR%20Acc%2BH2O.zip?no_redirect=true

See also the page on Merritt UI and try to download the file `TDR Acc+H2O.zip` from https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5kq31dt/1 .  Seems to be the same problem in both Dryad and Merritt.

There are a number of presigned URL problems from Merritt we keep being notified about (about 5 a day).  It seems like most of these contain the character `+` which is correctly encoded as `%2B` in our request URLs like above.  I believe Merritt is prematurely decoding %2B as a plus sign (which is a space in some query strings).  However, %2B should be passed through as a character to the script that operates on the filenames, not decoded in an earlier layer and interpreted as a space.

See for example https://www.w3schools.com/tags/ref_urlencode.ASP or https://tools.ietf.org/html/rfc3986 or many encoding/decoding libraries in languages such as Java or Ruby.

There may be some other issues in here, but most of these are from the `+` character encoded as `%2B` being mangled somewhere.

Also curl to test may be useful.

`curl -u username:password -L https://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5kq31dt/1/producer%2FTDR%20Acc%2BH2O.zip?no_redirect=true`

| filename | dataset url | resource id |
| --- | --- | --- |
| Baltic+6Regions_genera_sizes.xlsx | https://datadryad.org/stash/dataset/doi:10.5061/dryad.r7sqv9sb6 | 101525 |
| TDR Acc+H2O.zip | https://datadryad.org/stash/dataset/doi:10.5061/dryad.40gk7 | 1537 |
| HEAA_MER_Data+Scripts.zip | https://datadryad.org/stash/dataset/doi:10.5061/dryad.h4b48 | 14150 |
| Statham_Beast_mtDNA_modern+ancient_100M.tree | https://datadryad.org/stash/dataset/doi:10.5061/dryad.4g5gb | 24868 |
| raw data_FCM+morphometrics.xlsx | https://datadryad.org/stash/dataset/doi:10.5061/dryad.v7k54df | 22644 |
| level-0_fjord-boundaries.zip | https://datadryad.org/stash/dataset/doi:10.7280/D1FH5D | 86811 |
| level-1_shapefiles-domain-termini.zip | https://datadryad.org/stash/dataset/doi:10.7280/D1FH5D | 88168 |
| Crataegus subg. Sanguineae_collection sites + ecological variables.xlsx | https://datadryad.org/stash/dataset/doi:10.5061/dryad.75252 | 5365 |
| Crataegus subg Americanae + sanguinae_localities and bioclim data.xlsx | https://datadryad.org/stash/dataset/doi:10.5061/dryad.75252 | 5365 |

**Comment by elopatin-uc3** [comment]
@sfisher let us know if we can assist with this.

**Comment by sfisher** [comment]
Hi @elopatin-uc3 .  I've added more examples we've received warnings about and I think they are mostly caused by mishandling of the `%2B` in URLs.  This is an encoding for the + sign and should go through the pipeline so that the filename is interpreted that way.   It seems like it is being decoded early by something in Merritt or Apache so that it doesn't reach the final code intact.

**Comment by ryscher** [comment]
All of these have been fixed by the recent Merritt updates.
