### ISSUE TITLE
Update contact in journal module for Biological Journal of the Linnean Society

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1121]
"Could you please amend the template for the email 'Dryad Submission....' that provides the Biological Journal of the Linnean Society with the DOI once a deposition has been approved?
 
If possible, please ensure the following recipient is included: biolin_oup@newgen.co.  If necessary, you could remove 'biological.linnean@oup.com'."

**Comment by ryscher** [comment]
Added new email
