### ISSUE TITLE
Remove asterisks from displaying to the public in the related works section

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1125]
Asterisks are denoted for curators when the DOI doesn't validate, but it appears that the asterisk also displays on the published dataset for non-superusers. For example, open this dataset incognito mode: https://datadryad.org/stash/dataset/doi:10.5061/dryad.jdfn2z387

Let's remove the asterisk from showing up at publication (or to non-super users) since it is not meaningful to anyone else

**Comment by ryscher** [comment]
Asterisks will only show for superusers now. I also verified that this behavior works the same for affiliations.
