### ISSUE TITLE
Add AGU journals to journal module, cover cost for authors

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1126]
AGU Advances
·   	Earth's Future
·   	Earth and Space Science
·   	Geochemistry, Geophysics, Geosystems
·   	GeoHealth
·   	Geophysical Research Letters
·   	Global Biogeochemical Cycles
·   	Journal of Advances in Modeling Earth Systems (JAMES)
·   	Paleoceanography and Paleoclimatology
·   	Radio Science
·   	Reviews of Geophysics
·   	Space Weather
·   	Space Weather Quarterly
·   	Tectonics
·   	Water Resources Research
·   	JGR Atmospheres
·   	JGR Biogeosciences
·   	JGR Earth Surface

- ·   	Space Weather
- ·   	Space Weather Quarterly
- ·   	Tectonics
- ·   	Water Resources Research
- ·   	JGR Atmospheres
- ·   	JGR Biogeosciences
- ·   	JGR Earth Surface

**Comment by ryscher** [comment]
Set payment type to SUBSCRIPTION for existing journals. Created journals that didn't exist. Merged journal names for the JGR journals, which had several different representations (e.g., with and without colon).
