### ISSUE TITLE
Please remove empty file for Feb 9, 2021 for dataset doi: 10.5061/dryad.6djh9w10d

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1130]
**Background:**
Related to the scenario discussed in #1113 -- this author thought they could remove old files and resubmit, therefore leaving only the remaining files in the archive. Author did not want to resubmit exact copies of prior uploaded files, so they asked to remove that submission entirely, I attempted to, but it created an empty file for Feb. 9 2021.

**Request:** Please remove/hide Feb 9 2021 empty record.

**Comment by ryscher** [comment]
The Feb 9 version is now hidden.
