### ISSUE TITLE
Please associate Jérome Mathieu's ORCID (0000-0002-9106-6106) with new email address

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1131]
**Request:**
Please merge accounts for 0000-0002-9106-6106, email addresses that may have been used for old account:

jerome.mathieu@snv.jussieu.fr
jerome.mathieu@bondy.ird.fr
jerome.mathieu@nceas.ucsb.edu

Current email address: jerome.mathieu@upmc.fr

**Comment by ryscher** [comment]
Merged two accounts and updated current email address.
