### ISSUE TITLE
Please hide version of files for dataset doi: 10.5061/dryad.x3ffbg7hg

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1132]
**Request:** Please hide February 21, 2021 and the first February 23, 2021 (has 12 files in total) version for dataset from doi: 10.5061/dryad.x3ffbg7hg -- dataset published prior to FTP upload in error.

The data version(s) to keep
December 26, 2020
February 23, 2021 (archived at 02/24/2021 01:56:54 UTC) and has 14 files in total

**Comment by LoriEP** [comment]
I need to potentially add more to this ticket, please leave in backlog

**Comment by ryscher** [comment]
The extra versions are hidden now.
