### ISSUE TITLE
Promote 5 Kyoto University users to Administrators

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1133]
They've noted that they all logged in to Dryad already but let me know if that is not the case:

Shigeki Sugita
https://orcid.org/0000-0003-0573-6693

Shiho Murakami
https://orcid.org/0000-0001-8669-4725

Yuka Fujiwara
https://orcid.org/0000-0002-5750-5435

Hiroko Yoshida
https://orcid.org/0000-0002-0828-105X

Yumi Kitamura
https://orcid.org/0000-0002-2157-8499

**Comment by ryscher** [comment]
Updated role to `admin` for 5 users.
