### ISSUE TITLE
Please associate Maxwell Burton's new email address with ORCID 0000-0002-5330-0379 and merge accounts

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1136]
**Request:** 
Please merge accounts for ORCID: 0000-0002-5330-0379 prior email addresses max.burton-chellew@zoo.ox.ac.uk and max.burton-chellew@magd.ox.ac.uk 

current email address:  maxwell.burton@unil.ch

**Comment by sfisher** [comment]
Merged 3 accounts he had down to one.
