### ISSUE TITLE
Invoice was not generated for dataset doi: 10.5061/dryad.fj6q573rf

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1137]
**Request:** Please identify why invoice was not generated for 10.5061/dryad.fj6q573rf

**Note:** 
1. Dataset was not sponsored by journal SOIL and submitter was asked to agree to Dryad's payment terms. No invoice found in Stripe. Submitter stated they never received notification re: payment and wanted to pay. Dataset first published 2/4/21
2. Interesting to note that this appears to have been one of these datasets that are not moving to our submitted queue as expected, this one was not moved to the queue for one month (1/4/21 submitted) moved to curation on 2/4/21, potentially could be related?

**Comment by ryscher** [comment]
The journal was changed at some point during the dataset's lifecycle. Payment was charged to Soil Science Society of America Journal (ISSN 1435-0661), which has a payment plan.

I suggest we:
- Remove payment information from the dataset
- Generate a new Stripe invoice
- Check whether the Soil Science Society of America has been issued an invoice for this item yet.
- Review the curator process for checking payment plans when a submission changes journals.

**Comment by ryscher** [comment]
@LoriEP should I force creation of an invoice for this dataset?

**Comment by LoriEP** [comment]
@ryscher if it's simple yes, please do. If it's not, I can easily create an invoice in Stripe

**Comment by ryscher** [comment]
Generated invoice in_1IR3lnKX6qdZziO2foPX4ByQ
