### ISSUE TITLE
Please associate Tim Pusack's ORCID (0000-0003-2724-6329) with new email address

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1140]
**Request:** Please merge account for 0000-0003-2724-6329 

Previous emails: 
1.  tjpusack@mail.usf.edu 
2. pusackt@science.oregonstate.edu 
3. tpusack@mail.colgate.edu 
4. tpusack@gmail.com

Current email: tjp3@williams.edu

**Comment by sfisher** [comment]
Ok.  There were three accounts for him.  Now merged to 1.
