### ISSUE TITLE
Dataset numbers for reporting and projections

### ISSUE THREAD

**Issue by tracykteal** [CDL-Dryad/dryad-product-roadmap#1141]
I pull numbers from admin csv, but those are snapshots in time, and I'd like a bit more resolution, and to be able to compare current with historical, when I don't have access to the csv data. I also get some of this from the shopping cart data, but just putting it all together here for one picture.

Overall, I'd like to see how many datasets are new submissions or new private for peer review each day, how many we're processing per day, and how much is coming back to us after Action Action Required. Thank you!

For the date range January 1, 2020 to the current day:

Could I please get in a csv:
- The date, and then for each date:
- The number of new submissions that day (so the first time we see them as 'submitted' in the system)
- The number of new PPR that day (so the first time we see them as 'peer_review' in the system)
- The number processed that day (meaning the status changed from 'curation' to 'action_required', 'embargoed' or 'published')
- The number AAR'd that day (status change from 'curation' to 'action_required')
- The number published by a curator that day (status change from 'curation' to 'published' by a curator and not the system)
- The number embargoed that day (status change from 'curation' to 'embargoed' per day) 
- The number that come back to us after an Author Action Required that day (so they change status from 'action_required' to 'curation')
- The number resubmitted that day (were 'published' or 'embargoed' before, and change status to 'submitted')

I know there's lots of different ways things are tracked in the system, so this might not be the right representation or descriptive enough, so please do reach out to discuss if helpful or needed. 

Ideally there could be a script that exists from this, so we can run it and pull these numbers regularly. 

Thank you!

**Comment by ryscher** [comment]
Once this report is built, it should be runnable through the UI, e.g., with a simple menu option or button.
