### ISSUE TITLE
Report: number of new submissions (either to submitted or private for peer review) from 2/2/2021 - 3/2/2021.

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1143]
For Dryad Zenodo webinar would like to point to percentage of submissions that used Zenodo feature so it would be great to have the numbers on how many new submissions we got in 4 weeks, and then separately the number of packages that have a Zenodo submission (any status). Last week Scott pulled that second part for me and it was 87. I can see how many are published at Zenodo.

**Comment by ryscher** [comment]
Submissions during this time = 872
Submissions with Zenodo content = 86
Total datasets with Zenodo content (including in_progress) = 111
