### ISSUE TITLE
Getting error every time 'Cancel and discard changes' is clicked

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1145]
**Bug description:**
If a curator edits a dataset and they decide to cancel and discard changes, they receive an error that "Something went wrong."

**Steps to reproduce:**
Navigate to any dataset
click to edit
click to cancel and discard changes
Navigate back to the dataset, you will see that the dataset is 'in progress'

**Expected behavior:**
When a superuser clicks 'Cancel and discard changes' they should be directed back to the dashboard with no error and the last status of the dataset should be the same

Datasets where this occurred:
10.5061/dryad.7rh4625

**Comment by ryscher** [comment]
This was a side effect of rolling out the migration part of the S3 changes without the full feature set. A fix has been deployed.
