### ISSUE TITLE
Investigate datasets were published in v1 that contain manuscripts and were auto-published without curation

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1149]
**Request:** 
The following datasets are currently in the curation queue as they are resubmissions but the activity log for these datasets look as if they were self-published on the day the system transitioned to v2. 

DOIs: 10.17916/P6V880 and 10.17916/P68C7C

**Note:** They've already been viewed and downloaded extensively, so not clear whether we could pull them down, but may want to investigate what happened. We will wait to take any curation action until we understand what may have happened.

**Comment by ryscher** [comment]
These items were migrated from Dash, so I don't know their history, but I believe we decided to keep them.
