### ISSUE TITLE
Merritt presigned urls still require double-encoding of the % character

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1152]
I'm seeing some examples of failures in retrieving files from Merritt (for replication to zenodo).

Examples of merritt urls:

https://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm58681zx/3/producer%2F0.01%25MD.png?no_redirect=true

https://merritt.cdlib.org/api/presign-file/ark%253A%252F13030%252Fm5770mw2/6/producer%252FMrBayes50%25majrule_all_edited.nex

The Merritt UI works, but it is incorrectly double-encoding the % symbol to force it to work rather than following internet standards. `%25` is the correctly-encoded percent symbol (rather than `%2525` which is the double-encoded form).

plain filename: MrBayes50%majrule_all_edited.nex

correctly-encoded filename would be:  MrBayes50%25majrule_all_edited.nex

**Comment by sfisher** [comment]
This is still an issue, I believe.  We work around it.  It would be nice to follow http encoding rules, though.

**Comment by ryscher** [comment]
This may have been fixed by moving presigned URLs directly to S3, but we will need to test these again as we complete #2641, to ensure both new and old files are handled properly with the new code.

**Comment by sfisher** [comment]
The problem is fixed by moving to creation of S3 presigned URLs using the AWS libraries, which take care of encodings correctly.

See `https://datadryad.org/stash/dataset/doi:10.5061/dryad.sj3tx9617` for a dataset with % characters in the filenames.  It downloads correctly and I examined code we use for retrieval to see if there is any special handling for the character and there doesn't seem to be. 🎉 

I assume for deposit, it will be much the same.

Not about encoding, but large file deposits (maybe over 4GB?) have required splitting into separate parts in S3 in the past.  Not sure if it's still the case, but I suspect so.
