### ISSUE TITLE
Ownership change for UC Davis ICE SWAP dataset submission

### ISSUE THREAD

**Issue by elopatin-uc3** [CDL-Dryad/dryad-product-roadmap#1158]
#### Summary
The Merritt team will be submitting a dataset that encompasses all objects in the current Merritt UC Davis ICE: Source Water Assessment Program collection. The submission will not be done by the actual corresponding author, as she is retired and does not have an ORCID. Once it is completed, we will need to change the ownership of the dataset from @elopatin's ORCID to a new account created for the corresponding author, Leah Walker. A contributing author, James Quinn, will be added during the initial submission process.

#### Tasks
- [ ] @elopatin-uc3: Submit dataset
- [ ] @sfisher: Change dataset ownership from submitter to Leah Walker

**Comment by sfisher** [comment]
I believe this was done.  I seem to remember doing something like this where Erik submitted and then we changed authorship.

**Comment by elopatin-uc3** [comment]
@sfisher Yes, from what I recall I submitted the dataset, but then you changed the DOI so it was appropriate for Davis and changed the author as well.
