### ISSUE TITLE
Journal Name in Internal Data does not match Journal Name in Dryad web form (editing mode)

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1159]
**Bug description:**
For dataset doi: 10.5061/dryad.83bk3j9nf the Journal Name in the internal data is Ecosphere, but in the metadata within the Dataset submission web form, the journal is Ecological Applications.  Unsure if related to #1146 

**Steps to reproduce:**
Navigate to 10.5061/dryad.83bk3j9nf, 
review Activity Log Internal Data,
see Ecosphere listed as PublicationName
MS # 20-0205
Then click to edit dataset, 
see Journal Name is Ecological Applications

**Expected behavior:**
Internal Data for PublicationName should match the Journal Name in the application web form

**Note:** The manuscript numbers match in both fields as expected

**Comment by ryscher** [comment]
This is a problem similar to #736. If a user enters a known journal (with an ISSN in our system), the cannot later change to an unknown journal. 

- Which journal is correct for this dataset?
- Should we create a ticket parallel to #736, for changing from known to unknown journals?

**Comment by LoriEP** [comment]
Thanks @ryscher I would say users should be able to change the journal name to one with an ISSN not in our system. I think this is rare, but this does happen.

**Comment by ryscher** [comment]
I have created a PR to fix this problem in general -- users will be able to change from a "known" journal to an "unknown" journal.

For the dataset listed above, I removed the stored ISSN which was causing the problem. Both locations now list the journal as Ecosphere.
