### ISSUE TITLE
Migration script for file tables

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1169]
Most of our files are in stash_engine_file_uploads, so I think it may be best for the script to do these steps.

- [x] create query to INSERT INTO . . . SELECT for the new table to copy items from stash_engine_file_uploads (up to a certain id number).  It should put the correct table information into the 'type' column.
- [x] create query to INSERT INTO . . . SELECT for the new table from stash_engine_software_uploads (up to a certain id number).  It should put the correct table information into the 'type' column.
- [x] In Dev
  - [x] Run query for most files
  - [x] after we transition to new code run query again to pickup files after the previous ones (greater or equal to previous)
- [x] in Stage
  - [x] Run query for most files
  - [x] after we transition to new code run query again to pickup files after the previous ones (greater or equal to previous)
- [x] in Production 
  - [x] Run query for most files
  - [x] after we transition to new code run query again to pickup files after the previous ones (greater or equal to previous)

These are what we want to run.  I suggest running the migration up until about a month ago and then run again for the records since then while we're doing the maintenance.

```
INSERT INTO stash_engine_generic_files
  (upload_file_name, upload_content_type, upload_file_size, resource_id, upload_updated_at,
  created_at, updated_at, file_state, url, status_code, timed_out, original_url, cloud_service, digest,
  digest_type, description, original_filename, type)
      SELECT upload_file_name, upload_content_type, upload_file_size, resource_id, upload_updated_at, created_at,
           updated_at, file_state, url, status_code, timed_out, original_url, cloud_service, digest,
           digest_type, description, original_filename, "StashEngine::DataFile" as type
      FROM stash_engine_file_uploads
      WHERE created_at < "2021-03-01";
```

```
INSERT INTO stash_engine_generic_files
  (upload_file_name, upload_content_type, upload_file_size, resource_id, upload_updated_at,
  created_at, updated_at, file_state, url, status_code, timed_out, original_url, cloud_service, digest,
  digest_type, description, original_filename, type)
      SELECT upload_file_name, upload_content_type, upload_file_size, resource_id, upload_updated_at, created_at,
           updated_at, file_state, url, status_code, timed_out, original_url, cloud_service, digest,
           digest_type, description, original_filename, "StashEngine::SoftwareFile" as type
      FROM stash_engine_software_uploads
      WHERE created_at < "2021-03-01";
```

**Comment by sfisher** [comment]
I migrated old data to dev < "2021-03-01" for testing so far.

**Comment by ryscher** [comment]
These queries look fine to me.
