### ISSUE TITLE
Metadata associated with Papers in Palaeontology (PALA) not importing 

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1175]
**Bug description:**
Import metadata not working for PALA associated metadata. Other journals seem to be working, RSPB 'RSPB-2021-0181' used for comparison test. We received email from PALA editorial office that user has been having issues importing.

**Steps to reproduce:**
Navigate to new dataset, input Papers in Palaeontology in Journal Name field and the following ms number 'PALA-06-20-4807-OA' in the Manuscript Number field 
Click 'Import Metadata'
Receive error "We could not find metadata to import for this manuscript. Please enter your metadata below."

**Expected behavior:**
When an acceptance notice has been received and a user fills in the Journal Name and Manuscript Number field with valid metadata, the metadata from the acceptance notice should populate in the Title, Author, Keywords and Abstract fields.

**NOTE: Other tested PALA manuscript numbers: PALA-01-21-4991-OA, PALA-11-20-4944-OA**
**NOTE: This may be happening with other journals, but we have not received any additional reports**

**Comment by ryscher** [comment]
The ISSN used by v2 Dryad (the online ISSN) was not present in the v1 server. This resulted in the v1 server creating a new entry for the journal, which did not have any of the journal's settings. I corrected the issue and re-processed all of the journal's emails for the last 4 months. The sample manuscript number above now imports correctly.
