### ISSUE TITLE
Eliminate empty/blank subjects from DataCite metadata

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1185]
Doesn't happen often but we occasionally get blank subjects which causes the datacite schema to fail and submissions to fail.

If a subject is blank, just do not add it to the datacite metadata (or remove it).

**Comment by sfisher** [comment]
THis still happens occasionally and it's usually me who corrects and resubmits. :-)

**Comment by ryscher** [comment]
related to #2403, so should be done together
