### ISSUE TITLE
Throttle excessive traffic to Dryad UI and API

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#119]
Ryan was able to kill the API by sending requests as fast as possible for submissions.

We need to throttle, maybe through AWS Application Firewall options.  Or we may need to track and throttle ourselves.

Robots and automated agents should also be respectful and delay many requests such as 1 second.  We can add delay settings in robots.txt and encourage people to observe limits.

**Comment by sfisher** [comment]
@jimvanderveen does AWS have some good tools we can use for throttling?

**Comment by jimvanderveen** [comment]
Yes, Debra has recommended Web Application Firewall for this purpose @sfisher

**Comment by ryscher** [comment]
We did this with RackAttack, though Ashley may want to add WAF at some point.
