### ISSUE TITLE
Add new "DOI" field to "My Datasets" user dashboard

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1200]
**Problem description, and links to relevant helpdesk tickets:**
We often encounter duplicate submissions when the author creates multiple datasets with the same title and cannot differentiate between them when deciding which to retain and which to withdraw. 

**Describe the solution you'd like:**
In “My Datasets”, add a field for dataset DOI next to dataset title or elsewhere to ensure submitters can differentiate between their submitted datasets. 

**Additional context:**
Advising submitters on this issue and offering instructions to update status or edit submission is confusing to them because they don’t know which dataset to select.

**Comment by ryscher** [comment]
@jleighherzog Is this still relevant? Or has it been fixed by other changes?

**Comment by jleighherzog** [comment]
@ryscher : The author dashboard should be reviewed and improved. I think it would be useful to include this suggestion in the optimization spreadsheet. I'll do that. So, I would recommend closing this ticket.
