### ISSUE TITLE
Please associate Pauline Kamath's ORCID (0000-0002-6458-4514) with new email address 

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1206]
**Bug description:**
Please ensure this user's ORCID ID is linked to current email address: pauline.kamath@maine.edu
(Former email address: pkamath@usgs.gov)

**Comment by ryscher** [comment]
Updated email address in user account, verified that the current email address is present in the existing author listings.
