### ISSUE TITLE
Please embargo this dataset: 10.5061/dryad.bk3j9kdbp

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1207]
**Bug description:**
The status of this submission was incorrectly updated from "Private for Peer Review" and, therefore, the submission proceeded to curation and publication. The journal office notified us that the article is still under review and the data should not be available. 

Title: _Data from: Ontogenetic trajectories of septal spacing and shell shape in the Late Cretaceous gaudryceratid ammonoids: implications for their post-embryonic palaeoecology_
DOI: 10.5061/dryad.bk3j9kdbp

**Comment by ryscher** [comment]
There is now a 1-year embargo on this dataset both at Dryad and Zenodo.
