### ISSUE TITLE
Unable to download datasets

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1208]
**Bug description:**

Unable to download data for these two submissions:

Title: Data from: An International, Multi-Stakeholder Survey about Metadata Awareness, Knowledge, and Use in Scholarly Communications
DOI: 10.5061/dryad.4f4qrfj8s

Title: UCI Libraries' Chatbot Files (ANTswers)
DOI: 10.7280/D1P075

**Steps to reproduce:**
When "Download Dataset" is selected AND/OR when attempting to select individual files for download, both options fail to initiate download

Similar to the issue submitted previously, see ticket #1204 

**Expected behavior:**
When "Download Dataset" is selected, the files automatically begin to download

**Comment by sfisher** [comment]
This is related to https://github.com/CDLUC3/mrt-doc/issues/644 .

**Comment by elopatin-uc3** [comment]
We will be discussing 644 at our 11am team meeting today.

**Comment by sfisher** [comment]
These two should be fixed so downloads work and users can access them correctly.
