### ISSUE TITLE
UI changes to PubUpdater

### ISSUE THREAD

**Issue by tracykteal** [CDL-Dryad/dryad-product-roadmap#1210]
Title link should redirect user to the admin dashboard
- Current function: When you click on the Title, the link redirects the user to the dataset landing page. 
- Proposed functionality: When you click on the Title, the link will redirect the user to the Admin dashboard with the dataset selected (much like current functionality of redirect post submit during editing/curation)

Create an “Add DOI” button that will automatically add the Article DOI as a related work 
- Current function: Accept Changes will accept any changes that are in the article metadata that differ from what is in the dataset metadata
- Proposed functionality: 
       - Add button that will say ‘Add DOI’ 
       - Remove ‘Accept Changes’ button 
       - When the ‘Add DOI’ button is clicked, the DOI from the article will be added as a Related Work, with type “Article” in the dataset metadata. No other metadata should be added.
       - Curators should not need to Publish again 
       - Nice to Have: If there is an active embargo, clicking “Add DOI” will lift the embargo and move the dataset to Published

Add a “Dismiss button” and remove the “Reject” button 
- Current functionality: Reject button rejects datasets and articles that are not matches 
- Proposed functionality: Add a ‘Dismiss’ button 
       - Remove the ‘Reject’ button

**Comment by ryscher** [comment]
Closing in favor of #2259
