### ISSUE TITLE
Switch owner of datasets (internal Merritt transfer)

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1211]
John (on behalf of Merritt team) uploaded datasets to Dryad that were previously in Merritt collection. Scott, can you please change the owner of the datasets below to 
Karen Holl
kholl@ucsc.edu
https://orcid.org/0000-0003-2893-6161

The DOI being UCOP and not UCSC is fine those do not need to change. Just need to ensure Karen Holl is the author (she has logged into Dryad).

Let me know if you need other info.

Datasets:
    https://doi.org/10.18737/D7CC8B
    https://doi.org/10.18737/D77K51
    https://doi.org/10.18737/D73W34
    https://doi.org/10.18737/D70304
    https://doi.org/10.18737/D7VC8P
    https://doi.org/10.18737/D7QK5C
    https://doi.org/10.18737/D7KW3G
    https://doi.org/10.18737/D7G30G
    https://doi.org/10.18737/D7BC81
    https://doi.org/10.18737/D76K63
    https://doi.org/10.18737/D72W2F
    https://doi.org/10.18737/D79C7B
    https://doi.org/10.18737/D7Z316
    https://doi.org/10.18737/D75P5F
    https://doi.org/10.18737/D7TC70
    https://doi.org/10.18737/D7PK6F
    https://doi.org/10.18737/D7JW2S
    https://doi.org/10.18737/D71W24
    https://doi.org/10.18737/D7F606

**Comment by sfisher** [comment]
This should be done.  I changed both the owner and current editor to Karen.  From the status ("in progress"), it looks like these have been uploaded but not submitted to Merritt yet (also no submission logs).  Seems like Karen will then need to go in and submit each of them.  IDK if that is what is intended or not.
