### ISSUE TITLE
Submissions stuck "Processing" after attempting rebuild

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1213]
**Bug description**
The following submissions are stuck after attempting to edit data submissions:
10.5061/dryad.9w0vt4bf1
10.5061/dryad.tht76hdww
10.5068/D1F686 
10.5061/dryad.37pvmcvk6
10.5061/dryad.brv15dv92
10.5068/D1F686
10.5061/dryad.n2z34tmwf

**Expected behavior**
After selecting the option to 'Review & Submit', the submission should return to an actionable status.

**Comment by tracykteal** [comment]
It looks like all datasets that we've been trying to edit are getting stuck in status "Processing", so seems to be affecting all datasets and all curators.

**Comment by ryscher** [comment]
Submissions are now processing.
