### ISSUE TITLE
No result found when searching for submission (DOI: 10.5061/dryad.bg79cnpb4)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1214]
**Bug description:**
When I search for this submission using title or DOI, no search results appear. I had deleted the duplicate journal name from the Internal Data section (the only edit I made). The submission was previously "In Progress". 

Title: Source data for all figures
DOI: 10.5061/dryad.bg79cnpb4

**Comment by sfisher** [comment]
This appears for me when I search for the DOI .  Is there still a problem this one?

https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=10.5061%2Fdryad.bg79cnpb4&sort=relevance&all_advanced=1&commit=Search

It will not appear in the public search results until it is published.  I'm not sure which search you're referring to?

**Comment by jleighherzog** [comment]
It seems this is working properly. Please close this issue! Thanks.
