### ISSUE TITLE
Identical submissions created

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1219]
**Bug description:**
Recently, identical submissions will appear in our queue. These submissions are not duplicated by the author, they seem to be replicated by the system (maintaining the same DOI and metadata). 

To correct this issue, we 
1) Select the clock icon from the 'last modified' column of either submission 
2) Select the delete icon from the 'type' column for the journal name ('value' column) that has an asterisk (*) next to it. This resolves the issue leaving only a single submission. 

<img width="1181" alt="Screen Shot 2021-04-19 at 7 47 56 PM" src="https://user-images.githubusercontent.com/76497320/115437627-05f3cd00-a1d2-11eb-8675-53719e9af690.png">
<img width="1189" alt="Screen Shot 2021-04-19 at 7 48 08 PM" src="https://user-images.githubusercontent.com/76497320/115437640-08eebd80-a1d2-11eb-92b5-d30e11d77cee.png">

**Steps to reproduce:**
Here is a current/live example that has not been corrected: 
DOI: 10.5061/dryad.rjdfn2zbb
Status: Submitted

**Expected behavior: **
No identical submissions should exist.

**Comment by ryscher** [comment]
We have put some protections in place to guard against this.
