### ISSUE TITLE
Please associate Yong Zhou's ORCID (0000-0003-2546-8462) with current email address

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1221]
**Bug description:**
Please link Yong Zhou's ORCID account with the current email address provided. 

Current email: yong.zhou@yale.edu
Previous email: zhouyong1222@tamu.edu

**Comment by sfisher** [comment]
Hi.   I found their current login, but don't see that previous email address.  It looks like some other people with that name registered with email addresses at sina.com and someone else at gmail.

The gmail user has a dataset called "Soil carbon response to woody plant encroachment: Importance of spatial heterogeneity and deep soil storage."  Is that the same user and the same one?  I don't think the sina.com person has any datasets.

**Comment by jleighherzog** [comment]
The author has confirmed that this Gmail account is owned by them: yongzhou1222@gmail.com
And, the article you referenced was also submitted by them (DOI: https://doi.org/10.5061/dryad.ns92q)

**Comment by sfisher** [comment]
Ok.  These accounts are all merged.

**Comment by jleighherzog** [comment]
Thanks! We're good now.
