### ISSUE TITLE
Files from previous version erroneously appearing in new version uploaded (DOI: 10.25338/B8FH0P)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1228]
**Bug description:**

Title: _Data for: Social behavior, ovary size, and population of origin influence cuticular hydrocarbons in the orchid bee, Euglossa dilemma_
DOI: 10.25338/B8FH0P 

For this submission, three files from a previous version (listed below) are included in the most recent version when "Download Dataset" is selected. These three files don't appear in editing mode and they don't appear in the list of files included in the most recent version uploaded: 

- “Ovary_Gene_Expression_CHCs.csv”
- “Brain_Gene_Expression_CHCs.csv”
- “Euglossa_CHCs_R” 

**Steps to reproduce:**
Select "Download dataset"

**Expected behavior:**
Only the files listed in the most recent/current version should download when "Download Dataset" is selected. Files from previous versions that were not included in the most recent upload should not appear. 

_Note: Might be a similar issue to #1220_

**Comment by jleighherzog** [comment]
Hello, any update on the status of this request? Thanks!

**Comment by sfisher** [comment]
I believe it is all fixed, but checking in with the Merritt Repository team to reconfirm since this was something they worked to correct and come from their repository for the full version download.

Will confirm with their response when I hear back.

**Comment by sfisher** [comment]
The Merritt team says this is all fixed.  Let me know if you see any other problems like these with extra file in the full version download.
