### ISSUE TITLE
Handle content from Merritt's DataONE MN

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#1234]
See also: https://github.com/CDLUC3/mrt-doc/issues/437

For doi:10.25338/B8CH02, if possible, provide the schema.org/isBasedOn entry in the schema.org metadata being provided by Dryad

Sunsetting of the Merritt MN resulted in depositing the 16,804 objects into a single dataset into Dryad.  To ensure these datasets can still be discoverable via DataONE CN, adding the property schema.org/isBasedOn to the schema.org will support this.  

Completing the deprecation of the Merritt MN while retaining existing content and cross referencing the existing with the new aggregate involves:

- [ ] check with DaveV on the timeline for the schema.org harvesting from DataONE.

**Comment by elopatin-uc3** [comment]
@ryscher Let me know if you need any additional information regarding original Merritt ARKs for the datasets in this DOI.

**Comment by ryscher** [comment]
@elopatin-uc3 How do you suggest we wrap this up? Is there a specific value that Dryad should apply to this dataset's `schema.org/isBasedOn`? Or do we need to have a discussion about it? I see that https://github.com/CDLUC3/mrt-doc/issues/437 is still open.

**Comment by ryscher** [comment]
Closing this, as it appears that any remaining work will be performed by DataONE.
