### ISSUE TITLE
Dryad MN - updates to schema.org

### ISSUE THREAD

**Issue by marisastrong** [CDL-Dryad/dryad-product-roadmap#1237]
Sunsetting of the Merritt MN resulted in depositing the 16,804 objects into a single dataset into Dryad.  To ensure these datasets can still be discoverable via DataONE CN, adding the property schema.org/isBasedOn to the schema.org will support this.  More info and background is found in this ticket.
https://github.com/CDLUC3/mrt-doc/issues/437

**Describe the solution you'd like:**
Completing the deprecation of the Merritt MN while retaining existing content and cross referencing the existing with the new aggregate involves:

If possible, provide the schema.org/isBasedOn entry in the schema.org metadata being provided by Dryad
**Additional context:**
https://github.com/CDLUC3/mrt-doc/issues/437

- [ ] check with DaveV on the timeline for the schema.org harvesting from DataONE.

**Comment by elopatin-uc3** [comment]
Noting #1234

**Comment by sfisher** [comment]
This seems like primarily a Merritt issue? We've since migrated all Dryad content into one collection in Merritt.  I believe this can be closed, but if not, let me know and I'll re-open.
