### ISSUE TITLE
Planning for increased usage with journal integrations

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1238]
- what metrics should we measure to ensure service remains good?
- where are resources likely to be constrained?

**Comment by ryscher** [comment]
The way the journals are using the system, it should look very similar to normal submissions through the web UI. I don't expect Dryad to have issues until usage drastically increases. 

To track usage during the rollout of new journals, I made a simple list of stats to check and will regularly put them in a spreadsheet.
