### ISSUE TITLE
Rake tasks run slowly on production

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#1240]
On the Dryad production servers, rake tasks typically take 60 seconds or more before they actually start running. Although there is a delay on other servers, it is nowhere near this long.

Sample commands to reproduce:
```
cd /apps/dryad/apps/ui/current
bundle exec rake journal_email:validate_gmail_connection
```
Time to execute the above commands:
- on dryad-stg-a, 5.8 seconds
- on dryad-prd-c, 1 minute 43 seconds

**Comment by ryscher** [comment]
Scott reported that rake tasks were running quickly for him. After a little more testing, the behavior I see is dependent on the RAILS_ENV environment variable. If it is set correctly to `production`, the scripts run at normal speed. If it is set (incorrectly) to `development`, or if it is not set at all, the scripts run slowly.

So, I guess this is low priority, because it works correctly when everything is set correctly. But I'm still wondering why the behavior is different on the production server....

**Comment by sfisher** [comment]
Yes, I set mine to `RAILS_ENV=production bundle exec . . .` when I ran it when it was fast.
