### ISSUE TITLE
Prevent page navigation during uploads

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#1254]
While a file is uploading, it is possible to click the button to go to the Review page of the submission system, which will effectively cancel the upload. It would be nice if the navigation buttons were disabled while an upload is in progress.

**Comment by sfisher** [comment]
This is implemented a little differently, but stops navigation and issues a warning when trying to navigate off page if any of the items in the table are "pending" or still have an upload progressbar showing.
