### ISSUE TITLE
Make two admins 'admins' for Macquarie University

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1257]
Shawn Ross <shawn.ross@mq.edu.au>

Gerry Devine <gerry.devine@mq.edu.au>

**Comment by sfisher** [comment]
OK.  They're both admins now.  I switched Gerry to be at the Macquerie tenant since he was under the Dryad tenant probably from a login before or something (verified in his orcid profile that it lists he is at Macquerie, so pretty sure it's the same person.)
