### ISSUE TITLE
Investigate related works: absent and duplicates

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1260]
In one case the related works will not appear for Zenodo and in another there are duplicates showing for SI and software. This only happened when all three types of things are submitted.

**Comment by sfisher** [comment]
I thought I put this in the comments for this one, but maybe not.

https://dryad-stg.cdlib.org/stash/dataset/doi:10.7959/dryad.dbrv15dwn  is the one that didn't have the links to zenodo showing.

The one with double links is unknown.  I'll see if I can find it.
