### ISSUE TITLE
Remove version 1 from published dataset (DOI: 10.5061/dryad.kd51c5b5c)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1271]
Please remove version 1 of this dataset which was published on April 12, 2021: 

Title: Exceptional multifunctionality in the feeding apparatus of a mid-Cambrian radiodont
DOI: 10.5061/dryad.kd51c5b5c

The only dataset that should remain will be the most recent version (V2) published on April 29, 2021. 

If you have any questions, please let me know.

**Comment by ryscher** [comment]
The April 12 version is now hidden.
