### ISSUE TITLE
Remove dataset from site (DOI: 10.5061/dryad.hdr7sqvj2)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1286]
Please remove the publication record (all uploaded data and metadata) for the submission below:  

Title: _Cross-sectional comparisons of sodium content in processed meat and fish products among five countries - potential for feasible targets and reformulation_
DOI: 10.5061/dryad.hdr7sqvj2

Reason: Dataset was submitted without co-author knowledge or approval.

**Comment by sfisher** [comment]
This is now removed from public view and set to withdrawn.   I asked Zenodo to remove their copy of the data, also.

If we need to nuke it completely out of our database and the storage repository, let me know.  I think Ryan didn't think it was necessary.

Thanks,

          Scott
