### ISSUE TITLE
Reports on last few years of dataset curation and publication activities

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1295]
shopping cart report since we went live in new system by month

**Comment by ryscher** [comment]
- Shopping cart reports for current system
	https://github.com/datadryad/journal-payments/tree/main/shoppingcart
  - Historical shopping cart reports (slightly different format)
	https://drive.google.com/drive/u/1/folders/0BzWuiqo-UGbqTUFlck1PamMxcDg
