### ISSUE TITLE
Review handling for large files

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#1310]
We were hoping to use the FTP server less, since we improved uploading capabilities through the submission UI. But this appears not to be the case. Curators still use the FTP server several times per week.

Is it still the best solution, or could we do something better?

Sample cases that used the FTP server recently:
- SF 00004860
- SF 00004619

**Comment by sfisher** [comment]
I thought this was resolved?  Marking as `wontfix` until I hear differently.

**Comment by ryscher** [comment]
Definitely resolved.
