### ISSUE TITLE
Review Rubygems

### ISSUE THREAD

**Issue by marisastrong** [CDL-Dryad/dryad-product-roadmap#1312]
There are some rubygems used in Dryad which are owned by dmolesUC - https://rubygems.org/profiles/dmolesUC - should see which ones need other ownership, perhaps under the CDLUC3 account

**Comment by sfisher** [comment]
I believe this is not a problem.  Ryan and I have access to update the DataCite mapping gem (as maintainers at RubyGems and I believe can add additional maintainers).  The Merritt-related things got moved into our own codebase for our own specific changes as our relationship with Merritt has changed (SWORD, OAI, etc).

Though there are some utility classes I'm not sure are maintained by us.

**Comment by sfisher** [comment]
I think these are ok.

- ruby-enum -- don't see it used within our code
- typesafe_enum -- library used within some classes but not a CDL/Dryad specific library
- datacite-mapping -- we have power to maintain this
- xml-mapping_extensions -- library used by stash/wrapper and is a utility library
- resync-client -- doesn't seem used by Dryad
- resync -- doesn't seem used by Dryad
- stash-wrapper -- We have our own copy within the project to make easier to update and modify and specific to us
- config-factory -- Doesn't seem used
- merritt-manifest -- Added ryan as a maintainer
- stash-sword -- no longer used
