### ISSUE TITLE
Revise the SOLR startup scripts (or solr install) so it works correctly on servers

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#132]
The solr startup script isn't working on uc3-dryadsolr-dev.cdlib.org in the ~/init.d directory.

This may be because SOLR was installed a different way since David M installed them on Dash and I didn't see instructions, so installed them in the way I knew in Dryad.

In any case, we need to have solr start automatically after reboots.

**Comment by ryscher** [comment]
I believe this works properly, since it has been running on new servers for a long time.
