### ISSUE TITLE
Reports for cost model

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1337]
**Report 1: by DOI, one full report doesn't need to be separated by monthly CSVs Sept 18 until now**
- The first date that the dataset enters 'dataset to be curated'.
- How many times the dataset re-enters the 'datasets to be curated' queue
- The approval date

**Report 2: by DOI, one full report doesn't need to be separated by monthly CSVs sept 18 until now**
- DOI
- # of Files
- File Types
- Dataset size

**Comment by ryscher** [comment]
For report 2, should there be
a) one line per DOI, with all filetypes grouped together in a single field, OR
b) one line per DOI/filetype, with the DOI & size repeated for each filetype?

**Comment by dlowenberg** [comment]
Hey @ryscher could we re-run this report to include June and July?
