### ISSUE TITLE
Associate Brian Park's ORCID ID (0000-0003-2463-8503) with current email address

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1341]
Previous email address: brian.park@yale.edu
Current email address: brian.park@aya.yale.edu

**Comment by sfisher** [comment]
OK.  I updated his email address and merged 2 accounts.  It looks like he might also have a 3rd account without an email (at least we didn't get one from orcid) with ORCID 0000-0003-0989-009X at https://orcid.org/0000-0003-0989-009X .

Not sure if that is him or needs to be merged with his other accounts, too.
