### ISSUE TITLE
Edit to author line removes co-author ORCID IDs (DOI: 10.5061/dryad.6wwpzgmzx)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1347]
**Bug description:**
When attempting to remove multiple entries for author **Peter Hegemann** (listed in triplicate), ORCID IDs provided for other co-authors are also removed. 

Title: The inner mechanics of Rhodopsin Guanylyl Cyclase during cGMP-formation revealed by real-time FTIR spectroscopy
DOI: 10.5061/dryad.6wwpzgmzx

<img width="867" alt="Screen Shot 2021-06-29 at 3 55 15 PM" src="https://user-images.githubusercontent.com/76497320/123866892-428b2580-d8f3-11eb-953b-7e08e3b7b531.png">

**Steps to reproduce:**
See view of metadata in editing mode before removing author: 
<img width="1270" alt="Screen Shot 2021-06-29 at 4 03 10 PM" src="https://user-images.githubusercontent.com/76497320/123867157-9e55ae80-d8f3-11eb-975b-3e0242bb05ae.png">

And, view after editing metadate to remove author: 
<img width="1243" alt="Screen Shot 2021-06-29 at 4 03 23 PM" src="https://user-images.githubusercontent.com/76497320/123867167-a281cc00-d8f3-11eb-8ba2-e027e7b24dcf.png">

**Expected behavior:**
Curator should be able to remove author without impacting other author entries. 
_Note: Dataset was submitted post eLife API integration._

**Comment by ryscher** [comment]
@jleighherzog It looks like this is a problem with the display only, not with the content stored in our database. Please leave this ticket for us, but you can finish curating the item whenever you are ready. After deleting the duplicate authors, you can see the ORCIDs again by navigating to the "Upload Files" page, and then back to "Describe Dataset".

**Comment by ryscher** [comment]
We have replaced the system for editing authors, so this problem should no longer occur.
