### ISSUE TITLE
Prevent public access to "Unpublished" datasets

### ISSUE THREAD

**Issue by daisieh** [CDL-Dryad/dryad-product-roadmap#135]
We need to make sure that publicly-available servers don't immediately send all migrated datasets into Published, public mode. Curators will need to be able to manipulate datasets that are not yet published, and we don't want anyone to accidentally find that data. All datasets that users submit currently get the curation status "Unsubmitted." This means that nothing will be "Published" unless we manually add that status.

- [x] UI does not show non-"Published" datasets for non-superusers.
- [x] stash-wrapper has to include the current curation status of a dataset
- [x] Merritt harvester has to include that data
- [x] All public search interfaces have to include the "published" curation status facet for non-superusers.

**Comment by ryscher** [comment]
See notes about Dryad Workflow in the Google Doc "Prod Dev Notes" from  August 16,2018.

**Comment by ryscher** [comment]
Done as part of v2 deployment
