### ISSUE TITLE
Large datasets: downloading, reviewing, and storing

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1365]
Curators are seeing an increase in the number of large datasets submitted to Dryad (i.e. ~20GB and larger). As a result, the time and effort spent downloading and reviewing large datasets is dramatically increasing along with turnaround times. For some datasets, 12-18 consecutive hours are needed for download. If decompression is needed, it can require an additional 12-18 consecutive hours to accomplish. If downloads fail or decompression is interrupted, this process must restart, which means, it can take 2-3 days before datasets are ready to enter the curation process. Processing these datasets often cause our computers to become unresponsive while using all resources to download and we are left unable to use our machines for other work or personal use. 

Additionally, more recently, we've noted an increase in initial inquiries/requests from authors who would like to store large amounts of data (>300GB+), which will inevitably require more than one dataset submission (and DOI). Currently, it can be very clunky for these authors/users because there is no easy and clear way to link these datasets which can cause confusion for the authors who are uploading the data, editing metadata, linking the data, etc. The Related Works section is an option we use to link datasets and articles but it's not ideal for datasets that may require 40 separate submissions. 

Please consider these challenges and investigate solutions to address them! If you have any questions, please ask.

**Comment by ryscher** [comment]
Closing in favor of #2411
