### ISSUE TITLE
Remove previous version approved for publication DOI: 10.5061/dryad.t4b8gtj1s

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1370]
This submission was approved for publication and is currently in "Embargoed" status. 

Title: No evidence for female kin association, indications for extragroup paternity, and sex‐biased dispersal patterns in wild western gorillas
DOI: 10.5061/dryad.t4b8gtj1s

The version that was approved for publication contains coordinates for an endangered species. The author resubmitted a new version on July 12, 2021 (without coordinates). Both versions have yet to be "Published". 

1) Please remove the data file published on April 7, 2021
2) Only the files from July 12, 2021, should remain uploaded
3) The status should return to "Embargoed"

Please let me know if you have any questions.

**Comment by jleighherzog** [comment]
This is the updated file: 
[Genotypes_Gorillas_Dryad2.txt](https://github.com/CDL-Dryad/dryad-product-roadmap/files/6808944/Genotypes_Gorillas_Dryad2.txt)

**Comment by sfisher** [comment]
Ok.  This is fixed.   Take a look to be sure it looks correct.  https://datadryad.org/stash/dataset/doi:10.5061/dryad.t4b8gtj1s

There is also the sharing link in there which I checked and has the correct file, I think.

**Comment by jleighherzog** [comment]
Yes, I've confirmed that both the shared link and the uploaded dataset contain the correct file. Thanks!
