### ISSUE TITLE
Submission stuck in "Merritt Error" (DOI: 10.5061/dryad.0p2ngf1x0)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1371]
Please work your magic to remove the current error status for this submission: 

Title: Molecular assays of pollen use consistently reflect pollinator visitation patterns in a system of flowering plants
DOI: 10.5061/dryad.0p2ngf1x0

The submission should return to "Curation" status.

**Comment by sfisher** [comment]
Ok.  Fixed.
