### ISSUE TITLE
Dataset published in error DOI: 10.5061/dryad.x3ffbg7h4

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1377]
Dataset was published in error. Curator selected the incorrect status from the drop-down menu. 
Please return to 'Author Action Required' status

Title: 10-year comparative follow up of familial versus multifactorial chylomicronemia syndromes
DOI: 10.5061/dryad.x3ffbg7h4

**Comment by sfisher** [comment]
OK.  I've reset this back to author action required and made it so it shows as unpublished in our UI.
