### ISSUE TITLE
Check settings for PPR on all journals

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1385]
Ryan -- in stage if I put in "Diversity and Distributions" as the journal I am not offered PPR as an option. I thought we removed this ever fluctuating and PPR is always available? Need to ensure that journals all have this option in production.

**Comment by ryscher** [comment]
Yes, all journals were set correctly on production. I updated the settings on dev and stage. All journals now allow PPR on all systems.
