### ISSUE TITLE
Investigate Web Application Firewall rules

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1386]
IAS is looking at doing any blocking of malicious or bad actors on our web site using Web Application Firewall.

We haven't had problems with people causing us stability issues in a long time, but we did have some incidents in the past with downloads when we weren't doing them through S3.

It isn't something that needs to happen right away, but would be good to know our options and have something set up in case we encounter problems again (like on Christmas Eve Eve a couple years ago).

**Comment by ryscher** [comment]
We finished this without realizing there was a ticket.
