### ISSUE TITLE
Delete account for Zack Jackson (0000-0002-4633-8125)

### ISSUE THREAD

**Issue by hschubloom** [CDL-Dryad/dryad-product-roadmap#1389]
The user Zack Jackson has requested that their profile be removed from the Dryad system due to privacy concerns. Their email address is zj179316@ohio.edu and their ORCID ID is 0000-0002-4633-8125.

Please let me know if you need additional info to process this request.

**Comment by sfisher** [comment]
OK.  His accounts are gone and were not associated with any datasets.

We don't store much information (like name, email and orcid).  Probably ORCID knows much more about him than we do.  ;-)
