### ISSUE TITLE
Text changes for frictionless

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1401]
Text Changes
- On the report, remove second sentence "Although you are not obligated.." and change to "Please resolve the following formatting issues and re-upload the file: "
On the Upload page (error box) and copied on the Report
- Point 1: Remove "Click View n issues" and replace with "Click the error report in the 'Tabular Data Check' column"
- Point 2: Replace "Remove the file from the list with the Remove action." with "Click Remove in the Action column to delete the file."

**Comment by dlowenberg** [comment]
Hey @sfisher just tested through do you think you could also fix the first bullet point which is on the report making that wording change? Thank you!
