### ISSUE TITLE
Allow Dryad curators to select an empty entry in "Curator" column to unassign submission

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1404]
Curators have the option to claim and assign themselves to a dataset via the drop-down menu in the 'Curator' column on the Dryad Admin site. Currently, if a curator needs to unassign themselves, their only option is to reassign to another curator. In some instances, having the option to include an empty entry in the drop-down list to indicate no assignment would be useful. 

The need to unassign is mostly beneficial at the early stages of the submission history. For example: 1) when the system has auto-assigned one of the Helpdesk leads who edited the submission prior to it hitting the curation queue and/or 2) when a curator is unable to curate the submission and would like to place the dataset back in the queue (unassigned) for pick up by a colleague. 

With unassignment to an empty entry, is it possible to retain the history of that action (so that we can see it happened) or will it need to be removed entirely to avoid any backend auto-assignment processes? 

It will be necessary that the submission returns to a "Submitted" status from "Curation" if/when unassigned. If not, the option to select an empty entry will be problematic.

If there are any questions or concerns, please let me know. Attached is a screen capture of the column and drop-down menu:

<img width="624" alt="Screen Shot 2021-07-30 at 10 49 32 AM" src="https://user-images.githubusercontent.com/76497320/127687681-016cc4c2-6f56-41bb-9a7f-243dc8af451d.png">

**Comment by ryscher** [comment]
Update from Jess: When unassigned, the status will need to revert back to "Submitted" automatically. If not, we risk having submissions lost or lingering in "Curation" status.
