### ISSUE TITLE
Settings for 'new' integrated journal: Journal of Biogeography (JBI)

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1408]
Ryan, a Wiley journal has written that they are beginning to send us emails. Can we make sure that Journal of Biogeography (abbreviated JBI) is in our list and with settings of **no** embargo? We should ensure we have received their emails so if you can confirm for me as well that you see an email in the inbox that would be helpful.

**Comment by ryscher** [comment]
The journal is in our database. I removed the setting for automatic embargoes. We have received and processed 61 metadata emails, from 2021-4-28 through today. I tested one of the manuscript numbers and it imported correctly.
