### ISSUE TITLE
Return published data to "Private for Peer Review" status (DOI: 10.5061/dryad.mw6m905wk)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1418]
Data submission was published on August 3, 2021 but manuscript was rejected by journal. 

Authors would like to keep their data in Dryad but make it private to "avoid self-plagiarism during article processing". They will submit their manuscript to a new journal title for consideration. 

Please make the data private and return it to "Private for Peer Review" status. 

Title: Green first-order derivative synchronous spectrofluorometric analysis of valsartan and metolazone in pharmaceutical and biological matrices
DOI: 10.5061/dryad.mw6m905wk

**Comment by ryscher** [comment]
Status updated at Dryad, Zenodo, and DataCite.
