### ISSUE TITLE
Legacy bad Zenodo links still appearing on landing page

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1423]
This feature has since been fixed but old datasets that originally had content going to Zenodo and then were removed during curation or other, continue to show the Zenodo DOI on the related works area of the landing page. 

Can we remove the links for:
10.5061/dryad.tqjq2bvxg
10.5061/dryad.z612jm69r
10.5061/dryad.9zw3r22f8
10.5061/dryad.44j0zpcdh

**Comment by sfisher** [comment]
Ok.  I cleaned these up.
