### ISSUE TITLE
10.5061/dryad.bzkh1898p stuck in 'Processing'

### ISSUE THREAD

**Issue by hschubloom** [CDL-Dryad/dryad-product-roadmap#1426]
Dataset with DOI 10.5061/dryad.bzkh1898p is stuck in 'Processing.' Please return it to status 'Curation.' Thank you!

**Comment by ryscher** [comment]
fixed

**Comment by hschubloom** [comment]
Hi @ryscher - there seems to be a weird bug here. On the dashboard, the status is 'Author Action Required' but in the activity log it is 'Submitted.' The author cannot access the dataset to edit it. How should Mariah proceed?

**Comment by ryscher** [comment]
Oops, the automatic process for detecting 'in progress' items was confused by the dueling versions in this item. I reset the status and updated the older version so this does not happen again.
