### ISSUE TITLE
Associate Henry Chung's current email with ORCID ID 0000-0001-5056-2755

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1428]
Update email address for Henry Chung
ORCID is 0000-0001-5056-2755

Email from my previous institution is: hwchung@wisc.edu. This email is no longer active. 
Associate with current email: hwchung@msu.edu

**Comment by sfisher** [comment]
I updated this email for the user (updated both user record and a couple of author records).
