### ISSUE TITLE
Migrate account for Nidia Mendoza-Díaz (ORCID ID: 0000-0003-3740-7878)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1429]
Please associate this user's ORCID ID with the current email address provided below

ORCID ID: 0000-0003-3740-7878
email: nidia.mdz0@gmail.com

**Comment by sfisher** [comment]
It looks to me like this is already done.  The user had two accounts and successfully migrated the old account on their own (or else Ryan did it, idk).

There was an old dryad account from 2019 or before with the name "Nidia Mendoza" and the email "daieilsavam3@gmail.com".  However it has not been logged into for the past 2 years and also has no ORCID associated.  So if the user created that account years ago, I don't think it has ever been used to do anything.

The ORCID and email for this user's account is already set to 0000-0003-3740-7878 and nidia.mdz0@gmail.com .

Let me know if the user is seeing a problem that we're not aware of.
