### ISSUE TITLE
Tabular data check preventing file upload (DOI 10.5061/dryad.t76hdr80z)

### ISSUE THREAD

**Issue by hschubloom** [CDL-Dryad/dryad-product-roadmap#1430]
I am attempting to upload a file on behalf of the author for DOI 10.5061/dryad.t76hdr80z. When I upload the file and the tabular data check runs, it never stops running, blocking me from proceeding to page 3 and submitting the revised dataset. The file is small, a .xlsx with one tab. When I try to proceed to page 3 I receive this message: "Your tabular files are currently being checked for formatting and consistency issues. Please wait for the checks to complete before navigating away from this page." The author experienced the same issue. 

[Phalloceros_for_dryad.xlsx](https://github.com/CDL-Dryad/dryad-product-roadmap/files/7042600/Phalloceros_for_dryad.xlsx)

**Comment by ryscher** [comment]
This issue was already being tracked -- see https://github.com/CDL-Dryad/dryad-product-roadmap/issues/1424

It will be fixed with the next deploy.
