### ISSUE TITLE
Unable to locate/confirm Dryad DOI referenced in published article

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1431]
An article published in PLOS ONE references a Dryad DOI that we are unable to find and/or confirm. 

Received a Helpdesk inquiry as to why the dataset link (http://dx.doi.org/1:0.5061/dryad.5dr62) referenced in the published PLOS ONE article (https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0183837) isn't valid and/or active. The article was published in 2017. 

It's clear that there's a typo in the link published by the journal and the DOI should read: 10.5061/dryad.5dr62. Curator has searched on the abstract of the article, all author names, the article title, and article DOI but the dataset remains unfindable. 

Are you able to locate this dataset and confirm the correct DOI?

**Comment by Ariana-Orona** [comment]
Confirmed with author, please reinstate this dataset if possible.

**Comment by ryscher** [comment]
I located the data files and initiated restore from the long-term backup. They will be available in a few days and then I can reinstantiate the dataset.

**Comment by ryscher** [comment]
This dataset is now reinstated.
