### ISSUE TITLE
Remove previous published versions of dataset DOI: 10.5061/dryad.nvx0k6dsr

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1437]
Please remove all previous versions of this dataset that were published on June 23rd and July 27th.
Keep only the version published on August 27th containing this single file: Grimmond_et_al_BMJO_Supplementary_Data_v3_Aug25_2012

Title: A before/after Intervention study to determine impact on life cycle carbon footprint of converting from single-use to reusable sharps containers in 40 United Kingdom NHS Trusts
DOI: 10.5061/dryad.nvx0k6dsr

**Comment by sfisher** [comment]
Ok.  These do not show as published versions.
