### ISSUE TITLE
New "primary article" feature

### ISSUE THREAD

**Issue by rcurty** [CDL-Dryad/dryad-product-roadmap#1447]
**Bug description:** The DOI for the associated primary manuscript is not listed as the "primary article" under related works as expected. (https://datadryad.org/stash/dataset/doi:10.25349/D9M606). 

**Steps to reproduce:** We have tried to delete other related works and redo the process multiple times with no success.

**Expected behavior: ** Have the DOI https://doi.org/10.10...8/s41467-021-25436-3 listed as the primary article for the deposit above.

**Comment by bryanmgee** [comment]
@jleighherzog I think we should prioritize this; I believe the behaviour now applies to any dataset where there is no other 'Article' beyond the one designated as 'Primary Article.' Although the system consistently shows the 'Primary article' designation on the Review and Submit page, it will not display as such on the admin preview landing page or the published landing page. It doesn't seem to matter whether the author correctly designates the primary article, a curator fixes it for them (added as a Related Work but without dataset designation change), or a curator adds the article when it was not previously included in the metadata at all. This is something that Ted Haberman had noticed as well (sharp increase in ratio of datasets with Articles only vs. those with Primary Articles). [Example](https://doi.org/10.5061/dryad.k98sf7m99) from today below:

![Screen Shot 2023-02-06 at 11 07 28 AM](https://user-images.githubusercontent.com/113212676/217063615-0fa4b787-bf31-4355-a57b-4cb2c4f33b1c.png)

![Screen Shot 2023-02-06 at 11 10 48 AM](https://user-images.githubusercontent.com/113212676/217063644-c399a199-c2fb-414b-bb5a-782e8ee2706a.png)

**Comment by jleighherzog** [comment]
@bryanmgee : Ok!
