### ISSUE TITLE
Ensure service is able to respond to ORCID downtime

### ISSUE THREAD

**Issue by marisastrong** [CDL-Dryad/dryad-product-roadmap#145]
Here are the final details for the outage.
The outage will start at 2pm UTC on December 15.
The migration is going to take longer than we first thought. The outage will be up to 8 hours.
During the outage, users of the Registry UI will be shown a page which will briefly explain the outage and when to expect the system to be back up.
There will be announcements on Twitter (@ORCID_Org) to keep everyone up to date with progress.
The Member and Public APIs will return 503 Service Unavailable during the outage.
There is a blog post about the outage.

https://orcid.org/blog/2018/11/20/orcid-registry-scheduled-outage-december-15-2018

**Comment by ryscher** [comment]
The downtime that prompted this ticket was long ago. Since then, there have not been any major outages for ORCID, so I assume this is no longer relevant.
