### ISSUE TITLE
Unable to upload or remove files on 'Upload Files' page (10.5061/dryad.931zcrjks)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1452]
**Bug description:**
On the 'Upload Files' page of the Dryad submission form, the files uploaded by the author are not successfully added (confirmed) and cannot be removed. 

**Steps to reproduce:**
Visit this page of the submission form and attempt to remove/replace the files attached. 

**Expected behavior:**
Files should successfully load and be put through the frictionless file check before proceeding to submission.

<img width="1195" alt="Screen Shot 2021-09-06 at 4 01 58 PM" src="https://user-images.githubusercontent.com/76497320/132348415-9466e65b-c9bf-4828-be6b-2b71db7b8995.png">

If possible, please remove the files present and replace with these: 
[Calibration curve of LER ((Method C).xlsx](https://github.com/CDL-Dryad/dryad-product-roadmap/files/7121640/Calibration.curve.of.LER.Method.C.xlsx)
[Calibration curve of BTX (Method C).xlsx](https://github.com/CDL-Dryad/dryad-product-roadmap/files/7121641/Calibration.curve.of.BTX.Method.C.xlsx)
[Calibration curve of BTX (Method B).xlsx](https://github.com/CDL-Dryad/dryad-product-roadmap/files/7121642/Calibration.curve.of.BTX.Method.B.xlsx)
[Calibration curve of BTX (Method A).xlsx](https://github.com/CDL-Dryad/dryad-product-roadmap/files/7121643/Calibration.curve.of.BTX.Method.A.xlsx)

**Comment by ryscher** [comment]
@jleighherzog I corrected an issue with tracking the Frictionless output for this dataset. Please test whether you can make the modifications now.

**Comment by jleighherzog** [comment]
There's one remaining file in the 'Upload Files' screen that's still spinning (unable to upload or remove): Calibration_curve_of_BTX_(Method_B).xls

**Comment by ryscher** [comment]
Ok, I have removed that file.

**Comment by jleighherzog** [comment]
Thanks. Success!
