### ISSUE TITLE
Remove dataset entirely from the Dryad site (DOI: 10.5061/dryad.jh9w0vtcc)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1454]
The author(s) are unable to submit payment for their published dataset. 
Additionally, they mention they have submitted their data to a free repository. 

Can you remove this dataset entirely from the Dryad site? 

Title: Resilience of reptiles to megafires
DOI: 10.5061/dryad.jh9w0vtcc

**Comment by sfisher** [comment]
This dataset is removed.
