### ISSUE TITLE
Unable to find submitted dataset 

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1457]
I used the Force Edit feature to attempt to load files from the author. Now, I can't find the submission when I search for it. 

Title: "Feedbacks between forest structure and an opportunistic fungal pathogen"

Are you able to retrieve it and re-instate it?

**Comment by ryscher** [comment]
I see a new instance of this dataset has been created.

**Comment by jleighherzog** [comment]
Yes! Just today. Thanks.
