### ISSUE TITLE
Unable to upload file on behalf of author (DOI: 10.5061/dryad.d51c5b046)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1465]
The author is unable to upload a file to their dataset. I'm also unable to load it. The frictionless check seems to have a spinning wheel that doesn't resolve. Can you give it a try? 

Title: Plant diversity effects on herbivory are mediated by soil biodiversity and plant chemistry
DOI: 10.5061/dryad.d51c5b046

[TBE_Metadata_Metabolome_PLFAsum_Nematodes_CWMs_func.group.csv](https://github.com/CDL-Dryad/dryad-product-roadmap/files/7178150/TBE_Metadata_Metabolome_PLFAsum_Nematodes_CWMs_func.group.csv)

**Comment by sfisher** [comment]
I've updated this file by editing and submitting a version (see at https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=10.5061%2Fdryad.d51c5b046&sort=relevance&all_advanced=1&commit=Search&utf8=%E2%9C%93 ).

I hope this helps.
