### ISSUE TITLE
Dataset stuck in status "Processing" (DOI: 10.5061/dryad.gxd2547n3)

### ISSUE THREAD

**Issue by hschubloom** [CDL-Dryad/dryad-product-roadmap#1466]
Submission "Exocytosis of the silicified cell wall of diatoms involves extensive membrane disintegration" is stuck in processing and should be returned to curation under Mariah Kenney. Mariah believes that the bug was caused by two actions being taken at the same time for this dataset.

**Comment by sfisher** [comment]
Should be fixed and editable again.
