### ISSUE TITLE
Associate Beverly Ager's ORCID ID to current email (ORCID: 0000-0001-6686-7377)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1468]
Please associate Beverly Ager's ORCID ID to current email address: 

ORCID: 0000-0001-6686-7377

Current email: bev.agler@alaska.gov
Previous email: skuas@yahoo.com

**Comment by sfisher** [comment]
I updated her account to have that email address.  I didn't see any other old accounts or anything using that old email address.
