### ISSUE TITLE
Dataset stuck in status "Processing" (DOI: 10.5061/dryad.gxd2547n3)

### ISSUE THREAD

**Issue by hschubloom** [CDL-Dryad/dryad-product-roadmap#1469]
Dataset is currently stuck in the status “In Progress”. Attempted to force edit and submit, but dataset remains in “In Progress”. Dashboard has a different status of “AAR” and is not consistent. Author cannot update dataset.

**Comment by sfisher** [comment]
This should be fixed.  It looks like there were a couple versions submitted during the same time period.  The versioning should be sorted out and checked the downloads and they worked.
