### ISSUE TITLE
Dataset stuck in status "Processing" (DOI: 10.5061/dryad.4tmpg4f5v) 

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1475]
Dataset is currently stuck in the status in status "Processing". Attempted to force edit and submit, but received the error "You may not create a new version of the dataset until processing completes or any errors are resolved". Dashboard has a different status of “Private for Peer Review” and is not consistent. Author would like the dataset to be withdrawn, but status cannot be altered. 

Additionally, webpage states that dataset is 'Embargoed' which is not consistent with log.

**Comment by sfisher** [comment]
I've set this to `submitted` which makes it editable.  It was successfully submitted but was in a strange state.

https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=10.5061%2Fdryad.4tmpg4f5v&sort=relevance&all_advanced=1&commit=Search

You should be able to change it or withdraw it now.
