### ISSUE TITLE
Import Metadata feature not working for several integrated titles

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1478]
A few submitting authors have confirmed that they are unable to automatically populate the metadata for their data submissions using the "Import Metadata" feature. 

**Here's one example**:
Title: Opposing community assembly patterns for dominant and non-dominant plant species in herbaceous ecosystems globally
DOI: 10.5061/dryad.pzgmsbcn7

The journal is an integrated title: _Ecology & Evolution_ 
And, the journal name and manuscript number are input in an acceptable format in the submission form (no asterisks or revision indicators "R"). 

Ari has reported the same issue for two other integrated titles including _Ecography_ and _Functional Ecology_

Can you investigate why the metadata isn't importing?

**Comment by ryscher** [comment]
The new production server was not authorized to read mail from the journal GMail account. I reauthorized it, and messages are processing now.
