### ISSUE TITLE
Dataset stuck 'In Progress', error in file uploaded is preventing author from submitting (DOI: 10.5061/dryad.g4f4qrfr0)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1479]
The author of this dataset is unable to complete the submission process because of a file error in the 'Upload Files' page of the submission form: 

Title: Ancestry-inclusive dog genomics challenges popular breed stereotypes
DOI: 10.5061/dryad.g4f4qrfr0

This file that has an error identified is unable to be removed or replaced: ReferenceData_breed_stature.csv

**Comment by sfisher** [comment]
This should be deletable now and also put in prevention for this happening.
