### ISSUE TITLE
Dataset status change upon curator reassignment

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1480]
Dataset was moved from PPR to 'Submitted' when assigned curator was removed. PPR check box was not deselected and no system notifications are noted in log. (10.5061/dryad.6q573n60c)

**Comment by ryscher** [comment]
This is the action that Jess requests with the original feature (see https://github.com/CDL-Dryad/dryad-product-roadmap/issues/1404). Do we need a new rule for handling the unassign when items are in PPR?

**Comment by Ariana-Orona** [comment]
I see. Yes, the submission should revert back to PPR if we unassign ourselves, the most recent status was PPR, and the checkbox has not been deselected. There is currently work to update datasets which should remain in PPR until the author deselects the checkbox to ensure they are ready to move forward with curation.
