### ISSUE TITLE
Notes included after SF #### in log are removed

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1483]
**Bug description:**
Curators have noticed that notes following "SF ####" (without a colon) are removed when attempting to change the dataset status to AAR and include reasoning.  An example can be found here: 10.5068/D1H38S

**Steps to reproduce:**
Attempt to change the dataset status to AAR and include a note following the SF #### without a colon.

**Expected behavior: **
Notes remain although SF cases are linked/not linked when providing reasoning for AAR status, with or without a colon.

**Comment by ryscher** [comment]
I am unable to reproduce this problem. For every SF #### note I make, all of the text remains in the comment. Can you provide a more detailed set of directions for producing this issue?

**Comment by Ariana-Orona** [comment]
Here is an example: 10.5068/D1H38S

All of the cases related to this curator are similar when they note SF case numbers as such. However, another curator has confirmed this does not occur for the either. It could possibly be a singular issue.

We have since created a standard to ensure we are all noting SF case numbers in the log.

**Comment by sfisher** [comment]
I believe we should close this and re-open if the problem resurfaces since it seems like it cannot be reproduced and we haven't heard examples in a couple of years.
