### ISSUE TITLE
New tenant: University of Sheffield

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1487]
Logo in email from Rosie on Fri, Oct 1

**Comment by marisastrong** [comment]
@ashleygould please update contact info with this:  webteam@sheffield.ac.uk

@sfisher Sheffiled would like to perform an end-to-end SSO test with the application.  Stage Shibboleth is configured with their entityID and so the Dryad application in stage can be configured with the tenant.  Is it possibly to deploy this on stage for their testing?  Once this has been validated/verified, we can move to production.

**Comment by marisastrong** [comment]
QA - https://idp-qa.shef.ac.uk/shibboleth
LIVE - https://idp.shef.ac.uk/shibboleth
updated entityIDs 

This is not a non-federated institution, U of Sheffield are members of the UK federation.  The Dryad app has been configured as any other tenant who is a member of a federation.  No exception handling is required.
