### ISSUE TITLE
During curation handling

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#149]
Some things we need to consider with curation.  Things are submitted to Merritt and versioned, but they are not exposed to the public.

- [x] Hide landing page from the public for things under curation (except owners and logged in admins)
- [x] Things submitted under curation will need to be excluded from the public SOLR search index.  Probably means modifying the stash_wrapper sent to Merritt and harvester handling of the indexing.
- [x] We do not submit metadata to DataCite while under curation unless released.

Some of these items are fairly large or may deserve their own tickets or there may be other things we need to think through.

**Comment by ryscher** [comment]
Done for v2 launch
