### ISSUE TITLE
Curators experiencing duplicated download of dataset files when attempting dataset download

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1490]
**Bug description:**
When curators attempt to download datasets via the 'Download Dataset' button, they are experiencing multiple dataset downloads which occur randomly and sporadically.

**Steps to reproduce:**
-  Example: 10.5068/D1H38S
Select 'Download dataset' once, wait for the 'Preparing Download' screen to complete and multiple dataset files should download to your device. This happens randomly and does not occur for every download.

**Expected behavior:**
- Datasets should download the number of times the curator hits the 'Download Dataset' button.

---
Note:  There is a possible fix for this on stage.  Perhaps look at datasets from this search https://dryad-stg.cdlib.org/search?q=-%22data+from%3A%22 since there is some bad data on stage we could clear out (most of the stuff with "Data from:" in the title are currently bad).  We can try cleaning up stage some when we have a bit of time.

Or these are good for downloads:

```
https://dryad-stg.cdlib.org/stash/dataset/doi:10.7959%2Fdryad.34tmpg52
https://dryad-stg.cdlib.org/stash/dataset/doi:10.7959%2Fdryad.j6q573r3
https://dryad-stg.cdlib.org/stash/dataset/doi:10.7959%2Fdryad.4xgxd254v
https://dryad-stg.cdlib.org/stash/dataset/doi:10.7959%2Fdryad.wpzgmsbgp
https://dryad-stg.cdlib.org/stash/dataset/doi:10.7959%2Fdryad.3xsj3tx9r
https://dryad-stg.cdlib.org/stash/dataset/doi:10.7959%2Fdryad.hqbzkh1b8
https://dryad-stg.cdlib.org/stash/dataset/doi:10.7959%2Fdryad.hqbzkh40
https://dryad-stg.cdlib.org/stash/dataset/doi:10.7959%2Fdryad.9s4mw6mb6
https://dryad-stg.cdlib.org/stash/dataset/doi:10.7959%2Fdryad.z612jm67f
https://dryad-stg.cdlib.org/stash/dataset/doi:10.7959%2Fdryad.cjsxksn1h
https://dryad-stg.cdlib.org/stash/dataset/doi:10.7959%2Fdryad.b8gtht77t
```

The datasets in the notes didn't show the problems and I don't think it's particularly related to any specific dataset. I think it just happens in some circumstances to a small percentage of datasets, possibly with some specific kind of interaction.

Let me know if you can duplicate the problem with downloads on stage.

**Comment by Ariana-Orona** [comment]
Another example - DOI: 10.5061/dryad.dv41ns1wr

Steps to reproduce:
1. Select 'Download dataset'
2. Wait until the 'Preparing Download' has been completed and the folder pops up in the browser (wait time still present)
3. Additional, duplicated folders begin download

**Comment by Ariana-Orona** [comment]
Additional example: 
Chrome - Version 95.0.4638.69 (Official Build) (64-bit)
10.5061/dryad.70rxwdbz8

Each version relates to a separate curator.

**Comment by sfisher** [comment]
Please test on dryad-stage ( https://dryad-stg.cdlib.org/search?q=-%22data+from%3A%22  )to see if this is still happening.  See notes in ticket above.

**Comment by Ariana-Orona** [comment]
I believe I found updated instructions which may help:

Steps to reproduce:

Select 'Download dataset' once
Wait until the 'Preparing Download' is inititated
Navigate to an alternate tab and do not return to the dataset tab 
Duplicated folders begin download and pop up in the browser

I will see if the dryad-stage performs this as well.
