### ISSUE TITLE
Associate Jacqueline Jerney's ORCID ID with current email address (0000-0002-2736-5179)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1497]
Please associate Jacqueline Jerney's ORCID ID with the preferred/current email address: 

ORCID ID: 0000-0002-2736-5179
Current email: jacqueline.jerney@gmx.at
Previous email: jacqueline.jerney@helsinki.fi

**Comment by ryscher** [comment]
Merged 2 accounts.
