### ISSUE TITLE
Author unable to add ORCID ID to dataset (10.5061/dryad.k98sf7m4k)

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1500]
Author Adriana Allek (adriana.litaiff@gmail.com) has been unable to add their ORCID ID (0000-0003-4569-6593) to the noted dataset. When given the following link, author receives this error message "You've already added your ORCID to this dataset"

https://datadryad.org/stash/dataset/doi:10.5061/dryad.k98sf7m4k?invitation=EJcfI0eS1y3drGXLwvvG3g

Please update the dataset with the author's ORCID ID or let me know if another link should be sent to the author.

**Comment by sfisher** [comment]
I updated the orcid for this author.  The invitation for the author had already been accepted and validated by the main author and I could see that Adriana had the main author's ORCID in past versions.

It verifies the ORCID by having the person log in (the way ORCID requires us to integrate). So, for example, this might happen if sharing the same computer while working on it and Renato is already logged in to ORCID but Adriana checks her email on that computer and follows the link using Renato's already logged in account to validate the wrong ORCID.

**Comment by Ariana-Orona** [comment]
@sfisher thank you for taking the time to explain this. I appreciate it! I have let the author know their ORCID ID has been added.
