### ISSUE TITLE
Remove previously published version of dataset (DOI: 10.5061/dryad.05qfttf36)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1507]
The authors have requested that the first published version of this dataset be removed. It was published on July 17, 2021.
These files are included in the first version: 'metadata0718.zip' & 'README.docx'

From the author: "The reviewer advise us to improve our article by add more useful figures. We worry about that the change of figures arrange number in new submit database may make the reader confuse when compare to the figures arrange number in older one."

Title: In situ polyaniline coating of Prussian blue as cathode material for sodium-ion battery
DOI: 10.5061/dryad.05qfttf36

**Comment by sfisher** [comment]
The first version (July 17th) is no longer shown.
