### ISSUE TITLE
Can't remove journal information

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1512]
1. Go to the metadata entry page.
2. Select "manuscript in progress" and select a journal.
3. Go to review and it will show errors that you need to fill in a manuscript number and not let you submit.
4. Go back to the entry page.  Even if you remove the journal or select "other" from the radio buttons, it doesn't remove the journal and will harass you forever to enter a manuscript number.

**Comment by ryscher** [comment]
This has been fixed.
