### ISSUE TITLE
Error message when attempting to view Activity Log for Dryad datasets

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1513]
**Bug description:**
When I select the clock icon to view the Activity Log for any Dryad submission, the following error message appears: 

<img width="586" alt="Screen Shot 2021-11-02 at 8 29 45 PM" src="https://user-images.githubusercontent.com/76497320/139994998-1a0ccf3a-3ea8-4920-9422-f0fa6c304a4b.png">

Can you investigate?

**Comment by ryscher** [comment]
The page was not displaying because the Salesforce password had expired. I changed the password and updated the Salesforce policies so it will not expire again. Will make the app more robust so problems with Salesforce don't disable the entire page.
