### ISSUE TITLE
Update dataset to apply fee waiver (DOI: 10.5061/dryad.xpnvx0kgr)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1514]
A fee waiver should be applied to this dataset because the research was conducted by the Lwala Community Alliance, which is based in Kenya -- which is classified as a lower-middle income economy by the World Bank. 

Does the ORCID ID need to be linked to the alternate email address or does the tenant need to be updated so that the fee waiver is applied? 

Title: Lwala Household Survey 2018-2019: Demographic, Depression, and Economic Variables
DOI: 10.5061/dryad.xpnvx0kgr

Author's ORCID ID: **0000-0001-7954-5385** is associated with this email address: joseph.r.starnes@vanderbilt.edu
The author's alternate email is: Joey@lwalacommunityalliance.org

**Comment by sfisher** [comment]
I changed this to a fee waiver for based on Kenya.

It seems as though the fee waiver is normally based on the organization being in one of those countries based on the ror id.  It doesn't seem like this organization is know to ror (or its country) so the waiver wasn't automatically applied.  https://ror.org/search?page=1&query=lwala
