### ISSUE TITLE
Migrate account for David Peris Navarro (ORCID ID: 0000-0001-9912-8802)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1519]
Please associate David Peris Navarro's Gmail account with the ORCID ID provided below: 

ORCID ID: 0000-0001-9912-8802
Current email: david.perisnavarro@gmail.com
Previous email: perisnavarro@wisc.edu

**Comment by sfisher** [comment]
I've merged these two users.
