### ISSUE TITLE
Make published dataset private; place in "Private for Peer Review" status (DOI: 10.5061/dryad.1g1jwstxp)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1520]
Author has requested to make published dataset private because the related article hasn't been published. In my email to the author, I did mention that "the journal does not require the simultaneous or timed release of either entity, we suggest keeping your dataset publicly available." However, the author still maintains the data should be removed and placed in "Private for Peer Review" status instead. 

Title: Investigating the utility of Anchored Hybrid data to resolve the relationships among the Killifishes (Actinopterygii: Cyprinodontoidea), a globally distributed group of fishes
DOI: 10.5061/dryad.1g1jwstxp

**Comment by sfisher** [comment]
Ok.  This is back in private for peer review.
