### ISSUE TITLE
Add Biology Methods and Protocols to database as a journal that will be sending us metadata emails (integration) but are not cost covering (OUP)

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1526]
Not paying but want to be integrated

**Comment by ryscher** [comment]
Is this "Biology methods & protocols"? I don't see a "processes".

**Comment by ryscher** [comment]
They will need to send a test metadata message so I can verify that I have the correct format for their manuscript numbers, and that other metadata is processing correctly.

**Comment by dlowenberg** [comment]
Yes that was a careless copy paste sorry it's Protocols! And yes, I've asked both them and the ESA journal that is adding integration to please let me know when it's set up on their end (which it is not yet).
