### ISSUE TITLE
If we receive a notice of rejection on related manuscript, move dataset to status='withdrawn'

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1528]
cc: @Ariana-Orona letting you know we are changing what you showed yest, so it goes to withdrawn not AAR

**Comment by ryscher** [comment]
I have completed testing with journals that use email integration, and the messages already go to `withdrawn`. Is this issue associated with a journal that uses the API?

**Comment by ryscher** [comment]
This appears to be working as intended. The example of unexpected behavior was from the v1 system. So I'm calling this ticket done for now.
