### ISSUE TITLE
Return published dataset to 'Author Action Required' (DOI: 10.5061/dryad.x0k6djhk9)

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1532]
Please revert this published dataset entirely from the site and return dataset to 'Author Action Required'. Files contain information which was not properly curated. Zenodo files are fine to keep while we work to clean the files uploaded as 'Data'.

Title: New incidence or recurrence hepatocellular carcinoma (HCC) in genotype 4 hepatitis C virus treated with sofosbuvir/daclatasvir with or without ribavirin
DOI: 10.5061/dryad.x0k6djhk9

**Comment by sfisher** [comment]
It looks like Ryan might have already done this?  In any case it's not public now.

**Comment by ryscher** [comment]
Dataset is now unpublished. The latest version is in `curation` status. I'll leave it that way, and you can set it to AAR with the appropriate message.
