### ISSUE TITLE
Mitigate Rack::Attack filling inodes on filesystem

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1533]
We saw inodes filling.  One way to clear is `Rack::Attack.reset!` in the console, but it is a full clear.

This issue is related and mentions it uses the Rails file cache.  https://github.com/rack/rack-attack/issues/461

This talks more about some ways to manage the Rails file cache and clear it periodically.  Perhaps a cron job.

---

Clearing this came up again on a stage server and I cleared it on 2022-01-26.

Another way to clear is to do `Rails.cache.clear` in the console.

**Comment by ryscher** [comment]
It looks like the file cache can be managed just like log files, so we should be able to regularly clear it with a command like:
`find /apps/dryad/apps/ui/shared/tmp/cache -mtime +30 -exec rm {} \;`

Since there is no rush, let's discuss with Ashley what method she prefers.

**Comment by ryscher** [comment]
Ashley says it is fine for us to add the above `find` command to our existing cron scripts.
