### ISSUE TITLE
New institution: UBC

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1535]
Logo in email from Sheldon Armstrong

**Comment by marisastrong** [comment]
entityID="https://authentication.ubc.ca"

Metadata can be found here:  https://mdq.incommon.org/entities/https%3A%2F%2Fauthentication.ubc.ca

**Comment by marisastrong** [comment]
UBC to trust Dryad Metadata - ETA: Friday 26th November, 2021

FYI: Complying with the UBC’s privacy/governance – the eduPersonPrincipalName value sent will be an opaque identifier (similar in concept to eduPersonTargetedID) – in future, similar will be also applicable to the ‘mail’ (mail routable, however opaque – i.e. unique to the SP and address not identifiable to the user).

**Comment by sfisher** [comment]
Ok.  I've deployed it to dev and stage.  I appears to be working to me, but they will need to test logging in.

![Screen Shot 2021-11-29 at 3 56 01 PM](https://user-images.githubusercontent.com/105433/143961919-9e686138-b8a8-4c91-919d-5d95e1014f15.png)
![Screen Shot 2021-11-29 at 3 55 13 PM](https://user-images.githubusercontent.com/105433/143961920-7f7cf0bc-28c5-4812-9d5e-2523883b5689.png)
![Screen Shot 2021-11-29 at 3 46 15 PM](https://user-images.githubusercontent.com/105433/143961922-2e37095d-5be6-4aa2-bdd6-fbb64ddf5c48.png)
![Screen Shot 2021-11-29 at 3 45 34 PM](https://user-images.githubusercontent.com/105433/143961926-f0e57795-ef37-4b37-80ab-2343bbf9cec2.png)

**Comment by sfisher** [comment]
When I test on stage, I get "The application you have accessed is not registered for use with the service."

But maybe it's because they only set up to access https://datadryad.org

![Screen Shot 2021-11-29 at 4 44 18 PM](https://user-images.githubusercontent.com/105433/143965155-8e17c185-a888-4e37-b293-103ddf352960.png)
