### ISSUE TITLE
Messed up removal and formatting of authors

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1541]
There are two weird problems that are pre-existing and I ran into while trying to redo the autocomplete.

1.  The weird text `Link to associate ORCID: https://localhost:3000/stash/ . . .` under an author isn't removed if the author is removed, so there are just a stack of those weird messages plopped in the page for authors that no longer exist.
2.  A new author isn't actually removed if the "Remove" button is clicked.  Only authors that exist on page load are removeable.
  - Add a new author
  - Click "remove" for that author.  They disappear from the page.
  - Refresh the page -- they are back.

**Comment by ryscher** [comment]
Closing, since the autocomplete has been rewritten since this ticket was created.
