### ISSUE TITLE
Dataset linked with sponsoring institution but charged DPC (DOI: 10.5061/dryad.qjq2bvqhb)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1542]
The submitting author was charged the DPC, however, UC Santa Barbara is a member institution. As far as I can tell, everything seems to be linked appropriately. Can you investigate what the issue might be? Incorrect tenant? 

Title: Sex differences in behavioural and anatomical estimates of visual acuity in the green swordtail Xiphophorus helleri
DOI: 10.5061/dryad.qjq2bvqhb

Submitting author: Eleanor M Caves
ORCID ID: 0000-0003-3497-5925
Email: eleanor_caves@ucsb.edu
Affiliation: University of California, Santa Barbara

**Comment by ryscher** [comment]
The user had never authorized their account with UCSB. I updated the user account, updated payment info in the database, and voided the invoice.
