### ISSUE TITLE
"Review and Submit" page not displaying for dataset DOI: 10.5061/dryad.ns1rn8pv9

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1546]
This dataset doesn't display the "Review and Submit" page. Therefore, there's no option to complete the submission. Please investigate. 

Title: The angle of attack: Rapping technique predicts skill in hermit crab contests
DOI: 10.5061/dryad.ns1rn8pv9

**Comment by ryscher** [comment]
Fixed. The user had added a funder, but all of the funder information was blank. 

This was related to the `end_with?` issue, so going forward, it should already be fixed by https://github.com/CDL-Dryad/dryad-app/pull/716

**Comment by Ariana-Orona** [comment]
Same issue here:

Title: Characterization and biodiversity of native Azotobacter in semi-arid agroecosystems of Eastern Kenya
DOI: 10.5061/dryad.1vhhmgqv3

This has occured with two other datasets that I know of. I have been instructing users to exit the dataset and try again after a short break. This seems to have worked, but I have used a dangerous action to submit it for a user once before.
