### ISSUE TITLE
Remove duplicate published dataset (DOI: 10.5061/dryad.xpnvx0kd9)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1547]
Please remove this version entirely: 

Title: Ecological divergence and the history of gene flow in the Nearctic milksnakes (Lampropeltis triangulum complex)
DOI: 10.5061/dryad.xpnvx0kd9 -- published November 9, 2020

**Comment by dlowenberg** [comment]
Commenting here and closing ticket to let you know that we do not need to remove this unless there are concerns about it being public -- let me know if any issues with author correspondence
