### ISSUE TITLE
Migrate dataset to new submitting author (DOI: 10.5061/dryad.mgqnk98zz)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1550]
Please migrate this dataset to a new submitting author: 
> Frances Buderman
> ORCID ID: 0000-0001-9778-9906
> Email: fbuderman@psu.edu

Dataset information: 

> Title: Data from: Caution is warranted when using animal space-use and movement to infer behavioral states
> DOI: 10.5061/dryad.mgqnk98zz

**Comment by sfisher** [comment]
Ok.  I updated the owner of this datset to Frances Buderman from Duane Diefenbach and updated their email address in their user record.
