### ISSUE TITLE
Please withdraw published dataset (10.5061/dryad.mkkwh711p)

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1555]
Please withdraw the noted dataset. The author has informed us that the journal has concerns regarding the published dataset and there may be an update to the data related to the associated manuscript.

Title: Berberine protects against sepsis-related acute lung injury in rats via the upregulation of the PPAR - Υ signaling pathway, with amelioration at the cellular level - A functional, immune-histological and biochemical study
DOI: 10.5061/dryad.mkkwh711p

**Comment by dlowenberg** [comment]
Hi Ari, what are the concerns? Legal or Risk factors if we keep the dataset live? If you do not know yet, please write back and ask for them to let you know what the concerns are and then let me know what they say. In some cases, we may ask for them to provide an updated version but keep the old version live (do not mention this to them yet), and in some we may keep the DOI etc but just swap the file. Slack me if you have any questions.

**Comment by ryscher** [comment]
Closing, as this issue is no longer relevant. The underlying issue dealt with the journal's software for detecting plagiarism, and such software is generally not aware of datasets.
