### ISSUE TITLE
Please remove this published dataset (DOI: 10.5061/dryad.tx95x69w2)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1558]
Please remove this data submission entirely because it's a duplicate of an earlier published dataset.

Remove: 

> Title: Raw data from: Consumer-resource interactions along urbanization gradients drive natural selection
> DOI: 10.5061/dryad.tx95x69w2

**Comment by dlowenberg** [comment]
Like other case -- closing this and we do not need to remove unless issues with the data being public -- let me know if any issues with author correspondence
