### ISSUE TITLE
ORCID Maintenance

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#156]
mstrong [3:47 PM]
right so what do you do in the cause of a failure where this would get invoked?

sfisher [3:47 PM]
IDK, I haven't traced through all the omniauth code.
But it sounds like we can configure a failure endpoint and just put something there from what Brian says.
I'll have to look sometime.

mstrong [3:49 PM]
right.  that seems straightfoward?  or is Dash too complex to handle this type of thing?

sfisher [3:49 PM]
I think it's fairly straightforward.
probably something I need to set in our config and put in a template if we don't have one yet.

sfisher [4:04 PM]
I'll put in a ticket.  Is it this saturday?

mstrong [4:05 PM]
yeah @briri failure endpoint is just to redirect back to the homepage/dashboard.  seems like you could just redirect back to the page and display some kind of warning/error message?

**Comment by marisastrong** [comment]
Dec 15 is the maintenance day


________________________________

**Comment by sfisher** [comment]
Done.
