### ISSUE TITLE
Require README on upload page (technical)

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1563]
**Need:** Only on the data box on the upload page, require that a file be named README. For now, do not require a specific extension after that. If you need to -- the ones to account for are .txt, .doc, .docx, .md., .rmd. 

**For the error message:** include note in red box on page 3 where the other requirements are, and do not allow user to click submit along with the metadata field requirements.

Ticket 1564 to include wording for the upload page & static help page text

**Comment by ryscher** [comment]
Currently, data file uploads are optional. So I could interpret this ticket in two ways:
1) Require at least one data file, which must be a README. So the warning about 'no data files' is no longer needed.
2) Only require a README if there is at least one other data file. So there may be 0 data files, or a README plus other data files, but never exactly one data file.

Preference?
