### ISSUE TITLE
Initial React setup for metadata entry & investigate

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1576]
- [x] Create directory structure for organizing components (Do they need to be under the main app in /app/javascript/ components?  Or do we care and would like to consolidate them there, anyway?)
- [x] We need to investigate if one of a number of React form library projects offers any major advantages over generic React? (See https://dev.to/pmbanugo/looking-for-the-best-react-form-library-in-2021-it-s-probably-on-this-list-e2h or other sites)
  - Will it do most of what we need?
  - Does it actually save us effort or does it add more overhead and effort because defaults or something else isn't right?
  - Does it look actively maintained and have a good community?
- [x] Discuss what testing strategy is sufficient? Are Jest test that look at basic rendering plus any logic in React OK?

Some beginning general thoughts about how to approach going from Rails --> React are at  https://docs.google.com/document/d/1lsUKu2L6mtYUS_ANI04q8w3OUzADtPesv2QLwKd8fpA/edit?usp=sharing

**Comment by sfisher** [comment]
@ryscher I'm looking at how to structure things and coming up against a few decisions to make. They can be refactored later, but it would be nice to get in the ballpark of something that will scale and be OK to work with.

## Code structure
- I'm OK putting the code in `dryad-app/javascript` which is where it is right now, though I think i vanilla react projects it's usually `/src`.  The `components`  and `containers` seem pretty standard.   `Components make things look good, while containers make things work.`
- He mentions a `core` directory, which I think is similar to our existing `lib` directory.  In his, he has a bunch of model stuff since he's using typescript.  IDK if we should try to pile typescript on or not (it's basically typed Javascript).  Also some shared functions and things for working with some extra libraries are in there.
- It's not clear to me if we need a services directory or what they exactly do.
- I don't think we'll be adding many CSS styles or routes within react right now since we can mostly use the ones already defined in the main app.  Maybe at a later time we can restructure all that CSS or have multiple "pages" shows by something besides rails if we redo the whole app, but I don't see that happening soon.
- He says to put components in directories and sub-directories, but right now all the file stuff is in the base.  I might try to at least move the file upload stuff into its own directory if I can and not break things.
- He shows tests beside his components in the same directory.  Right now it looks like our Jest/Javascript tests are in `spec/javascript` and there are only a couple of tests.  Any preferences for keeping all tests in `spec` or would you rather see them next to the javascript?

## Redux ?
- From what I understand, Redux is a library that stores objects (in memory).  It can store complex objects unlike the session store (strings).  It requires special interfaces to store/filter. Apparently the advantage is that it makes it easier to use a `subscriber` model for state updates so that components re-render automatically if their data is changed or something like that.  I'm not really clear if it will be an advantage to start with it.  Any thoughts?

**Comment by ryscher** [comment]
- I would rather keep the tests in `spec`. I think the same-directory arrangement is more "old school". It's not necessarily wrong, but very few people do it that way now, and I don't see a compelling reason for us to change.
- Redux sounds useful, so we will probably want to add it at some point, but if it makes things complex we certainly don't need to add it in the first version.
