### ISSUE TITLE
Dataset stuck in 'Processing' - DOI: 10.5061/dryad.0gb5mkm1r	

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1582]
Dataset is currently stuck in 'Processing' and the author and curator cannot make changes. Please submit the latest version of the dataset and submit as 'PPR' so the author can make changes if necessary before the dataset enters our queue for curation.

Title: Thainema gen. nov. (Leptolyngbyaceae, Synechococcales, Cyanobacteria): A new genus of simple trichal Cyanobacteria isolated from a solar saltern environment in Thailand
DOI: 10.5061/dryad.0gb5mkm1r

**Comment by sfisher** [comment]
This should be out of processing now.  I have it under your name, but I'll let you update to the state you'd like to see it in for curation (or you could unassign yourself).

This is the one you mentioned:

https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=0gb5mkm1r&sort=relevance&commit=Search&utf8=%E2%9C%93

Note there is another dataset that looks like the same thing and was submitted again at https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=v15dv41x5&sort=relevance&commit=Search&utf8=%E2%9C%93 .
