### ISSUE TITLE
Datasets auto-assigned incorrectly; not assigned to previous curator

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1590]
Some datasets that were previously claimed and curated by our UCSB contact were auto-assigned to a Dryad curator (Ariana). Based on our workflow, any resubmissions should be assigned to the handling curator. 

Here are some examples: 
10.25349/D9ZG7Q
10.25349/D9SP5G

Can you investigate, please? I'm wondering whether this is a specific issue only for Renata. 

These UCSB datasets also begin with a different prefix for the DOI (10.25349) which might be helpful if a new rule needs to be created.

**Comment by jleighherzog** [comment]
Also, Greg Janee appears twice in the drop-down list of curators. One of the profiles for Greg has no dataset history attached so, please remove that one.

**Comment by ryscher** [comment]
I verified that Greg's extra account was not attached to any datasets (as author or curator), then removed it.
