### ISSUE TITLE
Migrate account for William Monahan (0000-0002-1796-8064)

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1594]
Please associate William Monahan's email with the ORCID ID provided below:

ORCID ID: 0000-0002-1796-8064
Current email: william.monahan@usda.gov
Previous email: Bill_Monahan@nps.gov

**Comment by sfisher** [comment]
Thanks @Ariana-Orona .  I've merged his user accounts and updated his information.
