### ISSUE TITLE
Add two journals: European Respiratory Journal and ERJ Open are both sponsored by the European Respiratory Society

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1595]
At quarterly invoicing Jen will need to groom through and apply vouchers to these journals - they are not actually paying subscription just using up the last of vouchers but in the meantime their authors can submit at no cost

**Comment by ryscher** [comment]
These journals were already attached to the correct organization. I updated the payment plans for them in both Dryad and Salesforce.
