### ISSUE TITLE
Annual cleanup!

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1599]
It's time for the annual removal of datasets in progress from the last two years, anything else that we wrote in last year that we also want to remove (from other statuses)?

**Comment by ryscher** [comment]
@jleighherzog There are around 30 datasets that have been in `peer_review` or `embargoed` for years. Could the curation team review and update them?

**Comment by jleighherzog** [comment]
@ryscher : J&J can do this. Can I get a list?
