### ISSUE TITLE
Improve ISSN handling in internal data

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#160]
There is an ISSN in internal data.  Currently all internal data is strictly Key/Value with a simple editing interface that is the same for all.

Daisie put in a ISSN journal lookup in the editing page.  Ideally curators would be able to look up with this instead of committing ISSNs to memory or having to go somewhere else to look them up.

Also, where those are shown in the internal data table it would be nice to display a name instead of just a number.  That may require external lookup calls and caching known journals (to minimize slow external lookups).  :-/

**Comment by ryscher** [comment]
We have refined this in many ways since the ticket was created....
