### ISSUE TITLE
Update to Dryad site and email notifications

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1603]
Changes noted here: https://docs.google.com/document/d/1Z0UMT01wot9EcdHupz6rHvQMWxj7Xdn-aGeYfsJNuEo/edit

**Comment by ahamelers** [comment]
@ryscher @sfisher Can anyone access this google doc?

**Comment by ryscher** [comment]
No, I requested access, but it might be owned by Ari's Dryad account, in which case she wouldn't see the email. I'm not certain whether her Google docs were transferred to anyone else, since she had a gradual transition to her new job. I can follow up with Jess.

**Comment by ryscher** [comment]
The document is now viewable.

**Comment by jleighherzog** [comment]
@ahamelers @ryscher : Access provided to Ryan, Audrey, Bryan. However, this document is old and outdated. I'll close this ticket and initiate a new one.
