### ISSUE TITLE
Migrate account for Gavin McNicol (0000-0002-6655-8045) 

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1607]
Please associate Gavin McNicol's email with the ORCID ID provided below:

ORCID ID: 0000-0002-6655-8045
Current email: gmcnicol@uic.edu
Previous email: gmcnicol@alaska.edu and/or gmcnicol@stanford.edu

**Comment by ryscher** [comment]
Merged 3 accounts, updated email.

**Comment by Ariana-Orona** [comment]
@ryscher Thank you. Is it possible to associate his account with University of Illinois at Chicago instead?
