### ISSUE TITLE
Curation report: milestones & turnaround times

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1611]
Report wish list:
- "Submitted" to "Curation" (1st statuses)
- "Submitted" to "Publication" (1st "Submitted" and 1st "Published" statuses)
- "Curation" to "Publication" (1st statuses, average and median times)
- "PPR" to "Curation"
- CurationCompletedDate - The status changed from curation to action_required, embargoed, or published.
- Time in AAR status (average and median times)
- 2021 only. If that's too much data, maybe just June-Dec 2021

Let me know what's possible. It's challenging for me to identify what statuses to report on because most datasets have multiple statuses like "In Progress" or "Curation" each time they're edited and rebuilt. But, if there's some way to remove the "noise" of the limbo statuses, measuring only 1st or final statuses, that might work:

**Comment by ryscher** [comment]
- want to run it at least monthly
- need to make first version available for board meeting

**Comment by jleighherzog** [comment]
Hi busy bees. Possible to have some numbers in two weeks time? Would be good to have something to present for future meeting with Iratxe, Scott, Catriona, & Jen (in 3 weeks)
