### ISSUE TITLE
Place dataset in AAR status DOI: 10.5061/dryad.3j9kd51js

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1612]
This dataset was accidentally published. The current status is "embargoed". 

Please remove the published version and place dataset in "Author Action Required" status. 

Title: Micro‐CT reconstruction reveals the colony pattern regulations of four dominant reef‐building corals (Part six)
DOI: 10.5061/dryad.3j9kd51js

**Comment by ryscher** [comment]
Unpublished from Dryad and made DataCite DOI non-searchable. Dataset had not yet propagated to Zenodo.
