### ISSUE TITLE
Associate Neal Tilhou' profile with the University of Wisconsin–Madison

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1625]
Please tie Neal Tilhou' profile with the University of Wisconsin–Madison

Email: wepking@wisc.edu
ORCID ID: 0000-0002-5221-1809

**Comment by ryscher** [comment]
Added tenant, updated email address.

**Comment by Ariana-Orona** [comment]
thank you @ryscher
