### ISSUE TITLE
Status update via API call inaccurate

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1630]
Title: LRET-derived HADDOCK structural models describe the conformational heterogeneity required for processivity of the Mre11-Rad50 DNA damage repair complex
DOI: 10.5061/dryad.qfttdz0h6

Dataset withdrawn 01/17/2022 although manuscript was accepted 01/27/2022

**Comment by dlowenberg** [comment]
Hi Ari, can you please clarify what the issue is and what needs to happen for resolution?

**Comment by Ariana-Orona** [comment]
Of course. The dataset was withdrawn on 01/17/2022, the Activity Log notes "status updated via API call" on this day. However, we received notice of manuscript approval on 01/27/2022 and I cannot find a rejection notice on 01/17/2022. Additionally, the manuscript number did not change. Datasets should be withdrawn if the manuscript is rejected (@jleighherzog and I will submit a ticket soon to request an automated email for these instances), but this seems to have been done incorrectly. The dataset should have been sent to the queue upon manuscript acceptance instead of withdrawn 10 days prior to the notification.

**Comment by Ariana-Orona** [comment]
![image](https://user-images.githubusercontent.com/80363462/153949505-72cfbdbb-c65c-48e9-84de-bef9e121d68e.png)

**Comment by ryscher** [comment]
Since this ticket was first filed, we have made many updates to API processing and improved the notes that appear in the activity log. If it happens again, there will be a much better trail to follow.
