### ISSUE TITLE
Replace README file for dataset (DOI 10.7272/Q69Z934Z)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1631]
Please remove the existing file "README.md" from the current version and replace with the file attached here:
[README.md](https://github.com/CDL-Dryad/dryad-product-roadmap/files/7982495/README.md)

Additionally, please update the title to follow sentence case as shown below: 

Title: Daily United States COVID-19 data for select cities and counties, May 29, 2020 to October 21, 2020
DOI: 10.7272/Q69Z934Z

I'm unable to make the update because the first name field is blank (and required). Prefer to keep the author line as-is without adding any special characters. 

Once complete, I'll publish it.

**Comment by ryscher** [comment]
I replaced the file, updated the title, and assigned it back to Jess.
