### ISSUE TITLE
Improve styling of <strong> tags

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#1634]
When users add **bold** formatting in the text editors, it is stored as a `<strong>` tag. The landing page does not display this very well. But the landing page does display other bolded information well, using a different style. So copy the other styling to the `<strong>` tags, and ensure it looks correct anywhere `<strong>` is used in the system.

**Comment by sfisher** [comment]
Or just modify the base stylesheet so that these base styles aren't reset to nothing, but show better.
