### ISSUE TITLE
FPT and virtual environment access for Iman Nematollahi

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1635]
Please provide Iman Nematollahi with access to our FTP server. Iman will be our point-person for all FTP requests from authors. Additionally, he will require sudo capabilities. 

Additionally, please provide Iman with access to our virtual environment. Mariah will no longer require access after Friday, February 11th. If necessary, you can remove my access to make room for one more! 

If you have any questions, please ask Mariah or Iman.

**Comment by ryscher** [comment]
Iman's accounts are set up. I will wait until after the 11th to disable Mariah's accounts.
