### ISSUE TITLE
Datasets stuck in "Processing" status after editing and rebuilding

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1638]
I edited and rebuilt these datasets and they've been stuck in "Processing" for at least 10 min. 
Can you investigate, please? 

Title: Re_source selection functions based on hierarchical generalized additive models provide new insights into individual animal variation and species distributions_
DOI: 10.5061/dryad.9p8cz8wh3

Title: _Changes in the direction of the diversity-productivity relationship over fifteen years of stand development in a planted temperate forest_
DOI: 10.5061/dryad.cvdncjt62

Title: Scientists attitudes toward sharing data over time 
DOI: 10.5061/dryad.4mw6m90c0

**Comment by ryscher** [comment]
There seems to be a delay in Merritt processing today. I have asked the Merritt team for the status.

**Comment by ryscher** [comment]
The Merritt team was able to correct the issue. All submissions are being processed normally now.
