### ISSUE TITLE
Associate Emily Donham’s profile with University of California, Santa Cruz tenant

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1641]
Please tie Emily Donham’s profile with the University of California, Santa Cruz 

Email: edonham@ucsc.edu
ORCID ID: 0000-0002-5190-0151

**Comment by ryscher** [comment]
Done

**Comment by Ariana-Orona** [comment]
@ryscher thank you! :)
