### ISSUE TITLE
Test CEDAR metadata template

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1642]
As promised, we have made a reasonably complex CEDAR template ("CEDAR-NCBI Human Tissue"), which is used to submit metadata about human tissue samples to the NCBI, available to CEDAR's Embeddable Editor. That template, together with the "eDNA ECT Demonstration" built by Ted, should be enough to test the different capabilities of the CEE. Here are the details of those two templates:

Template 53: “CEDAR-NCBI Human Tissue”:
- CEDAR url (requires authentication): https://cedar.metadatacenter.org/templates/edit/https://repo.metadatacenter.org/templates/dc3fa214-88f4-49dd-b56b-f4552b2d3474 
- Component server URL (doesn’t require authentication, accessed directly by the CEE): https://component.metadatacenter.org/cedar-embeddable-editor-sample-templates/53/template.json 

Template 52: “eDNA ECT Demonstration”:
- CEDAR url: https://cedar.metadatacenter.org/templates/edit/https://repo.metadatacenter.org/templates/30f40c2b-0fe2-4ad5-a130-d7329d0e6b50 
- Component server URL: https://component.metadatacenter.org/cedar-embeddable-editor-sample-templates/52/template.json 

The CEE reads the templates from CEDAR’s component server, where they are organized in numbered folders (one per template). 52 and 53 are the folders of the two templates listed above. All the templates made public via the component server are available on GitHub (https://github.com/metadatacenter/cedar-component-distribution/tree/master/cedar-embeddable-editor-sample-templates), and can also be accessed directly via the component server (e.g., to access template in folder XX, go to https://component.metadatacenter.org/cedar-embeddable-editor-sample-templates/XX/template.json). The CEE shows a list of the templates made available to it at the bottom  (“Sample templates” section).

We have updated the generic demo app (develop branch: https://github.com/metadatacenter/cedar-cee-demo-generic/tree/develop) to point to template 53 by default, and to read the templates from our production’s Component server (it was previously pointing to our staging server). Misha has also generated an empty CSS template for the CEE (https://github.com/metadatacenter/cedar-cee-demo-generic/blob/develop/assets/css/styles.css).

**Comment by ryscher** [comment]
Demonstration code and documentation is in the `cedar-test` branch.
