### ISSUE TITLE
File upload issue (DOI: 10.5061/dryad.6q573n612)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1644]
The author of this dataset has reported that they are unable to proceed to submit their dataset because the files aren't uploading. 

Title: Environment regimes play an important role in structuring trait- and taxonomy-based temporal beta diversity of riverine diatoms
DOI: 10.5061/dryad.6q573n612

From the author: "For an accepted manuscript (JEcol-2021-1016), I am trying to upload the required files to Dryad. However, I got a problem when I upload documents to the system. It stayed the same status for several hours that I can't upload finally."

The progress bar doesn't show any indication of advancement. I've attached a screen capture from the author. 
<img width="455" alt="Screen Shot 2022-02-08 at 12 57 43 PM" src="https://user-images.githubusercontent.com/76497320/153056776-4c774d7e-1f98-4fb1-8647-6710b3a80c38.png">

Please investigate. Ari also reported (to me) that she has identified the same issue this week. Raising a ticket so that we can populate other instances here.

**Comment by jleighherzog** [comment]
1) **What browser were you using?** 
I used both google chrome and IE, but unfortunately, both of them didn't work. 

2) **What type of upload? If by URL where are the data currently (e.g., Box)**
I used local uploading (from my laptop). There are 4 files (see below): one "readme.txt" (2 kb), one "Environmental factors.csv" (31.15kb), "Sp_diatom.csv" (102.46kb) and one "Tr_diatom.csv" (4.32kb). 

3) **How large are the files that are failing?**
 see above, the files are quite small.

**Comment by Ariana-Orona** [comment]
Additional dataset: 10.5061/dryad.66t1g1k3v

**1. What browser were you using?**
Firefox

**2. What type of upload? If by URL where are the data currently (e.g., Box)**
The author attempted to upload the files via 'Choose files' from their PC

**3. How large are the files that are failing?**
4 KB (.txt file) and 3.5 GB files (zip file containing a special format .ptu files)

**Comment by ahamelers** [comment]
Related to #2075?

**Comment by jleighherzog** [comment]
@ahamelers : Yes, different dataset but same issue.
