### ISSUE TITLE
Investigate Europe PMC links (fix if quick)

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1651]
All the documentation regarding the external links is available at this
URL: https://europepmc.org/LabsLink

You're already providing us with a perfectly valid "profile" file
(labslink-profile.xml), and similarly there's a valid "links" file
(labslink-links.xml) that was sent early this morning (14 Feb). The
links file has ~21,000 links, and the latest linked publication I could
find was from 2019.

So I don't think you'll need to worry too much about our documentation;
perhaps it's some change in your infrastructure in 2019 that means newer
records aren't being retrieved to generate the links file?

**Comment by ryscher** [comment]
Updated the process and re-ran. The links file now has recent content and a total of 25,058 links.
