### ISSUE TITLE
Do we need a longer field length for stash_engine_internal_data?

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1654]
![Screen Shot 2022-02-14 at 1 34 45 PM](https://user-images.githubusercontent.com/105433/153952259-c09b73f9-195a-4904-aa66-881cee57c65d.png)

**Comment by ryscher** [comment]
LOL, no. This was a request to store the journal title. They can't put a whole manuscript in there!
