### ISSUE TITLE
Enforcement of 1,000 file limit in file upload page

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1655]
Apparently, we lost all enforcement of the 1,000 file limit in the file upload page with that reworking.  We do enforce the limit on the review page, but by then it's too late because it causes us problems displaying the page.  It takes too long to display 15,169 items and makes the review page unusable.

A user uploaded 15,169 individual files.  Resource id: 161834 .

(User has since created a different dataset with zipping files, so this dataset is now deleted.)

**Comment by ahamelers** [comment]
Hi @sfisher, do any of the errors defined in `app/models/stash_datacite/resource/dataset_validations.rb` activate now on the file upload, or do they all generally need to be imported to the new react upload files page?

**Comment by sfisher** [comment]
The validations in the file you mention run on the review page and may can prevent submission if something is wrong.

Originally we had a check on the file upload page itself that checked size and number of files and disallowed and warned people.  One advantage of doing it on the upload page is that people don't have to spend a little to a lot of time uploading the files before they're told that they'll be exceeding the limits.  I know we get the number of files before they're actually uploaded (and filenames and things).  We might also get size as part of the metadata (don't remember 100%).

The check got lost when the page got redone but it would be nice to re-instate it.

It's kind of an edge case and I don't think very many people try to upload more files (or larger size) and so hasn't been all that critical to fix but it's a "nice to have" to enforce earlier in the process.  BTW, our limits for data files is 300 GB and 50GB each for software and supplemental information.

**Comment by ahamelers** [comment]
This is done, but based on the react-reorg branch, so I'll stash it until that one is merged to main.
