### ISSUE TITLE
Associate Michael Russello’s profile with The University of British Columbia tenant

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1662]
Please tie Michael Russello’s profile with The University of British Columbia 
Email: michael.russello@ubc.ca
ORCID ID: 0000-0002-9297-2485

Is it also possible to note his previously published datasets should be sponsored or should we work to void each invoice instead? The author noted the following;

"When I submitted the data, each time it indicated that costs were covered by my institution. I have had a number of submissions in the past few months, so I hope this can be resolved."

Is it possible his account is already associated with the tenant?

**Comment by ryscher** [comment]
Account is currently associated with UBC. 

The user has submitted many datasets over the years with various payments associated. Will message separately about which ones should be modified.

**Comment by Ariana-Orona** [comment]
Thank you! @ryscher
