### ISSUE TITLE
Update workflow rules for journal titles (GMS & Wiley)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1664]
Please create new workflow rules for the following journal titles listed below. 

NEW RULES: 
1) All new datasets received should automatically be placed in PPR status upon submission. 
2) The current workflow rule in place to auto-embargo published datasets for these titles should be eliminated. 
3) When accept notifications are received from these journal titles, PPR status should be automatically lifted and the dataset should move to "Submitted" status (Note: Any need to confirm that notifications are received from these titles, first?)

> GMS German Medical Science
> GMS Hygiene and Infection Control
> GMS Infectious Diseases
> GMS Interdisciplinary Plastic and Reconstructive Surgery DGPW
> GMS Journal for Medical Education
> GMS Journal of Arts Therapies
> GMS Medizin - Bibliothek - Information
> GMS Medizinische Informatik, Biometrie und Epidemiologie
> GMS Onkologische Rehabilitation und Sozialmedizin
> GMS Zeitschrift fur Audiologie
> GMS Zeitschrift zur Forderung der Qualitatssicherung in medizinischen Laboratorien
> Diversity and Distributions
> Ecology and Evolution
> Environmental DNA
> Evolutionary Applications
> Global Ecology and Biogeography
> Journal of Biogeography
> Molecular Ecology
> Molecular Ecology Resources
> Global Change Biology (GCB)
> GCB-Bioenergy (GCBB)

Please note, the embargo information will need to be updated on [this](https://datadryad.org/stash/journals) page. Additionally, the following journals have been discontinued, so there won’t be any submissions for these and we can remove them from our journal list online:

> - GMS German Plastic, Reconstructive and Aesthetic Surgery
> - GMS Health Technology Assessment
> - (GMS Health Innovation and Technologies is the successor of GMS Health Technology Assessment.)

**Comment by ryscher** [comment]
Comments on the new rules:
1. Datasets may be received after an article is published. In this case, we won't want to just blindly send the dataset to PPR. I propose we default the PPR checkbox to be checked for these journals, but we leave it enabled for the user to uncheck if needed.
2. Rule 2 is fine, and is a simple configuration change for these journals.
3. Rule 3 is already in place for all journals.
4. As far as I can tell, these journals are sending us metadata notices.
