### ISSUE TITLE
Create Dryad accounts for new hires

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1668]
Please create Dryad email accounts for the following new hires: 

> Arian Abdulla: arian@datadryad.org
Email: aabdulla.arian@gmail.com
> 
> Carolyn Tarpey: carolyn@datadryad.org
Email: ctarpey@uw.edu 
>
> Savannah Butler: savannah@datadryad.org
Email: skbutler@alumni.stanford.edu

If you need more information,  let me know.

**Comment by ryscher** [comment]
Created Google accounts and set users messages to activate the accounts.
