### ISSUE TITLE
Author tries to click "update" on published dataset and get error message that typically appears when you click "back"

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1669]
In dashboard, Author goes and clicks "update" on published dataset https://doi.org/10.6071/Z7WC73 and an error message appears (the one that appears if you start a new version and click 'back') not letting him make updates to the dataset

**Comment by ryscher** [comment]
This dataset had some strange issues. It appears correctly in Merritt, but Dryad never set the item back to 'submitted' status, so I had to force it. There is a mismatch between the Dryad version number and Merritt version number, so there was definitely a problem in the past. 

I have updated the version and set it to AAR status, so the author should now be able to edit it again. However, after the author resubmits, we may need to force it through again.
