### ISSUE TITLE
Associate Gail Schwieterman’s profile with University of California, Santa Barbara tenant 

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1670]
Please tie Gail Schwieterman’s profile with University of California, Santa Barbara tenant 
Email: gschwieterman@ucsb.edu
ORCID ID: 0000-0001-6356-0337

**Comment by ryscher** [comment]
Updated

**Comment by Ariana-Orona** [comment]
Thank you @ryscher!
