### ISSUE TITLE
Curators experiencing issues using Matlab in the virtual environment

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1671]
When attempting to view MATLAB files, the following error message is generated:
![image](https://user-images.githubusercontent.com/80363462/155445782-ce3cf223-579b-429a-935c-172609bc8d26.png)

**Comment by jleighherzog** [comment]
![image](https://user-images.githubusercontent.com/76497320/157161855-201cf59e-829b-4c45-b981-0d9a671279ac.png)

**Comment by ryscher** [comment]
We only have a single-user license for Matlab. This license is assigned to the "Curator" account. All curators should have the password for this account, so they may use it when they are curating a dataset that requires Matlab.

**Comment by ryscher** [comment]
@Ariana-Orona @jleighherzog Is this still a problem?

**Comment by Ariana-Orona** [comment]
@ryscher I remember you mentioned this in training. Can you remind me how to access this profile? I'll work to establish documentation for current and future ve users.

**Comment by ryscher** [comment]
I discussed with Ari and helped her connect to the Curator account. She will update documentation so the other curators can access it as well. Let me know if anything else is needed.
