### ISSUE TITLE
Create Dryad account for new hire

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1676]
Please create a Dryad email account for the following new hire:

> **Amelia Culp**
> Personal email: culpa@ohsu.edu
> Suggested Dryad email: amelia@datadryad.org

Once set up, I'll ask Amelia to log into our system to confirm access. If you need more information, let me know.

**Comment by ryscher** [comment]
- Created Google account
- Invited to Slack
- Sent instructions for accessing these accounts
