### ISSUE TITLE
Additional VE licenses 

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1680]
Please purchase additional licenses for the virtual environment (VE) to allow more than 2 curators to work in that space concurrently. 

As we are hiring 4 additional curators, and seeing larger datasets that require the VE for curation, I anticipate that there will be overlap in use of the VE. I'd like to request to allow 3 users at the same time. If there's a need for more, I'll submit a new ticket. 

Additionally, please install "license manager" software.

**Comment by ryscher** [comment]
The license manager is set up. Waiting for Mark/Jen to finalize purchase.

**Comment by ryscher** [comment]
New licenses are installed. We should not have to worry about this in the future.
