### ISSUE TITLE
Revert submission to previous status (DOI: 10.5061/dryad.9s4mw6mj5)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1681]
This dataset was published in error. Please revert to "Curation" status. 

Title: dataset-EGSAV
DOI: 10.5061/dryad.9s4mw6mj5

**Comment by ryscher** [comment]
Reverted to curation status in Dryad, made invisible at Zenodo and Datacite.
