### ISSUE TITLE
Associate submitting author's account with correct tenant 

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1683]
Please associate author's profile below with the correct UCSB tenant (see related dataset info). 

Submitting author: Juan Carlos Villaseñor-Derbez
ORCID ID: 0000-0003-1245-589X
Email: juancarlos@ucsb.edu

Title: Data for: Evaluating conditions for MFAD fisheries development in the Caribbean and Bermuda
DOI: 10.5061/dryad.3r2280gj3

**Comment by ryscher** [comment]
Updated author's tenant and payment settings on the specified dataset.

**Comment by jleighherzog** [comment]
Should we mark this as complete?
