### ISSUE TITLE
Migrate author profile to published dataset

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1684]
I believe the dataset referenced below was migrated over from the previous system and there's no author attached to it. This author wrote in asking to have their account information linked to the dataset. 

Name: Keizo Takasuka
Email: keizaf@gmail.com
ORCID: 0000-0001-8386-1292

Title: Data from: Host manipulation by an ichneumonid spider ectoparasitoid that takes advantage of preprogrammed web-building behaviour for its cocoon protection
DOI: 10.5061/dryad.3bf67

Let me know if you need more info.

**Comment by ryscher** [comment]
User had two accounts and the "other" account was attached to the dataset. I merged them, so he should now have access to the dataset.
