### ISSUE TITLE
Update email address for Dryad notifications to Entomological Society of America

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1693]
Josh Lancette, Managing Editor, Entomological Society of America has requested that all Dryad notifications be delivered to this email address: **pubs@entsoc.org** for the following journal titles: 

- Annals of the Entomological Society of America
- Environmental Entomology
- Insect Systematics and Diversity
- Journal of Economic Entomology
- Journal of Insect Science
- Journal of Medical Entomology

Here's an example of the notification received by the journal office: 
> Subject: Dryad Submission: "Reproductive ecology of Drosophila obscura: A cold adapted species"
> 
> The dataset "Reproductive ecology of Drosophila obscura: A cold adapted species" has been approved for publication in Dryad.
> 
> Data DOI: doi:10.5061/dryad.2v6wwpzqg
> Journal: Environmental Entomology
> Journal manuscript number: ENVENT-2021-0239
> Article DOI:
> 
> We welcome your feedback! Contact us at [help@datadryad.org](mailto:help@datadryad.org).
> 
> Please do not reply to this email.
> 
> The Dryad Team
> 
> https://datadryad.org/

**Comment by ryscher** [comment]
These addresses have been updated.
