### ISSUE TITLE
Dryad Admin site column data update

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1695]
Within the search results on the Dryad Admin site, there's a column for "Size". This field captures the _total size_ for all versions submitted. 

It would be beneficial to display the _actual size_. At a glance, it will help curators budget their time and adjust their approach to datasets. Because the actual size will always be smaller when multiple versions exist, datasets will less likely be skipped or saved for another time or space (i.e. the virtual environment). 

Is it possible to add both the total size and current version size to the "Size" column? 
Alternatively, add a new column or replace the existing column to display "Size (current version)"?

**Comment by ryscher** [comment]
Check whether it is complete only.

**Comment by ahamelers** [comment]
> What does this mean? "One possible approach to mitigate these issues is adding a new field in the resource to store the size." Add another column to the dashboard?

@jleighherzog This means adding another column to store this information in our database, which would take a much larger effort to set up, but would retain the ability to quickly query the database for this information and sort the table on size.

**Comment by ahamelers** [comment]
@ryscher 

This check is in /stash_api/files_controller.rb and is also using the Merritt total storage size:

```ruby
def check_total_size_violations
      return if @resource.new_size <= APP_CONFIG.maximums.merritt_size && @resource.size <= APP_CONFIG.maximums.merritt_size

      (render json: { error:
                          'The files for this dataset are larger than the allowed version or total object size' }.to_json,
              status: 403) && yield
 end
```

Should it also be changed to use the current resource size?
