### ISSUE TITLE
Duplicated institutions included on dataset landing page

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1710]
The following dataset(s) contain duplicated institution affiliations which are noted to be selected from the drop-down list and not duplicated on the Dryad "Describe Dataset" page.

- **10.6078/D1KD93**	
Affiliations not yet updated.

- **10.5061/dryad.gf1vhhmqn**
Affiliations not yet updated.

- **10.5061/dryad.mgqnk990p**	
Affiliations were updated by selecting another institution from the drop-down list, navigating to the "Review and Submit" page, and returning to the "Describe Dataset" page to reselect the correct institutional affiliation. Institutional affiliations were previously included as shown below:

![image](https://user-images.githubusercontent.com/80363462/159954682-abaa1f5c-bca5-4f27-af60-9a0dd39760d6.png)

Institutional affiliations should only be included once when selected from the drop-down list. Can you please review this and let me know if you need more information?

**Comment by ahamelers** [comment]
Duplicate issue https://github.com/CDL-Dryad/dryad-product-roadmap/issues/3025
