### ISSUE TITLE
Curators unable to use Microsoft Office (read-only) to view files 

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1711]
When attempting to view a data file using Excel, curators are currently unable to view the data file as "Read-Only" (screenshot included below).

![image](https://user-images.githubusercontent.com/80363462/160203615-e1570b27-c59c-491e-8e7a-ecb2fa5b2a8f.png)

We do not currently have a Microsoft Office license for the virtual environment but, previously, curators were able to view the data files as "Read-Only". From the screenshot, it appears Microsoft Office is unavailable in the virtual environment.

**Comment by ryscher** [comment]
No longer relevant.
