### ISSUE TITLE
Dataset version fails duplication with invalid author

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1736]
Every new version of a dataset is duplicated from the previous one.  Duplication fails if the author has two email addresses smashed into one email field.

It looks like the dataset I saw came from editorial manager. 10.5061/dryad.1c59zw3xp

Either reject that from being put in (did it come from the API)? Or else loosen rails validation on duplication without  so that people can edit it.

**Comment by ryscher** [comment]
This was fixed by https://github.com/CDL-Dryad/dryad-app/pull/499
