### ISSUE TITLE
Update settings for The University of Chicago Press

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1749]
- International Journal of Plant Sciences (in the system now)
- Physiological and Biochemical Zoology (please add)
- The American Naturalist (please change from the American Society of Naturalists as sponsor to The University of Chicago Press)

Can we please change 'University of Chicago Press' to 'The University of Chicago Press' too?

**Comment by ryscher** [comment]
Updated these journals to the correct sponsor. I'm assuming the desired payment plan is Subscription.
