### ISSUE TITLE
Something setting publication date prematurely

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1753]
(was Versions of dataset listed in incorrect order on landing page )

Something seems to set a publication date before an item is published and but doesn't take any additional publication steps.  If premature publication dates are part of a normal process then we should probably document them and also update landing page display so it doesn't look bad to curators and users.

Curators mentioned
- doi:10.5061/dryad.hmgqn9jk

I saw
- doi:10.5061/dryad.t513409

I spot checked about 20 others with multiple versions and they were all ok.

They said that the files were also not correct for the dates listed.  We usually list dates in chronological ascending order and these *looked* descending.  But it turns out to be the correct versions with just a wrong date displayed.

**Comment by jleighherzog** [comment]
Can you help us confirm that it's safe to publish this dataset? 

> 10.5061/dryad.hmgqnk9jk "Conflict over the eukaryote root resides in strong outliers, mosaics and missing data sensitivity of site-specific (CAT) mixture models"

When the option to select "Download dataset" is selected, the correct version downloads (the one that should be published). However, it lists the date of April 12 (a newer version with outdated files is available). There is a publication date of April 12, 2022 in the 'Publication Date' column -- but it has yet to be published. 

Here's the complete breakdown from Carolyn. 

Issue: A dataset that an author resubmitted overnight with all the requested edits addressed, has a timestamp for the new, updated data files that is earlier in time (April 12, 2022) than the original one (April 26, 2022).

Timeline:
04/26/2022 14:47:04 UTC Carolyn curates data set and requests author edits- Author action required
04/28/2022 12:51:04 UTC Author resubmitted, including new README file, and uploading some files to Zenodo
04/28/2022 Carolyn looks at the resubmitted dataset and there are two dates for the data files. The original set with files that should have been submitted to Zenodo and a subpar README are dated April 26, 2022 a second data set with fewer files and an updated README is dated April 12, 2022. Hitting the download dataset button downloads the April 12, 2022 most up-to-date files; The April 12, 2022 version of the files should be published.
