### ISSUE TITLE
Withdraw "In Progress" dataset which was not previously submitted

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1757]
Please change the status of dataset 10.5061/dryad.stqjq2c5d to "Withdrawn" as the author will submit their software to Zenodo directly. I am unable to "Cancel and Discard" changes because the dataset has not been submitted previously.

**Comment by sfisher** [comment]
I see what you mean about an unsubmitted dataset and manually set to withdrawn.
