### ISSUE TITLE
Link to software file not appearing in published datasets

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1761]
A code file was uploaded to the 'Software' section on the 'Upload Files' page of the submission form for these data submissions: 

> DOI:  10.5061/dryad.zgmsbccdf
> DOI: 10.5061/dryad.bcc2fqzdq
> DOI: 10.5061/dryad.41ns1rnh5
> DOI: 10.25349/D9C601

On the 'Review and Submit' preview page, the Zenodo file appears BUT, upon publication, there is no Related Works section on the main dataset page that includes a link to the file on Zenodo. 

<img width="337" alt="image" src="https://user-images.githubusercontent.com/76497320/166775385-9908cb41-3cc0-49a5-a6c2-0c065a2c4e36.png">

<img width="1227" alt="Screen Shot 2022-05-04 at 1 07 36 PM" src="https://user-images.githubusercontent.com/76497320/166781280-032f0770-79be-4c02-a40b-5ec00819faae.png">

**Comment by ryscher** [comment]
All of the listed items are now showing the Zenodo links. There are often errors/delays when transferring content to Zenodo, so content may take several days to be processed.
