### ISSUE TITLE
Add programs to virtual environment

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1764]
Please add the following programs to the VE: 

- Panoply (this is included in the list [here,](https://docs.google.com/document/d/1j2jez4IXqUjBgZDHrTaqcHxBJvMRkMjV-nKqGGgKPpI/edit) but Jeremy mentioned he's unable to find it in the VE; (uses it for .hdf files)
- ArcGIS Desktop
- FIJI (ImageJ)

**Comment by ryscher** [comment]
These applications are available from C:\DryadData\SoftwareShortcuts

I verified that they all run from a normal user account, but let me know if there is a problem opening files. (FIJI does show an error loading one of its plugins, I could invest more time in this if needed.)
