### ISSUE TITLE
Check out changes to CEDAR

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1766]
Documentation: https://github.com/metadatacenter/cedar-embeddable-editor/tree/develop 

They made changes for auto saving the metadata and paging

**Comment by ryscher** [comment]
The new updates look great! 
- They added a customTemplateInfo that will let us pass information into and out of the editor, which will be helpful for associating the CEDAR metadata with its associated object in Dryad.
- They added read/write capabilities for the primary metadata in the editor, so when someone versions a dataset, we con populate the editor with the metadata that was previously submitted.
- They greatly expanded the documentation, explaining how to use the editor in various contexts.
