### ISSUE TITLE
Update to sponsored journal title 

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1767]
Please remove _Ecosphere_ as a sponsored title in the Dryad site and update the[ journal page](https://datadryad.org/stash/journals).  

Authors submitting datasets linked to this title will be invoiced for the DPC. Existing submissions in these statuses = "Curation", "Author Action Required", "Submitted", or "Private for Peer Review" that have not yet been previously published and are noted to be sponsored by "Ecosphere" should have their sponsorship removed. Possible to update all to remove the association? If so, is there a way to also send an auto-notification to inform all submitting authors of the change?

**Comment by ryscher** [comment]
- Journal settings are now updated.
- There were 24 datasets that had not been published and were going to be charged to Ecosphere. I reset the payment info for 22 of them, so the author will be charged. The remaining 2 will be covered by member institutions.
- The 22 datasets that will incur charges are listed here with author email addresses, so you can send a mail merge: https://docs.google.com/spreadsheets/d/1Re1QSJiH1CjjKzqUlptyU2Jb6zgEh2AXGjgFrm07bdg/edit?usp=sharing
