### ISSUE TITLE
Configure Dryad site to open links in new tabs/windows

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1769]
In the Activity Log of any dataset, when a hyperlink is selected (see Salesforce Cases), the related Salesforce case will open in a new window. When you return to the Activity Log to select a different Salesforce case, it will open in the pre-existing tab/window instead of a _new_ tab). The same also happens when the hyperlinked title of a dataset is selected from the Dryad Admin view when there are multiple tabs open. 

This can be problematic because, oftentimes, curators are in the middle of processing a download which will be canceled if/when a new page opens in that tab. Of course, right-clicking a mouse to open links to a page in a new window is the known workaround but a fix would be better. 

Here's an example of a dataset with multiple Salesforce cases: 10.5061/dryad.d7wm37q2z

Note: The same also happens when the hyperlinked title of a dataset is selected from the Dryad Admin view when there are multiple tabs open.

**Comment by ryscher** [comment]
In both cases, this looks to be the result of a simple typo. The links have `target="blank"`, when it should be `target="_blank"`
