### ISSUE TITLE
Transfer dataset to corresponding author's account (10.5061/dryad.pc866t1rh)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1776]
This one is a bit messy. 

Currently, "Dryad System" is designated as the corresponding author and linked to this ORCID ID: 0000-0002-0030-2784. I used the Force Edit option to reach editing mode in an effort to properly link the appropriate author. However, this ID belongs to a contact who should not be associated with the submission. 

I'm unable to remove Dryad System from the author line. 
Can you remove it and associate this submission with the true corresponding author: 

> Joseph Travis 
> 0000-0002-2419-5020 
> travis@bio.fsu.edu

Title: Population regulation and density‐dependent demography in the Trinidadian guppy
DOI: 10.5061/dryad.pc866t1rh

If you'd prefer to talk through this one with me, let me know.

**Comment by ryscher** [comment]
I removed the corrupted author entry and set the owner to the correct author.
