### ISSUE TITLE
Update auto-assignment for revised or versioned datasets

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1777]
For data submissions that are resubmitted from AAR status (revised) or resubmitted post-publication (versioned), these submissions are currently auto-assigned to the longest-serving curator (who is not a superuser) IF/WHEN the previous handling curator is no longer at Dryad.

Can you update the workflow rule for these submissions so that they are auto-assigned randomly among _all_ current curators vs auto-assigned to a single curator? 

_Note: Any revised or versioned submissions that are auto-assigned to John C should also be randomly assigned to current curators._

**Comment by ryscher** [comment]
This process happens in the function `auto_assign_curator`

**Comment by Ariana-Orona** [comment]
@ryscher Bringing this to your attention

https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=%22Breast+cancer+patients%C2%B4knowledge%3A+Results+of+EORTC+QLQ30%2C+QLQ-INFO25+and+HADS%22&sort=relevance&commit=Search&utf8=%E2%9C%93

Sarah was assigned this case, although she does not perform curation. Can you investigate and modify auto-assign to update the rules to only assign to curators? I can send you a list, if you like.

**Comment by ryscher** [comment]
I wasn't aware that Sarah and Donna had been assigned as curators. We may need to create a new category of users if there will be people who need to view information but not actually curate it. Can you describe what information they need?

**Comment by jleighherzog** [comment]
@ryscher : You might also check John C's role too so that submissions aren't assigned to him. I don't know what info Donna and Sarah need. I will ask them and follow up here.
