### ISSUE TITLE
Return dataset to PPR status (10.5061/dryad.tb2rbp031)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1779]
Please place this dataset in 'Private for Peer Review' status, removing the data from public view. 

Curator error.

**Comment by ryscher** [comment]
This dataset is now in Private for Peer Review status.

**Comment by jleighherzog** [comment]
@ryscher : The current status of this submission is "In Progress". Possible to update to "Private for Peer Review"?
