### ISSUE TITLE
Import Metadata feature not working for noted dataset(s)

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1781]
A user is unable to utilize the "Import Metadata" feature when submitting a dataset related to the Journal of Ecology.

DOI: 10.5061/dryad.x3ffbg7n5	
Title: "Some neighbors are better than others: variation in associational effects among plants in an old field community"
Manuscript Number: JEcol-2021-1085

**Comment by jleighherzog** [comment]
@ryscher : This ticket can be closed.
