### ISSUE TITLE
PPR option is selected but isn't applied

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1782]
There are several datasets that have been submitted, curated, and published. However, the submitting authors have reported these datasets should not have been processed because they are certain that they selected the 'Private for Peer Review' option on the final page of the submission form. Because this is occurring with multiple submissions, please investigate. I'll continue to add more DOIs for impacted submissions here:

10.5061/dryad.x3ffbg7n2
10.5061/dryad.wdbrv15rc
10.5061/dryad.x95x69pmd
10.5061/dryad.2z34tmppq

These submissions should be placed in 'Private for Peer Review' status and the data files removed from public view.

**Comment by ryscher** [comment]
Fixed by https://github.com/CDL-Dryad/dryad-app/pull/851

**Comment by ryscher** [comment]
All datasets listed above have been moved to Peer Review.
