### ISSUE TITLE
Curator VE: Access files downloaded to the virtual environment on personal device

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1784]
Software available within the virtual environment and curators' personal devices can vary. Due to this, curators perform secondary checks to ensure that the software needed to open dataset files due not require proprietary software to open and/or the program needed to view the files is freely available by downloading certain folders to their personal device after the initial review and download that occurred within the virtual environment.

This process duplicates efforts and adds time to the overall curation process. To overcome this, it would be helpful to allow curators to access files downloaded in the virtual environment.

Is there a way curators can access and open the files downloaded onto the virtual environment from their personal devices?

**Comment by ryscher** [comment]
I discussed with Amelia. The primary use case is: 
- Author submits a large zip file
- Curator downloads the zip file onto the VE
- One of the files from the zip requires analysis that is best done on the curator's personal machine
- Curator wants to download that single file from the VE to their personal machine.

Proposed solutions:
- (preferred) Install SSH server onto the VE, which will use the Windows accounts. It appears this is possible, though the Windows users will need to be added to a Unix-style passwd file -- see https://www.itprotoday.com/windows-78/ssh-windows
- (fallback) Install Apache server onto the VE, and make the files available in a manner similar to the Apache on the FTP server.

**Comment by ryscher** [comment]
I was unable to get the SSH server to work. Instead, I set up a web server, which can be used to transfer individual files. 

To transfer files, copy the file you want into `C:\DryadData\PublicWebfiles`, and this file will then be available from other
computers at via a web browser. For example, the file `C:\DryadData\PublicWebfiles\myfile.txt` will be available at `http://curator.datadryad.org/myfile.txt`. Please delete files from `PublicWebfiles` after they are no longer needed.
