### ISSUE TITLE
Migrate account for Seth Bigelow (0000-0002-0052-191X) 

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1785]
Please associate Seth Bigelow's email with the 0000-0002-0052-191X provided below:

Orcid ID: 0000-0002-0052-191X
Current email: sethw.big@gmail.com
Previous email: seth.bigelow@jonesctr.org

**Comment by jleighherzog** [comment]
@dlowenberg : I merged this account but failed to retain the preferred/current email address: sethw.big@gmail.com
Can this be updated?

**Comment by ryscher** [comment]
Updated
