### ISSUE TITLE
Place dataset in PPR status (DOI: 10.5061/dryad.pc866t1rg)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1787]
This dataset has been submitted, curated, and published because the 'Private for Peer Review' option failed to be applied upon submission. 

Please place the dataset in 'Private for Peer Review' status and remove data files from public view: 10.5061/dryad.pc866t1rg

**Comment by sfisher** [comment]
Ok.  I updated this one.
