### ISSUE TITLE
Github: Move configuration repo from cdlib to CDL-Dryad

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#179]
Now that Github allows private repositories in non-premium accounts, we can move the configuration repository to the same organization as the rest of the code.

(We need to consider if only having three user access is permissible.  For more than that, they still require paid.)

- [ ] Copy the repository into the new location
- [ ] Update deployed copies of the repository to have the correct "git remote" settings 
- [ ] Update the documentation/config for the vagrant machines

**Comment by sfisher** [comment]
I'm also not sure how deployment keys are affected or if limited.  I think each of our environments uses a deployment key for accessing the private repo.

**Comment by ryscher** [comment]
No longer relevant. We absorbed the `dryad-config` repo into the main `dryad-app` repo long ago.
