### ISSUE TITLE
Update user profile

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1795]
Please update this user's profile to associate their Dryad account with the preferred email address (I'm unable to do this): 

> Pang-Ning Tan
> 0000-0003-3205-0339
> ptan@msu.edu

Dataset info: 
Title: Twitter vaccine misinformation data
DOI: 10.5061/dryad.d51c5b05j

**Comment by ryscher** [comment]
updated
