### ISSUE TITLE
Update user's account

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1796]
We had updated this user's account in ticket #1795. However, the author is still required to acknowledge responsibility for the data publication charge on the final page of the submission form. Maybe the author selected the incorrect tenant? Michigan State University should cover the DPC. 

Can you investigate? 

Pang-Ning Tan
0000-0003-3205-0339
[ptan@msu.edu](mailto:ptan@msu.edu)

Dataset info:
Title: Twitter vaccine misinformation data
DOI: 10.5061/dryad.d51c5b05j

**Comment by ryscher** [comment]
Tenant setting updated for the user and associated dataset.. Sorry, in #1795, I didn't recognize that MSU was a member institution, so I had left the default tenant in place.
