### ISSUE TITLE
[Waiting on Author] Transfer ownership of dataset (DOI: 10.5061/dryad.f1vhhmgzh)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1797]
Please transfer ownership of this dataset **10.5061/dryad.f1vhhmgzh** to this author's Dryad account: 

Shuko Nojiri
ORCID ID: 0000-0003-0422-8152
Email: s-nojiri@juntendo.ac.jp

_Note: Rie Kanamori should remain the first author_

**Comment by ryscher** [comment]
Shuko Nojiri has never logged in to Dryad. Please have them log in to initialize their account so we are able to transfer ownership.

**Comment by ryscher** [comment]
Also, note that Dryad treats the "owner" and "corresponding author" as the same person. If ownership is transferred, Rie Kanamori will no longer be the corresponding author. Can you clarify this with the authors?

**Comment by jleighherzog** [comment]
@ryscher : Oops. I wrote it incorrected. I meant Rie should remain first author. I corrected the text in the ticket.

**Comment by jleighherzog** [comment]
Sent reminder to author w/request to login

**Comment by ryscher** [comment]
Author still has not logged in. Seems like it's not that important for them to own this dataset....

**Comment by jleighherzog** [comment]
Sent reminder to author w/request to login

**Comment by ryscher** [comment]
Setting this aside until the author gets back to us.
