### ISSUE TITLE
Add new programs to the virtual environment

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1798]
Please add these programs to the virtual environment: 

1. **GraphPad Prism**
2. **VLC** 
3. **SPIERS**: https://github.com/palaeoware/SPIERS/releases/tag/v3.1.0 (unless someone knows another way to view .spv / .spvf files)

Re: GraphPad: If you have any questions please connect with curator, Savannah Butler.
> "Looks like from the “software” Google doc that it's a free trial for one week, then changes to view only (which is all we'd really need). It requires an email associated with it, but I assume we could get it for the curator profile in that case. I've found .pzfx files in two or three submissions in the last two weeks, and haven't been able to open them with other software that I'm aware of."

**Comment by sfisher** [comment]
Ok.  I installed these and also added copies of the shortcuts to the C:\DryadData\SoftwareShortcuts directory.  @ryscher I'm not sure if there was anything else I needed to do for these to show up for all users.
