### ISSUE TITLE
Adding EFS mount point to the UI Stage

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#181]

**Comment by jimvanderveen** [comment]
Shared EFS mountpoint for Dryad stage UI servers is `/apps/dryad-stg-shared`
This is attached to the uc3-dryad-stg instance. There are no backups or snapshots on this content. If that is needed, please let me know. IAS cannot use the existing snapshot capability on EFS devices, but they have other options if backups are necessary.

**Comment by jimvanderveen** [comment]
Should this ticket be held open until we get the second UI node set up, @dlowenberg ?

**Comment by jimvanderveen** [comment]
Closing this ticket, and adding an EFS task to the ticket for 2nd UI server.
