### ISSUE TITLE
Associated Niels Van Steenkiste with the University of British Columbia tenant

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1814]
Please tie Niels Van Steenkiste profile with the University of British Columbia 
Email: niels_van_steenkiste@hotmail.com
ORCID ID: 0000-0002-2676-7862

**Comment by jleighherzog** [comment]
[FYI] I don't think I'm able to take action on this ticket because I don't have access to update/edit the email address. 

<img width="1092" alt="Screen Shot 2022-06-09 at 1 59 38 PM" src="https://user-images.githubusercontent.com/76497320/172923817-5dde85c6-b0f1-4b98-9ca3-ebf15729d531.png">

**Comment by sfisher** [comment]
Ok.  Updated and also combined accounts.
