### ISSUE TITLE
Reduce email noise for curators related to help@datadryad.org

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#1816]
*Issue*
Jen has asked that the [help@datadryad.org](mailto:help@datadryad.org) be changed to [hello@datadryad.org](mailto:hello@datadryad.org) Apparently, help@ is used by various entities to get in touch with Dryad, and that adds noise for curators.

*Solution*
TBD: Per Ryan, "this warrants a discussion. We have been advertising help@ for 14 years, so it’s going to take a long time to change everyone’s behavior, and we will need a plan for someone to sort through both addresses for the next few years.

For the “various entities”, some of those are probably things that we manually signed up, and could be changed.
New

We might be able to improve the behavior by building some automatic processing rules into Salesforce.

**Comment by ryscher** [comment]
@jleighherzog says this is no longer relevant.
