### ISSUE TITLE
Deleted file still shows when dataset is downloaded

### ISSUE THREAD

**Issue by rcurty** [CDL-Dryad/dryad-product-roadmap#1818]
Dataset: 10.25349/D9SC9W	
The old README file still downloads even though it was removed from the upload file tab. 
Please remove "README_2022_The_Household_Context_of_In_Situ_Conservation_in_a_Center_of_Crop_Diversity_in_Oaxaca__Mexico.pdf"
and keep only "README.pdf"

**Comment by sfisher** [comment]
Thank you, @rcurty .  This is fixed.
