### ISSUE TITLE
Add a second UI stage instance

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#182]

**Comment by jimvanderveen** [comment]
I spoke with Debra about a second UI server (while working on #181 ). Our current stage UI server is Linux 1, but they are not provisioning only Linux 2 nodes. Linux 2 requires that we upgrade to Apache 2.4 (currently we are on 2.2)

I can request the second UI node so we can get started on Apache 2.4 conversion. I don't expect that to be too difficult, but it's an additional issue that should probably go on the tracker @dlowenberg

**Comment by marisastrong** [comment]
I spoke with IAS and we can continue with Linux1 server unless we want to delay work and move to Linux2.  This would require dev environment to be moved to Linux2 prior.  Need to decide on naming for this new server.

**Comment by jimvanderveen** [comment]
(NB: I'm looking over this after writing it, and it seems confusing to me. Maybe we should discuss this at standup tomorrow.)

I spoke with Debra about naming (as well as Linux1) today. She'd like us to request *both* the Linux1 name(s) along with the future Linux2 server names -- this would allow her to do a single certificate request, which wouldn't need to be redone when we get around to migrating to Linux2 later.

We also need to include the Internet-facing name for the load balancer. Currently we have a single UI server named `uc3-dryad-stg` which has an alias `dryad-stg`. We should move the `dryad-stg` name to the "outside" of our load balancer (once the ALB is set up).

For instances behind a load balancer, IAS is now using a numeric suffix plus a 1-lettter code to indicate the AWS Availability Zone (AZ) hosting that instance. For example, Linux1 names might be `uc3-dryadui-stg-1A` for the first server, with  `uc3-dryadui-stg-2c` as the second. As previously discussed, IAS will be adding a '2' after the middle part of the host name when that service is migrated to Linux2. The server names above would become `uc3-dryadui2-stg-1a` and  `uc3-dryadui2-stg-2c` (assuming they stayed in the same AZ's as before).

Does the team want to stick with 'dryad' as the service name, or switch to 'dryadui'? In other words,
uc3-dryadui-stg-1a or
uc3-dryad-stg-1a?

**Comment by jimvanderveen** [comment]
![dryad_alb_diagram](https://user-images.githubusercontent.com/6509071/52278629-54c42d80-290c-11e9-9add-bdaa4ca21b74.jpg)

**Comment by jimvanderveen** [comment]
Discussed in the standup today. We will go with the `uc3-dryadui...` names.

**Comment by jimvanderveen** [comment]
Debra informed me that the entire `-2a` suffix (for example) is part of the Availability Zone. Most (all?) of our instances are in US-WEST, with `-2a` referring to US-WEST-2A zone. US-WEST-2x is our cheapest option, so I'll be requesting (eventually) 4 instances named `uc3-dryadui{,2}-stg-2{a,c}`.

**Comment by jimvanderveen** [comment]
`dryad-stg.cdlib.org` currently points to `uc3-dryad-stg.cdlib.org`
`dryad2-stg.cdlib.org` points to the ALB (which doesn't work yet).

**Comment by jimvanderveen** [comment]
The load balancer control script is showing the dryad-stg ALB. Currently reporting "unhealthy", because I am still setting up the vhost.

`./load-balancer.bash uc3-dryadui-stg-alb`

**Comment by jimvanderveen** [comment]
DNS names on the new certificate, including ALB and Linux2 names
```
cn = dryad-stg.cdlib.org
alternate subject names: 
DNS:dryad2-stg.cdlib.org (in case we need it for a second load balancer during Amazon Linux 2 migration)
DNS:uc3-dryad-stg.cdlib.org DNS:uc3-dryadui-stg-2c.cdlib.org (Amazon Linux 1 host names)
DNS:uc3-dryadui2-stg-2a.cdlib.org, DNS:uc3-dryadui2-stg-2c.cdlib.org (Amazon Linux 2 host names)
```

**Comment by jimvanderveen** [comment]
ALB permissions fixed this morning. Debra suggests that the first test we do with a new ALB/host is to go through register/deregister/re-register, to verify tags and permissions are set correctly.
We also discussed https/http -- we can have one or the other between ALB-host. Since so much of Puppet config is hard-coded for https, we decided to use that. Localhost can still use http, e.g. for passenger:3000, so @sfisher doesn't have to deal with https for that.

I have a semi-working config on https://dryad2-stg.cdlib.org/ , but it's currently showing "service unavailable". I've got to take a look at shibboleth config, because I'm getting `Listener exception` from https://dryad2-stg.cdlib.org/cgi-bin/PrintShibInfo.pl

**Comment by marisastrong** [comment]
update shibboleth2.xml file to have uc3-dryad-stg.cdlib.org  here:
           
            <SSO discoveryProtocol="SAMLDS" discoveryURL="https://dryad-stg.cdlib.org/eds.html"> SAML2 SAML1 </SSO>


After we configure another SP for Dryad - we'll need to change the entityID as well
ApplicationDefaults entityID="https://dash-stg.cdlib.org/shibboleth"

**Comment by marisastrong** [comment]
![Slide2](https://user-images.githubusercontent.com/810543/55036772-de24e180-4fd8-11e9-8747-88b36f8c0299.jpg)

diagram of the new environment

**Comment by jimvanderveen** [comment]
Update on the high-availability status for Dryad stage: We currently have dryad-stg (our first UI node) installed as a singleton, non-HA server. The ALB (load balancer) is provisioned, as well as `uc3-dryadui-stg-2c`, the 2nd UI node. Both UI nodes have access to the EFS volume and database.

At this point, we _could_ move the first UI node behind the load balancer, but this would be disruptive to internal and external users. Instead, I'd recommend that somebody (probably Scott) spend some time installing the Dryad app on the ALB-covered server. Once that's done, we can test the entire HA stack. Then we would point the `dryad-stg` name at the ALB, and lastly we could bring the original UI node behind the load balancer with no downtime or risk. Scott estimates that he would need half a day to install the app, which will have to happen at some point anyway.

**Comment by jimvanderveen** [comment]
This work will be scheduled into the next sprint
