### ISSUE TITLE
Re-issue invoices for datasets

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1822]
I voided the invoice for these datasets in error: 

> 10.5061/dryad.w3r2280sz
> 10.5061/dryad.xd2547dj8

Can you generate new invoices? These should be delivered via email to the corresponding/submitting author.
Daniel Garrett
daniel.garrett88@gmail.com

**Comment by ryscher** [comment]
10.5061/dryad.w3r2280sz -- I generated a new invoice

10.5061/dryad.xd2547dj8 -- This dataset was sponsored by the journal, so I left it as-is.
