### ISSUE TITLE
Reset status so that invoice is generated upon (re)publication

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1826]
These dataets were accidentally published when the PPR option failed to remain active. The dataset has since been placed back in PPR status:

10.5061/dryad.tb2rbp031 
10.5061/dryad.wdbrv15rc 
10.5061/dryad.x3ffbg7n2
10.5061/dryad.pc866t1rg

Please reset the status of these datasets so that when the submission is published (again), an invoice will be auto-generated. 

I'll ask Cxore to void the invoice.

**Comment by ryscher** [comment]
I reset the payment information for all of these, and re-generated an invoice for `10.5061/dryad.tb2rbp031`, which has been published since this ticket was created.
