### ISSUE TITLE
Add to bottom of Our Governance page

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1828]
https://docs.google.com/document/d/1b1A8SXCB0Qszq0Bi-a705bK3d3AySqYLBe3_wW9nM38/edit

**Comment by sfisher** [comment]
It looks like I don't have access to this doc, so requested access in Google drive.

**Comment by dlowenberg** [comment]
Just changed access from Jen's doc, available now: https://docs.google.com/document/d/1b1A8SXCB0Qszq0Bi-a705bK3d3AySqYLBe3_wW9nM38/edit?usp=sharing
