### ISSUE TITLE
Provide FTP access to Ari + Amelia

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1830]
Please provide these curators with access to our FTP server including any sudo capabilities required: 

> Ariana Orona (ariana.orona@datadryad.org)
> Amelia Culp (amelia@datadryad.org)

If possible, please prioritize this request because we need these users to guide FTP transfers ASAP (Iman was our point person)

**Comment by ryscher** [comment]
Ari has access. Waiting for SSH key from Amelia.
