### ISSUE TITLE
Associate David Rheinheimer's profile with the University of California, Merced (UCM) 

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1831]
Please tie David Rheinheimer's profile with the University of California, Merced (UCM) 
Email: drheinheimer@ucmerced.edu
ORCID ID:  0000-0003-1525-9069

**Comment by sfisher** [comment]
Ok.  This is done.  BTW, can now be done under "user managagement" by Jess, too.
