### ISSUE TITLE
Intermittent failures in tests merging users

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1833]
I'm seeing this happen from command like

```
CAPY_SHOW=true bundle exec rspec ./spec/features/stash_engine/admin_spec.rb:259 -fd
```

There are a couple issues.

1. Seems like the merging/deletion may take some time in the UI so checking the database directly may not reflect the UI action yet (race condition).
2. I'm also seeing in some cases that the merge happens in the reverse order of the expected test.  It expects the later user to be merged into earlier and later deleted, yet sometimes it does the merge the opposite way.

Not sure that this merge difference is anything critical, but it's weird and blows up tests at times.  IDK why I haven't seen this much before.

**Comment by sfisher** [comment]
@ryscher  I haven't seen intermittent failures of this for a while.  Do you agree we can close?

**Comment by ryscher** [comment]
Yes, I agree. I don't remember seeing this error much, but it has definitely been a while.
