### ISSUE TITLE
Migrate ownership of dataset to submitting author's account (DOI: 10.5061/dryad.8b5g6)

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1839]
Please migrate ownership of this dataset

Title: "Data from: Maternal effects and Symbiodinium community composition drive differential patterns in juvenile survival in the coral Acropora tenuis"
DOI: 10.5061/dryad.8b5g6

to the submitting author:

Kate Quigley
ORCID ID: 0000-0001-5558-1904
Email address: katemarie.quigley@my.jcu.edu.au

**Comment by sfisher** [comment]
Thanks @Ariana-Orona .  I moved ownership of this to the account she had logged in to.  She had two accounts (one seems to be pre-2019 that she'd never logged in to since then) and a more recent one.
