### ISSUE TITLE
Determine the future of analytics and usage tracking

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#1841]
The current Universal Analytics will be discontinued in July 2023.

**Comment by sfisher** [comment]
BTW, CDL TechCouncil is looking into other analytics options out of privacy concerns and other stuff.  IDK if there has been a final recommendation, but @marisastrong may be able to update us about the recommendations when they become available or if a consensus emerges and if Dryad would like to follow that lead rather than figuring out both technical options and policy concerns on their own.

**Comment by marisastrong** [comment]
As Scott mentioned (I wasn't as quick as him on my reply!) CDL is putting together a team of product managers representing all the programs to evaluate GA4. This would be to understand what features we might take advantage of and perhaps implementation details.   My understanding is that Dryad will not be using GA4 but instead using the customized plausible.io.  CDL will share any findings with Dryad relating to GA4 evaluation.  The intent is to have this information before the deadline to migrate over to GA4.




________________________________
From: Ryan Scherle ***@***.***>
Sent: Tuesday, June 28, 2022 8:30 AM
To: CDL-Dryad/dryad-product-roadmap ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CDL-Dryad/dryad-product-roadmap] Upgrade to Google Analytics 4 (Issue #1841)


CAUTION: EXTERNAL EMAIL

The current Universal Analytics will be discontinued in July 2023.

**Comment by marisastrong** [comment]
Thanks Scott, that's helpful to understand what Dryad's use cases and needs are and what is being used for what.
________________________________

**Comment by ryscher** [comment]
Google Analytics 3 will sunset on July 1. Based on discussion with Scott, CDL is moving forward with Matomo as their preferred solution. 

For Dryad's needs, we will test Google Analytics 4 in parallel with Matomo, though I can't imagine sticking with Google...
