### ISSUE TITLE
Create Dryad Admin accounts

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1844]
Please create Dryad email accounts for the following new users. If possible, please create these accounts by **Wednesday, July 6**

**Bryan Gee**
Personal email: bmgee@uw.edu
Suggested Dryad email: bryan@datadryad.org

**Kailasha Purushothaman**
kailasha.p@kriyadocs.com
Suggested Dryad email:  kailasha@datadryad.org

**Ambika Shanmugam**
ambika.s@kriyadocs.com
Suggested Dryad email: ambika@datadryad.org

Once set up, I'll ask them to log into our system to confirm access. If you need more information, let me know.

**Comment by ryscher** [comment]
Accounts created and invites sent.

**Comment by jleighherzog** [comment]
These users have successfully logged into the Dryad Admin site. Do they need to be set up with any other Admin privileges?
