### ISSUE TITLE
Document required data & external sources for full external api submission

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1846]
RSpace doesn't want anyone to see our UI and looking into rebuilding our full UI for required data for a full submission in their own system.

They would like a full list of what is required, including external data sources and with reference to our API.

After submission, users will still need to interact with our UI still when curators ask them to change things or to manage their data later.  :shrug:

Also, for this use case, it's likely that we'll also need to allow them to create user accounts and submit for that user or else to do claim functionality in some way that might be a bit different than journals.

**Comment by ryscher** [comment]
The API for journals will create an account if needed. We assume that if the journal gives us an ORCID, they have validated it. Hopefully, RSpace has a plan to validate ORCIDs as well.
