### ISSUE TITLE
Remove published dataset

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1847]
Please remove this data submission from the Dryad site (all metadata and associated data files). The data files likely contain sensitive information that should be removed, resubmitted for evaluation and replaced. However, the author is unable to provide updated files. 

Title: Focus group transcripts for Influenza vaccination hesitancy in large urban centers in South America. Qualitative analysis of confidence, complacency and convenience across risk groups
DOI: 10.5061/dryad.r7sqv9scg

Please work to initiate a refund via Stripe for the data publication charge. If you need any specific information from the invoice, let me know.

**Comment by sfisher** [comment]
I've removed this from public view, though Zenodo is taking a long time to update and seems to be down right now.  I'll keep trying to get it out of zenodo over the next day when they're back up.

Refunded payment on the stripe invoice

![Screen Shot 2022-06-30 at 3 14 23 PM](https://user-images.githubusercontent.com/105433/176787905-b95ef15b-10e5-42c0-87d4-898343d8753e.png)

![Screen Shot 2022-06-30 at 3 15 03 PM](https://user-images.githubusercontent.com/105433/176787958-811e10ac-02fc-4c15-bd95-19b3c0ba7226.png)

Put to "Withdrawn" and if they come back with corrected data we can un-withdraw and re-publish without the sensitive data.
