### ISSUE TITLE
Transfer ownership of dataset(s) (DOI: 10.5061/dryad.69ss9, 10.5061/dryad.1gf7803, 10.5061/dryad.46tj577)

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1849]
Please transfer ownership of the noted dataset(s) to:

Christina Riehl
ORCID ID: 0000-0002-7872-336X
Email address: criehl@princeton.edu

Title: "Data from: Infanticide and within-clutch competition select for reproductive synchrony in a cooperative bird"
DOI: 10.5061/dryad.69ss9

Title: "Data from: Social parasitism as an alternative reproductive tactic in a cooperatively breeding cuckoo"
DOI: 10.5061/dryad.1gf7803   

Title: "Data from: Stable social relationships between unrelated females increase individual fitness in a cooperative bird"
DOI: 10.5061/dryad.46tj577

**Comment by sfisher** [comment]
Ok.  Done.  Two different accounts to be merged again.  Looks like there are 4 datasets in her account now.
