### ISSUE TITLE
Modify Admin Table to block curation state changes for some items

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#185]
Right now, the curation states can be changed by curators at any time.

Only datasets that are in a final stash_engine_resource_state of 'submitted' for the latest resource in the dataset can have states edited by curators.  This fixes lots of complexities for us with locking and other things.

This means for those items in the admin area, the status "edit pencil" icon will be disabled.  The publication date will also be disabled.  The "clock" icon that leads to the activity log would still work, but we don't want curators to "add note" or add/delete "internal data" unless in a submitted merritt state.

---

The state diagram for curation statuses is at http://ux.cdlib.org/jlee/completed/dryad_14dec2018/#g=1&p=dataset_status_flow_v4 

The curation state table is stash_engine_curation_activities and also stash_engine_identifier states .  
 stash/stash_engine/app/models/stash_engine/curation_activity.rb  and stash/stash_engine/app/models/stash_engine/identifier_state.rb .  The curation_activity records all changes and identifier_state just shows public UI changes.

Our model Identifer (dataset) has many resources (versions).  Most tables have a foreign key for resource_id.

For publication date, we have a current stash_engine_embargoes table, but it's probably confusing because we want a publication date for everything, not just embargoed.  We should probably make a new explicit use for publication date.  We have one in stash_engine_resources, but I'm not sure where or how consistently it is being set or used right now.

The notes field is a curation note in stash_engine_curation_activities .

We need to add a resource_id to the stash_engine_curation_activities table because right now we don't know what state goes with which resource.

**Comment by briri** [comment]
Updated UI to check the new `identifier.latest_resource.curatable?` method to determine whether or not to display the pencil icon that opens the status selector.

**Comment by briri** [comment]
@dlowenberg this out on dev and ready for QA.

It now checks to make sure that the current Merritt status is 'submitted' before displaying the pencil icon and allowing the user to change the status.

<img width="1237" alt="screen shot 2019-02-05 at 3 37 03 pm" src="https://user-images.githubusercontent.com/1204467/52311547-2a01c580-295c-11e9-80e1-670c38e3bbe1.png">

Do we want to display a different status in situations where its a new version? For example the original version was curated and eventually reached 'Author Action Required' or 'Published' and then a change was made and a new version created that is not yet 'submitted'. Perhaps something like 'Revisions in Progress'?
