### ISSUE TITLE
Provide LEADING fellows with access to Dryad Admin site

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1853]
Please provide Ali and Ana with Dryad Admin access (PRIORITY please): 

Alicia Krzton
ORCID: 0000-0001-9979-2471
Email: alicia.krzton@fulbrightmail.org

Anastasia Bennett
ORCID: 0000-0001-9393-749X
Email: ab233@uw.edu

**Comment by sfisher** [comment]
It looks like neither have logged in yet (those ORCIDs don't exist in our system).  Let me know after they've logged in and have created a user record in our system and then I can change their role to admin.

**Comment by jleighherzog** [comment]
Will do.

**Comment by sfisher** [comment]
Ok.  They are set.  BTW, you can also do this under Admin > User Management once someone has logged in and they have an account.
