### ISSUE TITLE
Files unavailable on dataset landing page (DOI: 10.5061/dryad.138fd23)

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1854]
Please investigate the following dataset:

Title:  "Data from: Climate severity and land-cover transformation determine plant community attributes in Colombian dry forests"
DOI:

The dataset landing page does not include files listed under "Download dataset."
![image](https://user-images.githubusercontent.com/80363462/177383107-1fa27088-f35b-4043-a585-bbc96eb9dd7a.png)

Additionally, when "Download dataset" is selected, the downloaded folder is correctly named but is empty.

**Comment by sfisher** [comment]
Is the intended state that the file *Colombian.dry.forests.rds* appears as the only file for the dataset?

It appears that this file was present in versions 1 and 2.  However it was removed in version 3 by a user or curator and then the dataset was published that way, with no user-facing files.

For now I'm going to change the published version to version number 2 which has the file above.  I cannot see the salesforce ticket without a login so don't know whatever details are in there.

LMK if something else should be done or if there was some reason that all files were removed by someone just before publication and they published it in an empty state (for example if they were trying to remove them?).
