### ISSUE TITLE
Give Maria P permissions

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1855]
- [x] Get Maria P into Github (mariapraetzellis)
- [x] Make Maria P a superuser on Dryad prod (DL)
- [x] Make Maria P superuser on dev + stage (DL)

**Comment by sfisher** [comment]
Ok @mariapraetzellis I added you to the roadmap (tickets) and the dryad-app (code) repositories.  We have a few other random repositories for code, but most everything is in these two.  LMK if you want to be added to the few for things like sub-components of our application like internal gems and I can add you to those if you like.
