### ISSUE TITLE
Provide Slack access to new curators

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1863]
Please ensure these users are set up with Slack accounts. If any other account set up is required, reference [this](https://docs.google.com/document/d/1xj27OsuMgWbuaeWqXkgsAWOBiSx9L-8uNbfpVmzbd5o/edit#heading=h.r2jddholk1n2) GDoc. 

Bryan Gee
bryan@datadryad.org

Kailasha Purushothaman
kailasha@datadryad.org

Ambika Shanmugam
ambika@datadryad.org

**Comment by sfisher** [comment]
This will be something that Ryan or some other person at Dryad with administrator access to Slack will need to do since I'm not a Dryad slack admin.  (I'm one at CDL, but that doesn't help your curators.)

**Comment by jleighherzog** [comment]
@sfisher : Thanks, I'll check with Jen

**Comment by ryscher** [comment]
Jenn set these up.
