### ISSUE TITLE
Journal blackout setting never allows manual publishing

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1865]
The admin dataset controller doesn't allow publishing if something is embargoed and if a manual publish step is tried.  If the journal allows blackout, it always resets to *embargoed* again and adds a note that it's adding a year.

@ryscher is there a reason for doing things this way?  Are blackout journals never allowed to be published by curators for some reason?

**Comment by jleighherzog** [comment]
@sfisher @ryscher : The date field that was once available to us was removed. Would that have something to do with it?

**Comment by ryscher** [comment]
Confirmed that this is related to the missing date field. Will be fixed when https://github.com/CDL-Dryad/dryad-app/pull/896 is deployed.
