### ISSUE TITLE
Place dataset in PPR status

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1867]
This is another submission where the author confirmed they had selected PPR status upon submission but the system didn't retain that status and, therefore, it was curated and published. Can you return to PPR status? 

When the related manuscript is accepted, the submission should auto-release from PPR and move to 'Submitted' (associated with _Diversity and Distributions_). 

Marine biodiversity patterns in coastal Australian waters revealed by a three-year environmental DNA survey
10.5061/dryad.931zcrjns

**Comment by jleighherzog** [comment]
Can we prioritize this one?

**Comment by ryscher** [comment]
Dataset is back in PPR
