### ISSUE TITLE
Dryad sandbox: Unable to access 'Dataset Curation' under the Admin tab

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1870]
I'm able to log in to the [Dryad sandbox](https://dryad-stg.cdlib.org/stash) but I'm not able to access 'Dataset Curation' under the Admin tab. Attached is a screen capture of the error message that pops up. 

If possible, please investigate ASAP because I'm using this site for training purposes. 

![Screen Shot 2022-07-13 at 10 27 42 AM](https://user-images.githubusercontent.com/76497320/178772265-13492e07-5b8a-4bda-bcfb-a1fc82bf36be.png)

**Comment by sfisher** [comment]
Caused by "Ambika" and "Silverfish-Stage" being set as curators because they are users with no last names which makes sorting not work correctly.

Added PR https://github.com/CDL-Dryad/dryad-app/pull/887 to fix and temporarily edited and restarted stage.
