### ISSUE TITLE
Return dataset to PPR status

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1871]
Curator accidentally published this dataset: 

[Digital Photographs, Image Processing Scripts, and Analysis Scripts for: Evolution of plumage patterns in pattern morphospace: a phylogenetic analysis of melanerpine woodpeckers](https://datadryad.org/stash/dataset/doi:10.5061/dryad.2rbnzs7qq)
DOI: 10.5061/dryad.2rbnzs7qq

Please return to PPR status

**Comment by sfisher** [comment]
Ok.  This is out of public view now.
