### ISSUE TITLE
New tenant: Australian Wine Research Institute

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1877]
<img width="942" alt="AWRI_LOCKUP_LOGO_BLUE_DIGITAL" src="https://user-images.githubusercontent.com/25755963/179001888-239202c8-a9e4-4140-9c86-aa2b80d1be37.png">

IP range: "Our external IP addresses are 129.127.182.188 and 129.127.182.166"

**Comment by sfisher** [comment]
OK.  I think this is done and looking good.
![Screen Shot 2022-07-18 at 11 40 54 AM](https://user-images.githubusercontent.com/105433/179581226-07ed1b5e-ce91-455b-967e-797df99e802e.png)

![Screen Shot 2022-07-18 at 11 39 51 AM](https://user-images.githubusercontent.com/105433/179581236-e06f0e6f-db6a-482f-bfa9-be6b036fbac8.png)
