### ISSUE TITLE
Please remove PPR option after dataset publication

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1882]
Can you please remove users' ability to change the status of a dataset to "Private for Peer Review" after the dataset has been published?

Admin shouldn't need to perform this, because returning a published dataset to "Private for Peer Review" would require a ticket. Additionally, any automatic checks should not revert the dataset back to PPR after publication.

I can add examples as they come in, but I have noticed that users will attempt to perform this and reach out to HD to request we make the dataset private. I am not sure if changing the status removes the view, but I do not think this should be an option and am concerned that users may be selecting PPR after publication without reaching out to HD and/or a curator.

**Comment by jleighherzog** [comment]
@sfisher : Can you confirm that the option for authors to place their published data submission in PPR status has been disabled/removed?

**Comment by sfisher** [comment]
Looks like it's working to me.  LMK if you see some way they are getting around it in the UI.

Before publication:

![Screen Shot 2022-11-10 at 3 39 27 PM](https://user-images.githubusercontent.com/105433/201229126-47a7aaeb-0795-4ce8-ab4a-1e84e34b7627.png)

Published:

![Screen Shot 2022-11-10 at 3 41 48 PM](https://user-images.githubusercontent.com/105433/201229194-18a53f7f-6fc3-4867-9780-9cfa4ef8e6e1.png)

After Publication the section and option are gone:

![Screen Shot 2022-11-10 at 3 42 07 PM](https://user-images.githubusercontent.com/105433/201229214-2bd06481-e3ca-4736-9cea-87678125c506.png)


![Screen Shot 2022-11-10 at 3 42 33 PM](https://user-images.githubusercontent.com/105433/201229239-a470fdf1-d255-4ef8-a1c9-a8affba3033b.png)
