### ISSUE TITLE
SFTP/SSH capabilities in the virtual environment

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1883]
Request for SFTP/SSH capabilities in the virtual environment. 

Primarily, this will enable access to the FTP server so that curators can use the VE to curate large files transferred by FTP.

**Comment by ryscher** [comment]
Files on the FTP server can be accessed using a URL like http://ftp.data-dryad.org/InCuration/JSmith/FileName.txt (must replace the final directory and file name with actual names).

The remainder of this ticket duplicates #1784, so I will close this one.
