### ISSUE TITLE
New homepage rotation image: November, 2022

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1886]
November 2022: 2) An aquatic snail shedding larvae of the blood fluke Schistosoma mansoni (elongated white specks in the surrounding water). Image credit: Clint Sergi (CC BY 4.0)
https://iiif.elifesciences.org/digests/59395%2Fdigest-59395.tif/full/617,/0/default.webp

**Comment by ryscher** [comment]
My understanding is that we are manually changing the image every 3 months. There are many usability problems with "carousel" images that change automatically.

**Comment by ahamelers** [comment]
> My understanding is that we are manually changing the image every 3 months. There are many usability problems with "carousel" images that change automatically.

Ah, I wasn't imagining a carousel, but more like, the header image being randomly selected from a set, whenever the page is accessed. But the fact that that does not come to mind for you does imply it was not intended by the initial ticket and discussion 😄
