### ISSUE TITLE
Login UI Changes

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#189]
Iterate on login screen following this wireframe:
http://ux.cdlib.org/jlee/completed/dryad_25jan2019/#g=1&p=login_v3_1

- Re do login screen looking like above wireframe
- After ORCiD is connected, return to same page where question appears about institutions
- Allow for someone to choose institution (which takes them to associated shib) or continue to My Datasets

**Comment by briri** [comment]
@dlowenberg how closely do we want to match the colors and font sizes in the wireframe? I'm currently using the site's standard styling. 

<img width="1229" alt="screen shot 2019-02-19 at 10 20 48 am" src="https://user-images.githubusercontent.com/1204467/53037893-32fc9780-3430-11e9-8682-9f8942872560.png">
