### ISSUE TITLE
Offboard Daniella on July 29th

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1890]
- [x] Remove Daniella from bcc on all emails
- [x] Remove Daniella from any alerts
- [x] Remove any special permissions Daniella has
- [x] Set Dryad bi-weekly Sprint meetings on Scott's zoom

**Comment by ryscher** [comment]
I ran through the standard Dryad offboarding checklist.

**Comment by sfisher** [comment]
You are removed from these emails in our code, but it hasn't deployed yet, which should happen tomorrow.

Let me know if you need it to stop earlier and we can do a deploy of just a few commits today.
