### ISSUE TITLE
Associate Federico Rossano’s profile with University of California, San Diego tenant

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1897]
Please tie Federico Rossano’s profile with the University of California, San Diego 
Email: frossano@ucsd.edu
ORCID ID: 0000-0002-6544-7685

**Comment by sfisher** [comment]
Thanks @Ariana-Orona .  The user profile was already associated with UCSD so this looked good.  I added the email address to the user information.  It didn't look like he had started any submissions yet.  Let me know if I need to do anything else.

Thanks,

          Scott
