### ISSUE TITLE
Add DOIs to quarterly journal-DEFERRED shopping cart reports

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#1900]
**Problem description, and links to relevant helpdesk tickets:**
Two journal-DEFERRED accounts have asked for additional information in the quarterly shopping cart reports.

**Describe the solution you'd like:**
Could the report be revised to include DOIs of datasets to be invoiced? We

**Comment by mark02139** [comment]
Ah, ok.

Actually, I just ran a test in Data Studio. I can pull the quarterly deferred from shopping cart reports--very easy.
I don't think you need to bother running them any more.

One question, though: I do have about 30 Wiley DOIs in the dataset as journal-DEFERRED. Don't know if they were in the past, but my understanding is that Wiley journals are on a subscription plan now.

**Comment by ryscher** [comment]
Mark and I compared notes about Wiley journals, and these are synced now.
