### ISSUE TITLE
Record fee waivers in Stripe

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#1902]
For business reporting purposes, we need to record the country-based fee waivers in Stripe. These should generate an invoice that shows the full DPC, but then add a full value discount for the waiver.

**Comment by ahamelers** [comment]
In a normal invoice there is the normal fee, and then there can be additional fees on top for size overages. What is the policy on waivers for these extra charges?

**Comment by ahamelers** [comment]
```
	<% else %>
		<p>This submission does not require a payment.</p>
	<% end %>
```
Also, should we change this to warn users with waivers that they will receive an invoice for 0.00USD? Maybe something like:

```
	<% else %>
		<p>This submission does not require a payment. Upon publication of your dataset, you will receive an invoice showing that the fee for this submission has been waived. If you have any questions, please <a href="mailto:help@datadryad.org">contact us</a></p>
	<% end %>
```

**Comment by ryscher** [comment]
The extra fees should be listed and waived, so the accounting works out. 

I like the expanded message to warn users about the invoice.

**Comment by ryscher** [comment]
@mark02139, now that we are going to create an invoice for each waiver, how do you want the payment information to appear in the shopping cart report? Options include:
- Keep it the same (e.g., `waiver`, `Afghanistan`) -- this means the shopping cart report would be unchanged, but it is slightly harder to find the associated invoice
- Replace with the Stripe info (e.g., `stripe`, `D0063F73-0001`) -- makes it hard to tell which payments are waivers
- Replace the country name with invoice number (e.g., `waiver`, `D0063F73-0001`) -- Indicates waivers, but makes it hard to tell which country
- Add another column to the shopping cart report -- we would have all of the information, but new reports would have an extra column that is not present in the old reports

**Comment by ahamelers** [comment]
I've added a new column with the slightly generic name "waiver basis", since I know waivers may not be limited to country in the future but may be used for other reasons.

**Comment by ryscher** [comment]
@mark02139 Audrey completed work on this change and we have generated a couple of sample invoices. (You might be able to see these in Stripe yourself, if you enable "test" mode.)
[Invoice-0AFA77D5-0001.pdf](https://github.com/CDL-Dryad/dryad-product-roadmap/files/9953300/Invoice-0AFA77D5-0001.pdf)
[Invoice-379F4C32-0001.pdf](https://github.com/CDL-Dryad/dryad-product-roadmap/files/9953301/Invoice-379F4C32-0001.pdf)

Shopping cart reports will be updated starting with the report that runs at the end of November.
