### ISSUE TITLE
Update published version (DOI: 10.5061/dryad.15dv41nzg)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1907]
Please remove the first and only published data file "[Blank.xlsx](https://datadryad.org/stash/downloads/file_stream/1237693)" and replace with the file attached.

[Nectar_sugar_per_taxon.xlsx](https://github.com/CDL-Dryad/dryad-product-roadmap/files/9246371/Nectar_sugar_per_taxon.xlsx)

**Comment by sfisher** [comment]
Ok.  I uploaded a new file and removed and old file.  No way to do this without creating a new version, but hid the last version since I guess they didn't want it.
