### ISSUE TITLE
Payment Logic: only charge users when necessary

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#191]
- [x] In submission system, only display payment information on page 3 if researcher is not at a member institution, or with a publisher that covers cost (check institution first).
- [x] In curation system, only create an invoice under the same conditions as above.

**Comment by sfisher** [comment]
@ryscher  When you get to this, it sounds like you are determining if a journal is paying and if it should go "private for peer review"?  If that is true can you expose a method to know this information somewhere?

We probably need to do something in there or else another set another ticket to set to the correct state ("private for peer review" or "submitted") from that callback.

Brian put a callback in for setting that state.  stash/stash_engine/app/models/stash_engine/resource_state.rb called sync_curation_activity! and right now it always goes to curation activity of submitted, but this will change.

The main reason I looked into this is that I didn't know if I needed to add any actions to the controller receiving notifications from the Merritt OAI-PMH feed (which also sends out some emails and other things if it hasn't been processed yet as well as setting the Merritt state).
