### ISSUE TITLE
Update VE to include missing software

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1912]
These programs were previously available in the virtual environment but are now missing. 
Please update to include the following: 
- VLC
- HDF View
- FigTree
- MeshLab
- Anaconda/Python (requested June 30, unsure if it was installed)

Additionally, would it be possible to update [this GDoc](https://docs.google.com/document/d/1j2jez4IXqUjBgZDHrTaqcHxBJvMRkMjV-nKqGGgKPpI/edit) with what's currently available? There's also a "wishlist" at the bottom.

**Comment by ryscher** [comment]
I added the software packages that were not there and updated the Google Doc.

However, I was unable to get FigTree to run. It runs fine on my Mac, but it doesn't seem to have been updated for recent versions of Windows. I know the phylogenetics community constantly develops new software. Is there a better alternative? Perhaps one of these? https://alternativeto.net/software/figtree/
