### ISSUE TITLE
Locate submission (DOI: 10.5061/dryad.tb2rbp005)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1919]
Are you able to find this submission in our database? 10.5061/dryad.tb2rbp005

The journal has published this Dryad DOI but I can't locate it in our system.

**Comment by sfisher** [comment]
I searched through our recent logs and do not see it as a dataset that was recently worked on.

I also checked Merritt and this dataset was never submitted to Merritt. It's pretty close to impossible to remove anything from Merritt without manual intervention and asking the Merritt team to do a removal manually and there is no automated way to remove.

![Screen Shot 2022-08-11 at 2 57 48 PM](https://user-images.githubusercontent.com/105433/184250026-d32fcc22-8200-4704-a800-b9751d6c84a0.png)

I'm not sure what workflow happened. The dataset may have been started in Dryad and that would create a preliminary DOI, but if that dataset was never submitted it will not be a real or valid DOI.

Users are able to delete their own datasets ("in progress" ones) completely before submission, so I assume that is what happened in this case.  The journal may have been given a preliminary DOI, but if a user deletes the dataset before submission then the preliminary DOI will be gone along with all the information about the dataset.  There is no permanent checkpoint that can't be deleted until the first submission.

My assumption is the user came in and deleted their own dataset.  Or perhaps they came in and created another copy of the dataset with a different DOI and deleted the preliminary DOI the Journal knew about.
