### ISSUE TITLE
Update crontab for notifier instead of harvester

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#192]
The harvester is no more and we're replacing it with the notifier, which just notifies Dryad about items that have been ingested by Merritt (without doing all the other complicated stuff the harvester did).

The current crontab line is this:

```
*/5 * * * * /bin/bash -l -c 'STASH_ENV=development /dryad/apps/dryad-harvester/current/bin/harvest.sh >> /dryad/apps/dryad-harvester/current/log/dryad-harvester.log 2>&1'
```

And can be changed to this.  Obviously, the STASH_ENV will change for each server to reflect the environment.  The logging automatically defaults to the log/ directory of the app and \<environment\>.log.

```
*/5 * * * * /bin/bash -l -c 'STASH_ENV=development /dryad/apps/stash-notifier/main.rb'
```

We probably want to start out with the change on uc3-dryadsolr-dev.cdlib.org and after being sure it works, move it into uc3-dryadsolr-stg.cdlib.org .

**Comment by jimvanderveen** [comment]
Hey @sfisher , I got the following error via email when I ran the cron notifier:

`/apps/dryad/local/lib/ruby/gems/2.4.0/gems/oai-0.4.0/lib/oai/client.rb:96: warning: constant ::Fixnum is deprecated`

**Comment by sfisher** [comment]
Because it's just a warning, I think it still ran ok.  I can track down the warning and try to get rid of it so it doesn't cause the weird output and verify that it is updating our states in Dryad.

**Comment by jimvanderveen** [comment]
I could also pipe stderr to stdout

**Comment by jimvanderveen** [comment]
Nuts! That didn't work. And I don't want to blithely pipe stderr to /dev/null

**Comment by jimvanderveen** [comment]
Hey @sfisher , is that logging path some ruby/rails magic, or does the script manage that?

**Comment by jimvanderveen** [comment]
I haven't been able to find a way to deal with that warning message, other than piping stderr to /dev/null. That's what's on dryadsolr-dev right now.

**Comment by sfisher** [comment]
It sounds like we can ignore this deprecation warning for now.  See https://stackoverflow.com/questions/41463999/warning-constant-fixnum-is-deprecated-when-generating-new-model  .  Something is changing in Rails.

I refreshed my memory about the logging.  It defaults to logging in \<app-dir\>/log if no other options are supplied.  If you notice the failures to notify Dryad in there, it's because some stuff in November got into Merritt but was deleted from Dryad.  So it's trying to notify us of things which no longer exist in our system.

If you'd rather capture the logs from standard out, I added an option with an environment variable.  Just set "NOTIFIER_OUTPUT=stdout" which tells the Ruby script not to log to a file but to send to its standard out from the logger object.  Ruby has a $stdout variable I use, which I hope does the right thing.

It sounds like that might be a better option to make it more explicit?  I don't really mind either way, and it maybe might make it easier to capture standard error (though I'm not sure).

I sent one through and it came through perfectly.  We can beat on it a bit to be sure it works, but I think I will go install the script on stage in the morning and so far I'm pretty happy that it seems to be working without any issues.

BTW, it will stop retrying the failed notifications to Dryad after a month of it telling it that the objects don't exist.  I figured if it can't notify Dryad that something completed in a month then something is seriously wrong and it doesn't help to keep trying for all time.

**Comment by jimvanderveen** [comment]
Hey @sfisher let's chat about this in the standup today.

**Comment by sfisher** [comment]
This is a drop-in replacement for what you had before if you want to create the log yourself.  You can run it and look at the log.  Seems fine to me.  Are you seeing problems I don't see?

```
/bin/bash -l -c 'STASH_ENV=development NOTIFIER_OUTPUT=stdout /dryad/apps/stash-notifier/main.rb >> /dryad/apps/stash-notifier/log/stash-notifier.log 2>&1'
```

**Comment by jimvanderveen** [comment]
This works great, @sfisher , thanks!
I have pushed this change into dryadsolr-dev. Let me know when you want to roll this out to stage.

**Comment by sfisher** [comment]
Hi @jimvanderveen We're ready to roll this out to stage.  If you could work this in relatively quickly, it would be nice since we have code that depends on this now.

I tested it manually on stage with this and it works great, so it just needs to go into the crontab.

```
/bin/bash -l -c 'STASH_ENV=stage NOTIFIER_OUTPUT=stdout /dryad/apps/stash-notifier/main.rb >> /dryad/apps/stash-notifier/log/stash-notifier.log 2>&1'
```

Thanks!

**Comment by jimvanderveen** [comment]
This is done on stage, @sfisher 
There was a change to `~dryad/init.d/solr.dryad` -- see `solr.dryad.save` for diffs

**Comment by sfisher** [comment]
Thank you, @jimvanderveen .  I looked at the crontab and looks good! Thanks for putting this in.
