### ISSUE TITLE
How to package and deploy lambda?

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1926]
We can test code in our AWS UI for Lambda and then eventually deploy it.

- [ ] We need to use "Lambda Layers" in order to install additional AWS libraries.  See https://www.geeksforgeeks.org/how-to-install-python-packages-for-aws-lambda-layers/ or https://www.linkedin.com/pulse/add-external-python-libraries-aws-lambda-using-layers-gabe-olokun/
- [ ] Where should we keep this code?  With our main app would be convenient, but IDK how that would work.
- [ ] How do we package and deploy it?

**Comment by elopatin-uc3** [comment]
@sfisher Though I'm not sure how similar your requirements are to ours, Terry and Mark have worked through options for Lambda deployments. Terry's out this week, but Mark is around if it would be helpful to sync up.

**Comment by sfisher** [comment]
I think for our project the requirements might be slightly different since this Lamba is somewhat limited in scope and is in a more supported language (Python). I'm sure the information will be helpful, from what I'm seeing "Layers" are a way to include additional libraries for a python script.

I'm sure they'll have good insight about how to manage the code and packaging which I think will be good to get into once I have some working code that needs to be packaged better than in testing mode from the AWS UI.

**Comment by sfisher** [comment]
Duplicated by another ticket we have.  Closing.
