### ISSUE TITLE
When current file is selected for download, previous version downloads

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1929]
DOI: 10.5061/dryad.mw6m905zn 

If I click on the newest (August 15) README file from the dropdown menu on the right hand side, it opens the August 14 version. However, when "Download Dataset" is selected and opened from downloads, it correctly includes the most recent README version.

Should this be corrected before we proceed to publication?

**Comment by ahamelers** [comment]
@jleighherzog Is this still occurring?

**Comment by sfisher** [comment]
To me it looks like it's corrected in a published version (version 6) from August 22.  The files and version numbers all match correctly and also match what is stored in Merritt as far as I can see.

Let us know if there is still a problem with this one.

**Comment by jleighherzog** [comment]
@ahamelers : It's tough to know since this dataset has been published but Scott confirmed all is a-okay. But, thank you for investigating. Will close this ticket.
