### ISSUE TITLE
Get stage to use efs mount for storing files

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#193]
In the Dryad application we either need to symlink as part of the deploy process or else change the configured path for storing files that are uploaded for staging to the application to use the efs mount.  It's at /app/dryad-stg-shared for the moment.

**Comment by jimvanderveen** [comment]
The EFS mountpoint has been set up on both stage servers. Is there anything else I need to do for this ticket, @sfisher ?

**Comment by sfisher** [comment]
I don't think you need to do anything else.  We'll need to create symlinks to use it in our application and I think we'll be good so long as the performance works for us.
