### ISSUE TITLE
Evaluate: constrained institution lists unless "My institution is not in the list" selected

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1931]
DMPTool does this for selecting a ROR institution around login to *urge* people to choose an institution from the autocomplete list and make inconsistent data harder than just doing the right thing and choosing from the controlled vocabulary.  User's can't have free text for the institution unless they check the box first.

I know we have some non-matched flags and also do exact string matching on RORs even if not chosen from the list.

This might be useful for us, though and reduce the amount of places users put in inconsistent crap and maybe reduce strain on curators.

**Comment by ahamelers** [comment]
Saw a demo and got a screenshot from Brian of the DMPTool solution
<img width="720" alt="Screen Shot 2022-12-14 at 11 20 50 AM" src="https://user-images.githubusercontent.com/1749394/207695251-0bd5e02c-2620-4830-8781-297835030513.png">

**Comment by ahamelers** [comment]
I think a solution similar to the DMPTool but with different timing/not red text (to indicate there is not an "error") would be best
