### ISSUE TITLE
Change Corresponding Author (doi:10.25349/D9KP60)

### ISSUE THREAD

**Issue by rcurty** [CDL-Dryad/dryad-product-roadmap#1936]
The depositor (Varun Iyer) for this dataset would like to transfer ownership to David Cleveland (https://orcid.org/0000-0002-9371-7507).

**Comment by jleighherzog** [comment]
Possible to prioritize this ticket please?

**Comment by sfisher** [comment]
Ok.  This is transferred to David Cleveland.  Though this is a very odd dataset in that it looks like the owner never edited it and it was only ever edited by curators and never the original author.  🤔

**Comment by rcurty** [comment]
@sfisher The original depositor is Varun Iyer, David Cleveland's advisor.
