### ISSUE TITLE
JXB and auto-PPR

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1937]
The _Journal of Experimental Botany_ (JXB) would like to incorporate the auto-PPR feature for all data submissions received by Dryad for this journal title (ASAP). This is an existing integrated title. 

Note: When a manuscript is rejected by the journal, if/when the authors are invited to resubmit, they initiate an entirely new submission on the journal side with a new manuscript number. In these instances, could we could auto-withdraw the existing Dryad dataset when a rejection notification is received from the journal? Then, the journal office can instruct authors to submit a new dataset, with the new manuscript ID.

**Comment by ryscher** [comment]
The auto-PPR setting is now enabled.

Our current workflow for rejected submissions is the same as described above -- when a dataset is in PPR and we receive a rejection notice, the dataset is withdrawn.
