### ISSUE TITLE
Provide GitHub permissions for curators

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1940]
Currently, our UCSB Curator, **Renata Curty**, has access to submit GitHub tickets for Dryad-related issues. However, she's unable to select from the 'Projects' and 'Labels' menus in order to appropriately tag/route the ticket. 
Can you provide her with additional permissions so that she can select the correct settings? 

Additionally, please provide **Bryan Gee** (bryan@datadryad.org) and **Savannah Butler** (savannah@datadryad.org) with access to GitHub including all the rights and permissions required to successfully submit tickets.

**Comment by ryscher** [comment]
Sent all three invites, which they will need to accept to get the appropriate permissions.
