### ISSUE TITLE
New role for Dryad Admin site? 

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1949]
We have several users who have "Curator" access to the Dryad Admin site, however, because we have automated assignment processes active in the background, perhaps a new role for these individuals should be created while maintaining the same level of access BUT removes the option to edit datasets (no access to editing mode).
- Donna Okubo 
- Sarah Lippincott
- Anastasia Bennett
- Alicia Krzton
- Kailasha Purushothaman
- Ambika S
- John Chodacki
- Jonathan Treadway

Donna & Sarah have confirmed that they can use the test site/sandbox if they'd like to demo the submission form. Therefore, no editing capabilities needed on the live site. 

I don't have a preference for what the new role is called. Whatever makes sense (Curator Basic, Basic Administrator, Intermediate User, etc.)

![Screen Shot 2022-08-29 at 2 14 27 PM](https://user-images.githubusercontent.com/76497320/187280437-ee91c0e7-27d3-4dc5-83c5-bc6cf4a30078.png)

**Comment by jleighherzog** [comment]
@sfisher : Possible to prioritize this one? We have quite a few auto-assignments to non-curators happening and I expect this will increase with additional staff departures (Ari and J&J). If you have any other ideas to prevent auto-assignment to non-curators, open to ideas!

**Comment by mariapraetzellis** [comment]
@jleighherzog We'll discuss this and get back to you about this feature.

**Comment by sfisher** [comment]
@jleighherzog Yes, this ticket was already in our current sprint and is already being worked on.

**Comment by sfisher** [comment]
Hi @jleighherzog 

Please see the changes in our stage server to see if this fits what you're looking for.  You may need to have two users to try it out (you can create more at mailinator for the sandbox orcid).

With one user, go to the other user and assign them a "Limited Curator."

Log in with the "Limited Curator" user to be sure the menus and actions they can take seem correct to you.

Thanks.
