### ISSUE TITLE
Plan for status page during maintenance or technical issues on production Dryad

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#195]
If apache is up, but server is done - put up a maintenance page

**Comment by jimvanderveen** [comment]
Are we going to use the Dash model for maintenance outages? (Basically having apache check for the existence of a maintenance page.)

**Comment by sfisher** [comment]
I think we should unless there is some better way you know of to do maintenance pages.  Or maybe the ALB can do this for us or something else?  IDK what the other options are.
