### ISSUE TITLE
Activity Log: clarification required re: 'Action Taken By' 

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1950]
The Activity Log for the dataset mentioned below confirms that this dataset was submitted on 08/13/2022 00:02:04 UTC. 

> Forecasting live fuel moisture of Adenostema fasciculatum and its relationship to regional wildfire dynamics across southern California shrublands
> 10.25349/D9HS51

But, I'm not sure whether the system auto-submitted this dataset or the author took action and their name isn't properly displaying. The Activity Log lists 'Dryad System' in the 'Action Taken By' column for the 'Submitted' date. I assume this should list the author's name, Isaac Park, instead. 

Can you clarify how this works, please? I just want to be sure there's no issue with the recorded history.

**Comment by ryscher** [comment]
The author took this action. Certain actions assume the user is the same as the previous user, and this is not useful when the previous user was "Dryad System". I will see whether there is an easy fix.

Other examples:
- https://datadryad.org/stash/ds_admin/activity_log/92306
- https://datadryad.org/stash/ds_admin/activity_log/93279
