### ISSUE TITLE
Update member list on the website

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#1953]
Please update the website with the new member list:
[Member list 30Aug2022.txt](https://github.com/CDL-Dryad/dryad-product-roadmap/files/9453038/Member.list.30Aug2022.txt)

**Comment by sfisher** [comment]
@mark02139 "University of Rochester" is that someone new who is coming on (since I don't see a partner login for them)? I don't see "University of Sheffield" listed who we have configured as a partner.
