### ISSUE TITLE
Salesforce API

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1958]
Please update the API in Salesforce, as noted below.

There are many 'In Progress' datasets in Salesforce that are related to cases that have already been resolved (published or withdrawn). To create automated processes in SF related to these cases, which would save curator time and provide accurate metrics, we would like for the dataset status to be included in Salesforce and update as it is changed on the Dryad site.

With this in mind, the "Dataset Title" field should also update as it is changed on the Dryad site, as well so that the information within the field remains accurate. The "Case Owner" should also update to reflect the curator assigned to the dataset.

**Comment by ryscher** [comment]
@jleighherzog Looking over other fields that are possible to sync
- Last Activity Date -- Is it useful to set this? Should it be the last date of submitter activity, or any activity? 
- Related DOI -- Am I correct in assuming this should be an article DOI?

**Comment by jleighherzog** [comment]
@ryscher 
1) Useful if "Dataset Status" field in Salesforce could match the current status of the submission in the Dryad Admin site (not based on "Last Activity Date")
2) No, "Related DOI" is used to record duplicate or associated data submissions. The "DOI" field in Salesforce is used to capture the DOI of the data submission on the Dryad Admin site
