### ISSUE TITLE
Filter by funder

### ISSUE THREAD

**Issue by gibsonjen** [CDL-Dryad/dryad-product-roadmap#1963]
This is my first ticket I'm so excited!! Can we please add the ability to filter by funder to our search and browse capability? This is required by the NIH GREI coopetition plan, section 3.2.3. 

-----

(Scott's note).

We'll add a funder facet into the search, populate funders into it and also represent NIH institutes and also a facet for NIH at a top level (which also includes the institutes).

- [x] Add funder facet to SOLR for searching.
- [x] Configure geoblacklight to use the new funder facet.
- [x] Add to our SOLR population script to include all funders people have added (through CrossRef funders)
- [x] Be sure any of the NIH institutes also get an entry for the general NIH value (so they could be limited either more broadly or more specifically)
- [x] Repopulate SOLR and test.

Note: I also added a new table for relationships called `dcs_contributor_groupings` which allows us to group individual funders under an umbrella organization as seems to be required by NIH.  Maybe other large funders will be using something like this in the future.

The other types of contributors are sponsors which is the DataCite value Daniella had us use for research facilities and I can imagine they might have umbrella organizations, also. (labs, campuses in a system, etc).

**Comment by ryscher** [comment]
Note that there is a difference between "funder" (NSF, NIH), and "funder division" (the various "institutes" of NIH). Currently, Dryad lumps these all into a single field, so a submitter could choose either the top level "NIH", or the more specific "National Institute of Environmental Health Sciences". For the first pass, we can just do simple matching and ignore the hierarchy, but in the future, we want to handle this better.

**Comment by mariapraetzellis** [comment]
The list of NIH ICOs is [here](https://www.nih.gov/institutes-nih/list-institutes-centers). I did a quick spot check, and these are in ROR, and their relationship to NIH is included in the metadata. For example: https://ror.org/04r5s4b52

**Comment by sfisher** [comment]
But we're using crossref funder registry for funders and not ROR currently.  Is changing to ROR in the cards?  Are we serious about a migration of all our old data and all the fun that may entail?
