### ISSUE TITLE
Transfer ownership and update ORCID IDs (DOI: 10.5061/dryad.g2q42)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1965]
1) Please transfer ownership of the submission referenced below to this author's Dryad dashboard: 
Adrian Brown
[0000-0003-1818-6192](https://orcid.org/0000-0003-1818-6192)

> Title: Description and preliminary results from a structured specialist behavioural weight management group intervention: Specialist Lifestyle Management (SLiM) Programme
> DOI: 10.5061/dryad.g2q42

2) I provided Adrian Brown with their unique link to associate their ORCID ID but, somehow, all co-authors now have the same ORCID ID. 
- Are you able to correct this? If I need to remove all authors (except for Adrian Brown) and re-add them without the ORCID IDs, let me know. I'm hoping you have a faster way. 
- Is this concerning? That link should have only worked for the submitting author.

**Comment by jleighherzog** [comment]
Possible to place priority on this ticket?

**Comment by ahamelers** [comment]
I've removed the duplicate ORCIDs from the authors. It didn't create user accounts for the others or anything, just copied the ORCID to the non-user authors—this is before my time and I can't guess why!
