### ISSUE TITLE
Update Dryad access for J&J contacts

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1966]
DEACTIVATE THESE USERS AT END OF BUSINESS DAY ON **THURSDAY, SEPTEMBER 15th** 

Molly Cockerel ([mollyc@jjeditorial.com](mailto:mollyc@jjeditorial.com))
Julia Stevenson ([julias@jjeditorial.com](mailto:julias@jjeditorial.com))

They have access to Slack channels, GDocs, Dryad Admin site

**Comment by ryscher** [comment]
Processed the Offboarding Checklist, and removed all access I found. Note that I did not find access to anything in Google Docs, so you may want to double-check the permissions on the curation folder, in case they had permissions through a non-Dryad Gmail address.
