### ISSUE TITLE
Website edit: Code of conduct page

### ISSUE THREAD

**Issue by gibsonjen** [CDL-Dryad/dryad-product-roadmap#1967]
I don't have a new CoC WG yet, so please can we remove the following section from this page - https://blog.datadryad.org/code-of-conduct/?

Remove this:

Dryad Code of Conduct Working Group
The composition of this group rotates & will be updated here. Last updated 2020-02-03

Tracy Teal – tkteal@datadryad.org
Jason Williams – williams@cshl.edu
Lou Woodley – louwoodley@cscce.org

Thank you!

**Comment by gibsonjen** [comment]
Thanks for remembering! Yes. I can do that. This ticket can be killed.

**Comment by marisastrong** [comment]
The section you requested to be removed is still there.  Is that ok?

```
Dryad Code of Conduct Working Group
The composition of this group rotates & will be updated here. Last updated 2020-02-03

Jennifer Gibson – jgibson@datadryad.org
Jason Williams – williams@cshl.edu
Lou Woodley – louwoodley@cscce.org
```

**Comment by gibsonjen** [comment]
I won't have the composition of a new group until after October 12. However, we should remove Lou Woodley in the meantime - and update the date updated to the day it's updated. Marisa, thanks for clarifying.
