### ISSUE TITLE
Geographical profile of Dryad authors

### ISSUE THREAD

**Issue by gibsonjen** [CDL-Dryad/dryad-product-roadmap#1969]
Hi team! I need help, please, describing the geographical profile of authors publishing data with Dryad. I'd like to get back to Schmidt Futures (!) with this info before the end of September if possible. 

I'd like to be able to say what countries, or continents, authors come from - ideally year on year so we can see changes over time. We (er - meaning Mark!) can analyse a csv using Datastudio. 

As we develop an inclusion and diversification strategy (still TBD), it will be valuable to be able to report on this once a year, around this time. 

What am I missing? 

Thanks in advance!

**Comment by gibsonjen** [comment]
@ryscher Any updates?

**Comment by ryscher** [comment]
@gibsonjen Should be done on Monday

**Comment by ryscher** [comment]
Ran this report and sent a copy to @gibsonjen
