### ISSUE TITLE
Update status of published dataset (DOI: 10.5061/dryad.7d7wm37xk)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1973]
Please set the status of this published dataset to PPR and hide any data files from public view: 10.5061/dryad.7d7wm37xk

**Comment by jleighherzog** [comment]
@ryscher + @ahamelers : Possible to prioritize?

**Comment by ryscher** [comment]
This dataset is back in PPR.
