### ISSUE TITLE
Add Dryad contact page to website

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#1974]
@ryscher , Jen has approved the contact page draft to be added to the website.
Link: https://docs.google.com/document/d/1cuDJcK3IdR20L9tlGkudvTdOQtb-2BuVJjY8W6rhh4M/edit?usp=sharing

She would like this to be prioritized.

**Comment by ahamelers** [comment]
I would suggest adding the page to the Help menu and to the site footer. Let me know if some other combination of page exposure is preferred!
