### ISSUE TITLE
Run a number of datasets through Frictionless processing to get some stats on time data

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1976]
We need to know how long things take.

**Comment by ryscher** [comment]
Is this complete? Scott did initial analysis for https://docs.google.com/document/d/17f3qG04LTGD4mfcB7go4zi7R40MPgMwV3gLwRhAMdPw/edit, and Audrey did more for https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2312

**Comment by ahamelers** [comment]
I think so, while file size does play a role in frictionless speed, it's not at all consistent. The real time sink seems to depend on the number of errors. I'm satisfied with that analysis, however if we want to create a test corpus of files of various types and sizes and record times and results and make a big table we could do that too.

Personally I think we should only go to the effort if we're going to publish the data, maybe write an article... 😉

**Comment by ahamelers** [comment]
I've made a big table for analysis of errors. In the course of this I've also made a big table of frictionless runtimes with file types, sizes, and frictionless error statuses. Here is a data file

[frictionless_runtimes.csv](https://github.com/CDL-Dryad/dryad-product-roadmap/files/12718314/frictionless_runtimes.csv)
