### ISSUE TITLE
Evaluate getting rid of gulp and changing UI library

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1984]
gulp is obsolete and not maintained.

Joel wanted the UI Library maintained as way to demo styles and revise them later without much programming involvement (html/css/sass only) but it is now very obsolete.

Can we move to another way of working with it that allows HTML page demos if they are still required but that isn't so awkward to use with our site and is not obsolete?

**Comment by marisastrong** [comment]
Is this a task we would like Joel to revisit?  We can reach out to check his availability.

**Comment by ryscher** [comment]
- As we expand to a larger team on a wider variety of platforms, it would be good to make the system as easy to manage as possible. Gulp has consistently been one of the most difficult pieces of our installation to maintain. It is worthwhile considering whether we need a dedicated tool for this, or whether it would be better to move the sample pages somewhere accessible and work directly from the CSS.
- We seem to be heading towards a large site redesign, though we haven't put it on the board yet. Would Joel be involved in such a redesign? If so, we definitely want something that would work for him.

**Comment by sfisher** [comment]
@marisastrong   I think there are a few parts to this: Joel's current practice and way to work on these things, our way to work on things and the technology we will want to use on our site after upgrades.

It certainly doesn't hurt to check and see what his current practices are and how he prefers to work.

We may also be making some changes with the way we use assets (images, css, javascript) in some way around the Rails upgrade.  (Rails 6 suggested approach is using the Sprockets gem only for css/images and Webpacker for Javascript.  Rails 7 has Sprockets as optional and many people have moved to Webpack(er) for all assets).

If we can find common technology (maybe Webpack/Webpacker) for both Joel and us then it may streamline and simplify having to maintain as many different technologies.

Right now we're running a hybrid approach with Sprockets for old Rails stuff, Webpack(er) for React components and Gulp for the UI library.  I'd love to move from 3 different technologies down to 1 or 2.  Audrey also has a lot of experience in the JS world and I'm sure will have useful resources in this discussion or in designing a less cumbersome system.

PS.  Webpack is a Javascript library for compiling assets.  Webpacker is a rails wrapper/interface around webpack to make it work more nicely with Rails (so the two kind of work together).  Sprockets is "The Asset Pipeline" system that Rails used from Rails versions 2 or 3 through 6 and became a separate optional gem in 7 that wasn't part of the core system anymore and I think a lot of people have moving away from it.

**Comment by sfisher** [comment]
This project may be in an area that Audrey has insight into (maybe just compile the scss with a yarn task?).  We may also want to conference with Joel and the web production people in case we plan on working with them in the future for updates.

**Comment by ahamelers** [comment]
I've used webpack to automatically compile SCSS files in the past, and there are several SASS compilers for node, I think it would be very easy to add one to the project to replace gulp

**Comment by ryscher** [comment]
It is clear that we no longer need gulp. Not clear whether we really need a standalone UI system. I'm going to close this ticket and create a new ticket for "remove gulp".
