### ISSUE TITLE
Remove data submission (DOI: 10.5061/dryad.1n6c4)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1986]
The author of this dataset, originally published in 2016, has informed that the data files contain identifying HSI data. A curator has reviewed the dataset and has confirmed the authors concern: 

_

> " ... without a README it isn't explicitly clear what each variable represents. However, given the column names, there are definitely several indicators present. Location (hospital name) is included in the metadata, plus from this variable list it appears that at least age, gender, height, weight are included as indirect indicators, plus the more concerning time and month which would be direct indicators. Overall the author has valid reason for concern."

_

Please remove entirely from the Dryad site: 10.5061/dryad.1n6c4

**Comment by sfisher** [comment]
This is no longer public.  If the user isn't ever planning to resubmit fixed or anonymized data, let me know and we can completely remove the dataset from our system and Merritt (though once it is gone there isn't a way to ever get it back).
