### ISSUE TITLE
Unable to edit curator assignment and update status (DOI: 10.5061/dryad.15dv41nzg)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1987]
Please reassign this dataset: 10.5061/dryad.15dv41nzg to me (Jess Herzog) and ensure that:
1) The status = "Curation"
2) I have the option to update the status. Currently, when I attempt to change the status, I am only provided with the option to leave a note (see screen capture). 

_**Note**: View related ticket [here](https://github.com/CDL-Dryad/dryad-product-roadmap/issues/1907#issue-1327409644)_

<img width="967" alt="Screen Shot 2022-09-19 at 11 58 50 AM" src="https://user-images.githubusercontent.com/76497320/191072411-6bbdadda-c1f7-44b8-86ac-40fb899683c5.png">

**Comment by ahamelers** [comment]
I've changed the curator to you, Jess, and it looks like the status is in curation
