### ISSUE TITLE
Cleanup Dynamic "twirly" Metadata loading by Javascript

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1995]
The original site design was that pages would display any number of metadata schemas.  Because of this, pages full of DataCite metadata loaded dynamically after page load by way of AJAX (UJS).

You'll notice a "twirly" when the page loads and the lots of DataCite specifics load after the page load.  (The idea being the "twirly" might decide to load some other metadata schema instead).

This never happened and engines have been stripped out for different metadata schemas, also.  We could probably remove the extra "twirly" step and just load DataCite-specifics with the page load instead which might reduce load times and simplify things.

Certainly not critical, but it would be a nice cleanup step for the longer term.

**Comment by ryscher** [comment]
This has been fixed as a side effect of cleaning up the submission pages.
