### ISSUE TITLE
CEDAR UI elements in submission page

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#1996]
(These were split out from #1805)

Current work for CEDAR is in the branch `cedar-base`. 

In the initial page of the submission system, there is a React component that launches the CEDAR editor. Please update this component to include the following features:
- [x] When the resource object has content in the `cedar_json` field, modify the component to show the name of the CEDAR template and include the edit and delete buttons. The template's short name will be in the JSON in `submission_pipeline`, and match to a value in the `APP_CONFIG`.
- [x] Create the dialog to confirm deletion of CEDAR metadata

Refer to the UI designs at https://li0zj8.axshare.com/  -- there are several pages of designs reachable via a menu on this page.

**Comment by ahamelers** [comment]
I've made the cedar modal much prettier on the `cedar-audrey` branch. For the actual goal of this ticket, I'd like to talk about possibly revamping this React compenent to rely much more on native React lifecycle functions—basically, I think it would be a lot easier to work with if it were more React-flavored

**Comment by ahamelers** [comment]
@ryscher This is ready to be merged back into `cedar-base`. The one thing missing is whether or not the template is "Incomplete" vs "Complete and Valid"—maybe we can discus (or find out from cedar?) how we can easily discover that status
