### ISSUE TITLE
Brand each campus Dryad with logos

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#200]

**Comment by briri** [comment]
Do we have copies of these branded logos?

**Comment by sfisher** [comment]
They are already in there for all our existing tenants, I thought.

dryad/app/assets/images/tenants

**Comment by briri** [comment]
Everything seems to be working properly. It always shows the Dryad logo and then the tenant (if applicable) next to it. 

We may need to write a script to properly set people's tenant_id in the database. Right now the 'Testing Account' and 'Daniella' are the only ones set to 'cop' everyone else is set to 'dryad'
