### ISSUE TITLE
Move Dryad blog link to top level of top nav

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2002]
**Problem description, and links to relevant helpdesk tickets:**
The link to "Our Blog" is pretty hidden under the "About" menu. 
<img width="419" alt="image" src="https://user-images.githubusercontent.com/82666810/192273085-55c7e1e6-c9d5-4988-abc6-074bb09861d4.png">

**Describe the solution you'd like:**
Jen recommends making this a top-level menu item called "News".

**Comment by ahamelers** [comment]
The blog link is also already in the footer and on the new contact page
