### ISSUE TITLE
Offboarding Ariana Orona

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2005]
Please follow the [offboarding procedures](https://docs.google.com/document/d/1xj27OsuMgWbuaeWqXkgsAWOBiSx9L-8uNbfpVmzbd5o/edit#heading=h.r2jddholk1n2) for Ariana Orona and deactivate all related accounts. 

Additionally, please remove Ari's profile from the [Our Team](https://datadryad.org/stash/our_staff) page on the website. 

Due date: Friday, September 30

**Comment by ahamelers** [comment]
Ari removed from the Our Team page in pull request https://github.com/CDL-Dryad/dryad-app/pull/941

**Comment by ryscher** [comment]
All of Ari's other accounts are now closed.

One major note: There are approximately 300 Salesforce cases still assigned to Ari, with status "Pending" or "In Process". Many of these are older and could simply be closed, but it's probably useful to have someone review them individually.
