### ISSUE TITLE
Hook back up Dryad's linking with Europe PMC

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#201]
Update linking - http://europepmc.org/search?query=%28LABS_PUBS:%221012%22%29&page=1  hasn’t been done really since 2016 — send to helpdesk@europepmc.org

**Comment by ryscher** [comment]
I'm not sure what the above URL is referencing, but some of the results do link to Dryad content.

@ahamelers Any ideas?

**Comment by ahamelers** [comment]
This is about the Europe PMC external links service (https://europepmc.org/LabsLink). '1012' is the external links provider ID for Dryad in Europe PMC's system, so using that search you can see the list of successfully created links on the Europe PMC end. The links are generated and sent to Europe PMC in https://github.com/CDL-Dryad/dryad-app/blob/main/lib/tasks/link_out.rake and that seems to be working fine, I recall it was last adjusted right after the recent ruby & rails upgrade.
