### ISSUE TITLE
Adjust contact page

### ISSUE THREAD

**Issue by gibsonjen** [CDL-Dryad/dryad-product-roadmap#2011]
Hi all – I'm getting a number of requests re dataset submission at hello@datadryad after the new contact page went up. Can I suggest that 1) on https://datadryad.org/stash/contact, above 'General enquiries', we add "If you need help with your data submission, please contact help@datadryad.org, and 2) move the contact us page to the About menu? Wdyt?

**Comment by ahamelers** [comment]
How about this reorganization?

---

<h1>Contact</h1>
<h2>Help & support</h2>
Please contact <a href="mailto:dev@null">help[at]datadryad.org</a> for assistance with dataset submissions.

<h2>General enquiries</h2>

<b>Email:</b> <a href="mailto:dev@null">hello[at]datadryad.org</a>

<b>Phone:</b> <a href="tel:+18332925326">+1 833-292-5326</a>

<p><a href="https://twitter.com/datadryad">Twitter</a> | <a href="https://www.linkedin.com/company/datadryad/">LinkedIn</a></p>
<h2>Head office</h2>
<p>Dryad<br>
417 Mace Blvd. , Ste J110<br>
Davis, CA 95618<br>
United States</p>
<p>Jennifer Gibson, Executive Director: <a class="emailr" href="mailto:dev@null">jgibson[at]datadryad.org</a></p>
<p>Jessica Herzog, Head of Publishing Services: <a class="emailr" href="mailto:dev@null">jherzog[at]datadryad.org</a></p>
<p>Sarah Lippincott, Head of Community Engagement: <a class="emailr" href="mailto:dev@null">sarah[at]datadryad.org</a></p>
<br>
<br>
<p>Dryad is a 501(c)(3) nonprofit corporation under the North Carolina Nonprofit Corporation Act, registered with the U.S. IRS, EIN number 46-1685419.</p>

**Comment by ahamelers** [comment]
> 2) move the contact us page to the About menu? Wdyt?

@gibsonjen I'm hesitant to do this mainly because that menu is very full. It would be good to do a site menu inventory and reorganization to make sure that the menu is serving the users in the best way—I'm sure the CDL UX team could help!

**Comment by gibsonjen** [comment]
Reorganisation looks great - thank you. Could you also please add Facebook (https://www.facebook.com/profile.php?id=100075926210112)?

Understood re long menu. One for future!

**Comment by ryscher** [comment]
We hadn’t added Facebook because I wasn’t aware the new Facebook page existed. We have an old page at https://www.facebook.com/DataDryad, which is a “business” page, but it hasn't been used for several years. I’m not sure how the "business" page relates to the type of page for the new page... Facebook keeps changing the types of pages and their capabilities.
