### ISSUE TITLE
Upgrade to Ruby 2.7 or 3.x

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2020]
Rails 6 requires Ruby 2.5 or newer.
Rails 7 requires Ruby 2.7 or newer.
(based on a google search)

Supposedly 3.x is somewhat higher performance, also.

Ruby 2.7 is end of life in March 2023 according to the internet so I think we will want to go to 3 or above before or as part of the upgrades.

**Comment by ryscher** [comment]
Based on in-person discussion, it will be best for us to move our servers directly to 3.x, regardless of whether we upgrade the code in smaller steps.

**Comment by ryscher** [comment]
Dryad notes: https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/ruby_version_server_upgrade.md

**Comment by ahamelers** [comment]
Working on 2.7 upgrade in preparation for upgrade to 3.0. Temporary disable:

```yaml
# TEMP IGNORE for ruby 2.7 upgrade
Style/OpenStructUse:
  Enabled: false
```

**Comment by ahamelers** [comment]
I have completed the upgrade to 2.7.6 in the linked branch (https://github.com/CDL-Dryad/dryad-app/tree/2020-ruby-upgrade)

We will need to upgrade rails to at least version 6 before we are able to upgrade ruby to 3.0 (see Merritt's ticket, https://github.com/CDLUC3/mrt-doc/issues/1071,  also linked in #2059)

We can attempt to run the linked branch on our dev server, and then if successful, use it for the rails upgrade.
