### ISSUE TITLE
Provide GitHub access to Savannah Butler

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2028]
Please provide GitHub access to Savannah Butler with access and permissions to submit GitHub tickets and route them. 

Savannah helps manage Helpdesk, so offering her the permissions to submit and edit tickets is useful to ensure efficient submission for fixes and tracking of issues. 

If possible, it would be great to provide Savannah with access within 1 week.

**Comment by ahamelers** [comment]
Savannah now has access to handle Github tickets
