### ISSUE TITLE
Derive billing email from an author email for payment

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#203]
We talked about this in our meeting and this is the conclusion that we came to with Daniella.

Since ORCID doesn't always give us emails:

1. We can get an email on dataset submission to Merritt by matching the user's ORCID with an Author ORCID and deriving the email from that.  That can be written to the user's record.

2. If there are no ORCID matches, Daniella felt we could just send a bill to the first author who will be in the same research group and they will have to deal with it.

**Comment by ryscher** [comment]
Closed, because it duplicates #204
