### ISSUE TITLE
Remove dataset (DOI: 10.5061/dryad.2fqz612q9)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2031]
10.5061/dryad.2fqz612q9

Remove the "In Progress" dataset DOI: 10.5061/dryad.2fqz612q9, title "Dimensionality and modularity of adaptive variation: Divergence in threespine stickleback from diverse environments" 

Reasoning: author confirmed we will retain the submitted duplicate. 

Low priority.

**Comment by ahamelers** [comment]
This dataset has been withdrawn

**Comment by jleighherzog** [comment]
@ahamelers : If a submission has a status of "In Progress", we can force edit to withdraw if the dataset was previously "submitted". If not, there may not be any checkpoints established (all required files and fields aren't populated) and then we kinda get stuck because we're unable to resubmit without filling in all the blanks. So, we post a ticket to withdraw/remove. However, there's a related ticket submitted to request that those with a 'Curator' role can bypass all submission requirements which should help.

**Comment by ahamelers** [comment]
Aha, that explains things very well! Thanks so much @jleighherzog
