### ISSUE TITLE
Place published dataset back in PPR status (PRIORITY)

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2034]
Can we get this dataset placed back in PPR as soon as possible? It's the one that prompted #2024 (submission oddly lifted out of PPR and into queue by some mysterious auto-notification that the journal didn't send).

DOI: 10.5061/dryad.mkkwh710c
Title: [Data from: Habitat quality influences pollinator pathogen prevalence through both habitat–disease and biodiversity–disease pathways](https://datadryad.org/stash/dataset/doi:10.5061/dryad.mkkwh710c)

**Comment by ryscher** [comment]
Returned to PPR.
