### ISSUE TITLE
PubMed links to Dryad

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2037]
PubMed reports that links from their pages to Dryad are not resolving correctly.

For example: https://pubmed.ncbi.nlm.nih.gov/31988662/ has a a link to Dryad at the bottom of the page. This link goes to https://datadryad.org/discover?query=10.1186/s13068-020-1649-7 -- it should be routed to the landing page for https://doi.org/10.25338/B8ZC80 but this routing is no longer working correctly.

config/routes.rb

**Comment by ahamelers** [comment]
Okay, there are two things here!

1. The routing for < or > 1 identifier results was directing to the API search page, not the blacklight search page as it seems was intended. I've fixed this.
2. This particular ID is not found via the query that would lead to a landing page, which searches internal data (see below)—the DOI 10.1186/s13068-020-1649-7 is not actually associated as the publicationDOI for this submission in internal data. It's in the DC related identifiers as an 'isCitedBy'. The API delivers this as type 'primary_article' but it hasn't made the jump to internal_data.

```sql
SELECT `stash_engine_identifiers`.* FROM `stash_engine_identifiers` INNER JOIN `stash_engine_internal_data` ON `stash_engine_internal_data`.`identifier_id` = `stash_engine_identifiers`.`id` WHERE `stash_engine_identifiers`.`pub_state` IN ('published', 'embargoed') AND (stash_engine_internal_data.data_type IN ('pubmedID','publicationDOI','manuscriptNumber') AND stash_engine_internal_data.value = '10.1186/s13068-020-1649-7')
```

So @ryscher for #2, what should be done there? Should we expand the search to include the dcs_related_identifiers table? Do a data cleanup of similar missing internal_data publicationDOIs? Something else/a combo?

**Comment by ryscher** [comment]
We should update to prefer the related identifiers. The `internal_data` field was used before we had an explicit `primary_article` indicator. 

There is a rake task `stash_datacite:internal_data_to_related_identifier` that converted them, but it looks like it was written a long time ago, and it's likely that someone entered the `internal_data` value through the UI after we had run the conversion.

I suggest re-running the conversion, and removing `publicationDOI` as a valid value from the `internal_data` table.

**Comment by ahamelers** [comment]
Okay, I've updated the search to use the related_identifier, and updated the rake task as well to use primary_article. Added to the pull request.
