### ISSUE TITLE
PPR was requested, but associated manuscript has already been accepted

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2039]
For integrated titles only, we sometimes find this note in the Activity Log:

> "Private for Peer Review was requested, but associated manuscript has already been accepted, so automatically moving to Submitted status"

Sometimes we proceed to curate and other times we check with the author before proceeding. I suspect that the authors don't realize that their attempt to select PPR was overridden by the notification received from the journal office. The data submission finds its way to our queue in 'Submitted' status. Is there a way to let authors know that their submissions won't be held in PPR? 

Pop-up window/notification? 
Custom submission auto-notification template?

**Comment by ryscher** [comment]
It might be nice to disable the PPR checkbox in these cases, and replace it with a notice like "Data will be published immediately, since the article is no longer in review."

**Comment by jleighherzog** [comment]
@ryscher : That's an interesting option. Let me run that by the team this week in our meeting.

**Comment by jeremywalter** [comment]
Another option might be to give the user a pop-up informing them that the PPR isn't going to work for them. Perhaps with some text: "The Private for Peer Review option is not available for this data submission because the article has been accepted for publication by the journal. Upon submission, the dataset will proceed to our curation process for evaluation and publication."

**Comment by jleighherzog** [comment]
@ryscher : What Jeremy posted. :)

**Comment by ryscher** [comment]
Related to ticket #1882

**Comment by jleighherzog** [comment]
@ahamelers : Can we view a mockup for option #2?

**Comment by ahamelers** [comment]
@jleighherzog Sure thing!

Normal:
---

<img width="1015" alt="normal" src="https://user-images.githubusercontent.com/1749394/207899531-47ba08ae-2020-4e4c-8353-76cd846dfcce.png">


Draft for accepted:
---
<img width="1016" alt="accepted" src="https://user-images.githubusercontent.com/1749394/207899572-d4c7ac33-8aa0-4bdd-805a-ed16438fab8e.png">


Draft for published:
---
<img width="1013" alt="published" src="https://user-images.githubusercontent.com/1749394/207899598-d3ed2921-8639-4aa4-a8e3-2fd8074fcca7.png">

**Comment by jleighherzog** [comment]
@ahamelers : Thanks, Audrey. Looks good!

**Comment by ahamelers** [comment]
> @ahamelers : Thanks, Audrey. Re: "**Draft for published**". I don't believe Dryad receives notifications of publication from integrated journals (we might only receive notifications of acceptance). What's the prompt for this text to display?


<img width="1009" alt="Screenshot 2022-12-20 at 16 32 40" src="https://user-images.githubusercontent.com/1749394/208704787-a88003c9-ed34-4336-84d6-407e0bd5e89d.png">

This is one of the cases currently covered by #1882 , as part of that ticket, the PPR option completely disappears if the data submission has previously been published, **or** if the author selects "A published article" in the Preliminary information section. I guess those are technically two different scenarios, so the text should actually have 3 slightly different versions

**Comment by jleighherzog** [comment]
Ok, I think that makes sense to me now. 3 scenarios: 1) published dataset; 2) published article; 3) DOI in metadata field
