### ISSUE TITLE
Remove dataset (DOI: 10.5061/dryad.2280gb5wg)

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2055]
Title: Data_scripts
DOI: 10.5061/dryad.2280gb5wg

The author sent in a HD query saying they'd forgotten their log-in info and want us to withdraw it, but it is 'In Progress' and has never been submitted (to PPR or otherwise), so I can't forcibly edit it to revert it to a previous editable state.

**Comment by ahamelers** [comment]
Done in #2056
