### ISSUE TITLE
Withdraw data submissions: 10.5061/dryad.mkkwh712z; 10.5061/dryad.2280gb5wg

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2056]
Duplicate dataset identified, please withdraw these data submissions: 
**10.5061/dryad.mkkwh712z**
**10.5061/dryad.2280gb5wg**

Submission is "In Progress", the curator is unable to withdraw via Force Edit feature because we don't know whether any checkpoints have been created.

**Comment by ahamelers** [comment]
Both are now withdrawn.
