### ISSUE TITLE
Upgrade to Rails 6

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2059]
- Notes from DMP Roadmap: https://github.com/DMPRoadmap/roadmap/wiki/Rails-Upgrade-Notes
- Merritt's ticket: https://github.com/CDLUC3/mrt-doc/issues/1071

**Comment by ryscher** [comment]
Dryad notes: https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/rails_version_server_upgrade.md

**Comment by ahamelers** [comment]
Useful guides:

https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-2-to-rails-6-0
https://guides.rubyonrails.org/classic_to_zeitwerk_howto.html
