### ISSUE TITLE
Configure auto-PPR process for "Paleontology" and "Papers in Paleontology"

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2060]
Journal office for _**Paleontology**_ and _**Papers in Paleontology**_ would like to configure the Dryad submission site so that all datasets received, that are associated with either of these titles, automatically enter 'Private for Peer Review' status upon submission. 

Additionally, when a notice of acceptance has been received, PPR status should automatically be lifted allowing the dataset to enter the queue for curation in 'Submitted' status.

**Comment by ryscher** [comment]
Settings for these journals have been updated.
