### ISSUE TITLE
AWS Dryad to CDL -- Lambdas and temp storage and deployment

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2061]
There are other tickets about finding the approach for infrastructure as code for AWS Lambdas. (like #2108 ).

- [ ] Deploying that code to the CDL AWS account instead which it sounds like is the preferred place.
- [ ] Addressing permissions for the lambdas to work correctly.
- [ ] Changing any of our lambda calls from our application as needed.
- [ ] Coordinating the deploy.

**Comment by ryscher** [comment]
No longer relevant as we transition away from CDL resources.
