### ISSUE TITLE
Dryad blog appears to be down

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2064]
**Bug description:**

As of 7:45 CEST, the [Dryad blog](https://blog.datadryad.org/) is giving the following error:
"Dryad news is not available at the domain blog.datadryad.org right now. There's a problem with the mapping for this domain. If you are the site owner, please log into your WordPress.com account for more information"
<img width="563" alt="image" src="https://user-images.githubusercontent.com/82666810/196607393-1652815d-cacb-4077-8625-bd216997b540.png">

**Comment by ryscher** [comment]
This is fixed now.
