### ISSUE TITLE
Remove journal info from dataset metadata (DOI: 10.5061/dryad.f1vhhmgz9)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2073]
The related manuscript for this dataset was rejected by the journal, _Functional Ecology_. Can you remove the journal information (journal name, manuscript number) from the metadata please? 

_Note: I'm unable to edit/remove the journal information while in editing mode. Should I instead delete the journal information from the Internal Data section?_

**Comment by ahamelers** [comment]
Hi Jess! The answer is yes, you should remove the journal information—particularly the ISSN!—from the Internal Data section. If you don't remove the ISSN, the title may be repopulated. I've removed the information from Internal Data myself in this case. Please let me know if there are any unforeseen issues.
