### ISSUE TITLE
Please add Lee Dirks and Kevin Smith to list of past BOD members

### ISSUE THREAD

**Issue by gibsonjen** [CDL-Dryad/dryad-product-roadmap#2074]
On the page at https://datadryad.org/stash/our_governance, at the bottom, we list past BOD members in alpha order by last name. We missed Lee and Kevin. Can they please be added? Thank you!

Once done, I'd like to delete this page on Github so that the information is only displayed and maintained in one place. Ryan will let me know if he objects : ) https://github.com/datadryad/governance/blob/main/board_of_directors.md

Thank you!

**Comment by ahamelers** [comment]
@ryscher, if you have the power, can you also accept this pull request? https://github.com/datadryad/governance/pull/3
