### ISSUE TITLE
CEDAR -- UI improvements from CEDAR team

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2079]
These fixes must be implemented by the CEDAR team:
- [x] Fix heading tags to use h1, h2, etc. instead of the MaterialUI cards. 
- [x] Fix problem that resets the margin on the `<body>` element when the cedar JS is opened (This is fixed in https://github.com/metadatacenter/cedar-cee-demo-generic/blob/develop/assets/js/cedar-embeddable-editor-2.6.18-SNAPSHOT.js, but that file also includes problematic changes to the heading tags, so it's not worth updating on its own.)
- [ ] Add hook so we can run tasks after the `Save` button is pressed, such as closing our modal.

**Comment by ryscher** [comment]
Still waiting for the CEDAR team...

**Comment by ahamelers** [comment]
The latest status of these issues: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2830#issuecomment-1741026581

**Comment by ryscher** [comment]
Audrey moved the close button outside the scrollable area, so the modal can always be closed now. And we are automatically saving metadata with each update. Do we still need the `after-save` hook?

**Comment by ahamelers** [comment]
The editor no longer has a save button embedded in it. I think this can be closed.
