### ISSUE TITLE
DPC and waiver updates to be scheduled for release Jan 4, 2023

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2082]
Please schedule the following updates to be implemented on **January 4, 2023**: 

Webpage: https://datadryad.org/stash/faq#cost
Section: How much does it cost? 

> Current text: 
> The base DPC per data submission is $120 USD. DPCs are invoiced upon curator approval/publication, unless the submitter is based at a [member institution](https://datadryad.org/stash/our_membership#institutional) (determined by login credentials), an associated journal or publisher has an agreement with Dryad to sponsor the DPC ([see list](https://datadryad.org/stash/journals)) or the submitter is based in a fee-waiver country (see above).
> 
> Replace with: 
> The base DPC per data submission is $150 USD. DPCs are invoiced upon curator approval/publication, unless the submitter is based at a [member institution](https://datadryad.org/stash/our_membership#institutional) (determined by login credentials), an associated journal or publisher has an agreement with Dryad to sponsor the DPC ([see list](https://datadryad.org/stash/journals)) or the submitter is based in a fee-waiver country (see above).

Dryad Admin site: 

1) Update page 3 of the Dryad submission form ("Review and Submit") to display $150 USD (removing $120). See screen capture below. 

2) Additionally, update the follow texting: 
Dryad charges a fee for data publication that covers curation and preservation of published datasets. Upon publication of your dataset, you will receive an invoice for $150 USD. We’re sensitive to the fact that fees for individual researchers are a burden and create inequities. If you'd like to request a fee waiver, please contact help@datadryad.org 

<img width="1205" alt="Screen Shot 2022-10-28 at 1 42 28 PM" src="https://user-images.githubusercontent.com/76497320/198709408-d4cbb692-cc02-49d3-9e89-c487931a4551.png">

**Comment by ryscher** [comment]
This also requires a change to the `data_processing_charge` in the config file, so the appropriate charges are placed into Stripe invoices.

**Comment by jleighherzog** [comment]
@sfisher : Is it too late to make a minor edit to the text here? Instead read: "We’re sensitive to the fact that fees for individual researchers can be a burden and create inequities. If you'd like to request a fee waiver, please contact help@datadryad.org "

**Comment by sfisher** [comment]
Hi @jleighherzog  I think the only change is "are a burden" to "can be a burden" is that right?

We already deployed yesterday afternoon so it's a lot of work to retag and redeploy for such a small edit.  I could just go edit it on the server and then make changes that will go into the next deploy if that works.

**Comment by jleighherzog** [comment]
@sfisher : Right, that's the only edit (not urgent). Next deply works!
