### ISSUE TITLE
Update rules for author auto-notifications

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2083]
1) When a curator edits a data submission, regardless of status, upon rebuilding/refreshing I believe the author receives an automatic confirmation email. 

For example, this submission (10.7272/Q6Q23XH9) was edited multiple times by a curator in a matter of minutes. I believe that the author received email notifications each time the submission returned to PPR status after being edited. Visit SF case #18031.

Is there a way to eliminate unnecessary auto-emails from being sent to the author? Specifically those notifications that are sent after curators have edited a submission? Perhaps create a rule based on operator? It might be helpful to view a list of rules set up for the auto-emails. 

2) Additionally, would it be possible to capture all auto-notifications sent in the Activity Log? It would be helpful to view all actions in the history for each dataset.

**Comment by ahamelers** [comment]
I have pulled out task 2 into its own ticket, #2153, as it's a different area of the project and might need discussion over details.

**Comment by ahamelers** [comment]
@jleighherzog I've put in a check that won't send the PPR email notification if the submission has ever gone to PPR before. Is that fine, or is there any reason why, or workflow cycle where, you would want users to get multiple PPR notifications?

**Comment by ahamelers** [comment]
@jleighherzog After discussion with Ryan and Scott, we are confused about the workflow that caused this issue and its actual frequency (see commentary in https://github.com/CDL-Dryad/dryad-app/pull/1051). We think that it seems like an unusual set of circumstances. We'd like more information about it, maybe we can have a call in the new year?

**Comment by jleighherzog** [comment]
@ahamelers : Yes, a call sounds great!
