### ISSUE TITLE
Author DOI link not working

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2084]
**Bug description:**
An author emailed in to say:

I have submitted the dataset through Dryad, currently my paper has been acceptable. However it seems that only the peer review link works instead of doi. How can i fix it? 

Please refer below for the dataset information:

The data that support the findings of this study are currently openly available for peer review in Dryad at:

https://datadryad.org/stash/share/SbJT0yK0zeL0dWxOoHmyywctRtJvCFqkBQHHRZg02F4

The DOI of dataset is: https://doi.org/10.5061/dryad.0rxwdbs3k
**Steps to reproduce:**
As above.
**Expected behavior: **
DOI should resolve to dataset.

**Comment by ryscher** [comment]
Dataset is still in PPR. Savannah claimed it to curate earlier today, so I expect the author will hear from her soon (either with a published status, or request for updates).

**Comment by sfisher** [comment]
Yes.  The DOI is not registered with DataCite until an item is embargoed (metadata shown to the public, but not files) or is published.  This is expected behavior.
