### ISSUE TITLE
Allow curators to revert metadata to a previous version

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2086]
We had discussed this in our sprint meetings.  It is harder to revert files since we'd need to re-download them all and re-insert them into S3 and it could be a long process that requires more code, progress indicators, etc.  Jess felt that just being able to revert metadata in a new version to that of a previous version would be enough (and any files that needed to be changed could happen manually).  That is what this ticket is now based on.

This is what I came up with as a basic interface and once clicked it would open the standard curatorial editing screens.  In some cases if a user hasn't submitted their changes then that needs to be taken care of first with some of the other options in the UI (like force edit, etc).

![revert_metadata](https://user-images.githubusercontent.com/105433/214386093-d85554bc-effc-46d1-8c0b-211d7501504d.png)

---
Original text below
---

There are instances when authors attempt to delete their data submission **post-publication** by logging in, deleting all the metadata and/or removing the data files. If they choose to select "Submit", the revised version is resubmitted, assigned to the previously handling curator, and received in "Submitted" status for another round of evaluation prior to republication. 

Curators are unable to decline the revisions and revert to the previous version. Would it be possible to include a feature that would allow curators to 'reject version'? The next step would be for Curators to notify the authors to explain why the previous version will be retained. 

We can talk through some potential options if you like!

**Comment by mariapraetzellis** [comment]
We will look into just reverting the metadata and not the data files.

**Comment by sfisher** [comment]
Hi @jleighherzog 

I looked at the code and when you choose to revert the data, it copies over the original publication date from the version you choose, but does not actually set the publication or embargo status.

This means that it doesn't publish it if that version is published, but I think when it gets published then it would show the date of publication as the original date of the one you copied the data from.  Is this correct behavior or should I blank out the publication date or set it to the current date or something else?
