### ISSUE TITLE
Transfer ownership of data submission (DOI: 10.5061/dryad.98sf7m0mz)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2089]
Please transfer ownership of this data submission to co-author listed below: 

> Title: _Spatial and temporal genetic stock composition of river herring bycatch in southern New England Atlantic herring and mackerel fisheries_
> DOI: 10.5061/dryad.98sf7m0mz

Eric Palkovacs 
epalkova@ucsc.edu
0000-0002-5496-7263

**Comment by ahamelers** [comment]
This is done!

**Comment by jleighherzog** [comment]
@ahamelers : Can we revisit this one? The corresponding author/owner of this data submission is affiliated with UCSC, which means, the cost of the submission should be covered but maybe the system isn't able to register the sponsorship because it was originally submitted by an author affiliated with a non-sponsoring institution. Is that right? Which means, we might not be able to update it now but I can request that the invoice is voided upon publication. That's the workaround.

**Comment by ahamelers** [comment]
Hi @jleighherzog ,

Because this one is still in PPR I believe I was able to edit the database to reflect the new user's sponsorship, so no invoice will be created when it is published. Please let me know if there are any issues!
