### ISSUE TITLE
Database restore tests

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2090]
In order to feel comfortable with getting rid of our database dumps we want to test with IAS and do a fire drill to be sure the restore process works in a way that would work for us and that we know our own database dumps can serve.

I think a minimal process looks like:

- [ ] Make some trackable changes to a dataset or the database. (v3)
- [ ] Do a restore of the database from RDS backup sometime like 2 hours before.
- [ ] Verify changes in the backup are the old values.
- [ ] Be sure we can access the "restore" database separately by a useful means (new connection or whatever) without overwriting our running database or having to restore everything.
- [ ] Test pulling some data out of it such as a dump of a table or a dump of a SQL query for some data.

I think if this all works we'd feel ok with our ability to do selective "rollback" which we've had to do a few times because of data problems, a botched process or an "oops."

We can test restoring an entire database, but I assume that will be easier and will not be the test we're most concerned about, but not a bad idea to try on a dev database or something also.

**Comment by ryscher** [comment]
Ticket was written with IAS in mind, but given the platform transition, we should do this testing in the new platform.

**Comment by ryscher** [comment]
This has been tests as a side effect of other work on the transition.
