### ISSUE TITLE
Zenodo link not generated, DOI: 10.5061/dryad.9zw3r22hr

### ISSUE THREAD

**Issue by Savannahbutler** [CDL-Dryad/dryad-product-roadmap#2094]
The Zenodo link for supplemental information has not been generated for the following dataset:
DOI: 10.5061/dryad.9zw3r22hr
Title: Southward migration of Arctic Ocean species during the last glacial period

**Comment by sfisher** [comment]
Let us know if there is still a problem.  (It shows the supplemental info at https://datadryad.org/stash/dataset/doi:10.5061/dryad.9zw3r22hr and the link seems to open.)

The Zenodo links do not appear until it has been successfully deposited and published at Zenodo which isn't an instant or real-time process for all deposits.  If they have problems or for larger items it can take some time to appear.

It seems to have gone through to me, but let us know.
