### ISSUE TITLE
Add Publisher Integration: Rockefeller University Press

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2098]
**Tenant name:** 
Rockefeller University Press

**Journals:**
Journal of Cell Biology	
Journal of Experimental Medicine		
Journal of General Physiology

**Website**
Add RUP to the list of publisher members.		

**Salesforce notes:**
Publisher account, contacts, and journal accounts set up.

**Logo location:** 
TBD

**Contacts to receive submission notices:** 
TBD
@ryscher @jleighherzog @ahamelers

**Comment by ryscher** [comment]
- Journals updated/created in Dryad
- Publisher name added to website
- Will coordinate with Sarah about notifications of dataset publication and access to dashboards

**Comment by ryscher** [comment]
I added dashboard access for two administrative users.
RUP does *not* want any automated notifications; they will just check the dashboard.
