### ISSUE TITLE
Transfer ownership of dataset DOI: 10.5061/dryad.r2445

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2103]
Please transfer ownership of this dataset to the new corresponding author: 

Benjamin Gilbert
benjamin.gilbert@utoronto.ca
0000-0002-4947-6822

_Note: No longer able to connect with the current corresponding author._

**Comment by ahamelers** [comment]
The ownership has been set, let me know if there are any issues!
