### ISSUE TITLE
Update README pop-up window

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2107]
Please update the README me pop-up window (see screen capture) with the following text. Helpdesk was receiving queries that required more specific guidance on how to use Markdown. This should help!

<img width="741" alt="Screen Shot 2022-11-07 at 8 00 34 PM" src="https://user-images.githubusercontent.com/76497320/201181892-e5ec457e-d504-4c21-ac02-3837bca35f07.png">

If you prefer, you can edit the Markdown online at [hackmd.io](http://hackmd.io/).
1. Open the link (above)
2. Create a new note by clicking “+” at the top left of the screen
3. Copy and paste your text
4. Click the three dots on the top right to download as a Markdown file
5. Rename to ‘README.md’ and upload the file under the _Data_ category

**Comment by jleighherzog** [comment]
Please check to ensure that this pop-up doesn't appear when the .md file is uploaded!

**Comment by ryscher** [comment]
@jleighherzog Can you pass those examples on to us?
