### ISSUE TITLE
Tests act different on local machine than on travis.ci, database history makes weirdness

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#211]
When you run travis-build.rb on a local machine it sometimes gives different results than travis.ci.

This is no good and super annoying.  I believe it has to do with different tables existing locally than the tables that are built from scratch on a new virtual machine everytime travis.ci runs.

The easy solution is to drop all tables in the test database(s) when running bundle exec rake or travis-build.rb.

I suppose this adds a bit of extra time to run tests, but makes them more consistent than if some existing state is causing weirdness.

---

OK, there is probably more to this than that.  I believe that travis.ci uses the travis-prep.sh and symlink_config.sh.  I believe we used to have a more nuanced symlinking procedure for config files and Daisie changes some of this.

The main problem is that locally we have real config files with secret information in them from the private config respository.  On travis it just copies over the example ones.

It would be nice if the test suite ran against the example ones, also.  But doing so would mean renaming the real ones and then copying the example ones or some such thing.  It could get messy.

Alternately, we need to be very careful to keep the real and example/test  configs in strict sync as much as we can.

---

The easiest way to fix this may be to switch all the yml files to be read out of dryad-config-example when running RAILS_ENV=test so that tests always run off the example rather than the real files and then to remove the test sections from all real configs.

**Comment by briri** [comment]
This is a great idea.

**Comment by sfisher** [comment]
I think this is done until it rears its head again and we have to deal with it again.  It's been pretty OK the past few weeks.  (Knock on wood.)
