### ISSUE TITLE
PRIORITY: Update membership web page

### ISSUE THREAD

**Issue by gibsonjen** [CDL-Dryad/dryad-product-roadmap#2112]
I've got a couple of web-text updates, please. I've got one set of tiny edits to the homepage and then a request to overwrite the copy at https://datadryad.org/stash/join_us

All details here.
@mariapraetzellis: Forever in debt if these can be included in the next sprint. Need to align comms and marketing with increasing demand for data services. 

https://docs.google.com/document/d/1RGvqxLCqYETrE7CYmc_yxJhaYtaXKUVE_WLaRN1u-rg/edit#

Thank you!

**Comment by ahamelers** [comment]
@gibsonjen Are the edits in the document ready to go? If so, could you accept or reject the edits present there?

**Comment by gibsonjen** [comment]
@ahamelers All set now. Thanks!
