### ISSUE TITLE
PRIORITY - place published dataset back into PPR (DOI: 10.5061/dryad.2jm63xss9) 

### ISSUE THREAD

**Issue by Savannahbutler** [CDL-Dryad/dryad-product-roadmap#2115]
Please prioritize placing this dataset back into PPR (current status: In Progress):
DOI: 10.5061/dryad.2jm63xss9
Title: Area, connectivity and plant life strategy diversity and abundance in temporary ponds of Southeastern Carpathians (Romania, Europe)
Initial publication date: July 11, 2022

**Comment by jleighherzog** [comment]
@mariapraetzellis : Can we prioritize this ticket please?

**Comment by ryscher** [comment]
Dataset returned to PPR.
