### ISSUE TITLE
Code deployed to development machine going bonkers with emails

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2116]
The code that is deployed on dev is this revision

```
commit a720158005812726171cca99e10e13935d27bac7
Author: Ryan Scherle <ryan@scherle.org>
Date:   Sat Nov 12 22:30:49 2022 +0000

    move into resource so it can be called easier
```

I submitted a new dataset in the development environment around 3:30.  I got hundreds of emails telling me my dataset had been submitted (like 3 a minute).

I finally had to go into the database and delete my dataset from the database.

I suspect this is being triggered by some update to one rails model that triggers another update to another model (like last modified and does this in a circular way so it spams everyone to death).

I think it's likely a callback on a model (before___ or after__).  Likely if something should be updated in tandem with an event couple places it's best to put the manually in rather than tying it to every change or save in the model.

IDK for sure if that is what is happening but I suspect it could be.  Maybe salesforce updates or something else that changed recently and got deployed to dev.

**Comment by ryscher** [comment]
Ugh. Sorry about that. Fixed now.

It wasn't actually cascading updates. It was silly Rails behavior of terminating the callbacks when something returns false, so the notifier just kept trying to update the status, and each time it would get most of the way through the process before rolling back. I've seen some sources that claim this behavior was removed in Rails 5, others claim it was removed in Rails 6.

**Comment by sfisher** [comment]
Thanks for finding this and figuring this out, Ryan!
