### ISSUE TITLE
Add Tenant: Washington

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2119]
**Tenant name:** 
University of Washington Libraries

**Logo location:** 
See comment below

**Contacts to receive submission notices:** 
Jenny Muilenburg
Data Management Librarian
jmuil@uw.edu

**Shibboleth info, if not in [InCommon](https://incommon.org/community-organizations/):**
urn:mace:incommon:washington.edu

Tasks:
- [ ] add config to dryad-config repo
- [ ] add logo to dryad-app repo
- [ ] deploy and test on stage (institution should log in to verify working as expected)
- [ ] update tenant_id for users in the database who have emails with the institutional domain name
- [ ] add institution's name to the Dryad website

**Comment by mariapraetzellis** [comment]
![Wordmark_stacked_Purple_Hex](https://user-images.githubusercontent.com/27511575/210673947-acc2da32-1eb6-4738-a625-8508ae19ef70.png)
