### ISSUE TITLE
System automatically sets affiliation to "ALL CAPS" case

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2121]
DOI: 10.5061/dryad.5mkkwh795
Title: Bayesian species distribution models integrate presence-only and presence-absence data to predict deer distribution and relative abundance

One of the affiliations in this dataset (Deer Management Solutions) is displayed in ALL CAPS formatting. This is not an affiliation matched in ROR, but I have not had issues with unmatched affiliations recently. Attempted unsuccessful fixes:

- Manually re-entering in title case
- Entering 'N/A', clicking over to Review and Submit to cache change, and re-entering in title case
- Creating new author entry and manually entering in title case

![Screen Shot 2022-11-17 at 9 53 47 AM](https://user-images.githubusercontent.com/113212676/202521057-d71c5ed6-82b1-4365-a372-44f9e145f562.png)

**Comment by sfisher** [comment]
This happens because it uses entries for previously entered institutions when it makes a (non-case-sensitive) match.  It apparently got entered in ALL CAPS which became the entry for the name of that institution.  It is fixed now.
