### ISSUE TITLE
Add Code/Software documentation instruction to README template

### ISSUE THREAD

**Issue by AmeliaCulpP1819** [CDL-Dryad/dryad-product-roadmap#2122]
After discussions with curation team, we would like to recommend adding this section to the README template to instruct authors to, at least minimally, document their code:

Code/Software
If your submission contains scripts, code, or notebooks (e.g., R, Python, Mathematica, MatLab), describe each of those files as well as the software versions (including loaded packages) that you used to run those scripts. If your repository contains more than one file whose relationship to other scripts is not obvious, provide information about the workflow that you used to run those scripts and notebooks.

**Comment by ahamelers** [comment]
I changed the wording some to match the other sections. I also edited the middle section to make it more clear what is instructional and what is the template structure to be followed.

---
# Title of Dataset
---

Give a brief summary of dataset contents, contextualized in experimental procedures and results.


## Description of the data and file structure

This is a freeform section for you to describe how the data are structured and how a potential consumer might use them. Be as descriptive as necessary. Keep in mind that users of your data might be new to the field and unfamiliar with common terminology, metrics, etc.


Describe relationships between data files, missing data codes, other abbreviations used. Be as descriptive as possible.


## Sharing/Access information

This is a section for linking to other ways to access the data, and for linking to sources the data is derived from, if any.

Links to other publicly accessible locations of the data:
  * 

Data was derived from the following sources:
  * 


## Code/Software

This is an optional, freeform section for describing any code in your submission and the software used to run it.

Describe any scripts, code, or notebooks (e.g., R, Python, Mathematica, MatLab) as well as the software versions (including loaded packages) that you used to run those files. If your repository contains more than one file whose relationship to other scripts is not obvious, provide information about the workflow that you used to run those scripts and notebooks.
