### ISSUE TITLE
Update Dryad site mentions of "repository" (PRIORITY)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2123]
As requested, please update the Dryad site to replace mentions of "Dryad Digital Repository" with "Dryad Data Platform" (where it makes sense). Jeremy has been tasked with identifying and editing all relevant text that needs to be updated. 

See related ticket: https://github.com/CDL-Dryad/dryad-app/pull/1008#issue-1454010191

**Comment by ryscher** [comment]
This partially addresses https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2123

There are a few places where internal code needs to be updated. Some code includes "Dryad Digital Repository", particularly when metadata is sent to Datacite and PubMed.

**Comment by jleighherzog** [comment]
Jeremy has provided a markup with the edits needed
