### ISSUE TITLE
Add Tenant: University of Rochester

### ISSUE THREAD

**Issue by mariapraetzellis** [CDL-Dryad/dryad-product-roadmap#2125]
**Tenant name:** 
University of Rochester
**Logo location:** 
Attached
**Contacts to receive submission notices:** 
s.pugachev@rochester.edu
**Shibboleth info, if not in [InCommon](https://incommon.org/community-organizations/):**
https://shib2.its.rochester.edu/idp/shibboleth
Tasks:
- [x] add config to dryad-config repo
- [x] add logo to dryad-app repo
- [x] add institution's name to the Dryad website 
![URlogo](https://user-images.githubusercontent.com/27511575/203120427-554a5b99-6815-4313-902b-92ccc73308ef.png)
- [x] deploy and test on stage (institution should log in to verify working as expected)
- [ ] update tenant_id for users in the database who have emails with the institutional domain name

**Comment by ryscher** [comment]
Deployed on dev server and ready for testing.

![Screenshot 2022-12-16 at 11 31 04 AM](https://user-images.githubusercontent.com/605143/208144890-04fdd212-54a4-4d2b-92e2-6ff37c6da107.png)

**Comment by mariapraetzellis** [comment]
Received confirmation that this is working in stage
