### ISSUE TITLE
Add "total size" to file upload page

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2126]
Requested to help users and curators stay under the 300GB limit. 

Somewhere on the page for `Upload your files`, add an indicator of the total size of files currently attached to the dataset.

**Comment by ahamelers** [comment]
If we add a column in the database for the current total size that would solve this issue as well: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/1695
