### ISSUE TITLE
Return published data submission to PPR status (DOI: 10.5061/dryad.pzgmsbcqw)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2129]
Title: Rapid evolution of a brood parasite’s egg pattern does not lead to large increases in mimetic fidelity
DOI: 10.5061/dryad.pzgmsbcqw

Can you please remove the published files from public view and return this data submission to 'Private for Peer Review' status? The author is aware of the PPR checkbox and it sounds like there was some legitimate error that prevented the status from sticking.

**Comment by sfisher** [comment]
This is back in PPR.
