### ISSUE TITLE
Check that Dryad is consistent in the doi case that we're using

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#213]
@dmolesUC3 Mentioned that we're using all different cases for DOIs.

We need to check that we're consistent in the case we use between systems or not changing case or always using the same case -- if it's case sensitive.  I believe in all the UI we use the case that EZID (or the EZID Gem) gives us without ever transforming it (need to verify), though the "doi:" prefix is lower since it is tacked on to distinguish DOIs from other identifiers (which we really never used).  EZID or the EZID gem gives it to us uppercase when we mint, I believe (but need to verify).  DataCite is generated differently and is probably lowercase.

We'll need to check the full process to see if we're ever transforming the case (such as in Sword submissions and other stuff) and also make sure it the Merritt side doesn't transform it either.  In the update_uris Merritt-Sword is returning, it is all in lower case.  I'm not clear if it's because we transform it before submitting to Merritt-Sword or if it's doing transformations.

**Comment by ryscher** [comment]
Standardized long ago
