### ISSUE TITLE
Search using journal name

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2138]
I spoke with Rebecca Cunning today (JXB Editorial Office). Using the [Explore Data](https://datadryad.org/search) page, she searched for all published submissions linked to _Journal of Experimental Botany_. We both retrieved only 7 results. 

Rebecca provided an example of a published data submission that is not appearing in the search results: 
[Assembled RNA-seq data of Bougainvillea peruviana Thimma](https://datadryad.org/stash/dataset/doi:10.5061/dryad.sj3tx964z)
10.5061/dryad.sj3tx964z

I've checked the metadata and confirmed that the journal name is properly matched to an entry in the Journal Title field drop-down menu. Please investigate.

**Comment by jleighherzog** [comment]
Dataset now available in search results

**Comment by jleighherzog** [comment]
Reinstating the ticket. If I search on the title, I find a result. If I search by journal title, the published dataset isn't included in the results. This might be an issue for other journal titles so, it would be worthwhile to investigate.

**Comment by ryscher** [comment]
I'm not certain we ever supported searching with a journal name in the initial search box. But it seems like a reasonable feature to add.

**Comment by sfisher** [comment]
Changed in SOLR on

- [ ] Development
- [ ] Stage
- [ ] Production
