### ISSUE TITLE
Journal Clean-up list: DOIs requested (PRIORITY)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2139]
Please refresh re-pull a new list of submissions that require [clean-up](https://docs.google.com/spreadsheets/d/1WBLcVRYWj08fEz_M6-Hw2JbxfzVKmW9F1jkdelSTXa8/edit#gid=0) to the journal title metadata. 
With this pull, it would be useful to include the DOIs. 

A Drexel LEADING fellow is working on this project.

**Comment by ryscher** [comment]
Since the LEADING fellow is actively working in the spreadsheet, I will not regenerate the entire sheet. I will just fill in DOIs for the items where required.
