### ISSUE TITLE
Dryad Shibboleth Service Providers (SP) for both stage and production

### ISSUE THREAD

**Issue by marisastrong** [CDL-Dryad/dryad-product-roadmap#214]
For the production instance, Dryad should have it's own SP defined as opposed to utilizing the Dash SP (which is what we are doing for dryad-stg; it's defined as an endpoint under the dash-stg.cdlib.org entityID).  this SP will apply for membership in the Incommon Research & Scholarship category.  For completeness and clarity, we should also create an SP for dryad-stg which we can use instead of Dash.  Once live, we can delete all the old Dash supported SPs.  

- [x] Create production datadryad.org SP along with all required Incommon Metadata https://spaces.at.internet2.edu/display/InCFederation/User+Interface+Elements
- [ ] create self-signed certificate for SP - included in above metadata
- [ ] privacy policy URL needs a home
- [ ] Apply for R&S category
- [ ] update XML for IdPs to release required attributes to the Dryad SPs
- [ ] update shibboleth documentation 
- [ ] confirm attributes that are being returned Attribute Name are needed:
displayName
eduPersonPrincipalName
givenName
mail
sn

**Comment by marisastrong** [comment]
@jimvanderveen is it possible to create a cert for the Incommon Metadata if we don't have the server provisioned  yet?

**Comment by marisastrong** [comment]
link to logo is here https://dryad-dev.cdlib.org/images/logo_dryad.png

**Comment by jimvanderveen** [comment]
@marisastrong Yes, I can generate the key pair and store it on the Puppetmaster.  https://wiki.shibboleth.net/confluence/display/CONCEPT/SAMLKeysAndCertificates#SAMLKeysAndCertificates-CreatingaSAMLKeyandCertificate

**Comment by marisastrong** [comment]
notes on the SP Incommon Metadata configuration
the following fields will need to be udpated when we have current information that is publicly available:
update logo
update privacy policy URL
Include this SP metadata in the InCommon export aggregate

The SP has been submitted for production is being reviewed by UCOP ITS.

**Comment by marisastrong** [comment]
@jimvanderveen i created the metadata using the current Dash certificate.  So when we build out the Dryad production server, we can copy over the Dash cert key files.  Optionally, we can create new ones at that time if necessary.

**Comment by jimvanderveen** [comment]
When we're ready to create a new key, the script is `${INSTALL_ROOT}/etc/shibboleth/keygen.sh`
For the `yum` package, install root is simply `/`

**Comment by ryscher** [comment]
This work was completed long ago.
