### ISSUE TITLE
Biology Letters concerned re: not receiving notifications for deposits to Dryad

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2140]
_**Biology Letters**_ have asked us to check and confirm that emails for all data submissions are sent to their inbox. They mentioned that they sometimes receive the Dryad emails with the exception of **transferred papers**.

Biology Letters  [biologyletters@royalsociety.org](mailto:biologyletters@royalsociety.org)

This is what they said:
> "I think we get most of the notifications but not all. The attached is an example where the author deposited their dataset in Dryad but we didn’t get the email with the temporary Dryad URL or final Dryad DOI. We noticed in their submitted manuscript that they included the final DOI but of course that leads to an error page as this hasn’t been accepted yet. We did a search for the email with the temporary URL but don’t seem to have got this, so we unsubmitted and asked the author to include this instead. This was transferred from Proc B so I thought maybe you guys got the Dryad email but the authors seemingly deposited their data on 4th November, which is when it was with us." 

DOI: 10.5061/dryad.15dv41p1f

**Comment by jleighherzog** [comment]
Contacts: 
Shalene Singh-Shepherd [Shalene.Singh-Shepherd@royalsociety.org]
Phil Hurst [Phil.Hurst@royalsociety.org]

**Comment by ahamelers** [comment]
Hello @jleighherzog, 

The settings are such that journals can be set to receive email notifications when 1) a submission is published and 2) when a submission is set to peer review. The Biology Letters email address is set to receive emails in both these cases, and as far as we can tell they are going out successfully! In the specific case in question, the submission has never been completed and is still In Progress, so the journal would not have received any notification. Possibly the author is unaware that they have not completed their submission.

You've given us a couple of additional contact email addresses. Just to clarify, were these just to be contacted if we had additional questions about this issue? Or did you want us to add them to the list of addresses to receive emails for all Biology Letters notifications?

Thanks,
Audrey

**Comment by ryscher** [comment]
Thinking back to our conversation in the sprint meeting, I believe I had asked Jess for the contact info so we could reach out and fully settle the issue of whether they are missing emails. Jess, if they still have concerns after you relay the above info, I'm happy to have a call with them.
