### ISSUE TITLE
Accessibility updates for CEDAR

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2144]
See notes from the UX team at:
https://docs.google.com/document/d/1Q2JBslDvxaC7iqYoR10ga39KdS4Rhnh0T_BRTeNf5Q8/edit?usp=sharing

**Comment by ryscher** [comment]
Cannot be performed until #2079 is done.

**Comment by ahamelers** [comment]
The latest status of these issues: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2830#issuecomment-1741026581
