### ISSUE TITLE
Update email distribution list for Paleobiology

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2146]
Received this request from the _Paleobiology_ journal office: 

Could you remove Mark Patzkowsky [mep12@psu.edu] from the email distribution list? 
His Editor-in-Chief term has ended and is no longer an editor for the journal.

**Comment by ryscher** [comment]
His email has been removed from both the `notify_contacts` and `review_contacts`.
