### ISSUE TITLE
Testing of Rails 6 manually

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2148]
https://docs.google.com/document/d/1BTCx1ELZaUJ6yF3-FH8R-RWSlUMvaCa2Ldw5QUv16mI/edit#heading=h.d8bac851fe0n

**Comment by sfisher** [comment]
Hi @ahamelers and @ryscher .  I've gone through most of the document and put 🎃  by the ones I tested manually and put 💩  by a few that aren't working (I think the geoblacklight search is borked with some version conflicts and or customizations).

To me it looks like most stuff is working though I haven't finished going through the full list completely yet.  It took a long time to figure out how to test a few things and we have a TON of features that are really not evident from normal usage.  There is a ton of stuff in there.

Also, a couple places some things are wonky but I think are existing problems that aren't huge severity and not unique to the upgrade.

**Comment by sfisher** [comment]
I finished a round and didn't find a much that was a severe error except geoblacklight problems.  A couple of minor things.

**Comment by ahamelers** [comment]
I am mad that Ryan beat me to using the 🤖 emoji
