### ISSUE TITLE
Update institution selection box

### ISSUE THREAD

**Issue by briri** [CDL-Dryad/dryad-product-roadmap#215]
Replace the existing institution selection box with the accessible auto-complete widget used in the DMPTool. related to #189

<img width="1014" alt="screen shot 2019-02-19 at 9 06 38 am" src="https://user-images.githubusercontent.com/1204467/53033338-b1a00780-3425-11e9-8368-0fea61ef5816.png">

Pull in appropriate JS files and create a new ui-library component. The DMPTool files can be found here:  
- 3rd party include for the accessible auto-complete component: https://github.com/DMPRoadmap/roadmap/blob/4d9665ef8c76736ac750fe6ed0763da26be2a0f3/package.json#L36
- Custom JS: https://github.com/DMPRoadmap/roadmap/blob/master/app/javascript/utils/autoComplete.js
- ERB partial: https://github.com/DMPRoadmap/roadmap/blob/master/app/views/shared/_accessible_combobox.html.erb
- Example of partial being used: https://github.com/DMPRoadmap/roadmap/blob/4d9665ef8c76736ac750fe6ed0763da26be2a0f3/app/views/shared/_my_org.html.erb#L10

**Comment by jimvanderveen** [comment]
@briri does this involve the Shibboleth discovery feed, like the JS files & related CSS etc that are under Puppet management on DMPTool?

**Comment by briri** [comment]
no @jimvanderveen

**Comment by ryscher** [comment]
Note: This is for the *tenant* selection box when a user first logs in. We should standardize it to use the same autocomplete framework as the submission system uses.

**Comment by ahamelers** [comment]
This issue seems a bit out of date—half of the links no longer work. Is this something we still want to do? @ryscher @briri

**Comment by ryscher** [comment]
Yes, the overall issue is still something we want. The tenant selection list is getting too long for a simple dropdown.

I wouldn't worry about the outdated links to DMP's autocomplete. We want to use our existing autocomplete in that new location. (Also requires adding React to the page.)

**Comment by ahamelers** [comment]
Okay, thanks Ryan, then do you agree it makes sense to do it in concert with #653 ?
