### ISSUE TITLE
Wordpress blog: changes to styles and presentation

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2150]
**Problem description, and links to relevant helpdesk tickets:**
With a growing volume of content going out via our Wordpress site, we’d like to improve the site’s functionality, slightly, and bring the styling closer in line with the Dryad platform. Jen and Sarah request the following updates to [Wordpress](https://blog.datadryad.org/).

**Describe the solution you'd like:**
- Change the presentation on the index page so that snippets for each blog (title, first few lines and maybe date) are displayed only – and not the full text for each blog.

- Disable the plug-in that supports auto-posting to Twitter. It has lost its connection to our Twitter account and isn't necessary for our social media strategy.

- Enable manual creation/editing of URLs. Wordpress currently auto-generates a URL and does not allow changes. I'd like to be able to edit the URL manually (before publication) so I can have greater control when planning social media campaigns around blog posts.

- Change the heading and body (read: all) fonts to match the Dryad website in style and colour. So, Open Sans/Roboto (?) and Orange (#cf4817) for H1 and Blue (#005581) for H2. 

- Increase default size of H2 to 20px

- Revise default button to match styles at https://wordpress.com/post/blog.datadryad.org/4819. 

**Additional context:**

January delivery if possible?

**Comment by ahamelers** [comment]
The following are currently possible:

>- Change the heading and body (read: all) fonts to match the Dryad website in style and colour. So, Open Sans/Roboto (?) and Orange (#cf4817) for H1 and Blue (#005581) for H2.
>- Increase default size of H2 to 20px

The rest are not possible while continuing to use wordpress.com for hosting without a "business" account. A version of this first one is possible, but we would lose the sidebar, and the automatic loading of additional posts on scroll:

> - Change the presentation on the index page so that snippets for each blog (title, first few lines and maybe date) are displayed only – and not the full text for each blog.
>- Disable the plug-in that supports auto-posting to Twitter. It has lost its connection to our Twitter account and isn't necessary for our social media strategy.
>-  Revise default button to match styles at https://wordpress.com/post/blog.datadryad.org/4819.


This I don't think is possible hosting on wordpress.com at any level (but would be possible self hosting wordpress)

>- Enable manual creation/editing of URLs. Wordpress currently auto-generates a URL and does not allow changes. I'd like to be able to edit the URL manually (before publication) so I can have greater control when planning social media campaigns around blog posts.

**Comment by sarahklippincott** [comment]
Thanks for this review @ahamelers. Currently discussing with Jen and looking into upgrading to a business plan. I think we can ditch the last item as it probably doesn't make sense to customize to that degree or to self-host.

**Comment by sarahklippincott** [comment]
@ahamelers Mark has just upgraded the Wordpress account. Can you confirm that you'd be able to address the following three features with this change in place?

- Change the presentation on the index page so that snippets for each blog (title, first few lines and maybe date) are displayed only – and not the full text for each blog.
- Disable the plug-in that supports auto-posting to Twitter. It has lost its connection to our Twitter account and isn't necessary for our social media strategy.
- Revise default button to match styles at https://wordpress.com/post/blog.datadryad.org/4819.

**Comment by ahamelers** [comment]
Yes, these 3 should be possible now. I'll get to work on the full list of 5 items.

**Comment by ahamelers** [comment]
All the requested items are completed. I also changed the menu bar color. Let me know if anything isn't what you were expecting @sarahklippincott, or if anything was missed.

Technically we can make much more drastic changes now (i.e., making entirely our own wordpress theme), so that is something to think about for the future.

**Comment by sarahklippincott** [comment]
This looks amazing. What a difference a few changes make! I reviewed the changes and don't see anything missing.
