### ISSUE TITLE
Search -- removing criteria

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2159]
1. Search for a term, such as "data"
2. Filter the results using one of the facets on the left -- the result list will correctly update
3. Below the search bar, click the 'x' to remove your original search term, leaving only the filter -- the result list will *not* update

**Comment by sfisher** [comment]
I do not see this happening when I try.  When I remove "data" after choosing other filters then the list updates and I see more in the list afterward.

Can you confirm this is happening?  If not, lets close this one.

**Comment by ryscher** [comment]
I confirm that the feature is working properly. I wonder whether it was fixed in the past two months, or was I just hallucinating?

**Comment by ahamelers** [comment]
@ryscher I think we did some changes and upgrades to geo/blacklight gems as part of the ruby and rails upgrades.
