### ISSUE TITLE
Add links to HSI and ES guidelines on the "Upload Files" page of submission process

### ISSUE THREAD

**Issue by Savannahbutler** [CDL-Dryad/dryad-product-roadmap#2163]
On the "Upload files" page of the submission process, please include links to the human subjects and endangered species policies. Specifically, it would be helpful to include within the checkbox text (underneath file uploads) that states " *I confirm that no Personal Health Information or Sensitive Data are being uploaded with this submission." (screenshot for reference). 

Suggested text: 
Data archived in Dryad are publicly available, and any human subjects data or species data must be properly anonymized and prepared under applicable legal and ethical guidelines. For human subjects guidance, click [here](https://datadryad.org/docs/HumanSubjectsData.pdf). For species conservation guidance, click [here](https://datadryad.org/docs/EndangeredSpeciesData.pdf)."
[separate line below] * I confirm that no Personal Health Information or Sensitive Data are being uploaded with this submission.

![Screenshot 2022-12-08 15 52 56](https://user-images.githubusercontent.com/114602548/206565700-499279d2-1a01-4859-835b-5e1ba2935691.png)

**Comment by ahamelers** [comment]
Hi Savannah,

For accessibility reasons, "click here" or "here" are not adequate link text. A better option might be something like:

>Data archived in Dryad are publicly available, and any human subjects data or species data must be properly anonymized and prepared under applicable legal and ethical guidelines. Please see our [human subjects guidance](https://datadryad.org/docs/HumanSubjectsData.pdf] and [species conservation guidance](https://datadryad.org/docs/EndangeredSpeciesData.pdf).

**Comment by ahamelers** [comment]
Also, what with the site switching to sentence casing in general, is the capitalization in the following still preferred?

>I confirm that no Personal Health Information or Sensitive Data are being uploaded with this submission.

**Comment by jleighherzog** [comment]
@ahamelers : I don't think so. I always thought it was strange that those words were capitalized.

**Comment by Savannahbutler** [comment]
@ahamelers thanks for letting me know! The updated text looks good on my end.
