### ISSUE TITLE
PRIORITY: New rules for the availability of the Reviewer URL

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2165]
Can you configure the site so that the Reviewer URL is **not active** or **deactivated**: 

When the status of a data submission is set to '**Withdrawn**' so that none of the data files are accessible (especially if there is sensitive human/species data present)

Additional concern: 
When datasets are placed in AAR status for HSI or species-related modifications or while we await author action/responses the data is technically available via the Reviewer URL (also accessible while in 'PPR' status, 'Submitted' status, etc. -- essentially anytime pre-publication). Thoughts on how we might better manage the availability of data files prior to approval for publication?

**Comment by jleighherzog** [comment]
Explore providing a password-protected Reviewer URL (suggested by Bryan). Example: [Morphobank](https://morphobank.org/)

**Comment by jleighherzog** [comment]
@sfisher : Awesome! Deactivated for all withdrawn submissions from this point forward or will it also include past submissions in withdrawn status?

**Comment by sfisher** [comment]
This will also work for old submissions.  As long as the status is still withdrawn then it disallows use of the PPR reviewer url.
