### ISSUE TITLE
13 datasets currently status'd as PPR after having been previously published

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2167]
While I was sorting through the PPR data to investigate that bug (pull [1041](https://github.com/CDL-Dryad/dryad-app/pull/1041)) and then seeing Jess' recent ticket (#2166), I noticed that there were several datasets set as PPR that had citations – 13 in total. 11 of them were published by a curator and then accessed and set back to PPR by the author, where evidently they "remain," with regular reminders being sent. Although the Activity Log often reads "System auto-assigned curator," there is no indication that one was actually (re)assigned. 

- [10.5061/dryad.nvx0k6dvj](https://datadryad.org/stash/ds_admin/activity_log/87982?), published May 9, 2022; reverted to PPR by author on May 30, 2022; citations: 2
- [10.5061/dryad.2v6wwpzhp](https://datadryad.org/stash/ds_admin/activity_log/39726?), published December 30, 2019; reverted to PPR by author on May 6, 2021; citations: 2. Note that Aadithya is assigned this dataset, but the Activity Log does not show an auto-reassignment. This one also looks similar to Jess' #2166 issue; the citations are 2010 and 2015 for an article published in 2019.
- [10.5061/dryad.d51c5b04g](https://datadryad.org/stash/ds_admin/activity_log/78281?), published January 9, 2022; reverted to PPR by author on January 9th, 2022; citations: 2. Note that Joe is assigned this dataset (and published it), but the Activity Log does not show the system correctly returning the dataset to him for curation.
- [10.5061/dryad.9p8cz8wfw](https://datadryad.org/stash/ds_admin/activity_log/65208?), embargoed for 1 yr on January 17, 2022; reverted to PPR by author on May 3, 2022; citations: 1. 
- [10.5061/dryad.cfxpnvx35](https://datadryad.org/stash/ds_admin/activity_log/48677?), published on July 21, 2020; reverted to PPR by another curator on July 22, 2020, after author resubmitted (no PPR designation indicated with resubmission); citations: 1
- 1[0.5061/dryad.3r2280ghs](https://datadryad.org/stash/ds_admin/activity_log/82803?), published on February 2, 2022; reverted to PPR by author on April 3, 2022; citations: 1. Note that Jeremy is assigned this dataset (and published it), but the Activity Log does not show the system correctly returning the dataset to him for curation.
- [10.5061/dryad.xwdbrv19j](https://datadryad.org/stash/ds_admin/activity_log/41029?), never published, last submitted with PPR on March 22, 2021; citations: 1. Note that this is the only one where clicking on the 'Citation' brings up an empty box; this one also has 0 views and 0 downloads (all others have >0).
- [10.5061/dryad.m37pvmd07](https://datadryad.org/stash/ds_admin/activity_log/50451?), published on August 29, 2020; reverted to PPR by author on April 31, 2020. System shows no evidence of attempting to auto-assign curator or return to original; citations: 1.
- [10.5061/dryad.bk3j9kdcc](https://datadryad.org/stash/ds_admin/activity_log/71414?), published on January 10, 2022; reverted to PPR by author on January 10, 2022; citations: 1.
- [10.5061/dryad.msbcc2fzf](https://datadryad.org/stash/ds_admin/activity_log/74477?), published on August 26, 2021; reverted to PPR by author on December 9, 2021; looks like a classic "the author scrubs the metadata to try to unpublish it"; citations: 1.
- [10.5061/dryad.931zcrjns](https://datadryad.org/stash/ds_admin/activity_log/91306?), intentionally returned to PPR by Jess/Ryan after initial curation (never published); citations: 1.
- [10.5061/dryad.vt4b8gtv9](https://datadryad.org/stash/ds_admin/activity_log/89545?), published on May 12, 2022; reverted to PPR by author on July 27, 2022; system last assigned to Molly but did not reassign evidently because of PPR; citations: 1.
- [10.5061/dryad.pc866t1rg](https://datadryad.org/stash/ds_admin/activity_log/89101?), published on May 24, 2022; reverted to PPR on May 25th by author; Jess is assigned as the most recent editor but Amelia was the one who published it; citations: 1.

For some of these (but hardly all), the "citation" is the linked Zenodo submission (which I don't think should be counting as a citation anyway?), but that suggests that there could be more datasets that have been reverted back to PPR by the author and that don't have a citation because they don't have a Zenodo counterpart.

**Comment by bryanmgee** [comment]
@sfisher Thanks Scott! I ended up down this rabbit hole because we got a HD inquiry from one of these authors who got one of the automatic PPR reminder blasts that went out recently, and they were very confused about what was going on

**Comment by ahamelers** [comment]
@bryanmgee I'm going to mark this as closed, please reopen if Scott's answer didn't clear everything up!
