### ISSUE TITLE
System won't allow me to re-assign published dataset to another curator

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2171]
DOI: 10.5061/dryad.66t1g1k2g
Title: Performance and refinement of nitrogen fertilization tools

I just published this dataset from the Curation status (Jeremy was having an issue with it and was the previously assigned curator). After successfully publishing the dataset, it won't allow me to re-assign the dataset back to him and gives this message.

![Screen Shot 2022-12-09 at 6 14 05 PM](https://user-images.githubusercontent.com/113212676/206823891-b6f1dbe4-3b32-4bc4-a2d8-f61bc9f233fd.png)

**Comment by ryscher** [comment]
This was due to an internal bug. I manually set the curator back to Jeremy, and made a code update to prevent the problem in the future.
