### ISSUE TITLE
Add Publisher Tenant: American Ornithological Society

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2173]
**Tenant name:** 
American Ornithological Society

**Logo location:** 
TBD

**Contacts to receive submission notices:** 
Probably Mark Penrose, Managing Editor, Ornithology & Ornithological Applications
aospubs@americanornithology.org

**Journals**
Ornithological Applications
Ornithology

**Shibboleth info, if not in [InCommon](https://incommon.org/community-organizations/):**

Tasks:
- [ ] add config to dryad-config repo
- [ ] add logo to dryad-app repo
- [ ] deploy and test on stage (institution should log in to verify working as expected)
- [ ] update tenant_id for users in the database who have emails with the institutional domain name
- [ ] add institution's name to the Dryad website 
@ryscher @mariapraetzellis @jleighherzog

**Comment by ryscher** [comment]
Both of these journals are already in Dryad with a "subscription" payment plan sponsored by American Ornithological Society, so I don't think any technical changes are needed.

**Comment by sfisher** [comment]
We may also want to add a different template for journals since this one for adding a "tenant" partner institution isn't really the correct information or process.

**Comment by ryscher** [comment]
Oh, I did make a new template, but after this was done.
