### ISSUE TITLE
PRIORITY: Deactivate Reviewer URL (DOI: 10.5061/dryad.cjsxksn9f)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2176]
Possible to deactivate the Reviewer URL for this data submission? The link is currently available online (published with the preprint) and the journal requires a double-blind review process. 

Title: Long-term ecological responses of a Dipterocarp forest to climate changes and nutrient availability
DOI: 10.5061/dryad.cjsxksn9f

**Comment by ryscher** [comment]
I changed the review URL in our database, so the accidentally-published URL will no longer function.
