### ISSUE TITLE
Update to 'at a glance' view on Curation Stats page

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2179]
Please update the 'at a glance' box at the top of the [Curation Stats](https://datadryad.org/stash/curation_stats) page to reflect the following: 

- Datasets currently in 'Submitted' status (that are unclaimed/unassigned)
- Datasets currently available for curation (these will be in 'submitted' or 'curation' status)
- Datasets available for curation and not touched within 72hrs (these will be in 'submitted' or 'curation' status)

**Comment by jleighherzog** [comment]
Also, please confirm how this stat is calculated: 
datasets available for curation and not touched within 48hrs (these will be in 'submitted' or 'curation' status)

**Comment by ryscher** [comment]
Confirmation for @jleighherzog's question above. "datasets available for curation and not touched within XXhrs" counts datasets where:
- the last curation activity on the last resource/version has status "curation" or "submitted" AND
- the last resource/version has not been changed in any way in the past XX hours
