### ISSUE TITLE
PRIORITY: Dryad sandbox API (AAAS)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2181]
Please investigate the issue reported by Rebecca Franz of AAAS (rfranz@aaas.org): 

> "For the last week or so, we’ve been having some issues with the Dryad sandbox API. Any API call to create a new dataset seems to be resulting in the Internal Server Error. Also, we’ve tried to submit/update some of the existing datasets that were created previously, and they seem to be stuck in ‘Processing’ state while the API returns ‘error’ as a version status for those. Can you take a look and provide an estimate on when this could be fixed? This is impacting our development and preventing us from successfully testing the integration. If there’s any additional information you need, please let us know."

**Comment by ryscher** [comment]
Fixed an issue I found when trying to replicate the problem, though I'm not 100% sure this was the same problem AAAS was seeing. I let them know that a problem was fixed and asked them to supply more details if they still encounter it.
