### ISSUE TITLE
Salesforce MFA in Spring 2023

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2186]
Is this anything we need to worry about?  I think maybe not and we are using an API that this doesn't affect for our interactions with Salesforce.

From the Salesforce email.

# Be Ready for MFA Auto-Enablement

Your org is included in the auto-enablement phase that takes effect when the Spring ’23 release rolls out. This action turns on MFA for all users who log in directly with their username and password.

For full details about MFA auto-enablement, see this article. Here’s a summary of what to expect:

- We use the Release Update mechanism to auto-enable MFA for orgs. The MFA Auto-Enablement Release Update for your org is visible now in the Release Update node in Setup and it will go into effect with Spring ‘23.
- When this Release Update goes into effect, it turns on the Require multi-factor authentication (MFA) for all direct UI logins to your Salesforce org setting.
- After your org is auto-enabled, users are prompted to provide an MFA verification method each time they log in. If they haven’t already, they’re guided through the steps to register a method.
- There’s a 30 day grace period where users can skip registration and log in without MFA. The grace period begins on the day your org is auto-enabled and the same 30 day window applies to all users in the org.
- Salesforce Admins have the option to temporarily turn off MFA (until Salesforce enforces MFA in the future).
To ensure that MFA is enabled for all direct logins, Salesforce is applying the MFA Release Update to all production orgs — even orgs that already satisfy the MFA requirement and those that use single sign-on (SSO) for Salesforce access. Note that the Release Update doesn’t affect logins that happen via SSO.

---

To comply with the latest browser and security standards, Salesforce is requiring that customers deploy enhanced domains to update the hostname formats for the domains that serve Salesforce orgs. This is a reminder that Salesforce will deploy enhanced domains in your orgs with the Spring ’23 release.

**Comment by ryscher** [comment]
I think we can enable it for individual users, so we should start testing in early spring.

**Comment by ryscher** [comment]
Some notes:
- There is a huge amount of documentation on the MFA transition. The best "quick" overview is https://help.salesforce.com/s/articleView?id=000388806&type=1
- MFA does not apply for API logins, so this will only affect humans, not the Dryad codebase
- Dryad's Salesforce runs on cloud instance NA111, which is scheduled to force MFA starting on February 11 
- The most straightforward solution for Dryad staff is to use the phone app "Salesforce Authenticator" 
- In the Salesforce user settings, MFA is controlled by the Profile. To enable, add permission `Multi-Factor Authentication for User Interface Logins`. To exclude from a requirement, add permission `Waive Multi-Factor Authentication for Exempt User`
