### ISSUE TITLE
Jen needs a plain-language explanation of the eJP integration for new customers pls

### ISSUE THREAD

**Issue by gibsonjen** [CDL-Dryad/dryad-product-roadmap#2189]
We're organising a webinar for late February, so this would be good to have by then please. 

Right now, I'm preparing a blog post to tout the available integration in plain language. The latest is here: https://docs.google.com/document/d/1K31DTsSELXrd1z_LYD1GCAr1udevIwSRvKYhEQjwkMM/edit#

@ryscher has provided guidance so far - thank you!

Based on the draft, the eJP team have said the following. It sounds like it would be helpful to have post-blog information (perhaps another blog, or something we keep in our pockets) on how to take this forward.  I don't think* we have anything yet. What do we think?
 
From the eJP team, via Anna:

* I asked our team to review the blog post and they replied saying, “The EJPress client will need to sign up for Dryad and obtain credentials (user ID and secret/password) that Dryad provides. After that, they will need to contact EJPress Support and provide those Dryad credentials to have the integration settings enabled.” It would be enabled first on the client’s EJPress test site and is then scheduled, after client testing/approval, to be taken live on the live site, so they are also wary of calling it too easy or fast.

* Can you add wording to the blog post that directs societies on how to start the conversation with Dryad to get those credentials? Not being the ones to have that particular relationship with Dryad, we weren’t sure if signing up to get those Dryad credentials for the society/journal was free, but whatever the process we are happy to share that knowledge in the future. [I've done this but want to be sure it all rings true to you all]

* Additionally, our team noted that another of our clients (not even the one we sat at lunch with) are also starting the process to turn this on, and while what is already available is very much a one-size fits all integration, we might know more about how and if clients should expect they will desire any custom coding to make it fit with their requirements. Perhaps and additional blog post once that implementation goes live would also be worthwhile?

**Comment by ryscher** [comment]
Following up on the blog post and webinar, there is now a simplified description with screenshots in https://docs.google.com/document/d/1yuBXOcmAuxEL5ZjleERQV3qhTULs1QZkZ39gRdM5SO4/edit?usp=sharing
