### ISSUE TITLE
Wiley quarterly invoicing for DPCs

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2190]
**Problem description, and links to relevant helpdesk tickets:**
We have reached an agreement with Wiley to invoice them quarterly for DPCs submitted from their proprietary journals as well as submissions from society journals for whom Wiley will be sponsoring DPCs.

The invoicing is based on the volume of datasets approved for publication, in 5 descending tiers.

We will need to:
1. Calculate the quarterly amount to be invoiced based on the volume of submissions approved for publication, and

2.  Create a report to accompany the quarterly invoice.

**Describe the solution you'd like:**
Calculation rules:
1. Tiers:
1-10 datasets: $0/dataset
11-100 datasets: $135/dataset
101-250 datasets: $100/dataset
251-500 datasets: $85/dataset
500+ datasets: $55/dataset

2. The total number of datasets approved for publication in each quarter establishes the cost basis. Thus, if Wiley’s volume reaches 300 in the first quarter, all datasets will be invoiced at $85/each, f they exceed 500 in the first quarter, all datasets will be invoiced at $55/each, and so on.

Reporting:
Components
1. Total invoice amount
2. A report to accompany the invoice, in PDF format, modeled after the quarterly reports for current ‘deferred’ payment plans:
https://github.com/datadryad/journal-payments/blob/main/deferred/deferred_submissions_Wiley_2021-Q3.pdf
3. The report should be emailed to operations@datadryad.org and mkurtz@datadryad.org

**Additional context:**
A Google Sheets calculator can be found here:
https://docs.google.com/spreadsheets/d/1BqKpkuf1-IYgqqSscOuPHwMpWlbKnMvjOlZHm92ezk8/edit?usp=sharing

This needs to be completed by March 2023 for Q1 invoicing in April.
@mariapraetzellis @sfisher @ryscher @ahamelers @jleighherzog

**Comment by ryscher** [comment]
- [ ] Introduce new type of payment plan (TIERED) in the enum for `payment_plan_type`
- [ ] Ensure journals on the tiered plan do not get invoiced at submission time
- [ ] Add a report for tiered plans similar to the deferred report
- [ ] Calculate total charges based on the levels specified above (levels and rates should be in the config file)
- [ ] Move Wiley journals onto the tiered plan and ensure they are synced with Salesforce

**Comment by ryscher** [comment]
Initial work is done, but some additional work is needed to convert from a "pure" quarterly billing to a cumulative billing that takes into account the volumes reached in previous quarters.
