### ISSUE TITLE
PRIORITY: Remove "published" status for 10.5061/dryad.fj6q573zn

### ISSUE THREAD

**Issue by Savannahbutler** [CDL-Dryad/dryad-product-roadmap#2192]
10.5061/dryad.fj6q573zn (Title: "Data for: Diverse mating consequences of the evolutionary breakdown of the sexual polymorphism heterostyly") was accidentally published while the curator attempted to edit the metadata. Please remove it from public availability and return it to Curation as soon as possible.

**Comment by ahamelers** [comment]
@Savannahbutler this is done in our system!

**Comment by Savannahbutler** [comment]
@ahamelers awesome thanks!

**Comment by jleighherzog** [comment]
@ahamelers : Issue resolved, can close this ticket. Data submission can remain "Published"
