### ISSUE TITLE
Change behaviour of notification emails to authors

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2195]
**Issue:** With the implementation of the Activity Log recording all automatic emails sent by the system, several curators found out for the first time that the system is sending these emails every time we edit the submission and "submit" it again as part of the regular curation workflow. This is likely annoying many authors and possibly causing them to ignore or miss more important emails that are not automatic (e.g., AAR emails). Additionally, this behaviour essentially allows authors to timestamp when their dataset has been actioned (i.e. they receive a notification of submission when they did not (re)submit it), which may lead to problems when there are delays in the curation process (e.g., difficult datasets, large datasets, server/system issues, unexpected OOO/emergencies, etc.). 

**Example:** In the below example ([full Activity Log](https://datadryad.org/stash/ds_admin/activity_log/101454?)), I had curated the dataset below and returned it to the author for editing. The author made the changes and resubmitted (one automatic email sent). I then examined the changes, did some minor edits to the metadata, and submitted those changes (second automatic email sent). After the dataset cleared the system, I then published the dataset (third automatic email sent). This is three emails within 8 minutes, but even if they were more dispersed, it's a lot of emails for the author to be getting that could detract from the ones that actually require their attention.

![Screen Shot 2022-12-21 at 12 50 58 PM](https://user-images.githubusercontent.com/113212676/209000751-097c9d52-977f-4fcc-acee-33e911cf114e.png)

**Request:** We discussed this in the curation team meeting and are wondering if it is possible to turn off these automatic emails when a dataset is "submitted" by a curator (it is very rare that we have to hijack a dataset and do an actual submission on behalf of the author). 

**Secondary request:** In the same vein, the system currently does not send automatic emails when a dataset is set to Withdrawn, and HD staff have to manually send confirmation emails after receiving requests for withdrawal. It would be helpful if the system could automatically send the notice of withdrawal emails with that status change.

**Comment by mariapraetzellis** [comment]
@jleighherzog will review auto notifications with @ryscher and comment.

**Comment by jleighherzog** [comment]
Q: Check to confirm whether auto-notifications are sent for submissions that are removed during regular 'clean-up' of submissions 'In Progress'.

Q: Withdrawn auto-notification text: 

> Dear [First name, Last name], 
> 
> Your data submission has been withdrawn from the Dryad platform:
> 
> Title:
> DOI: 
> 
> If you would like to reinstate your submission, at any time, please contact the Dryad Helpdesk at help@datadryad.org. 
> 
> All the best,
> The Dryad Team

**Comment by ryscher** [comment]
After discussion with Jess, list of steps to complete:
- document all automatic notifications, referencing the curation workflow diagram
- remove auto notifications when curator causes dataset to go to Submitted/Curation/InProgress
- add a notification to users when curators set status to withdrawn (text above)

**Comment by ryscher** [comment]
A [new version of the curation workflow diagram](https://docs.google.com/drawings/d/1rTW6uvpnJEXNVGHcCMc3Kd1NO0CJlIcIYQ8QtIe0Nfw/edit?usp=sharing) now includes notes about all automatic notifications.

**Comment by ahamelers** [comment]
@bryanmgee @jleighherzog The next step for this ticket is for you to look at the tagged version of the curation workflow diagram (see [Ryan's comment above](https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2195#issuecomment-1400814197)) and decide if any of the notification events should change.

Unless there is any reason not to, we can also go ahead and:

- [ ] remove auto notifications when a curator causes a dataset to go to Submitted/Curation/InProgress
- [ ] add a notification to users when curators set status to withdrawn

**Comment by bryanmgee** [comment]
@ahamelers @jleighherzog I think those two actions should be fine; one other thing I was wondering about is when a published dataset is "re-published" (latest version approved) – does the author get another email of that? The reason I'm asking about this is that when I do Twitter promos, I usually need to add the associated article, resubmit, and then republish the dataset. I would prefer that the author not be notified of when I have submitted the changes or republished it, as I think those would be more confusing than anything else.

**Comment by ahamelers** [comment]
@bryanmgee unlike the `previously_submitted` check, the `previously_published` check appears to check whether _any_ previous version of a dataset was published, and does not send the email if that is the case. So you should be good!

**Comment by jleighherzog** [comment]
@ahamelers @bryanmgee : When withdrawn submissions are reinstated, the authors and co-authors will receive the same confirmation email as before which also contains the same offer to co-authors to add their ORCID iDs. Can we NOT send a notification? If reinstatement is requested, we usually respond to the author's email to confirm.

**Comment by ahamelers** [comment]
@jleighherzog @bryanmgee 

Our new proposed solution for the main issue of this ticket is that if a new version of a submission is created (by the curator) when the submission is in 'Curation' status, we will place the new version _directly in Curation status_, without sending it through In Progress, etc.

Is there any workflow, recording, or other reason you can think of for us not to do this?

**Comment by bryanmgee** [comment]
@ahamelers @jleighherzog 

The only thing I can think of is whether this would affect curators' ability to get back into the dataset if they accidentally left it in editing mode because they closed out of the window or hit the 'back' button. But I think anyone should still be able to "hijack" it using the Forcible Edit button anyway to get back in right?

**Comment by ahamelers** [comment]
I wanted to tackle this by not passing through some of these statuses when a new version is edited while in 'Curation', but the system is a little too complicated for me to figure out how to do that on my own—maybe we can check the status sequences for sensibility at a later date. Instead I changed it so the 'submitted' email does not send if submitted by a curator, as initially asked for in this ticket.

**Comment by bryanmgee** [comment]
@ahamelers can we look into this again? Curators have noticed that the system is again sending a submission confirmation email to authors when curators are saving metadata changes during curation. I did some digging, and it looks like this started happening about a month ago (June 22 or 23) and is now uniformly happening for all datasets again.

**Comment by ahamelers** [comment]
@bryanmgee in the interest of speed, do you have examples at hand where this can be seen in the logs?

**Comment by bryanmgee** [comment]
@ahamelers example here: https://datadryad.org/stash/ds_admin/activity_log/113379; it's that 'Status change notification sent to author' line that's reappearing now when we are submitting the changes to metadata.

What I did to try and figure out when this started was filter all my claimed datasets by Submitted date and then start clicking through Activity Logs to see when that was not present (e.g., one from June 19th that doesn't display that action: https://datadryad.org/stash/ds_admin/activity_log/111746). I was able to get through June 21st without seeing that line (e.g., https://datadryad.org/stash/ds_admin/activity_log/84732), but I was mostly OOO on the 22nd and 23rd when it seems to have started sending notifications to the author again; it's definitely happening by the following Monday (the 26th; e.g., https://datadryad.org/stash/ds_admin/activity_log/100650)

**Comment by ahamelers** [comment]
Hi @bryanmgee , none of these examples look wrong to me—in this ticket, I updated the notifications for the 'submitted' status, to only send once per version, and not to send if the current editor in the 'submitted' status is a curator. In the examples you've sent, this does seem to be still in place. In the examples you've sent, the notifications have gone out for other statuses, or actions by other users.

**Comment by bryanmgee** [comment]
So what we're seeing is this; where after we put it into Curation, do something to the metadata, and save it, it sends a status change notification to the author

![Screen Shot 2023-07-26 at 11 29 46 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/50a85d2d-c807-43b4-a572-fbff6f215ab3)

What it should be doing (and was for a few months) was not doing that after we save the metadata

![Screen Shot 2023-07-26 at 11 29 29 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/f1db9ad1-ea26-41e2-9861-52341e9ae470)

**Comment by ahamelers** [comment]
@bryanmgee Thank you for the clarification! It looks like this is because of the new 'Processing' status, which was added to move the dataset out of the user "in progress" section for the new dashboard. I will carry the user id forward through this step which I think should solve the immediate problem, but I do think the workflow and movement through statuses needs an overhaul. When curators make edits, I do not think the dataset should move back to the "in progress" status for user edits.
