### ISSUE TITLE
Transfer ownership of dataset (10.25338/B8WW6S) – PRIORITY

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2198]
**DOI:** 10.25338/B8WW6S
**Title:** E-bike rebate survey datasets

**Transfer to:**
Dillon Fitch-Polse
ORCID: 0000-0003-3760-322X
Associated email: [dtfitch@ucdavis.edu](mailto:dtfitch@ucdavis.edu)

**Comment by ahamelers** [comment]
This is done
