### ISSUE TITLE
Onboarding: Laura Bowman

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2207]
A new Data Curator, Laura Bowman, is expected to begin onboarding Monday, January 23rd. Please begin to provide Laura with access to all necessary accounts/systems/etc. Please reference [this GDoc](https://docs.google.com/document/d/1xj27OsuMgWbuaeWqXkgsAWOBiSx9L-8uNbfpVmzbd5o/edit#) for the onboarding tasks. 

**Laura Bowman**
> Personal email: ljb5065@psu.edu
> Suggested Dryad email: [laura@datadryad.org](mailto:amelia@datadryad.org)

Once set up, I'll ask Laura to log into our system to confirm access. If you need more information, let me know.

- Create Google account
- Invite to Slack
- Provide access to VE
- Salesforce access (when license is available)
- Send instructions for accessing these accounts

**Comment by ryscher** [comment]
Google, Slack, and VE are set up. Salesforce is pending (will discuss with Jess)

**Comment by ahamelers** [comment]
Hi @jleighherzog ,

Laura now has a google account, slack invite, and VE access. Who is to manage Salesforce access going forward is under discussion.

To complete the remaining onboarding tasks, when Laura starts we will need her:

- ORCID
- Bio, and photo for the staff page

**Comment by jleighherzog** [comment]
@ahamelers : I submitted a request via email to Laura weeks ago for the ORCID & Bio. Will follow up today! Thanks.
