### ISSUE TITLE
Prevent machine-gun clickin™️ when curators edit datasets

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2212]
When curators try to open a dataset for editing (creating a new in-progress version) it's possible for them to machine-gun click so that creation has a race condition and two (or more) new versions may be created simultaneously.  (If one is fully created before the other then it is disallowed or opens the existing one.)

Add javascript to disable the edit button after 1 click to avoid machine gunning.

**Comment by ahamelers** [comment]
I'll steal and do this if that's okay @sfisher , should take just moments. Generally what I do for such situations is add a CSS `pointer-events: none;` to the entire body during the action, disabling all clickable items until the action is complete.
