### ISSUE TITLE
PRIORITY: Review set up for Rockefeller University Press

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2213]
Rockefeller University contacts were testing the submission process and found that the checkboxes on the final page of the Dryad submission form were _**not**_ greyed out and the checkbox to acknowledge payment upon publication was active. I confirmed the same on Dryad's test site (sandbox) even after I matched the entry for "Rockefeller University" in the 'Institutional Affiliation' field.

Can you check the settings for Rockefeller University to ensure payment will not be required for submitting authors?

**Comment by ryscher** [comment]
Rockefeller University is a valid tenant, which covers payment. I suspect the users did not connect their accounts to the university.

Can you give us the names of the contacts and IDs for datasets they were testing?

**Comment by ryscher** [comment]
Note that the "Affiliation" field does *not* grant users automatic coverage under a member's payment plan. To be covered, they must associate their user account with the university by logging in. (Except for the few odd universities that are covered by other processes.)

**Comment by ryscher** [comment]
(See related thoughts on improving the process in ticket #2000)

**Comment by jleighherzog** [comment]
@ryscher : Ok, want to close this ticket? We can follow up with the users regarding their login process. Thanks, Ryan!

**Comment by sarahklippincott** [comment]
@jleighherzog @ryscher This is actually for the Rockefeller University **Press** membership. When they made a test deposit through their EJP integration, they found that the checkboxes on the final page of the Dryad submission form were not greyed out and the checkbox to acknowledge payment upon publication was active. Is there a process for overriding that for authors coming in through a publisher member integration?

**Comment by jleighherzog** [comment]
@sarahklippincott : Ah, thanks for the clarification Sarah -- Rockefeller Univ Press

**Comment by sarahklippincott** [comment]
@ryscher Can you provide any update on this? I have a meeting today with RUP and would like, if possible, to give them an idea of when we'll have this sorted out, or at least a diagnosis of what's going on. Thank you!
