### ISSUE TITLE
PRIORITY: return dataset to PPR (10.5061/dryad.7d7wm37zs)

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2214]
Can this published dataset be returned to Private for Peer Review? The author did not select PPR upon the latest submission, so it was curated and published, but the journal requires double-blinding of all materials including data for peer review.

DOI: 10.5061/dryad.7d7wm37zs
Title: Female preferences for more elaborate signals are an emergent outcome of male chorusing interactions in túngara frogs

**Comment by ahamelers** [comment]
This is done!
