### ISSUE TITLE
Tabular data checker: update to 'error' text box

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2218]
We'd like to update the language of the text that appears when a report is generated that identifies _potential_ issues with the tabular files uploaded. Specifically, 
1) We'd like to remove any mention of 'error' and eliminate the instruction to correct the file(s). Helpdesk often receives emails from authors who are confused/irritated about the report because sometimes there are no errors, no edits needed and this delays submission. 
2) The edited version provides examples of common formatting concerns identified and identifies, more specifically, what it's checking for (format and structure).
3) The edited version still suggests that the submitter reviews the file(s) identified and provides the _option_ to edit and re-upload a new version.

**Current**:
Our tabular format checker found formatting issues in [file name]. Please view the issues from the links below and correct them.

Manually correct the issues shown in your local copy of the file. Click the error report in the Tabular data check column to get detailed information about the issues found.

Click Remove in the Action column to delete the file.

Re-upload the corrected file using the Choose files or Enter URLs button above.

**Edited**:
Our automated tabular data checker has identified potential inconsistencies in the format and structure of the file(s) uploaded (i.e. empty cells, missing column headings). A detailed report is available in the 'Tabular data check' column for each file scanned. To address the report: 
1) Review the local copy of your file(s).
2) If you would like to edit and replace any files, click 'Remove' in the Actions column to delete the current file.
3) Re-upload any updated file(s) using the _Choose files_ or _Enter URLs_ options above.

**Comment by jleighherzog** [comment]
Removing this text from the request but reserving here for consideration: 
_Note: You can choose to proceed to the final page of the submission form without editing your file(s). At curation stage, if there are questions about how your data is presented, a curator will contact you with options to improve the organization, readability, and/or reuse of your dataset._

**Comment by ahamelers** [comment]
Re my suggestion that we evaluate the possibility of skipping some types of errors as "not real errors", here's information on skipping errors: https://framework.frictionlessdata.io/docs/guides/validating-data.html#pick-skip-errors
 
And here are the error types (first of many pages): https://framework.frictionlessdata.io/docs/errors/metadata.html

**Comment by jleighherzog** [comment]
Update: UCSB curator, Renata Curty, reported at least 3 authors who expressed frustration concerning the tabular data checker which also stalled the submission process. Other UC contacts have reported the same to Renata. The visual impact is concerning to authors - red text, flags highlighting many errors, etc.

I'd like to request that we reconsider including this note below (if not in this sprint, I can create a ticket for a future sprint). This might help eliminate confusion as we work to improve the tool. 

_You can choose to proceed to the final page of the submission form without editing your file(s). At curation stage, if there are questions about how your data is presented, a curator will contact you with options to improve the organization, readability, and/or reuse of your dataset._

**Comment by ahamelers** [comment]
Thank you @jleighherzog , in #1091 I've linked to a planning document for work we need to do around frictionless/tabular data check that includes the work in this ticket as well, since we need to plan and work on everything in concert. Sorry for not linking it here previously!

Here it is as well: https://docs.google.com/document/d/1_qlSH105VtS6Lchd5puknX3r1Bn5TyJGSoOx7p1Y6BQ/edit?usp=sharing

**Comment by ahamelers** [comment]
This ticket has been replaced by (and will be integrated into) #2311
