### ISSUE TITLE
Rotate the passwords we can in application

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2219]
Merritt did this a while back and we probably should, also.  We can check with Terry about any trickiness they ran into or what procedure they used.

- [ ] Get list of the passwords we use from the service
- [ ] It would be better to have another account on each service so we don't have to actually change all passwords during an outage time, but IDK if that is feasible.
- [ ] Update credentials with the new passwords (& account)
- [ ] Set up an outage and do a deploy in sync with the password changes

If we cannot create other new accounts for rotation, maybe we can set the passwords we want to use and then get all Dryad hands on deck and update passwords as a group so there is minimal time for the outage.

Passwords we don't use within the service itself can be changed at our leisure.

**Comment by ryscher** [comment]
See also #2133
