### ISSUE TITLE
Edit emails to Authors

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#222]
Emails go to authors:
- When you've submitted it 
- When it's gone through successfully
- When it's passed through curation to embargo or publish (adding one for embargo would be new)

Change to:
-Migration Email
- Submit, Status=Private for Peer Review
- Submit, Status=Submitted
- Embargoed
- When it's publicly available

Email Text and Subject Lines: https://docs.google.com/document/d/1j1ubCq-Q2DDEXtRJrF6Y_h98H4OAGViIWkqdizNVxWk/edit?usp=sharing

**Comment by briri** [comment]
will also check the logic that asks users to register their ORCID so that it doesn't ask users who have already registered theirs.

**Comment by briri** [comment]
PR is out for this. Getting the citation into the email is more complex than expected, so going to create a separate ticket to track that work for next sprint. Here are samples of the new emails:

**Dataset becomes Published**
<img width="630" alt="Screen Shot 2019-03-21 at 9 01 32 AM" src="https://user-images.githubusercontent.com/1204467/54766193-1af76f80-4bb8-11e9-9bcf-c7a25c29d3ef.png">
**Dataset is Embargoed with a future publication date set**
<img width="626" alt="Screen Shot 2019-03-21 at 9 01 21 AM" src="https://user-images.githubusercontent.com/1204467/54766195-1af76f80-4bb8-11e9-8ae0-e480094634d1.png">
**Dataset is Embargoed permanently (with no future publication date set)**
<img width="629" alt="Screen Shot 2019-03-21 at 9 01 09 AM" src="https://user-images.githubusercontent.com/1204467/54766196-1af76f80-4bb8-11e9-9b99-0d2e4bdbcfe9.png">
**Dataset is ready for Peer Review (passed through Merritt successfully and has a journal)**
<img width="632" alt="Screen Shot 2019-03-21 at 8 58 41 AM" src="https://user-images.githubusercontent.com/1204467/54766198-1b900600-4bb8-11e9-854b-d25793b33f97.png">
**Dataset is Submitted (passed through Merritt successfully)**
<img width="635" alt="Screen Shot 2019-03-21 at 8 57 22 AM" src="https://user-images.githubusercontent.com/1204467/54766199-1b900600-4bb8-11e9-9d08-58bf9f465cd8.png">

**Comment by briri** [comment]
The ORCID invitation text, submission failure text and error report (to admins) remain unchanged
