### ISSUE TITLE
Dryad auto-notifications: updates

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2220]
We've reviewed all Dryad auto-notifications and have provided updated text in this [GDoc](https://docs.google.com/document/d/1V2Ve7HvrN01DWhFfSC2gRdRfOyuiece0KGu7nFGqJKA/edit) for the following: 
- Submitted
- Published
- Peer Review Reminder
- Peer Review
- ORCID invitation
- Journal review notice
- Journal publish notice
- In Progress Reminder
- Embargoed 

_Note: See question posted in "Embargoed" notification and note in the "Published" notification._
Please check spacing, spelling, line breaks, etc. 

Possible to view a preview of the edited versions without the HTML markup?

**Comment by ahamelers** [comment]
> Please check spacing, spelling, line breaks, etc.
> Possible to view a preview of the edited versions without the HTML markup?

@jleighherzog I've changed the document to show the email contents without HTML or other markup, where possible. I've also put in some suggested edits to the text.

**Comment by jleighherzog** [comment]
@ahamelers : Added a few questions/comments, and then should be good to go.
