### ISSUE TITLE
PRIORITY: Transfer of ownership of dataset 10.5061/dryad.dz08kps07

### ISSUE THREAD

**Issue by ctarpey** [CDL-Dryad/dryad-product-roadmap#2222]
DOI: 10.5061/dryad.dz08kps07
Title: Vietnamese chickens genotypes

Transfer to:
Luc Do Duc
ORCID:  0000-0003-3364-1296
ORCID associated emails: [doducluc@yahoo.com](mailto:doducluc@yahoo.com) and [ddluc@vnua.edu.vn](mailto:ddluc@vnua.edu.vn).

The email address he is using to correspond with me in Salesforce is:
[dtghn@yahoo.co.uk](mailto:dtghn@yahoo.co.uk).

**Comment by ahamelers** [comment]
Hello @ctarpey , none of the 3 existing authors for this dataset are named Luc Do Duc. Are you sure this user should be given ownership of the dataset?

**Comment by ahamelers** [comment]
Hi @ctarpey, should this be closed?
