### ISSUE TITLE
Transfer of ownership for DOI: 10.5061/dryad.fj6q573tv

### ISSUE THREAD

**Issue by Savannahbutler** [CDL-Dryad/dryad-product-roadmap#2223]
Please transfer ownership of 10.5061/dryad.fj6q573tv 
**From:** Xin Shu 
**To:** co-author Tom Sizmur, ORCID: 0000-0001-9835-7195 and associated email address: t.sizmur@reading.ac.uk

**Comment by ahamelers** [comment]
This is done!
