### ISSUE TITLE
CEDAR template for DataCite/Templeton grant

### ISSUE THREAD

**Issue by mariapraetzellis** [CDL-Dryad/dryad-product-roadmap#2226]
DataCite has a new draft template for the CEDAR editor to try out. This new template was created jointly between DataCite and the Max Planck Institute of Empirical Aesthetics research team. They are still finalizing the template, but it's a good time to see how the implementation will work.

The template is available here: https://openview.metadatacenter.org/templates/https:%2F%2Frepo.metadatacenter.org%2Ftemplates%2F7479dcb2-2c2f-44c8-953d-507c8b52c06a 

DataCite has some questions and things to look into when deploying the template. Here are the questions from the Product Manager at DataCite, Xiaoli Chen:

1. Repeatable fields and elements: these are a bit awkward on CEDAR itself. For repeatable fields, CEDAR would open an editable spreadsheet to collect this information, not a repeated UI element. And for repeatable elements, it doesn't show an additional empty element under the filled-out one, but replaced the filled-out element with an empty one...  just  I wonder if it works the same on the Dryad implementation.
For example, the "Experiment Paradigm" element is repeatable, and the "Related Work" field within the element is also repeatable. 

2. Ontological support: fields that have either an ontology class or term assigned. 
For example, the "Sensory Type" field is assigned a small ontological class. 

3. Headings: I'd like to make sure the different level headings are shown in a recognizable way. The help text is quite small when shown on the CEDAR UI I wonder if inserting rich text blocks to explain the fields would be more effective. Most of the fields have help texts.

**Comment by ahamelers** [comment]
Refer to #2144

**Comment by ryscher** [comment]
Currently deployed to dryad staging server. A few notes on the above questions:

1. Repeatable fields and elements.

   These are working, but the CEDAR tool doesn't render them in an
   understandable way. For each repeatable section, there are one or more fields
   that can be repeated, but there is no indication where the repeatable section
   ends and it goes back to being just normal fields.

2. Ontological support: fields that have either an ontology class or term
   assigned.
   
   The ongology displays for Sensory Modality, but it is not enforced.

3. Headings

   The rich text and headings appear to be rendering fine in Dryad. Note that
   the HTML in the original template was encoded. I had to decode it before it
   would render.
