### ISSUE TITLE
Test functionality of link to create submission that is provided to authors by journal

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2230]
Sometimes we get HD cases where the author was given a link with their manuscript number included in it, but the link only takes them to a blank submission, when the expected behaviour is that it should auto-populate some of the fields similar to the Import Metadata function. This ticket follows up on the convo with JH and RS today for Ryan to run a quick test that these links are generally behaving like we expect them to.

**Comment by ahamelers** [comment]
Duplicated by #2231
