### ISSUE TITLE
Check our backup script for mysql

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2232]
From Martin Haye:

If you use mysqldump in a script with the --single-transaction flag, you may encounter a brand new problem. I think it's caused by an undocumented change in 5.7.41, that causes mysqldump to try to use a permission that RDS doesn't grant to any clients. You'll know it by this symptom:
mysqldump: Couldn't execute 'FLUSH TABLES WITH READ LOCK': Access denied for user <your-user-here>
If you encounter this, let me know. I know of a couple workarounds.

**Comment by ryscher** [comment]
Our current backups appear to be fine. I unzipped one of the files and looked at the beginning and end; it has the expected content.

**Comment by sfisher** [comment]
Thanks for checking @ryscher .

**Comment by sfisher** [comment]
Assigned to ryan and marked as done.
