### ISSUE TITLE
Finalize version of datacite-mapping gem

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2234]
When we performed the latest Rails upgrade, we referenced a branch of the datacite-mapping. This should be merged into the main branch and released.

**Comment by ryscher** [comment]
Updates are merged into datacite-mapping, so the Dryad reference can be updated.

**Comment by ahamelers** [comment]
I can update our gemfile to remove the branch reference, but it still needs to reference the git repository, unless we can also release the update on rubygems

**Comment by sfisher** [comment]
@ahamelers Do you have an account on RubyGems?  If you do, I think I can make you a maintainer which would allow you to publish an update.

**Comment by ahamelers** [comment]
@sfisher thank you, I was just about to link this to another ticket about this gem, to ask if you could add me as a maintainer! I'm ahamelers on rubygems.
