### ISSUE TITLE
Reactivate Reviewer URL (DOI: 10.5061/dryad.cjsxksn9f)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2237]
Possible to re-instate the Reviewer URL that was deactivated in this related ticket: 
[Deactivate Reviewer URL (DOI: 10.5061/dryad.cjsxksn9f) #2176](https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2176#issue-1495059692)

**Comment by ryscher** [comment]
I reset the reviewer URL to the value that I *think* it was previously, but I will Slack you the URL so the customer can double-check.
