### ISSUE TITLE
Usage stats for UC Merced 

### ISSUE THREAD

**Issue by mariapraetzellis** [CDL-Dryad/dryad-product-roadmap#2246]
UC Merced has requested a report that includes all of the deposits that have an author affiliated with UC Merced. Within that data set, the fields they're interested in are:

- Author name
- Author email (if you have it)
- Initial deposit date
- Publication date
- Metrics (views/downloads/citations)
- Deposit URL or DOI

**Comment by ryscher** [comment]
Ran the "Authors at an institution report" with minor adjustments to add author email and dataset creation date. Shared results in a Google sheet.
