### ISSUE TITLE
Track multiple ISSNs per journal

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2247]
We currently use a single ISSN per journal. As we get more journals sending information via the API, we cannot control whether they will send the ISSN we expect, so we need to store multiples, and allow any of the ISSNs to match the journal's entry in the system.

**Comment by ahamelers** [comment]
@ryscher , do you know about the issue of multiple instances appearing for journal titles in the `stash_engine_journals` table? This appears to be causing this bug: #2261 

Will that also be resolved as part of this ticket?

**Comment by ryscher** [comment]
Splitting the de-duplication work into a separate ticket, because it cannot be completed until this feature is deployed.
