### ISSUE TITLE
Non-stash website navigation and content changes

### ISSUE THREAD

**Issue by gibsonjen** [CDL-Dryad/dryad-product-roadmap#2250]
Hi team!

I've written up some changes to the website navigation and would like to add some pages, please. These are important additions for communications and partner recruitment and would be good to have online by the end of Feb if possible. Please take a look and let me know what you think and if you have any recommendations re my suggested approaches. Thank you!

https://docs.google.com/document/d/1BrcmMZBUyheeu3TTG2VbLaOf53Bl9n_IUrdUVqjPR2s/edit?usp=sharing

@ahamelers Ha - finally! : )

**Comment by ahamelers** [comment]
Hi @gibsonjen 

The new pages and the reorganization of the dropdowns all sound very good, and I'll consider the general menu functionality. I have one other point of caution, which is that the changes lengthen the menu horizontally, and for _logged in_ users, the menu is already a bit long—for curators and site administrators, even more so!

<img width="1226" alt="long_menu" src="https://user-images.githubusercontent.com/1749394/216358764-73b8d5ec-e268-4f46-bf3f-d8a2968e8ef0.png">

With changes:
<img width="1224" alt="longer_menu" src="https://user-images.githubusercontent.com/1749394/216360014-e387e26d-c7d7-4262-b4cc-fa8625aa7b75.png">


I have a couple of suggestions for dealing with this to free up some more space in the menu:

- Move 'Explore data' to the same line as the Search bar (this also makes it more clear what 'Search' is searching)
- For logged in curators and admins, move 'My datasets' into the Admin menu, under a new heading, 'Datasets' or 'Dataset admin'

<img width="1233" alt="proposed_menu" src="https://user-images.githubusercontent.com/1749394/216360165-100a422f-9797-4aa9-9db8-8d51783ec09e.png">

Please let me know your thoughts (or if @ryscher, @jleighherzog, etc. have any feedback?)

**Comment by ahamelers** [comment]
I've only now noticed that you'd also like 'Join us' added to the main navigation, which I think only strengthens my point about the number and length of existing main navigation items.

**Comment by jleighherzog** [comment]
@ahamelers : 
1) What happens to all the pages within the "Admin" menu? Curation Stats, Pub Updater, etc.? Are they relocated under "Datasets"?

2) I like where you moved "Explore Data". When a search is performed, how do the results appear? Are we attempting to hide this landing page: https://datadryad.org/search?

**Comment by ahamelers** [comment]
> @ahamelers :
> 
>     1. What happens to all the pages within the "Admin" menu? Curation Stats, Pub Updater, etc.? Are they relocated under "Datasets"?

Yes, that's what I was suggesting! I understand there's a tenants menu as well I'd need to look at. Basically I'm suggesting there is a menu space that for normal users contains a direct link to 'My Datasets', and for other kinds of users is a dropdown that contains 'My Datasets' as well as other options.

>     2. I like where you moved "Explore Data". When a search is performed, how do the results appear? Are we attempting to hide this landing page: https://datadryad.org/search?

'Explore data' would still link to that landing page. (As part of a separate discussion, I'd also like to change the design of that landing page 😄 )

**Comment by ahamelers** [comment]
> The title of the dropdown is totally up for discussion if you have other suggestions, but since pretty much all functionality of the Dryad site is about handling and managing datasets, I thought that was a reasonable one-size-fits-all title.

'Management' would also be a reasonable title, in my opinion!

**Comment by sfisher** [comment]
I'll also mention that all partners get a secondary logo in addition to Dryad and we're more or less at the limit of space for top-level menus with our current layout if someone has some kind of admin access.

![Screen Shot 2023-02-06 at 9 47 33 AM](https://user-images.githubusercontent.com/105433/217047019-7b54ebf3-1c4a-4ddc-b5d8-6b15c2ebe8da.png)

Audrey, it is easy to change to see a partner even if you can't log in with them.  Just fill in the tenant_id in for your user in the database and you can see other logos.  We limit partners logos by height so they don't blow out the page vertically.  However, even when we used to suggest max sizes for logos in the past, people have difficulty limiting themselves. Like they want the library AND the university to both be represented; or there isn't a smaller logo; or they don't know how; or the university has strict logo/wordmark rules; or we just haven't forced people to make a special logo for us or whatever.  🤷   We also have (had?) a setting for flipping the order of the logos for people who had some strict reason the university one had to appear first (we had a UC, I think Davis, that insisted on it at on it).

We could also think about having a mini-dryad logo for co-branding when both logos appear, but having two wide logos really limits the space available for menus if they're horizontally next to each other.

So this is another thing to consider when thinking about menus in our current layout and we want to please our partners who are giving us money and subscribing to our service.

**Comment by ahamelers** [comment]
@sfisher I've reimplemented the entire header to better fit navigation items and any logos that are present without running over the side of the page.
