### ISSUE TITLE
Merritt presigned errors

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2251]
We receive dozens of these errors every day. Are they real problems? Can Merritt do anything to fix them?

```
Merritt couldn't create presigned URL for http://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5d27119/2/producer%2FPvirgatum_v1.1_273_gene_exons_updated_ChrUn_representative.gff3.gz?no_redirect=true
Http status code: 404
 app/models/stash_engine/data_file.rb:53:in `merritt_s3_presigned_url'
```

**Comment by sfisher** [comment]
@ahamelers We also see a number of errors like this in emails.  It probably means investigating if the file really exists in Merritt and if it does then why people can't download the particular file.  Do you have the Merritt login to look at their UI? (I think you probably have it in an encrypted file).  Their site is merritt.cdlib.org and you can probably search for the DOI there and will need to verify filenames in their version vs ours for some of these to see if it's legitimately 404 and missing.

We may have some data consistency problems a few places (likely many of these errors are being triggered by bots scraping our site when we get them).

**Comment by ryscher** [comment]
I believe this is fixed now.
