### ISSUE TITLE
Low priority: Update status to "Published" (DOI: 10.5061/dryad.1jwstqjws)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2253]
A previous version of this published dataset was restored (see this ticket #1956)
DOI: 10.5061/dryad.1jwstqjws

However, I'm unable to update the status to "Published", it remains "In Progress"

Possible to update the current status to "Published" **AND** maintain the original publication date of 02/01/2022?

**Comment by sfisher** [comment]
Ok, this is published and it has the original date.
