### ISSUE TITLE
Shopping cart report errors

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2254]
**Bug description:**
PRIORITY: This pertains to accurate invoicing and accounting.

The shopping cart reports have a number of apparent errors:

1. Naming conventions: Institutions have inconsistent naming conventions (see attached screenshot).
2. Sponsor column: if a dataset is attributed to an institutional member, the institution name should appear in the Sponsor column.
3. Hierarchy: Publishers are meant to come first in the invoicing hierarchy, but often a dataset with a Sponsor shows payment type as 'institution' (see attached CSV and screen shot).
4. Stripe: Datasets with a named Sponsor regularly have 'stripe' as the payment method, which is incorrect (see attached screenshot).

**Steps to reproduce:**
Analyze recent shopping cart reports or view in Google Data Studio (please ask me for access and I will share).

**Expected behavior: **

1. Institutional naming conventions adhere to a controlled vocabulary (preferably ROR)
2. All sponsors, whether publishers or institutions, are correctly identified in the Sponsor column
3. The invoicing hierarchy is correctly applied (publisher > institutional member > waiver > stripe)
@ryscher @mariapraetzellis

![Screen Shot 2023-01-30 at 3 11 08 PM](https://user-images.githubusercontent.com/76785652/215587266-96206a25-e3cd-4451-97ad-908d857db91d.png)
![Screen Shot 2023-01-30 at 3 11 27 PM](https://user-images.githubusercontent.com/76785652/215587275-7639d609-27c1-4351-aa08-e1e5ad275461.png)
![Screen Shot 2023-01-30 at 3 13 08 PM](https://user-images.githubusercontent.com/76785652/215587289-bba08705-d4de-412c-9e06-0fcfe7
![Screen Shot 2023-01-30 at 3 16 23 PM](https://user-images.githubusercontent.com/76785652/215587308-c5756442-8e7e-404c-a591-90e712adad41.png)
34d037.png)
[Shopping Cart Report Dashboard_All entities_Table.csv](https://github.com/CDL-Dryad/dryad-product-roadmap/files/10539657/Shopping.Cart.Report.Dashboard_All.entities_Table.csv)

**Comment by ryscher** [comment]
1. Known misspellings are now corrected. Ticket #2183 was recently completed as a way to prevent these from being introduced, but some may still slip through, since we need to allow authors to use institutions that do not exist in ROR.

**Comment by ryscher** [comment]
2. The Sponsor column is currently very simplistic; it simply takes the journal's current sponsor, even if the dataset was submitted prior to the journal's payment plan. It should be updated to reflect the actual payment that was charged in the Payment type column. Transferred to new ticket: #2347

3. Many of these issues are due to the journal information being added to the dataset after the initial submission, after the user's institution has already been associate with payment. Transferred to new ticket: #2346
