### ISSUE TITLE
The autocompletes appear very wonky now

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2255]
We probably need to examine this or roll something back if this isn't only me seeing this (but is an issue for everyone).  I did a preview merge of everything that would be going into this release plus stuff in the main branch (in branch preview-release-01-23 and then did a dev deploy of the latest changeset as shown in `git log`) and I saw the data entry form like this:

![Screen Shot 2023-01-30 at 5 44 47 PM](https://user-images.githubusercontent.com/105433/215638937-35da1ab5-32a4-4d9e-aac8-6e1f4f29e493.png)

I think this is maybe a result of the ✔️ for adding something not in the list?  IDK exactly why.

We maybe need to investigate if this is just something weird about the deploy or if it's something in the code that needs fixing or rolling back out.

**Comment by ahamelers** [comment]
@sfisher This looks normal to me, could it be a CSS caching issue?

<img width="1249" alt="Screenshot 2023-01-31 at 15 32 28" src="https://user-images.githubusercontent.com/1749394/215788793-93281129-f2ac-43ad-8258-ea8cc2078352.png">
