### ISSUE TITLE
Configure auto-PPR for Rockefeller University Press titles

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2256]
Please set up auto-PPR for the following **Rockefeller University Press** titles: 

- Journal of Cell Biology | 0021-9525 
- Journal of Experimental Medicine | 0022-1007
- Journal of General Physiology | 0022-1295 

When notifications of "Accept" or "Accept pending minor revision" are received, the data submission should be released from PPR status and move to "Submitted" status for curation.

**Comment by ryscher** [comment]
Settings changed
