### ISSUE TITLE
Return PubUpdater to regular use

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2259]
The PubUpdater has not been used in years. We would like to get it running again to close the "gap" of datasets that are not linked to publications.

To help curators prioritize content, they would like to add these features: 
- Sort by journal
- Export
- Search on ISSN, Publication, Title

Jess also needs to confirm which fields should be overwritten by the Accept button.

**Comment by jleighherzog** [comment]
@ryscher : Currently, Ted is exploring the interface on the test site. We'll reconnect with him to discuss options moving forward and update this ticket with proposed solutions, modifications, etc.

**Comment by ryscher** [comment]
Waiting for feedback from curation team on what is needed to improve accept/reject buttons. In the meantime, will prioritize #2386.

**Comment by sfisher** [comment]
BTW, one thing I always thought was very weird about the pub-updater was that the arrows pointed the opposite direction of data flow.  See example below.  Even though the publication data would move to overwrite the dataset metadata, the flow arrows point the opposite direction.  I remember Brian Riley worked on this originally and he had the arrows pointing the direction of data flow--yet curators said it was confusing and that the arrows should point the opposite direction.

![Image](https://user-images.githubusercontent.com/105433/227664032-04d252a5-2057-42bc-842a-08f14d0004d6.png)

IDK if the curators still think the arrows should point opposite the flow direction (or maybe he misunderstood or it was opposite day when he checked).

**Comment by ryscher** [comment]
After review from @jleighherzog, the new functionality for the Accept button should be:
- Add the link to the publication as a `primary_article`
- Update the dataset keywords to include any keywords from the article that are not already in the dataset
- (already exists) Update the PubUpdater entry to mark it as "accepted"
