### ISSUE TITLE
System keeps unmatching journal after manually matched

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2261]
DOI: 10.5061/dryad.zgmsbccfd 
Title: Supplementary data for: Genomics of secondarily temperate adaptation in the only non-Antarctic icefish

When the dataset was submitted, the journal was listed as "Molecular Biology & Evolution," which doesn't match because the real name of the journal uses 'and,' not the ampersand. However, after I fixed this and matched the journal (the check box of "I can't find my journal" disappeared), if I tab over to another page and then back, it has kept the correct name but then checked the box for "I can't find my journal" again. I've tried every order I can think of for editing the journal – unchecking the box, then matching; matching first (which automatically makes the box disappear – and am making sure I tab to the next field to save that change. If I put 'N/A' for the journal name and changes tabs, it saves that change, but then re-entering the journal name and matching it results in the same behaviour of a matched journal with the checkbox enabled.

It's not a big issue for this dataset specifically because the sponsorship of the dataset is by the institution in this case, but I'm not sure if this a larger bug that's related to the new feature rollout. 

![Screen Shot 2023-02-02 at 9 58 59 AM](https://user-images.githubusercontent.com/113212676/216405842-a24d202e-d48c-45f3-9c02-c6bec74f830c.png)

**Comment by ahamelers** [comment]
Thanks Bryan, I'm able to recreate this with the same journal, but _only_ with that journal (so far) and not in any other autocomplete area. It might be some issue in the database for this journal in particular: the checkbox is meant to appear checked if the recorded item has a name (text entered) but no id recorded from the database. I'll check more to see what else might be affected.

**Comment by ahamelers** [comment]
It looks like there are actually 2 results from searching for the same journal name, which have different ISSNs. On the front end, it looks like these are combined into one text option, and checking the database, when that text option is selected it looks like _neither_ ISSN is actually recorded as the selected ID.

I think this will have been the case until now for any journal name that appears more than once! Which according to a quick DB search is 81 journals. Maybe this will be resolved by #2247 ? I'll discuss with @ryscher and @sfisher  whether we need to change the form functionality as well and how to check for this bug historically—I'm guessing the recent database cleanup caught a lot.

```json
[
	{
		"id": 730,
		"title": "Molecular Biology and Evolution",
		"issn": "0737-4038",
		"website": "",
		"description": "",
		"payment_plan_type": null,
		"payment_contact": null,
		"manuscript_number_regex": "",
		"stripe_customer_id": "",
		"notify_contacts": "[]",
		"review_contacts": "[]",
		"allow_review_workflow": true,
		"allow_embargo": true,
		"allow_blackout": false,
		"default_to_ppr": false,
		"created_at": "2020-04-14T16:43:31.000Z",
		"updated_at": "2020-04-14T16:43:31.000Z",
		"journal_code": null,
		"sponsor_id": null
	},
	{
		"id": 1186,
		"title": "Molecular Biology and Evolution",
		"issn": "1537-1719",
		"website": "",
		"description": "",
		"payment_plan_type": null,
		"payment_contact": null,
		"manuscript_number_regex": "",
		"stripe_customer_id": "",
		"notify_contacts": "[]",
		"review_contacts": "[]",
		"allow_review_workflow": true,
		"allow_embargo": true,
		"allow_blackout": false,
		"default_to_ppr": false,
		"created_at": "2020-04-14T16:46:57.000Z",
		"updated_at": "2020-04-14T16:46:57.000Z",
		"journal_code": null,
		"sponsor_id": null
	}
]```

**Comment by ahamelers** [comment]
@ryscher When #2286 is done, do we need to go through and put in ISSN 'matches' for any resources affected by this?

**Comment by ahamelers** [comment]
@ryscher I have found that 123 publicationName fields match one of the affected 'duplicate' journals, but have no associated ISSNs matched (so, 123 identifiers were affected by this bug). These results and the associated (probably wildly inefficient) query can be found in the attached google sheet: https://docs.google.com/spreadsheets/d/1I-9JnttjKCltyVeNZqdWjt9Mi_4lndSkjCk3iLhERuA/edit?usp=sharing

**Comment by ryscher** [comment]
Added ISSNs to all datasets that had a publicationName but not an ISSN.
