### ISSUE TITLE
Add Tenant: University at Buffalo

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2263]
**Tenant name:** 
University at Buffalo  (This is a SUNY school, see the ticket about adding the systemwide and it may be useful to name all SUNY tenants similarly so they're easy to see in the config.)

**Logo location:** 
TBD

**Contacts to receive submission notices:** 
TBD

**RORs that are considered part of the tenant (including medical centers, alternate campuses, etc.)**
~https://ror.org/05ms04m92~
https://ror.org/01y64my43

**Shibboleth info, if not in [InCommon](https://incommon.org/community-organizations/):**
https://docs.google.com/spreadsheets/d/1aCvJfvuHvrCuIcayIkGW7TFYRoyEQIMoWQtKlfr9v0g/edit?usp=sharing

Tasks:
- [x] send [Technical Welcome Message](https://docs.google.com/document/d/14NmHkg__5xOgkg5fTeizuaqOwCcLlKinouMLz9a_BNY/edit?usp=sharing)
- [ ] add config to dryad-config repo
- [ ] add logo to dryad-app repo
- [ ] deploy and test on stage (institution should log in to verify working as expected)
- [ ] update tenant_id for users in the database who have emails with the institutional domain name
- [ ] add institution's name to the Dryad website

---

Hi Audrey, I think you are seeing the technical info doc.  Essentially start by copying an existing one and updating the information to be correct.  I think the SUNY spreadsheet has most of the information you need.  If not, check in with Mark or someone who has been communicating with them.

**Comment by ahamelers** [comment]
@mark02139 Is there any word on a logo for this tenant?

**Comment by mark02139** [comment]
Same answer as in the previous case. We're revising our onboarding workflow to get you all the information you need at the time of ticket creation.
