### ISSUE TITLE
Update corresponding author (DOI: 10.5061/dryad.6hdr7sr4d)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2264]
Priority: Low 
Impact: Dataset pending publication

Title: Data from: The impact of land surface properties on haboobs and dust lofting
DOI: 10.5061/dryad.6hdr7sr4d

Please update the corresponding author of this data submission to be: **Jennie Bukowski**
- ORCID ID: 0000-0002-7092-7405
- Jennie's preferred email address: [jenbukow@ucla.edu](mailto:jenbukow@ucla.edu)

**Comment by ahamelers** [comment]
This is done
