### ISSUE TITLE
Wordpress changes

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2265]
A couple of changes for blog.datadryad.org:

1. Please disable commenting site-wide.
2. Please add a link to datadryad.org to the top nav on the blog. Labeled Datadryad.org unless you have a better idea!

**Comment by ahamelers** [comment]
Okay, done!

By the way, the about page says the title of the blog is 'Dryad news and views'; should that be changed?
