### ISSUE TITLE
BES journal staff: configure journal access on Admin site

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2266]
**Impact**: BES editorial staff
**Priority**: Medium (before the end of the week, if possible) 

The following BES staff members all have Admin site access and have logged in successfully to the site. Now, each contact will need access to the list of BES journal titles listed below: 

[Francis Harris](https://datadryad.org/stash/user_admin/user_profile/93032)
0000-0002-4192-4512
frank@britishecologicalsociety.org

[Philip](https://datadryad.org/stash/user_admin/user_profile/92539)
0000-0002-3710-874X
philip@britishecologicalsociety.org

[Lydia Groves](https://datadryad.org/stash/user_admin/user_profile/92679)
0000-0002-7744-1651
lydia@britishecologicalsociety.org

[Amy Harrison](https://datadryad.org/stash/user_admin/user_profile/91639)
0000-0001-5113-8956
Amyh@britishecologicalsociety.org
__________________________________________________________________
These users are properly configured with access to all 7 titles, double-check their profiles, if you like!

[Milly Anderson](https://datadryad.org/stash/user_admin/user_profile/80887) [ALL SET]
0000-0002-1438-1671
milly@britishecologicalsociety.org

[Andrea Baier](https://datadryad.org/stash/user_admin/user_profile/52677) [ALL SET]
0000-0002-0791-2366
andrea@britishecologicalsociety.org 

**Journal titles**: 
> - Journal of Ecology
> - Journal of Applied Ecology
> - Journal of Animal Ecology
> - Methods in Ecology and Evolution
> - Functional Ecology
> - Ecological Solutions and Evidence
> - People and Nature

**Comment by ahamelers** [comment]
This should now be done
