### ISSUE TITLE
Static page UX/design updates

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#2271]
In concert with #2250 , make UI improvements and combinations for testing, evaluation and approval

- [x] Make a branch with some of the UI improvements outlined in the suggestion document, specifically:
    - Font sizes
    - Link colors
    - Heading sizes, margins, etc.
    - Line widths and the addition of on-page navigation where possible

With the addition of page section navigation, combine some of the new pages:

- [x] Move the list of members to the Join us page—change any links to 'our members' to go directly to that section of the page
    - [ ] See if it is possible to use tenant logos to add graphical interest to the member list
- [x] Make the new 'What we do' a top section, and put the new 'Process' page on the same page
    - [x] If possible, combine 'Platform' onto the same page by rewriting the platform page a bit/making it a bit shorter
- [x] Move Collaborations and Origins into 'Who we are'
    - [x] Add some visual interest to the Origins timeline with bubbles and lines
    - [x] If time permits, combine the Members, Board, and Team pages into 'Who we are' as well

**Comment by ahamelers** [comment]
I've made most of the design and page changes listed in this as a starting point for evaluation on the dev server! It can be compared to the initial work done for #2250, on the staging server.

Notes on remaining work:
- I put the link to the blog under 'Help' (not a great place for it), I think there are better ways we can incorporate the blog into the main site—we could show snippets of the most recent couple of posts, or posts based on tags, in some different contexts including on the home page.
- I'd still like to look at what we can do with tenant logos!
- I have some ideas for how to make the features list in the platform section a bit more interactive, too—first we should check that that list is up to date ( for example it talks about geoblacklight location features, which we have turned off).

**Comment by jleighherzog** [comment]
- Those expandable menus (board/staff/advisors) -- love! 

- Thoughts on using a gradient color scheme for [Dryad's timeline](https://dryad-dev.cdlib.org/stash/about#origins) so that each year is different? My eye is grouping years having the same color. If not, no biggie. 

- Within the 'Our curation and publication processes" heading, can you update this paragraph, please? 

Current: 

> Dryad Curators do not verify, validate or authenticate data for scientific reuse, however, they do assess submissions carefully and raise questions for investigation/escalation when there are concerns about the reusability, provenance, interoperability, or comprehensibility  of the data submitted for publication in Dryad. We do not attempt to assess rigor. 

Updated: 

> Dryad Curators assess submissions carefully and raise questions for investigation/escalation when there are concerns about the reusability, provenance, interoperability, or comprehensibility of the data submitted for publication in Dryad. We do not attempt to assess rigor.

**Comment by ahamelers** [comment]
@jleighherzog I've added 2 more colors to the timeline. For changes to the new content, can you go to #2250 (or the google doc linked therein) so Jen has a chance to take a look at your edits?

**Comment by ahamelers** [comment]
>I put the link to the blog under 'Help' (not a great place for it), I think there are better ways we can incorporate the blog into the main site—we could show snippets of the most recent couple of posts, or posts based on tags, in some different contexts including on the home page.

The incorporation of latest posts is done and the help link is removed.
