### ISSUE TITLE
Rotate Merritt credentials

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2275]
This is much like the others.

1. Get new user/pwd from merritt.
2. Update our config & test & release our app
3. disable old user/pwd or set to something long that no one knows

PS.  I mentioned to Terry/Eric and verified that they can create additional accounts for us when we do this.

See https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2133

**Comment by ryscher** [comment]
No longer needed.
