### ISSUE TITLE
Rotate EZID credentials

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2276]
We will need to check with EZID to see if they can create an additional account that has the same access as our current one.  If so:

1. New account
2. Update app credentials & test & release
3. disable old

Otherwise we'll need to synchronize credentials updates in both places.

See https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2133

**Comment by ryscher** [comment]
No longer relevant.
