### ISSUE TITLE
Rotate ORCID credentials

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2278]
We use ORCID with API keys, OAuth style.  I believe they create new credentials by contacting them and there isn't an automated way from their site (much like us).

If they'll issue additional credentials for our sites then we can create new API keys and then revoke the old ones once the new ones are in place.

This will be a longer process since it will require some communication with them and more testing since our login comes from them and we use their API during login.

See https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2133

**Comment by ryscher** [comment]
Closing as no longer relevant, since we will be moving to a new ORCID account soon.
