### ISSUE TITLE
Instructions for Hackio.md markdown editor are confusing

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2281]
This was never the most elegant solution, but it seems like they've also changed their site so the instructions no longer work well.

1.  Clicking the + sign to duplicate a template now has a menu for "new markdown" or "choose from a template" and the templates it includes are like resumes and other random crap (not our template).
2. I believe in the past, it would duplicate the template we have but now it starts a new document without starting from a template.

The whole process seems confusing for someone who might not know what markdown is.

I know we avoided putting this in because it's hard to fit more in the file upload flow and it's a bigger rework project.  Yet I think even if we popped up our own editor in a new window with stuff pre-filled, it would be better than what we have now and the confusing process.  Super extra bonus points if there was a save button and it uploaded into their files with the right name.

This just seems extra icky flow that is really awkward right now.

**Comment by ahamelers** [comment]
Closing and handling in #2410
