### ISSUE TITLE
Cursor jumps to end of text entry in certain metadata fields

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2289]
Priority: Medium
Impacted: curators

In fields where authors are intended to match to a certain system, moving the cursor to a position within the entered text and entering any character will jump the cursor back to the end of the text entry. The same behaviour occurs when deleting a single character within the text entry as well. This occurs in the fields for Journal Name, Institutional Affiliation, Research Facility, and Granting Organization (but not Research Domain). This makes it tedious for curators when we need to add a word to the front to get a match (e.g., _The_ Ohio State University) or to spell out a listed abbreviation (e.g., U.S. to United States); similarly, going in reverse (requiring point deletions) is also tedious because of this. Probably in a related vein, it's not possible to delete an entire field's text (you have to delete all but the first character and then remove that last one); this comes up sometimes because we normally remove the Research Facility if it's the same as the authors' institutional affiliation.

**Comment by ahamelers** [comment]
It looks like this is a bug in the component we use to create these elements: https://github.com/downshift-js/downshift/issues/1108
