### ISSUE TITLE
Fix sitemap.xml file for new system

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#229]
Things we need to fix about the sitemap.xml.

- [ ] Make it list everything for all domains.
- [ ] Make it query off the curation status for what is public to view rather than the Merritt status.
- [ ] Make it cache for a long while (like an hour or a day) since we don't want to hit our database all the time to make this file, especially if it has like 25,000 items in it which we will have with Dryad.
- [ ] If it's still too slow we may want to generate it outside the web application on a cron and drop it in the /public folder for the application where it will be served as a static file.

**Comment by ryscher** [comment]
This has been working for a long time
