### ISSUE TITLE
Require a README file for all datasets initiated prior to 12/21/2021

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2290]
**Priority**: Medium 
**Impact:** Curators, submitting authors

Dryad currently requires a README file for all new submissions. This requirement was enabled around December 21, 2021. 

Still, there are submissions that were initiated before the requirement was implemented. And, for those, it's highly likely that we will need to request a README file. To save time: 

1) For submissions that are 'In Progress' prior to Dec 21st, can we enforce the README file requirement prior to submission? 

2) Can we ensure that Curators can bypass the requirement while in editing mode? This will save the Curator time in creating a 'dummy' file to upload in order to proceed.

**Comment by ryscher** [comment]
@jleighherzog To clarify, do you want to extend the README requirement to *all* legacy datasets? Or just back to the cutoff date when we launched the current system (Sept 17, 2019)?

**Comment by jleighherzog** [comment]
Decided that this isn't a requirement, Chances are, an updated README will be required. Will close the ticket.
