### ISSUE TITLE
Add previously withdrawn check for ORCID email

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#2294]
From @jleighherzog  in #2195

> When withdrawn submissions are reinstated, the authors and co-authors will receive the same confirmation email as before which also contains the same offer to co-authors to add their ORCID iDs. Can we NOT send a notification? If reinstatement is requested, we usually respond to the author's email to let them know it's back in play.

**Comment by ahamelers** [comment]
@jleighherzog It looks like the ORCID invitation email only goes out when a is published—are you saying there should be a check where emails are not sent out again if it was previously published?

**Comment by jleighherzog** [comment]
@ahamelers : Based on the [diagram](https://docs.google.com/drawings/d/1rTW6uvpnJEXNVGHcCMc3Kd1NO0CJlIcIYQ8QtIe0Nfw/edit), looks like the ORCID invitation (b) is sent upon initial submission. Can you check my understanding? Looking at this ticket, I think we should ignore it. It's not often that a withdrawn submission is reinstated so, even if they receive the same message as before, it's probably a good thing that the co-authors know the dataset has been resubmitted. Closing it.

**Comment by ahamelers** [comment]
It would be good if maybe @ryscher could verify what I'm seeing in the code against the diagram —I'm only seeing the email sent at publishing but I could definitely be missing something!
