### ISSUE TITLE
Admin page display table changes widths, squishing column headers

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2297]
Priority: Low
Affected: Anyone using the admin site

The admin page view showing any given filtered table of datasets seems to change widths based on some attribute of the displayed datasets' fields. This can lead to "squishing" of one or a few columns, which although not a substantial functional issue for curators, may appear unsightly to other users of the interface.

![Screen Shot 2023-02-14 at 5 17 53 PM](https://user-images.githubusercontent.com/113212676/219091731-a80b47bc-b928-4947-9d66-2a1bc6c04f7c.png)
![Screen Shot 2023-02-14 at 5 17 36 PM](https://user-images.githubusercontent.com/113212676/219091739-26a216a0-5ed2-4d7f-b69b-a5952c7e867e.png)

**Comment by ahamelers** [comment]
I'm going to use this ticket as an excuse to redesign all our "sortable" tables 😄
