### ISSUE TITLE
Technical onboarding -- Steve Diggs

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2303]
Steve has received some accounts, but still needs access to Dryad servers, Google docs, etc.

---
**Full name:** Steve Diggs

**Position:** Product Manager

**Dryad email address:**  Steve.Diggs@ucop.edu

**Personal email address:** 

**ORCID:** 

**Github username:** sdiggs

Please complete the [onboarding tasks](https://docs.google.com/document/d/1xj27OsuMgWbuaeWqXkgsAWOBiSx9L-8uNbfpVmzbd5o/) for this new staff member.

**Comment by ahamelers** [comment]
I've added Steve to this repo, but I do not have the power to add him to the [Dryad Devs Team](https://github.com/orgs/CDL-Dryad/teams/dryad-devs) or to https://github.com/CDL-Dryad, @ryscher

**Comment by ryscher** [comment]
Added to GitHub.

**Comment by ahamelers** [comment]
Hi @sdiggs, we need a bio and a headshot of you for [our staff page](https://datadryad.org/stash/about#our-staff)!

**Comment by sdiggs** [comment]
> Hi @sdiggs, we need a bio and a headshot of you for [our staff page](https://datadryad.org/stash/about#our-staff)!

![scd_headshot_Atlanta_Blueshirt_2018](https://user-images.githubusercontent.com/12074379/224167880-2796d756-af4f-4078-942c-0153a7d50ade.png)

**Comment by ahamelers** [comment]
Don't forget a bio @sdiggs !
