### ISSUE TITLE
Offboarding: Carolyn Tarpey

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2309]
Please follow the [offboarding procedures](https://docs.google.com/document/d/1xj27OsuMgWbuaeWqXkgsAWOBiSx9L-8uNbfpVmzbd5o/edit#heading=h.r2jddholk1n2) for Carolyn and deactivate all related accounts.

Additionally, please remove Carolyn's profile from the [Our Team](https://datadryad.org/stash/our_staff) page on the website.

Due date: Friday, February 24 (end of business on this day; 6pm Pacific)

**Comment by jleighherzog** [comment]
@ahamelers @ryscher : Note: Please be sure that any returned revisions or versioned submissions are distributed in rotation among the curators. I think Joseph's were all reassigned directly to me.

**Comment by ahamelers** [comment]
@jleighherzog In the offboarding procedures we ask for a specific person who should be assigned any of the assigned datasets from the leaving curator, either to handle to to reassign, I believe that not being provided is why ones have been assigned to you in the past. There's not currently a mechanism to distribute them at random!

**Comment by jleighherzog** [comment]
@ahamelers : They were randomly reassigned upon resubmission. I'm sure of it. Let's check with @ryscher!

**Comment by jleighherzog** [comment]
Here's an example of a random auto-assignment, check Activity Log notes: https://datadryad.org/stash/ds_admin/activity_log/90213

**Comment by ahamelers** [comment]
@jleighherzog Sorry for the confusion, I think we were talking about 2 different things, I'm talking about any that are currently in Curation status only! As stated in the procedures:

>If there are any datasets assigned to them in “Curation” status, Ryan will assign all datasets to ??? for team reassignment, if necessary

You are right that any in other statuses, that were _previously_ assigned to Carolyn, should already be automatically randomly distributed if they're returned 😄

**Comment by jleighherzog** [comment]
Thanks, @ahamelers. That makes sense.

**Comment by ahamelers** [comment]
This is done!
