### ISSUE TITLE
PPR links still disabled for reinstated datasets when previously withdrawn by curator

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2310]
Priority: High
Affected: Authors, curation team, journal offices/reviewers

#2238 previously dealt with the PPR links not working when an author reinstated a dataset after it was automatically withdrawn via notification from the journal. It seems that this behaviour is still in place for when datasets are withdrawn manually by a curator (e.g., after chasing the author unsuccessfully). As we've been able to keep the queue down, we've been chasing AAR'd datasets that have yet to be actioned and been receiving more reinstated datasets that had been previously withdrawn due to inactivity (as of 2/16, this [unpublished dataset](https://datadryad.org/stash/ds_admin/activity_log/80643?) would be a good example; I'll tag in more if I can find them in case that one gets published soon).

**Comment by ryscher** [comment]
TODO: find datasets anything with `pub_state=='withdrawn'`, but current curation status isn't actually withdrawn. Set them to 'unpublished'.

**Comment by ryscher** [comment]
Ran a script to correct all of the affected items as described above.
