### ISSUE TITLE
Remove data files (10.5061/dryad.r4xgxd29s, 10.5061/dryad.b8gtht78d, 10.5061/dryad.bnzs7h45v)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2313]
**Priority**: URGENT

The author of these published datasets contacted us with a request for removal: 

10.5061/dryad.r4xgxd29s - too many direct/indirects (age, bmi, dayadmission [date]) and undefined columns, minors
10.5061/dryad.b8gtht78d - age, gender, marital status, employment status, retirement status, and undefined columns
10.5061/dryad.bnzs7h45v - age, gender, death, bmi, and undefined columns

From the author: 
> "The problem is that the datapoints can be combined and result in the potential identification of the patient. For example: the age with specific lab values and other demographics can identify the Patient. Our IT department as well as our institutional ethics committee have major concerns regarding these issue. The anonymization of the data is unfortunately not sufficient."

Removing the data files is the first step. Next, I'll work with the author to determine 1) whether the files will be replaced and 2) what type of notice we'll post for future users/readers.

**Comment by ryscher** [comment]
I set embargoes on these datasets at Dryad and Zenodo. Will let Jess decide whether any other action is needed.
