### ISSUE TITLE
Pensoft journals for email integration

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2317]
**Priority**: Medium
**Impact**: Integration of journal titles

Attached is a spreadsheet that contains a list of Pensoft titles to be set up for email integration. There are approximately 65 titles in the list. Pertinent information provided for set up: 
> Journal title
> ISSNs
> Sample manuscript number format

If any additional information is required, please let me know. 

[DRYAD_Pensoft_Publishers_hosted_journals.xlsx](https://github.com/CDL-Dryad/dryad-product-roadmap/files/10786684/DRYAD_Pensoft_Publishers_hosted_journals.xlsx)

**Comment by jleighherzog** [comment]
Q:  What do Yes/No/? entires mean in column G of the spreadsheet (Dryad Data Submissions)?

A: The spreadsheet is prepared by our Indexing team, so I also had to ask the same - what do Yes/No/? mean. It's their response to the question on whether the journal has already been integrated with DRYAD or not. So the firm Yes and No confirm or deny this, while the ? expresses a doubt, and at the same time it's a question - whether the journal needs to be integrated or not. Following an internal discussion in this regard we decided to provide you with the full list and ask for all journals' integration. This way you will also be able to check the list of the integrated journals (marked with Yes in the G-column), update their details if needed, and then integrate the rest of them (marked with No and ? in column G).

**Comment by ryscher** [comment]
Steps to perform:
1. Check whether the journal exists in Dryad. If not, create it
2. Add all ISSNs
3. Copy manuscript_number_regex and notify_contacts from ZooKeys
4. Set the sponsor_id to be 75 (Pensoft), so we can track these journals together, even though there is not currently a payment plan.

**Comment by ahamelers** [comment]
There are a couple of journals already in the database with pensoft as the payment_contact that aren't in this sheet:

- International Journal of Myriapodology
- Zoologia

Should they get the new sponsor_id as well?

**Comment by ahamelers** [comment]
This is done, minus the question above!

**Comment by ryscher** [comment]
Those two journals are no longer published by Pensoft, so no need to add them.
