### ISSUE TITLE
Add Google Analytics to blog.datadryad.org

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2322]
To give us greater visibility into blog traffic, I'd like to have Google Analytics deployed on the blog.datadryad.org domain. We'll need an additional property (see screenshot for reference) for the blog domain and the Google Tag code installed on the Wordpress site.

![Screenshot_2023-02-21_at_15 45 43](https://user-images.githubusercontent.com/82666810/220570441-5843d0c8-df3f-4508-8944-e0edf1ebf451.png)

**Comment by sarahklippincott** [comment]
I have a semi-related question to add to this. What would be involved in migrating the blog to the primary domain (from blog.datadryad.org to e.g., datadryad.org/news)? Would this be a minor or major undertaking?

**Comment by ryscher** [comment]
My first thought is that it's major, because it would require us to install and manage our own copy of Wordpress. There may be a way to proxy the existing site through Rails, which would be less effort, but I suspect it would be much more fragile.

**Comment by ahamelers** [comment]
@sarahklippincott Because `blog.datadryad.org` is a subdomain, we can direct wordpress.com to use it as the URL for the blog site, which is hosted on their servers. We could not do the same thing using our direct domain and a path, which is what datadryad.org/news is. 

I wonder what is the thinking behind this question—what is the desired outcome? With our current setup, we can make the blog site appear identical to, or as a sub-page of the regular Dryad site. We can also do something like put in a redirect, so that `datadryad.org/news` goes to the blog. If you tell us the outcome you are looking for, we can provide options.

**Comment by sarahklippincott** [comment]
The primary motivation was to be able to track website and blog analytics together (this was a suggestion from Kelly, our marketing consultant). Secondarily, Jen is interested in moving away from the word "blog" to "news" in the URL (which I imagine doesn't necessarily require moving domains).

**Comment by sarahklippincott** [comment]
> We should be able to track the domain and subdomain together using the same property, I think slightly differently depending on which version of google analytics we have. I can try to set this up if that's desired.
> 
> If this is a goal, could we change the blog subdomain to news.datadryad.org? That would not require us to move hosting from wordpress and handle hosting ourselves, which would be a bigger undertaking.

Thanks @ahamelers ! Let me check in with Kelly and Jen about both of these things. I'll be back to you shortly.

**Comment by sarahklippincott** [comment]
@ahamelers Please do try to track the domain and subdomain together using the same property, if possible.

Hold off for now on changing the subdomain prefix. I'll follow up about that in a separate ticket if we decide to move forward.

**Comment by ahamelers** [comment]
> Please do try to track the domain and subdomain together using the same property, if possible.

This should be done, though some settings take 24 hours to begin working. Please check in a few days and let me know if you see anything unexpected or would like anything refined.

**Comment by sarahklippincott** [comment]
@ahamelers Thank you! We can now see traffic for the blog.datadryad domain overall which is great. 

However, we want to be able to break the traffic down by individual blog post/page like we're able to for the main domain. Can that be done?

**Comment by ahamelers** [comment]
@sarahklippincott I think that should be happening, but I may have set up the filter to display the full URL wrong, please give it another 24 hours 😄
