### ISSUE TITLE
Improve github issues and project board

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#2327]
- [x] Go through [all the open issues that are not in the project](https://github.com/CDL-Dryad/dryad-product-roadmap/issues?page=1&q=is%3Aopen+no%3Aproject). Either add them to the project, or close them (@ryscher @sfisher)
- [x] Remove 'Completed' column from the [board status options](https://github.com/orgs/CDL-Dryad/projects/1/settings/fields/Status). When a sprint review is over and issues are completed, [archive them](https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-items-in-your-project/archiving-items-from-your-project).
- [x] Create new custom field for numbered Sprint
- [x] Create new custom field for priority/due date (or both) (TBD)

**Comment by ahamelers** [comment]
I started doing item 1 before creating this ticket, then realized it was smarter to have you two take a look rather than me adding dozens of tickets to the board all with is-this-done? tags 😆

**Comment by ahamelers** [comment]
I've changed sprints from labels to milestones on github, because we weren't using milestones for anything else

**Comment by ryscher** [comment]
I added fields for priority and due date, and filled in values for the current sprint. Also added a "By Priority" view.

**Comment by ryscher** [comment]
Scott and I cleaned up the last of the issues that were not on the board.
