### ISSUE TITLE
Give full-time curators admin permissions on VE

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2329]
Priority: Medium
Affected: Curators using the VE (so mostly Bryan)

Previously, Amelia had admin permissions on the VE to install programs, update existing ones, etc. It would be ideal if full-time curators (so me and Laura) could get those permissions so that we can add packages/libraries (in MATLAB and R in particular) and do periodic updates of programs like Fiji on our own. I will promise not to download Taylor's entire discography onto the desktop.

**Comment by ahamelers** [comment]
Done!
