### ISSUE TITLE
Provide Isabel Sanmartin access to Systematic Biology datasets

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2330]
Priority: Low

Isabel Sanmartin, Editor-in-Chief, of _Systematic Biology_ has access to Dryad's Admin site. 

Can you kindly update her profile to allow her access to datasets associated with _Systematic Biology_?

Email: isanmartin@rjb.csic.es
ORCID iD: 0000-0001-6104-9658

**Comment by ahamelers** [comment]
This is done!
