### ISSUE TITLE
Change SWORD endpoint to collection name and simplify Merritt config

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2332]
This is a small incremental change, but I'm hesitant to do it immediately in case we need to roll back to SWORD if there are problems.

We're mostly extracting a collection name from Merritt endpoint SWORD urls.  We could just change this to a collection name and simplify code.  Will require changes a number of places in code, some fixture data and tests.

For now we can continue pretending like all collections have SWORD urls.  A further refinement is that I think we can remove the Merritt configuration from each individual tenant and put it in the app_config.yml since I believe each full environment only uses one collection now.

**Comment by ryscher** [comment]
Closing, as we no longer use SWORD
