### ISSUE TITLE
Add permissions for SUNY Consortium administrator

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2333]
Please provide Catherine Stollar Peters with access to systemwide administrative dashboards for the SUNY consortium (let me know if you require a list of members) and pre-authenticate. 

**ORCID id:** 0000-0002-3810-1881
**email:** Preference for `marycatherine.peters@esc.edu` ; if institutional email address is required `catherine.stollarpeters@suny.edu`

**Comment by ahamelers** [comment]
This user has been set to an admin for the SUNY consortium tenant, however we need to investigate more to be sure that consortia dashboard viewers have access to see everything they should
