### ISSUE TITLE
Onboarding: Evangeline Janani

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2334]
**Priority**: Medium (set up within 1 week)
**Impact**: Ideally, user is set up by Friday, March 3rd at the latest so that I can provide access to documentation, Dryad site, etc. 

A new Data Curator, Evangeline Janani, is expected to begin onboarding Tuesday, February 28. Please begin to provide Evangeline with access to all necessary accounts/systems/etc. Please reference [this GDoc](https://docs.google.com/document/d/1xj27OsuMgWbuaeWqXkgsAWOBiSx9L-8uNbfpVmzbd5o/edit#) for the onboarding tasks.

Evangeline Janani
Work email: evangeline.j@kriyadocs.com
Suggested Dryad email: evangeline@datadryad.org

Once set up with a Dryad email address, I'll ask Evangeline to log into our system to confirm access. If you need more information, let me know.

- [x] Create Google account
- [x] Invite to Slack
- [x] Provide access to VE
- [x] Salesforce access (when a license is available)
- [x] Send instructions for accessing these accounts

**Comment by jleighherzog** [comment]
@ahamelers @ryscher: Need this today. Possible?

**Comment by ahamelers** [comment]
Mostly done 😄

**Comment by ryscher** [comment]
The Salesforce account is set up, but we will need to add the ORCID so creating new cases from Dryad works correctly. Otherwise, I think we're done on the dev side.

**Comment by jleighherzog** [comment]
Added ORCID iD to Evangeline's Salesforce profile

**Comment by ahamelers** [comment]
@jleighherzog Can you open another ticket with Evangeline's photo and bio?

**Comment by jleighherzog** [comment]
@ahamelers : Jeremy can do this. I sent him the bios and photos today.

**Comment by ahamelers** [comment]
Ah, I asked because I've already got a pull request in with edits on that page. @jeremywalter , can you send me the bio and photo? Or, just push your commit to [the static-content-updates branch](https://github.com/CDL-Dryad/dryad-app/pull/1131)

**Comment by jleighherzog** [comment]
@ahamelers : Can you copyedit as needed and edit the photos, if necessary?

**Comment by ahamelers** [comment]
@jleighherzog , sure! I've moved adding these people to the staff page to #2368
