### ISSUE TITLE
Remove files for 3 published datasets

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2336]
**Priority**: Medium-Low (because files are already embargoed)

The author of these published datasets contacted us with a request for removal. Unfortunately, despite several requests, the authors are unable to provide updated files that will meet our requirements for publication. 

These submissions are currently embargoed. Next steps are to remove the data files from Merritt, Zenodo, etc. -- prefer to keep the metadata live, available. I'll plan to post a note in each dataset and link to the Corrections that will be published by the journal. 

- 10.5061/dryad.r4xgxd29s - too many direct/indirects (age, bmi, dayadmission [date]) and undefined columns, minors
- 10.5061/dryad.b8gtht78d - age, gender, marital status, employment status, retirement status, and undefined columns
- 10.5061/dryad.bnzs7h45v - age, gender, death, bmi, and undefined columns

From the author:
> "The problem is that the datapoints can be combined and result in the potential identification of the patient. For example: the age with specific lab values and other demographics can identify the Patient. Our IT department as well as our institutional ethics committee have major concerns regarding these issue. The anonymization of the data is unfortunately not sufficient."

Related to this ticket: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2313#issue-1588420668

**Comment by sfisher** [comment]
These datasets are removed from Dryad and related systems now.  Mark is removing this from Merritt, also.
