### ISSUE TITLE
Import metadata function error message

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2337]
Priority: Medium
Affected: Authors, Helpdesk

We've received two separate HD queries today about the Import Metadata function not working. In one of the author's own words:

> I'm trying to upload a dataset for my recently accepted article in Journal of Animal Ecology to Datadryad. However, after logging in, picking "a manuscript in progress" and picking the "Journal of Animal Ecology" from the dropdown list and entering my manuscript number "JAE-2022-00616", I get the following error message: "Please select your journal from the autocomplete drop-down list" and your system does not import any manuscript data.

The second case was for this journal submission: Functional Ecology, FE-2022-00975.R2

I tested creating datasets on the live site with these metadata, matched the journal, and the Import Metadata button became active, but I received the same error as the author quoted above. I'm not sure if this may be related to the recent fix for the issue of journal matching and multiple ISSNs.

**Comment by ahamelers** [comment]
Is this still an issue?

**Comment by bryanmgee** [comment]
I haven't seen this in HD in a long time, I think it's not an issue anymore
