### ISSUE TITLE
Improve documentation of Shibboleth

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2342]
Our Shibboleth interactions should be better documented, so we can understand the dependencies.

Documentation we provide to new members: https://docs.google.com/document/d/14NmHkg__5xOgkg5fTeizuaqOwCcLlKinouMLz9a_BNY/edit?usp=sharing

**Comment by ryscher** [comment]
For InCommon, we can look up the IDP here: https://incommon.org/community-organizations/

**Comment by marisastrong** [comment]
[UC3-ShibbolethServiceProvider-240823-1523-104.pdf](https://github.com/CDL-Dryad/dryad-product-roadmap/files/12433817/UC3-ShibbolethServiceProvider-240823-1523-104.pdf)
