### ISSUE TITLE
Geoblacklight styles are off on "explore"

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2345]

**Comment by ahamelers** [comment]
@sfisher Hi Scott, I can see the icons and text are overlapping which is very weird! I'll take a look.

**Comment by ahamelers** [comment]
It was a very basic order of operations thing—I put in a default line height for our static pages in the wrong spot, so it overwrote some geoblacklight line heights. I've put in a pull request 😄
