### ISSUE TITLE
Journal update status (journal sends email and that triggers curation status change)

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#236]
If article is rejected, set status to "Withdrawn"
If article is accepted, set status to "Submitted"

old system calls new system with status changes based on receiving metadata from journals

**Comment by ryscher** [comment]
Ryan's notes on how to manually test this feature:

# Send email for an existing journal:

To: journal-submit@datadryad.org
Subject: Prepopulation data email

Journal Name: Journal of the American Medical Informatics Association
Journal Code: JAMIA
Print ISSN:	1067-5027
Online ISSN: 1067-5027
MS Reference Number: abc123-f
Article Status: submitted
MS Title: Example dataset for curator demo
MS Authors: Someone, Joe; SomeoneElse, Tina
Abstract: I'm So Abstract
EndDryadContent

# set the email to use the tag
# (can remove old tag if it's not needed on production server)
dev-journal-submit

# process the email
curl http://ryan-vm.datadryad.org/journal-submit/retrieve
curl http://datadryad.org/journal-submit/retrieve

# can see in the (old) DB with
select * from manuscript order by manuscript_id desc limit 1;

# on new dryad (dev server), make a submission from the manuscript, 
	# import the manuscript metadata
	# select the option for peer review
# wait for the notifier to move into “private for peer review“ status

# send an email with "accepted"

Journal Name: Journal of the American Medical Informatics Association
Journal Code: JAMIA
Print ISSN:	1067-5027
Online ISSN: 1067-5027
MS Reference Number: abc123-f
Article Status: accepted
MS Title: Example dataset for curator demo
MS Authors: Someone, Joe; SomeoneElse, Tina
Abstract: I'm So Abstract, I'm accepted
EndDryadContent

# verify that the item was automatically moved into “submitted” status, ready for curation, and that it has a curator note indicating what happened
