### ISSUE TITLE
Bug: You are not authorized to download this file until it has been published

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2360]
To reproduce, go to Dryad dev dataset at https://dryad-dev.cdlib.org/stash/dataset/doi:10.5061%2Fdryad.0t2c8 .  Click to download a zip file while logged in as a user that is a superuser.  

You get the message "You are not authorized to download this file until it has been published."  But a superuser should be allowed to download anything.

Perhaps it's either a permissions error or else this file doesn't actually exist (we have some data consistency problems on dev).  🤔   I suspect this may not be a serious issue or we would've heard about it.

**Comment by ryscher** [comment]
This issue went away when we purged the dev database.
