### ISSUE TITLE
PRIORITY: Medium -- Provide member access to Paleobiology and Journal of Paleontology

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2362]
**Priority**: Medium
**Impact**: Anne is the President of the Paleontological Society. It would be great if we could provide her with access before the end of this week (March 10)

Could you please provide Anne Raymond with access to _Paleobiology_ and _Journal of Paleontology_

ORCID iD: 0000-0001-9835-1789
Email: raymond@geo.tamu.edu

**Comment by ahamelers** [comment]
This is done!
