### ISSUE TITLE
Add Tenant: Stony Brook University

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2364]
**Tenant name:** Stony Brook University

**Logo location:** 
![SBU horz_2clr_rgb_300ppi](https://user-images.githubusercontent.com/82666810/223683749-387ea818-2dda-478b-8860-7ca967e14ff2.png)

**Contacts to receive submission notices:** None

**RORs that are considered part of the tenant (including medical centers, alternate campuses, etc.)** https://ror.org/05qghxh33

**Shibboleth info, if not in [InCommon](https://incommon.org/community-organizations/):** InCommon member

Tasks:
- [x] add config to dryad-config repo
- [x] add logo to dryad-app repo
- [ ] deploy and test on stage (institution should log in to verify working as expected)
- [ ] update tenant_id for users in the database who have emails with the institutional domain name
- [x] add institution's name to the Dryad website

**Comment by sarahklippincott** [comment]
@ahamelers @ryscher I'm not seeing Stony Brook in the dropdown at https://datadryad.org/stash/user_admin. My contact at Stony Brook had the same issue when attempting to log in.

**Comment by ahamelers** [comment]
Hi @sarahklippincott , this was automatically "closed" by the merging of the code into the master branch, but this won't be released and ready for users until 28 March. Sorry for the confusion, and I hope that is okay!

**Comment by sarahklippincott** [comment]
@ahamelers Ah, that makes sense. No problem and thanks for the update on the timing.

**Comment by sarahklippincott** [comment]
@ahamelers I had another inquiry from Stony Brook -- are they still scheduled to "go live" today?

**Comment by ahamelers** [comment]
Yes, the release will be end of day today (California time). The new tenants will be on the staging server around noon (also California time) if there's any desire to test there.

**Comment by sarahklippincott** [comment]
Thank you!
