### ISSUE TITLE
Question about staging site and API integration testing for AAAS

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2367]
**Bug description:** 
AAAS is in the process of completing their API integration and follow-up testing. They are using the Dryad staging site and their developers are getting the message on the final page of submission that authors will be invoiced for the cost of publishing their data (see screenshot).  

When on _staging_, should they be seeing the message that data deposit has been sponsored? I'm not sure if this is just because of the environment, or if they aren't set up correctly in our system.

![Screenshot 2023-03-08 at 4 27 40 PM](https://user-images.githubusercontent.com/82666810/224258287-0552c4ec-7b84-48fb-846a-bc206e253054.png)

**Comment by ryscher** [comment]
AAAS is not yet set up... ticket https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2283 is in progress. They should be set up early next week.

**Comment by sarahklippincott** [comment]
Got it, thanks @ryscher
