### ISSUE TITLE
Curator access for VE

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2372]
**Priority**: Medium
**Impact**: New curators will be able to download and curate large files

Provide curators with access to the virtual environment: https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/external_services/curator_pc.md 

> **Sachin Gopinath**
> sachin@datadryad.org
> 
> **Prerana Charakara Sukumar**
> prerana@datadryad.org
>
> **Evangeline Janani**
> evangeline@datadryad.org

**Comment by ahamelers** [comment]
Waiting for final list of curators/due date.

**Comment by jleighherzog** [comment]
@ahamelers : Please add all curators to the VE by Friday, March 31st

Sachin Gopinath
[sachin@datadryad.org](mailto:sachin@datadryad.org)

Prerana Charakara Sukumar
[prerana@datadryad.org](mailto:prerana@datadryad.org)

Evangeline Janani
[evangeline@datadryad.org](mailto:evangeline@datadryad.org)

**Comment by ahamelers** [comment]
All curators have been added and an email with access instructions has been sent to their dryad email.
