### ISSUE TITLE
Add Tenant: University of Pennsylvania

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2375]
**Tenant name:** University of Pennsylvania

**Logo location:** https://idp.pennkey.upenn.edu/UPenn_logo.png

**Contacts to receive submission notices:** 

**RORs that are considered part of the tenant (including medical centers, alternate campuses, etc.)** https://ror.org/00b30xv10

**Shibboleth info, if not in [InCommon](https://incommon.org/community-organizations/):** InCommon member

Additional info in [tech onboarding spreadsheet](https://docs.google.com/spreadsheets/d/1rs9sc3c0bmKRsjLap94AwaADvLDo0mCUHvoIrLNiXwM/edit#gid=0).

Tasks:
- [x] add config to `config/tenants`
- [x] add logo to `app/assets/images/tenants`
- [ ] deploy and test on stage (institution should log in to verify working as expected)
- [ ] update `tenant_id` for users in the database who have emails with the institutional domain name
- [x] add institution's name to the Dryad website

@ryscher @ahamelers @sfisher @sdiggs @marisastrong

**Comment by ahamelers** [comment]
The institution name on the website is now automated from the tenant config (#1115)
