### ISSUE TITLE
Salesforce credentials on stage

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2383]
(related to #2120)

These credentials suddenly stopped working, and the failure to load prevented the Activity log from displaying.

I temporarily commented out the Salesforce section from the Activity log page on stage.

**Comment by sfisher** [comment]
Seems like this has happened a few times.  If it's not a lot of effort to do so, I'm thinking we can rescue Salesforce errors and just indicate an error in part of the page rather than preventing the whole page from loading.
