### ISSUE TITLE
(PRIORITY) Dryad sandbox: Error message when attempting to access Activity Log

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2384]
**Priority**: High
**Impact**: Current using sandbox for training purposes

The following error message appears when users attempt to access the Activity Log for test submissions 

![Screenshot 2023-03-20 at 8 18 21 AM](https://user-images.githubusercontent.com/76497320/226350941-d7050335-5119-45e2-85c9-a11071661596.png)

**Comment by jleighherzog** [comment]
<img width="930" alt="Error" src="https://user-images.githubusercontent.com/76497320/226393244-f878734b-0e8e-477d-93c2-d228ac3eeaf7.png">

**Comment by ryscher** [comment]
@jleighherzog This is now working
