### ISSUE TITLE
Upgrade sandbox permissions for user

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2388]
Please provide admin permissions to sandbox user Jonah McAllister-Erickson (https://sandbox.orcid.org/0009-0001-1126-0575). If this is something I can do in future, I'm happy to learn how!

**Comment by ryscher** [comment]
I assigned some permissions, but this user is not currently attached to a member. Is there a particular institution/journal that they should be attached to?

I also increased your permissions, Sarah, but you don't yet have access to change the user settings yourself. We are in the process of updating our permissions system, so you should be able to do this in the near future.

**Comment by sarahklippincott** [comment]
@ryscher This is a prospective member. Will they be able to see any data without being affiliated with a member?

**Comment by ryscher** [comment]
They will be able to see some data in the dashboard. It will be relatively random test data that was created by various users testing the system out.
