### ISSUE TITLE
Update Salesforce to track volunteers for user testing

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2393]
Salesforce already contains information about potential testers -- representatives of member organizations. Curators also spend a lot of time corresponding with users in Salesforce; many of these could be turned into testers. Consult with CloudMasonry on the best way to track these people.

**Comment by ryscher** [comment]
CloudMasonry may not be able to do much during their current contract, so some of this work may need to be postponed until summer.

**Comment by ahamelers** [comment]
Strategy outline document: https://docs.google.com/document/d/1UuXUI7VQujlC4Y8n2p-xqlaTNWHHq9VTlhq2Z9CNvto/edit?usp=share_link
