### ISSUE TITLE
Collect volunteers for user testing

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2394]
Develop methods that we can use to gather volunteers for user testing. This may include:
- emails to existing contacts in Salesforce
- standard footer in response to helpdesk tickets
- form on the Dryad website

Consult with the UX group as needed.

**Comment by ahamelers** [comment]
Drafted emails for curator use: https://docs.google.com/document/d/1d-L8iBkHhoe7eB-qGeeBPM7ANnhYvwsQY6WGuVzXijg/edit

I wasn't sure if I should try to hack together something on Salesforce to record what we want for this, or wait until we've had Salesforce set up specifically for this in the next period. I've created a google sheet to store user information temporarily.

**Comment by ahamelers** [comment]
I am working getting approved contact info for a minimal number of users for README testing.
