### ISSUE TITLE
Update 'Join us' page -- Spring

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2395]
Updates related to changing membership models. [Document with new text](https://docs.google.com/document/d/1-2lyQgh8OZQAQBzz5Ossy-qdUS52oNnv50nxbcn8_IE/edit?usp=sharing).

**Comment by ahamelers** [comment]
This is now updated on https://dryad-stg.cdlib.org/stash/join_us, if you'd like to check it before it goes live @sarahklippincott
