### ISSUE TITLE
Prioritize items in curation optimization spreadsheet, add them to task list

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2402]
https://docs.google.com/spreadsheets/d/1crMWGheTHrXt_5vyzyDp8jTeFelUEmBGBkgto7CHpuI/edit?usp=sharing

**Comment by ahamelers** [comment]
@bryanmgee @jleighherzog Please ping me when you've selected values for columns E-G for these!

**Comment by bryanmgee** [comment]
@ahamelers we got a meeting later this week to go over this as a team, so hopefully it'll get done soon!

**Comment by bryanmgee** [comment]
@ahamelers we have now completed scoring (more or less), we did score some for how long we thought it would take to implement and were generally conservative about it

**Comment by ahamelers** [comment]
There are about 20 remaining issues that we need to discuss further before making tickets for; we'll schedule a meeting for this soon!
