### ISSUE TITLE
Update metadata for general recommendations from GREI working groups

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2403]
Determine what updates are needed, if any. Actual tasks may need to be split into separate tickets.

**Comment by ryscher** [comment]
Updates to Datacite metadata:
- add resourceTypeGeneral
- dates:
  - Issued should be an actual date, not just a year -- this should be the metadata publication date (sans embargo)
  - add the Available date (it's on some historical content) -- this should be date any embargo was released
- add schemeURI to the RORs and funder IDs
- In the subjects, remove the prefix "FOS:" when exporting the FOS terms, since it is indicated by the subjectScheme
- Remove the duplicate entry for the FOS term

**Comment by sfisher** [comment]
There are some DataCite problems preventing this from working (AFAICT) which I've moved into separate tickets as dependencies waiting on them 2587 and 2586.

**Comment by ryscher** [comment]
Thanks for the cleanup! All is working as expected. (With the noted exceptions that are in other tickets.)
