### ISSUE TITLE
Replace current counter-processor with DataCite widget (Pilot)

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2409]
I'm assigning myself since I think I'm in the middle of some aspects of this and I'll likely continue with it.

Broad phases:

- [x] Put the new widget into landing pages using the `repoid`
- [x] Follow up with Kristian about how we can log downloads (even if we are not doing it the strict way of https://www.projectcounter.org/code-of-practice-rd-sections/7-processing-rules-underlying-reporting-data/ section 7.1 about return codes).
  - It would be preferable not have to intermediate downloads to serve the http 200 or 304 response codes ourselves and still allow S3 presigned URLs since they are a great feature for not having to dedicate additional server resources for downloads.  This may be counter to COUNTER, which is taking a document-centric approach and implies everything comes from a UI server where tracking is easier.
- [ ] Validation stage with DataCite to compare our log numbers with their tracker tool numbers and understand if it seems reasonable or to understand differences.
- [ ] We need to get backlog of counter reports into the DataCite system since we've had some difficulty with the large compressed-file deposit of the reports.
- [ ] Assuming all stats come from DataCite then we need to update the views/download widget to get (and probably cache) numbers from DataCite.

This is a high level overview and may be smart to break out some of these phases or steps into tickets as we get more details.

**Comment by sfisher** [comment]
Closing this since it's split into separate tickets.
