### ISSUE TITLE
Improve UX for README files

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2410]
https://gsim5h.axshare.com/?id=84iah2&p=prepare_readme_b&g=1 (Design B)

Related:
- #2290

**Comment by ahamelers** [comment]
See also #2281, #2480

**Comment by ahamelers** [comment]
> Feedback screen captured
> 
> ![Screenshot 2023-08-04 at 10 15 47 AM](https://user-images.githubusercontent.com/76497320/258939494-bffe3686-6849-4a84-870a-0e0f0cb70529.png)
