### ISSUE TITLE
Curation and Publication report for Banbury Meeting

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2419]
**Urgency**: Deadline within a month
**Type/Visibility**: Promise to internal stakeholders 
**Ease of implementation**: Will take 1-2 weeks
**Impact**: N/A
_____________________________________________
@ryscher : As discussed, I'd like to obtain data to present at our April meeting. Here are some initial thoughts on what I think might be useful and why. Your input is welcome. If any existing reports are available that capture these stats, please point me in that direction. For all data, might be most useful to capture data between **January 2021-March 2023**.

1) **Size of dataset** (actual if possible, aggregate if not)
Objective: Useful to show the change in file size over the past few years (Jan 2001-Mar 2023) because it highlights the need to address large file sizes AND curator time/effort needed to evaluate submissions

2) **Number of files in dataset**
Objective: same as above

3) **Type of data files uploaded, file extensions** 
Objective: Curation has become increasingly time-consuming & challenging as we're receiving more uncommon file types. This costs curators time in working to figure out what software is needed to open the files, what we should expect to see when opening the files, and impacts overall turnaround times.

4) **Turnaround times**
Objective: I haven't been able to successfully capture how long it takes to evaluate a dataset. The 'Curation' status should be reserved for active evaluation of a dataset, however, I do realize that some submissions linger in this status as curators are working to address escalated issues, download files, etc. AND revised datasets are always resubmitted in 'Curation' status (vs 'Submitted'). This is just to say that I know the stats won't be accurate. 

5) **Queue size over time** (existing ticket [here](https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2239))
Objective: Illustrate the progress made and/or easily identify a growing need for more resources

6) **Curation Start date** (ie date claimed from queue); for all versions
Objective: Capture how long datasets sit in the queue before beginning curation

7) **Status entered after curation** (ie AAR, Withdrawn, Publication, Embargo)
Objective: How many datasets are returned to authors for revision vs have a final decision post-curation 

8) **Total time from 'Submission' to 'Publication'**
Objective: Total turnaround times, over time 

9) **Total time from 'Curation' to 'Publication'**
Objective: Total turnaround times, over time

**Comment by jleighherzog** [comment]
@ryscher : Abbreviated version

**Turnaround times**
Objective: I haven't been able to successfully capture how long it takes to evaluate a dataset. The 'Curation' status should be reserved for active evaluation of a dataset, however, I do realize that some submissions linger in this status as curators are working to address escalated issues, download files, etc. AND revised datasets are always resubmitted in 'Curation' status (vs 'Submitted'). This is just to say that I know the stats won't be accurate.

Total time from 'Submission' to 'Publication'
Objective: Total turnaround times, over time

Total time from 'Curation' to 'Publication'
Objective: Total turnaround times, over time

**Queue size over time** (existing ticket https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2239)
Objective: Illustrate the progress made and/or easily identify a growing need for more resources

**Comment by ryscher** [comment]
Sent a report for the abbreviated request, plus the "easy" things from the original request. Let me know if you have questions. 

Note: Queue size over time (existing ticket https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2239) is forthcoming....
