### ISSUE TITLE
BUG: On stage trouble editing status

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#242]
Can edit status of anything in "submitted" except for this dataset: 10.5072/dryad.8cz8w9j0 which is at "submitted". Why is this?

**Comment by briri** [comment]
Likely some bad data. @sfisher and I ran into a similar issue a week or two ago. Will investigate and update our scripts to make sure no existing data ends up in this situation when you go live.

**Comment by briri** [comment]
Think this was just bad data that should be resolved now that the database has been reset
