### ISSUE TITLE
Troubleshoot AAAS API integration

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2421]
_@ryscher Moving this conversation out of Slack and into a ticket for easier reference._

AAAS is having trouble with their API integration. They report that:

> “While the credentials do seem to be working, the level of permissions does not seem to be configured properly. When Niko tried to create a dataset, he got an error: ‘Unauthorized: only superusers and journal administrators may set a specific user.’ This happened on Sandbox as well, when we were given the regular instead of journal admin account. Can you please give us Journal Admin permissions?”

> @ryscher verified that the account has admin access for the AAAS journals and suspected that they are either (a) omitting the publicationISSN field, or (b) sending an ISSN that we don’t expect. 

They reported back that they are using the following API request and that it _does_ work in the sandbox, but not in production.

```
{
    "title": "Another Test",
    "abstract": "Another Test",
    "authors": [
        {
            "firstName": "Test 1",
            "lastName": "Benetech",
            "email": "test1@team489852.testinator.com",
            "affiliation": "Benetech"
        }
    ],
    "userId": 0,
    "publicationISSN": "0036-8075"
}
```
Is that the ISSN we're expecting?

**Comment by ryscher** [comment]
Root cause: When a journal contains multiple ISSNs, the permissions checker was not searching the array of ISSNs correctly.
