### ISSUE TITLE
Add Tenant: University of Nevada Reno

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2445]
**Tenant name:** University of Nevada Reno

**Logo location:** https://nevada.app.box.com/v/UniversityLogos/file/914932586675

**Contacts to receive submission notices:** N/A

**RORs that are considered part of the tenant (including medical centers, alternate campuses, etc.)** https://ror.org/01keh0577

**Shibboleth info, if not in [InCommon](https://incommon.org/community-organizations/):** InCommon member

Tasks:
- [x] add config to `config/tenants`
- [x] add logo to `app/assets/images/tenants`
- [ ] deploy and test on stage (institution should log in to verify working as expected)
- [ ] update `tenant_id` for users in the database who have emails with the institutional domain name
- [x] add institution's name to the Dryad website

@ryscher @sfisher @marisastrong @ahamelers

**Comment by ahamelers** [comment]
@sarahklippincott We no longer need a separate checkbox for adding the name to the Dryad site; it's now an automatic process 😄

**Comment by ahamelers** [comment]
@sarahklippincott Ryan has updated the 'new tenant' template, so you shouldn't need to worry about manually removing this checkbox or anything 😅

**Comment by ahamelers** [comment]
This is now deployed on stage
