### ISSUE TITLE
Add Maria G. to staff page

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2447]
Please add Maria to https://datadryad.org/stash/about#our-staff after Jen.

**Maria Guerreiro**
Maria is an open science enthusiast who enjoys working collaboratively with researchers and other stakeholders in scholarly communication to drive positive change. Maria joins Dryad after more than ten years in academic publishing,  primarily at the not-for-profit and open-access journal eLife, where she was Head of Journal Development and worked closely with scientists, research organizations and funding agencies in the biomedical and life sciences space in initiatives to drive growth, foster community engagement and promote best practices in peer review and scientific publishing. At Dryad, Maria helps grow the community of academic and research institutions, research funders, journals and publishers that invest in us to pursue the open sharing and full reuse of all research data.

![MariaGuerreiro_Dryad](https://user-images.githubusercontent.com/82666810/229810640-a0c65d5e-3024-49a1-b086-056e18cfd31a.jpg)

**Comment by ahamelers** [comment]
Hi Sarah, what is Maria's title?

**Comment by sarahklippincott** [comment]
I knew I was forgetting something :) 

Head of Partnership Development
