### ISSUE TITLE
Post-deploy tasks: sprint 88

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2449]
- [x] update RUP and AAAS journals to have multiple ISSNs again @ryscher 
	- Journal of Experimental Medicine ["0022-1007", "1540-9538"]
	- Journal of Cell Biology          ["0021-9525","1540-8140"]
	- Journal of General Physiology    ["0022-1295","1540-7748"]
	- Science ["1095-9203","0036-8075"]
	- Science Translational Medicine ["1946-6234","1946-6242"]

- [x] Update tenant for UNR affiliated users (#2445) @ahamelers

**Comment by ahamelers** [comment]
@ryscher Have you finished your task for this one?

**Comment by ryscher** [comment]
Not yet -- I was doing some tests to double-check that the updates would work as expected, and I had difficulty replicating the problem. Will dig a little deeper before I make the change.
