### ISSUE TITLE
libicu development libraries needed on servers

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2452]
I added the gem `charlock_holmes` to help correctly identify character sets of path/filenames in zip/tar.gz files.

It works correctly on my machine (MacOS) and also seems to work under the default github actions ubuntu installs.

It seems to be failing on our servers when it tries to install the gem because it needs libicu-dev installed.  It is `International Components for Unicode` for working with unicode and the gem helps detecting character sets in use.

```
***************************************************************************************
*********** icu required (brew install icu4c or apt-get install libicu-dev) ***********
***************************************************************************************
```

**Comment by ashleygould** [comment]
I've added package libicu-devel to puppet module uc3_dryad_ui.
