### ISSUE TITLE
Provide users with Sandbox admin dashboard access

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2461]
Please give the following users access to their respective admin dashboards in the Dryad sandbox environment:

**for NCSU**
Moira Downey
https://sandbox.orcid.org/0009-0007-0543-5192

Susan Ivey
https://sandbox.orcid.org/0009-0009-0652-1783

**for University of Nevada Reno**
Nathan Gerth
https://sandbox.orcid.org/0009-0005-8059-7883

**Comment by ahamelers** [comment]
This is done and live on our staging server
