### ISSUE TITLE
Redesign user dashboard results

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#2462]
**Problem description, and links to relevant helpdesk tickets:**

User/author dashboard is confusing. For example, authors are confused as to why they find their single submission in two separate places: "Submitted" and "In Progress". We receive questions about this dashboard so much that we created custom email templates for our response. It also costs time and introduces delays in the submission and publication processes. 

uthors confused by difference between statuses "Submitted" vs "In Progress". Upon notification of publication, authors sometime enter editing mode which will either put theyir submission "In Progress" or "Submitted" (versioned)

**Describe the solution you'd like:**

- Refresh author dashboard; reorganize
- Find a way to deter authors from accessing their published dataset when no edits are required
- Update user-facing dashboard, change terms and/or provide key for what all of the statuses are

[additional_notes.txt](https://github.com/CDL-Dryad/dryad-product-roadmap/files/11224553/additional_notes.txt)

**Additional context:**

From @ahamelers:
>I think it makes perfect sense for authors to only see each of their datasets listed once. We could change this page design to list all an author's datasets in order by update date, and list the status as just one of the details of the result.

**Comment by ahamelers** [comment]
@jleighherzog @bryanmgee @lauradryad @ryscher 

Here is a simple redesign idea:

<img width="1043" alt="Dashboard redesign" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/1749394/b638b2bc-00bd-4d20-866f-1ed03e3e9523">

- Each dataset only shown once
- Divided into sections based on status, and sections listed in order of attention needed. Page through full list of datasets instead of divided list.
- Specific actions available for each dataset based on current version status—peer review release made as easy as possible
- Publication status of previous versions indicated
- Clicking 'Delete' or 'Release for curation' loads a popup modal:

<img width="1262" alt="Screenshot 2023-05-15 at 12 06 24" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/1749394/9dbad23d-ef4e-4d76-a942-9c49c64b81e8">
<img width="1279" alt="Screenshot 2023-05-15 at 12 06 37" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/1749394/8a07c0b9-3196-47e6-ad66-e59bcfc2b558">

**Comment by lauradryad** [comment]
It looks great! Much easier to understand.

**Comment by jleighherzog** [comment]
Like! What will it look like for submissions in "Withdrawn" or "Embargoed" statuses?

**Comment by ahamelers** [comment]
> Like! What will it look like for submissions in "Withdrawn" or "Embargoed" statuses?

@jleighherzog I thought they'd also be under the 'Complete' heading, although maybe there should be a separate heading for Withdrawn & the status color for those should be grey—what do you think? For embargoed we could display the embargo date.

**Comment by bryanmgee** [comment]
What do we think of adding the DOI on the same line as the version and date? The number of authors who have no idea what their dataset's DOI is, is much higher than zero, and it seems some people just never read the automated emails and don't know they cant click on the dataset title to preview the landing page link. The other reason for this is sometimes we have duplicates submitted with the same name, and even though we tell them what the DOIs are, they usually can't figure out which one in their dashboard is the one to keep and the one to delete (and then end up resubmitting both)

**Comment by ryscher** [comment]
Looks great! 

The "previous version published" -- I'm assuming this will show up when any previous version was published, not just the most recent version. If you press the "Delete" for a dataset that was previously published, the confirmation dialog should let you know that the published version will still be available.

**Comment by ahamelers** [comment]
> If you press the "Delete" for a dataset that was previously published, the confirmation dialog should let you know that the published version will still be available.

I was thinking of changing the "Delete" button to "Revert" for anything with more than one version.

**Comment by ahamelers** [comment]
This is fully implemented (see the pull request). It can be loaded up on dev or stage for more extensive testing and feedback gathering.
