### ISSUE TITLE
Keywords are duplicated

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#2467]
**Bug description:**

Keywords can end up being duplicate or triplicated, and essentially all have to be removed in order to avoid duplication.

If related to the Import Metadata feature, find a way de-duplicate the auto-population of metadata (including author info, etc.)

**Steps to reproduce:**

Could be a problem linked to the Import Metadata function (Bryan said so). Making corrections to this is time consuming for curators. 

**Expected behavior:**

Only one of each Keyword appears

**Comment by ryscher** [comment]
Possibly related problem reported by Bryan: I've seen a few recently where the dataset was created and submitted recently (anytime this year) and the Research Domain field is empty, but there's no error message on the last page, and something that is a research domain is listed with the keywords; is that supposed to be how that works now?

**Comment by bryanmgee** [comment]
This has now been reported by other curators; I wonder if it's related to previously entered keywords that were entered as such but that are the same word/phrase as a Research Domain? I noticed that I am not able to find certain first- or second-order OECD domains like 'Social sciences' in the dropdown now ('Computer and information sciences' was another I had yesterday), but those phrases are entered in the keywords field along with other keywords.
