### ISSUE TITLE
Improve keyword entry

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#2468]
**Problem description, and links to relevant helpdesk tickets:**

Keyword entry entry isn't user friendly

**Describe the solution you'd like:**

Optimize Keywords section of dataset

**Additional context:**

@ahamelers tagging @bryanmgee: this needs more fleshing out, what precisely isn't user friendly?

**Comment by ahamelers** [comment]
Maybe we can close https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2331 in favor of this one.

**Comment by ahamelers** [comment]
@bryanmgee I've tried this again, and when typing in the keyword field, I can use the up and down arrow keys to move through the dropdown list that is generated, then clicking enter to select an option. I think this is standard keyboard operation for dropdown lists. How would you suggest this be modified?

**Comment by bryanmgee** [comment]
That functionality sounds fine to me but I think that the issue relates more to that dropdowns are not common for keyword entry in other contexts. Authors are more used to hitting 'Tab' or 'Enter' without having to select (match) the keyword to an existing one; this is by far the more common experience when submitting manuscripts in journal submission systems like ScholarOne and Editorial Manager in my experience, as pretty much none of them use any sort of controlled vocabulary (or it's in some janky 'add from column A to column B with arrows' thing). If we're using a controlled vocabulary to ensure that you don't end up with five different entries for 'dog', 'DOG', 'Dog', 'dog.' and 'dog ', then the selecting from the dropdown functionality to "match" becomes much less important (and people are matching to the "problem ones" with extra spaces or punctuation now anyway). People are usually just copying and pasting from the MS, so I don't think most authors are typing one word and then browsing the entire list to see what comes up.

**Comment by ahamelers** [comment]
@bryanmgee I think we are using a controlled vocabulary now with https://github.com/CDL-Dryad/dryad-app/pull/1221 and #2469—maybe @sfisher can correct me?

**Comment by bryanmgee** [comment]
Update: hitting 'Tab' does not always move you to create a new keyword if you are just freeform entering – it will kick you into the next field (Usage Notes)

**Comment by sfisher** [comment]
Just a FYI, the tab key should *not* set the keyword and move you to the keyword entry field over and over again (how it used to be a few years ago).  The accessibility evaluation indicated that this trapped users inside this field and didn't allow them to move through the document.

It is a bit wonky if you want to enter multiple keywords, but perhaps some other shortcut such as the *enter* key would be appropriate for entering a keyword that doesn't autocomplete and then entering another keyword.

**Comment by sfisher** [comment]
And it only autocompletes from the PLoS vocabulary now since there were lots of complaints of it autocompleting off insane things that other users entered.  One user enter's something like `CrAnBeRrIes` and then 10 other users autocomplete with it.

"If your friends jumped off a cliff, would you do it also?"  The answer seems to be "yes, yes they would."
