### ISSUE TITLE
Investigate ROR integration improvements

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#2474]
**Problem description, and links to relevant helpdesk tickets:**

Need to investigate various ways to improve ROR integration (unsure if it's a ROR issue or a Dryad issue). Examples include: name only matches in English even though ROR lists native language name (CrossRef is much better with "original" name); drop-down menu does not differentiate between orgs of same name but different locations/branches/encompassing org (e.g., governmental divisions) unless the country name is in the official name

**Describe the solution you'd like:**

Weren't we one of the first adopters of ROR? Maybe that will give us some leverage to ask for changes if they are on ROR's end, otherwise we need fixes on our end for both display and search functions

**Additional context:**

This is an investigation ticket to see on what end(s) a solution needs to happen.

**Comment by ryscher** [comment]
Related to #653. We store a local copy of the ROR database, which only includes the primary name of each entity. Some of these changes would require us to expand our storage to include alternate names.

**Comment by ahamelers** [comment]
The ROR database storage should be expanded to store alternate institution names and institution locations (see linked ticket)
