### ISSUE TITLE
Question about SSO

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2485]
A prospective member uses CAS (and also OpenAthens authentication) and reports that they have been unable to work with sites that "can't/won't set up the Logout CAS...and require the CAS server to send user email addresses."

Can you provide any additional info about our SSO protocol and the settings requirements that we can pass on? Any additional insight into the question above? Or reassurance that we can find a way to work with their requirements?

@marisastrong

**Comment by marisastrong** [comment]
I will investigate our metadata for Dryad - I believe we have a Logout URL but I may be confusing it with one of our other SPs.  We don't require email address, just the ePPN.  Which can be an email address, but does not have to be.

**Comment by marisastrong** [comment]
@sarahklippincott Dryad does not have a Logout functionality.  

Also I stand corrected from previous comment.

From https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/membership/README.md

Dryad requires that the following SAML attributes are released from your IdP:

- `eduPersonPrincipalName` (aka eppn)
- `mail`

**Comment by marisastrong** [comment]
If those are indeed their requirements (require Logout, do not send email),  authentication via IP addresses is an option that could be offered.

**Comment by ryscher** [comment]
@sarahklippincott I believe that the information from Marisa above is everything you need. We will close this ticket, but let us know if you need anything else.
