### ISSUE TITLE
Transfer many datasets from one author to another

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2489]
Please transfer ownership of all of the following datasets, which are all associated with a single eLife MS:

- 10.5061/dryad.jwstqjqfd
- 10.5061/dryad.prr4xgxrf
- 10.5061/dryad.8sf7m0ctd
- 10.5061/dryad.h70rxwdp9
- 10.5061/dryad.v41ns1s1q
- 10.5061/dryad.dfn2z356r
- 10.5061/dryad.9kd51c5nz

to...

Laura Nocka
0000-0003-2556-4227
lnocka@stanford.edu

The last four have never been submitted, which is part of the ongoing dialogue with one of the authors. Additionally, we should look into why the Activity Log is showing multiple authors in the Activity Log for the first three, which were submitted for curation. The first activity is the eLife API assigning to John Kuriyan but then shows a separate entry from Laura Nocka who apparently actually submitted those datasets. However, Laura does not see any datasets if she logs into our site, and her user profile does not show any either in our system.

**Comment by ahamelers** [comment]
This is done!
