### ISSUE TITLE
COUNTER validation of old/new system

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2491]
See https://github.com/CDL-Dryad/dryad-app/pull/1444 .  Richard has also looked over the differences in our logs.

We log a lot more things than the COUNTER tracker does, but we can match up the events they have to some of our most of the time.

The ones that do not match seem to be a high proportion of bots and crawlers and other things that aren't traditional users browsing.

The stats will change, but I suppose this is expected.

---
Original message below
---
Updates from Kristian.

We need to do a submission to "the hub" for July 1-15 since this is the period that we want to validate against the stats being sent with the javascript tracker.

We should turn off the auto updates to our stats until Kristian has had time to validate.

**Comment by sfisher** [comment]
I've emailed Kristian about this and we'll see what the next steps are.

**Comment by sfisher** [comment]
I'm checking in with Richard Hallett since he's the new contact since Kristian is no longer at DataCite.  Kristian and I were planning for the July 1-15th period of data for validation.  We may need to run the report again for all of July (which takes about a week) but coordinating.

**Comment by ryscher** [comment]
Scott will schedule a call to plan final steps.

**Comment by ahamelers** [comment]
@sfisher what is the status of this ticket?

**Comment by sfisher** [comment]
We can close this issue.  We are aware of differences and the logs more generous counting and bots.  I think we've all discussed it in many standups and meetings and are OK accepting the differences and moving on.
