### ISSUE TITLE
Provide sandbox admin dashboard access to member representatives

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2496]
Please provide the following users with access to University of Pennsylvania datasets in the Sandbox admin dashboard:

Lauren Phegley
https://orcid.org/0009-0006-2858-4492

Lynda Kellam
https://orcid.org/0009-0003-0236-4318

**Comment by ahamelers** [comment]
Hi @sarahklippincott , for the Dryad sandbox, the users will need sandbox ORCID IDs (https://sandbox.orcid.org/), and the users should make accounts on https://dryad-stg.cdlib.org/ with those ORCID IDs.

**Comment by sarahklippincott** [comment]
Oops! Didn't notice those weren't Sandbox ORCIDs.

Lauren Phegley's Sandbox ORCID is 0009-0007-0334-0157.

Lynda's is forthcoming.

**Comment by sarahklippincott** [comment]
Lynda Kellam's Sandbox ORCID: https://sandbox.orcid.org/0009-0004-4853-8624

**Comment by ahamelers** [comment]
Okay, these users have been made admins for the UPenn tenant on the sandbox
