### ISSUE TITLE
Next steps in FundRef to ROR

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2501]
I'm attaching the results of queries on production (these are tsv files, though they have the csv extension to upload to github).

What I found out:

- There are 19,010 unique "bespoke" funders where people entered very specific information and didn't choose a FundRef item originally.  For some of them there may not be a FundRef item for their funder, but for others they may have been sloppy and just typed something a little bit wrong and it wasn't matched to an ID or they did things like including something as specific as a department or research group that FundRef doesn't know about.
- There are 1,255 unique names with a FundRef ID that doesn't map to any ROR IDs.  Some of these probably don't all have FundRef IDs at all since a few have a URL with `none` in it rather than a number at the end.
- There are 4,061 unique rows where a FundRef ID matches up to a ROR ID through the data in the ROR database.  The same RORs and FundRef IDs are repeated sometimes since we seem to have variations on names but with the same FundRef IDs.  Most likely we are allowed people to enter alternate names.  Also a few things seem suspect and it's not clear that the name and funder IDs really match like they are supposed to (the matched names seem wildly different or wrong in a few cases).

If we are going to transition to RORs we will need to decide how we will handle the conversion.

- i suppose, items without IDs can remain items without IDs under ROR, though we may want to have someone go through and correct obvious issues or names that probably have IDs and someone just entered sloppy data.
- We will also need to decide how to handle the 1,255 unmatched items.  Do they just become uncontrolled under ROR?
- For the items that match up, the conversion is fairly easy, but there are still questions about whether we normalize the textual names the user put in to be the the official ROR name or if we allow them to stay as alternate names they currently are.
- It looks like the special work we did for NIH to force choosing directorates will still work under ROR since it seems to have separate entries for the directorates so things map cleanly.
- We will need to modify our force-prompt we put in so people don't choose the NIH top level.  It will need to work with ROR instead of the FundRef IDs.
- We would need to modify our autocomplete to work with ROR instead and may also need to include alternate names and be sure the performance is good for funders.
- Likely we will want to make a backup copy of the table and do any conversion in a way that is easy to restore if something goes wrong.
- In the past we had people outside the development team go through lists like these to correct and make bad data better or more consistent. They gave us spreadsheets with additional columns to indicate changes that we brought back in to the database for correcting issues.
- We also may need to change what we send to DataCite or at least double check it and re-send metadata updates for published datasets.

[no_ids_2023042615-13-05.csv](https://github.com/CDL-Dryad/dryad-product-roadmap/files/11337792/no_ids_2023042615-13-05.csv)
[unmatched_ids_2023042614-38-27.csv](https://github.com/CDL-Dryad/dryad-product-roadmap/files/11337794/unmatched_ids_2023042614-38-27.csv)
[matching_ids_2023042614-33-25.csv](https://github.com/CDL-Dryad/dryad-product-roadmap/files/11337793/matching_ids_2023042614-33-25.csv)

**Comment by sfisher** [comment]
I'm attaching the results of queries on production (these are tsv files, though they have the csv extension to upload to github).

What I found out:

- There are 19,010 unique "bespoke" funders where people entered very specific information and didn't choose a FundRef item originally.  For some of them there may not be a FundRef item for their funder, but for others they may have been sloppy and just typed something a little bit wrong and it wasn't matched to an ID or they did things like including something as specific as a department or research group that FundRef doesn't know about.
- There are 1,255 unique names with a FundRef ID that doesn't map to any ROR IDs.  Some of these probably don't all have FundRef IDs at all since a few have a URL with `none` in it rather than a number at the end.
- There are 4,061 unique rows where a FundRef ID matches up to a ROR ID through the data in the ROR database.  The same RORs and FundRef IDs are repeated sometimes since we seem to have variations on names but with the same FundRef IDs.  Most likely we are allowed people to enter alternate names.  Also a few things seem suspect and it's not clear that the name and funder IDs really match like they are supposed to (the matched names seem wildly different or wrong in a few cases).

If we are going to transition to RORs we will need to decide how we will handle the conversion.

- i suppose, items without IDs can remain items without IDs under ROR, though we may want to have someone go through and correct obvious issues or names that probably have IDs and someone just entered sloppy data.
- We will also need to decide how to handle the 1,255 unmatched items.  Do they just become uncontrolled under ROR?
- For the items that match up, the conversion is fairly easy, but there are still questions about whether we normalize the textual names the user put in to be the the official ROR name or if we allow them to stay as alternate names they currently are.
- It looks like the special work we did for NIH to force choosing directorates will still work under ROR since it seems to have separate entries for the directorates so things map cleanly.
- We will need to modify our force-prompt we put in so people don't choose the NIH top level.  It will need to work with ROR instead of the FundRef IDs.
- We would need to modify our autocomplete to work with ROR instead and may also need to include alternate names and be sure the performance is good for funders.
- Likely we will want to make a backup copy of the table and do any conversion in a way that is easy to restore if something goes wrong.
- In the past we had people outside the development team go through lists like these to correct and make bad data better or more consistent. They gave us spreadsheets with additional columns to indicate changes that we brought back in to the database for correcting issues.

[no_ids_2023042615-13-05.csv](https://github.com/CDL-Dryad/dryad-product-roadmap/files/11337792/no_ids_2023042615-13-05.csv)
[unmatched_ids_2023042614-38-27.csv](https://github.com/CDL-Dryad/dryad-product-roadmap/files/11337794/unmatched_ids_2023042614-38-27.csv)
[matching_ids_2023042614-33-25.csv](https://github.com/CDL-Dryad/dryad-product-roadmap/files/11337793/matching_ids_2023042614-33-25.csv)

**Comment by marisastrong** [comment]
The Funder Registry (currently maintained by Crossref/Elsevier) is ultimately going to be merged into ROR

**Comment by ryscher** [comment]
Based on the recent discussion with Maria G, we will put this on hold until ROR has a chance to reconcile more of their content with FundRef.

**Comment by ryscher** [comment]
A fun new example came into the helpdesk today:
- National Center for Sustainable Transportation (USA) -- has a ROR, but no Fundref
- National Center for Sustainable Transportation Technology (Indonesia)-- has a Fundref, but no ROR

Users are obviously confused by this, especially since we do not currently display countries in our autocomplete.

**Comment by ryscher** [comment]
A new plan has been developed in #2663, so I'm closing this ticket in favor of that one.
