### ISSUE TITLE
Dataset, correct status not displaying or being recognized

### ISSUE THREAD

**Issue by lauradryad** [CDL-Dryad/dryad-product-roadmap#2506]
**Bug description:** I (Laura) put a dataset (10.5061/dryad.q2bvq83qk) in AAR, but the author emailed us saying that they could not edit it because Laura Bowman was editing the dataset (I could not see that on my end). 
![Screenshot - submitted section](https://user-images.githubusercontent.com/124197995/235574034-94e2f982-b419-448d-86c0-982577fa625b.png)

I went back in, forced it into Curation from AAR, edited the dataset, and resubmitted it, and then when I attempted to put it back into AAR, I could only see the status options that are visible when a dataset is submitted, not in curation:
![image](https://user-images.githubusercontent.com/124197995/235573613-432f107a-29d4-496f-b3d9-b6af3c4cab59.png)

therefore, I am unable to put it back into AAR right now. 

**Steps to reproduce:**  Click the pencil for the status on this dataset (Bryan did also try and saw the same thing). There are also multiple 'version 2' in the log of this dataset (not sure if that's related or not).

**Expected behavior: ** Status options of AAR, publish, and withdraw.. not curation.

**Comment by ahamelers** [comment]
Multiple of any version will indeed cause problems, I think this is ultimately the same issue as #2400 @lauradryad . Not sure what happened here or how to prevent it in future, but it would be nice to know! Possibly a double click?

<img width="556" alt="Screenshot 2023-05-02 at 16 39 59" src="https://user-images.githubusercontent.com/1749394/235699904-5c76822d-ace2-4b74-8d48-0a9139385f0c.png">

There are various ways we can prevent multiple versions from being created, but it would help a lot if we could narrow down the cause. If you have any time, and could go on dev to *try* to make the same multiple-of-one-version issue occur, and record your steps, that would be really appreciated!

**Comment by ahamelers** [comment]
@lauradryad I've updated the versioning to reflect that there are in fact 3 versions, which should fix the bugs. I will leave you (and the author) to decide which should be active, and if one should be deleted.
