### ISSUE TITLE
De-list Kyoto University

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2508]
**Problem description, and links to relevant helpdesk tickets:**
Kyoto University has informed us (with regret) that it does not have the funds to maintain its Dryad membership, even discounted to $3,000/ann. (they should be at $13,000).

Jen has approved de-listing them as a Dryad member.

**Describe the solution you'd like:**

- Deprecate integration
- Remove IIT from list of members on the website
- Configure system for billing authors

**Additional context:**
Please tag me when this is complete so I can update Salesforce.
@ryscher @ahamelers @sdiggs

**Comment by ryscher** [comment]
@mark02139 This change will go live tonight.
