### ISSUE TITLE
SUNY consortium additional members

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2517]
**Problem description, and links to relevant helpdesk tickets:**
SUNY consortium has amended their agreement to add 2 additional insitutions:

- SUNY Oneonta
- SUNY Fredonia

**Describe the solution you'd like:**
These will need to be added to the quarterly volume-based invoicing process.

**Additional context:**
@ryscher @ahamelers @sdiggs

**Comment by ahamelers** [comment]
ROR IDs were added to the tenant config in https://github.com/CDL-Dryad/dryad-app/pull/1177

**Comment by ahamelers** [comment]
@mark02139 Will these be added to the table at https://docs.google.com/spreadsheets/d/1aCvJfvuHvrCuIcayIkGW7TFYRoyEQIMoWQtKlfr9v0g/edit#gid=0 ?

**Comment by mark02139** [comment]
@ahamelers , I don't know whose spreadsheet that is (maybe Donna's?).
I've updated Salesforce.

**Comment by ahamelers** [comment]
We will close this and handle invoicing in #2418  and #2524
