### ISSUE TITLE
Reword PPR selection explanation text

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#2519]
Previous text:

> By choosing this option, your dataset will be private during your related article's peer review period. You will have access to a private dataset download URL to be shared with collaborators or the journal. Your dataset will not enter curation or be published. Because we may not have the status of your related article, the default for this period is six months. Please [email us](mailto:help@datadryad.org) or uncheck this box at any point if your dataset is ready to enter curation.

Current text:

> By choosing this option, your dataset will be private during your related article's peer review period, or for 6 months in cases where we do not know your related article's status. You will have access to a private dataset download URL to be shared with collaborators or the journal. Your dataset will not enter curation or be published. After submission, please [email us](mailto:help@datadryad.org) or edit this choice when your dataset is ready to enter curation.

Jess suggests:

> By choosing this option, your dataset will be kept private during your related article's peer review process. Your submission will not be evaluated by curators or published until you choose to release your submission from this status by deselecting this checkbox. While your article is in peer review, your Dryad data files can be shared with collaborators and/or the journal using a private URL that will be provided upon successful submission. 

_Originally posted by @jleighherzog in https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2509#issuecomment-1540462651_

**Comment by ahamelers** [comment]
(But also... would it be crazy if we _did_ automatically move submissions out of PPR after 6 months?)

**Comment by jleighherzog** [comment]
Ha ha! I like the idea. Because these PPR datasets can sit in that status forever despite reminders. We'd run into the issue of us potentially publishing datasets that are linked to rejected manuscripts AND authors emailing the Helpdesk to request the data be removed because they didn't release it from PPR themselves. There's a solution in here somewhere and it's worth a group discussion.

**Comment by jleighherzog** [comment]
I like your updated text. Thank you!
