### ISSUE TITLE
Add Tenant: Macalester College

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2521]
**Tenant name:** 
Macalester College

**Invoicing**
Macalester College is on the quarterly, volume based invoicing plan.

**Logo location:** 

**Contacts to receive submission notices:** 

**RORs that are considered part of the tenant (including medical centers, alternate campuses, etc.)**
https://ror.org/04fceqm38

**Shibboleth info, if not in [InCommon](https://incommon.org/community-organizations/):**

Tasks:
- [x] add config to `config/tenants`
- [x] add logo to `app/assets/images/tenants`
- [ ] deploy and test on stage (institution should log in to verify working as expected)
- [ ] update `tenant_id` for users in the database who have emails with the institutional domain name

@ryscher @ahamelers

**Comment by sarahklippincott** [comment]
Logo files:
![mac-sec-horizontal-logo-spot blue (2)](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/82666810/3db7ed77-4e43-4560-9047-7213fb9e5f6c)
![mac-primary-logo-spot blue](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/82666810/39e05e7d-d6fb-4597-a294-bd04968d661f)

**Comment by sfisher** [comment]
@marisastrong and/or @ashleygould 

Do you know what we need to do with shibboleth to get it working for them?  I couldn't find them in the shibinfo discovery.

![Image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/105433/51372ce1-2269-4776-a481-ade063fdd564)

I added the other things to the config besides the shibboleth info.

![Image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/105433/a37d330b-dd6a-4c1e-bfe3-f1d2c52c4d52)

Their single sign on seems to be through an outside provider from what I can tell.  https://macalester.galaxydigital.com/user/login/, I believe.

Steve had forwarded some information to me a few weeks ago:

```
I am responsible for managing SSO authentication for Macalester College. Louann Terveer has requested I work with you to configure SSO for our institution. We use a hosted service for our SSO which leverages WSO2 for our IdP. Can you please share your metadata file so I can configure things on our end? Here is the URL to access our metadata information:
https://macadmsys.macalester.edu/banner_support/macalester_IDP_QL8_prod.xml
Also, can you tell me which attributes we should be releasing in the SAML assertion?

Thanks,
Tim
Tim Friemann
```

Let me know if I can help out, though IDK how we've done the special shibboleth configs in the past.
