### ISSUE TITLE
Tiered and deferred accounts review

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2524]
**Problem description, and links to relevant helpdesk tickets:**
We need to be sure Business Ops and Dev are aligned on existing tiered and deferred quarterly invoicing.
Please review this list and ensure that we are producing the quarterly reports necessary to issue invoices.

**Describe the solution you'd like:**
List of current tiered and deferred:

Publishers and societies

- AAAS - tiered
- Ecological Society of America - tiered
- eLife - tiered
- Rockefeller University Press - tiered
- The Paleontological Society - tiered
- Wiley - tiered
- AGU - deferred @ $105
- AMIA - deferred @ $115
- German National Library of Medicine - deferred @ $115

Institutions

- Macalester College - tiered
- SUNY Consortium - tiered

**Additional context:**
@ryscher @ahamelers @sdiggs

**Comment by ryscher** [comment]
Related to #2418

**Comment by mark02139** [comment]
@ryscher , I've just audited publisher agreements as part of the budgeting process. Here are a couple of additional accounts to add to the list:

- American Genetic Association - tiered
- PLOS (Pathogens) - tiered
- Institute of Botany, Chinese Academy of Sciences - tiered
- Oxford University Press - deferred

**Comment by mark02139** [comment]
@ryscher , attached is a CSV listing the journals associated with tiered and deferred quarterly invoicing (except Wiley, which I'll update once we have a signed agreement with them).
[Journal list for quarterly invoicing.csv](https://github.com/CDL-Dryad/dryad-product-roadmap/files/11542185/Journal.list.for.quarterly.invoicing.csv)

**Comment by mark02139** [comment]
@ryscher , Wiley just signed their agreement (!!!). Following is the current list of journals. Note that additional societies/journals will be added going forward, as Wiley recruits more societies to join the agreement.

**Proprietary journals**							
Diversity and Distribution							
Ecology and Evolution							
Environmental DNA							
Evolutionary Applications							
Global Ecology and Biogeography							
Journal of Biogeograph							
Molecular Ecology							
Molecular Ecology Resources							
Global Change Biology							
GCB Letters							
Ecology Letters							
Ethology							
							
**Society Partners							
British Ecological Society:**							
Journal of Ecology							
Journal of Animal Ecology							
Journal of Applied Ecology							
Methods in Ecology and Evolution							
Functional Ecology							
Ecological Solutions and Evidence							
People and Nature							
							
**Nordic Society Oikos:**							
Oikos							
Ecography							
Journal of Avian Biology							
Wildlife Biology							
Nordic Journal of Botany							
							
**European Society for Evolutionary Biology**							
Journal of Evolutionary Biology							
							
**Association for Tropical Biology and Conservation**							
Biotropica

**Comment by ryscher** [comment]
These are all verified, though the institutions need a separate report. Created ticket #2610 for that task.
