### ISSUE TITLE
Refresh Queue Size column in Curation Stats report

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2528]
Bryan has been manually tracking the queue size over time and confirmed that the numbers aren't a match with what's reported in the "Queue Size" column of the [Curation Stats](https://datadryad.org/stash/curation_stats) page. 

For example, the curation team was working through the datasets submitted on May 13th yesterday and looked ahead at how many were submitted on the 14th (Saturday) – even though there were 14 unpublished submissions in "Submitted" status with a Submitted date of May 14th, the Curation Stats page counts only 8 new to "Submitted" on this day. 

Bryan also tracked counts for "Datasets available to be curated" in [this GDoc](https://docs.google.com/spreadsheets/d/1Fy8jqYMHBaO2KqjkgtDak-uRPleLYHx4MhxSFGFAQxU/edit#gid=181198187) -- it's our understanding that this number should update in real-time, and it's consistently out of sync with manually counting Submitted + Curation

![Newly submitted datasets comparison](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/f64b0482-6a3a-4735-ad47-19a9edc5a5ac)

Note from Bryan: for context on how I generated the above plot, I pulled the spreadsheet of every dataset in the system, then binned it by month to count how many datasets were listed with a 'Submitted' date in each month. I then did the same based on the Curation Stats page, downloading that report and binning by month. The discrepancy is quite high in some months (20–30%) but oddly aligns nearly perfectly in other months (e.g., the spike of last year is May).

**Comment by ahamelers** [comment]
@bryanmgee @jleighherzog It looks like if a submission moves into submitted or curated AND past/out of that status on the same day, it will not be added to the queue size for the day. Basically the system is checking the "final" status for each submission for the day to calculate this. Is this desired, or not?

**Comment by bryanmgee** [comment]
That sounds right to me; for the one that is not tracked in real-time and reported in the table on the Curation Stats page, what we want is the total number of datasets that are available for curation (everything in Submitted or Curation) at the moment when the system calculates the stat (I assume this is between 11:59 PM–12:01 AM UTC). I don't immediately see any reason why we would want the "max" as either a substitute or separate stat, but maybe see if Jess has any thoughts

**Comment by ryscher** [comment]
Currently, the stats are calculated at noon Pacific Time, since they run on UC servers. But they use UTC cutoff times. So a dataset is "in the queue" if it has a status of `submitted` or `curation` at the end of the UTC day.

**Comment by ahamelers** [comment]
@bryanmgee Is there something identifiably wrong with the Queue size column currently? That's what the title of this issue indicates, but the description doesn't have much about Queue size and covers a lot of other stuff we've worked on or are working on in other tickets.

**Comment by bryanmgee** [comment]
This one requires more exploration to see if it's accurate or not (I'm pretty sure it's overcounting somewhere); @ryscher and I talked about this yesterday, and what I'll be doing for at least the next week is tracking the number of datasets in Submitted and Curation status (what should be considered Queue Size) at midnight UTC (5 PM my time) – then we'll be able to figure out whether it's accurate and if not, to at least guess at what may be going wrong. We may need to wait until this surge in versioned datasets dies down though, as it is blowing the numbers through the roof right now

**Comment by ryscher** [comment]
Fixes seem to be working.
