### ISSUE TITLE
Remove file from published dataset: 10.5061/dryad.msbcc2g3d

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2529]
The author contacted us with concerns regarding the species data for this published dataset: 

Title: _Trait-based and multi-scale approach provides insight on responses of freshwater mussels to environmental heterogeneity
DOI: **10.5061/dryad.msbcc2g3d**_

Version 3 was published on 4/13, 2023. Please remove this file from Dryad, Zenodo, etc.: 
**Mitchell_et_al_San_Saba_River_field_data**

The most recent version uploaded on 5/12 contains an updated data file.

**Comment by ryscher** [comment]
Removed visibility of the offending version in Dryad. The Zenodo instance was already updated due to Dryad having a more recent file.
