### ISSUE TITLE
Bug: Metadata edits and saves from an admin (Curator) to activity log.

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#253]
From Elizabeth:
When metadata is edited, there is an indication in the activity log that something happened, but the change descriptions that we are asked to record before pressing ‘submit’ are not saved, Changes to metadata that were made by the curator (Admin) are recorded in the activity log as changes made by the author, Any change to metadata made by the curator/admin, including when I clicked on the pencil icon to see if a change was saved, but did not edit anything, causes the status of the item to revert to ‘In Progress’ and then ‘Submitted’

In more detail:

The activity log indicates that these changes were made by the submitter (Test Author) rather than the curator
The description of edits I was asked to include before clicking “submit” is not recorded in the activity log

Test whether recorded information will be different if status is first changed to “Curation”
Click on pencil and change status of item to “Curation”
Click on pencil icon to edit metadata
Add journal name and keywords (these changes did not register/save earlier)
I add a description of what I changed and click “submit”
I’m led to the “My Datasets” page
To get back to where I was, I have to click “admin” and search again for the submission I was working on

Back at admin dashboard. The submission again shows as ‘In progress’, and after waiting a time, and then refreshing, submission is back to being “Submitted”
I change status again to “Curation” 
Activity log indicates again that Test Author made changes (not Curator), but the description of those changes has not been recorded.

Return submission to author (change status to ‘author action required’)
This step and note are recorded in the activity log
As author, I click ‘update’, make changes (delete one file) and click ‘submit’ to resubmit. I am not asked to enter a description of what I changed
This step is recorded in the activity log, but without any note on what changed
As curator, change status to ‘curation’ and then to ‘embargoed’
These steps and notes are recorded in the activity log

**Comment by briri** [comment]
Need to update logic so that status always go back to 'Curation' after curator makes changes to the dataset.

Update logic to store curator's note as the curation activity note.
