### ISSUE TITLE
Shibboleth future plannning

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2534]
https://docs.google.com/document/d/1sM7aTzfBSrr5cVqxFY36w_k0y7CDclszg_b7HESN-SY/edit?usp=sharing

**Comment by marisastrong** [comment]
https://shibboleth.net/mailman/listinfo/announce - provides information on security vulnerabilities in Shib software

**Comment by ryscher** [comment]
Closing this as most planning is done; actual actions tracked through #2636
