### ISSUE TITLE
CoreTrustSeal planning

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2538]

**Comment by ahamelers** [comment]
Some notes and important links/info:

- [CoreTrustSeal Requirements](https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fdoi.org%2f10.5281%2fzenodo.7051011&c=E,1,leU-1yRFeajq80pXToiEFh-CLXkMDu-TF5mtwFd9tbI8MH0LcYDvRW-VevfEkyiPTqzYIKI9kwKVI9yR5zxBFS6a6o1GlyfPAarahplF28XdxQe9P06z&typo=1)
- [Additional requirements information](https://www.coretrustseal.org/why-certification/requirements/) (Webinars etc.)
- [Full list of certificates with complete requirement response PDFs](https://amt.coretrustseal.org/certificates)
- [CoreTrustSeal Application Management Tool](https://amt.coretrustseal.org/)

We need to make an account in the Application Management Tool and use that tool to create our submission. There is a 1000 EUR administrative fee for the certification review process.

**Comment by ahamelers** [comment]
Created tickets #2615 and #2614 about creating an application tool account and beginning to gather requirements responses (probably in a google doc)
