### ISSUE TITLE
Urgent: Email links on contact support page not working properly

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2540]
**Bug description:**
The links at https://datadryad.org/stash/contact do not seem to be connecting to the email addresses listed in the text. According to a user, one of the email addresses returns messages as undeliverable because the mailbox is undergoing maintainance).

The help@datadryad.org email address in the line "Please contact help@datadryad.org for assistance with dataset submissions." links to dev@null. And the general inquiry email hello@datadryad.org also seems to link to dev@null.

**Comment by ryscher** [comment]
The email obfuscator is not working correctly on this page.... we should also check other places emails appear on the site.
