### ISSUE TITLE
Urgent: Member support request -- login not working

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2541]
**Bug description:**
Report from a researcher at the University of Rochester : 

> Once I log in to Dryad with my ORCID and then select "University of Rochester" in the box appearing under "Your institution may be a member* of Dryad," I get an error message."

I've requested further detail on the error message they're receiving, but wanted to pass this along in the meantime in case it's possible to reproduce the error based on this limited info.

**Comment by bryanmgee** [comment]
FYI, the author got back to me yesterday and said: 

"I also checked at our university end and it seems that part of the issue may have been with the single-sign-on configuration at the university end. I expect to get someone to help with that tomorrow (Monday May 22)."

So this may end up being an irreproducible issue on our end

**Comment by marisastrong** [comment]
Please confirm the tenant configuration for  the entityID is for University of Rochester .  It should be:

https://uidp-prod.its.rochester.edu/idp/shibboleth

Looking at the tenants file, it needs updating

https://github.com/CDL-Dryad/dryad-app/blob/main/config/tenants/rochester.yml

**Comment by sfisher** [comment]
Thanks for checking on this, Marisa.

I've created a pull request for the change (to deploy tomorrow) and also edited the rochester config manually on production and restarted puma.  This should allow the person who was having a problem to get in today.

**Comment by ryscher** [comment]
@sarahklippincott @bryanmgee This is now fixed.
