### ISSUE TITLE
Automate reminders for AAR'd datasets

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2542]
Currently, curators follow a protocol to send manual reminders to authors for submissions that they've returned to the authors' Dryad dashboard for edits. When the curation queue is high or climbing, the Chasing task is the first to be dissolved in favor of keeping on top of new/revised/versioned submissions received. Automating this process will save curators time and allow consistency in our follow-up. 

Below is the schedule and text for all 3 reminders. 
_Note: for the 3rd/final reminder, we're proposing that the submission is withdrawn with the option to reinstate the dataset at any time_
- **1st reminder**: 2 weeks after AAR status is set
- **2nd reminder**: 2 weeks after 1st reminder is sent (4-week mark)
- **3rd/final reminder** (withdraw): 2 weeks after 2nd reminder is sent (6-week mark)

Things to keep in mind: 

- Ideal to record the chase activity in the Dryad Activity Log of the data submission (Reminder 1, Reminder 2, Final reminder)
- If withdrawn on the Dryad Admin site, the status of the related case(s) should update in Salesforce (_Note: we realize it won't close the case_)

**1st reminder**: 2 weeks after the AAR date is first set
Subject line: Action required: Dryad data submission (DOI: xxxxx)
> Dear {{{Case.SuppliedName}}},
> 
> A couple of weeks ago, we requested modifications to your Dryad data submission. As a reminder, these changes must be addressed before we can publish your dataset:
> 
> Title: "{{{Case.Dataset_Title__c}}}"
> DOI: {{{Case.DOI__c}}}
> 
> Our previous email correspondence contains specific details on the changes required. Please let us know if you have any questions or no longer wish to proceed with the publication of the dataset. We will send you another reminder in about 2 weeks. 
> 
>We hope to hear from you shortly.
> 
> The Dryad Team
> help@datadryad.org

**2nd reminder**: 4 weeks after initial AAR date (2 weeks after 1st reminder is sent)
Subject line: Reminder: Action required for Dryad data submission (DOI: xxxxx)
> Dear {{{Case.SuppliedName}}},
> 
> As a reminder, we are unable to proceed with the publication of your data submission to Dryad titled, "{{{Case.Dataset_Title__c}}}” because the changes requested in our previous correspondence have not been addressed.
> 
> If we do not receive a reply or if no action is taken within 2 weeks, we will withdraw your dataset. Please note, once withdrawn, your submission can be reinstated at any time. All previously provided metadata and data files will be retained allowing you to easily resume the curation and publication processes. 
> 
> We hope to hear from you soon.
> 
> The Dryad Team
> help@datadryad.org

**Final reminder**: 6 weeks after AAR date (2 weeks after 2nd reminder is sent) - dataset is withdrawn and notification is sent
Subject lines: Your Dryad data submission has been withdrawn (DOI: xxxxx)
> Dear {{{Case.SuppliedName}}},
> 
> Because we have not received a response to our initial request and subsequent reminders regarding edits to your Dryad dataset, we have withdrawn your data submission to Dryad titled, "{{{Case.Dataset_Title__c}}}."
> 
> You are welcome to reinstate your submission at any time. All previously provided metadata and data files will be retained as well as the assigned DOI. To restore your submission and resume the curation and publication processes, contact help@datadryad.org.
> 
> We hope you will consider Dryad to host your future data submissions.
> 
> The Dryad Team
> help@datadryad.org

**Comment by sfisher** [comment]
I worked through some of the craziness of trying to do this.  It looks like there are about 4596 items that would be notified on production based on what I could figure.

Some random selection to spot check and make sure it seems right:

```
identifier: "10.5061/dryad.5sj684q",
   identifier: "10.5061/dryad.g13c7dj",
   identifier: "10.5061/dryad.f81f3fp",
   identifier: "10.5061/dryad.78kf81b",
   identifier: "10.5061/dryad.56s3g32",
   identifier: "10.5061/dryad.g6k73pm",
   identifier: "10.5061/dryad.d507t",
   identifier: "10.5061/dryad.26961",
   identifier: "10.5061/dryad.562rp12",
   identifier: "10.5061/dryad.9pd2nc6",
   identifier: "10.5061/dryad.tm02t2n",
   identifier: "10.5061/dryad.hk523v1",
   identifier: "10.5061/dryad.905qftthz",
   identifier: "10.5061/dryad.44j0zpcdj",
   identifier: "10.5061/dryad.c866t1g70",
   identifier: "10.5061/dryad.f1vhhmgxm",
   identifier: "10.5061/dryad.34tmpg4m3",
   identifier: "10.5061/dryad.cjsxksn6n",
   identifier: "10.5061/dryad.1ns1rn8w9",
   identifier: "10.5061/dryad.ncjsxksxw",
   identifier: "10.5061/dryad.4b8gthtf6",
   identifier: "10.5061/dryad.0cfxpnw5b",
   identifier: "10.5061/dryad.d2547d832",
   identifier: "10.5061/dryad.xksn02vkg",
   identifier: "10.5061/dryad.59zw3r2b8",
   identifier: "10.5061/dryad.sf7m0cgbr",
   identifier: "10.5061/dryad.dbrv15f4k",
   identifier: "10.5061/dryad.vmcvdnczg",
   identifier: "10.5061/dryad.s7h44j1cm",
   identifier: "10.5061/dryad.fj6q5741h",
```

**Comment by sfisher** [comment]
@ryscher I double checked the list of Action Required items I pulled out (which I believe are somewhat representative of all ~4500).  It looks to me like about 1/3 are from pre-2019 since they have shorter DOI identifiers.

@jleighherzog I had some concerns about sending out 4,596 chasing emails for the full history of Dryad since it seems unlikely to me that some of the older ones will do anything and probably have long since moved on and it might generate a lot of unnecessary helpdesk traffic.  Is it reasonable to just chasing things started in the last year or something like that?

**Comment by ryscher** [comment]
Note: Although this work was done, we commented out the cron entry that runs it, because curators were not ready to handle extra workload that it might cause.
