### ISSUE TITLE
Investigate timing and frequency of PPR reminders

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2543]
Please investigate the timing and frequency of PPR reminders sent. Here are two examples of reminders sent earlier than expected: 

- https://datadryad.org/stash/ds_admin/activity_log/105652
- https://datadryad.org/stash/ds_admin/activity_log/97176 
- https://datadryad.org/stash/ds_admin/activity_log/108904
- https://datadryad.org/stash/ds_admin/activity_log/101346
- https://datadryad.org/stash/ds_admin/activity_log/110218
- https://datadryad.org/stash/ds_admin/activity_log/110064
- https://datadryad.org/stash/ds_admin/activity_log/103840
- https://datadryad.org/stash/ds_admin/activity_log/109716
- https://datadryad.org/stash/ds_admin/activity_log/110492
- https://datadryad.org/stash/ds_admin/activity_log/108429
- https://datadryad.org/stash/ds_admin/activity_log/109720
- https://datadryad.org/stash/ds_admin/activity_log/110547
- https://datadryad.org/stash/ds_admin/activity_log/108001
- https://datadryad.org/stash/ds_admin/activity_log/107083
- https://datadryad.org/stash/ds_admin/activity_log/112046
- https://datadryad.org/stash/ds_admin/activity_log/111815

_Note: Ryan & Jess reviewed these during a meeting 5/22_ (only the first two, Bryan keeps adding new ones as he finds them)

**Comment by ahamelers** [comment]
So, it looks from these logs like this reminder is sent immediately when the job runs after the peer review status is set, and then once each month thereafter. I'm assuming it is just the first part of this which is a problem—that the first message is being sent too early, but the monthly frequency after the first message is correct?

**Comment by ahamelers** [comment]
It looks like this is a 'default to PPR' journal issue, as all the examples are from default to PPR journals and that route is missing the crucial end date setting step, although it looks like Editorial Manager submissions may also have an issue here. I'll make the PPR end date setting happen universally when the submission is moved to peer-review status, regardless of origin—up until now it had been set when the user selected the PPR setting, which wasn't quite correct for the date calculation anyway.

**Comment by ahamelers** [comment]
@jleighherzog Just to note, with the change I am proposing, if the author edits and resubmits anything in PPR, keeping it in PPR, the peer_review_end_date will be reset each time they resubmit (to be 6 months from that date). Is this correct/desired?

**Comment by jleighherzog** [comment]
@ahamelers : To be clear, the **peer_review_end_date** will be set and reset whenever a submission is placed in PPR status. This means that, at 6 months, the first PPR reminder will be sent and additional reminders will be sent on a monthly basis thereafter. The **peer_review_end_date** will signal the initial reminder. 

The **peer_review_end_date** will be reset each time a submission is returned to PPR status, moving that 6-month mark futher into the future.(I think this is okay, this is how it works now).  

For integrated titles that have PPR enabled automatically upon submission, these submissions will have the same end dates and reminders attached, however, they will auto-release from PPR status when we receive a confirmation of acceptance from the journal title. 

Do I have that right? If so, sounds fine. I've run this past Laura too!

**Comment by ahamelers** [comment]
Yes, that's correct! 

> The peer_review_end_date will be reset each time a submission is returned to PPR status, moving that 6-month mark futher into the future.(I think this is okay, this is how it works now).

This may not actually be the case currently, because the setting of the date does seem to be tied to the form action of the selection of peer review by the user—so if the user resubmits without editing the peer review status in the form, I believe the mark is not moved. If a curator sets something to peer review status, though, it is moved! This difference seems like a bug to me, and I'd rather it be tied very firmly to the movement to peer review status regardless of who initiates it (as proposed), or to some other consistent action or state change—or, alternatively, it could be set once when it is first moved into peer_review, and then never moved into the future after that point. Either option would be an improvement!
