### ISSUE TITLE
No radio button selected in "Choose when to publish"

### ISSUE THREAD

**Issue by lauradryad** [CDL-Dryad/dryad-product-roadmap#2545]
**Bug description:** I went into a dataset for curation and saw that neither option under "choose when to publish" was selected for the dataset 10.5061/dryad.m0cfxpp8c
![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/124197995/2dd9edfa-548d-4937-a720-af7fbc9abdb1)

I emailed the author to ensure they were ready to publish and they were able to resubmit the dataset again without selecting either option. 

**Steps to reproduce:** I've only seen it in this particular dataset.

**Expected behavior:** System would not allow submission until one radio button is selected.

**Comment by bryanmgee** [comment]
Somewhat amazingly, I actually managed to run into [another example](https://datadryad.org/stash/ds_admin?q=%2210.7272%2FQ62Z13RT%22&sort=relevance&commit=Search&tenant=&editor_id=&curation_status=&publication_name=&sponsor_org=&utf8=%E2%9C%93) of this bug.

**Comment by lauradryad** [comment]
Found a [new example](https://datadryad.org/stash/dataset/doi:10.5061/dryad.jh9w0vtgw) of this bug today.
