### ISSUE TITLE
Transfer dataset ownership (back: 10.5061/dryad.4xgxd25fh)

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2563]
The authors want this dataset (which already had dataset ownership transferred once #2527) to be transferred back to:

**Title:** Bat passive acoustic monitoring (PAM) data analyzed in PAMGuard workflows based on four different detection approaches and a deep learning species classifier
**DOI:** 10.5061/dryad.4xgxd25fh

Jamie Macaulay
0000-0003-1309-4889
jdjm@st-andrews.ac.uk

...so they can upload new files...

**Comment by ryscher** [comment]
Updated ownership to Jamie Macaulay, user id 80820.
