### ISSUE TITLE
Revert to previously published version: 10.5061/dryad.5dv41ns9t

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2567]
Please remove the files from the most recent, unpublished version -- maintaining the files from version 5 first published on May 11 (GB in size). 

<img width="894" alt="Screenshot 2023-06-02 at 8 16 51 PM" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/e87600c6-b824-4667-8e45-973964f9f64f">

**Comment by sfisher** [comment]
Version 5 was the published version with the large set of files.  Merritt was able to remove version 6 & 7 which came after, so we did the same in Dryad.  The dataset should now be at the same state it was in when it was published (with subsequent activity removed).
