### ISSUE TITLE
Edit FAQ and submission page to reflect 3 mandatory keywords

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2573]
Please update the [Dryad FAQ](https://datadryad.org/stash/faq) to reflect that we now _require_ 3 keywords upon submission. 

See section: **What should I include in my metadata?**

Remove this text from the "We recommend" list and add it to the "We require:" list: 
> Keyword(s): Descriptive words that may help others discover your dataset. We recommend that you determine whether your discipline has an existing controlled vocabulary from which to choose your keywords. Please enter as many keywords as applicable.

Keyword description should appear last in the "We require" list, following "Research domain"

Additionally, might be useful to update the submission page where keywords are entered to indicate the minimum number of keywords required ("minimum 3").

**Comment by sfisher** [comment]
I believe we already have the last item, though we can change the text if you don't think the current message works ("at least three keywords").  It only displays on new datasets created after yesterday.

![Screenshot 2023-06-07 at 9 21 25 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/105433/77b1e982-ba1a-487d-a409-66b192ab62e3)

**Comment by jleighherzog** [comment]
@sfisher : Apologies, I wasn't specific. I meant to include a note about the minimum requirement here (where the keywords are entered). But, I think it's fine as-is because we're likely to get MORE than the minimum requirement if we don't mention a minimum. 
 
<img width="1000" alt="Screenshot 2023-06-07 at 3 49 27 PM" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/5df97678-7f02-455d-a5da-6e7e4cff8570">

**Comment by ahamelers** [comment]
Stealing this to do with some other static page changes 😄
