### ISSUE TITLE
Review code for dryad-stripe-dashboard

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2574]
[https://github.com/datadryad/dryad-stripe-dashboard](https://github.com/datadryad/dryad-stripe-dashboard)

**Comment by ahamelers** [comment]
I am able to load and the dashboard app. It seems to be working fine, and looking at the code I am confident we can manage, and modify the app in future if necessary. We need to go over with Mark what his expectations are about the app functionality and verify that it has all the capabilities he requires.

<img width="49%" alt="Screenshot 2023-06-27 at 17 15 56" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/1749394/716bb854-9fac-453f-9a5e-e2cabb487a0e">
<img width="49%" alt="Screenshot 2023-06-27 at 17 16 18" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/1749394/a5655266-df45-4638-aacb-f96184434e17">

The project is using a test API key associated with our test Stripe data. This key is exposed in the github repository: https://github.com/datadryad/dryad-stripe-dashboard/blob/d1ff54beb227baf313c2d61a8578d5d900f0aa52/src/api/routes/StripeWebhook.js#L8

Moving forward, we should:

1. modify the project to keep secret project keys secret
2. remove the test key from the public git history
3. delete the test key from Stripe
