### ISSUE TITLE
Edit Help page to include update to file types checked by Frictionless

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2575]
With the recent update to the Frictionless, the tool now checks for additional file types: TSV, JSON, and XML files. 

Please update the "Tabular data check" section on [this page](https://datadryad.org/stash/submission_process). I've updated the paragraph below to include these additional file types: 

For all data files uploaded to Dryad in CSV, XLS, XLSX, TSV, JSON, and XML formats (5MB or less), a report will be automatically generated by our tabular data checker, integration with the [Frictionless framework](https://frictionlessdata.io/). This integration allows for automated data validation, focused on the format and structure of tabular data files, prior to our curation services.

**Comment by ahamelers** [comment]
The JSON and XML checks are much, much less thorough. Suggest:

> For all data files uploaded to Dryad in CSV, XLS, XLSX, and TSV formats (5MB or less), a report will be automatically generated by our tabular data checker, an integration with the <a href="https://frictionlessdata.io/">Frictionless framework</a>. This integration allows for automated data validation, focused on the format and structure of tabular data files, prior to our curation services. JSON and XML files are also checked for basic file validity.
