### ISSUE TITLE
When API kicks something out of PPR, authors still see PPR radio buttons

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2577]
(Reported by curators, so I'm not 100% certain that this is the sequence of events to reproduce)
1. Create a submission in PPR, associated with a journal/manuscript
2. Send an API call or email to mimic the journal stating that the article is accepted
3. The system will move the dataset into `submitted` status
4. The user will still be able to version the dataset, and have the option to incorrectly select PPR status for the new version

**Comment by bryanmgee** [comment]
Here are two examples of when a dataset was created after the MS was accepted at Ecology & Evolution: [link](https://datadryad.org/stash/ds_admin/activity_log/110363) and [link](https://datadryad.org/stash/ds_admin/activity_log/110330?) (this could be more of an issue around how it displays in the Activity Log, obviously at this point, I don't actually know if the author could still see the radio buttons).

Hunting for some examples of when it sits in PPR for a bit and is then kicked out...

**Comment by ahamelers** [comment]
Based on what is in the activity logs and my testing, I think what is happening is not that the radio buttons are appearing after the accepted manuscript association, but that the initial PPR selection in the database is still copied to additional versions, so we're seeing that repeated notification in the logs. I've added toggling the PPR selection to false at the first notification, to prevent it being copied and repeating when new versions are created.
