### ISSUE TITLE
Include free-text field for fee waiver options

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2580]
In the Dryad admin site, when attempting to apply a fee waiver, it would be useful to include a free-text field for all reasons available in the drop-down menu. This will eliminate the need to maintain detailed, separate tracking. 

![Screenshot 2023-06-09 at 8 57 44 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/dea3ac27-0665-49e8-a141-209433fe945a)

![Screenshot 2023-06-09 at 8 57 52 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/a3c971e9-0db6-4e65-abb4-7ea8811c8301)

From Bryan (7/17): It would be also be ideal to add a field (free-form or select options that includes an 'Other') for career stage; we definitely want to capture what % are ECRs, for example. If we wanted to have a drop-down list, I would recommend at least the following:

- Undergraduate student
- Graduate student
- Postdoc
- Professor
- Government
- Non-academic non-profit (e.g., museum)
- Other

**Comment by ryscher** [comment]
Moving this to "blocked", as it requires more discussion about what we want to track in the database.

**Comment by ryscher** [comment]
We will not do this in the Dryad database directly. Instead, it will be part of the new fee-waiver approval form.
