### ISSUE TITLE
Update HSI PDF links

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2582]
**PRIORITY**: Before end-June
GREI task

A new version of the **HSI PDF** is ready for posting [this is the new version](https://docs.google.com/document/d/1bBwFn8kHbsUtj9PmyeieEdyyi7fcOj0bkr_B5_-zIKo/edit#). 

**HELP**: On page 2-3, I'm unable to figure out a way to carry over the heading of the table (see below) so that it _also_ appears on page 3 (where it's continued). I was successful in doing so for the table on pages 3-4. Can you help with the formatting? 

![Screenshot 2023-06-09 at 10 24 59 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/4cc36a7f-5ff2-424f-9d14-ed4de474be13)

1) On the [best practices page](https://datadryad.org/stash/best_practices), replace the link that appears in this paragraph: 

> Human subjects data must be properly anonymized and prepared under applicable legal and ethical guidelines (see [tips for human subjects data](https://datadryad.org/docs/HumanSubjectsData.pdf)).

2) On the [FAQ page](https://datadryad.org/stash/faq), update these paragraphs to include the new link: 

> Dryad does not accept submissions that contain personally identifiable human subject information. Human subjects data must be properly anonymized and prepared under applicable legal and ethical guidelines. Please see [additional guidance on human subjects data](https://datadryad.org/docs/HumanSubjectsData.pdf).

AND

> No Personal Health Information or sensitive data can be included. See [tips for human subjects data](https://datadryad.org/docs/HumanSubjectsData.pdf) and [tips for sensitive species data](https://datadryad.org/docs/EndangeredSpeciesData.pdf).

**Comment by ahamelers** [comment]
The repeating header just would not work for this table, so I faked it.
