### ISSUE TITLE
Test Zenodo-on-Invenio

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2584]
From Alex:

As we might have mentioned in the past in conversations and [on the Zenodo blog](https://blog.zenodo.org/2022/12/07/2022-12-07-zenodo-on-inveniordm/), we are progressing steadily towards in September moving Zenodo on top of [InvenioRDM](https://inveniordm.docs.cern.ch/), the next generation of the platform, which includes many new features that were in our pipeline for quite some time.

We’ve recently imported to our [demo instance](https://zenodo-rdm.web.cern.ch/) a snapshot of the Zenodo live database from early February, including user accounts, communities, records, and draft uploads.

We have also ported the existing Zenodo REST API endpoints to this new instance, with the purpose of keeping full backwards compatibility for active REST API clients like yours. That means that there are no changes necessary on your client code in order to run your existing workflows. To verify this we took a sample from requests from the live Zenodo environment, and “replayed” it on the new platform successfully.

We now need some help from you to verify that this backwards compatibility layer works as expected. Basically, what we’re asking is that you point one of your test environments to "[zenodo-rdm.web.cern.ch](http://zenodo-rdm.web.cern.ch/)" instead of “[sandbox.zenodo.org](http://sandbox.zenodo.org/)", and send requests to the REST API as you would normally do as part of your workflows. 

The REST API access tokens you’re already using to authenticate in the Zenodo Sandbox and production systems have also been migrated to the new system, but in case you want to create new ones you can follow these steps:

Get access to your migrated account by resetting your password at https://zenodo-rdm.web.cern.ch/lost-password/
Once logged-in, you can create a new token at https://zenodo-rdm.web.cern.ch/account/settings/applications/tokens/new/ (select all the available scopes for the token).

There are still some known issues and missing functionality that we are currently working on, that shouldn’t be affecting your regular workflows:

UI display of metadata fields on record landing pages. You might see some fields appearing at different locations of the page, or completely missing.
REST API responses
Field names in files-related endpoints response payloads might have slightly different naming; all exposed information though is still the same, i.e. file sizes, checksums, etc.
Some error responses might not fully match the old payload format and status codes.
The RAT tokens functionality, used for generating read-only links for unpublished draft files, hasn’t been ported yet
Editing files of existing non-Zenodo DOI records, is also not possible yet

We expect to have the RAT tokens, and non-Zenodo files editing features ported by the end of June.

If you come across any errors, issues, or anything out of the normal, please send us a brief description of the issue along with any application logs with timestamps, request/response payloads, etc. The more information you can include the better.

**Comment by sfisher** [comment]
I've done initial testing after getting updated login information and a lot of the API seems to be working.

However, file uploads are now failing with 404s, 504s 502s and other things.

I know there were two different file APIs in the old system and Alex advised us to use the direct bucket upload system (or something like that).

I've emailed to find out if we need to rewrite to a different API call or what the next steps are to get file uploads working.
