### ISSUE TITLE
Dataset submitted without journal metadata when "a manuscript in progress" was selected

### ISSUE THREAD

**Issue by lauradryad** [CDL-Dryad/dryad-product-roadmap#2585]
**Bug description:**

When curating this dataset ([https://datadryad.org/stash/dataset/doi:10.7280/D1FH75](https://datadryad.org/stash/dataset/doi:10.7280/D1FH75)), I noted that no journal metadata was input for the manuscript though it is marked as a required field. The author was able to submit the dataset without error. When I made the updates to the metadata, I also received no error message about the lack of journal metadata. I did not change it or click any of the radio buttons while I was editing the dataset. The dataset is still in AAR as of the time of this ticket (I have asked the author to input journal metadata). 

What I saw
![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/124197995/a681d310-10fd-47cd-a77a-097ca5bdec0d)

**Steps to reproduce:**
This is the second time the curators have seen this issue recently, but we did not document the first one. This one was started June 6 and submitted June 7. 

**Expected behavior:**
When the dataset is set to manuscript in progress, the author should not be able to submit the dataset without any journal metadata (not sure if this changed when we changed the default designation to manuscript in progress).

**Comment by ahamelers** [comment]
After discussion, this is not exactly a bug, because the journal and manuscript aren't really required (from when "other" was the default selection), however this is confusing since these fields are in fact marked "required". As we know, the whole submission form needs revamping.

**Comment by ryscher** [comment]
I created #2601 to capture some of the things we discussed in standup - for this ticket we can simply enforce that the fields are required when one of the first two options are selected. We can do a more complete redesign for #2601 in the future.

**Comment by ahamelers** [comment]
Currently the fields _marked_ required are:

- Journal name and Manuscript number, for manuscript
- DOI, for published article

Should journal name be required for published articles as well?

**Comment by ryscher** [comment]
Yes, but if the DOI is entered first, does it make sense to fill the journal name automatically? Maybe move the DOI field to the left side?

**Comment by ahamelers** [comment]
We are not already automatically filling the journal via the DOI, so I don't think adding that functionality should be in the scope of this ticket (maybe for #2601 we can add that). And it looks like the journal name is required before the 'Import article metadata' button can be clicked, so I think the asterisk missing may just have been an oversight! But we can also look at changing that functionality in the future as well (enabling the import with just the DOI)

**Comment by ryscher** [comment]
Yes, it can definitely be a different ticket!
