### ISSUE TITLE
Add Tenant: MIT

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2588]
**Tenant name:** Massachusetts Institute of Technology

**Logo location:** https://libraries.mit.edu/news/libraries-logo/

**Contacts to receive submission notices:** N/A

**RORs that are considered part of the tenant (including medical centers, alternate campuses, etc.)** https://ror.org/042nb2s44

**Shibboleth info, if not in [InCommon](https://incommon.org/community-organizations/):** SAML -  InCommon Federated metadata - R&S category

Tasks:
- [x] add config to `config/tenants`
- [x] add logo to `app/assets/images/tenants`
- [ ] deploy and test on stage (institution should log in to verify working as expected)
- [ ] update `tenant_id` for users in the database who have emails with the institutional domain name

@marisastrong @sfisher @ryscher If there's any way we can include MIT in today's release I'd be really grateful! There was some miscommunication on our end and they've been waiting on launch for a few weeks. Any questions can go to Adam Shire - Shirea [at] mit [dot] edu.

**Comment by ahamelers** [comment]
Hi @sarahklippincott , should all the child organization RORs (listed on https://ror.org/042nb2s44) be included?

**Comment by sarahklippincott** [comment]
@ahamelers Yes, please.
