### ISSUE TITLE
PRIORITY: AGU moving to volume-based quarterly invoicing

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2589]
**Name to appear on membership page:** 
American Geophysical Union (already a member)

**Payment plan:**
AGU is currently on the 'deferred' payment plan. Under a new membership agreement, they are moving to the tiered pricing model.  This will become effective as close to July 1 as possible.

**Journals included:** 
AGU Advances
Earth and Space Science
Earth's Future
Geochemistry, Geophysics, Geosystems
GeoHealth
Geophysical Research Letters
Global Biogeochemical Cycles
Journal of Advances in Modeling Earth Systems
Journal of Geophysical Research: Atmospheres
Journal of Geophysical Research: Biogeosciences
Journal of Geophysical Research: Earth Surface
Journal of Geophysical Research: Oceans
Journal of Geophysical Research: Planets
Journal of Geophysical Research: Solid Earth
Journal of Geophysical Research: Space Physics
Paleoceanography and Paleoclimatology
Radio Science
Reviews of Geophysics
Space Weather
Space Weather Quarterly
Tectonics
Water Resources Research

**Email contacts to receive submission notices: (note whether they receive all notices, or different lists for different journals)** 
Assume the same as previously. The new contact (following Brooks Hanson's retirement) is Matthew Giampoala, mgiampoala@agu.org

Development tasks:
- [x] update payment settings to 'tiered' for each journal
- [x] ensure that each journal has AGU set as the sponsor_id
- [x] update journal notification settings to new contact

**Comment by ahamelers** [comment]
Done!
