### ISSUE TITLE
Homepage UI changes

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#259]
- Finalize links in How it Works
“Dryad member” - link to new member list page
“Upload” - link to submit
“curators” - link to /help > Curation (need anchor)
“cite” - link to /help > Publication and Citation (need anchor)
- Why use Dryad? - Add period after “Any format” 
- Help menu:
Fix typo “Fequently”
Change to “Data Publishing Charges” (not processing)
- Need new pages for:
Terms of Service (goes at footer)
- Add photos for staff and governance
https://datadryad.org/pages/organization#governance
https://datadryad.org/pages/ourTeam

**Comment by elizabethdryad** [comment]
Request another new page for "Best practices" (link under the Help menu). Also still need a plan for this content:
https://datadryad.org/pages/journalLookup
