### ISSUE TITLE
Add SCOSS supporters to collaborations

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2591]
We need to recognize SCOSS supporters on the website. I suggest we add a section at https://datadryad.org/stash/about#collaborations. Open to thoughts about formatting, language, and best place to add this info!

> Dryad is grateful to the following consortia and institutions for their support of Dryad through [SCOSS](https://scoss.org/). Their contributions enable us to grow our outreach and promotion efforts to bring new members into our community; increase community engagement with current members and users; and stay at the forefront of best practice for data-sharing and building best practice for data reuse. 
> 
> - Council of Australian University Libraries (CAUL)
>   - Auckland University
>   - University of New South Wales
>   - University of Melbourne
> - Canadian Research Knowledge Network (CRKN)
>   - Mount Royal University
>   - Toronto Metropolitan University
>   - University of Alberta
>   - University of the Fraser Valley
>   - University of Saskatchewan
>   - University of Waterloo
> - SwissUniversities
>   - ETH Zürich
>   - Lib4RI
>   - Université de Lausanne
> - Independent contributions
>   - Iowa State University

**Comment by sarahklippincott** [comment]
Makes sense to me @ahamelers

**Comment by ahamelers** [comment]
@sarahklippincott mock up:

<img width="875" alt="Screenshot 2023-06-21 at 17 07 47" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/1749394/30313abd-15de-4b06-ae7b-64a87af7ca70">
