### ISSUE TITLE
Check configuration of AAAS journal titles

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2597]
**Priority**: Medium
**Impact**: Ensure submissions are placed in PPR automatically and also auto-releasing from PPR status upon notification of acceptance from journal

Please check the setup for all AAAS titles to ensure 1) they are placed in auto-PPR; 2) that they will auto-release from PPR status upon manuscript acceptance. 

Bryan has reported that he has not seen evidence of a dataset auto-releasing from PPR - only manual update of the status by a curator. I performed a search by the sponsor (AAAS) for submissions in 'Submitted' status and a spot check confirmed that no auto-PPR was activated: https://datadryad.org/stash/ds_admin?tenant=&editor_id=&curation_status=submitted&publication_name=&sponsor_org=74

> - Science 
> - Science Advances  
> - Science Immunology 
> - Science Robotics
> - Science Signaling
> - Science Translational Medicine

**Comment by ahamelers** [comment]
We can't find any problems with the setup or with our API. Ryan will triple check, and contact AAAS to see if they are having any issues.
