### ISSUE TITLE
Fix metadata import from journal module

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#260]
When users enter a journal and manuscript ID, a POST call is made to the journal module, which is then supposed to make another POST/PUT to insert a new resource into Dryad. This is currently broken.

Rather than just repair the broken calls, it would be better to send a GET call to the journal module, retrieve the appropriate manuscript JSON, and perform the mapping to fill out the resource. 

- [x] (Ryan) add the GET query to the journal module 
- [x] (Scott) in new system, call the GET query and map the results into the resource

-----

This is how to test manually:

Run `bundle exec rake old_dryad_api:manuscript` to get a random manuscript to test.  The manuscript numbers are changing all the time, I'll put some in here for convenience, but they might expire and the rake task should give current ones.

Some to try:

journal: Evolutionary Applications
manuscript id: EVA-2017-299

journal: The Condor: Ornithological Applications
manuscript id: CONDOR-18-188

journal: Journal of Avian Biology
manuscript id: JAV-01536

journal: Natural Sciences Education
manuscript id: NSE-2018-12-0021-ORA

Then go in to the metadata entry page and choose manuscript option and start typing journal and select it from autocomplete.  Then put in manuscript ID and submit the form to autofill.

Includes both unit and feature tests.

**Comment by ryscher** [comment]
The GET query looks like this (but must include a valid API key):
```http://api.datadryad.org/api/v1/organizations/<journal-issn>/manuscripts/<manuscript-id>```

Valid manuscript IDs change regularly as manuscripts are processed. For a full list of manuscripts that are valid for a given journal, use:
```http://api.datadryad.org/api/v1/organizations/<journal-issn>/manuscripts```

**Comment by sfisher** [comment]
Here's more to try since a bunch of the ones in there have gone out of date since last week.

journal: Soil Science Society of America Journal
manuscript id: S-2018-10-0370-OR

journal: Journal of Ecology
manuscript id: JEcol-2017-0864

journal: Journal of Systematics and Evolution
manuscript id: JSE-2018-03-026

journal: Journal of Heredity
manuscript id: JOH-2018-069

journal: People and Nature
manuscript id: PAN-18-10-081
