### ISSUE TITLE
<Enter> no longer selects autocomplete from list of keywords

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2602]
I believe this is a side effect of the recent changes for \<Enter\> to put in a keyword from the keyword form.

How to duplicate the problem:

1. Go into the keyword entry field.
2. Type a partial autocomplete like "mouse" and use the arrows on the keyboard to select "Mouse hepatitis virus" and press \<enter\> to fill.
3. The item saved to the database is "mouse" rather than the "Mouse hepatitis virus" which was selected and <Enter> should autocomplete when it's selected.  (Clicking with the mouse still seems to work.)

Expected behavior:

If nothing is selected from the autocomplete list then the \<Enter\> key fills and saves the value in the box; if an item is selected from the autocomplete list by keyboard then \<Enter\> would fill that instead rather than the partial value being typed into the text box.

**Comment by ahamelers** [comment]
I could have sworn I tested this!
