### ISSUE TITLE
Autofill metadata from DOI of a published article

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#261]
We need to retrieve metadata from CrossRef and fill the basic metadata the they have into our dataset after people successfully put in a valid DOI.

These are some test DOIs that worked:

10.1098/rsif.2017.0030
10.1126/sciadv.1602232
10.1021/acs.jctc.6b00449
10.1578/am.37.4.2011.486
10.5194/acp-16-15247-2016
10.1073/pnas.1711233114
10.1073/pnas.1718211115
10.1002/ecs2.1645
10.1371/journal.pone.0143878
10.3732/ajb.1600326
10.1021/acs.macromol.7b00672
10.1016/j.compag.2017.09.011

You can put in fake or invalid or blank DOIs to test.

1. Create new dataset.
2. Click "a published article"
3. Add the DOI or mess with it in the form.
4. Click "Import Article Metadata"

It should import the metadata which is often very incomplete in CrossRef.  Many do not have more than a title and authors.  Some have an affiliation.  Very few have an abstract.  Some have funder information.  I don't think any had any of the other stuff.

---

The current Dryad system retrieves XML from CrossRef using a call like this:

https://api.crossref.org/works/doi:10.1086/695495/transform/application/vnd.crossref.unixref+xml

**Comment by sfisher** [comment]
Note to self, I believe all these dois are good for testing metadata retrieval from our current Dash system.

10.1098/rsif.2017.0030
10.1126/sciadv.1602232
10.1021/acs.jctc.6b00449
10.1578/am.37.4.2011.486
10.5194/acp-16-15247-2016
10.1073/pnas.1711233114
10.6078/d1k08k
10.6078/d1f66n
10.1073/pnas.1718211115
10.6078/d18h32
10.1002/ecs2.1645
10.1371/journal.pone.0143878
10.6084/m9.figshare.1293447
10.6078/d1g010
10.3732/ajb.1600326
10.6078/d16k5w
10.1021/acs.macromol.7b00672
10.1016/j.compag.2017.09.011
10.5281/zenodo.1195605
10.1073/pnas.1904242116
