### ISSUE TITLE
Set up auto-PPR upon submission for Proceedings of Royal Society B

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2613]
**Priority**: Medium (1-2 weeks)
**Impact:** It would be great to have this implemented soon because many Proc B datasets are published while the related manuscript is rejected

Please configure automatic PPR for all datasets linked to the journal **Proceedings of Royal Society B**. 0962-8452

All new submissions should automatically be placed in PPR status when Proceedings of Royal Society B is selected.

Upon receipt of an acceptance notification from the journal, datasets should be auto-released to the queue for curation (in "Submitted" status). Rejected manuscripts should be auto-withdrawn. 

Let me know if you have any questions!

**Comment by sfisher** [comment]
@ryscher I'm not clear if something else needs to happen here.  I set the auto-PPR flag for the journal.

Isn't the acceptance notification to the Dryad gmail account automatically releasing items when an acceptance comes in.  Is there something else to change?

**Comment by jleighherzog** [comment]
@ryscher : There was no auto-PPR set up for this journal, authors were selecting the option manually upon submission. The release may have been working for those submissions in PPR status with a manuscript accepted for publication on the journal side. Thank you!
