### ISSUE TITLE
Investigate CoreTrustSeal Application Management Tool

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#2615]
We need to make an account in the Application Management Tool and use that tool to create our application submission for CoreTrustSeal certification (#2614). There is (eventually) a 1000 EUR administrative fee for the certification review process.

CoreTrustSeal important links/info:

- [CoreTrustSeal Requirements](https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fdoi.org%2f10.5281%2fzenodo.7051011&c=E,1,leU-1yRFeajq80pXToiEFh-CLXkMDu-TF5mtwFd9tbI8MH0LcYDvRW-VevfEkyiPTqzYIKI9kwKVI9yR5zxBFS6a6o1GlyfPAarahplF28XdxQe9P06z&typo=1)
- [Additional requirements information](https://www.coretrustseal.org/why-certification/requirements/) (Webinars etc.)
- [Full list of certified repositories with complete requirement response PDFs](https://amt.coretrustseal.org/certificates)
- [CoreTrustSeal Application Management Tool](https://amt.coretrustseal.org/)

**Comment by ahamelers** [comment]
The main question here @ryscher is: what email address should I use for creating this account? Is my datadryad.org email fine, or would it be preferable to use one of the mailing list group emails?

**Comment by ryscher** [comment]
As the coordinator, your address is fine, but if you would like a more generic one, feel free to use `admin@datadryad.org`, which you are already a member of.

**Comment by ahamelers** [comment]
Created account and an application.
