### ISSUE TITLE
Update Salesforce to track volunteers for user testing

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2619]
Second attempt at the work described in #2393.

**Comment by ahamelers** [comment]
Waiting on completed SOW and timeline.

**Comment by ahamelers** [comment]
We will investigate using Mailchimp (as Sarah and Jess are doing) instead of editing Salesforce

**Comment by ahamelers** [comment]
Imported contacts into mailchimp. Need to discuss possibility of automation. Without paying for mailchimp automation tools specifically for this group of contacts is limited
