### ISSUE TITLE
Change journal name autocomplete to use Dryad Journal Module, not CrossRef

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#262]
Test it out on Dryad module but otherwise make this a smarter search

Also update wherever the crossref API is used to get journal names.

**Comment by ryscher** [comment]
This may no longer be a priority. We have reduced the list of journals that are not available through the CrossRef API. The curators report that some of these journals will not continue their Dryad subscriptions, so they won't need matching for payment purposes.

**Comment by elizabethdryad** [comment]
Addressing the functionality of the journal drop-down should definitely still be a priority. Many submissions are coming in without a journal name (when they should have one), and users/curators are reporting that the drop-down is sometimes very slow or doesn't work at all.

**Comment by elizabethdryad** [comment]
I think another part of the issue is that on the first page of submission, the default selection is "other or not applicable," meaning the option to add a journal and MS number is not visible -- so people might just be blowing past that. Recommend that the default be changed to "a manuscript in progress"

**Comment by ryscher** [comment]
- test with Dryad journal module -- this will return fewer results, but they will be the results we want
- prioritize matches at the start of string instead of alphabetizing results
- make it clear when a search is actually happening vs waiting for more to be typed
