### ISSUE TITLE
Recruit some data scientists to be testers

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2620]
This should happen naturally as part of our recruitment efforts, but if it does not, we will need to do some targeted recruiting.

**Comment by ryscher** [comment]
Initial step is to write a blog explicitly calling for data scientists.

**Comment by ahamelers** [comment]
Blog post draft: https://blog.datadryad.org/wp-admin/post.php?post=5679&action=edit

**Comment by ryscher** [comment]
Marking as blocked while we wait for the blog to be released.
