### ISSUE TITLE
Document process to copy search indexes

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2629]
Document process to obtain a snapshot of search indexes from the solr server and copy them to a new server.

**Comment by sfisher** [comment]
We have always just regenerated the SOLR indices from the database if they are blank or have issues.  I believe this is the `rsolr:reindex` task, though it hasn't been run in a while. It runs quickly in less than an hour or two as I recall. I believe indexes exist in a specific solr directory, though I haven't ever tried copying them from one server to another.
