### ISSUE TITLE
Configure Shibboleth onto new Dryad servers

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2636]
- [x] Crete new Shibboleth servers
- [x] Set up to work with new InCommon account
- [x] Migrate new dev/stage to use new system
- [x] Migrate old dev/stage to use new system
- [ ] Migrate new prod to use new system
- [ ] Migrate old prod to use new system

**Comment by ryscher** [comment]
Waiting for InCommon account

**Comment by ryscher** [comment]
Documentation in https://docs.google.com/document/d/1sM7aTzfBSrr5cVqxFY36w_k0y7CDclszg_b7HESN-SY/edit

**Comment by DragosIorgulescu** [comment]
Left to do:
- set this up on the rest of the servers (staging & prod)
- update the docs https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/external_services/amazon_aws_ec2_setup.md#set-up-shibboleth-service-provider
