### ISSUE TITLE
BUG: Unable to load 'Review & Submit' tab

### ISSUE THREAD

**Issue by briri** [CDL-Dryad/dryad-product-roadmap#264]
Brian ran across this where a dataset isn't UC and it continues on and does a ROR request to see if the first author's institution matches a fee-waiver country.  It seems like in many instances the results.parsed_response['items'] is blank inside the 'identifier#submitter_country' method.

I've patched this up to get by for now, but there is more that probably would be good to do in here.

The things I'd like better if they were improved about this method:

- [ ] Putting the ROR URL outside the code in the app_config.yml file so it's easier to change if it changes or they add a sandbox or other stuff.
- [ ] Are there other common Network errors to catch?  Some people say to catch StandardError, but that seems a little broad.
- [ ] Caching maybe?  could set @submitter_country and return at the first if already set in the object instance.
- [ ] Rubocop hates the length and complexity, so if there is a nice way to improve it that is all good.
- [ ] It's would be good to add some rspec tests for additional cases where it would've been failing in the past because of blanks or unexpected values.

The main things I changed were that I'm checking for blank? (a rails method that is either nil or empty for an object), checking the HTTP status response code and also rescuing some exceptions.

---

Original description below.

Unable to load the 'Review & Submit' tab after creating a new dataset. The following error appears in the log:

<img width="985" alt="Screen Shot 2019-03-28 at 9 14 37 AM" src="https://user-images.githubusercontent.com/1204467/55174136-214a9600-513a-11e9-9068-e2e7435cb6e0.png">

**Comment by ryscher** [comment]
This has been cleaned up, and our ROR implementation has evolved greatly since then.
