### ISSUE TITLE
Publisher tiered quarterly reports

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2642]
**Missing clients and needing revision**
The 2023-Q2 tiered report needs some adjustment

Missing: **The Paleontological Society**
Journal of Paleontology
Paleobiology

Missing: **Rockefeller University Press**
Journal of Cell Biology (JCB)
Journal of Experimental Medicine (JEM)
Journal of General Physiology (JGP)

Needing adjustment: **Ecological Society of America**
ONLY Ecological Monographs (not other ESA journals)

@ryscher @ahamelers

**Comment by mark02139** [comment]
Individual DPC billing.

**Comment by ahamelers** [comment]
Thanks @mark02139 ! Do the journals for The Paleontological Society and Rockefeller University Press need any other changes, or should their payment contact information, etc. remain as is?

**Comment by ahamelers** [comment]
I've adjusted the payment_plan_type for all journals as indicated; Ryan and I will run the report again on Monday (so I can be trained in how it's done)

**Comment by mark02139** [comment]
@ahamelers , not quite sure I understand your question. We maintain contact and billing info in Salesforce--but I don't know what info info of that sort you also maintain.

**Comment by ryscher** [comment]
Ahh, I see. I forgot that column existed. That information was used for invoicing in the far distant past, but Salesforce has the correct information now. We should probably just clear out that column now, to reduce confusion.

**Comment by ryscher** [comment]
@mark02139 Reports are updated for the above changes.
