### ISSUE TITLE
SUNY Consortium affiliated institutions

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2645]
**Tenant name:** 
State University of New York (SUNY)

SUNY acts as a sponsor for a number of institutions (not all) in the SUNY system, meaning we need to produce a teired invoice for the SUNY Consortium for datasets associated with the institutions it sponsors. Note that only the SUNY Consortium is a Dryad member; the institutions it is sponsoring are not.

List of institutions in the agreement: 

- Buffalo State College
- New York State College of Ceramics at Alfred University
- Purchase College
- State University of New York at New Paltz
- State University of New York at Oswego
- State University of New York at Potsdam
- State University of New York College at Cortland
- State University of New York College of Optometry
- State University of New York Maritime College
- SUNY Brockport
- SUNY College at Old Westbury
- SUNY College of Environment Science and Forestry
- SUNY Downstate Health Sciences University
- SUNY Fredonia
- SUNY Geneseo
- SUNY Oneonta
- SUNY Plattsburgh
- SUNY Polytechnic Institute
- SUNY Upstate Medical University

@ryscher

**Comment by ryscher** [comment]
Thanks, Mark. I'll close this ticket, but it will serve as a reference for the ticket where the actual work is happening, #2610
