### ISSUE TITLE
Improve logging for API

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2646]
- [ ] API requests should go to an API-specific log file, so it is easier for us to diagnose problems.
- [ ] Requests that are made by an authenticated API user should also log the name of the API account.
- [ ] We don't need to keep these logs for long. They should roll and be purged on the same schedule as the regular log files.

**Comment by ahamelers** [comment]
Duplicate of #2420?

**Comment by ryscher** [comment]
Why yes, it is a duplicate. Closing.
