### ISSUE TITLE
EZID transition planning documentation

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2652]
We need some extra clarity around the EZID --> DataCite DOI transition, so we need a short beginning document for people to evaluate and agree on.

I can write that up and then create tickets after some discussion and agreement.  Since this involves multiple stakeholders (Dryad, EZID, DataCite) we need buy in on what makes sense and what is technically feasible for all groups and we need a plan to respond to in order to get better feedback from everyone.

**Comment by ryscher** [comment]
I believe this is finished.
