### ISSUE TITLE
Review settings/permissions for UCSB Curator dashboard view

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2653]
Renata reports that she is no longer able to view filters by 'curator' and 'institution' on the Dryad Admin Dashboard. 

Please investigate. 

@rcurty : Feel free to update this ticket with more information, screen capture, etc.

**Comment by ahamelers** [comment]
@jleighherzog any update on this ticket?

**Comment by jleighherzog** [comment]
@ahamelers : From Renata: 

"The curator list makes it easier to select all associated deposits, than just sorting within a long list of curators, since not only the 3 of us curate UCSB deposits; also having that option makes it easier to combine filters to narrow down results."

Here's a screen capture of Renata's current view. 

![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/01d95793-7f9c-42a0-a9c9-231e5e72dcec)

**Comment by ahamelers** [comment]
Thanks @jleighherzog ! I'm sure I can add back the curator list. Am I correct that the tenant_curators are already limited to their institution, and do not need Institution dropdown access?

**Comment by jleighherzog** [comment]
@ahamelers : I've asked @rcurty to join this ticket to explain exactly what's needed. Here's a screen capture of my view with the filters for "Institution" and "Curator". The thing is, I'm not sure why the filters disappeared from their view but, we need to be careful about updating the 'tenant_curator' role because it will impact other users, obviously. 


![Screenshot 2023-08-07 at 5 24 51 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/4ed158b3-1de8-46cc-a30c-b91e7c95ced8)

**Comment by jleighherzog** [comment]
Another question: For UCSB-affiliated submissions the DOI will either contain 10.5061 or 10.25349 when minted — how or in what circumstances are these assigned by our system? Renata can see both in her tenant view. We're just curious, without the institutional filter, whether these are all UCSB-related. It seems, from a spot check, at least one author is affiliated with UCSB (but may not be the corresponding/submitting author).

**Comment by ahamelers** [comment]
> @ahamelers : I've asked @rcurty to join this ticket to explain exactly what's needed. Here's a screen capture of my view with the filters for "Institution" and "Curator" which is what UCSB curators used to see. The thing is, I'm not sure why the filters disappeared from their view but, we need to be careful about updating the 'tenant_curator' role because it will impact other users, obviously.
> 

@jleighherzog It changed because of the change for the institution filter, which was changed to appear and show a list depending on the number of institutions the user has access to, rather than based on the user role. We did not notice at the time that the curator list was within the same conditional block; I've edited this so the conditional check for the curator list is separate (you can see this in the pull request attached to this ticket).

**Comment by ahamelers** [comment]
> Another question: For UCSB-affiliated submissions the DOI will either contain 10.5061 or 10.25349 when minted — how or in what circumstances are these assigned by our system? Renata can see both in her tenant view. We're just curious, without the institutional filter, whether these are all UCSB-related. It seems, from a spot check, at least one author is affiliated with UCSB (but may not be the corresponding/submitting author).

During our partnership UC system dataset DOIs were not minted through DataCite, but through a special process dictated by the UC system, through EZID, and the DOIs have been under the control of the CDL. Each tenant had a DOI prefix assigned, and I assume any variations in those DOIs were asked for by their administrators/CDL. As part of the transition we are turning off the EZID process, the existing UC-prefixed DOIs are being transferred to Dryad's control through DataCite, and I believe UC system submissions will receive normal Dryad DOIs in future. 

- https://github.com/CDL-Dryad/dryad-product-roadmap/issues?q=is%3Aissue+ezid+label%3Aezid
- https://docs.google.com/document/d/1mNBtFmmb6-Ss_lh5zhFc-lcj_1s1_62ZJwq6uQ1yUCg/edit
