### ISSUE TITLE
Activities for Dryad to become an InCommon Member

### ISSUE THREAD

**Issue by marisastrong** [CDL-Dryad/dryad-product-roadmap#2657]
In order for Dryad organization to establish the application as an SP within InCommon they must become a member.

[Planning for InCommon and SSO](https://docs.google.com/document/d/1VD4Qswx3J79hqCFAfjtevn9932cZiUOM8NT0d22ac48/edit#)

To Join InCommon as a sponsored partner https://incommon.org/join-incommon/sponsored-partners/
- [x] UCOP/CDL to provide sponsorship letter
- [x] Dryad (@ryscher ) documentation of annual revenue to determine which [fee level](https://incommon.org/join-incommon/fees/) Dryad fits into.
- [x] Dryad to send in information to InCommon

**Comment by marisastrong** [comment]
UCOP will need a letter sent from the UCOP CISO (UCOP's InCommon Executive) to InCommon.  I have drafted a letter for her.

**Comment by marisastrong** [comment]
Letter sent from UCOP to InCommon for sponsorship.  @ryscher was cc'ed on the letter.

**Comment by ryscher** [comment]
Financial information sent to InCommon. Mark will initiate the participation agreement. 

Next tasks are tracked as part of #2622.
