### ISSUE TITLE
Invoice needed for published dataset (DOI: 10.5061/dryad.d7wm37q3v)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2659]
The author of this dataset didn't receive an invoice and DPC is not covered by either his institution or the journal. 
Is it possible to raise an invoice? 

Data from: A novel laboratory method to simulate climatic stress with successful application to experiments with medically relevant ticks) 
DOI: 10.5061/dryad.d7wm37q3v
Published: September 2, 2022

**Comment by ryscher** [comment]
Generated new invoice BBF7F0D0-0002
