### ISSUE TITLE
FundRef to ROR transition planning documentation

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2663]
We need to plan how to transition Fundref to ROR. There are some pieces of this out there, but we need a draft plan so that people can give feedback and buy in rather than speculating and we can get concrete tasks that work for everyone out of it.

**Comment by sfisher** [comment]
See https://docs.google.com/document/d/1svrl8I1yU6ZS1p45pupWSWSVe63m796XjrAEq0hRp_4/edit?usp=sharing for a tentative plan.  I'll circulate to Maria and Steve, also.
