### ISSUE TITLE
Website page -- How to request a feature

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2665]
https://docs.google.com/document/d/1jmhb_ZAX7AOH8bVDUHqG4qlXugxSM4JGGh-2jY8Lju0/edit?usp=sharing

**Comment by ahamelers** [comment]
I think we should redo the contact page to contain this and other content https://docs.google.com/document/d/19aCkbCaIz_CIgA4yodK_MybTkTqWBMoVFy2YdENWNh0/edit#heading=h.whnhqlstiegy
