### ISSUE TITLE
ACSESS member not listed on the website

### ISSUE THREAD

**Issue by mariaguerreiro** [CDL-Dryad/dryad-product-roadmap#2671]
**Bug description:**
The Alliance of Crop, Soil and Environmental Science Societies (ACSESS) has signed a membership agreement at the end of last year but they're not listed as members of the website. 

**Steps to reproduce:**
The societies are not listed here: https://datadryad.org/stash/join_us#members

**Expected behavior:**
They should be displayed under "Publishing organizations"

**Comment by ahamelers** [comment]
Hi @mariaguerreiro, is it just this member who is not listed or are other societies affected?

**Comment by ahamelers** [comment]
For the future, 

- is there any location where all publisher members are listed, that we can check on a regular basis, or
- will someone make tickets when publisher members are added or removed, for this list to be updated?

**Comment by mariaguerreiro** [comment]
@ahamelers From what I can tell, is only this one. 

We will add new tickets as new publishers and societies need to be added. Thank you!
