### ISSUE TITLE
PRIORITY: Place dataset in PPR status (DOI: 10.5061/dryad.z08kprrjp)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2672]
Short story: Told the author we would keep the submission in PPR status, and published it instead. 

Please return to PPR status ASAP. 

Thanks.

**Comment by sfisher** [comment]
Thanks @ryscher  .  It looks like you started on this.

**Comment by ryscher** [comment]
Ok, this is now back in PPR.
