### ISSUE TITLE
Update notifications for ACSESS

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2678]
Please update notification preferences for member representatives of American Society of Agronomy Crop Science of America Soil Science Society of America Certified Crop Adviser Agronomic Science Foundation (ACSESS).

**Email contacts to **remove** from receiving all submission and publication notices:

ipopkewitz@sciencesocieties.org, lvandriel@sciencesocieties.org, amorrison@sciencesocieties.org, cbishop@sciencesocieties.org

**Email contacts to receive all submission and publication notices:  

Mary Ellen Archer

[marcher@sciencesocieties.org](mailto:marcher@sciencesocieties.org)

ORCiD: https://orcid.org/0009-0000-9415-5465

Kelsey Stanczak

[kstanczak@sciencesocieties.org](mailto:kstanczak@sciencesocieties.org)

ORCid: https://orcid.org/0009-0007-2122-7000

Becky Funck

[rfunck@sciencesocieties.org](mailto:rfunck@sciencesocieties.org)

ORCid: https://orcid.org/0000-0003-2600-5929

**Comment by ryscher** [comment]
Contacts updated.
