### ISSUE TITLE
Increase space in VE (virtual environment)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2680]
**Priority**: Medium (within 1-2 weeks)
**Impact**: No interruption to curation work. Without space or limited space, large files cannot be downloaded to the VE

Please add additional space to the VE in anticipation of additional full-time curators that will be hired and onboarded in early September. 

FYI: For the second time this week, space was limited (~100GB remaining). 

Thanks!

**Comment by ahamelers** [comment]
I increased the space of the C drive to 2TB, which is its current maximum (Actually I increased it past that in AWS and then found out that was its maximum, so I need to wait 6 hours to modify it again 🙄 ). I'm going to need more information from @ryscher on whether I should make other volumes, clear the drive out and change how it is partitioned so the volume size can be increased, or whatever else I should do.

**Comment by ryscher** [comment]
I think the 2TB max is for the OS drive? I created the D drive with the intention of expanding it to a larger size, though obviously this was never tested...

**Comment by ahamelers** [comment]
Hmm, unlike the C drive, the D drive is nowhere near full—I'm seeing 1.51 TB free there. Are we sure the correct drive is being used by curators?

**Comment by ryscher** [comment]
Usage varies greatly. They are constantly downloading new content and deleting old content on both drives.

**Comment by ahamelers** [comment]
Okay, I'll try adding space to the D drive!
