### ISSUE TITLE
Change dataset ownership (10.5061/dryad.fj6q57402)

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2687]
Please change ownership of this dataset:

Title: DnaJC7 specifically regulates tau seeding
DOI: 10.5061/dryad.fj6q57402

...to:

Author: Valerie Perez
Email: valeriea.perez@utsouthwestern.edu
ORCID: 0000-0001-8854-515X

**Comment by ryscher** [comment]
Changed ownership; added ORCID and email.
