### ISSUE TITLE
Search by journal name in admin layer and front end search

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#269]
We store the ISSN, we call the journal API for journal name from the ISSN

This should be broken into two tickets:
1) Search within admin layer: one field that aggregates all search data, include journal name as one of the facets
2) Search on the landing page: search against SOLR, but we aren't storing this in SOLR because it's internal data... Check geoblacklight schema which has a section for this.

**Comment by briri** [comment]
moved the public search to #283
