### ISSUE TITLE
System automatically putting datasets into In Progress on its own

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2701]
Curators have identified published datasets that are currently In Progress, with the Activity Log indicating that a curator accessed the dataset and left it in that status, but the curator did not in fact do so. When viewing searches in the Admin Site, there is no listed assigned curator for these datasets. At least [one author](https://dryad.lightning.force.com/lightning/r/Case/5003h00000djB3sAAE/view) has emailed HD with confusion (or maybe frustration) over the subsequent automated 'In Progress' reminder email. These weird occurrences are identifiable to curators because they occur on days of the week or times of the day during which they are never active. It is unknown whether this is only occurring for published datasets or when this started to occur.

Known examples:

- https://datadryad.org/stash/ds_admin/activity_log/111815
- https://datadryad.org/stash/ds_admin/activity_log/112300
- https://datadryad.org/stash/ds_admin/activity_log/107671
- https://datadryad.org/stash/ds_admin/activity_log/111652
- https://datadryad.org/stash/ds_admin/activity_log/112300
- https://datadryad.org/stash/ds_admin/activity_log/108429

**Comment by ahamelers** [comment]
Could this have something to do with the pub updater? @sfisher @ryscher

**Comment by ryscher** [comment]
I verified that this is not happening through normal PubUpdater activities.

**Comment by ahamelers** [comment]
There is no notification when someone moves a dataset to "in progress"; there is a rake task that sends out a reminder email to the submitter when a has been left "in progress" for 3 days.

```ruby
  desc 'Email the submitter when a dataset has been `in_progress` for 3 days'
  task in_progess_reminder: :environment do
    p "Mailing users whose datasets have been in_progress since #{3.days.ago}"
    StashEngine::Resource.joins(:current_resource_state)
      .where("stash_engine_resource_states.resource_state = 'in_progress'")
      .where('stash_engine_resources.updated_at <= ?', 3.days.ago)
      .each do |r|

      reminder_flag = 'in_progress_reminder CRON'
      if r.curation_activities.where('note LIKE ?', "%#{reminder_flag}%").empty?
        p "Mailing submitter about in_progress dataset. Identifier: #{r.identifier_id}, Resource: #{r.id} updated #{r.updated_at}"
        StashEngine::UserMailer.in_progress_reminder(r).deliver_now
        StashEngine::CurationActivity.create(
          resource_id: r.id,
          user_id: 0,
          status: r.last_curation_activity.status,
          note: "#{reminder_flag} - reminded submitter that this item is still `in_progress`"
        )
      end
    rescue StandardError => e
      p "    Exception! #{e.message}"

    end
  end
```
We could alter this rake task to check and only send the reminder email if the was set to "in progress" by the submitter. Does that seem like a reasonable action? It doesn't solve the problem of datasets being mysteriously set to in progress.

**Comment by ahamelers** [comment]
I have searched through the code for every way in which new versions are created and can't yet find any that could be triggering this—all new version methods should record the current_user in the activity log; none that I can find use the latest curator name. This is a really weird one!

**Comment by bryanmgee** [comment]
Can we investigate the AAAS integration? Like I mentioned (but I don't think it's in the ticket), I'm seeing a lot of these instances where the author says they're locked out, specifically because it's In Progress due to being edited by an AAAS Admin but then the Activity Log said it was me editing me (which I wasn't, it was accessed at like 9 PM for me).

**Comment by ahamelers** [comment]
Thanks for the tip @bryanmgee , I will check that out specifically! Do you have any thoughts about the proposed change to the in progress notification?

**Comment by ahamelers** [comment]
@bryanmgee thank you so much, you were correct! The new version appears to be from an API request from AAAS. From such an API adjustment, the current editor is set to the API requestor, but the curation activities log user is apparently not—I'm still not clear on why it's set to the last curator, since that doesn't seem to be a default or anything, but I'm fixing this so it will also be set to the API requestor in future (which will at least be much less confusing).

I have looked and it seems like we no longer have logs for these dates, but I have no reason to think these API requests from AAAS were handled incorrectly—they may have been made unintentionally on their end, but there's nothing we can do about that. But in any case, they should have sent a submission request after sending their new version creation request, which clearly did not happen.

We don't want to prevent these requests, or delete any changes made via API request ourselves. The most reasonable solution, to me, is to remind AAAS to complete their submission, instead of bugging the submitter. I propose we change the in-progress reminder notification to go to the current_editor, instead of the submitting user—this makes the most sense in all cases, since anyone but the current_editor is actually locked out from editing anyway.

**Comment by ryscher** [comment]
Looking through this, AAAS is *correct* in not sending a "submitted" status. The workflow they are using should look like this:
1. User presses a button in the AAAS system to create a dataset
2. AAAS uses the API to create the initial dataset, with all of the metadata they currently have available.
3. Dryad responds to the API request with a response that includes an "editLink"
4. AAAS redirects the user's browser to the editLink
5. The user completes the submission, adding all required metadata, and then presses the Submit button.

Bryan sent a new example dataset that had the problem (https://datadryad.org/stash/ds_admin/activity_log/10083). This dataset had the original submitter for the first resource's `user_id` and `current_editor_id`. The second resource (the one with the problem) had the submitter as `user_id`, and AAAS Admin as `current_editor_id`.

**Comment by ahamelers** [comment]
@ryscher the links in the ticket are not creating initial datasets though, but previously published ones, creating new in progress versions that the submitters are then locked out of editing. So is your preferred solution making the submitter also the current_editor when these API requests come in?

**Comment by ahamelers** [comment]
@ryscher we removed setting AAAS admin as the current editor, but for published manuscripts where a curator was the last editor, it looks like that current editor id is copied and the actual owner is still locked out from editing. Should we explicitly set the submitter/owner user as the current editor? Make it blank? (any other ideas?)

**Comment by bryanmgee** [comment]
Okay, so the latest iteration of this bug is that the Activity Log says that it's the author editing it, but the author cannot in fact edit it, and they see "being edited by AAAS Admin" on their dashboard. Came up for [this dataset](https://datadryad.org/stash/ds_admin/activity_log/110058?); here is a screenshot of what I see in the Activity Log and then one from the author:

![Screen Shot 2023-09-14 at 8 51 27 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/b239bbc2-746e-4640-8676-90c88983f4d7)

![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/9021a83b-da6a-46bc-836a-676a9bdceb31)

**Comment by ahamelers** [comment]
@bryanmgee I think this is the same issue as originally and not a new issue, as you can see the dates of the latest status changes on this one are back in May. Fixing the problem so it doesn't occurr going forward will not change the database settings for any datasets previously affected. You can mess with these yourself to try to take over the editing, or please make individual tickets if you need the database editor/submitter ids changed.
