### ISSUE TITLE
Discrepancies in Curation stats

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2705]
Curators have noticed discrepancies in the Curation stats, and Bryan analyzed the problems. 

It is possible that these problems are occurring due to recent additions/changes to the activity log. This system is a bit brittle. The stats are calculated based on the log history, but the automated tests surrounding the curation stats are relatively limited, so we do not always notice when changes to log entries will have an effect on the stats.

**Comment by ryscher** [comment]
Bryan's analysis:
[Curation stats discrepancies.zip](https://github.com/CDL-Dryad/dryad-product-roadmap/files/12223452/Curation.stats.discrepancies.zip)

**Comment by jleighherzog** [comment]
See related ticket https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2721#issue-1841487292 for proposed changes to column data.

**Comment by ahamelers** [comment]
@bryanmgee 

1. "Author versioned" is checking the logs for new 'submitted' versions where the DOI was previously 'published' or 'embargoed'. "Author revised" is counting only those that were in 'action_required', specifically, and that are now in 'curation'. I can't see anything wrong with the way these calculations are being done—however, in contrary to what I think your report supposes, they have little to nothing to do with each other, and I can imagine that what is being counted in either or both cases is not _useful_. I thinking in #2721 we should discuss and decide what these should actually be counting.
2. I am still looking at the new/to-submitted/to-ppr checks, I will investigate further.

Are there any other discrepancies I've missed from your report?

**Comment by bryanmgee** [comment]
@ahamelers those are all of the ones I flagged; Author Versioned and Author Revised should not have any relationship to each other, but the former is clearly not calculating what we want it to (the prescription is accurate, so something must be going wrong in the formula); I just used Author Revised as a comparison point because that one may be accurate and is more useful (i.e. how many datasets are resubmitted per day)

**Comment by ahamelers** [comment]
@bryanmgee I added an extra check to see if there are duplicate Author Versioned ones as well
