### ISSUE TITLE
High priority: add Journal of Applied Entomology to Wiley 

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2714]
**Description**
Wiley has added the Journal of Applied Entomology to the list of journals for which it's covering DPCs.

**Describe the solution you'd like:**
Please add this journal to the invoicing list.
Pernille at Wiley would like it added 'ASAP'.

@ryscher @ahamelers @jleighherzog

**Comment by ryscher** [comment]
Journal settings updated.

**Comment by ryscher** [comment]
@jleighherzog The journal list is automatically generated, based on the internal settings. It is now listed.
