### ISSUE TITLE
Author submitted dataset with no data files

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2717]
This dataset ([DOI](https://datadryad.org/stash/dataset/doi:10.5061/dryad.8w9ghx3n8)) entered the queue, but as can be seen on the landing page, there are no actual data files (just something submitted to Zenodo). It also displays as 0 bytes on the [table view](https://datadryad.org/stash/ds_admin?q=%22Supplement+2+to+the+paper+%E2%80%98What+can+supraspecies+richness+tell+us%3F%E2%80%99%22&sort=relevance&commit=Search&tenant=&editor_id=&curation_status=&publication_name=&sponsor_org=&utf8=%E2%9C%93). The [Activity Log](https://datadryad.org/stash/ds_admin/activity_log/75413?) indicates it was created about 2 years ago and then released from PPR via the author dashboard button.

**Comment by sfisher** [comment]
Seems like the author probably had the same thing open in multiple windows and removed the files in one window and submitted in the other where it was correct (but that wasn't the current version).
