### ISSUE TITLE
PubUpdater feedback/requests

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2720]
I spent a while going through PubUpdater and looking for different potential hang-ups and pinch points in the process. In addition to #2667, here are some other areas (with examples) that we would need to address or get clarity for ideal workflow on before we can have it returned to regular usage:

1. System makes a match but there are no apparent suggested changes. 
![Screen Shot 2023-08-07 at 8 05 07 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/c9fb56a2-b90b-40fa-a331-e9dddb3cf019)

I thought that PubUpdater was supposed to import keywords to match the article's, but I tried it with one of these that didn't show any apparent suggested changes, and the keywords, which were different than the article's, did not change. The Activity Log did log the change, but I didn't actually see anything change.

2. System only suggests changing the ISSN (from print to electronic or vice versa).
![Screen Shot 2023-08-02 at 5 15 41 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/8a33a785-92a2-455f-8687-863ec0e2c9ae)

3. System tries to replace filled ISSN field with blank ISSN field despite correctly identifying a journal in our system. This usually occurs in tandem with another suggested change that we would want to implement, such as adding the article DOI.
![Screen Shot 2023-08-02 at 5 16 22 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/e5198d02-2303-4565-988a-2d71e60342e8)

4. System matching to Withdrawn datasets. In the first example, there are three datasets with the same name; one of the two shown below is Withdrawn, and the other is in AAR (but should be Withdrawn since the third, not shown here because it already had its article added during curation, is Published). 
![Screen Shot 2023-08-02 at 5 20 27 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/5850cdc2-c9b0-4cfc-b981-ede57d2f4016)
![Screen Shot 2023-08-02 at 5 28 47 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/dacfb972-a0da-402a-9025-5036927ee694)

I believe that one of the original purposes of PubUpdater was to look specifically for unpublished datasets that had published articles as a means of prioritizing curation, but I don't think that we need to do this with the current turnaround time. Currently, if you sort on Publication Date, it's sorting on that of the article, not that of the dataset, so it isn't possible to do a quick sort for already-published datasets to ignore Withdrawn ones. The system catching Withdrawn datasets also slows down the process in terms of attempting to import metadata only for a Published dataset when there are duplicates with the same metadata in our system.

5. System attempting to overwrite correctly matched/originally input Primary Article with another article DOI.

![Picture1](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/03271f4c-ccf1-42e9-a4ed-57135e5f8899)

**Summary**: Right now, the issue posed in #2667 is the most frequent by far and thus creating the most inefficiency; most of the top matches are attempting to overwrite an article DOI with a bioRxiv preprint (e.g., 42 of the first listed 50 entries are this issue). All of these other issues were identified at least several times, however, and their relative frequency is as follows:

- System matching to Withdrawn dataset
- System makes match with no apparent changes
- System wants to replace one ISSN with another (same journal)
- System wants to remove ISSN
- System wants to replace correctly primary article with unrelated article

**Comment by sfisher** [comment]
Also, some old datasets that have been in the publication updater for a while do not have the latest subjects and information and may need to have a special script to match them and update the data in our database again from xref.
