### ISSUE TITLE
Assign ownership of dataset (DOI: 10.5061/dryad.3m2c3)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2722]
Please assign ownership of this dataset (10.5061/dryad.3m2c3) to this author: 

Nicholas Marino
[0000-0002-5702-5466](https://orcid.org/0000-0002-5702-5466)
[nac.marino@gmail.com](mailto:nac.marino@gmail.com)

**Comment by ahamelers** [comment]
This is done.
