### ISSUE TITLE
Add Tenant: Northeast Ohio Medical University

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2724]
**Tenant name:** Northeast Ohio Medical University

**Logo location:** https://www.neomed.edu/marcom/brand/logo/tier-1/

**Contacts to receive submission notices:** N/A

**RORs that are considered part of the tenant (including medical centers, alternate campuses, etc.)** https://ror.org/04q9qf557

**Shibboleth info, if not in [InCommon](https://incommon.org/community-organizations/):** Azure Active Directory (SAML 2.0 compliant)

Tasks:
- [ ] add config to `config/tenants`
- [ ] add logo to `app/assets/images/tenants`
- [ ] deploy and test on stage (institution should log in to verify working as expected)
- [ ] update `tenant_id` for users in the database who have emails with the institutional domain name

**Comment by ryscher** [comment]
We can add the basic tenant immediately. Integration with Azure Active Directory will have to wait until later, likely spring 2024. Is there a range of IP addresses we can use until the Azure connection goes live?
