### ISSUE TITLE
Transfer responsibility for payment to new affiliation (DOI: 10.5068/D1339F)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2727]
The author initiated a data submission using her ORCID iD that was connected to her previous institution (UCLA). She's since updated her ORCID iD to reflect Univ of Washington and I've updated her user profile. 

The dataset still reflects that payment will be covered by UCLA. Possible to update this to reflect payment will be covered by Univ of Washington?

**Comment by ryscher** [comment]
Due to #2768, I had to set the tenant_id for the Resource object back to `ucla`. Note that the payment information still reflects `washington`.
