### ISSUE TITLE
Localize times for admins

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#2733]
Related to #2721

1. Localize (to browser time) all dates in the Admin Dashboard (show the UTC datetime as a tooltip on hover).
2. On the Curation Stats page, rather than the UTC date, show the end time of the period localized to the user's browser time—this way the Admin Dashboard and Curation Stats pages can still be matched up.

Examples from my own time zone:

<img width="1168" alt="Screenshot 2023-08-16 at 20 32 38" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/1749394/f42b6c9c-4413-4641-add4-957c6cf84dbf">
<img width="1171" alt="Screenshot 2023-08-16 at 20 32 52" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/1749394/207707f0-66ba-4c13-8940-b796a02edd61">

@jleighherzog @bryanmgee @lauradryad thoughts?

**Comment by ryscher** [comment]
Please add a display above or below the table that indicates the time zone being displayed. See attached sample from Doodle.
![Screenshot 2023-08-21 at 1 30 08 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/605143/aaf8a430-799b-4185-828b-f000f1961f43)

**Comment by ahamelers** [comment]
> When any stats are pulled/exported, will they be in the local time zone? 

No

> Should we expect that, depending on the time zone and time pulled, the stats will be a little bit off?

No, this is just translating the UTC time for each event to the user's local time zone. Everyone will still see the same things.

> Possible for users to select their preferred time zone? 

That would be more of a major feature (not a quick and easy javascript thing, like this)

> Possibly to display the time zone? 

Ryan commented and it's now on the top of the tables
