### ISSUE TITLE
BUG: doi_linking_invitation

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2739]
The `doi_linking_invitation` is mailing authors who have already received messages.

**Comment by ryscher** [comment]
I believe the problem lies with the final `include?` in `lib/tasks/stash_engine_tasks.rake` line 250. This statement receives an array of strings, but it only matches on an exact string match (it doesn't look inside the strings).

Note that I temporarily disabled the emails by commenting out the relevant entry in `daily.sh` on the production server.

**Comment by ryscher** [comment]
While fixing this, it would be useful to add the DOI or title to the emails.

**Comment by sfisher** [comment]
IDK about this task, but I believe there is an `.include?` method on both Array and String classes.  Array checks the entries to see if an array includes an exact entry.  String include checks for a substring.  If this is supposed to be a String include then perhaps join the array of strings so it becomes a single string before calling `include?`
