### ISSUE TITLE
Provide librarian at member institution with admin site access 

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2741]
Eric Kuijt (data librarian at the Netherlands Institute of Ecology (NIOO-KNAW)) would like to be granted limited access to the admin site to monitor datasets submitted by affiliated researchers

ORCID: 0009-0000-9455-6680
Email: e.kuijt@nioo.knaw.nl

**Comment by ryscher** [comment]
You can change these permissions on the "Manage users" page. Ensure the user is assigned to the correct institutional tenant, and use the "Tenant Administrator" role setting.
