### ISSUE TITLE
Prevent resubmissions if author has not changed anything

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2742]
We have two semi-common instances in which authors resubmit a previously submitted dataset without making any changes, and this adds time to the curation workflow:

1. A dataset has gone through curation and has been returned to the author for edits. The author either misses the emails or ignores them and, either way resubmits without changes. This sometimes happens repeatedly, despite curators following up with the author each time.
2. A published dataset is "versioned" without any apparent changes.

It would be ideal if the system can at least display a message indicating that no changes have been made or to simply prevent them from resubmitting at all if no changes have been made. We may want to craft specific messages if we go the pop-up message route that are different for previously published datasets vs. unpublished datasets (e.g., "email help@datadryad.org if you are unsure what changes need to be made")

**Comment by ahamelers** [comment]
@bryanmgee is there some kind of explanatory message displayed within the system for the user if a dataset is set to action_required?

**Comment by bryanmgee** [comment]
Not as far as I know. The real pie in the sky would be if the system could somehow display the contents of the last email sent to them like ScholarOne does (admittedly not always that well), but a message like: "We noticed that you have not changed your metadata or files. Please refer to an email from help@datadryad.org, sent to the email address that you provided, with details on queries that require your attention before we can publish your dataset." or something similar would be useful

**Comment by ahamelers** [comment]
I mean, if 

<img width="527" alt="Screenshot 2023-08-21 at 20 11 03" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/1749394/d69835d9-0666-4442-83c2-94235107bb70">


1. this is how you set something to action required, and 
2. you fill in this "Notes" field with something user-readable

We could definitely display that Note content.

**Comment by bryanmgee** [comment]
Oh I do not think we want to do that hahahaha, it would completely mess up anyone used to the current workflow in which anything entered in the Admin Site is only visible to other users of the Admin Site (and is entered candidly with that expectation), and the level of detail that we normally enter in there is very short and would not be sufficiently useful to a user if they didn't receive or read our email

**Comment by bryanmgee** [comment]
Yeah, so we only use that Note section for quick self-reference. You could compare this [SF email ](https://dryad.lightning.force.com/lightning/r/Case/5003h00000djjYQAAY/view) with the [notes](https://datadryad.org/stash/ds_admin/activity_log/115233) I put for it in that field and see the discrepancy.
