### ISSUE TITLE
Update documentation for submission API

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2744]
We have increased requirements for data submissions, but we have not always updated the API documentation to acknowledge these requirements.

Bring the [API documentation](https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/apis/submission.md) up to the current level to describe all minimal metadata and steps to fulfill requirements (e.g., how an API user performs the equivalent of the "No funding received" checkbox).

Ensure reports API is fully documented.

**Comment by ahamelers** [comment]
Added more detailed documentation for reports API to swagger documentation

**Comment by ryscher** [comment]
Update the sample submission metadata to use current examples, and show all possible fields, including research domain, funder, and grant IDs.
