### ISSUE TITLE
Import metadata after curation, different functionality

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2745]
Curators note that authors who import metadata after curation generally mess up and reset many fields that were previously lovely.

The exception seems to be getting additional keywords (subjects).

Perhaps don't do a full import after curation has completed (or perhaps even after an initial submission).  Maybe just update keywords.

**Comment by ahamelers** [comment]
I am going to treat this as urgent since, with the addition of the DOI invitation email, this seems to be affecting the curators now in a big way

**Comment by ahamelers** [comment]
@sfisher after merging in your pubupdater changes ,I found your new populate_pub_update method does exactly what I had put in place for this. Convenient!
