### ISSUE TITLE
Author was able to submit dataset without README (10.5061/dryad.rr4xgxdf2)

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2746]
[Dataset](https://datadryad.org/stash/dataset/doi:10.5061/dryad.rr4xgxdf2) ([Activity Log](https://datadryad.org/stash/ds_admin/activity_log/115516?)) – this was only created last week, so it is not a legacy behaviour, and if you access the dataset, it displays the error message that there is no README file (there is a README file earmarked for Zenodo). However, if you download from the landing page (which also shows no README in the file list), it does download with a README file.

![Screen Shot 2023-08-23 at 11 50 33 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/16bbe247-3372-4d95-9440-d23fe622cdfe)
![Screen Shot 2023-08-23 at 11 50 15 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/57981092-13e9-4472-80ae-2ee46f009a38)

**Comment by ahamelers** [comment]
The new README mechanics will be released next week (#2410) and have a lot more required checks on the presence and type of README content, should re-evaluate this then

**Comment by ahamelers** [comment]
I think between the new README checks and @sfisher 's changes for https://github.com/CDL-Dryad/dryad-app/pull/1327, this is resolved
