### ISSUE TITLE
populating citations working correctly still?

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2748]
Some complaints that we weren't getting the citations desired.

Evaluate weekly cron and task `bundle exec rails counter:populate_citations`.

---

I don't think this is technically really part of COUNTER though it's in the same rake task and related, but it does look for citations from DataCite weekly and populates into our DB.

Looking in `stash_engine_counter_citations` it has some and seems to have updated recently.  @ahamelers IDK if this is what you were talking about in the standup?  If you look up the `identifier_id`s in that table and load the landing page from the DOI then it shows citations like at https://datadryad.org/stash/dataset/doi:10.5061/dryad.fttdz08zw .

These are items citing the current dataset and I don't believe it auto-adds an outgoing relationship FROM the dataset (the citation is an incoming relationship and it just add information about the citation).

Whether this is all the right way to do everything or whether we're getting everything possible from DataCite, IDK, but I think it is continuing to run and do something.

**Comment by ahamelers** [comment]
@sfisher as far as I can see you're correct. This appears to be working correctly. I think the numbers of the citations are just less than the curators may have been expecting.
