### ISSUE TITLE
Change dataset ownership (10.5061/dryad.nzs7h44vf)

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2749]
Please change ownership of this dataset:

DOI: 10.5061/dryad.nzs7h44vf
Title: Data for: Photosystems in the eye-like organelles of heterotrophic warnowiid dinoflagellates

...to:

Elizabeth Cooney
0000-0001-7435-7609

**Comment by ahamelers** [comment]
I've set the owner as requested. The current editor is still you, I think.
