### ISSUE TITLE
System does not open preview landing page or display Review and Submit page for certain datasets

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2757]
The full-time curators have identified issues with loading the preview landing pages of datasets (either in a new tab or new window) and the Review and Submit tab when in editing mode of datasets. The preview landing pages display the "We're sorry, but something went wrong" screen, and the Review and Submit tab displays no content except for a cycling (loading) wheel. As one of us is using Chrome (LB) and the other is using Firefox (BG), this does not appear to be related to the utilized browser (I am also not using any plug-ins/extensions on either Chrome or Firefox). This ticket will be updated as more information comes in, but preliminarily we have identified:

As of 8/29/23, 5 PM Pacific:
- At least two recently submitted datasets that have not been actioned by curators that exhibit this behaviour (https://datadryad.org/stash/ds_admin/activity_log/115947 and https://datadryad.org/stash/ds_admin/activity_log/109679) and that have content entered in the old Usage Notes field
- At least one recently submitted dataset that has not been actioned by curators (https://datadryad.org/stash/ds_admin/activity_log/115853) that does not load the preview landing page but that does not have Usage Notes and does load the Review and Submit Page. 
- At least one recently submitted dataset that has not been actioned by curators (https://datadryad.org/stash/ds_admin/activity_log/116150) that has no Usage Notes and that does not load the preview landing page or the Review and Submit page.

Additional notes (5:17 PM):

A cursory examination of datasets in Curation status (that have already been returned to the author and resubmitted in all cases), indicates this is more prevalent, but not fully characteristic of, older submissions. Examples:
- https://datadryad.org/stash/ds_admin/activity_log/82271
- https://datadryad.org/stash/ds_admin/activity_log/92618
- https://datadryad.org/stash/ds_admin/activity_log/104650

As a counterpoint, here as some old ones in Curation that have no issues:
- https://datadryad.org/stash/ds_admin/activity_log/71950
- https://datadryad.org/stash/ds_admin/activity_log/92618

This also seems to occur with relatively recent submissions that have been initially curated but not yet returned to the author or published:
- https://datadryad.org/stash/ds_admin/activity_log/112526
- https://datadryad.org/stash/ds_admin/activity_log/111414

Additional notes (5:25 PM):

No surprises per se, but this also applies to Published datasets:
- https://datadryad.org/stash/ds_admin/activity_log/107019
- https://datadryad.org/stash/ds_admin/activity_log/110759
- https://datadryad.org/stash/ds_admin/activity_log/115400
- https://datadryad.org/stash/ds_admin/activity_log/115485

**Based on the current assessment, which has essentially been done at random, it appears that this issue could potentially apply to over 50% of datasets**

**Comment by ryscher** [comment]
The underlying issue appears to be an attempt to render a README file that has an ASCII encoding within a page that is otherwise UTF-8.

Sample error message from our log files:
```
I, [2023-08-29T17:32:11.594394 #25087]  INFO -- : [2e0fa3a7-a204-4b6e-96ce-32f675544a8f]   Rendered stash_engine/landing/show.html.erb within layouts/stash_engine/application (Duration: 321.0ms | Allocations: 64072)
I, [2023-08-29T17:32:11.594454 #25087]  INFO -- : [2e0fa3a7-a204-4b6e-96ce-32f675544a8f]   Rendered layout layouts/stash_engine/application.html.erb (Duration: 321.1ms | Allocations: 64099)
I, [2023-08-29T17:32:11.594578 #25087]  INFO -- : [2e0fa3a7-a204-4b6e-96ce-32f675544a8f] Completed 500 Internal Server Error in 332ms (ActiveRecord: 7.2ms | Allocations: 69652)
F, [2023-08-29T17:32:11.595764 #25087] FATAL -- : [2e0fa3a7-a204-4b6e-96ce-32f675544a8f]   
[2e0fa3a7-a204-4b6e-96ce-32f675544a8f] ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT):
[2e0fa3a7-a204-4b6e-96ce-32f675544a8f]     20:        locals: { abstract: review.abstract, methods: '',
[2e0fa3a7-a204-4b6e-96ce-32f675544a8f]     21:      other: '', highlight_fields: [] } %>
[2e0fa3a7-a204-4b6e-96ce-32f675544a8f]     22: 
[2e0fa3a7-a204-4b6e-96ce-32f675544a8f]     23:   <%= render partial: "stash_datacite/descriptions/readme", locals: { review: review, highlight_fields: [] } %>
[2e0fa3a7-a204-4b6e-96ce-32f675544a8f]     24: 
[2e0fa3a7-a204-4b6e-96ce-32f675544a8f]     25:   <%= render partial: "stash_datacite/descriptions/show",
[2e0fa3a7-a204-4b6e-96ce-32f675544a8f]     26:      locals: { abstract: '', methods: review.methods,
[2e0fa3a7-a204-4b6e-96ce-32f675544a8f]   
[2e0fa3a7-a204-4b6e-96ce-32f675544a8f] app/views/stash_datacite/resources/_show.html.erb:23
[2e0fa3a7-a204-4b6e-96ce-32f675544a8f] app/views/stash_engine/landing/show.html.erb:31
[2e0fa3a7-a204-4b6e-96ce-32f675544a8f] config/initializers/wicked_pdf.rb:26:in `render'
[2e0fa3a7-a204-4b6e-96ce-32f675544a8f] app/controllers/application_controller.rb:3:in `process_action'
```

I temporarily fixed this on production by removing the calls to the `readme` partial from:
- `app/views/stash_datacite/resources/_review.html.erb`
- `app/views/stash_datacite/resources/_show.html.erb`

**Comment by ryscher** [comment]
Grrr. Still getting problems for some datasets, so we may need to handle other encodings. One example is https://datadryad.org/stash/dataset/doi:10.5061/dryad.jm63xsjf8 with the error:
```
 [e581cf32-a12d-452e-a973-32d5222ccf50] ActionView::Template::Error (invalid byte sequence in UTF-8):
[e581cf32-a12d-452e-a973-32d5222ccf50]     2: <% content = review.readme_content %>
[e581cf32-a12d-452e-a973-32d5222ccf50]     3: <% if review.readme_content.encoding == Encoding::ASCII_8BIT %>
[e581cf32-a12d-452e-a973-32d5222ccf50]     4:   <% content = review.readme_content.force_encoding(Encoding::UTF_8) %>
[e581cf32-a12d-452e-a973-32d5222ccf50]     5:   <% if content.match(/\\#/) %>
[e581cf32-a12d-452e-a973-32d5222ccf50]     6:     <% reformat = markdown_render content %>
[e581cf32-a12d-452e-a973-32d5222ccf50]     7:     <% content = ActionView::Base.full_sanitizer.sanitize(reformat) %>
[e581cf32-a12d-452e-a973-32d5222ccf50]     8:   <% end %>
[e581cf32-a12d-452e-a973-32d5222ccf50]   
[e581cf32-a12d-452e-a973-32d5222ccf50] app/views/stash_datacite/descriptions/_readme.html.erb:5:in `match'
[e581cf32-a12d-452e-a973-32d5222ccf50] app/views/stash_datacite/descriptions/_readme.html.erb:5:in `match'
[e581cf32-a12d-452e-a973-32d5222ccf50] app/views/stash_datacite/descriptions/_readme.html.erb:5
[e581cf32-a12d-452e-a973-32d5222ccf50] app/views/stash_datacite/resources/_show.html.erb:23
[e581cf32-a12d-452e-a973-32d5222ccf50] app/views/stash_engine/landing/show.html.erb:31
[e581cf32-a12d-452e-a973-32d5222ccf50] config/initializers/wicked_pdf.rb:26:in `render'
[e581cf32-a12d-452e-a973-32d5222ccf50] app/controllers/application_controller.rb:3:in `process_action'
```

**Comment by ahamelers** [comment]
OK, I have some ideas, will try again

**Comment by ryscher** [comment]
The README in the example above is `iso-8859-1`

**Comment by ryscher** [comment]
Thanks, this fixes the problem! (for most files, at least...)
