### ISSUE TITLE
New member question about SSO

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2758]
New member's SSO configurations are managed through HelloID (Tools4Ever) following SAML 2.0 protocol.

Metadata: https://cdrewu.helloid.com/metadata/download?ApplicationGUID=45e9e389-4fc4-497b-be46-8121c700a829

They are asking for Dryad metadata in order to configure on their end -- is this necessary? I don't remember having done this for other set-ups.

**Comment by ryscher** [comment]
Answered this on the [Jira card](https://datadryad.atlassian.net/browse/NMO-309)
