### ISSUE TITLE
Update log-in page

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2759]
**Problem description, and links to relevant helpdesk tickets:**
The log-in page (https://datadryad.org/stash/sessions/choose_login) could be used as a useful landing page (for use in blog posts, advertising, marketing materials, etc.) with some enhancements to the text.

**Describe the solution you'd like:**
- Change header from "ORCID account" to "Get started" or "Log in" or "Start a submission".
<img width="553" alt="image" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/82666810/75ba5611-7357-407f-a8c7-3edb8ca59af7">

- Change "Dryad's Commitment to You" to sentence case ("Dryad's commitment to you").
- Update commitments text with links out to additional info:

Curation
All datasets are curated to ensure they are Findable, Accessible, Interoperable, and Reusable. [Learn more.](https://datadryad.org/stash/mission#our-curation-and-publication-process)

Compliance
Enabling adherence to funder and publisher open data mandates. [Learn more.](https://blog.datadryad.org/category/policy/)

Community supported
Dryad is researcher-led and supported by our institutional and publisher members. [Learn more.](https://datadryad.org/stash/join_us)

**Comment by ahamelers** [comment]
Would it be better to rename 'Dryad's commitment to you" to something like "Why use Dryad?"

**Comment by sarahklippincott** [comment]
Yes! I like that.

**Comment by ahamelers** [comment]
Okay! Just a note, link text of "Learn more" (particularly repeated) is inaccessible. I'll add links to the text where it's descriptive of the link instead.

**Comment by sarahklippincott** [comment]
@ahamelers Yes, please do change them to descriptive text.
