### ISSUE TITLE
Authentication setup -- SUNY Fredonia

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2767]
```
I am the SSO admin at SUNY Fredonia and have received the request 
from our Librarian to set up SSO for Dryad. We are not a member of the 
InCommon Federation, we use Microsoft Azure for SSO. Please forward 
your metadata, link or file, and I will set up the application in our Azure 
tenant for SSO. I understand that you require we release the 
eduPersonPrincipalName and mail attributes, is this correct? Here is the 
link to our federation metadata: 
https://login.microsoftonline.com/c124053c-f078-4984-8f9d-35ae0f78c58a/federationmetadata/2007-06/federationmetadata.xml
Let me know if you need anything else from us. 

```

Related to #2724. If we cannot do Azure easily, we should fall back to IP verification.

**Comment by marisastrong** [comment]
@ashleygould to update the /non_federation_metadata.xml file in stage and perform testing of authentication.

@ryscher Provide attribute_release.xml files to SUNY to configure their IdP for release of attributes
 https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/membership/dyrad_attribute_release.xml

**Comment by marisastrong** [comment]
Once tested in stage can add to production

**Comment by ashleygould** [comment]
I've updated non-federated-metadata.xml for uc3-dryad-ui-stg hosts. We are ready for SUNY folks to test.

But I still need contact info to fill in this block:

```
  <ContactPerson contactType="administrative">
    <SurName>??</SurName>
    <EmailAddress>mailto:??</EmailAddress>
  </ContactPerson>
```

**Comment by sdiggs** [comment]
Hey Ashley,

You can use …
Idalia Torres
***@***.******@***.***>
________________________________

**Comment by ryscher** [comment]
IP verification is set up. Steve/Ashley may wish to continue working on SSO.
