### ISSUE TITLE
Add tenant: Lawrence Berkeley Lab

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#277]
Emailing logo b/c its an SVG I can't upload here. Shib is confirmed to work on their end.

**Comment by briri** [comment]
Added tenant setup and logo for LBNL
<img width="1268" alt="Screen Shot 2019-04-23 at 8 48 25 AM" src="https://user-images.githubusercontent.com/1204467/56596038-a479d300-65a4-11e9-8ec6-10439e2a5fda.png">
<img width="1224" alt="Screen Shot 2019-04-23 at 8 47 09 AM" src="https://user-images.githubusercontent.com/1204467/56596039-a479d300-65a4-11e9-8690-592bb44d942b.png">
