### ISSUE TITLE
AGU report for datasets to determine payment type

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2772]
**Priority**: This report is essential now because the status of datasets can change at any time
**Impact**: Who will pay is set and agreed upon by journal, Dryad, and authors

Please pull a report for all AGU-related journal titles in Dryad. The purpose of this report will be to determine which datasets will require the author to pay the DPC vs datasets that will be covered by AGU sponsorship based on the created date and/or submitted date and its relationship to the cutoff date (August 1, 2023 is when membership ended).
Fields to include: 

1. > Journal name
2. > Dataset DOI
3. > Status
4. > Title
5. > Authors
6. > Created date
7. > Submitted date

**Comment by jleighherzog** [comment]
@mariaguerreiro : Ticket for a report to eliminate manual check

**Comment by ryscher** [comment]
@jleighherzog To verify, my understanding is that we will add the Created date to the CSV that is generated from the Admin dashboard. All of the other fields are already in this CSV.

I hope that these reports will only be used for informational purposes, and not create a lot of manual follow-up work. Having a member leave should not cost us extra effort. When we remove a member on the dev side, any new submissions created after that date are no longer charged to the member. We should formalize policies for how members are charged when they start and end memberships, so the system can handle all of this without manual intervention.

**Comment by jleighherzog** [comment]
@ryscher : That's a better idea. Sounds good. Wasn't sure whether a new column could/should be added.

**Comment by ryscher** [comment]
@jleighherzog The updated column is now available in the CSV exports from the admin page.
