### ISSUE TITLE
Markdown rendering on landing page not displaying carriage returns

### ISSUE THREAD

**Issue by lauradryad** [CDL-Dryad/dryad-product-roadmap#2773]
**Bug description:**
When carriage returns are visible in the markdown editor, they are not rendering on the landing page, causing huge chunks of text. Below are pictures of one of the datasets where I encountered this. 

The markdown file in a text viewer: 
![Screenshot 2023-09-05 at 12 35 39](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/124197995/40401930-18d0-47db-aa4f-cbef0714a127)

How it looks on the landing page:
![Screenshot 2023-09-05 at 12 32 54](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/124197995/f76eca01-3f9d-49cb-86c3-4181e57665e5)

It is taking out all the carriage returns in the file making it one big lump. I also went into the WYSIWYG editor to add carriage returns and header formatting and this is what it looks like: 
![Screenshot 2023-09-05 at 12 37 11](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/124197995/acd34605-47e7-4f2b-86b8-3ad039d2df4f)

But then this is still what the preview looks like on the landing page:
![Screenshot 2023-09-05 at 12 32 00](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/124197995/498ea67f-ec41-4e28-b6c0-bfc39b1ca191)

The headers are fixed but still no carriage returns. I also had this issue when working with MacDown - making carriage returns display as a new line was a separate setting so I'm not sure if it's a choice that can be made when rendering. 

**Steps to reproduce:**
Edit a README in the submission editor and add carriage returns within one chunk of 'paragraph' text and then toggle to Review and Submit page. 

**Expected behavior:**
Carriage returns in WYSIWYG editor will display on landing page.

**Comment by bryanmgee** [comment]
Another example:

![Screen Shot 2023-09-05 at 4 09 10 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/84e2723e-1214-4b39-b978-81894c3a46e9)
![Screen Shot 2023-09-05 at 4 09 34 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/2b46c8c7-73be-43d3-aa02-84a340937823)

**Comment by ahamelers** [comment]
>Expected behavior:
>Carriage returns in WYSIWYG editor will display on landing page.

@lauradryad
It is pretty standard for markdown rendering for an actual separating line to be needed for breaks. It's definitely frustrating for the WYSIWYG editor rendering to be different from the final rendering, though, so I'll see what I can do to make them match

@bryanmgee 
A fix like Laura has asked for should add the desired line breaks into that example of yours, but I don't think there is any markdown rendering setting that will make those tabs appear permanently in the WYSIWYG editor or final rendering. If the user wants to, it they can use the markdown table option.

**Comment by ahamelers** [comment]
I just want to add that this change will add a line break in the HTML whenever they appear in the markdown—it's pretty common for people to add line breaks just to make all the lines in a paragraph the same length, without intending for them to appear in HTML rendering—so this may be a surprise in some cases. However, I think it does make sense to match the WYSIWYG rendering in the editor (which I am less able to change).
