### ISSUE TITLE
"Authors in" report for Macquarie

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2781]
Macquarie University has requested the "authors in Dryad" report.

(Related to #2495.)

**Comment by ahamelers** [comment]
This is in Drive in the Institutional Submission Reports directory https://docs.google.com/spreadsheets/d/1PwfEEz9rR79zMVIJ8lXRAIptJUZ8rM4xyVAOWhCJEtk/edit#gid=0
