### ISSUE TITLE
Fix for bucket Access Control Lists (ACLs)

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2782]
This is turning into its own problem where we cannot access any of the Merritt-written content in the Dryad bucket.  We can access our own content that we've written, however.

I did a lot of experimentation and feel pretty certain this is an ACL problem on all the Merritt content. It took a while to figure this out and I think Joe Somontan also agreed it was likely an ACL issue.  AWS now says they do not recommend using ACLs because of complexity and management problems and it was an older way to do things.

## Examples of problems

- In the AWS web console, try downloading anything by using a user that isn't the Merritt one.  `Permission denied`
- In the AWS command line interface
```
# works for an item Dryad wrote
aws s3 cp "s3://dryad-assetstore-merritt-stage/ark:/99999/fk8222rzm|1|producer/testfile01.txt" .


# Merritt written: fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
aws s3 cp "s3://dryad-assetstore-merritt-stage/ark:/99999/fk8222rzm|1|producer/aaaTEST.txt" .
```
- In our Ruby code:
```
s3 = Stash::Aws::S3.new(s3_bucket_name: APP_CONFIG[:s3][:merritt_bucket])
s3.exists?(s3_key: 'ark:/99999/fk8222rzm|1|producer/aaaTEST.txt')
# gives "Caused by Aws::Waiters::Errors::UnexpectedError: stopped waiting due to an unexpected error: Aws::S3::Errors::Forbidden"

s3.put_file(s3_key: 'ark:/99999/fk8222rzm|1|producer/testfile01.txt', filename: '/Users/sfisher/testing_zenodo_relations.txt') # true

s3.exists?(s3_key: 'ark:/99999/fk8222rzm|1|producer/testfile01.txt') # true

s3.presigned_download_url(s3_key: 'ark:/99999/fk8222rzm|1|producer/testfile01.txt') # works and downloads

s3.presigned_download_url(s3_key:'ark:/99999/fk8222rzm|1|producer/aaaTEST.txt') # gives a URL which returns

<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>0K84H4CAMB1THM9W</RequestId>
  <HostId>bU9MzHdJhGpFhBuAZzJMKVqp4Nhn2NU0BPzjrnrFYth0CT/OkUsNQW7jfO6sLfWiRqRsVS7JMMhAxD2fU7zK+A==</HostId>
</Error>
```
- The web interface does not allow resetting to policy-managed while the ACLs are present currently (may be ways around that, see below)
- Also unable to see the permissions on individual objects written by someone else.  Perhaps Merritt could see them for their owned objects.

## Possible solutions

- I had a zoom with Joe Somontan about the problem and he suggested copying everything in the bucket to another since that solves the problem. He had a lambda and had done this elsewhere.  Ryan also verified that copying it elsewhere solved the problem.
- I found this [blog post](https://www.puppeteers.net/blog/how-to-disable-s3-bucket-acls/) about how to remove the ACL option (which isn't obvious how to do).  The summary of it is that you need to:
  - Reset bucket ACLs to the default "Private" settings (I guess because that is the default) 
  - Set Object Ownership for the bucket to "Bucket Owner Enforced"
  - It seems to have a lot more good details.

## Doing it without disruption
- If we want to pursue disabling the ACLs then ~we should be aware that both Dryad Dev and Dryad Stage use the same bucket (Merritt Stage) so it may be disruptive to both of those environments if something goes wrong.~
  - We would probably want to test the procedure on a non-used bucket first to be sure we understand how it works (and set up some data written from an entirely different account besides Dryad so it's in the same situation).
  - We would want to then do it on the Merritt stage bucket (and be sure their writing isn't affected) and is successful.
  - And then production
  - How do we roll back if something goes terribly wrong?

- If we want to consider making a copy of of the contents to work around the problem, then that copy would need to be continually updated with new content since Dryad production has new content arriving all the time.

**Comment by ryscher** [comment]
Here's a new AWS help page that has a suggested resolution to the problem: https://repost.aws/knowledge-center/s3-bucket-owner-access

**Comment by sfisher** [comment]
Thanks for this info @ryscher .  The command they have works, but only after booting any external owners off the bucket (under ACL in the web interface, remove the external account grantee).

This is an example of the command.

```
aws s3api put-bucket-ownership-controls --bucket example-bucket --ownership-controls 'Rules=[{ObjectOwnership=BucketOwnerEnforced}]'
```

I believe this might also be able to be done in the UI so long as the external grantee is removed first.

I tried this out and it does allow us to move off the ACLs into a policy-managed mode like AWS now recommends.  It seemed to break the stage content so I put the ACLs back for now.

I'm hoping Ashley will be available next week to help us find the best policy that allows Merritt to retain access, reduce the ACL complexity and also allow Dryad access to its own content.  The ACLs were limiting access at the object level, I believe (which is a granularity I don't believe we need).

**Comment by sfisher** [comment]
So it turns out that the dev content is going to a different S3 bucket that CDL owns.  I was under the impression that dev and stage merritt collections went to that one bucket but they don't.

See https://docs.google.com/document/d/1GRr1BYP7TTZd1_m20smCTVL6HvI1yS-PiF3tUBer6VA/edit?usp=sharing .

**Comment by sfisher** [comment]
This is fixed in dev and stage and we have instructions of how to fix for production.
