### ISSUE TITLE
Migrate WAF settings to v3 servers

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2791]
- [x] Get current WAF settings for Dryad servers
- [x] Install WAF for v3 servers

**Comment by DragosIorgulescu** [comment]
Left to do:
- set this up on the rest of the servers (staging & prod)
- update the docs https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/external_services/amazon_aws_ec2_setup.md#set-up-shibboleth-service-provider
