### ISSUE TITLE
Checksum validation for v3 storage

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2792]
- Build a process to download a data file and validate its checksum
- Make a cron to manage the validation process for all data files

S3 has [new support for checksums](https://aws.amazon.com/blogs/aws/new-additional-checksum-algorithms-for-amazon-s3/ ) that may be helpful.

**Comment by ahamelers** [comment]
Hi Ryan,

* I assume when you say "download a file" you mean from S3?
* Is Merritt currently doing checksum validation? Is this documented anywhere?

Thanks!

**Comment by ryscher** [comment]
Yes, download would be from S3, but may not be necessary if the file can be processed directly from S3. For smaller files, this process could happen in Lambda.

Merritt computes a checksum when the file is ingested, an validates the checksum on every file every 60 days. The general description is in the [Merritt future planning](https://docs.google.com/document/d/1lFGCXtiuHc0AwWXu4F_MXAwpKlIKk2gvziilrvX1q4I/edit?usp=sharing) document, but I'm not aware of any Merritt internal documentation. 

Initially, it would be worthwhile for our validation cron to mimic the Merritt process. We have discussed the possibility of validating less frequently in the new system, particularly for large files. The Merritt team said that they have never found actual file corruption, only the occasional indication that one of their other systems had a problem. But we may want to continue the same frequency to provide a high level of preservation assurance.

Users sometimes want to validate checksums to ensure they have downloaded the complete file. But we haven't been able to reliably provide checksums to end users -- see [ticket 962](https://github.com/CDL-Dryad/dryad-product-roadmap/issues/962).
