### ISSUE TITLE
Transition COUNTER stats to DataCite tracker

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2793]
As of 2024-01-03 these are the steps to take to finish this off.

After December is run:

1. Change app_config.yml to [:counter][:account], [:counter][:token] to DRYAD.DRYAD and move in the credentials in the encrypted files (currently commented out).
2. remove code to call python processor.
3. Continue to use datacite_data_repo_id: da-80l49bsf for the repo id.  No changes needed.
4. Datacite can retroactively set the stats from the beginning of January.  our december report is done.
5. We can completely remove the crons for Counter stuff and remove code after that.

---

Emailed Richard/Kelly at DataCite on 2023-12-11 to see what we need to do for this to go from CDL.DASH to DRYAD.DRYAD.  Will update more info as we hear or we may call a meeting if more work on our side is needed (such as resubmitting all our current COUNTER reports which we have as JSON on our ec2 instance drive.

---

Current plan:

- Finish out 2023 submitting under the CDL account (and a last submission in January for the full month of December).
- Any new reports from logs for Jan 2024 or after should come from the DRYAD.DRYAD JWT.
- Independently checking about the switch to the web tracker and what we and DataCite need to do to make it the source of our reporting.  It is currently submitting to DataCite in test mode.
- The switch to web tracker doesn't have to happen at the same time as the switch to the DRYAD.DRYAD account but we should stop sending stats from our logs when that gets switched.
- New credentials are in encrypted file, but currently commented out so they are easy to switch at the appropriate time.

**Comment by sfisher** [comment]
I believe this task is now complete (PR for the cleanup) and I emailed Kelly to have them turn on the javascript tracker stats starting January 1st, 2024.
