### ISSUE TITLE
Develop test plan for v3 system

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2796]
Develop a comprehensive test plan for validating all functionality in v3. Do we need to add more to rspec? Or make a list of manual tests?

**Comment by ahamelers** [comment]
I've found the last manual test list we used for the ruby and rails upgrade, and checked the current test coverage. In the next sprint I will work to write new tests to expand test coverage as much as possible and to make a spreadsheet of all functionality and whether it has automated tests and/or requires manual testing (#2833). I think it would also be a good idea to schedule a bug bash (if possible, one each for the existing system and the new system)
