### ISSUE TITLE
embedding (bad) images causes the markdown editor not to load

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2799]
There was an author who had the markdown inline editor not loading.  By examining the console errors, there were two things causing it.

The author put in embedded images like `![](README_files/figure-gfm/Legume%20plots%20for%20number%20of%20introduced%20ranges-1.png)<!-- -->` in the code.

This caused one problem since these are embedded images that will not resolve to the path given since any files uploaded will not have relative paths/urls like this.  It might or might not work with a full URL somewhere else on the internet, but then those images will probably go away sometime and no 

It also caused another problem since the HTML comment (`<!-- -->`) also seemed to break the markdown editor.

IDK how we prevent or handle the errors, or maybe we need to strip out images or other embeds and maybe some kinds of HTML or make people edit manually-only if they have that content.

**Comment by ahamelers** [comment]
Moving this to the next sprint, in which I will attempt to replace the editor.
