### ISSUE TITLE
Migration for user accounts in the database

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#28]
Perform the database-side user migration.

- [x] Determine whether old user accounts should go into the main (stash users) table, or into a completely new table. What info do we need to store in this table? (When this is done, notify team so they can build to the new user info).
- [x] Modify the tables appropriately (i.e., make a rails migration to update the schema)
- [x] Determine whether user accounts should be migrated via SQL import/export commands, or via some more rails-oriented method
- [x] Implement migration of the user account records (though these won't do anything until the UI account migration is enabled)

**Comment by daisieh** [comment]
> Determine whether old user accounts should go into the main (stash users) table, or into a completely new table. What info do we need to store in this table? (When this is done, notify team so they can build to the new user info).

We have decided that the only change needed to merge the two tables (stash_engine_users and eperson) is to add an eperson_id column to stash_engine_users.

> Modify the tables appropriately (i.e., make a rails migration to update the schema)

https://github.com/CDL-Dryad/stash/pull/15 adds the necessary column to the schema.

> Determine whether user accounts should be migrated via SQL import/export commands, or via some more rails-oriented method

We've decided to use SQL directly, because developing a user API does not seem necessary for MVP.

**Comment by daisieh** [comment]
>>>Implement migration of the user account records (though these won't do anything until the UI account migration is enabled)

https://github.com/CDL-Dryad/migration-utils/pull/1 pulls old Dryad epersons into the stash_engine_users as stub entries with email, eperson_id, firstname, lastname.
