### ISSUE TITLE
Landing pages now displaying strings of commas when listed authors do not have an email provided

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2802]
This seems to affect most datasets regardless of current status, but I have seen at least [one](https://datadryad.org/stash/dataset/doi:10.5061/dryad.pzgmsbcnv) where only one email address was provided, but there is no string of commas. The first time I saw this, I thought the author had put a space or similar 'blank' in each email field, but that wasn't the case.

![Screen Shot 2023-09-12 at 3 51 34 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/d604e0ca-e99e-4631-aff8-9eb01f539780)
![Screen Shot 2023-09-12 at 3 50 46 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/dcb19da3-14df-44ea-a60f-96f70176d9bf)
![Screen Shot 2023-09-12 at 3 50 32 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/0a3c7deb-f27c-4247-8e74-4e4eeb33c11c)

**Comment by ahamelers** [comment]
It's very mysterious to me that this was not discovered in testing
