### ISSUE TITLE
Dataset won't validate README or save changes made in editor

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2805]
DOI: [10.5061/dryad.4qrfj6qg1
](https://datadryad.org/stash/ds_admin?q=%2210.5061%2Fdryad.4qrfj6qg1%22&sort=relevance&commit=Search&tenant=&editor_id=&curation_status=&publication_name=&sponsor_org=&utf8=%E2%9C%93)

Before yesterday's deploy, the author told me they had resubmitted with an updated README, but when I went into their dataset, it looked like nothing had changed, and there was no new version of files. I had them email me the updated version as a result. Now that I went to update the README, it looks like the system is simply not saving any changes to content in the README editor (after I tab over, it pops up the "you need to make a change" message, and when I tab back, it's wiped my changes). I can, however, trick it with a README.txt file on the Upload Files tab, but we don't want the really bad original .md README.

Semi-priority: AAAS submission with the paper dropping next week.

**Comment by ahamelers** [comment]
@bryanmgee Could you send me the file you are trying to replace the text with?

**Comment by ahamelers** [comment]
Okay, I got the README from the Salesforce case and this does in face seem to be the case. The response for this text in particular is a 403 Forbidden. I'll try to work out exactly what content is causing a problem—just a guess but could be some special character.

**Comment by ahamelers** [comment]
By pasting one section at a time, I've found that the issue is with the line containing this placeholder URL:

> Preprint: https://doi.org/10.26.../chemrxiv-2023-gq2h0

Altering this not to contain an ellipsis makes the content save just fine. But it's a bit bewildering that it's blocked!

@sfisher @ryscher Is there some security level on the production database that is not allowing this text to be saved? Is it possible to turn it off for this object?

**Comment by sfisher** [comment]
This looked like a Web Application Firewall rule from the default AWS ruleset called GenericLFI_BODY .  https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-baseline.html 

I disabled blocking on the rule and I believe it works ok now.  Test and let me know.  Thanks for tracking this trickiness down, Audrey.

**Comment by bryanmgee** [comment]
Everything went through this time, thanks all!
