### ISSUE TITLE
disallow web page uploads for zenodo, especially github web pages

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2807]
We put in something saying "no" when people tried putting in html pages a long while back.

However we've seen a few creeping in again for urls like 

```
https://github.com/dahalsushil/S_mexicanum/tree/main/morphometrics
https://github.com/dahalsushil/S_mexicanum/tree/main/phylogenomics
```

These are just web pages, even if they are a github web page that lists a "directory" of files.

IDK why these are not being caught these days, but they do not work for the upload process to zenodo and stall out.

We can maybe figure out what status these are presenting in the upload to zenodo process and flag a better error there since these are a bit difficult to see why they are failing without wasting a bunch of time looking through details.

Recommend the zip release from github or else using a service such as archive.org for web pages (and not Dryad or Zenodo).

**Comment by DragosIorgulescu** [comment]
> Recommend the zip release from github or else using a service such as archive.org for web pages (and not Dryad or Zenodo).

this should show up as a message in the UI if there are upload errors related to a github link like the ones given as an example

**Comment by DragosIorgulescu** [comment]
Based on my investigation, I could not get this to work in any way, it looks like HTML pages are correctly rejected -- checked this in the code as well and it seems to [perform proper validations](https://github.com/CDL-Dryad/dryad-app/blob/c235a986202c6f3d68a6a0bb4cf1e0c9be755d90/app/models/stash_engine/url_validator.rb#L152)

![Image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/1225100/b26eaa4c-03f2-43c6-9b83-ab287d12f749)
