### ISSUE TITLE
Investigate tracking failure in Matomo

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2810]
Matomo is unable to track https://datadryad.org/stash/sessions/choose_login. Could this be related to the recent changed to that page?

**Comment by ryscher** [comment]
I'm not aware of any recent changes to the page. I verified that the Matomo code appears properly there. I suspect this was a one-time failure due to other issues (e.g., we had low memory on the server this morning, so the page may have taken a little extra time to load)

**Comment by sarahklippincott** [comment]
Thanks for investigating @ryscher :)
