### ISSUE TITLE
PRIORITY: Remove public files

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2812]
**Priority**: High
**Impact**: Sensitive data published, swift removal is appreciated

Title: _Change and persistence of hunting & dietary practices among Kadazandusun-Murut (KDM) bearded pig hunters in Sabah, Malaysia_
DOI: [10.6078/D1CT5V](https://datadryad.org/stash/dataset/doi:10.6078/D1CT5V)

Please remove the data files from public view including any files that are copied to other locations (Zenodo?). The author has raised concerns regarding the data submitted and these concerns warrant removal. Keep the metadata available, I'll post a note regarding the removal of the metadata on the dataset landing page. 

Let me know if you have any questions.

**Comment by ryscher** [comment]
Files have been removed from view in both Dryad and Zenodo.
