### ISSUE TITLE
Remove American Medical Informatics Assn & German National Library of Medicine

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2816]
**Problem description, and links to relevant helpdesk tickets:**
The AMIA and the German National Library of Medicine are not renewing their (ancient) agreements with Dryad.

**Describe the solution you'd like:**
Please remove both organizations from the website and from the quarterly deferred revenue list. 

We will need to begin invoicing their authors.

@ryscher @ahamelers @mariaguerreiro

**Comment by ryscher** [comment]
What is the effective date? Should they receive an invoice for this quarter?

**Comment by mark02139** [comment]
@ryscher , effective when you have a chance to get to it. Their agreements are really old and not technically in effect anyway, and their volumes are so low that it's really not worth processing invoices for them.

**Comment by ahamelers** [comment]
@ryscher Several of the journals for these 2 orgs are set to default to PPR. Should I change this setting?

**Comment by ryscher** [comment]
Let's fine to leave the PPR setting. It's not associated with the payment plans.
