### ISSUE TITLE
Transfer ownership of datadryad.org from Dryad to CDL

### ISSUE THREAD

**Issue by marisastrong** [CDL-Dryad/dryad-product-roadmap#282]
I've submitted a ticket to IAS to initiate this transfer.

**Comment by marisastrong** [comment]
hi @ryscher 
Our IT team (IAS) needs the following information:

 In order for the domain to be transferred, we need the person who manages the domain to do the following at namecheap.com:
 
Disable domain privacy for the domain so we can get your contact information.
Ensure the domain's registrant email at WHOIS is valid and reachable.
Get an authorization code for the domain
All the steps are important.  Once I get the authorization code, I can start the request to transfer.
 
Or if you can provide the information without disabling the domain privacy you can do that too :-)

**Comment by marisastrong** [comment]
i'm wondering if we need to do anything regarding the mail server since all your email resides at datadryad.org domain.

**Comment by ryscher** [comment]
Email will continue to be handled by our Google Apps account, as long as we retain the existing MX records. But we will need to retain all of the other DNS records that we're currently using, anyway.

**Comment by ryscher** [comment]
I have created a google doc describing the process and technical issues surrounding this transfer:
[https://docs.google.com/document/d/14QWgeWW1bIzqCfkNBZc5pLchE0pAAU_QDv--xMZOqsg/edit?usp=sharing](https://docs.google.com/document/d/14QWgeWW1bIzqCfkNBZc5pLchE0pAAU_QDv--xMZOqsg/edit?usp=sharing)

Please have IAS review this document before initiating the transfer. (And add any comments of your own as well.)

In response to the request from IAS: 
- It looks like NameCheap is automatically making everything private. I was not able to find a way to disable the privacy.
- The registrant email is `admin@datadryad.org`, which goes to me.
- I have obtained an authorization code: `0i523l2u@2s5r1w`

**Comment by marisastrong** [comment]
@ryscher discussion of DNS management is separate from the transfer of ownership.  Let's complete the transfer of ownership and then we can discuss the DNS management.  I'll set up a meeting for us.

**Comment by ryscher** [comment]
@marisastrong That's fine as long as IAS understands not to change the nameservers before completing the requested setup. Doing so could break critical functionality in the current Dryad system.
