### ISSUE TITLE
Problem with Zenodo integration for https://datadryad.org/stash/dataset/doi:10.25349/D9WP6S

### ISSUE THREAD

**Issue by brunj7** [CDL-Dryad/dryad-product-roadmap#2821]
**Bug description:**
Hi,
I am a curator at UCSB. I just published a data archive https://datadryad.org/stash/dataset/doi:10.25349/D9WP6S that had 2 Zenodo integrations: one for software and one for supplemental information (zip file of 1.52GB).

However, currently, only the software is listed as related work on the landing page. When I search on Zenodo, I find both entries but the supplemental material one does not list the supplemental data (only the files on DRYAD

**Steps to reproduce:**

Zenodo links:
- software : https://zenodo.org/record/8323153 ✅
- supplemental data: https://zenodo.org/record/8364678 ❌ there should be a `data.7z` file listed

**Expected behavior:**

**Comment by ryscher** [comment]
Hi @brunj7, the movement of content to Zenodo sometimes takes a while, depending on the size of the submission and the other submissions in process. This is currently one of 12 items in the queue that are being transferred. We will check back later in the week to ensure the transfer has completed properly.

**Comment by brunj7** [comment]
oh, ok thank you for letting me know!

**Comment by ryscher** [comment]
Update on this submission... the software has been transferred. The supplemental information is still waiting in our queue.

**Comment by sfisher** [comment]
Both are showing up as related now and I fixed a few items that showed errors in the zenodo queue.

**Comment by brunj7** [comment]
Thank you!
