### ISSUE TITLE
Understanding file retrieval failures

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2822]
We receive many notices from Merritt about a failure to retrieve a file, usually dozens per day. We have ignored them until now, because they generally do not represent valid requests.

Notices look like this:
```
 Merritt couldn't create presigned URL for http://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5hq9m3g/2/producer%2FR_bubbles_allSamples.relAb.R?no_redirect=true
Http status code: 404
 app/models/stash_engine/data_file.rb:54:in `merritt_s3_presigned_url'

```

In the case of the specific request listed above, the request is for version 2, and the file was marked as deleted in version 2, so it correctly doesn't exist in Merritt, and should never have been requested. 

We need to determine whether all of the notices are the result of such requests, and if so, why are these requests being made? Are the download URLs available through the API, or some other mechanism?

More importantly, as we change to non-Merritt retrievals, what kind of logging do we need in the new system to alert us to such failures?

**Comment by sfisher** [comment]
Because the download urls have ids in them, I assume some bots may also just be replacing with sequential numbers.  I suppose we should've used a less obvious id so that it's harder for people to just try sequential numbers.
