### ISSUE TITLE
Add Yoast SEO plug-in to Wordpress

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2825]
Please add [Yoast SEO](https://yoast.com/wordpress/plugins/seo/) plug-in (free version) to blog.datadryad.org.

**Comment by ahamelers** [comment]
this is done

**Comment by ahamelers** [comment]
@sarahklippincott I've made you an admin on the Wordpress site so you can configure this. If you are overwhelmed by the power, let me know and I'll knock your permissions back down 😁

**Comment by sarahklippincott** [comment]
Thank you!! I won't let the power go to my head.
