### ISSUE TITLE
Add Tenant: Charles R. Drew

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2832]
**Tenant name:** Charles R. Drew

**Logo location:** 

**Contacts to receive submission notices:** 

**RORs that are considered part of the tenant (including medical centers, alternate campuses, etc.)**
https://ror.org/038x2fh14

**Shibboleth info, if not in [InCommon](https://incommon.org/community-organizations/):** 

Tasks:
- [x] add config to `config/tenants`
- [x] add logo to `app/assets/images/tenants`
- [ ] deploy and test on stage (institution should log in to verify working as expected)
- [ ] update `tenant_id` for users in the database who have emails with the institutional domain name

**Comment by ryscher** [comment]
Ashley has determined how to integrate with their SSO system. It should be tested in the next day or two.

**Comment by ahamelers** [comment]
@ryscher 👍 But what do I need to put in the tenant config for this?

**Comment by marisastrong** [comment]
Metadata can be found here:

https://cdrewu.helloid.com/metadata/download?ApplicationGUID=45e9e389-4fc4-497b-be46-8121c700a829

 @ashleygould can you configure in stage so we can test that the attribute release is working properly before the entityID is configured in production?

**Comment by sdiggs** [comment]
Sorry, just seeing this.

I sent Ashley the metadata file earlier in the week.

From: marisa strong ***@***.***>
Date: Thursday, September 28, 2023 at 9:52 AM
To: CDL-Dryad/dryad-product-roadmap ***@***.***>
Cc: Steve Diggs ***@***.***>, Mention ***@***.***>
Subject: Re: [CDL-Dryad/dryad-product-roadmap] Add Tenant: Charles R. Drew (Issue #2832)

CAUTION: EXTERNAL EMAIL

@ryscher<https://urldefense.com/v3/__https:/github.com/ryscher__;!!Mih3wA!AyESLomE7SvtyA6mzoAt-FwWBjN1HRf9w2jJ9RoD20HnDIezYizPG9BEZkSxOquQWbzmQe-1amt2Jh7aD8B9VPw$> @sdiggs<https://urldefense.com/v3/__https:/github.com/sdiggs__;!!Mih3wA!AyESLomE7SvtyA6mzoAt-FwWBjN1HRf9w2jJ9RoD20HnDIezYizPG9BEZkSxOquQWbzmQe-1amt2Jh7a1-4CkRE$> do we have the metadata file for them?

Below are the steps needed to validate before adding the entityID in the tenant config file for non-InCommon members.

[Image removed by sender. Screen Shot 2023-09-28 at 9 50 57 AM]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/810543/271359274-343fbf9b-50a1-41e0-903d-54ee3776de7a.png__;!!Mih3wA!AyESLomE7SvtyA6mzoAt-FwWBjN1HRf9w2jJ9RoD20HnDIezYizPG9BEZkSxOquQWbzmQe-1amt2Jh7az4y-qKc$>
