### ISSUE TITLE
Support RORs in funder field

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2840]
[Planning document ](https://docs.google.com/document/d/1svrl8I1yU6ZS1p45pupWSWSVe63m796XjrAEq0hRp_4/edit?usp=sharing)

1. Modifications to Dryad import script for the local ROR database so CrossRef IDs are also part of the imported data. (#2862, #2860)
2. Switch the autocomplete and vocabulary lookup to begin using ROR rather than CrossRef. The autocomplete should allow pass-through of any existing CrossRef funder names and IDs if there are some remaining that are not ROR and doesn't modify them unless the user changes them. (#2858)
3. Be sure that funder data submission to DataCite works with both ROR funders, CrossRef funders or both in the same record. Ready scripts to backup existing funder data and convert existing FundRef data to equivalent ROR data and test in other environments such as development/stage. (#2859)
4. Ensure that the search system is able to handle ROR funders rather than CrossRef funders for the funder facet display and filtering. (#2861)

**Comment by ahamelers** [comment]
Can this be closed in favor of #2862 ?
