### ISSUE TITLE
A few errors with file downloading (s3 directly)

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2848]
```
An ActionController::ActionControllerError occurred in downloads#file_stream:

  Cannot redirect to nil!
  lib/stash/download/file_presigned.rb:30:in `download'
```

There are only a few errors with this. Probably fewer of these than we used to get from Merritt (based on the past weekend), so I don't think this is any worse than what was existing for years.

Most likely these are mostly bots and perhaps trying to hack the URLs with file numbers.

A few examples:

```
URL        : https://datadryad.org/stash/downloads/file_stream/228006
HTTP Method: GET
HTTP_USER_AGENT                                         : Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)
```

```
 * URL        : https://dash.ucmerced.edu/stash/downloads/file_stream/249697
  * HTTP Method: GET
  * IP address : 185.191.171.6
  * HTTP_USER_AGENT                                         : Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)
```

```
* URL        : https://dash.ucmerced.edu/stash/downloads/file_stream/227991
  * HTTP Method: GET
  * IP address : 185.191.171.6
  * HTTP_USER_AGENT                                         : Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)
```

```
* URL        : https://datadryad.org/stash/downloads/file_stream/102442
  * HTTP Method: GET
  * IP address : 111.225.149.97
  * HTTP_USER_AGENT                                         : Mozilla/5.0 (Linux; Android 5.0) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; Bytespider; https://zhanzhang.toutiao.com/)
```

**Comment by sfisher** [comment]
These all had versions off and you could tell the Merritt versions had been messed around, probably because of deposit issues.  A sign of this is if the merritt and dryad versions don't match.  This isn't always a problem, but if we believe a deposit was successful in an earlier version then when it went in then there can be download issues.

These were all bots hitting these urls.

You can test with the dataset https://dryad-dev.cdlib.org/stash/dataset/doi:10.7959/dryad.8931zct2 and the NIOO.svg file.  It is made to be bad like these so that the deposit took place into S3 in V2, but our database indicates V1 deposit.

I think it's somewhat important to have our "created" states line up with when files were actually deposited in Merritt or at least not point to an S3 version before something was actually deposited.

**Comment by ryscher** [comment]
Closing, as it appears that the offending files have been corrected now.
