### ISSUE TITLE
New Tenant: Montana State University

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#285]
They have confirmed their shib works.

Logo attached - can email SVG if easier
![lib-logo235x54](https://user-images.githubusercontent.com/25755963/56751805-c063ad00-673b-11e9-939f-2aec22c8f78d.jpg)

**Comment by briri** [comment]
Will be available for testing next week at the end of the sprint:
<img width="1230" alt="Screen Shot 2019-05-01 at 2 41 24 PM" src="https://user-images.githubusercontent.com/1204467/57044375-46419580-6c1f-11e9-8603-813b480c2e39.png">
