### ISSUE TITLE
Update contact for Dryad email communications (NCSU library)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2852]
**Priority**: Medium (within 10 days)
**Impact**: Route communications to a new contact 

Please review the message below from **Hilary Davis** (NCSU). We will need to update the contact who receives Dryad email communications for submissions that are linked to NCSU researchers. Can we add **Moira** and **Susan** as recipients or is one contact preferred? 

> "My last working day was Sept 29 and my official last day at **NC State University** will be October 13, 2023.  Soon thereafter, I will no longer be able to access my NCSU email account. Would it be possible to remove my email ([hmdavis4@ncsu.edu](mailto:hmdavis4@ncsu.edu)) from getting notifications about Dryad submissions from NC State researchers?
> 
> Hopefully you have Moira Downey ([mcdowney@ncsu.edu](mailto:mcdowney@ncsu.edu)) and Susan Ivey ([slivey@ncsu.edu](mailto:slivey@ncsu.edu)) already set to receive those notifications.  I'm cc'ing them here in case there is anyone else they want to add."

**Comment by ryscher** [comment]
Removed Hilary. Confirmed that Moira and Susan are on the list.
