### ISSUE TITLE
Provide Michael Tobler with access to Oikos via Dryad Admin dashboard

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2854]
**Priority**: Medium (1-2 weeks)
**Impact:**  Access for journal contact

Please provide **Michael Tobler** with access to Oikos journal data via the Dryad Admin dashboard. 
Email: michael.tobler@oikosoffice.lu.se
ORCID iD: 0000-0001-5895-6302

Q: Are journal contacts typically provided Tenant Administrator access?

**Comment by ahamelers** [comment]
@jleighherzog , the publisher and funder permissions are distinct and assigned in a completely different way from our institutional tenant permissions—Ryan is always using the word "orthogonal" for these 😆 

These users can view the Admin dashboard page, limited to listing submissions associated with their publisher, society, or funding body.

**Comment by jleighherzog** [comment]
@ahamelers : Good question/catch. Let me confirm.

**Comment by ahamelers** [comment]
The requested permissions have been added

@jleighherzog I haven't been party to any communications with this journal sponsor so I do not know if they are sending metadata or using our API to send acceptance updates, or if they've requested auto PPR
