### ISSUE TITLE
Stuck dataset doi:10.5061/dryad.1vhhmgr0b

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2857]
Dataset is stuck in "processing", does not appear in Merritt UI.

**Comment by ryscher** [comment]
The README.md file had a lot of strange characters (not valid markdown characters), and one of these characters was preventing the automatic conversion to load in the README editor.

**Comment by sfisher** [comment]
Ah, thanks for finding this, Ryan.  I took a look but it appeared to have gone through ok and files could download. https://datadryad.org/stash/dataset/doi:10.5061/dryad.1vhhmgr0b
