### ISSUE TITLE
Check integration for importing metadata from Wildlife Biology

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2864]
An author emailed HD saying that they had a manuscript accepted in Wildlife Biology (sponsored title) but that inputting their MS # (WLB-2023-01133) returned the error message that the system could not find metadata to import. I found the journal acceptance notification email, verified the MS #, tried both the core # and adding '.R2' after it, and encountered the same problem. I also see on the [Journals](https://datadryad.org/stash/journals) page that there is no timestamp for 'metadata last received' for Wildlife Biology.

**Comment by ryscher** [comment]
Even though Wildlife Biology has been sending metadata emails since 2021, no one validated the content of these emails. They obviously copied the email format from Ecography without changing the basic information, *including the ISSN*. We will need to ask them to update their emails.

**Comment by jleighherzog** [comment]
Emailed the journal contact, waiting for reply.

**Comment by jleighherzog** [comment]
@ryscher @bryanmgee 

Journal Name: Wildlife Biology 
Journal Code: WLB
Online ISSN: 1903-220X
Journal Admin Email: [me@wildlifebiology.org](mailto:me%40wildlifebiology.org)
Journal Editor: Maria Persson
Journal Editor Email: [me@wildlifebiology.org](mailto:me%40wildlifebiology.org)
MS Reference Number: WLB-YEAR-NUMBER (e.g. WLB-2023-01232)
Publication DOI: 10.1002/wlb3.NUMBER (e.g. 10.1002/wlb3.01232)

Journal Name: Ecography 
Journal Code: ECOG
Online ISSN: 1600-0587
Journal Admin Email: [ecography@oikosoffice.lu.se](mailto:ecography@oikosoffice.lu.se)
Journal Editor: Maria Persson
Journal Editor Email: [ecography@oikosoffice.lu.se](mailto:me%40wildlifebiology.org)
MS Reference Number: ECOG-NUMBER (e.g. ECOG-06960)
Publication DOI: 10.1111/ecog.NUMBER (e.g. 10.1111/ecog.06960)

Journal Name: Oikos 
Journal Code: OIK
Online ISSN: 1600-0706
Journal Admin Email: [assistant-ed@oikosoffice.lu.se](mailto:assistant-ed%40oikosoffice.lu.se), [oikostech@oikosoffice.lu.se](mailto:oikostech%40oikosoffice.lu.se)
Journal Editor: Åsa Langefors
Journal Editor Email: [oikos@oikosoffice.lu.se](mailto:oikos%40oikosoffice.lu.se)
MS Reference Number: OIK-NUMBER (e.g. OIK-10469)
Publication DOI: 10.1111/oik.NUMBER (e.g. 10.1111/oik.10469)

Journal Name: Nordic Journal of Botany 
Journal Code: NJB
Online ISSN: 1756-1051
Journal Admin Email: [njb@oikosoffice.lu.se](mailto:njb%40oikosoffice.lu.se)
Journal Editor: Friederike Gehrmann
Journal Editor Email: [njb@oikosoffice.lu.se](mailto:njb%40oikosoffice.lu.se)
MS Reference Number: NJB-NUMBER (e.g. NJB-04103)
Publication DOI: 10.1111/njb.NUMBER (e.g. 10.1111/njb.04103)

Journal Name: Journal of Avian Biology
Journal Code: JAV
Online ISSN: 1600-048X
Journal Admin Email: [jab@oikosoffice.lu.se](mailto:jab@oikosoffice.lu.se)
Journal Editor: Friederike Gehrmann
Journal Editor Email: [jab@oikosoffice.lu.se](mailto:jab@oikosoffice.lu.se)
MS Reference Number: JAV-NUMBER (e.g. JAV-03133)
Publication DOI: 10.1111/jav.NUMBER (e.g. 10.1111/jav.03133)

**Comment by ryscher** [comment]
Hi Jess, it's great to have this information. Are they updating it in the emails they send? Here is an excerpt from the last email we received from Wildlife Biology:

```
Journal Name: Wildlife Biology
Journal Code: ECOG
Online ISSN: 1600-0587
Journal Admin Email: [me@wildlifebiology.org](mailto:me@wildlifebiology.org)
Journal Editor: Maria Persson
Journal Editor Email: [ecography@oikosoffice.lu.se](mailto:ecography@oikosoffice.lu.se)
MS Reference Number: WLB-2023-01133.R2
```

**Comment by jleighherzog** [comment]
@ryscher : Yes, I provided them with the same example and have asked them to review their templates and make any necessary updates.

**Comment by jleighherzog** [comment]
Followed up with journal contact, Michael, today

**Comment by jleighherzog** [comment]
Followed up with journal contact, Michael, today

**Comment by jleighherzog** [comment]
Update from Michael: 

> I've now gone through all our Dryad email templates and updated the tags where necessary. It should be correct and match with the information I gave you now. If you notice some deviation please let me know!
> 
> Also, and perhaps even more embarrassing, I noted that I gave you the wrong journal editor name for my 'own' journal. So for JAB it should be as below and not Friederike Gehrmann. Can you please check that this is updated in your system.

Journal Name: Journal of Avian Biology
Journal Code: JAV
Online ISSN: 1600-048X
Journal Admin Email: [jab@oikosoffice.lu.se](mailto:jab@oikosoffice.lu.se)
Journal Editor: **Michael Tobler**
Journal Editor Email: [jab@oikosoffice.lu.se](mailto:jab@oikosoffice.lu.se)
MS Reference Number: JAV-NUMBER (e.g. JAV-03133)
Publication DOI: 10.1111/jav.NUMBER (e.g. 10.1111/jav.03133)

**Comment by mahirst** [comment]
This issue is still occurring. Yesterday, we received the prepopulation data from Wildlife Biology for manuscript number WLB-2024-01380.R1 and the author is reporting not being able to use the import metadata function. 

SF38896 (for my records)

DOI: 10.5061/dryad.stqjq2ccd
Resource ID: 328361

**Comment by ahamelers** [comment]
I've updated 27 WLB manuscripts to connect to the correct journal. I checked recent manuscripts from all the other journals for this publisher integration and it is only Wildlife Biology manuscripts that continue to be sent to us with the incorrect journal information (for Ecography)

**Comment by jleighherzog** [comment]
@ahamelers : I'll contact the journal office again today.

**Comment by ahamelers** [comment]
@jleighherzog No, that looks right! I wonder if what they think is sending the information is not what is sending it, and the errors are somewhere else? Because what we are receiving is not:

<img width="193" alt="Screenshot 2024-11-14 at 10 02 28 AM" src="https://github.com/user-attachments/assets/58ab0831-7690-438b-96c7-cd5561261c70">

(I hope you can verify this in the email Molly said we received)
