### ISSUE TITLE
Put CEDAR in production for neuroscience

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2866]
From the FAIR Workflows [Statement of Work](https://docs.google.com/document/d/16SpkAbj_uH4tXLUx8uLFDKikJZ02Qs9IE9RPUTz09zQ/edit?usp=sharing):

> - [Dryad will integrate the CEDAR Embeddable Editor component 
> - The discipline-specific metadata created will be saved and made publicly available alongside the datasets being deposited.
> - Dryad will work with DataCite to determine the relation type for associating metadata template and dataset through the relatedIdentifier property. 
> - Dryad will include the DOI of the template in the DOI metadata of the dataset as a related identifier. 

Improve the saved JSON file:
- [x] When storing the JSON, the template/id field should be the CEDAR id of the template, not our internal id (we may want to make our internal id correspond to the CEDAR id)
- [x] On landing pages, the JSON should be available as `DisciplineSpecificMetadata.json`

Other improvements needed:
- [x] (DataCite) review the template with neuroscientists to make the template usable (e.g., remove default text of "click here to see instructions")
- [x] Only show the CEDAR controls when the dataset is relevant to neuroscience. This includes any dataset where the title, abstract, or journal title contains "neuro" or a neuroscience keyword ([sample keyword list](https://www.teachthought.com/neuroscience-terms/))
- [x] When only one CEDAR template is being presented, just show the template title and associated "Add metadata form" button; don't show a dropdown list.
- [x] Update the process for installing the CEE, to include more Dryad-specific CSS at the time the JS is generated

**Comment by ahamelers** [comment]
Do in concert with #2967

**Comment by ahamelers** [comment]
Since this will appear in part based on the presence of certain keywords, I'll also move the segment to add CEDAR metadata to after the segment where keywords are added.

**Comment by ahamelers** [comment]
>  Only show the CEDAR controls when the dataset is relevant to neuroscience. This includes any dataset where the title, abstract, or journal title contains "neuro" or a neuroscience keyword

@ryscher Doing this, with the current functionality of the site, with the CEDAR editor on the same page on which the title, abstract, keywords are entered is difficult/impossible. With the current setup, each REACT component for metadata entry is siloed and individually loaded and controlled. If a user enters neuroscience triggering keywords in the title or abstract, that wouldn't register or trigger the appearance of the CEDAR editor the unless user left and returned to the page, or reloaded. Large swathes of site functionality would need to be changed to change this.

In a submission system redesign in which each form entry appears on its own page this would be much easier. If this needs to be implemented before such a redesign can be done, the sub-optimal solution would be to have the CEDAR editor component loaded on a later page on which it doesn't naturally fit, like the "Prepare README" or "Upload files" page.

**Comment by ahamelers** [comment]
I put the cedar element and check for neuroscience in a rails route, that I have reload, via javascript, whenever the 'All progress saved' element appears, if the cedar section is not already on the page.

**Comment by ahamelers** [comment]
The latest emails imply the template isn't yet ready to go, so I haven't changed the config for production. The editor will potentially need updating as well and the instructions for installing may change again.
