### ISSUE TITLE
Frictionless: followup about recent updates

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2870]
- [x] Check whether Frictionless has released any new code; if so, determine whether it affects #2405 and whether we should upgrade
- [x] Collect a summary of what we have changed this year in our use of Frictionless
- [x] Document our results of investigating errors, including recommendations for things that Frictionless might change
- ~Ask to have a call to go over recent changes and determine next steps~

**Comment by ahamelers** [comment]
@sfisher how can I see what version of frictionless-py our lambda is using?

**Comment by ahamelers** [comment]
Scott told me how to get the lambda layer, I checked it and we're using version 4.40.8 of frictionless-py. They're up to 5.16 in releases.

**Comment by sfisher** [comment]
Hi Audrey,

Here is some additional information at https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/frictionless_integration/implementation_overview.md .  It links to https://www.linkedin.com/pulse/add-external-python-libraries-aws-lambda-using-layers-gabe-olokun/ which has a procedure to create all the external dependencies under AWS cloudshell and bundle them into a zip for use as a lambda layer.  I believe you upload the zip to S3 and pull it in as a lambda layer from there.

Thanks for discovering the version number but it sounds like it can certainly be updated.

**Comment by ahamelers** [comment]
Summary of frictionless changes:

- Reduced file size of files checked to max 5MB (we should check if the other changes we've made mean we can increase this again, #2880 )
- Added an error limit of 10 to reduce frictionless running time (analysis showed that number of errors had a greater or equal effect on frictionless running time than file size)
- Added a timeout for checking frictionless results commensurate with the lambda running time
- Added actually blank columns to null columns identification list (this was a bug or oversight, fixing this fixed our overabundance of data type errors)
- Documented frictionless errors for our users and integrated documentation into our error reports

I've a separate ticket for upgrading our frictionless version from 4.40.8 to 5.16, as the migration guide indicates changes to the validation and report features that will require changes to our UI code and testing: #2926
