### ISSUE TITLE
Alliance of Crop, Soil, and Environmental Science Societies (ACSESS) quarterly tiered invoicing via Wiley

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2873]
**Description, and links to relevant helpdesk tickets:**
**Commencing January 1, 2024**, Wiley will be covering quarterly tiered DPCs for ACSESS.

**Describe the solution you'd like:**
Journals included in the agreement:

- Agricultural & Environmental Letters
- Agronomy Journal
- Agrosystems, Geosciences & Environment
- Crop Science
- Crop, Forage, & Turfgrass Management
- Journal of Environmental Quality
- Journal of Plant Registrations
- Natural Sciences Education
- Soil Science Society of America Journal
- The Plant Genome
- The Plant Phenome Journal
- Urban Agriculture & Regional Food Systems
- Vadose Zone Journal

@ryscher @mariaguerreiro @jleighherzog

**Comment by ryscher** [comment]
Changed plan from SUBSCRIPTION to TIERED and moved ACSESS under the parent organization Wiley.
