### ISSUE TITLE
Member survey for 2024 priorities

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2879]
Develop a survey that allows members to provide input to the 2024 development priorities. It can include:
- A prioritization exercise of the high-level features listed in the community meeting, and anything else of interest from the "major features" board
- For the features that have some initial requirements gathering (dashboards, search, landing pages, Zenodo), we could make mockups and ask for comments on them
- Open commentary to solicit new features the members need
- Anything else Sarah needs to know from the community

Note: This survey will not completely determine our priorities! We have obligations to GREI and the strategic plan, but member input can influence the relative ordering and the specifics of how these get implemented.

**Comment by ahamelers** [comment]
We've got quite a number of surveys on Jotform now, and have been running into some trouble collaborating on them with each one belonging to an individual—plus each free account only comes with 5 surveys and a 100 monthly responses to those surveys (and 1000 monthly views). Should we consider getting paid account(s), with them or another survey company? They've got nonprofit discounts...

**Comment by ahamelers** [comment]
@ryscher Do we have an update on jotform or other survey builder account status? Or should I create this survey on my individual account for now?

**Comment by ahamelers** [comment]
@sarahklippincott I've started a Typeform for this—please take a look!

**Comment by sarahklippincott** [comment]
@ahamelers This is looking great. Could we add brief descriptions for the proposed features?  (Maybe you are already planning to include that in the survey email or somewhere else). Some of the proposed features are easier to interpret than others.
