### ISSUE TITLE
Test data set

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2881]
**Description**
I would like a test dataset to do augmentation testing.

**Describe the solution you'd like:**
Please produce a test dataset from the most recent 25 **uncurated** datasets submitted, consisting of abstracts and metadata files.

For the metadata files, JSON is fine.

@ryscher

**Comment by DragosIorgulescu** [comment]
- Some of the information is accessible via API only
- extra permissions are needed to download from admin

**Comment by DragosIorgulescu** [comment]
Attaching a JSON of the latest 25 uncurated datasets: [25_uncuratted_datasets.json](https://github.com/CDL-Dryad/dryad-product-roadmap/files/13887800/25_uncuratted_datasets.json)

2 questions:
- I was not sure if the associated files were needed here as well?
- where are [the swagger docs](https://datadryad.org/stash/api#/datasets/get_datasets) generated in the codebase? There are some available params missing in the docs which I'd like to update

**Comment by ryscher** [comment]
- Files are not needed, just the metadata
- The swagger docs are not automatically generated, we edit them manually

**Comment by DragosIorgulescu** [comment]
Sry, missed your response @ryscher  
> Files are not needed, just the metadata

In this case, this ticket should be ready, see file attached in my previous comment

> The swagger docs are not automatically generated, we edit them manually

I updated these in [this PR](https://github.com/CDL-Dryad/dryad-app/pull/1470)

**Comment by ryscher** [comment]
Sent @mark02139 a copy of the datasets via email.
