### ISSUE TITLE
ROR downloader/updater is broken

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2888]
Ryan or someone made a task to download the latest updates.  It seems like it is now super broken.

The URL doesn't resolve https://zenodo.org/api/records/?communities=ror-data&sort=mostrecent .

The ror-data community on Zenodo is at https://zenodo.org/communities/ror-data?q=&l=list&p=1&s=10&sort=bestmatch in the UI, but it seems like the last releases were in 2021.

It seems like the instructions at https://ror.readme.io/docs/data-dump are out of date or no longer valid.

**Comment by sfisher** [comment]
It turns out that Zenodo changes have made this not work or maybe there are other problems.

I added a workaround to download the zip and extract the json manually and just run a task with the path to the file. `RAILS_ENV=development bundle exec rails affiliation_import:populate_ror_db /path/to/file`

**Comment by ryscher** [comment]
Workaround is fine. Work to reinstate/fix the old process will be done in #2893.
