### ISSUE TITLE
PPR after AAR

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#2899]
**Bug description:**

Authors are able return (or newly place) dataset in PPR on their own after it’s been AAR’d, which they should not be able to do

Examples:
https://datadryad.org/stash/ds_admin/activity_log/117270
https://datadryad.org/stash/ds_admin/activity_log/119041
https://datadryad.org/stash/ds_admin/activity_log/100304
https://datadryad.org/stash/ds_admin/activity_log/96171
https://datadryad.org/stash/ds_admin/activity_log/86472

**Comment by bryanmgee** [comment]
It seems like this issue has come up again; [here](https://datadryad.org/stash/ds_admin/activity_log/116034?) is one example (the author actually didn't want to put it in PPR and emailed HD very agitated about it).

**Comment by lauradryad** [comment]
Not sure if this is the best ticket to put this in, but had another case of a dataset that should not have been able to go back into PPR but repeatedly did after AAR: https://datadryad.org/stash/ds_admin/activity_log/126451? (doi: 10.5061/dryad.4tmpg4fjg)

**Comment by lauradryad** [comment]
And another one: https://datadryad.org/stash/ds_admin/activity_log/130787? (doi: 10.5061/dryad.cjsxksnf3). I was going to check on the radio button on this one but everything is getting caught in processing at the moment, so I couldn't.
