### ISSUE TITLE
Upgrade to Rails 5.2 or later

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#29]
We'd like to be on a rails that is getting more than just security fixes before we're even more obsolete.

**Comment by marisastrong** [comment]
@dlowenberg this is a higher priority now as Rails 4.2x is no longer being updated with security fixes since Rails 6 was released Nov 5, 2019.
https://guides.rubyonrails.org/maintenance_policy.html#security-issues

**Comment by ryscher** [comment]
Some additional notes:
- Check code coverage of tests before we do the upgrade
- See Brian Riley's notes in Google Docs and Confluence. 
- See also the upgrade PR for DMP: https://github.com/DMPRoadmap/roadmap/pull/2488
- After (or during?) upgrade, we want to change from Passenger to Puma

**Comment by ryscher** [comment]
This has been replaced by #768, #769, #770.
