### ISSUE TITLE
Import ROR institutions and IDs to database (post-migration)

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#290]
1 spreadsheet has Dryad DOIs and related journal DOI
1 spreadsheet has the ROR information for each author, but the DOIs are for the related journal DOI
Crosswalk to match the Dryad DOI to author name, ror name, ror ID

For adding to DataCite schema:
https://schema.test.datacite.org/meta/kernel-4.3/

Example XML to follow: https://schema.test.datacite.org/meta/kernel-4.3/example/datacite-example-affiliation-v4.xml

**Comment by briri** [comment]
Created script to pull in this data. When combining all TSV files there are around 97k records to process. 

I ran the script on  dev and stage to test it out and things seem to load correctly. We will need to do some analysis and cleanup afterward though. We have quite a few authors and affiliations with bad characters:
```sql
select * from dcs_affiliations where long_name like '%�%';
select * from dcs_affiliations where long_name like '%\_%';

select * from stash_engine_authors where author_first_name like '%�%' or author_last_name like '%�%';
select * from stash_engine_authors where author_first_name like '%\_%' or author_last_name like '%\_%';
```
For example, in this screenshot of data loaded to stage we had 2 authors with bad characters in the string. The bad chars prevented the script from matching them up with the correct author records which appear above. So we will need to reconcile and make sure that the correct author record is associated with the affiliation.
<img width="1233" alt="Screen Shot 2019-07-26 at 10 45 23 AM" src="https://user-images.githubusercontent.com/1204467/61973015-ddf11e80-af97-11e9-8fd6-169c04531b72.png">
