### ISSUE TITLE
Investigate metadata received from eLife (preventing PPR)

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2903]
An author emailed HD saying that they are creating a dataset associated with a manuscript for eLife (eLife-RP-RA-2023-92675) and that the system prevented them from selecting PPR (it simply says "The private for peer review option is not available for this manuscript" without giving the actual reason). I initially suspected that this was because the associated MS is accepted, but the message should state that if so, and the authors clarified that the MS isn't even submitted yet, only created, which is presumably why the Import Metadata function doesn't work because it isn't completed in eLife's system. 

We both independently speculated that this could be related to eLife's new publishing model in which nothing is really "accepted"; can we check whether the metadata that we're receiving from eLife have changed? 

Update: I did a test dataset on production where I input eLife but put 'n/a' in the MS # field, and it gave the same message. This suggests something might have broken in the configuration for eLife (but I guess we should check other journals too) that is not related to the API/metadata connection.

![Martin_screenshot 1](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/32fda063-3ee9-420e-80fa-e0e10c3f4af9)
![Martin_screenshot 2](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/2878558f-fa92-4e0c-a4cc-424f75c9d252)

**Comment by ryscher** [comment]
eLife currently has their configuration set to not allow PPR. I believe this is because in their current publication process, there is not an "acceptance" step; content is available immediately.

I do see though that they have sent us several acceptance notices in the past week, so perhaps they are still making changes to their process.
