### ISSUE TITLE
Multiple ISSNs used in too many places

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2911]
The support for multiple ISSNs was intended to be used only within the journal model, so other parts of the system did not need to be aware of them. However, multiple ISSNs have started appearing elsewhere, such as this dataset's internal data and payment id: https://datadryad.org/stash/ds_admin/activity_log/118730?

- [x] find whatever code is using the `Journal.issn` method, and change it to `Journal.single_issn` (likely in an autocomplete? Looks like the change occurred around 2023-7-20)
- [x] update entries for internal data and payment ID to use a single ISSN rather than an array
- [x] determine whether it it worthwhile to make `issn` a private method, or to modify it so it returns the single value, using techniques like the ones described [here](https://stackoverflow.com/questions/3764899/is-there-a-way-to-make-rails-activerecord-attributes-private)

**Comment by ahamelers** [comment]
autocomplete is using `single_issn`, it must be another culprit!

**Comment by ahamelers** [comment]
Easy SQL queries for these—to do again after code is deployed

`update stash_engine_internal_data set value=value->>'$[0]' where data_type='publicationISSN' and value like '[%'`

`update stash_engine_identifiers set payment_id=payment_id->>'$[0]' where payment_type like 'journal%' and payment_id like '[%'`
