### ISSUE TITLE
Restrict formatting permitted in submission forms

### ISSUE THREAD

**Issue by lauradryad** [CDL-Dryad/dryad-product-roadmap#2916]
**Problem description, and links to relevant helpdesk tickets:**

Curators spend a lot of time reformatting text that authors have pasted into the submission forms as the formatting stays with the text. We can remove all format, but that undoes the italics, superscript, and subscripts that we need to keep. 

**Describe the solution you'd like:**

We would like the editor format options to change depending on who is logged in:

Proposed to keep in text editor for all:
- Text styles
- Bold
- Italic
- Superscript/subscript
- Bullet points/numbering
- Paragraph indent
- Table
- Hyperlink
- Remove all formatting

Proposed to keep only for curators
- Font color
- Highlight color
- Strikethrough

Proposed to remove for all
- Horizontal line
- Block quote
- Font size (if we can restrict font type, make all fonts the same size too)
- Paragraph align

**Comment by ahamelers** [comment]
There's [a complicated Tiny MCE editor plugin](https://www.tiny.cloud/docs/plugins/opensource/paste/) to handle removal of various things when pasting. I've added this plugin and done some basic setup to try to limit pasted things to italic, bold, and super and subscript.

**Comment by ahamelers** [comment]
I guess you still want everyone to be able to select heading levels and monospace?

And curators should still be able to insert code blocks, and that should still be limited to curators?
