### ISSUE TITLE
Removing members from the website

### ISSUE THREAD

**Issue by mariaguerreiro** [CDL-Dryad/dryad-product-roadmap#2918]
Hello Dev, 

Can you please remove the following from the list of members from the website:

* University of Chicago Press
* American Medical Informatics Association
* German National Library of Medicine

Many thanks, 

Maria

**Comment by ahamelers** [comment]
Hi @mariaguerreiro ,  American Medical Informatics Association and German National Library of Medicine were previously removed. Are you still seeing them somewhere?

**Comment by sfisher** [comment]
The only place I can see the American Medical Informatics Association is an example of internal documentation that shows how to send emails to Dryad for metadata about a submitted manuscript.

I believe all but the University of Chicago Press have been already removed.  I removed it from our list.

**Comment by sfisher** [comment]
See https://github.com/CDL-Dryad/dryad-app/pull/1413
