### ISSUE TITLE
Investigate unavailability of PPR option for non-integrated titles

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2921]
This [dataset](https://datadryad.org/stash/ds_admin/activity_log/119856) is associated with a manuscript that was just submitted to a non-integrated, non-sponsored title, _Genome Biology and Evolution_ (I checked the email as well to make sure we didn't have anything). However, the system displays the same generic 'PPR is not available' message that was showing up for eLife submissions (#2903, #2912; i.e. there is no explanation for why) and there is no primary article linked to this dataset that would disable it.

![Screen Shot 2023-11-01 at 8 53 23 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/119f9128-9a82-4feb-92e9-9a92466111ec)

**Comment by ahamelers** [comment]
Having no PPR allowed is a result of this change:

https://github.com/CDL-Dryad/dryad-app/pull/1395

https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2899

Please specify the solution you would like to see if this is not it.

**Comment by bryanmgee** [comment]
Whoops sorry, forgot about that fix. Can we update the message to specifically say that PPR is not available because the dataset has already entered curation? I thought that it used to say that before we discovered that bug that allowed them to return it to PPR on their own.
