### ISSUE TITLE
Remove 'published' status (10.5061/dryad.f4qrfj72j)

### ISSUE THREAD

**Issue by lauradryad** [CDL-Dryad/dryad-product-roadmap#2935]
Dataset [10.5061/dryad.f4qrfj72j](https://datadryad.org/stash/dataset/doi:10.5061/dryad.f4qrfj72j) was accidentally published before everything was curated. Please remove the published version and revert to Curation. The author did make updates after the published version went live, so I'm not sure if this will cause issues. 

Title: Latitudinal gradient, MEND experiment, and BioGen experiment relating species richness and net primary productivity (NPP)

**Comment by ahamelers** [comment]
This is done
