### ISSUE TITLE
Return published dataset to PPR (10.5061/dryad.vhhmgqp0r)

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2936]
[This dataset](https://datadryad.org/stash/ds_admin/activity_log/115912?) should not have been published yet as the associated manuscript, which has yet to be accepted, names new species. To avoid violating standards for these taxonomic acts, the dataset needs to be returned to PPR temporarily.

**Comment by ahamelers** [comment]
This is done
