### ISSUE TITLE
ZIP download via API

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2939]
#2728 updated the ZIP file functionality to use a browser-based solution instead of the Merritt solution. This works for UI requests, but does not accommodate API requests.

Develop a system to create and deliver ZIP files in response to API requests. (Likely based on Lambda, so we don't need to maintain a separate server.)

**Comment by ahamelers** [comment]
@sfisher do you also think it makes sense for a new zipping lambda to use the all-presigned-urls endpoint you made for #2944 ?

**Comment by ahamelers** [comment]
I have written a lambda that creates and streams a zip file to the client, and edited the version download in the API to use it. There are several remaining things to be done:

- For streamed lambda responses, "There is an initial maximum response size of 20 MB, which is a soft limit you can increase." To meet the target of up to 10GB downloads, the size of downloads (streamed response size) allowed by the lambda will need to be increased, which looks like it will require contacting Amazon ("The payload size for streamed responses can be increased from default values. Contact AWS Support to inquire further.")
- Probably the timeout for the lambda will also need increasing. This can be edited in the configuration, but I can't really test what it needs to be increased to before the response size is increased.
- Currently, to retrieve the file URLs, the lambda queries a new API endpoint I made in a very insecure way. Some level of security should be added here, but this is complicated by the fact that we have to use a GET request to redirect to the lambda and thus cannot send it sensitive tokens. I have a couple ideas for this & we can discuss.
