### ISSUE TITLE
Reduce exposure of secrets

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2941]
As we bring on more contract workers, we don't necessarily want everyone to have access to all of the passwords in the Rails encrypted file.

Is it possible to create an alternate encrypted file that contains only the credentials for dev environments? And give new employees access to a key that only unlocks that file?

**Comment by ahamelers** [comment]
The Merritt team uses AWS Systems Manager Parameter Store: https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html

Description of their process: https://uc3.cdlib.org/2020/11/05/streamlining-merritt-microservice-configuration/

**Comment by ahamelers** [comment]
I think the solution for our project's current needs should be much simpler: starting with Rails 6, we may now have multiple, environment-specific credentials and keys.

If environment specific credentials and key files are not present, then the application falls back to the global credentials/key. We could either:

1.  Keep the current credentials and key as they are
2. Create environment specific credentials and keys for development and test
3. Do not share the master key with people who should have dev-only access, and instead share the new dev and test keys with them

Or:

1. Alter the global credentials to contain only dev and test
2. Share the master key with all developers
3. Create environment specific credentials and keys for staging and production, and share staging and production keys only with privileged users

I've read accounts of both setups and it seems like dealer's choice—which feels right to you, @ryscher ?

**Comment by ryscher** [comment]
The second option seems a bit more error-proof. We're less likely to accidentally distribute the more sensitive keys if they only exist on a couple of machines.

**Comment by ahamelers** [comment]
Okay! The only slightly annoying thing with this method is to remember that if a new default secret is added, it will need to be added to all 3 files.
