### ISSUE TITLE
zip stream contain contents for files of "Request rejected due to rate limits."

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2944]
This appears to happen with datasets with a large number of files.  Maybe because presigned urls are either created or opened too quickly.

An example I found was https://datadryad.org/stash/dataset/doi:10.5061/dryad.z612jm6hn which has a lot of files.

We can test more cases and find a solution we know works and then reinstall the download method again.

**Comment by sfisher** [comment]
@ahamelers Can you figure out why this code is directing to a new page rather than downloading?  See the file: `public/stash/service-worker.js` especially in the branch `new-zip-updates`.

I thought I got all the asyncronous stuff correct with the promises and .then clauses, but I must've messed something up.

It does a fetch request to get all the information and presigned urls for the files but it doesn't work.

The nesting is kind of impossible to track, but I put a bunch of console.log stuff in and I can see it seems to be setting up the right files and sizes and other stuff, I think.

It took me a while to figure out how to debug service workers in chrome but I finally found where the logging was going and how to refresh the service worker from the development console (for a while it wasn't reloading with the page).

**Comment by ahamelers** [comment]
@sfisher I thought you were going to handle creating the new endpoint and I was going to handle any adjustments to the javascript and the service worker—making it work in the first place took days of my life, Scott! 😆
