### ISSUE TITLE
PRIORITY: return dataset to curation (10.5061/dryad.rbnzs7hgh)

### ISSUE THREAD

**Issue by lauradryad** [CDL-Dryad/dryad-product-roadmap#2949]
Dataset 10.5061/dryad.rbnzs7hgh was published today, but the author reached out that it's in the middle of a double-blind review. Please return this dataset to Curation as soon as possible, please.

Title: [Male song structure predicts offspring recruitment to the breeding population in a migratory bird](https://datadryad.org/stash/dataset/doi:10.5061/dryad.rbnzs7hgh)

**Comment by ryscher** [comment]
Done. Reset status in Dryad back to `curation`. Updated copies at Zenodo and DataCite.
