### ISSUE TITLE
Update to journal page

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2959]
Priority: Low-Medium
Impact: Pathogens should be removed as a cost-covering journal

Please update the entry for **_PLOS Pathogens_**:
https://datadryad.org/stash/journals

If we're still connected via API, their sponsorship status should be updated in the "Sponsored by" column

**Comment by mark02139** [comment]
@mariaguerreiro , do you have detail for PLOS Pathogens for @ryscher ?

**Comment by mariaguerreiro** [comment]
This is being captured here: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2974

**Comment by ryscher** [comment]
Closing this ticket, as activity has shifted to #2974
