### ISSUE TITLE
Remove data files from DOI: 10.5061/dryad.s7h44j14z

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2962]
**Priority**: High
**Impact**: Remove/hide files that contain identifying information

Please remove files included in version 6 that was first published on Feb 23, 2021. There are concerns regarding re-identification. 
Retain current version 8 published on Nov 20, 2023

**Comment by ahamelers** [comment]
I have hidden this on our site. @ryscher I may need instructions on deleting a version from zenodo (I only know how to set an embargo there)
