### ISSUE TITLE
Investigate programmed automatic deletion of uncompleted 'In Progress' submissions

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2963]
Datasets that were never completed and left in 'In Progress' status are supposed to be fully removed (deleted, not withdrawn) after a year of inactivity (per the Last modified timestamp). It looks like there are many author-created datasets dating back to January 20, 2022, that meet these criteria ([link](https://datadryad.org/stash/ds_admin?curation_status=in_progress&direction=asc&editor_id=&page=10&page_size=100&publication_name=&q=&show_all=false&show_last_page=false&sort=updated_at&sponsor_org=&tenant=)), which suggests that the automated process is no longer working properly. Example screenshot below of this [dataset](https://datadryad.org/stash/ds_admin/activity_log/83017).

![Screen Shot 2023-11-20 at 10 27 45 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/58677f2f-13df-4b40-9871-1d4da4da31ef)

**Comment by DragosIorgulescu** [comment]
So far, I think there may be 2 potential issues:
- these datasets don't match one or more of the criteria the rake task checks, so they are skiped
- there is an exception somewhere in the flow which causes the task to exit early

@ryscher would it be possible to 
- share a dump of the prod data here, it would help with further investigations. 
- share the production logs of the last few runs of this task (or grant me some form of limited access to AWS to check them)

**Comment by DragosIorgulescu** [comment]
ping @ryscher let me know when you get a chance to send a dump of the prod db for these datasets. An alternative would be to give me read-only access to the db (maybe to one of the read replicas?) and I will perform testing against it directly.
