### ISSUE TITLE
README editor - previously submitted READMEs not displayed in editor

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2975]
So far I have identified two datasets that were submitted before the release of the new README editor (but that had proper Markdown-formatted READMEs, not some weird renamed rich text file) and that now display a blank README editor when in editing mode. The README file available for download still contains the content of the last version.

- Example 1: https://datadryad.org/stash/dataset/doi:10.5061/dryad.cfxpnvxcs; for this one, the README editor is both blank, and the README does not render on the preview landing page
- Example 2: https://datadryad.org/stash/dataset/doi:10.5061/dryad.1jwstqk1x; for this one, the README editor is blank, but the README does render on the preview landing page

In both cases, if I download the README file and copy it into the Markdown tab, make sure the changes save, and then change to the rich text tab, nothing is displayed on that tab.

**Comment by ahamelers** [comment]
Since these can be opened in the markdown editor, just not the rich text editor, I've added in parser checks, error messages, and the auto-loading of the markdown editor for these.
