### ISSUE TITLE
Set up auto-PPR upon submission for Systematic Biology

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2976]
**Priority**: Medium (1-2 weeks)
**Impact**: It would be great to have this implemented soon to eliminate the manual work of identifying datasets that are not yet approved for publication but enter our queue for curation.

Please configure automatic PPR for all datasets linked to the journal _Systematic Biology_. 1063-5157

All new submissions should automatically be placed in PPR status when _Systematic Biology_ is selected.

Upon receipt of an acceptance notification from the journal, datasets should be auto-released to the queue for curation (in "Submitted" status). Rejected manuscripts should be auto-withdrawn.

Let me know if you have any questions!

**Comment by ryscher** [comment]
Did the journal ask for this? Historically, Systematic Biology has always wanted us to prevent data from going to PPR. They had preferred everything to publish immediately.

**Comment by jleighherzog** [comment]
Yes, they agreed. I walked them through the process and benefits. Yay!

**Comment by ryscher** [comment]
Done
