### ISSUE TITLE
Return to PPR status (DOI: 10.5061/dryad.f4qrfj72h)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2980]
**Priority**: Medium
**Impact**: Metadata and data files are hidden from public view

Please return this published data submission to 'Private for Peer Review' status: 
Title: _Eurasian tree sparrows are more food neophobic and habituate to novel objects more slowly than house sparrows_
DOI: 10.5061/dryad.f4qrfj72h

**Comment by ahamelers** [comment]
This is done
