### ISSUE TITLE
Update license file

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2988]
The [license for the Dryad software](https://github.com/CDL-Dryad/dryad-app/blob/main/LICENSE.md) has not been updated in many years.
- [ ] Update the dates to reflect the current year
- [ ] Update the license holder? Who should be the license holder as we transition to the Dryad organization performing primary development work? If it changes, how do we acknowledge the UC role?

**Comment by ahamelers** [comment]
I think we should actually remove the year range and just have it as 2015: https://opensource.stackexchange.com/questions/5778/why-do-licenses-such-as-the-mit-license-specify-a-single-year

**Comment by ahamelers** [comment]
> Update the license holder? Who should be the license holder as we transition to the Dryad organization performing primary development work?

The same as the website itself: Dryad

> If it changes, how do we acknowledge the UC role?

Not in the license—we should do this in any appropriate READMEs

**Comment by ahamelers** [comment]
After discussing I changed my mind on this, I think it should be

```
Copyright (c) 2015-2023 The Regents of the University of California,  2023-2024 Dryad
```

Will wait for confirmation
