### ISSUE TITLE
Ensure all ad-hoc methods that Ryan and Daisie added to the API are documented

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#299]
These are methods added for internal use. If we want to make them public they need to follow HATEOAS and probably go into the open-api config.

Tests and API methods all need to follow the HATEOAS (Hypertext as the Engine of Application State) standard.  This means that each action would provide URLs for itself and related actions in the API for discovery.  The ad-hoc items for internal use do not follow this standard and should not be exposed to the public until they do or if we decide we've abandoned this standard.

**Comment by ryscher** [comment]
Fixed long ago
