### ISSUE TITLE
Remove presigned URLs from API responses

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2990]
Some API responses for files (like [this one](https://datadryad.org/api/v2/versions/26724/files)) include S3 presigned URLs. In this case they are expired, but I didn't check whether they always are.

- [ ] Remove all expired presigned URLs from stash_engine_generic_files
- [ ] Determine whether there is a path that puts new presigned URLs into this table, and if so, disable it.

**Comment by ahamelers** [comment]
I think it would make sense to no longer expose upload URLs in the file list API at all, as there's no guarantee these URLs were ever meant to be permanent, and there's no indication to those who use the file upload service that they will be exposed to other users
