### ISSUE TITLE
GREI 1.3.6 - Automatically PPR datasets

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2996]
Automatically send datasets to `peer_review` status when the associated manuscript is not accepted.

On the "Review" page of the submission system, check the most recent Manuscript object associated with this dataset. If this manuscript has not been accepted (see `Identifier.has_accepted_manuscript?`) AND the manuscript has not been rejected (see `Manuscript.rejected?`), then.... 

In the "Choose when to publish" section of the page,
- don't display the radio buttons 
- add a note to the PPR section telling user why they cannot choose (ask curators for the text of this note)
- automatically set the `hold_for_peer_review` to true for the current Resource

**Comment by jleighherzog** [comment]
**Proposed text**: This dataset will remain in ‘Private for Peer Review’ status until we receive a notification from the journal confirming formal acceptance of the associated manuscript.

Also, please **hold** on implementing. Jess is drafting email communication to all journal contacts of integrated titles that will include 1) an implementation date; and 2) an opportunity to ask questions or discuss before the implementation date. Will get drafting!

**Comment by ryscher** [comment]
Ryan will send Jess an export of current journals and contacts.

**Comment by jleighherzog** [comment]
**Date set: Friday, March 22, 2024**
Please schedule an update for this date to configure all integrated journal titles to auto-PPR upon submission

Will share the final list of titles notified by me (Jess)

**Comment by ryscher** [comment]
This PR should be merged on March 22 for release on March 25.

**Comment by jleighherzog** [comment]
These should have auto-PPR already in place: 
- GMS German Medical Science
- GMS Health Technology Assessment
- GMS Infectious Diseases
- GMS Interdisciplinary Plastic and Reconstructive Surgery DGPW
- GMS Journal for Medical Education
- GMS Onkologische Rehabilitation und Sozialmedizin
- GMS Zeitschrift zur Forderung der Qualitatssicherung in medizinischen Laboratorien
- GMS German Plastic Reconstructive and Aesthetic Surgery

These journal titles will be impacted by this update: 
- GMS Health Innovation and Technologies
- GMS Hygiene and Infection Control
- GMS Journal of Arts Therapies 
- GMS Medizin - Bibliothek - Information   
- GMS Medizinische Informatik, Biometrie und Epidemiologie   
- GMS Zeitschrift fur Audiologie     

Pensoft journals: 

- Acta Ichthyologica et Piscatoria
- African Invertebrates
- ARPHA Conference Abstracts
- ARPHA Proceedings
- Arthropod Systematics & Phylogeny
- Atomic Layer Deposition
- Aquatic Invasions
- Alpine Entomology
- One Ecosystem
- BioDiscovery
- Biodiversity Information Science and Standards
- BioRisk
- Biosystematics and Ecology
- Biodiversity Data Journal
- Breathe
- BRICS Journal of Economics
- Bulgarian Cardiology
- Caucasiana
- Check List
- Comparative Cytogenetics
- Contributions to Entomology
- European Respiratory Review
- European Science Editing
- Evolutionary Systematics
- FASEB BioAdvances
- Folia Medica
- Food and Ecological Systems Modelling Journal
- Fossil Record
- Geologica Saxonica
- Herpetozoa
- Interventional Cardiology Forum
- International Journal of Myriapodology
- Italian Botanist
- Journal of the Bulgarian Geographical Society
- Journal of Orthoptera Research
- Journal of Universal Computer Science
- Languages and Modalities
- Lex Genetica
- Maandblad voor Accountancy en Bedrijfseconomie
- Metabarcoding and Metagenomics
- Modern Electronic Materials
- MycoKeys
- Nature Conservation
- NeoBiota
- Neotropical Biology and Conservation
- Nuclear Energy and Technology
- Pharmacia
- PhytoKeys
- Plant Sociology
- Plant Ecology and Evolution
- Population and Economics
- Research Ideas and Outcomes
- Rethinking Ecology
- Russian Journal of Economics
- Silva Balcanica
- Travaux du Mus√©um National d‚ÄôHistoire Naturelle ‚ÄúGrigore Antipa‚Äù
- Tuhinga
- Vegetation Classification and Survey
- Vertebrate Zoology
- Viticulture Data Journal
- Zitteliana
- ZooKeys
- Zoologia

Wiley:
- Evolution and Evolution Letters

Ent society titles: 
- Environmental Entomology
- Insect Systematics and Diversity
- Journal of Economic Entomology
- Journal of Insect Science
- Journal of Medical Entomology

The rest:
-  Systematic Botany
- Applications in Plant Sciences 
- American Journal of Botany 
- Heredity
- Journal of Heredity
- FASEB BioAdvances
- The FASEB Journal 
- Development and Disease Models & Mechanisms
- Journal of Cell Science 
- Journal of Experimental Biology
- Biology Open
- Ornithological Applications 
- Ornithology 
- European Respiratory Journal
- ERJ Open Research
- Biotropica
- Annals of the Entomological Society of America
- Crop, Forage & Turfgrass Management
