### ISSUE TITLE
New policy pages

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#2997]
There were a few pages outstanding from #2396, including a new terms and a new privacy page. The google doc links in the old ticket are no longer accessible. What is the status of these pages? Can they be put up on the website? Most importantly, we need to be able to link to our own Accessibility policy page (rather than the CDL one). #2846 cannot be completed without these new policy pages.

**Comment by ryscher** [comment]
[Privacy policy](https://docs.google.com/document/d/13P0VCwOZIB3yw92TKWQ-HMvpUKwhgyR2NyLTIZZwFLI/edit?usp=sharing) is ready to go. Accessibility policy is being developed.

**Comment by ahamelers** [comment]
- [ ] Privacy policy
- [ ] Accessibility policy
- [ ] Terms page replacement

**Comment by ryscher** [comment]
Remaining work will be split into new tickets
