### ISSUE TITLE
Fix email fill-in from ORCID

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#30]
This was filling in an email address if it was exposed from orcid into the user record, but now it no longer seems to work.

**Comment by briri** [comment]
I tried changing my email visibility settings in Orcid (sandbox and regular) to each of the 3 levels but the `omniauth_hash` always has an empty email.

```json
{
  "credentials": {
    "expires": "true",
    "expires_at": "2163695751",
    "refresh_token": "0987654321",
    "token": "1234567890"
  },
  "extra": {
    "raw_info": {
      "description": nil,
      "email": nil, 
      "external_identifiers": [
        "first_name": "John",
        "last_name": "Doe",
        "location": nil,
        "other_names": [],
        "urls": []
      ],
  "info": {
    "description": nil, 
    "email": nil,
    "first_name": "John",
    "last_name": "Doe",
    "location": nil,
    "name": "John Doe",
    "urls": []
  },
  "provider": "orcid",
  "uid": "0000-0000-0000-0000"
}
```

The gem's documentation shows an email address in  the 'raw_info' section but we seem to be missing it. 
https://github.com/datacite/omniauth-orcid

I'm not sure yet if we're missing something in our config, or if there's an issue with me running it from localhost. It might be defaulting to the public API.

**Comment by marisastrong** [comment]
you can email orcid support to check on this.  if you're getting some attributes back and not others, doesn't seem to be an issue with the localhost, but perhaps public API doesn't provide this now?

**Comment by sfisher** [comment]
Hi @briri, @marisastrong and @dlowenberg .  It turns out this isn't a problem with the API  It seems this was a design choice which I'd forgotten about.

We may use email accounts to connect up to previous user accounts in Dryad and give them control of all their previous datasets.  The ORCID API tells us whether the email address has been confirmed/validated with ORCID. I'm ignoring unvalidated email addresses since someone might put that email into ORCID but it's not really their validated email.

So right now it's ignoring non validated emails.

To make this work you can go into sandbox.orcid.org and into the profile and set it for public or partner.  Then click the "verify" or whatever link in there next to an email.  After verifying it should go in.

Or if you think that is too tight on security or picky I can relax things and accept any email from orcid whether verified or not.

**Comment by sfisher** [comment]
Daniella and I chatted about this and it sounds like we're ok accepting any emails ORCID will give us, whether verified or not.

**Comment by marisastrong** [comment]
i think this is okay, although if we end up moving to or using AWS SES we could run into issues with sending out messages to bad email addresses.  this could be an issue if we have to clean up emails later.  if we know the email is unverified, it might worth noting that so we can identify them later if needed.




________________________________
