### ISSUE TITLE
Return dataset to PPR status

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3003]
**Priority**: Medium-High
**Impact**: Dataset will remain private until the manuscript is accepted

Please return this submission to PPR status. It seems to have been erroneously auto-released from PPR status (can you check?). 

Data from: Evolvability predicts macroevolution under fluctuating selection
DOI: 10.5061/dryad.4j0zpc8hx

**Comment by ahamelers** [comment]
This is done
