### ISSUE TITLE
System reverts PPR selection if journal manuscript metadata is updated

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#3005]
When a dataset was previously associated with a manuscript and designated to be kept in PPR, if the author changes the journal metadata (either changes the name of the journal or enters a new manuscript number), the system automatically changes the PPR designation on the Review and Submit page to "Make my dataset available for public download as soon as possible" (it does not tell the author this). This should be disabled, as it causes problems with datasets being released for curation/being published prematurely.

Steps to reproduce in a sandbox:

1. Create dataset and fill in a journal name and MS number
2. Fill out all the other fields to bypass checks
3. Designate dataset to be kept in PPR
4. 'Create new version' and change journal name or manuscript number (does not need to be both)
5. Examine PPR designation on Review and Submit page

**Comment by ahamelers** [comment]
We should at least draw attention to the change/give them the option to re-select PPR
