### ISSUE TITLE
Investigate addition/retention of empty <a> HTML tags

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#3008]
As long as I've been at Dryad, we occasionally see datasets come through with empty <a> tags in the Abstract, Methods, or Usage Notes. These aren't always easy to detect and show no apparent pattern (e.g., some are for entire paragraphs, others are for single words). These are normally rare, including for most of 2023, but we've been seeing an increasing incidence in the past 2–3 weeks.

Examples (more will be added later, I'll try not to fix these in datasets that I curate until Audrey's had time to look into this more):

- https://datadryad.org/stash/dataset/doi:10.5061/dryad.6t1g1jx57
- https://datadryad.org/stash/dataset/doi:10.5061/dryad.000000091

![Screen Shot 2023-12-11 at 1 37 16 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/522d0276-6e6b-4eaa-95d0-d1139f93fd70)
![Screen Shot 2023-12-11 at 1 37 02 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/b339834a-953f-45b3-9cee-5d4a3410ed47)
![Screen Shot 2023-12-11 at 1 38 06 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/5eee2b03-9c10-442b-959e-67dd254cb0bf)

**Comment by ahamelers** [comment]
I can remove these empty a tags from text pasted into these boxes.
