### ISSUE TITLE
Submission stuck in "Processing" status

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3009]
**Priority**: Medium
**Impact**: Author can resume submission process 

[Modelled past autumn leaf phenology of deciduous trees](https://datadryad.org/stash/dataset/doi:10.5061/dryad.dv41ns22k)
DOI: 10.5061/dryad.dv41ns22k

This data submission seems to be stuck in "Processing" status. The author informed us via Help Desk that he receives this error message: "You may not edit a submitted version of your dataset by using the back button. Please open your dataset from the editing link." I attempted to Force Edit but received the error message below. 

![Screenshot 2023-12-12 at 7 48 18 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/45396757-702f-4dff-8e0f-f54f0723a4f7)

![Screenshot 2023-12-12 at 7 43 42 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/bb0c7a01-7b90-46f1-9a2d-ab033bf677d0)

**Comment by ahamelers** [comment]
I will try forcing the resource state back to in progress, since this was submitted so long ago that its no longer in the queue
