### ISSUE TITLE
Investigate PPR errors for AAAS submissions

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#3015]
I have seen several submissions this week that were specifically released from PPR via API call from AAAS, as logged in the Activity Log, curated and returned to the author, and then resubmitted. Upon resubmission, the Activity Log shows that the author put the dataset back in PPR, which I thought was related to #2899, but I was lucky enough to get one of the authors to email me a screenshot after they said they definitely did not put it back into PPR and couldn't even if they wanted to because the system properly displayed the "this dataset isn't eligible for PPR because it's already been through curation." I haven't seen this in non-AAAS submissions after reviewing all datasets assigned to me that are in PPR status right now.

Known datasets this affected:

- https://datadryad.org/stash/ds_admin/activity_log/112161
- https://datadryad.org/stash/ds_admin/activity_log/119494
- https://datadryad.org/stash/ds_admin/activity_log/117313

The below screenshot is what the author of the second dataset sent me:
![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/d2a73884-1b5b-4119-a3dc-7aebf206c6b7)

**Comment by ryscher** [comment]
Dependent on #2420.

**Comment by ahamelers** [comment]
All of these are from 'default_to_ppr' journals. I think I found an issue where if a user clicks the 'Import metadata' button at any time, and that form is set to a 'default_to_ppr' journal, the setting to hold_for_peer_review will be set to true over again without any additional checks. I'm not sure if this definitely caused the issue here, but it's the only truly weird thing around setting peer_review status I've been able to find.

**Comment by bryanmgee** [comment]
@ahamelers I think this is still an issue unfortunately... See this one: https://datadryad.org/stash/ds_admin/activity_log/118115

I went into the dataset to check and it's displaying the "The private for peer review option is not available for this data submission, because the dataset has been submitted and entered curation. Upon submission, the dataset will proceed to our curation process for evaluation and publication." The author actually emailed HD because they need it back in PPR, but the system let them do it themselves
