### ISSUE TITLE
Update CEDAR 2024-1

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3018]
CEDAR has made further updates to their editor, which may fix the display of the "Click to read instructions" fields. (See email from Xiaoli on 2023-12-14)

Import a new copy of CEDAR and report back to DataCite.

**Comment by ahamelers** [comment]
I have done this update as part of #2866

Notes:

1. Instructional text now appears on the top under "About the metadata template". However, we still also see an editable "About the template" field, which I don't think is meant to be present. Similarly we now see instructions above, but still see incorrectly editable text fields for "Dataset Instruction", "Experimental Instruction", etc.
2. All the icons are now broken—Material Icons files are included in dist/assets/ after running `ng build --configuration=production` but these of course not included in the javascript file for the webcomponent. In fact, the web application tries to load everything from /assets/ and has console errors when they can't be found. We'd need to copy the assets directory over to the equivalent route, which is a big pain for our application, or put them somewhere more reasonable and manually modify the files to alter these urls. The documentation for "[Building the Webcomponent](https://github.com/metadatacenter/cedar-embeddable-editor#building-the-webcomponent)" does not mention this.

**Comment by ryscher** [comment]
For (2) above, I originally had this problem when adding the CEDAR editor. I put the MaterialUI files in the /public directory and added some redirects into the routes.rb to help the editor find them. Since these files are publicly available, it made more sense to just put them in a public directory that we could address, rather than try to include them in the asset pipeline.
