### ISSUE TITLE
Some landing pages display a duplicated affiliation for certain authors

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#3025]
As per title, we're seeing some seemingly random datasets where a matched affiliation is displayed multiple times for a single author. There's nothing in the submission form itself (e.g., a duplicated author entry row) that appears to explain this, and it occurs for only some but not all authors of a given dataset.

[Published example](https://datadryad.org/stash/dataset/doi:10.5061/dryad.sbcc2frcw)
![Screen Shot 2023-12-27 at 10 08 06 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/df79adef-016b-46f9-99ff-34850d360103)

[Unpublished example](https://datadryad.org/stash/dataset/doi:10.5061/dryad.37pvmcvqx)
![Screen Shot 2023-12-27 at 10 07 31 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/7e1def1f-c918-497e-8c0a-4998fcc627f0)

**Comment by ahamelers** [comment]
For the first example, the database has 3 affiliations for the author, all created in the same second:

|id | affiliation_id | author_id | created_at | updated_at|
|-- | -- | -- | -- | --|
|1725235 | 322 | 1208348 | 2023-11-10 5:06:35 | 2023-11-10 5:06:35|
|1725234 | 322 | 1208348 | 2023-11-10 5:06:35 | 2023-11-10 5:06:35|
|1725233 | 322 | 1208348 | 2023-11-10 5:06:35 | 2023-11-10 5:06:35|

I'll check for why duplicates are being created, put in a fix, and try to clean up the database.
