### ISSUE TITLE
Article DOI adjustments & update ROR in DataCite metadata schema

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#303]
Article DOIs are currently stored in two places:
- DataCite relation `isCitedBy`
- internal metadata `publicationDOI`

Cleanup tasks:
- [x] change all current uses of `isCitedBy` to `isSupplementTo` (see Slack conversation, https://dryad.slack.com/archives/CBTGUSKSS/p1554903947149300)
- [x] when an admin user enters or edits the `publicationDOI`, automatically create an equivalent `isSupplementTo` relation
- [x] when a submitter adds an article DOI at the top of the initial submission screen, ensure the journal name and ISSN are stored in the internal metadata

**Comment by briri** [comment]
We may want to stop storing this data in the `stash_engine_internal_data` table completely. 

The curator's are able to manually change these values on the Dataset activity log page. If they do make a change and we store the info in both tables, they would become out of sync.

We would need to update the activity log page to pull and display info from both tables if we decide to go this route. If we stick to using both tables, we will need to make sure that the tables are kept in sync as the curator makes changes.

**Comment by briri** [comment]
Update the `stash_datacite/publications_controller.rb` so that the `manage_internal_datum` method is storing the publicationDOI and the`manage_pubmed_datum` method is storing the Pubmed Id in the correct table(s).

**Comment by briri** [comment]
ROR id can be found in `dcs_affiliations.ror_id`

**Comment by briri** [comment]
Looks like our `datacite-mapping` gem doesn't support Datacite's 4.3 schema yet, so adding the ROR ids will take a bit more work than expected. See #417
