### ISSUE TITLE
Checksum validation load testing and scheduling

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3031]
- [x] on the v3 production server, run tests of the checksum validator
    - [x] @ahamelers check to make sure validation task is dependant on presence of checksums in DB
    - [x] @ahamelers add task to daily cron
    - [x] @ahamelers copy ~100 checksums to the production database from the temp table
    - [x] run the task once (make sure there's no problem with the copy query)
    - [x] @ahamelers copy ~400 more checksums to the production database from the temp table
- [x] determine whether the validator interferes with basic operation of the Dryad application
- [x] based on test results, add to crontab for existing machine OR create a ticket for a new machine

**Comment by ahamelers** [comment]
Do we need another ticket for copying out checksums to existing 'copied' status files? Or should that be part of the date-staggering rake task?

**Comment by ryscher** [comment]
Load testing is fine. However, there are differences in the checksums for some items. For example, on the production server, files failed to validate for id 21-30 (and more would have failed, but I stopped the process).

**Comment by ahamelers** [comment]
Are all the ones failing the previously existing md5 type digests? If that is the case, we could exclude those from the validation task for now, to continue the tests (and decide what to do about them later, after figuring out if the issue is in the files, the digests, or in the validator)
