### ISSUE TITLE
Zenodo now doesn't allow more than 100 files

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#3035]
Two parts:

## part 1
Communication with user of this dataset https://datadryad.org/stash/dataset/doi:10.5061/dryad.qbzkh18qq since their dataset will not go through because they have too many files.  Maybe zip them up?  Zenodo will not accept that many. identifier_id: 123743, resource_id: 271049

## part 2

Add limitation for only 100 files to go to software or supplemental in the file upload widget and give errors for more since Zenodo will error on us with that number or more now.

**Comment by sfisher** [comment]
@jleighherzog  The dataset above is one which has more than 100 files which Zenodo now doesn't support in their new system.  IDK the best way to handle, but maybe the user could zip them and submit that way or something.

**Comment by ryscher** [comment]
Part 1: the user has been contacted

Part 2: we will not address at this time, since the problem is very rare
