### ISSUE TITLE
Curation states not being set when Ryan doing API submissions

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#304]
I'm not clear why this is happening, but some curation states are not being set.  This also causes the UI to fail in the My Datasets page, I believe.  Not sure if this is a function of a bug in Ryan's submissions, something skipping setting something it shouldn't or what.

You can find these with 

```
SELECT r.id, r.`title`, rs.resource_state FROM stash_engine_resources r
LEFT JOIN stash_engine_curation_activities c
ON r.id = c.`resource_id`
JOIN stash_engine_resource_states rs
ON r.`current_resource_state_id` = rs.id
WHERE c.id IS NULL;
```

**Comment by sfisher** [comment]
This might be a transitory state while things are submitting, but we probably want to be sure all datasets have some kind of curation state to start or else go through all our code and be sure we catch exceptions for no curation state existing.

This is  the list I see of things without curation state right now from the query above.    It may change or go away later, IDK.

![Screen Shot 2019-05-10 at 1 20 51 PM](https://user-images.githubusercontent.com/105433/57554608-be4a4280-7326-11e9-8e73-901ddd74105f.png)

**Comment by ryscher** [comment]
This is a problem with the migration process for items that are in the user's workspace (have not been submitted for curation). I need to adjust the migration script to ensure these items get a state.

**Comment by ryscher** [comment]
Migration was completed long again, and the API now regularly sets the states correctly.
