### ISSUE TITLE
Add Sai Prathiba's photo and bio to Dryad's "Our Staff" page

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3043]
**Priority**: Low

**Bio:**
Sai Prathiba holds a Master's degree in Biosciences with a specialization in Biotechnology. During her role as a junior research fellow, she engaged in a clinical (interventional) study, where her involvement spanned various aspects of the project lifecycle including conducting comprehensive literature reviews, securing participants and consent, designing proforma documents, blood sample collection for biochemical analysis, rigorous statistical analysis of gathered data, and publication of findings. Beyond her professional pursuits, Sai Prathiba finds joy in culinary endeavors, gardening, and music.

**Photo:** Please crop the photo to match the size of other staff photos on [this page](https://datadryad.org/stash/about#our-staff).
![Sai Prathiba Photo](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/50a42f7e-65a8-46e0-99e3-0505ac80160d)

**Comment by ryscher** [comment]
@DragosIorgulescu Please add your own photo and bio to the page as well!

**Comment by DragosIorgulescu** [comment]
**Bio:**

Over the past ~15 years I have been involved in a series of start-ups and large-scale enterprises, ranging from training applications and cloud SAAS/IAAS platforms to medical credentialing/licensing, trading, banking, and social media. This has allowed me to work on complex and challenging projects, gaining experience with understanding product requirements and translating them into intuitive and performant solutions. Being part of both start-ups and large-scale teams meant I had to learn and work in the whole stack, from setting up the infrastructure and deployment to server and client-side integrations, writing APIs, and integrating with third-party services. When I'm not coding, I like to practice sports, travel, & disconnect.

**Photo:**

![Image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/1225100/6536e40c-002c-48fd-b562-ea8c9f3229f5)

**Comment by DragosIorgulescu** [comment]
@ahamelers Thank you! Haha, for some reason I thought this ticket was assigned to me so I can add my bio to it 🤦🏻‍♂️ I'll make the necessary edits in the codebase 👍
