### ISSUE TITLE
Robustness of ZIP downloads

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3044]
Todd Vision reported that he received an eror when trying to download the ZIP for https://doi.org/10.5061/dryad.7wm37pvvr. The error was "Network error retrieving list of presigned urls". 

Please review the process for collecting the presigned URLs to minimize chances of receiving this error, and see whether we can intercept it to give the user a more helpful response.

**Comment by ryscher** [comment]
Bryan reports that the error appears for him occasionally as well. Refreshing the page typically fixes it.

**Comment by ahamelers** [comment]
- Added a delay & retry for the URL retrieval
- Improved the error message if this still does not work
- Fixed some new problems with serviceworker operation in firefox
- Found that with current session-based security check, if a user opens a few datasets in tabs and then returns to the first one to download, it will always fail there. I changed this, now it works better in Firefox and Chrome, but _any_ number of tabs is totally broken in Safari. I think some other security method would be preferable for this.

**Comment by ahamelers** [comment]
I've switched to using standard CSRF token security for this fetch request. Not sure why that wasn't used in the first place!

**Comment by ahamelers** [comment]
I've removed the session check and switched to using standard CSRF token forgery protection for the fetch request. It doesn't seem like that should be necessary, since it's a GET request and should already be fine under a normal origin request policy, but if we need _some_ kind of security check on the request, that one seems to work much better.

**Comment by ahamelers** [comment]
I've removed the session check and switched to the more standard permissions check we use for downloads. Also removed the retry since the session/permissions check was the only reason for failure, and retrying will not solve that. Kept the improved error messages, etc.
