### ISSUE TITLE
Generate and save checksums during submission processing

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#3047]
- [x] After files are submitted, during processing, make sure there is a step to generate a checksum (using `Stash::Checksums` in /lib/stash/checksums.rb) and add it to the database for the created file.

**Comment by ryscher** [comment]
- Add checksum creation to `SubmissionJob. copy_to_permanent_store`
- In `RepoQueueState.available_in_storage`, return false unless the file model contains a checksum
