### ISSUE TITLE
Evaluate search system and prioritize fixes

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3048]
For GREI year 2, we have a commitment to create an "evaluation of our on-site search facility, with recommendations for improvement" 

Review the search system and make a proposal for the most important fixes. Many of these fixes are already documented in tickets with the label "site search". The report should include: 
- Are there any easy fixes that can be completed by Feb 29 for GREI year 2?
- Which fixes are recommended for GREI year 3?
- Which fixes will be most helpful for our users? (results from member survey or short interviews with users from our volunteer pool)

**Comment by ahamelers** [comment]
https://docs.google.com/document/d/1NC94-rm3_farA-kxmCthKFDcsaIWwA3NsExZ44W2Hm8/edit

**Comment by ryscher** [comment]
Thanks -- I added a few of the quick items for sprint 111, and the rest we can schedule for GREI year 3.
