### ISSUE TITLE
User testing plans for 2024

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3049]
In the Dryad strategic plan, we committed to doing at least the pre-design testing on the README system (done), plus a test of at least one other major feature by then end of June. We expect to increase testing in the second half of 2024.

Prepare an overview of user testing plans for 2024. The overview should answer these questions:
- Which features most urgently need to be tested?
- What type of testing is needed for each feature?
- What testing can be done with casual contacts at a conference booth?
- What testing will require interacting with our pool of volunteer testers?
- At what point in the schedule will we need extra help to run user tests?

**Comment by ryscher** [comment]
Would be nice to prioritize #2752, which is needed for GREI year 2.

**Comment by ahamelers** [comment]
https://docs.google.com/document/d/1k9Be7zduCAMtI0eJ8lyU3zC5Gwa0ly9MacOh73Lif34

**Comment by ryscher** [comment]
Great start! I'm closing this ticket even though we will continue to refine the plan over the next month.
