### ISSUE TITLE
'Edit description' button on Review and Submit page sometimes obscures keywords

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#3053]
See below:

![Screen Shot 2024-01-09 at 6 43 24 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/137443a6-63a8-4e0e-83ba-d749cd982cb5)

**Comment by ahamelers** [comment]
Apparently this button should only have appeared if there were funders or related works, but this was broken.
