### ISSUE TITLE
Add Tenant: Temple University

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#3056]
**Tenant name:** Temple University

**Logo location:**  https://library.temple.edu/assets/temple-logo-t-box-90cc3fa538df8cb198867442038a1dac87756f1e375393193f775e8760013fdf.svg

**Contacts to receive submission notices:** None

**RORs that are considered part of the tenant (including medical centers, alternate campuses, etc.)** https://ror.org/00kx1jb78, https://ror.org/04zzmzt85

**Shibboleth info, if not in [InCommon](https://incommon.org/community-organizations/):** InCommon member ; contact Chin Kim Chin [at] temple [dot] edu with any questions.

Tasks:
- [x] add config to `config/tenants`
- [x] add logo to `app/assets/images/tenants`
- [x] deploy and test on stage (institution should log in to verify working as expected)
- [x] update `tenant_id` for users in the database who have emails with the institutional domain name

**Comment by sarahklippincott** [comment]
See also: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2998

**Comment by ahamelers** [comment]
@sarahklippincott What is the payment plan for Temple (i.e., are they tiered?)

**Comment by ryscher** [comment]
University is done. Health system will be done via #2998
