### ISSUE TITLE
Complete removal of Merritt ZIP requests

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3059]
The Merritt team reports that they are still seeing a small number of requests for ZIP files. It looks like `lib/stash/download/version_presigned.rb` is still making calls to Merrit's `assemble-version`. Update this method to use the new process.

It would also be useful to remove all instances of `assemble-version` from documentation and rspec code.

**Comment by ahamelers** [comment]
I've checked and I think the only place VersionPresigned is being actively used is in the tests! I will remove it from the code entirely. There are many unused methods in the codebase, a general audit and cleanup might be a good idea in the future.
