### ISSUE TITLE
Transfer ownership of GDocs to current staff

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3072]
**Priority**: Low
**Impact**: New ownership, replacing previous Dryad staff member

Transfer ownership to Laura Bowman: 
https://docs.google.com/document/d/1i4kAcDiP6vCDCUs0V2ZRK0q-niu6i6S9Gma64ZZ8dyk/edit#heading=h.4rcutb8vgjtt

Transfer ownership to Bryan Gee: 
https://docs.google.com/document/d/1ySagMTkdK28hfeirM5c54uvym1z6Fg46nzH36Bl-XeQ/edit#heading=h.d8qtuiuibk8d
https://docs.google.com/document/d/1Sj2A2P4vJ7xXwB9AHszW_EvxunEYk2U4ZcyLB3Qf5s8/edit#heading=h.at09ue774rd8

**Comment by ryscher** [comment]
I transferred ownership of the first document to Laura.

The other documents, were created in the shared drive. Therefore, they have no "owner". Bryan is a manager of the documents and has the same power as the other managers.
