### ISSUE TITLE
Text outlines in README editor

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3079]
While editing a README, blue outlines started to appear around the content. Clicking outside of the editor window made them disappear, so I assume they are focus indicators, but it is unclear why they appeared in this distracting manner.

**Comment by bryanmgee** [comment]
@ryscher related to #3033 ?

**Comment by ryscher** [comment]
![Image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/605143/1fd4c304-3988-419a-b0c2-98b82b61bc20)

**Comment by lauradryad** [comment]
This just happens to me in every dataset regardless of <br> tags.. while using Chrome. Not sure how it's grouping things.
