### ISSUE TITLE
New Tenant: UCLA

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#309]
Shib should be good - they confirmed success

Emailing logo to whoever is handling this since I can't upload svg here.

**Comment by briri** [comment]
Setup tenant config and logo for UCLA
<img width="1232" alt="Screen Shot 2019-06-12 at 10 41 18 AM" src="https://user-images.githubusercontent.com/1204467/59373514-ae939480-8cfe-11e9-9f52-a3dad621503e.png">
