### ISSUE TITLE
Changing tabs in README editor erases changes made in RT tab

### ISSUE THREAD

**Issue by AmeliaCulpP1819** [CDL-Dryad/dryad-product-roadmap#3090]
When making changes in rich text tab of README editor, switching to markdown tab will erase changes. Making changes in RT and proceeding to overview page without opening MD tab, changes persist as expected.

This is consistent on all datasets for me, using Chrome on Mac. The same behavior was observed in curating mode and author editing mode on sandbox. Just tested with DOI: 10.7959/dryad.1rn8pk0pf on sandbox (slack me if you want to see a screen recording of the issue).

**Comment by ahamelers** [comment]
I'd noticed this myself while working on a different ticket (#3033), thanks for making a ticket!
