### ISSUE TITLE
Add Tenant: University of Oklahoma

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#3095]
**Tenant name:** University of Oklahoma

**Logo location:** https://www.dropbox.com/scl/fo/ft1o90s7zc1fa6uf25gmr/h?rlkey=ndtdx3qckrukp084nliqyglac&dl=010:21

**Contacts to receive submission notices:** N/A

**RORs that are considered part of the tenant (including medical centers, alternate campuses, etc.)** https://ror.org/02aqsxs83

**Shibboleth info, if not in [InCommon](https://incommon.org/community-organizations/):** PingFederate by PingIdentity for SAML 2.0 SSO connections. Contact Jonathan Killgore  killgore [at] ou [dot] edu with questions.

Tasks:
- [x] add config to `config/tenants`
- [x] add logo to `app/assets/images/tenants`
- [ ] deploy and test on stage (institution should log in to verify working as expected)
- [ ] update `tenant_id` for users in the database who have emails with the institutional domain name

**Comment by ahamelers** [comment]
It looks like they are in InCommon—is there some reason not to use this? https://incommon.org/community-organization/?id=0015000000IL7E8AAL

If we should not use their Shibboleth, we will need IP addresses or a unique strategy. We do not support SAML.

**Comment by ahamelers** [comment]
https://met.refeds.org/met/entity/https%253A%252F%252Fshib.ou.edu%252Fidp%252Fshibboleth/

**Comment by sarahklippincott** [comment]
In order to allow us connect via InCommon, UO have requested answers to the following:

Will the information technology be internet-accessible? Yes No

Will the information technology require multi-factor authentication? Yes No

What types of remote access are needed?

Will the information technology use SSO, Federated, or Active Directory authentication? Yes No

Will data at rest be encrypted? Yes No

Will data in motion be encrypted? Yes No

Does this service have the ability to produce a report of current and active users? Yes No Not Sure

Does this service create and retain log records when a user logs in? Yes No Not Sure

_Note, they already have the HECVAT and are requested this in addition._

**Comment by ryscher** [comment]
Will the information technology be internet-accessible? **Yes**

Will the information technology require multi-factor authentication? **No**

What types of remote access are needed? **Standard Internet access**

Will the information technology use SSO, Federated, or Active Directory authentication? **Yes**

Will data at rest be encrypted? **Yes**

Will data in motion be encrypted? **Yes**

Does this service have the ability to produce a report of current and active users? **Yes**

Does this service create and retain log records when a user logs in? **Yes -- though logs are destroyed after 60 days for privacy purposes**

**Comment by sarahklippincott** [comment]
Thanks @ryscher !
