### ISSUE TITLE
shibboleth set up on dryad-dev.cdlib.org

### ISSUE THREAD

**Issue by marisastrong** [CDL-Dryad/dryad-product-roadmap#31]
Configuration of shibboleth to work with dryad-dev.cdlib.org end point.

**Comment by marisastrong** [comment]
[  ] Update the InCommon Metadata for the Dryad Dev Service Provider endpoint
[  ] The following files are affected:
local/shibboleth-sp/etc/shibboleth/
attribute-map.xml - (dev/stg/prd will be same)
sp-key.pem - copied from dmp2-{dev/stg/prd}
sp-cert.pem - copied from dmp2-{dev/stg/prd}
shibboleth2.xml - {dev/stg/prd}
[ ] Incommon Metadata - Add the AssertionConsumerService endpoints for HTTP-POST, HTTP-Artifact and Browser/Post endpoints
[ ] Shibboleth2.xml file needs to be updated to reference the host name - see notes below for detailed edits
[ ] attribute-map.xml needs to have all required attributes that we are requesting noted at top of file.  For dryad, we are requesting displayName, eppn, and mail.
[ ] Test using PrintShibInfo.pl to ensure attributes are coming back okay

**Comment by marisastrong** [comment]
Testing using   https://dryad-dev.cdlib.org/cgi-bin/printenv to ensure attributes are coming back okay.  Placed the eds.html file in the htdocs dir under apache but nothing coming up when I hit the printenv URL.  
Incommon Metadata has been published with dryad-dev.cdlib.org endpoint.  But doesn't seem to be going to the IdP so troubleshooting this step by looking at local/shibboleth-sp/var/log files.

**Comment by marisastrong** [comment]
i saw that @sfisher put this in review.  I thought review was for when something was ready to be tested by PM - this is still being worked on I don't think it belongs in review.

**Comment by marisastrong** [comment]
https://uc3-dryad-dev.cdlib.org/eds.html?entityID=https%3A%2F%2Fdash-dev.cdlib.org%2Fshibboleth&return=https%3A%2F%2Fdryad-dev.cdlib.org%2FShibboleth.sso%2FLogin%3FSAMLDS%3D1%26target%3Dss%253Amem%253A62b65f3c38aa35bd4d0fd312600b8efacfd011e3007b6c017ce738aa46a8d908

**Comment by marisastrong** [comment]
the printenv script is still not working as expected so need to look into this.

**Comment by jimvanderveen** [comment]
I'll take a look at it

**Comment by marisastrong** [comment]
the following files have been put onto the server to support printenv

/dryad/apps/apache/htdocs/
eds.html
idpselect_config.js
idpselect.css
idpselect.js

/dryad/local/shibboleth-sp/etc/shibboleth/
attribute-map.xml
shibboleth2.xml

**Comment by marisastrong** [comment]
the eds.html file needed to be placed in htdocs, not the vhost dir
updated the ipdselect_config.js to pick up the DiscoFeed.json from Shibboleth.sso/DiscoFeed

The attributes returned are as follows:

displayName="Marisa Strong"
eppn="Marisa.Strong-ucop.edu@ucop.edu"
mail="Marisa.Strong@ucop.edu"

all is working as expected.  Not sure if @jimvanderveen needs to do anything for puppet.  I will update the Shibboleth code notes on confluence include all that is needed to get printenv working.

**Comment by jimvanderveen** [comment]
Puppet config updated accordingly.

@marisastrong I saw an error message mentioning `localDiscoFeed.json` -- I found a file by that name in the Puppet repo. Looks like we used to (?) use this for Dash. Should I install that on Dryad? Or do we just run with your DiscoFeed change?

**Comment by marisastrong** [comment]
@jimvanderveen have we updated the idpselect-config.js file in puppet?  let me know if there is any work left on your end, if not we can close out this issue.

**Comment by marisastrong** [comment]
@jimvanderveen the logo is in place (uc_logo.png) and can be included in puppet config files along with my update to the idpselect_config.js file.

also reached out to Mark Boyce downstairs to request that UCOP Idp update their metadata.  He says it's on his todo list.

**Comment by jimvanderveen** [comment]
Okay. If I have a chance tonight, I'll take care of it; otherwise, first thing tomorrow morning on the way in to Oakland.

**Comment by jimvanderveen** [comment]
@marisastrong are we waiting on Mark Boyce for that IDP metadata update, or carrying on without it?

**Comment by marisastrong** [comment]
incommon metadata was updated - delay with downstairs since there is a new online form that seems to have a slightly different workflow (notifications are no longer emailed to me when I submit changes) but all is set up and working  

https://dryad-dev.cdlib.org/cgi-bin/printenv
