### ISSUE TITLE
New API account

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#3100]
Please create an API account for daniel [dot] jacob [at] inrae [dot] fr

Daniel is developing a metadata management tool (Maggot - see our online instance: https://pmb-bordeaux.fr/maggot/ and would like to add the possibility of submitting datasets via API in the Dryad repository in the same way as Zenodo or Dataverse currently implemented.

**Comment by ryscher** [comment]
Account created and sent, with the appropriate apologies for the delay.
