### ISSUE TITLE
Admin search pages -- add total

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3111]

**Comment by ahamelers** [comment]
The total # of search results is actually already displayed!
<img width="347" alt="Screenshot 2024-01-31 at 11 33 42" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/1749394/906007fa-c51e-4a57-8b1c-c5af1b5fca69">

**Comment by ahamelers** [comment]
@ameliaculp @bryanmgee Was this suggestion actually for the admin pages?

**Comment by ahamelers** [comment]
@AmeliaCulpP1819 @bryanmgee Can you verify the origin of this suggestion?
