### ISSUE TITLE
Review VPAT for needed updates

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3116]
The most recent VPAT is available at https://dryad.slack.com/files/U02TL168UMR/F05UQMLPZH6/dryad_vpat_30january_2023_update.docx.pdf

Sarah had commented that only the contacts need to be updated, but it's worth a runthrough to determine whether anything else is out of date.

**Comment by ahamelers** [comment]
https://dryad.slack.com/files/U041YUJAUPM/F06G32B3AB1/dryad_vpat_31january2024_update.pdf

**Comment by ahamelers** [comment]
@sarahklippincott could also review this 😄
