### ISSUE TITLE
Ensure contentUrl is set appropriately for direct package downloads

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#312]
Set contentUrl for files (sending to DataCite)

-----
It seems like in Dash the contentURL is not being sent to DataCite (whether through EZID or DataCite).

We should make sure that it is set when we update all the DOIs when doing the final migration push when transforming Dash & Dryad to the New Dryad service.

**Comment by ryscher** [comment]
@sfisher Is this still relevant? I see where we are setting a distribution/contentUrl, but I see no evidence that EZID or DataCite is using it.
