### ISSUE TITLE
Updates to email distribution list for American Ornithological Society (AOS)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3133]
**Priority**: Medium (within **1 month**)
**Impact**: Email communications re-routed to appropriate contact

Please route Dryad data submission updates related to _American Ornithological Society_ to
Christie Riehl [criehl@americanornithology.org](mailto:criehl@americanornithology.org)

Remove Scott Sillett as a recipient. Scott's AOS account will be deactivated next month
ssillett@americanornithology.org

**Comment by ryscher** [comment]
done
