### ISSUE TITLE
Admin access for Proceedings of the Royal Society B editorial office contacts

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3136]
**Priority**: Medium (1-2 weeks)
**Impact**: Editorial contacts will be able to access the Dryad Admin dashboard 

Please provide this user account with rights to access _Proceedings of the Royal Society B_ datasets on the Dryad Admin site. I've provided this account with the Tenant Administrator role. The editorial office contacts will use and share this account. 

[Emilie Aime](https://datadryad.org/stash/user_admin/user_profile/664)

**Comment by ahamelers** [comment]
This account has been made an admin of this journal.
