### ISSUE TITLE
FOS browsing on v3

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3142]
On some (all?) datasets that are in v3 servers, the FOS subjects are not behaving correctly.

To reproduce:
1. Visit https://sandbox.datadryad.org/stash/dataset/doi:10.7959/dryad.xgxd254c1
2. In the keywords box, click on "Chemical sciences"
3. There are no results, even though at least the dataset that had that keyword should display.

**Comment by ryscher** [comment]
Perhaps the rake task that rebuilds the search index was never updated to include the FOS subjects?

**Comment by ahamelers** [comment]
It looks like this is actually set to exclude FOS subjects on purpose. [And it's been this way for 3 years](https://github.com/CDL-Dryad/dryad-app/blame/9d9fe7cf2df550484b59ad6b2ef4be00396cb2cf/lib/stash/indexer/indexing_resource.rb#L122C43-L122C43).

```
      def subjects
        @resource.subjects.non_fos.map { |s| s.subject&.strip }.reject(&:blank?)
      end
```

Looking at the live site, I'm seeing very similar (un)functionality, actually! Click the FOS subject from any of the datasets in search results. 😬 

Should I change this? If so, how: Should FOS subjects be re-included as subjects, or changed to be a different kind of SOLR field?
