### ISSUE TITLE
Provide curators with access to the VE

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3147]
**Priority**: Medium (1 week)
**Impact**: New curators will be able to train in and have access to the virtual environment

Provide access to: 
Savannah Butler | sbutler@datadryad.org
Kathiyayini J | kathiyayini@datadryad.org
Molly Hirst | molly@datadryad.org

**Comment by ahamelers** [comment]
All done
