### ISSUE TITLE
Admin access for Proceedings of the Royal Society B editorial office contactsv (new request)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3150]
**Priority**: Medium (1-2 weeks)
**Impact**: Editorial contacts will be able to access the Dryad Admin dashboard

Please provide this user account with rights to access Proceedings of the Royal Society B datasets on the Dryad Admin site. The editorial office contacts will use and share this account. https://datadryad.org/stash/user_admin/user_profile/107202

0009-0005-6034-466X

Also, remove admin access for this user account: https://datadryad.org/stash/user_admin/user_profile/664

**Comment by ahamelers** [comment]
Done!
