### ISSUE TITLE
Dataset stuck in processing

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3159]
Dataset 10.5061/dryad.m905qfv7h is stuck in `processing` status. This was one of the first datasets to be processed after we released the non-Merritt storage.

Resources 278470 and 278559 were processed correctly by the new storage system. Why did 278560 fail to complete?

**Comment by ryscher** [comment]
Files had processed correctly (no updates needed, since they were not changed in this version). For some reason, the step in `repo_queue_state.rb` that registers the resource as "harvested" had not completed properly.

Not sure of the exact cause. It's something to keep an eye on.

**Comment by AmeliaCulpP1819** [comment]
10.5061/dryad.2v6wwpzr1 stuck in processing after curator edits, may be a related issue. Error message was displayed on browser tab after submitting.

**Comment by lauradryad** [comment]
I believe the same thing just happened to me with this dataset: DOI: 10.5061/dryad.gmsbcc2v0

**Comment by ryscher** [comment]
Every time this occurs, there are no new data files; the dataset is simply being versioned for metadata. Find places this could cause the process to fail.

**Comment by ryscher** [comment]
Note that #3180 is related, but appears to have been a different issue.

**Comment by lauradryad** [comment]
Another one stuck in processing after a curator edit; author is trying to use the PPR link, but cannot [10.5061/dryad.3n5tb2rr2](https://datadryad.org/stash/ds_admin/activity_log/125038?)
