### ISSUE TITLE
Dataset PPR link not working

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#3161]
The author of [this dataset](https://datadryad.org/stash/ds_admin?q=%2210.5061%2Fdryad.69p8cz991%22&sort=relevance&commit=Search&tenant=&editor_id=&curation_status=&publication_name=&sponsor_org=&utf8=%E2%9C%93) emailed HD saying that the PPR link doesn't work for their dataset; it returns this error message:

![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/4bf0fa89-3b4a-4057-b8f7-bf31c76f278b)

When I try this in incognito mode on Firefox, it displays the message that it doesn't allow the automatic download but does allow me to download the files. When I/Laura try this on Chrome and Safari, we get the same error as the author. I tested a few other PPR links and did not have issues with them in Chrome. The Activity Log is rather vanilla with nothing of note other than perhaps that the author has updated it a few times today (always in PPR).

**Comment by ahamelers** [comment]
It looks like an issue with retrieving the presigned URL for one (or more) of the files. Possibly due to a mix of old and new storage methods?

```
A NoMethodError occurred in downloads#zip_assembly_info:

  undefined method `[]' for nil:NilClass
  app/models/stash_engine/resource.rb:439:in `merritt_ark'
```

**Comment by ahamelers** [comment]
It is in fact not just a zip download error, but an error with retrieving the README file specifically, which was copied from an earlier version: https://datadryad.org/stash/downloads/file_stream/2918499

**Comment by bryanmgee** [comment]
@ahamelers can I get you to look at this briefly and let me know whether it's related? We had an author email about [this published dataset](https://datadryad.org/stash/dataset/doi:10.5061/dryad.mp4jt67):

> When I try to download the full dataset or open the version file of August 26th, the download is immediately canceled and the link to the version file returns a broken site.
> 
> Is this a problem in the Dryad website or may it be a problem in my computer? I have tried to download the file both in Google Chrome and with Microsoft Edge, but both these browsers returned the same problem.

I tried the following:

- Firefox when logged into Admin Site, no issues via 'Download Dataset' button
- Firefox in incognito mode, 'Download Dataset' button is missing??? but I can download it fine by clicking on the file
- Chrome in incognito mode, same issue as user, download does not initiate

Can make into a new ticket if not related.

**Comment by ahamelers** [comment]
> Firefox in incognito mode, 'Download Dataset' button is missing??? but I can download it fine by clicking on the file

This will always be the case, it's a specific aspect of Firefox's incognito mode that the tech the download runs on will not work (service workers)

> Chrome in incognito mode, same issue as user, download does not initiate

This is very strange, it does seem to be a problem on Chrome only, for this specific file. You can see the issue just trying to download the file. No idea why it's only on Chrome,or what it is about this file (could it be the spaces in the filename?) but this is a different issue and needs its own ticket. The issue in this case (unlike the one in this existing ticket, which shows a ruby/rails error) seems to be on the AWS side: `dryad-assetstore-merritt-west.s3.us-west-2.amazonaws.com sent an invalid response.` `Failed to load response data: No data found for resource with given identifier`

**Comment by lauradryad** [comment]
@ahamelers got another HD email saying that an author could not download the README specifically and then when they tried to the Download Data button, it stalls out. I was able to download using the button on Chrome, but I did get the error when I tried to just download the README (it says Not Found). Is this related to this one?

DOI: https://doi.org/10.5061/dryad.zcrjdfnkw

**Comment by ryscher** [comment]
Closing this ticket, as the main issue is fixed by https://github.com/CDL-Dryad/dryad-app/pull/1529

Moving https://doi.org/10.5061/dryad.mp4jt67 to a separate ticket
