### ISSUE TITLE
Report for Wiley: dataset subject areas over time

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3162]
**Priority**: Low (3-4 weeks)
**Impact**: Wiley would like data on subject areas associated with dataset submissions over time. This will help them determine other journals that they might target for conversations; interested to know where there's growth

Possible to pull a report that contains the following fields (_not_ restricted to Wiley titles): 
- Journal name
- Publisher (?)
- Research domain
- Jan 2020-Feb 2024
- Submitted date
- Publication date
- Subject keywords (useful or too specific?)
- 
@mariaguerreiro : Anything else to add or clarify?

**Comment by mariaguerreiro** [comment]
This is great, thank you, @jleighherzog I would concur that we could drop keywords if that is challenging to obtain.

**Comment by mariaguerreiro** [comment]
@ryscher Wiley chased me about this data. Can you get me an estimate date of delivery? Many thanks!

**Comment by mariaguerreiro** [comment]
@ryscher An update to say that I sent disciplinary data from Dimensions to Wiley and they're good, so we no longer need this report. cc @jleighherzog 
Thank you!
