### ISSUE TITLE
CEDAR on v3 Review page

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3167]
Sarah reports that, on the v3 servers, when a CEDAR metadata file is created, it cannot be downloaded from the Review page of the submission system.

(I didn't test this issue on the v2 servers, so it may exist there as well.)

**Comment by ahamelers** [comment]
@ryscher Is this related to #3161? The README and CEDAR file are saved in the same way; has something gone wrong with that?

**Comment by ryscher** [comment]
Both the README and CEDAR files download correctly from the dataset landing page. In the submission system, the README link on the Review page goes back to the README editor (which is nice). The CEDAR link on the Review page doesn't work.

**Comment by ahamelers** [comment]
As far as I am aware this is working as intended. You also cannot download the README from the Review page, as these files are not created until submission. Both the README and DisciplineSpecificMetadata file list links link back to the pages where the content for these can be edited.
