### ISSUE TITLE
7zip uploads

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3173]
For dataset doi:10.5061/dryad.2fqz612x7, resource 278786, the user uploaded a 7zip file (Datasets_P2.7z). However, in the temporary S3 storage, there was also a ZIP file with the same base filename that does not appear in our `generic_files` table. Was this ZIP created automatically?

The files caused problems, because the recorded file size in `generic_files` was incorrect -- possibly the size of the ZIP got recorded for the 7zip entry??? With the mismatch, the dataset would not enter "submitted" status.

I verified that the 7zip file is intact, and can be uncompressed correctly.

Since it was an initial upload, I corrected the file size in the database and let the dataset complete processing, but I would like to get Audrey's opinion before closing this ticket.

**Comment by ahamelers** [comment]
I can't find anything in our code, or in searching the AWS docs and various message boards, that would indicate the automatic generation of a zip copy of a 7z file. 

- Did the zip size actually match the bad size value for the 7z?
- Is it possible the user uploaded and removed a zip file with the same name as the 7z? And then there was some issue with the removal (like the file was removed from our table, but not from AWS)?
- Is there any way at all that this issue can be recreated (did you save a copy of the 7z and zip files?)
- I doubt the user remembers what they did _exactly_, but if they do, or if we could verify at least my "did you upload a similarly named zip file at some point" theory, that would be helpful
