### ISSUE TITLE
Investigate "Download error" for dataset

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3174]
**Priority**: Medium-High
**Impact**: Error impacting datasets in multiple statuses

1) We're receiving a 'Download error' for [this](https://datadryad.org/stash/dataset/doi:10.5061/dryad.8sf7m0cwb) dataset when the option to "Download full dataset" is selected.

From Kailasha: "I tried to re-upload the specific files that caused the download error. At first, it was for the Matlab code file and then it was for the parameter data file. Now I'm again getting an error for the m code file."

Once fixed, can proceed to publish dataset. 

![Screenshot 2024-02-19 at 10 30 05 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/af637dda-8af2-4d44-b8c9-7e69c97c7b77)

2) Unable to download files using the sharing URL
Title: Rapid measurement and statistical ranking of leaf drought tolerance capacity in cotton
DOI: 10.5061/dryad.59zw3r2gb
Receiving the same error message as above.

**Comment by Savannahbutler** [comment]
Adding additional dataset that is also showing this download error:
DOI: 10.5061/dryad.47d7wm3m0
Title: Density data for Lake Erie benthic invertebrate assemblages from 1930 to 2019.
Attempting to download individual files throws this error message: "We're sorry, but something went wrong."

**Comment by Savannahbutler** [comment]
And DOI: 10.5061/dryad.41ns1rnnc (Title: "Data for: Biomechanical adaptations enable phoretic mite species to occupy distinct spatial niches on host burying beetles"). Am able to download individual files on this case

**Comment by kailashap** [comment]
Adding one more dataset to this issue:
DOI: 10.5061/dryad.931zcrjm7
Dataset title: Data from: Combinatorial expression of gamma-protocadherins regulates synaptic connectivity in the mouse neocortex

**Comment by kailashap** [comment]
Adding another dataset related to this issue:
DOI: 10.5061/dryad.41ns1rnmv
Dataset title: Data from: the flashy escape: support for dynamic flash colouration as anti-predator defence

**Comment by ahamelers** [comment]
Possibly the same as #3169 —Is this in Chrome only, like that one? (Do the downloads work in firefox?)

**Comment by ahamelers** [comment]
Others in the comments sound like the same issue as #3161

**Comment by kailashap** [comment]
Adding one more dataset related to this issue:
DOI: 10.5061/dryad.nvx0k6f01
Dataset title: How are the impacts of multiple anthropogenic drivers considered in marine ecosystem service research? A systematic literature review (once resolved we can publish this dataset)

**Comment by ryscher** [comment]
I believe this is related to https://github.com/CDL-Dryad/dryad-app/pull/1524 -- I'm going to "hot fix" this on the server and see if the issue clears up.

**Comment by ryscher** [comment]
Applied additional fix https://github.com/CDL-Dryad/dryad-app/pull/1529 -- all datasets mentioned in this ticket are now working.
