### ISSUE TITLE
Dataset stuck in "Processing" status (DOI: 10.5061/dryad.9zw3r22m8)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3178]
Priority: High
Impact: Dataset can proceed to curation and publication; article publication depends on a live DOI for this dataset

Please investigate this submission which is stuck in "Processing" status. 
I was unable to use the Force Edit feature to gain access to editing mode.

**Comment by ryscher** [comment]
fixed
