### ISSUE TITLE
Database backup system

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#318]
As we saw in the Zenodo failure, it is important to be able to recover the database quickly in the event of an error.

We should make frequent database backups (every 30 minutes, or better yet every 10 minutes). The frequent backups should be retained for 24 hours.

We should also have daily/weekly backups, which are retained for longer time periods.

**Comment by briri** [comment]
- check with Debra on RDS backup frequency
- setup CRON to dump DB every 30 minutes

**Comment by ryscher** [comment]
CRON entries for the existing Dryad system:

# Export database for backup purposes
PGPORT=5432
PGUSER=dryad_app
PGDATABASE=dryad_repo
DRYAD_DB_HOST=prod-db-hostname.rds.amazonaws.com
0,30 * * * * /home/ubuntu/dryad-utils/database-export.sh -q > /dev/null 2>&1

# Export daily backup to dryad-backup at AWS
15 8 * * * /home/ubuntu/dryad-utils/aws-tools/backup-sql-solr.sh > /dev/null 2>&1

**Comment by ryscher** [comment]
The scripts mentioned in the cron entries above can be found in https://github.com/datadryad/dryad-utils/
