### ISSUE TITLE
Two datasets stuck in "Processing" status

### ISSUE THREAD

**Issue by Savannahbutler** [CDL-Dryad/dryad-product-roadmap#3180]
Two of my datasets have been stuck in the Processing status for several days, upon author resubmission. 

DOI: 10.5061/dryad.0vt4b8h5z (Title: "Plant species richness, not hygrothermal stress, is the main predictor of gall-inducing insect richness in Peruvian Amazon forests")

DOI: 10.5061/dryad.pg4f4qrx3 (Title: "Dung beetles increase plant growth: a meta-analysis")

**Comment by lauradryad** [comment]
I believe I have another one for this ticket (stuck in processing after author made edits and submitted) 10.5061/dryad.83bk3j9t1 

Author said he got this screenshot when he hit "resume" (and says he did not use the back button) 
![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/124197995/c84c0350-65cf-4d35-943e-66bec14957b9)

**Comment by Savannahbutler** [comment]
@ryscher my dataset 10.5061/dryad.0vt4b8h5z is stuck in processing again, following my curation edits.

**Comment by ryscher** [comment]
I fixed the datasets mentioned in this ticket. I developed a process to identify others with this problem, and fixed those as well. The next deploy may fix the problem, but we keep this ticket open until we can verify...

To see resources stuck in processing, in Rails console:
```
rr=StashEngine::Resource.where("updated_at > '2024-02-01'")
rr.each do |r|
	puts "#{r.id}" if r.resource_states.last.resource_state == "processing"
end;nil
```
