### ISSUE TITLE
Dataset stuck in "Processing" (DOI: 10.5061/dryad.70rxwdc4m)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3183]
**Priority**: Medium (by end of day on Friday)
**Impact**: The journal requested that this dataset be publicly available

Please publish this submission. It's currently stuck in "Processing"
Curators are unable to Force Edit to change the status

[Data from: Differential involvement of the senses in disgust memories](https://datadryad.org/stash/dataset/doi:10.5061/dryad.70rxwdc4m)
DOI: 10.5061/dryad.70rxwdc4m

**Comment by ryscher** [comment]
fixed
