### ISSUE TITLE
Off board - US Fish and Wildlife.

### ISSUE THREAD

**Issue by DonnaOkubo** [CDL-Dryad/dryad-product-roadmap#3197]
US Fish and Wildlife is no longer a member as of 2/29/24

Please do the following:
1.  Take them off the drop down member menu
2.  Take them off the website
3.  Please let curator  know they are no longer members.

**Comment by ryscher** [comment]
- Removed subscription settings from their 2 journals
- Updated tenant files to remove institutional payment plan
- Noted the unpublished datasets for discussion in next dev/curator meeting.

**Comment by mariaguerreiro** [comment]
Thank you, @ryscher !
