### ISSUE TITLE
Investigate Stripe Payment

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#32]
I've asked Melissanne and Elizabeth to figure out what their needs are for Stripe invoicing and create an account. Once the account credentials are created we can hook it up to our system.

Stripe account set up by Elizabeth.

Our need for Stripe:
I need Stripe to be triggered to invoice a submitter when a data submission is approved by the curation team, if there is no fee waiver or sponsorship for the DPC. If a payment fails, I need Stripe to email the submitter with instructions for updating their payment information. When a payment is made, I need Stripe to send the researcher a customized receipt.

**Comment by marisastrong** [comment]
what are the requirements that we need to meet for payment?  what does current system do and what do we want to ensure is met for things that don't work in the current system?

**Comment by dlowenberg** [comment]
This ticket is for investigating how Stripe can integrate into a system. We do not need to base this on what Paypal currently does in the old system. In the new system, Stripe will be through email and triggered when a dataset is published (post curation, could be months after submission). Elizabeth will be handling the invoicing & reporting.
