### ISSUE TITLE
Provide member access to Dryad Admin site (CDN)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3204]
**Priority**: High
**Impact:** Member contact will have access to Dryad Admin site

Provide [Judy Hum-Delaney](https://datadryad.org/stash/user_admin?q=Judy+Hum-Delaney&tenant_id=&commit=Search) [Canadian Science Publishing] with access to these journal titles on the Dryad Admin site:

- FACETS
- Arctic Science
- Drone Systems and Applications
- Canadian Journal of Fisheries and Aquatic Sciences

**Comment by ahamelers** [comment]
"Drone Systems and Applications" isn't currently in our journal database

**Comment by ahamelers** [comment]
I have added the admin permissions for the other 3

**Comment by ahamelers** [comment]
Aha, I see in #3187 I need to add this other journal

**Comment by ahamelers** [comment]
The journal and organization have been added and this user is an admin
