### ISSUE TITLE
Place dataset in PPR status (DOI: 10.5061/dryad.wpzgmsbvq)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3205]
Priority: High
Impact: Dataset will be in PPR status supporting the double-blind peer review process the journal follows

Utilizing 360° photography and virtual reality to analyze forest habitat structure following a major hurricane
10.5061/dryad.wpzgmsbvq

**Comment by ryscher** [comment]
Moved into PPR, removed Zenodo and Datacite entries.
