### ISSUE TITLE
Checksum duplication

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3208]
Many recent files contain the same checksum in the database, `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`. It appears that there is some logic that is storing the wrong checksum. 

When fixed, close Salesforce case #00031581

**Comment by ahamelers** [comment]
Out of curiosity I googled this hash, and it looks like it's the hash for an empty file! It must be a download/timing issue.

**Comment by ahamelers** [comment]
The issue creating the problem should be fixed in the linked PR, but database cleanup will also need to be done, probably with a task. We're over 9000 file entries now which is a lot to fix manually.
