### ISSUE TITLE
Investigate "Upload error" (DOI: 10.5061/dryad.6wwpzgn5z)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3209]
This dataset has a status = "Upload Error" 
I'm unable to access the submission via Force Edit feature. 
Can you investigate to determine what the issue might be? 

[High-content high-resolution microscopy and deep learning assisted analysis reveals host and bacterial heterogeneity during Shigella infection.](https://datadryad.org/stash/dataset/doi:10.5061/dryad.6wwpzgn5z)
10.5061/dryad.6wwpzgn5z

From the author: 

> When I pressed submitted I saw that my dataset on Friday has been "processing" since then.
> 
> I was wondering a few things, please:
>       - First, I was hoping I could access the dataset at any time to update it. I realised that one of the datasets I intended to upload is actually not there.
>       - Second, I provided the DOI above in a manuscript that I submitted to Elife on friday. If the manuscript goes for peer review they will post the manuscript in a pre-print service (bioRxiv). For the editorial process and peer review process I would need the data to be accessible as soon as possible, please.

**Comment by Savannahbutler** [comment]
adding DOI: 10.5061/dryad.1jwstqk18 here with similar "Upload error" showing under status

**Comment by jleighherzog** [comment]
Another instance: 

[High-content high-resolution microscopy and deep learning assisted analysis reveals host and bacterial heterogeneity during Shigella infection.](https://datadryad.org/stash/dataset/doi:10.5061/dryad.6wwpzgn5z)
DOI: 10.5061/dryad.6wwpzgn5z

**Comment by ahamelers** [comment]
These have been reprocessed successfully
