### ISSUE TITLE
Expose a domain name for the migration server

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#321]
The migration server needs to be accessible for @ryscher's migration scripts to run against it.  It doesn't particularly matter what it is called.

- [ ] If keeping it as `uc3-dryadui-stg-2c.cdlib.org` is accessible to @ryscher then it is ok.
- [x] Otherwise obtain a domain name (something like `dryad-migration.cdlib.org`).
- [x] Obtain and install any certificates needed so that we can access it.

**Comment by jimvanderveen** [comment]
Opened CDLSYS ISSUE=12961 for CNAME, SSL certs, and verifying access for Ryan via ssh and http/s

**Comment by jimvanderveen** [comment]
@ryscher , can you test your access to https://dryad-migration.cdlib.org/stash

**Comment by jimvanderveen** [comment]
I think this is done, but I haven't heard anything from @ryscher re testing. Okay to close this ticket @sfisher ?

**Comment by sfisher** [comment]
I believe this should work for him as long as any server names are added to his sshuttle startup script and the firewall rules allow him through still.

I think we can consider this done and re-open a new ticket if a problem arises.

**Comment by jimvanderveen** [comment]
Okay, closing.

**Comment by ryscher** [comment]
Sorry... somehow I missed the comment yesterday. Yes, I have access to it. Thanks!
