### ISSUE TITLE
Unable to submit dataset, missing required field (DOI: 10.5061/dryad.1dp8r8s)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3214]
I think this submission was imported and I'm unable to move it to submitted status because the submitting author's email isn't registering. I've tried inserting the same email into every field but—no luck. 

[Data from: Serum triglycerides in Alzheimer’s disease: Relation to neuroimaging and CSF biomarkers](https://datadryad.org/stash/dataset/doi:10.5061/dryad.1dp8r8s)
DOI: 10.5061/dryad.1dp8r8s

I currently have this in editing mode because no checkpoints for submission have been created. 

<img width="1090" alt="Screenshot 2024-03-11 at 8 32 03 AM" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/96851e53-972f-4dc5-be94-fbe020dead4a">

**Comment by ahamelers** [comment]
Hi Jess, this seems to be because the submitting author's user account is not associated with an ORCID. The current check for this validation requires the owner of the resource to have an ORCID. 

@ryscher should we change the validation settings for this or perform some other solution?

**Comment by ryscher** [comment]
I updated the user account with the most likely ORCID -- see if you can submit it now.
