### ISSUE TITLE
Apache, puppet changes & startup scripts for migration server

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#322]
The migration server needs to be able to be managed and have access to the web application through apache. I believe we'll call the Rails environment `migration` instead of stage.

- [x] Branch current Puppet config to save work on high-avail config.
- [x] Puppet scripts to install whatever needs to be installed on the server.
  - [x] Apache config and start so that it has correct domain name and points at the correct passenger reverse proxy.
  - [x] Passenger start/stop.
  - [x] Set correct Rails environment in Puppet
- [ ] Any nagios or whatever things are standard for our servers.
- [ ] Add startup scripts, test via reboot

**Comment by jimvanderveen** [comment]
For migration, we will not have shibboleth running, correct? So I will only start apache and passenger upon reboot at this time.

**Comment by sfisher** [comment]
That is correct.  We don't need shibboleth (or SOLR) working for the migration instance in order to migrate data.
