### ISSUE TITLE
Submission repeatedly failing processing

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#3220]
10.5061/dryad.3ffbg79rm is repeatedly in processing for over 24 hours and then erroring out because of this extensive time spent in processing. All of the associated files seem to have been transferred to permanent storage successfully; it is unclear why processing is not completing.

**Comment by ryscher** [comment]
Please try determine what processing is actually happening. If all processes are really completed, you can force completion by:
1. In a console, run `StashEngine.repository.harvested(resource: r)`
2. Delete the RepoQueueStates that reference this resource

**Comment by ahamelers** [comment]
There was in fact a file error here—some discrepancy between file name and file size (one file had a different 'original' file name, which matched a different file, and the file size in the table also matched other file and not the actual file, somehow). I got the files from AWS and reuploaded them and it processed successfully.
