### ISSUE TITLE
Fix "Upload Error" (DOI: 10.5061/dryad.1dp8r8s)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3221]
[Data from: Serum triglycerides in Alzheimer’s disease: Relation to neuroimaging and CSF biomarkers](https://datadryad.org/stash/dataset/doi:10.5061/dryad.1dp8r8s)
DOI: 10.5061/dryad.1dp8r8s

I'm working to get this submission back in "Submitted" status.

**Comment by jleighherzog** [comment]
Can we prioritize this one please?

**Comment by ahamelers** [comment]
This is a weird one—this has a file set to upload via URL, but the URL provided is one of our own presigned URLs, which has of course timed out. The URL is also for an object that is in glacier storage. Is there some other copy of the file that can be provided?

**Comment by ahamelers** [comment]
We've started the file restore from deep storage, which can take up to 12 hours

**Comment by ryscher** [comment]
This very old file never made it into permenant storage. It was in PPR in the old DSpace system and then withdrawn since it was presumed abandoned. We will attempt to load it from our old Glacier archive of the things that were in Dryad v1 prior to the migration into (v2) Merritt.

**Comment by ahamelers** [comment]
I updated the file URL so it was successfully loaded, and the submission is now "Submitted".
