### ISSUE TITLE
PRIORITY: Unable to select "Published" to make datasets public

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3222]
When "Published" is selected from the drop-down menu, and "Submit" is selected to confirm the decision, the "Submit" button doesn't respond. The window sits open without action. There have been a few instances reported today. 

Curators will post examples here: 
- 10.5061/dryad.bk3j9kdjk

**Comment by ahamelers** [comment]
This is due to DataCite being down—we are unable to send the notice to DataCite to update the DOI to be publicly accessible, and thus the publication fails.

**Comment by jleighherzog** [comment]
I'm able to publish datasets again. Will close this ticket.
