### ISSUE TITLE
Change dataset ownership (10.5061/dryad.x95x69prq)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3228]
Please change ownership of this dataset:

DOI: 10.5061/dryad.x95x69prq
Title: Data from: Investigation of heterotrophs reveals new insights in dinoflagellate evolution

...to:

Elizabeth Cooney
0000-0001-7435-7609

**Comment by ahamelers** [comment]
Done
