### ISSUE TITLE
Provide GitHub access to curators, Molly Hirst and Kailasha Purushothaman

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3231]
**Priority**: Medium (2-3 weeks)
**Impact**: See below

Please provide GitHub access to Molly and Kailasha with access and permissions to submit GitHub tickets and route them appropriately for action.

- Molly will help manage Helpdesk, so offering her the permissions to submit and edit tickets is useful to ensure efficient submission for fixes and tracking of issues.
- Kailasha will be able to submit tickets for issues that her team experiences outside of US business hours. 

If possible, it would be great to provide access within 2-3 weeks.

**Comment by jleighherzog** [comment]
@ryscher : Ah, of course. I forgot about that step.

**Comment by jleighherzog** [comment]
@ryscher
Molly = mahirst 
Kailasha = kailashap

**Comment by ryscher** [comment]
Invites sent.
