### ISSUE TITLE
Improve automatic ROR matching

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#3244]
**Problem description, and links to relevant helpdesk tickets:**

ROR matching for import metadata is bad/wrong

**Describe the solution you'd like:**

See #3004 for improvements made to normal search

**Additional context:**

@mahirst @lauradryad Please give examples if possible!

**Comment by mahirst** [comment]
https://doi.org/10.5061/dryad.jh9w0vtk5

**Comment by ahamelers** [comment]
> https://doi.org/10.5061/dryad.jh9w0vtk5

I'm not sure how to fix this one on import. Some of these are departments in institutions, for which I would say we could search for just the last thing after the comma, however I think some are listing _multiple_ affiliations (i.e., "State Key Laboratory for Mineral Deposits Research" and "School of Earth Sciences and Engineering, Nanjing University" are two different affiliations). I think this may still require a human to check for now, since it's not always clear programmatically where such affiliations should be divided up to search each component part

**Comment by ahamelers** [comment]
In addition to doing exact name lookups, affiliation lookups from importing metadata will now also look for matches in a ROR org's aliases and acronyms (case insensitive). If you could please continue to track annoying match misses, we can make additional tickets.
