### ISSUE TITLE
Dataset stuck in "Processing" (DOI: 10.5061/dryad.51c59zwgh)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3250]
This submission is stuck in 'Processing' please set to 'Submitted' status. 

[Data from: Direct synthesis, characterization, in vitro and in silico studies of simple chalcones as potential antimicrobial and antileishmanial agents](https://datadryad.org/stash/dataset/doi:10.5061/dryad.51c59zwgh)
DOI: 10.5061/dryad.51c59zwgh

**Comment by ahamelers** [comment]
We did not retry any errored datasets yesterday. We are moving the database to the new servers currently and will retry any datasets that need it after that is complete.

**Comment by kailashap** [comment]
Following are some of the datasets that are also stuck in 'Processing'

DOI: **10.5061/dryad.9zw3r22p2**
Title: Data from: preserved appendages in a Silurian binodicope: implications for the evolutionary history of ostracod crustaceans
Status: Please set 'Processing' to 'Submitted' status.

DOI: **10.5061/dryad.r4xgxd2mf**
Title: Data from: Early-life variation in migration is subject to strong fluctuating survival selection in a partially migratory bird
Status: Please set 'Processing' to 'Submitted' status.

DOI: **10.5061/dryad.1g1jwsv46**
Title: Data from: Optimal sampling interval for characterisation of the circadian rhythm of body temperature in homeothermic animals using periodogram and cosinor analysis
Status: Please set 'Processing' to 'Action Required' status.

DOI: **10.5061/dryad.dr7sqvb42**
Title: Data from: strawberry guava invasion of a Hawaiian rainforest: changing population pattern
Status: Please set 'Processing' to 'Submitted' status.

DOI: **10.5061/dryad.ghx3ffbwj**
Title: All babies in southeast Sweden: Neurodevelopment and early life factors
Status: Please set 'Processing' to 'Submitted' status.

DOI: **10.5061/dryad.bg79cnpjg**
Title: Vibrating aggression: Spider males perform an unusual assessment strategy during contest displays
Status: Please set 'Processing' to 'Action Required' status.

DOI: **10.5061/dryad.5mkkwh7dh**
Title: CABO Canopy-Level Spectra from Forest Sites
Status: Please set 'Processing' to 'Action Required' status.

DOI: **10.5061/dryad.5qfttdzdx**
Title: Fecal standing crop with real time correction using scat detection dogs to estimate population density
Status: Please set 'Processing' to 'Submitted' status.

DOI: **10.5061/dryad.3bk3j9ksh**
Title: Data from: evolution of wing shape in geometrid moths: phylogenetic effects dominate over ecology
Status: Please set 'Processing' to 'Action Required' status.

DOI: **10.5061/dryad.hmgqnk9rc**
Title: Data from: Factors affecting temporal use of feeding sites by wolves in the central Apennines, Italy
Status: Please set 'Processing' to 'Submitted' status.

DOI: **10.5061/dryad.fqz612k12**
Title: Data from: Dietary partitioning among three cryptobentic reef fish mesopredators revealed by visual analysis, metabarcoding of gut content, and stable isotope analysis
Status: Please set 'Processing' to 'Submitted' status.

**Comment by ahamelers** [comment]
We are aware of all datasets in the processing status. There are delays because scheduled jobs were turned off for the release.

**Comment by ryscher** [comment]
Most of these datasets are processed now, but the one that started the ticket still needs some attention.
