### ISSUE TITLE
Dataset in "Processing" status (DOI: 10.5061/dryad.b2rbnzspm)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3262]
Direct observational evidence of strong CO2 uptake in the Southern Ocean
10.5061/dryad.b2rbnzspm

https://datadryad.org/stash/dataset/doi:10.5061/dryad.b2rbnzspm

**Comment by lauradryad** [comment]
This one is also stuck in processing (10.5061/dryad.wwpzgmsrb) [Early, typical, and late talkers: an exploratory study on predictors of language development in the first two years of life](https://datadryad.org/stash/dataset/doi:10.5061/dryad.wwpzgmsrb)

**Comment by ahamelers** [comment]
These are listed in the curation activities as not having been submitted and as "in progress". I'm not sure why we have a 'processing' repository state for them—I hope we didn't lose any data during the database switch over. I've set them back to in progress for editing and submission

**Comment by ahamelers** [comment]
I logged into the old CDL database and double checked, and there was no indication these had been submitted in the curation activities there, either. No longer concerned about data loss.
