### ISSUE TITLE
DOI URL doesn't work for dataset 10.5061/dryad.xsj3tx9ms

### ISSUE THREAD

**Issue by lauradryad** [CDL-Dryad/dryad-product-roadmap#3264]
This dataset was published, but the DOI does not work. https://datadryad.org/stash/dataset/doi:10.5061/dryad.xsj3tx9ms

I believe it may need to be resent to DataCite? It was published on March 28.

**Comment by kailashap** [comment]
Similar issue with this dataset [10.5061/dryad.280gb5mwd](https://datadryad.org/stash/dataset/doi:10.5061/dryad.280gb5mwd).

**Comment by ahamelers** [comment]
Neither of these are in DataCite. Both were created in 2023 (June and November, respectively). I'm looking to see if there is an easy way to find and send missing DOIs to DataCite, but may need to wait for Ryan to look into this.

**Comment by ryscher** [comment]
See [https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/server_maintenance/troubleshooting.md#updating-datacite-metadata](instructions for updating DataCite)

**Comment by ahamelers** [comment]
Thanks Ryan, I will resend these 2. Not sure if there are any others affected. Maybe we need a 3rd task to check for things that are missing, and just send those?

**Comment by ahamelers** [comment]
The mistakenly published DOI from #3263 (10.5061/dryad.hmgqnk9rc) is also not appearing when searching our datacite account

**Comment by ahamelers** [comment]
We decided to resend all published dataset DOIs to be on the safe side, so I'm doing that as well

**Comment by EvangelineJanani** [comment]
This dataset was published, but the DOI does not work: https://doi.org/doi:10.5061/dryad.5qfttdzdx

**Comment by ahamelers** [comment]
There is another open ticket for these: #3267 

We are resubmitted the DOIs of all published datasets to DataCite, which takes a while. It's about half done.
