### ISSUE TITLE
Dataset in "Upload Error" status (DOI: 10.5061/dryad.02v6wwqb2)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3266]
[Uncovering microstructural architecture from histology](https://datadryad.org/stash/dataset/doi:10.5061/dryad.02v6wwqb2)
DOI: 10.5061/dryad.02v6wwqb2

**Comment by ahamelers** [comment]
This and a few other datasets are showing a `The specified key does not exist. (Aws::S3::Errors::NoSuchKey)` error when the system attempts to copy them to permanent storage

**Comment by jleighherzog** [comment]
Possible to prioritize this one? Maybe it's already scheduled for action.

**Comment by jleighherzog** [comment]
@ahamelers : Is there an update I can offer to the authors?
