### ISSUE TITLE
Published datasets DOI link isn't resolving

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3267]
[Neglected patterns of variation in transgenerational plasticity: The importance of different sources of environmental variation differs across ages and sexes in a cyprinid fish](https://datadryad.org/stash/dataset/doi:10.5061/dryad.1jwstqk2w)
DOI: 10.5061/dryad.1jwstqk2w

[Processed data for the analysis of human mobility changes from COVID-19 lockdown on bird occupancy in North Carolina, USA](https://datadryad.org/stash/dataset/doi:10.5061/dryad.gb5mkkwxr)
DOI: 10.5061/dryad.gb5mkkwxr

[Leaf fluctuating asymmetry is not a reliable indicator of stress](https://datadryad.org/stash/dataset/doi:10.5061/dryad.547d7wmgk)
DOI: 10.5061/dryad.547d7wmgk

[Data from: Quantifying the impact of internal variability on the CESM2 control algorithm for stratospheric aerosol injection dataset](https://datadryad.org/stash/dataset/doi:10.5061/dryad.66t1g1k7v)
DOI: 10.5061/dryad.66t1g1k7v

I attempted to access the datasets via an incognito window and also received an error.

**Comment by ahamelers** [comment]
I've also opened #3265 to re-send smaller sets of stuff to DataCite, so we'll hopefully be able to resolve similar issues faster in the future

**Comment by mahirst** [comment]
Hey Audrey, thanks for the responses. Do we have a timeline for when this might be resolved? And would you like us to continue sending DOI links for incoming HD queries about this issue?

**Comment by mahirst** [comment]
Adding this one; DOI links to Dryad homepage: 

DOI: 10.7280/D1NH6N

https://datadryad.org/stash/dataset/doi:10.7280/D1NH6N

"How syllabi relate to outcomes in higher education: An evaluation of syllabi learner-centeredness and grade inequities in STEM"

**Comment by mahirst** [comment]
A few more:
[Behavioral discrimination and olfactory bulb encoding of odor plume intermittency](https://datadryad.org/stash/dataset/doi:10.5061/dryad.crjdfn387)
DOI: 10.5061/dryad.crjdfn387

[Data From: Dietary restriction extends lifespan across different temperatures in the fly](https://datadryad.org/stash/dataset/doi:10.5061/dryad.fttdz091j)
DOI: 10.5061/dryad.fttdz091j

**Comment by lauradryad** [comment]
doi: 10.5061/dryad.cnp5hqcbh

**Comment by ahamelers** [comment]
The big DOI resend is complete and everything that existed in our system at the time that started now works. I will send the 2 newest (10.5061/dryad.qnk98sfkp, 10.5061/dryad.8cz8w9gzh) separately.

**Comment by mahirst** [comment]
Here's a resource ID for a dataset with DOI not working: 286997

Do you want us to continue submitting these here or in #3265?

**Comment by lauradryad** [comment]
Another resource ID that's not working yet: 286891

**Comment by ahamelers** [comment]
Both resent!
