### ISSUE TITLE
Some DOIs are not successfully arriving at DataCite

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#3278]
**Bug description:**

Some DOIs for published datasets are not successfully making it to DataCite on first attempt (#3267). [Resending using some task or method](https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/server_maintenance/troubleshooting.md#updating-datacite-metadata) makes them immediately appear.

**Steps to reproduce:**

Unknown

**Expected behavior:**

DOIs should successfully send, or should have automatic retry attempts until successful. Has there been some change to the DataCite API we don't know about? Is there some initial error or warning message from the DataCite API we're missing?

- [x] Check existing code for any problems or improvements

**Comment by ryscher** [comment]
Also consider adding a button to the Activity log, which would allow a superuser to force resending of the DOI metadata.

**Comment by ahamelers** [comment]
It looks like we already have things in place to ensure we know about any DOI—we actually were not sending these 🤦 . I'm sure we could handle any failures more gracefully. Currently we just don't allow the dataset to complete the move to 'published' and show an error—maybe we need something like a publication queue, with automatic retries, to take the work or monitoring and retrying off the curators. But this second point is no longer urgent and can move to another ticket with a much lower priority!
