### ISSUE TITLE
Dataset stuck in "processing"

### ISSUE THREAD

**Issue by mahirst** [CDL-Dryad/dryad-product-roadmap#3286]
[Below-ground root nutrient-acquisition strategies are more sensitive to long-term grazing than above-ground leaf traits across a soil nutrient gradient](https://datadryad.org/stash/dataset/doi:10.5061/dryad.1zcrjdg0w)
DOI: 10.5061/dryad.1zcrjdg0w
Resource ID: 287070
SF32584

I've been working with the author to access their dataset. However, their dataset is stuck in "processing" and they cannot access it. I tried forcibly editing the dataset, but that didn't work either. Any help is appreciated!

**Comment by ahamelers** [comment]
This is fixed! Sorry it took so long, got lost in my email
