### ISSUE TITLE
Permanently delete files uploaded to "in progress" dataset 10.5061/dryad.3bk3j9kt4

### ISSUE THREAD

**Issue by lauradryad** [CDL-Dryad/dryad-product-roadmap#3287]
Author uploaded all their files individually, but now realizes they can upload compressed archives and would prefer that. They apparently uploaded over 900 files so would like them deleted on our end so they don't have to do it manually. Please let me know when this is completed!

https://datadryad.org/stash/dataset/doi:10.5061/dryad.3bk3j9kt4

**Comment by ahamelers** [comment]
This is done! The user had an in progress second version, so I didn't remove the files from verison 1, so you will still see a record as an admin of the 800 or whatever deleted files. 😬 Sorry about that
