### ISSUE TITLE
Dataset stuck in "Processing" status (DOI: 10.5061/dryad.3bk3j9kt0)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#3291]
[Climate and habitat type interact to influence contemporary dispersal potential in Prairie Smoke (Geum triflorum)](https://datadryad.org/stash/dataset/doi:10.5061/dryad.3bk3j9kt0)
DOI: 10.5061/dryad.3bk3j9kt0

I edited the submission and attempted to rebuild it with my edits incorporated but, it became stuck "Processing"

**Comment by mahirst** [comment]
[Insights from a 31-year study demonstrate an inverse correlation between recreational activities and red deer fecundity, with bodyweight as a mediator](https://datadryad.org/stash/dataset/doi:10.5061/dryad.0rxwdbs7t)
DOI: 10.5061/dryad.0rxwdbs7t
Resource ID: 285586

Author requested that I forcibly edit the dataset, but I cannot. Error message says "You may not create a new version of the dataset until processing completes or any errors are resolved"
