### ISSUE TITLE
Dataset stuck "In Progress" with error message to check that files have uploaded

### ISSUE THREAD

**Issue by lauradryad** [CDL-Dryad/dryad-product-roadmap#3293]
I put a dataset (10.5061/dryad.v9s4mw73n) into AAR on April 2, but when the author went in to edit it, they noted that it said I was editing the dataset. I checked the activity log which says this:
![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/124197995/c4702f2d-a440-4050-bc87-6afabf47b2e3)
but I did not go into this dataset on a Sunday evening. 

When I did go in to edit the dataset to put it back into AAR, I get this warning that I cannot bypass:
![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/124197995/e51b2c1c-1ea1-4f5b-b5ab-daafd6bec611)

I have not seen this warning before, so I'm not sure how to get around it, or why the system thought I was editing the dataset on April 8 at all.

**Comment by ahamelers** [comment]
@lauradryad I have no idea why this happened. My first thought was maybe *I* messed something up in the database (I was deleting those 804 generic files from that other dataset and maybe I went crazy!) but I can't see any evidence of that. I'm just going to delete that in progress version, and verify the user_id is not yours!

**Comment by ahamelers** [comment]
(Usually that error is if some file is in the database but didn't make it to storage, or the fact that it made it to storage didn't make it to the database)
