### ISSUE TITLE
Status dashboard for internal/external services

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#332]
Create a status dashboard that collects together information about the status of various parts of Dryad. Although some of this is covered by Nagios and other tools, there is nothing that currently collects together all of the services we need.

It would be useful to make this public so curators or anyone can quickly verify that things are working. For an example, see [Amazon's status page](https://status.aws.amazon.com/).

Internal services:
- Apache
- Passenger
- SOLR
- Database
- Stash-notifier
- Journal Module

External services:
- Merritt OAI server
- Merritt file download
- Datacite
- Stripe
- ROR
- Crossref
- ORCID
- EventData

**Comment by ryscher** [comment]
Is this related to #195?

**Comment by briri** [comment]
Some screenshots of the new dependency status dashboard:

<img width="1210" alt="Screen Shot 2019-06-07 at 12 11 58 PM" src="https://user-images.githubusercontent.com/1204467/59127889-921de380-891d-11e9-93ba-021ddaa9b412.png">

Example of troubleshooting dialog (triggered by user clicking on red icon next to 'Solr'):
<img width="1220" alt="Screen Shot 2019-06-07 at 12 11 01 PM" src="https://user-images.githubusercontent.com/1204467/59127923-a9f56780-891d-11e9-93b3-c00db7341859.png">

**Comment by briri** [comment]
Added logic in that will email the admins when the system detects a dependency that is offline:
<img width="636" alt="Screen Shot 2019-06-10 at 10 17 59 AM" src="https://user-images.githubusercontent.com/1204467/59213173-1d3ee980-8b69-11e9-85f8-69b2573718ae.png">
