### ISSUE TITLE
Add Cron job for LinkOut (pre-production release)

### ISSUE THREAD

**Issue by briri** [CDL-Dryad/dryad-product-roadmap#339]
We need to add a Cron job to one of the production servers that will generate the LinkOut XML files and transfer them over to the FTP servers. The output should probably be piped to a log.

`bundle exec rake link_out:publish`

We should also run a test of the actual FTP logic first, and make sure that files are being appropriately broken up when they get too large.

**Comment by jimvanderveen** [comment]
Will this initially be run with `RAILS_ENV=migration` on the dryad-migration server, uc3-dryadui-stg-2c?

**Comment by briri** [comment]
I don't think so @jimvanderveen, but I'll let @ryscher weigh in. I think the migrated data will not need these jobs run since they'll already be in the appropriate curation statuses, etc.
