### ISSUE TITLE
Up the uc3-dryadui-stg-2c.cdlib.org (migration) server to 4 GB RAM

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#343]
It looks like this is still 2 GB (same as our dev server when it crashed on us doing migration tests).

I think we want to up this to 4 GB before we start doing serious migration.

You can work with @briri and @ryscher when you need to take it down to up the memory.  They can also let you know when they'll start putting real data through migration, so far it's only test data.

**Comment by jimvanderveen** [comment]
Opened CDLSYS ISSUE=12974 yesterday for this. I'll coordinate the upgrade with Dryad teams once IAS is ready to proceed.

**Comment by jimvanderveen** [comment]
Upgrade completed earlier today.
