### ISSUE TITLE
Allow researchers to self select Private for Peer Review

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#347]
Add section before Agree to Terms with the following text:

**Enable Private for Peer Review (in blue ribbon)**
Text:  By choosing this option, your dataset will be private during your related articles peer review period. You will have access to a private dataset download URL to be shared with collaborators or the journal. Your dataset will not enter curation or be published. Because we may not have the status of your related article, the default for this period is six months. Please email help@datadryad.org or uncheck this box at any point if your dataset is ready to enter curation. 
Checkbox: Keep my dataset private while my related article is in peer review

--
Then we put into that status which triggers that email re-iterating the information (this work is already done)

- Move it to “Submitted” six months from the day. - Lift and move to “Submitted” if box is unchecked by author or a curator.

**Comment by briri** [comment]
What is the workflow after they user checks this box and initially submits their dataset? Is the intention that they would go back in and uncheck it on the review page or would we prefer for them to be able to do that on the 'My Datasets' page?

**Comment by dlowenberg** [comment]
After they check the box it puts the dataset into "Private for Peer Review" the dataset should go into that status (followed by that status email) and sit in darkness. This status should be lifted and the dataset should enter "Submitted" if a) the journal tells us the article is accepted (this is a ticket Ryan has in the backlog), b) if the check box is unchecked, or c) if it has been six months from the date submitted initially.

By doing it this way we can allow for the researcher themselves to go in and uncheck the box without emailing help desk, or they could email us saying their related article is ready and a curator can uncheck the box. The six month thing is so that we don't keep a backlog of many datasets and authors who forgot to tell us about it. No need for them to access checkbox from My Datasets page, they would go back to the third page of data submission and click submit again (a curator or researcher) to uncheck.
