### ISSUE TITLE
Paging/filtering on admin screen

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#350]
When viewing the admin screen, it would be nice to see more than 10 items at a time. The URL contains a page_size parameter, but changing it does not change the number of items displayed.

**Comment by briri** [comment]
I also think we should consider pre-filtering the statuses on initial page load so that curators don't see datasets that they cannot act upon (e.g. In Progress). Once all of the data has been migrated this page may start to load very slowly.

**Comment by ryscher** [comment]
Also, ask the curators what is the most useful initial sort order. Currently, it is by title, which seems to be one of the least useful options.

**Comment by ryscher** [comment]
The entire page has been revamped since this ticket was created.
