### ISSUE TITLE
Capistrano deploy for Stage/Migration servers not compiling assets

### ISSUE THREAD

**Issue by briri** [CDL-Dryad/dryad-product-roadmap#354]
The most recent tag, v0.3.18, had some CSS and JS changes. After running our normal Capistrano deploy to stage and migration, we found that it was not picking up the changed CSS and JS. 

Both of the updated files were in `app/assets/[stylesheets/javascripts]/stash_engine/ui.[css/js]` but the `public/assets/[stylesheets/javascripts]` dir on the server did not have any recent versions of the minified and fingerprinted files.

I had to manually run `cd /dryad/apps/ui/current && bundle exec rake assets:precompile` on both the stage and migration servers after running the Capistrano deploy. 

We should look at the Capistrano deploy and make sure its compiling assets for stage/migration/production

**Comment by ryscher** [comment]
Scott reports that this was fixed a few months ago.
