### ISSUE TITLE
Verify Apache Balancer settings with Jim

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#357]
Our current settings for Dash are these.  We should verify these on the new servers.  I think some of the rewrite flags were important and according to the note, the longer timeout was needed for larger file uploads to Merritt.  So we should validate that uploads still work ok with the shorter timeout if we have one.

```
RewriteRule ^/(.*)$ balancer://passenger_cluster%{REQUEST_URI} [P,QSA,L]

<Proxy balancer://passenger_cluster>
      # See https://www.pivotaltracker.com/n/projects/1291624/stories/135348781
      BalancerMember http://uc3-dash2-prd.cdlib.org:3000 max=1 acquire=1 timeout=600 Keepalive=On
  </Proxy>
```

**Comment by jimvanderveen** [comment]
We had to bump up `acquire` to get the load balancer to work. (The setting on Dash is 1 *millisecond*). We changed it to 500 on Dryad (which is using application load balancer in front of the web server).

I have raised the timeout to 600 seconds on the Dryad migration server.

**Comment by jimvanderveen** [comment]
Here are the comments from discussion I had with Brian Riley and Mark Reyes re the problems we were having in May with the application load balancer/high availability config:

```
    # 2019-05-07, Jim: 600 seconds is too long for timeout, especially for testing.
    # 2019-05-08, Jim: Testing some suggestions that Mark, Brian, and I came up with.
    # 1. Change fqdn to localhost for the balancer, to remove DNS lookup. No improvement.
    # 2. Acquire is max milliseconds to wait for server?!? Let's try 500 ms, rather than 1!
    # 3. Remove max threads, or at least increase it.
    # 4. Remove Keepalive, not needed since no firewalls between backend services.
    BalancerMember http://localhost:3000 acquire=500 timeout=600
```
