### ISSUE TITLE
Better Merritt-Sword submission error logging of their errors

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#358]
**Email the Merritt-Sword body for http error statuses in addition to our stack trace.  Also probably smart to log this to our submission logs table, also.**

Ryan suggested this for helping to ease our troubleshooting and it's been something that has annoyed me for a while, too.

Background info:

It is pretty hard to find the exact error returned to us by Merritt-Sword when we submit an item without searching through the UI server logs.  It usually has a longer trace of the error in our logs at about the timestamp when the error was sent.

#792 is probably a duplicate

**Comment by ryscher** [comment]
Sword is no longer in use
