### ISSUE TITLE
DOI renaming and re-routing

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#369]
https://github.com/CDL-Dryad/dryad-product-roadmap/wiki/Migration

Dryad classic uses /resource/\<doi\> as its landing page.  New Dryad needs to accept /resource/\<doi\> links and either also display the dataset landing page at that URL or else redirect to /stash/dataset/\<doi\> from that path.

Dryad also has "file" and "version" DOIs.  I assume these also resolve from the /resource/\<doi\> path, @ryscher ?  These seem to be variations on the same DOIs like shown at http://wiki.datadryad.org/DOI_Usage .

If that is the case then we also need to detect /resource/\<doi-with-suffix\> for the file and version ones and show or redirect to /stash/dataset/\<doi\>, also.

-----
If we can show/redirect all above then the following is unnecessary before launch: "The file-level DOIs and version level DOIs need to be updated at DataCite to use /resource/<doi> links ahead of release."

**Comment by ryscher** [comment]
Yes, file and version numbers should resolve from /resource. All of these details can easily be handled by truncating the DOI at the first period after "dryad.", as in:

/resource/doi:10.5061/dryad.abc123.3/2.1  --> /resource/doi:10.5061/dryad.abc123
