### ISSUE TITLE
Retain Apache access logs

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#370]
(not critical for MVP) 

Dryad is periodically asked to generate reports about usage that the system was not inherently designed to collect. Often, these reports can be obtained by processing the access logs from Apache. Therefore, we have been keeping our historical access logs for many years.

Current logs are in S3, dryad-logs/var-log-httpd-dryad

The new Dryad system should also upload the access logs to S3 on a regular basis.

**Comment by sfisher** [comment]
We may have to be careful what we keep and how long because of privacy concerns.  I know CDL has a policy of keeping for only 60 days because of this.  Not sure if Dryad has a privacy policy or how it might affect keeping logs for a long time.

**Comment by mstrong-admin** [comment]
My understanding is that we are following[ Dryad's privacy policy ](https://www.cdlib.org/about/privacy.html) but I do want to check with IAS since the application is running on CDL servers so not sure if we need to abide by [CDL Privacy Policy ](https://www.cdlib.org/about/privacy.html)

**Comment by jimvanderveen** [comment]
The main reason we need to drop the logs after 60 days is IP addresses, which is (afaik) the only personally identifiable information in the logs.

**Comment by ryscher** [comment]
At standup, we discussed that retaining the logs is probably not essential given the new functionality we are building for institutions. Melissanne independently confirmed this. So I am closing the ticket as no longer relevant.
