### ISSUE TITLE
Prepare existing Dryad server for its post-release role

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#372]
Related #330 

After release, the existing Dryad production server will continue to serve two major functions:
1)  journal-related functions, including processing manuscript metadata from journals and storing the settings related to each journal.
2) as a store of historical metadata that staff can reference when investigating issues in the new system

Preparations will include:
- create a new DNS name, and use this name in new-Dryad configs
- document how to disable logins for all but superusers
- document how to display a notice for users to visit the new Dryad page
- evaluate crontab and mark functions that will not be needed after release
- edit config on dspace to point to production dash server
- edit config on dash to point to production dspace server
- edit configs (both dspace and dash) to point to correct API locations https://docs.google.com/spreadsheets/d/19AtAAzay3eUG2awI1i-pgGSi06HrG2azefgTojVYaIU/edit#gid=0
- anything else?

**Comment by marisastrong** [comment]
We met with IAS today to discuss DNS management; @ryscher will manage DNS for all the datadryad endpoints including this one noted here.  
CDLSYS ticket 12891

**Comment by ryscher** [comment]
Some notes for launch day...

Disable logins:
update eperson set can_log_in=false;

Enable superuser logins:
update eperson set can_log_in=true where eperson_id in (select eperson_id from epersongroup2eperson where eperson_group_id=8);
