### ISSUE TITLE
Determine how to access old APIs after production release

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#379]
We need to determine how to provide access to the "old" APIs after release. Some of these APIs will still need to be accessed by third parties, until those third parties can update their systems to use the new APIs.

The various APIs that exist are listed in https://docs.google.com/spreadsheets/d/19AtAAzay3eUG2awI1i-pgGSi06HrG2azefgTojVYaIU/edit?usp=sharing

Most of these could be managed by using Apache redirects or proxies that send the various endpoints to the appropriate servers. However, we need to resolve the overlap between old and new systems that both use the endpoint "/api". Technically the old APIs use "/api/v1", and the new ones don't have a version yet, so we could detect the difference. Since the old "/api" system is only used by us and PLOS, it may be better to only provide this API on a particular subdomain (e.g., api.datadryad.org).

**Comment by sfisher** [comment]
Changing our api path to something like /apiv1, /api_v1 or /api/v1 is (though this last overlaps with exiting one) is fine with me.  I think we do want to change before release with a version somewhere, so we can release a newer or non-backwards compatible one in the future (and run them side by side or eventually deprecate an old one as needed).

**Comment by sfisher** [comment]
Marisa mentioned we should keep the existing Dryad classic API as v1 and call the new one v2.  I think she's probably right so people don't get confused between the two and they have distinct versions.

Probably we just maintain the "internal use only" things where they are? IDK if this is feasible.

**Comment by ryscher** [comment]
The spreadsheet has been updated with plans for transitioning the APIs.
https://docs.google.com/spreadsheets/d/19AtAAzay3eUG2awI1i-pgGSi06HrG2azefgTojVYaIU/edit?usp=sharing
