### ISSUE TITLE
Set up config for redirecting old Dash campus domains to datadryad.org (but not deploy it until day of).

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#381]
I believe these two rewrite rules will do the trick on the old domains and we really don't need much else.  Needs to be both in 18880 and 18443 sections of vhost configs.

```
RewriteRule "^/stash/dataset/((doi|DOI):\S+)" "https://dryad-dev.cdlib.org/stash/dataset/$1" [R=301,NE,L]
RewriteRule "^(.*)$" "https://dryad-dev.cdlib.org/stash" [L,R=301]
```

dash.berkeley.edu
dash.library.ucsc.edu
dash.lib.uci.edu
dash.ucdavis.edu
dash.ucmerced.edu
dash.ucop.edu
dash.ucpress.edu
dash.ucr.edu
dash.ucsb.edu
datashare.ucsf.edu
ocdp.lib.uci.edu
oneshare.cdlib.org

**Comment by marisastrong** [comment]
@marisastrong will  ask IAS if we can use the ias iascommonhost to perform the redirect for the Dash campus URLs

**Comment by sfisher** [comment]
@marisastrong These are the domain names to be redirected and are currently set up in our dash vhost files.  We would like them to redirect to the same path on the datadryad.org server as they are going to on the dash server (especially important for landing pages for datasets with paths like **\/stash\/dataset\/\<doi>**, this means that for anyone who linked directly to something instead of using a DOI like they should have then the links will still work.

dash.berkeley.edu
dash.cdlib.org
dash.library.ucsc.edu
dash.lib.uci.edu
dash.ucdavis.edu
dash.ucmerced.edu
dash.ucop.edu
dash.ucpress.edu
dash.ucr.edu
dash.ucsb.edu
datashare.ucsf.edu
ocdp.lib.uci.edu
oneshare.cdlib.org

**Comment by mreyescdl** [comment]
@sfisher 
How would you like me to proceed?  Should I start with dev or stage?

Puppet overwrote your UCB test on dev.  Can you recreate them and I can use that as a template?  Thanks

**Comment by sfisher** [comment]
Hi Mark.  I can try to clean it up some more since I just dropped those lines in and I think we want to get rid of all the extra cruft.

I'll try something in a few minutes.

**Comment by sfisher** [comment]
Here you go, Mark.  I took out a bunch that I thought we didn't need.  I think we probably still need the certs and other stuff to support SSL.  You'll see the two lines I mention above in there.  If you can compact it more then great.

[vhost-dash-dev.berkeley.edu.conf.zip](https://github.com/CDL-Dryad/dryad-product-roadmap/files/3557583/vhost-dash-dev.berkeley.edu.conf.zip)


Really all it's doing is redirecing the landing page (like https://dash-dev.berkeley.edu/stash/dataset/doi:10.5061/dryad.3bc76 or http://dash-dev.berkeley.edu/stash/dataset/doi:10.5061/dryad.3bc76 ) to the same path on dryad.  Everything else coming in is going to the homepage which is at /stash on dryad.

The current URLs it's redirecting to are for testing (dryad-dev.cdlib.org).   In the real production files the domain name would always be datadryad.org and we wouldn't put these redirects in place until we released.

**Comment by mreyescdl** [comment]
Okay, all the redirects should be in place expect for dash-dev.ucop.edu and dash-dev.cdlib.org

Can you verify the following...

dash-dev.berkeley.edu
dash-dev.ucdavis.edu
dash-dev.ucpress.edu
dev.dash.ucsb.edu
oneshare-dev.cdlib.org

**Comment by marisastrong** [comment]
i tried them all and they all worked as expected.  redirected to https://dryad-dev.cdlib.org/stash

marisa

________________________________

**Comment by sfisher** [comment]
Thanks Mark. I tested all these with both http and https and also a dataset landing page like "/stash/dataset/doi:10.5061/dryad.3bc76" for each of the domains.  It's all great.
