### ISSUE TITLE
Manage notifier and MDC stats under *frequency* cron scripts

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#389]
Brian added a few frequencies of cron since we have a lot of crons now.  Lets move some existing crons into this framework so we don't have to have Mark or Jim's replacement manage so many things and we have more control of our app's behavior.

May also need to look at how they log and use the same logging naming scheme/rotation as he sets up.

I think should be a relatively small item.

- [x] Before running scripts combine daily logs from each server.
- [x] Run reports (don't send to Datacite until in production).

**Comment by briri** [comment]
Just noting the corresponding pivotal ticket that discusses the crontab and log rotation request:
https://www.pivotaltracker.com/n/projects/2157590/stories/165710280
