### ISSUE TITLE
Configure production servers

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#399]
Be sure UI application is installed on both (MR)
SOLR installation (MR)

- [x] Install schema for SOLR (SF)
- [x] Configure shibboleth for datadryad.org and for dryadx2-prd.cdlib.org (MS)
- [x] Ensure any Cron jobs  special scripts are installed (SF)
- [x] Configure application for ORCID
- [x] Contact ORCID to have them add application call back URL
- [x] Schedule Crons (MR) **
- [x] Set up ORCID on prod

Info below is about what each script does and is mostly just to remember and be sure they're ok to run.

cron scripts to schedule 
- [x] Every 5 minutes
  - rake status_dashboard:check
  - stash-notifier  (It's ok to run this on the new system, but it may find item from Dash and the other way around which it will fail to update because they don't exist in the other system.)
- [x] Every 30 minutes
  - rake dev_ops:backup
- [x] daily
  - rake identifiers:publish_datasets
  - rake identifiers:embargo_datasets
  - rake identifiers:expire_peer_review
  - MDC script to combine logs and submit to DataCite (this isn't configured to submit yet)
- [x] weekly
  - rake link_out:publish
  - rake publication_updater:crossref

**https://www.pivotaltracker.com/n/projects/2157590

**Comment by marisastrong** [comment]
InCommon has asked for a TXT record to verfiy ownership of domain.  Requesting from IAS and then @ryscher can produce what is needed to send to InCommon.

DATADRYAD.ORG<http://datadryad.org/>

We require verification that your organization controls this domain. This authorization may be achieved as follows:

1. Create a new TXT record in DNS for the domain listed above:
Host: _incommon.DATADRYAD.ORG<http://incommon.datadryad.org/>
Type: TXT
Value: incommon-dcv=BOoAqgkXvasFL7hmjGoB

**Comment by marisastrong** [comment]
@sfisher do we need an endpoint for dryad.cdlib.org?

**Comment by marisastrong** [comment]
https://ucop.box.com/v/DryadLinux2-Env - this diagram outlines the production environment.  so looks like it's dryadx2-prd.cdlib.org.

**Comment by sfisher** [comment]
Thanks Marisa,

We decided we were fine without the shorter "vanity" domain name for pre-production dryad.

We're sticking with https://dryadx2-prd.cdlib.org for now since that is what Mark set up.  And of course it will eventually become datadryad.org when we release.
