### ISSUE TITLE
UI & SOLR/Harvester Servers for Dryad/Dash

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#4]
We need servers set up and they may involve a number of things.  Development environment will be most time-critical to get into a basic useful state.

- Things installed on them from puppet scripts, which might include the following
- Shibboleth Service Provider
- Certificates for ssl/https
- Apache/configs
- Ruby
- Some basic Linux libraries like mysql and a few other things (I hope these are in puppet)
- Crons
- Any external shibboleth shenanigans to get logins working for the servers such as registering the domains
- I'm sure there is more, Marisa and Jim, help me fill out this list

**Comment by jimvanderveen** [comment]
IAS will want the hostnames to be `uc3-*-dev`. Should I just use e.g. uc3-dryadui-dev, uc3-dryadsolr-dev?

To get the https certificates, I will need to know what we want for the external name. I am assuming that the dev UI (http/https) should be accessible, to simplify access for Ryan and Daisie.

I'll let IAS know that Daisie and Ryan will also need access to both the ui and solr servers via ssh.

**Comment by jimvanderveen** [comment]
Can we put the new dryad database on our dash2 DB server, or should I requisition a new database server for this?

**Comment by marisastrong** [comment]
decided on dryad-dev.cdlib.org

**Comment by jimvanderveen** [comment]
Notes from stand-up:
cname for dev will dryad-dev.cdlib.org -- this will be the only vhost/domain name initially
we will try using the same database server, if IAS can make that happen

**Comment by sfisher** [comment]
Hi Jim.  I'm getting the following error when trying to deploy to the new server:

```Running autoreconf for libffi
/apps/dryad/apps/ui/shared/bundle/ruby/2.4.0/gems/ffi-1.9.21/ext/ffi_c/libffi/autogen.sh:
line 2: exec: autoreconf: not found
make: ***
["/apps/dryad/apps/ui/shared/bundle/ruby/2.4.0/gems/ffi-1.9.21/ext/ffi_c/libffi-x86_64-linux"/.libs/libffi_convenience.a]
Error 127

make failed, exit code 2

Gem files will remain installed in
/apps/dryad/apps/ui/shared/bundle/ruby/2.4.0/gems/ffi-1.9.21 for inspection.
Results logged to
/apps/dryad/apps/ui/shared/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0-static/ffi-1.9.21/gem_make.out

An error occurred while installing ffi (1.9.21), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.21' --source 'https://rubygems.org/'`
succeeds before bundling.```

According to what I get when googling it says it means the "autoconf" package needs to be installed on the server in order to make it run (though it does say autoreconf) in the message.

Maybe you can work with Brian to see if you can get this resolved so the deploy works and the application will run.

**Comment by jimvanderveen** [comment]
I've added `autoconf` to the Puppet config and run the config manually. Any way for me to test that this resolves the issue?

**Comment by sfisher** [comment]
Thank you, Jim.  This is what I get trying to install that ffi gem manually on the server.  Now it looks like some problem with aclocal.  You can try to figure out missing libraries and test if the gem will install with the command in the first line below.

```dryad@uc3-dryad-dev:~$ gem install ffi -v '1.9.21'
Fetching: ffi-1.9.21.gem (100%)
Building native extensions. This could take a while...
ERROR:  Error installing ffi:
	ERROR: Failed to build gem native extension.

    current directory: /apps/dryad/local/lib/ruby/gems/2.4.0/gems/ffi-1.9.21/ext/ffi_c
/apps/dryad/local/bin/ruby -r ./siteconf20180723-23942-z8l7q1.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for shlwapi.h... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
creating extconf.h
creating Makefile

current directory: /apps/dryad/local/lib/ruby/gems/2.4.0/gems/ffi-1.9.21/ext/ffi_c
make "DESTDIR=" clean

current directory: /apps/dryad/local/lib/ruby/gems/2.4.0/gems/ffi-1.9.21/ext/ffi_c
make "DESTDIR="
Running autoreconf for libffi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4 --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
make: *** ["/apps/dryad/local/lib/ruby/gems/2.4.0/gems/ffi-1.9.21/ext/ffi_c/libffi-x86_64-linux"/.libs/libffi_convenience.a] Error 1

make failed, exit code 2

Gem files will remain installed in /apps/dryad/local/lib/ruby/gems/2.4.0/gems/ffi-1.9.21 for inspection.
Results logged to /apps/dryad/local/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0-static/ffi-1.9.21/gem_make.out```

**Comment by jimvanderveen** [comment]
Thanks for the test command, @sfisher ! That'll make it much easier to chase down.

**Comment by jimvanderveen** [comment]
No such package `aclocal`, but a quick thing to find with yum:

```
[ Mon Jul 23, 20:47 jvanderv@uc3-dryad-dev:~/test-puppet/git-puppet-uc3 ]
$ sudo yum provides aclocal
Loaded plugins: priorities, update-motd, upgrade-helper
1045 packages excluded due to repository priority protections
amzn-main/latest/filelists_db                                                                                | 5.7 MB  00:00:00     
amzn-updates/latest/filelists_db                                                                             | 1.7 MB  00:00:00     
epel/x86_64/filelists                                                                                        | 7.3 MB  00:00:00     
automake-1.13.4-3.15.amzn1.noarch : A GNU tool for automatically creating Makefiles
Repo        : amzn-main
Matched from:
Filename    : /usr/bin/aclocal
```

So those are installed, but I'm getting a new error now. Looks like the build wants libtool, so I'll take a look at this in the morning:

```
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
(snip)
configure.ac:41: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:7636: error: possibly undefined macro: AC_PROG_LD
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by briri** [comment]
Hey Jim,


It sounds like you're on the right track. I did some Googling and found others with the same issue on both Ubuntu and OSX.


For OSX they needed to install: automake autoconf libtool


For Ubuntu: libffi-dev


Here's the thread: https://github.com/ffi/ffi/issues/611

[https://avatars0.githubusercontent.com/u/32728518?s=400&v=4]<https://github.com/ffi/ffi/issues/611>

ffi (1.9.21) instalation fails in linux · Issue #611 · ffi ...<https://github.com/ffi/ffi/issues/611>
github.com
Hi Team, When I run bundle install I am getting following error due to that our execution is completely blocked . Please take a look and provide me a solution ASAP.



________________________________

**Comment by jimvanderveen** [comment]
```
[ Tue Jul 24, 09:01 dryad@uc3-dryad-dev:~ ]
$ gem install ffi -v '1.9.21'
Building native extensions. This could take a while...
Successfully installed ffi-1.9.21
Parsing documentation for ffi-1.9.21
Installing ri documentation for ffi-1.9.21
Done installing documentation for ffi after 25 seconds
1 gem installed
```

I've added these dependencies to our Puppet config.

**Comment by sfisher** [comment]
Yay.  Thank you, Jim.
