### ISSUE TITLE
Testing of some scenarios we expect we might have problems with

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#403]
To test the load balancing:
- Take down a server, keep one server up
- Download a dataset (especially a large one)
- Test the "migrate your data" option to be sure it still works.

**Comment by sfisher** [comment]
I tested the ALB by stopping Apache on one server at a time.  The results are that we get a "502 Bad Gateway" error for about 60 seconds before the ALB decides the server is gone and begins directing all requests to the remaining server.  It works well and 60 seconds downtime is quite good, IMO.

I also tested shutting down passenger (the rails server which is behind apache).  In this case the ALB doesn't pick up that the server is gone and we get a 503 status from Apache which can't connect to passenger and it never goes away.

Perhaps we can have apache return a different status for this case that will trigger the ALB to fail over and take one server out of rotation.
