### ISSUE TITLE
DOI registration issues on development server

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#406]
Finish testing to determine exactly when these issues occur; message DataCite to get a resolution.

**Comment by ryscher** [comment]
This issue is now corrected -- we had to register new DOI prefixes for testing purposes. See https://github.com/cdlib/dryad-config/pull/51

**Comment by briri** [comment]
awesome! thanks @ryscher 👍

**Comment by sfisher** [comment]
Wow, that's awesome that it's fixed.  Thank you for sorting through all of this, @ryscher .  I was worried it might involve some code rewrite (which isn't the end of the world, but I'd rather spend the time on other things).
