### ISSUE TITLE
curation popup doesn't work or pop up on some items

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#419]
I submitted an item viewable under https://dryad-dev.cdlib.org/stash/ds_admin?utf8=%E2%9C%93&q=bed+rat&commit=Search and the curation lightbox popup doesn't work.

Maybe it is not escaping javascript or some other problem in the javascript that creates the dialog.  Look for the dataset "Blah cat: bed rat, I can't work, I can't work"

**Comment by briri** [comment]
That's a `remote: true` link, so its likely logging an issue in the app log.

**Comment by sfisher** [comment]
Yeah, I looked at the requests and it seems to be returning javascript correctly from the ajax.  I think it's some kind of problem that makes the javascript not actually run.  I suspect because I have apostrophes and other things in my title.  Maybe it chokes on it.

**Comment by briri** [comment]
think you're right @sfisher. I manually updated the title to remove the apostrophes and the popup started working again

**Comment by sfisher** [comment]
BTW, that title came from this YouTube of a cockateel running around yelling crazy stuff.  Ian think's it absolutely hilarious.  https://www.youtube.com/watch?v=bUNECHCKWBc
