### ISSUE TITLE
Use EFS shared filesystem for ~/apps/ui/current/public/system

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#423]
This is a task we need to do to ensure load-balancing works correctly with manifest submissions.  The directory in the title is where we expose some files for Merritt to pick them up served by our web server.

(I think) Merritt will be picking up the files from the main domain name which may actually go to one of two different servers, so we need to make the files available no matter which worker Merritt gets a response from.  Also this needs to be shared so all version deploys of the app use the same storage directory.

Probably just create a symlink here to a directory on the shared EFS and copy over any existing files currently in that (old) location before making it a symlink into the EFS directory that is symlinked to.

**Comment by elopatin-uc3** [comment]
@sfisher please let Merritt peeps know if we can do anything to facilitate testing this.

**Comment by sfisher** [comment]
Thanks, @elopatin-uc3 .  I think the main thing we can do is to get it set up correctly on our end and put a bunch of things through Dryad stage to be sure the manifest submissions work for us.

We'll get rejections from Merritt if it can't find the files we tell it to get.  I think we'll probably get failures about half the time if we haven't set it up right.

This will be more of our problem to get right than yours, yet I appreciate the help and we may ask you to look on your side if we can't figure out reasons for rejections.

**Comment by elopatin-uc3** [comment]
Sounds good, on all counts @sfisher.

**Comment by sfisher** [comment]
I created these symlinks on our systems for sharing EFS and it seems like all manifest submissions work on stg where we have load balanced servers.  I'd think production would also work.
