### ISSUE TITLE
Nagios monitoring task info

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#436]
Mark asked for items he could use Nagios to be sure our services are up.

Hitting the UI at \<servername\>/stash should return HTML with the following value in it "Promoting scholarship through open data" .

SOLR has a healthcheck status which I've enabled.  You can test the health by hitting a URL \<servername\>:8983/solr/geoblacklight/admin/ping

It will return a json document with information about the core.  If it is OK, it contains `"status":"OK"` in the json.

**Comment by mreyescdl** [comment]
Request sent to IAS to add Nagios check for the following URLs.  These URLs are populated by a 5 minute cron which checks the actual service as defined by Scott (see above)
If the service is offline a request to the URL will return a 404.

SOLR
http://uc3-dryadsolrx2-stg.cdlib.org:8888/uc3-dryadsolrx2-stg.cdlib.org.8983.ok

Passenger
http://uc3-dryaduix2-stg-2a.cdlib.org:8888/uc3-dryaduix2-stg-2a.cdlib.org.3000.ok
http://uc3-dryaduix2-stg-2c.cdlib.org:8888/uc3-dryaduix2-stg-2c.cdlib.org.3000.ok
