### ISSUE TITLE
Update DOI targets with DataCite for landing pages

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#44]
Dryad-classic DOIs currently go to URLs like https://datadryad.org/resource/doi:10.5061/dryad.9g .  Our normally set URLs are in the format /stash/dataset/\<doi\>

**Problem description, and links to relevant helpdesk tickets:**

We need to update the target URLs for non-Dash, Dryad-classic DOIs.

**Describe the solution you'd like:**

In a rake task, but some of the code may be in other places, also.

- [x] Generate list of DOIs to update. Order by ID so the order doesn't change.
  - [x] This would be items from non-Dash collections.
  - [x] List should only be items that are pubished or embargoed.
  - [x] Add some basic test or validation to be sure selection is correct.
- [x] For each DOI in the list, call our update code that is in our Rails app.  This will update metadata and target to current values..
  - [x] Add delays between updates of datacite metadata so as not to overload DataCite's servers (maybe a second or two), be sure we have generous retries since DataCite will undoubtably have problems at some point or network problems or whatever.
  - [x] Create some way of restarting the script again if it fails out in the middle.  Maybe just as simple as saying "start at item n" so long as the list we're working from is consistent and isn't regenerated.
- [x] Run and monitor the updates.  IDK how long-running this task will be, but it might take a long time if we have to update a lot of datasets.
- [x] There will be some items with problems.  Keep list of items that need manual intervention for fixing the small number of bad data from Dryad classic or weird problems.
- [x] Fix one-off or weird problems.  I hope not too many of them.

Oh, some other random notes about checking targets manually by hand for validation.  Looks like urls like https://doi.org/10.5061/dryad.9gf10?action=showurls will show the target urls easily without special headers.

More info than I ever wanted about DOIs at https://www.doi.org/doi_handbook/TOC.html .

And handy api for viewing like https://api.datacite.org/dois/10.5061/dryad.9gf10 .  See docs at https://support.datacite.org/docs/api-get-doi .

**Comment by ryscher** [comment]
Current structure of Dryad DOIs is described on http://wiki.datadryad.org/DOI_Usage

**Comment by sfisher** [comment]
These are the items that had a problem updating and may need to be fixed manually.  It seems like all were because of required DataCite metadata missing except one which I think may be a DOI we messed around with to "move collections" for it.  Need to look manually at these.  The rest seem good.

```
166: 10.5061/dryad.ft58s
Value cannot be empty or nil

425: 10.5061/dryad.jh3kk
Value cannot be empty or nil

723: 10.5061/dryad.pq269b0
Value cannot be empty or nil

1106: 10.5061/dryad.b2k47
Value cannot be empty or nil

1842: 10.5061/dryad.k3bh40bg
Value cannot be empty or nil

5969: 10.5061/dryad.qf2vm
Value cannot be empty or nil

8187: 10.5061/dryad.1289
Resource must have at least one creator

8195: 10.5061/dryad.gs27k
Value cannot be empty or nil

10416: 10.5061/dryad.c7f1f
Value cannot be empty or nil

11946: 10.5061/dryad.bq583
Value cannot be empty or nil

22803: 10.5061/dryad.1926
Value cannot be empty or nil

22890: 10.5061/dryad.cb43g0n
Value cannot be empty or nil

24342: 10.5061/dryad.dd65d
Value cannot be empty or nil

24674: 10.5061/dryad.b2534
Value cannot be empty or nil

35013: 10.25349/D9P88J
DataCite failed to update metadata for resource 40870 -- #<OpenStruct body={"errors"=>[{"status"=>403, "title"=>"Access is denied"}]}, status=403, headers={"Date"=>"Fri, 13 Dec 2019 23:14:34 GMT", "Content-Type"=>"text/plain; charset=utf-8", "Connection"=>"keep-alive", "Status"=>"403 Forbidden", "Cache-Control"=>"no-cache", "Vary"=>"Accept-Encoding, Origin", "X-Runtime"=>"0.083737", "X-Credential-Username"=>"DRYAD.DRYAD", "X-Request-Id"=>"3fefb106-087c-4715-bdcc-4c73bd75db44", "X-Powered-By"=>"Phusion Passenger 6.0.4", "Server"=>"nginx/1.17.3 + Phusion Passenger 6.0.4"}, url="https://mds.datacite.org/metadata">
```
