### ISSUE TITLE
Publication Updater script says "reached the publication state" multiple times

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#448]
Error on page 5 of publication updater, page 6 and more works, newest ones work
**Re-visit to see if problematic still:**
It seems like the publication updater keeps on updating publication states.
![Screen Shot 2019-09-04 at 1 28 15 PM](https://user-images.githubusercontent.com/105433/64288889-0ca7d080-cf18-11e9-9a29-03277b12669e.png)

**Comment by ryscher** [comment]
Fixed long ago.
