### ISSUE TITLE
Direct automated notifications to Slack

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#457]
Create a new channel, `dryad-cdl-notifications`. Direct all automated error notifications there.

- [ ] Nagios 
- [ ] AWS monitoring (though this may all be moved to Nagios)
- [ ] DataCite alerts from https://status.datacite.org/history.rss
- [ ] Notifications from our Dashboard page

**Comment by marisastrong** [comment]
thanks for writing up all the different notifications Dryad receives.  

Can you elaborate on what AWS monitoring is?  Is this checking if EC2 server is up? (which as you stated could be covered via Nagios) or is there something different that needs monitoring.  

I would be leary of having infrastructure notifications and application notifications go to the same channel.  I.e. I'm not interested in application/dashboard notifications but would be interested if prod server is down.  

Nagios supports sending notifications to a slack channel, however it is just a notification, still need to go to the email and/or Nagios dashboard to acknowledge. Debra notes "It's probably possible, but that's a fairly major project to handle the ACK on the nagios side."

I propose a channel for dryad-nagios alerts

**Comment by ryscher** [comment]
Current AWS monitoring checks these pages:
- (production server)/pages/organization
- (production server)/resource/doi:10.5061/dryad.20
- (secondary server)/resource/doi:10.5061/dryad.20

**Comment by ryscher** [comment]
We reworked the monitoring a while ago. Now, critical notifications go to slack, and less critical notifications email the developers.
