### ISSUE TITLE
Lengthen temporary Dryad URL timeouts for ingest into Merritt

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#47]
https://github.com/CDL-Dryad/dryad-product-roadmap/wiki/Migration

The current dryad has 24-hour public urls.  It sounds like these will be used to ingest things into Merritt.  It sounds like they need to be longer than that.

**Comment by daisieh** [comment]
I have changed it to two days before timeout: https://github.com/datadryad/dryad-repo/pull/1468

I could lengthen it again if we think that it's still not long enough.
