### ISSUE TITLE
Migration one-off fixes

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#477]
https://doi.org/10.5061/dryad.221f9g2
this was archived/ in blackout in old Dryad and the DOI is now returning an error page

doi:10.5061/dryad.rs2qp -- a few issues:
- An improper embargo was applied (files were fully published in old Dryad)
- Submitter migrated it to his account and switched out a file -- it's still showing as In Progress, so maybe he didn't finish submitting - I can ask
- Submitter was asked to agree to payment even though this is a version -- he won't be invoiced, will he?

**Comment by ryscher** [comment]
https://doi.org/10.5061/dryad.221f9g2 is publicly available now.

doi:10.5061/dryad.rs2qp is also publicly available, there is no longer a version in progress, and the user was not invoiced.
