### ISSUE TITLE
Migration: Users can't access email verification - need manual migration to account

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#479]
can you manually associate their datasets? Magnus Blystad - magnushbl@gmail.com, Matthew Gage - M.Gage@uea.ac.uk

**Comment by elizabethdryad** [comment]
Another one - Rowan Lymbery - email from old Dryad is rowan.lymbery@research.uwa.edu.au, he can no longer access the account

**Comment by elizabethdryad** [comment]
Fangbin Hu - 774257461@qq.com - did not receive email

**Comment by ryscher** [comment]
@elizabethdryad All of these accounts have been merged, so they should be able to login now and see any content they had in either system. Note that Fangbin Hu had two nearly-duplicate submissions.

**Comment by elizabethdryad** [comment]
@ryscher Current list of manual migrations needed is in this spreadsheet
https://docs.google.com/spreadsheets/d/1mrB-TJHx22j9EXQX9ttCLK_roJL-wncWha_Ea-Mh3ik/edit#gid=0
