### ISSUE TITLE
EZID (UCSD) minting error in new submissions

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#480]
Saket Navlakha wrote in that she got "error cannot mint DOI" at submission. She is at UCSD. I asked Brian to check config he confirmed it's set up right. 

**Update from Rushiraj who investigated from EZID perspective:**
Dryad is making duplicate CREATE identifier requests to create an identifier and then set the metadata. The problem could probably be fixed by changing the second CREATE request to a SET METADATA request.

Logs:
BEGIN mintIdentifier doi:10.6075/J0 dash ark:/99166/p93b5wb73 merritt ark:/99166/p9pn8xd8d

END SUCCESS doi:10.6075/J0F47MHP

BEGIN createIdentifier doi:10.6075/J0F47MHP dash ark:/99166/p93b5wb73 merritt ark:/99166/p9pn8xd8d datacite <?xml%20version="1.0"%20encoding="UTF-8"?><resource%20xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"%20xmlns="http://datacite.org/schema/kernel-4"%20xsi:schemaLocation="http://datacite.org/schema/kernel-4%20http://schema.datacite.org/meta/kernel-4/metadata.xsd"><identifier%20identifierType="DOI"></identifier><creators><creator><creatorName/></creator></creators><titles><title/></titles><publisher/><publicationYear/><resourceType%20resourceTypeGeneral=""></resourceType><descriptions><description%20descriptionType="Abstract"></description></descriptions></resource> _status reserved _profile datacite
It is the xml object appended after the datacite keyword on line 2 that seems to be the cause of this issue.

A successful mint/create operation looks like this:
BEGIN mintIdentifier ark:/13030/m5 merritt ark:/99166/p9td9n725 merritt ark:/99166/p9pn8xd8d

END SUCCESS ark:/13030/m5g78m0m

BEGIN createIdentifier ark:/13030/m5g78m0m merritt ark:/99166/p9td9n725 merritt ark:/99166/p9pn8xd8d

END SUCCESS

**Comment by sfisher** [comment]
Oh, this is probably easier to fix than that.  I think we are trying to mint identifiers twice.

In old Dash it didn't actually mint an identifier until just before submitting.  Now we mint one up front, so it should no longer need to be minted at the end of the process just before submitting.

**Comment by sfisher** [comment]
I found the errors in our log and I do not believe we are doing anything wrong, but it is a problem with EZID or the UCSD shoulder that needs fixing.  I emailed ruishiraj and am waiting to hear back.  I gave him two examples.  One example worked and one example didn't and literally the only difference is that the one that did not work used the UCSD shoulder.

I found the errors in our logs, but they were just EZID failures and I don't believe we tried minting multiple times as the cause of the error.

It also sits for about 30 seconds before it gives us a failure, so it is very slow to fail.

Sadly I began modifying our code just in case something was odd and to clean it up a little, but it seems like maybe that was in vain and wasted time.  :-(

**Comment by dlowenberg** [comment]
From Maria: "The problem seemed to have stemmed from Merritt and Dash not being configured in EZID with the right access to that shoulder. We reconfigured their access and Rushiraj tested it and successfully minted an identifier."

Can test this tomorrow (Tues 24th)
