### ISSUE TITLE
Curators are unable to edit published or embargoed items

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#481]
- No edit pencil next to title
- If edit pencil next to status is clicked, I just get a notes box - can't change status
- Note: if I hit "submit" in the pop-up the item status changes to Embargoed

**Comment by elizabethdryad** [comment]
We also can't edit the metadata for Embargoed items (no edit pencil next to title). This is needed to be able to add the associated article DOI when it is published.

**Comment by elizabethdryad** [comment]
Sorry but we also can't edit the metadata for submissions that Private for Peer Review. This is needed less often, but might as well address all at once?
