### ISSUE TITLE
Items paid by vouchers or waivers in old Dryad

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#482]
doi:10.5061/dryad.k3q6v8j had a voucher applied in old Dryad, but when we are curating it in new Dryad, the "I accept payment" box is appearing

assume that means the submitter will be invoiced if we approve -- which they should not be

**Comment by elizabethdryad** [comment]
@ryscher we are also unsure if fee waivers selected in old Dryad are being applied in the new system

**Comment by ryscher** [comment]
The example given above is fixed; the general fix is forthcoming.

**Comment by ryscher** [comment]
These items have been updated in New Dryad.
