### ISSUE TITLE
Optimize author order / submitter who is not an author

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#483]
The submitter is automatically added as the first author, and the first author is also the corresponding author. This is problematic in a few cases:

- When the submitter is not the first author but needs to be the corresponding author.
- When someone (e.g. lab staff) is submitting on behalf of the authors (is not an author themselves), but needs to receive correspondence about the submission.

Re-ordering authors is also difficult/not obvious; requires removing values and shifting the other ones around.

**Comment by elizabethdryad** [comment]
Receiving more help tickets (including from institutional members) where univ staff need to submit data on behalf of other people.

**Comment by elizabethdryad** [comment]
Another issue that is coming up: if the submitter should not be listed as the first author, and thus removes themselves from the first position and adds themselves further down in the author list, their ORCID is not retained and they do not receive an opportunity to add it.

**Comment by ryscher** [comment]
We have revamped the system for managing authors, so this ticket is no longer relevant.
