### ISSUE TITLE
User successfully deposited some google pages

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#484]
https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=v9s4mw6qd&commit=Search

Probably trying to do google drive and getting URLs wrong or else a problem in our drive URL transformations or else we need more of them because google has many different URLs.

**Comment by ryscher** [comment]
This particular dataset was cleaned long ago, and we have improved the submission form to prevent future problems.
