### ISSUE TITLE
Error: Cannot publish datasets 

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#487]
Curators trying to publish datasets but get the error message that they cannot likely because of a DOI problem

10.5061/dryad.58bb05p
10.5061/dryad.r9162p5
10.5061/dryad.d39b44r

**Comment by sfisher** [comment]
message is "Unable to save your changes at this time. This is typically due to a  DataCite/Ezid error."  But I think this might have been caused by stripe billing error since I saw those messages in our email logs.

**Comment by sfisher** [comment]
Should be fixed.  I published the top two in the UI.  The last was embargoed and not sure if it should be published, too.
