### ISSUE TITLE
Change SSL from application to ALB

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#488]
What we need from mark:
Change the settings in the ALB to take care of/require SSL in ALB

-- this should happen before we turn it off on our side

We will turn off SSL in our application
Restart application

**Comment by marisastrong** [comment]
For Incoming port 80 requests, can we redirect to the URL:

- https://dryad-stg.cdlib.org

**Comment by mreyescdl** [comment]
ALB now redirects all port 80 requests.
Application should never see a port 80 request, so we can turn off "force_ssl"
