### ISSUE TITLE
Make publication blackout page

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#489]
For Mark:

Create a redirect in Apache on the production servers:

/publicationBlackout --> http://v1.datadryad.org/pages/publicationBlackout

This is similar to the redirects we did at the beginning of launch day.

**Comment by ryscher** [comment]
Assigning this to @marisastrong since Mark isn't on our GitHub.

**Comment by mreyescdl** [comment]
Which rule looks more correct.  I'm not sure if there will be additional pathname info on the requests

    RewriteRule "^/publicationBlackout(.*)" "http://v1.datadryad.org/pages/publicationBlackout$1" [R=301,L,QSA]
    RewriteRule "^/publicationBlackout" "http://v1.datadryad.org/pages/publicationBlackout" [R=301,L,QSA]

**Comment by mreyescdl** [comment]
Complete

**Comment by marisastrong** [comment]
@mreyescdl only made it to one server

**Comment by mreyescdl** [comment]
Fixed. Both servers now support Blackout redirect
