### ISSUE TITLE
Bug: Dataset landing page files are not available for download

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#494]
Christina Park    
https://doi.org/10.7280/D18W95    new    Nothing appears under "Data files"

Ana Montero    https://doi.org/10.5061/dryad.77rn2    new    Individual files under "Data files" are corrupted - ReadMe is blank, Excel file won't download (Download complete dataset is fine) -- **This is a different problem, see https://github.com/CDL-Dryad/dryad-product-roadmap/issues/495 for info on this one**

Yanwei Cai    https://doi.org/10.5061/dryad.qn8p2n0    new    Nothing appears under "Data files"

Magnus Blystad    https://doi.org/10.5061/dryad.kb7b0j0    new    "Data files" box does not appear at all

Jefferson Hall    https://doi.org/10.5061/dryad.845kg37    new    Nothing appears under "Data files"

**Comment by elizabethdryad** [comment]
Alexis Will | https://doi.org/10.5061/dryad.83533nh | Nothing appears under "Data files"
Melissa Plasman | https://doi.org/10.5061/dryad.rc739b0 | Nothing appears under "Data files"

**Comment by sfisher** [comment]
These are two different issues (hidden display vs problem downloading).  I'm going to move the problem downloading to it's own ticket.
