### ISSUE TITLE
Bug: ROR affiliations get converted to different values

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#499]
When users enter an affiliation that is not chosen from the drop-down, it gets converted to a different/incorrect value (which shows on the review screen).

Examples:
- Southern Right Whale Health Monitoring Program changed to Whale Museum
- 9GTZ designs changed to Southern Design

Curators have a list of other examples/submissions to be cleaned up

Some values that *are* in ROR/the drop-down also get converted to other values, e.g.:
- Anhui University of Science and Technology changes to Consejo Nacional de Ciencia y Tecnología
- Luxembourg Institute of Science and Technology changes to Instituto de Ciência e Tecnologia de Polímeros
- Animal Production Institute changes to Istituto per il sistema produzione animale in ambiente Mediterraneo
- Hebei University changes to North China University of Science and Technology
- Ulsan National Institute of Science and Technology changes to Consejo Nacional de Ciencia y Tecnología
- École Normale Supérieure changes to École Normale Supérieure d´Abidjan

**Comment by ryscher** [comment]
Fixed long long ago!
