### ISSUE TITLE
Download errors

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#504]
I ran into problems loading the individual files from these datasets.  See if there are common issues.

https://datadryad.org/stash/dataset/doi:10.15146/R32S37

https://datadryad.org/stash/dataset/doi:10.15146/R30C70

https://datadryad.org/stash/dataset/doi:10.15146/R3VP4Q

https://datadryad.org/stash/dataset/doi:10.15146/R3QW2S

I'm trying to use "rack.hijack" to correct this since it should avoid leaving the process as a web server thread where it might be killed by the passenger web server.

On development I created this https://dryad-dev.cdlib.org/stash/dataset/doi:10.5072/FK2B56NP8K which always seems to time out after 2:30 to 3 minutes and slightly different sizes (over my network from home).

I put debugging and the error I get is `error reading from socket: Could not parse data entirely (1 != 0)`  .  I'm not sure what the solution is to it or if it is because Merritt express decided to close the connection and stop delivering data or if it's something on my side.

I may want to try with readpartial, but not sure it will be different results.

Maybe try a different client like restclient or httpclient.

**Comment by elizabethdryad** [comment]
Help desk report re doi:10.5061/dryad.89n87 -- "Download complete dataset" not working, downloading first zip file not working

**Comment by elizabethdryad** [comment]
More examples of errors with "Download complete dataset"
https://doi.org/10.5061/dryad.dk1j0
https://doi.org/10.5061/dryad.71c6r
(tried a few individual files for both and they seemed okay)

**Comment by elizabethdryad** [comment]
doi:10.5061/dryad.pc5j0
Email to help desk reported multiple people unable to download complete dataset, but I could do it.

**Comment by elizabethdryad** [comment]
Download errors encountered by curators:
10.5061/dryad.np574cj
10.5061/dryad.8gs9388
10.5061/dryad.fc0qr81
10.5061/dryad.824f24t
10.5061/dryad.23p15n1

**Comment by elizabethdryad** [comment]
Helpdesk report of download errors for 10.5061/dryad.315km76 - I got an error with "Download complete dataset" but was able to download the zip from under "Data files"

**Comment by elizabethdryad** [comment]
Author reports unable to download files in 10.5061/dryad.8m40rb0 by either method

**Comment by elizabethdryad** [comment]
10.5061/dryad.61pd6 - Download complete dataset results in "network error". Downloading individual files seems to work.
