### ISSUE TITLE
Differentiate "until article appears" embargoes from longer ones

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#505]
- Submitters and journals are confused about why data is getting embargoed for a year when they did not request that
- Users have no way to know that data will likely be available sooner than a year

Suggested language to appear on dataset landing page:
"This dataset is embargoed and will be released when the associated article is published. Contact help@datadryad.org to notify us of article publication.

Lists of files and downloads will become available to the public when released."

**Comment by elizabethdryad** [comment]
Make sure to also update language in the email notification

**Comment by elizabethdryad** [comment]
Related nice-to-have: if submitters could lift these embargoes themselves (and get asked to provide the article DOI). Some people are coming to the dashboard looking for this functionality.

**Comment by ryscher** [comment]
How to detect these:
- have a CurationActivity that mentions "untilArticleAppears"
- OR have a CurationActivity automatically set based on the journal's blackout setting

**Comment by ryscher** [comment]
Main request is fixed in https://github.com/CDL-Dryad/stash/pull/290. Moving the "nice to have" part into a new ticket, since it requires some UI decisions.
