### ISSUE TITLE
Journal metadata import needs to ignore ".R2", ".R3", other suffixes on manuscript numbers

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#507]

**Comment by ryscher** [comment]
Sample where this did not act correctly: doi:10.5061/dryad.t6855h4 (manuscript had ".R1" in the acceptance email)

**Comment by elizabethdryad** [comment]
Another example: EVA-2019-358-OA.R1 only works if you enter EVA-2019-358
