### ISSUE TITLE
Intermittant error when creating email validation code

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#51]
![screen_shot_2018-08-06_at_1 24 13_pm](https://user-images.githubusercontent.com/105433/43746472-5a062d64-9999-11e8-98e4-ad0f4a6dad4e.png)

See the screenshot above from Daniella testing.  We are not sure why this happens intermittently.

One of the objects in the screen shot and highlighted line is nil.  It's hard to tell if current_user or params[:code].  I looked at the expanded environment info at the bottom of the screen on Daniella's computer when she got it to happen again.  It seemed like the session[:user_id] was set (which is what the current_user is derived from) and it didn't show a value for any params at all it seemed like.

Though it seems like maybe it would've returned previously if that param was nil.  I suppose User.find_by_migration_code might return some kind of object or other thing that isn't considered nil? Or maybe it's finding a migration_token that is null? I'm totally guessing.

Maybe this helps, but maybe not.  We need to reproduce the cause of this issue.

```
return if params[:code].blank? || User.find_by_migration_token(params[:code]).nil?
```

**Comment by dmolesUC3** [comment]
Looks to me like it's `current_user` that's nil.

`User.find_by_migration_token(params[:code])` shouldn't be nil since the first return statement should check it, but I'd extract it into a variable anyway—you don't want to run the `find` twice.

**Comment by daisieh** [comment]
I can't get it to reproduce...was Daniella properly logged in at the time of the error? Does she have more details about how to reproduce this?

**Comment by dmolesUC3** [comment]
Might be a good idea to change

```
before_action :require_login, only: [:show]
```

at the top of the file to

```
before_action :require_login, except: [:metadata_basics, :preparing_to_submit, :upload_basics]
```

since everything else is likely to require a user. Or even move those actions to a separate controller (if they're still relevant?) and just make it

```
before_action :require_login
```

for everything.
