### ISSUE TITLE
Bug: public search for journal not finding results

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#512]
Contact from Toxicological Sciences reports that when she searches for that title, only 1 result comes up (true). However by browsing I can see that there are 62:
https://datadryad.org/search?_=1569348240034&f%5Bdryad_related_publication_name_s%5D%5B%5D=Toxicological+Sciences

(Search for PLOS ONE = 9 results)

**Comment by ryscher** [comment]
Closing in favor of #2138
