### ISSUE TITLE
(maybe) something adding duplicate affiliation.long_names, causes duplication errors with validation

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#519]
There were only 3 of these in the database with duplicate long names, but when going to create a new version (duplication) it then causes an error on save because there is a validation on affiliations.long_name that disallows duplicate names for separate affiliation rows.

There were two duplicate sets of names in from today (9/25) which were not related to any authors or contributors and I'm not sure how they got in.  Maybe from the migration server???  I didn't see any before or after except the following one.

There was one set of duplicate name for "University of Connecticut."  The original one went in in June, so was probably from testing data before the data validation went into place.

So maybe our code is fine, but when something creates duplicates (probably not in our current code) it makes failures in hard to find places when duplicating rather than when the error actually occurred.

I guess keep an eye on this and if it never arises again we can close it since it is likely caused by old code or some other code somewhere manipulating the database directly.

**Comment by ryscher** [comment]
Hah, this issue itself has now been duplicated, in #652. So I'll close this version of it.
