### ISSUE TITLE
API versioning: user account

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#531]
If logged in through the API and using a user account.

- [ ] List display of all datasets is public + their owned ones.
- [ ] mostly like it is now with submissions.  Not sure any changes there.
- [ ] version listing is accepted/flagged versions plus any post-accepted versions.  They will also need to see any in-progress items in the list so they may continue to work on them through the API and this is where this may differ from the UI.
- [ ] Does it make sense to just assume that an API user is an advanced user and so they can see all internal versions (with some status) and just get to make sense of it themselves?

It seems like Admin/superusers don't require changes and see all internal data and options for their scope.

**Comment by ryscher** [comment]
Fixed long ago
