### ISSUE TITLE
Fix for custom submission links

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#534]
Integrated journals provide their authors with submission links (e.g. http://datadryad.org/submit?journalID=BITR&manu=BITR-19-142.R1). In the old system, if you were logged in and used this link, you would go right to a submission with your manuscript metadata filled in.

We need to provide some solution for people who are trying to use these links, as they are very confused.

**Comment by ryscher** [comment]
This was fixed at some point, but is broken again. Current ticket is #2231
