### ISSUE TITLE
Associate Stripe customer_id with the submitter, not the first author

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#535]
When we created the Stripe integration, email addresses were only guaranteed to be attached to the authors, so we set up invoices for the first author.

Now that the submitter is guaranteed to have an email address, it seems more obvious for them to receive the invoice.

This will require a database moving the customer_id field to a different table.

**Comment by sfisher** [comment]
I'm not sure that it's guaranteed that the submitter will have an email address, still.  Are you seeing someplace where it's required?

ORCID certainly doesn't release email addresses for all authors.  We might get them by shibboleth login or by migrating data, but I don't think either of those things id guaranteed.

Before you change to rely on an email address for all users, I'd be careful to be sure this really exists for all users.
