### ISSUE TITLE
Merritt problem with file with line feed or carriage return in the filename

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#537]
This is information from David Loy (below).  Basically he is asking if we can resubmit this item with the filename with the linefeed in it corrected.

```
ark: ark:/13030/m52p02q4
doi: doi:10.5061/dryad.sv72c

As part of the minio migration I ran into the problem that
ark:/13030/m52p02q4 would not replicate.

The problem is a line feed in the file name:
xml key: ark:/13030/m52p02q4|1|producer/Data Availability&#10;.xlsx
manifest key:  ark:/13030/m52p02q4|1|producer/Data Availability<U+2028>.xlsx

Storage is unable to retrieve the content using this key.

For Merritt, the fastest way (if possible) to correct this problem would
be: fix the file name and submit doi:10.5061/dryad.sv72c as a new object
The existing object, ark:/13030/m52p02q4, would then be deleted. Right
now, a new version of this object will not work.

I need to review why the linefeed causes a problem. How Merritt should
handle filenames having a line feed needs to be discussed.
```

**Comment by marisastrong** [comment]
unicode line separator.  in storage, when it (saxmanager) sees newline, treats like a textual newline and continue the content inserting a blank line in front of it.  Some unicode 2 byte control characters (these differ from ASCII)  will cause issues.   
Merritt is curious how this linefeed came into being because it's not standard.  Can't accept control characters in filenames.  

short story, dryad will need to resubmit.

**Comment by sfisher** [comment]
Yes.  This is some bad migrated data.  Ryan said he'll re-submit this one.

**Comment by ryscher** [comment]
I have updated this item in Dryad, but the incorrect version needs to be removed from Merritt.

**Comment by ryscher** [comment]
From David's comments above, it seems like the entire item might need to be removed from Merritt before Dryad can transfer it? For my current transfer, the DOI was detected, so the update was attached as a new version to the existing ARK in Merritt, which David says will not work. (Though for Dryad's purposes, we would be fine if the file with the offending name was removed, leaving only the good file.)

**Comment by elopatin-uc3** [comment]
We hit a similar snag recently where a file in an older version of a Dryad dataset contained PII which needed to be removed. We managed remove the old version by: a) downloading the latest dataset object from Merritt (w/good data/files), b) deleting the entire object in Merritt, c) re-ingesting the latest object and entering the DOI as a local ID, d) updating the Dryad db accordingly. @sfisher performed this last step.

Should we follow the same procedure for this issue? Sounds like it would be successful, given that the latest version generated by @ryscher contains the file with a corrected filename.

**Comment by elopatin-uc3** [comment]
New object now available, which uses the same DOI as the old one:
https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5dn9bp5

Note: David removed the ark <-> localID link pertaining to the old object in the inventory database.
