### ISSUE TITLE
Users not always getting "private for peer review" option

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#539]
Multiple help tickets from people saying they do not see this option on the "Review and Submit" page. I asked them to confirm that they had selected "manuscript in progress" and their journal title from the drop-down.

Example: 10.5061/dryad.sj3tx9617

**Comment by ryscher** [comment]
Feature is working as designed. Some journals disallow the `peer_review` option.
