### ISSUE TITLE
"Describe edits made" box should appear for submitters, not just admins

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#540]
It can be difficult to tell what specifically has changed when authors update a submission.

When curators update a dataset that has previously been submitted, on the "Review & Submit" page, we have to "describe edits made."

Please require authors to fill in that note as well, and make sure it is recorded in the activity log.

**Comment by ryscher** [comment]
We addressed this by highlighting the changed fields/files on the review page. This shows the curators actual changes, instead of (potentially untrue) comments from the authors.
