### ISSUE TITLE
Logic fixes and/or validation of files before submitting

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#542]
I think doing this task would probably fix the problems with #443 and #514 .  We may also want to combine this work with #475 .  (There is a temporary quick-fix hack to correct #475 so it will not cause us grief right away, but it isn't a good permanent fix, especially if we deploy our servers slightly differently.) 

It seems like we have situations where people add two deletions for the same file or add a file twice and then delete only one of the files from the list, so the list of files is a slight mismatch from what is on the actual file system.

Likely this could be fixed by a little logic in the controller, even if it's hard to do in the javascript (which is complex and tricky).  Essentially, if someone adds the same file more than once then we remove the first before adding a second.  Or if they "delete" the same file more than once then we don't put anther request into the list for deletion from Merritt if there is already one.

It might also be nice to validate any added files to be sure they exist on the file system as part of the review process and ask users to fix any failed upload that isn't present or is the wrong size as indicated in the database.

**Comment by ryscher** [comment]
Closing, since this problem is almost certainly fixed, and even if it isn't, we will be reworking the associated logic again soon, as part of the redesign for file uploads.
