### ISSUE TITLE
Inappropriate Stripe invoices

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#545]
Stripe invoices are being created and sent when they shouldn't be, in a few different cases:

- submitters who already paid the DPC in old Dryad are being invoiced when their submissions are published in new Dryad. Examples: doi:10.5061/dryad.65492qt and doi:10.5061/dryad.67c92vm (approved into blackout/payment processed in old system 30 August; submission released today and they were sent an invoice)

- doi:10.5061/dryad.78nf7dq is for sponsored journal Systematic Biology, which appears to have been entered correctly, but an invoice was still issued

**Comment by elizabethdryad** [comment]
Also seeing dups - see david.logue@uleth.ca and maarten.larmuseau@kuleuven.be

**Comment by ryscher** [comment]
Duplicate for was marked "published" three times within 10 seconds. Is this an issue with curators having multiple windows open simultaneously? Probably the best approach is to avoid any issue with Rails caching -- "reload" the identifier before issuing an invoice, and "save" it immediately after.

**Comment by ryscher** [comment]
Elizabeth says that most (all?) of the inappropriate invoices are for items that went through publicationBlackout -- so there may be some issue with the timing of when the items were migrated vs when payment was processed.

**Comment by ryscher** [comment]
The pattern for the main case here: 
- item was in blackout at the time it was migrated
- user created a new version before the blackout expired
- user submitted the new version

**Comment by ryscher** [comment]
Ran a process to guarantee an existing `invoice_id` for all items that had previously been in blackout and had the shoppingcart marked `completed` in v1.

Added a small PR https://github.com/CDL-Dryad/stash/pull/295 to protect against creation of multiple invoices for the same Identifier.
