### ISSUE TITLE
Block file names containing Unicode line separator

### ISSUE THREAD

**Issue by dloy** [CDL-Dryad/dryad-product-roadmap#552]
At this time Merritt cannot handle the Unicode line separator utf8 x(e2 80 a8) in a storage file path. The failure is in the Java XML handling. The character is converted to a NL and then reprocessed by adding a blank with the remaining file name content appended. Escaping does not appear to avoid this problem.

If Dryad could block any file path name containing this character from Merritt submission (either zip or manifest) it will help prevent several errors on the Merritt side, primarily making the file content inaccessible.

**Comment by ryscher** [comment]
We implemented filename filtering long ago, fixing this problem and problems with many other special characters.
