### ISSUE TITLE
API for /datasets/{doi}/download not working

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#556]
User-reported issue: https://nescent.fogbugz.com/f/cases/48234/

This API is in our documentation, but it only works under some circumstances, due to the way it redirects to a Merritt URL, instead of streaming the file directly.

Update this API so it returns the download the same way as /datasets/versions/{id}/download.

**Comment by janxkoci** [comment]
Where can I read about the API please? I'm writing an application for our published dataset and I noticed it doesn't work now because of link change.

**Comment by dlowenberg** [comment]
Hello, the documentation is here: https://datadryad.org/api/v2/docs/ Let us know if you have any specific questions about it
