### ISSUE TITLE
New Tenant: Victoria University

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#557]
![Victoria_University_Melb_Aus_Logo_Landscape_K](https://user-images.githubusercontent.com/25755963/67261982-eacac480-f457-11e9-96c0-7988f16f11dc.png)

**Comment by ryscher** [comment]
Talk with Brian about how this works, update the Google Doc instructions that are linked from the Dryad Operations page.
