### ISSUE TITLE
Make script to cleanup old/abandoned data

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#560]
This isn't urgent but we probably want to do sometime.  We should determine what our policy is for keeping old, unsubmitted files and make a cleanup script to follow that policy and delete abandoned files and any database records that go along with them.

We end up paying storage fees in EFS for all those staged but unsubmitted files sitting around and they also clutter up our file system.

Keeping metadata is something I'm less concerned about since it it really small, though I"m not sure if it would be weird to keep abandoned versions of datasets and metadata while destroying the files if they are abandoned for too long.

----

Also this is related and I'm adding here.

We use a lot of space on our disks and run out of space at times. We need to manage this better.

Counter takes a lot of space and combines files from other machines to process. It also takes lots of processor when it's going. Long run we should move it off our UI server to somewhere else, I think.

The 48 database backups a day seem a bit extreme to me and each is approaching 200 MB, so I think they take around 9 or 10GB.

The individual cron item logs don't seem rotated. Most are small, but the stash-notifier.log is huge since that script runs every minute, so it runs 1,440 times a day, even though individual runs aren't that bad.

We probably should look into either getting more space, reducing our usage or else putting some things we think could legitimately grow onto EFS where we have more space.

However dumping stuff on EFS means we pay for usage of space (such as we are for all the abandoned crap people abandon without submitting). It may also have network speed limitations.

Update: server space upgraded to 100GB

**Comment by sfisher** [comment]
```
sfisher 10:18 AM
Deletion of their in-progress editing/files that they never bothered to submit [are what we'd delete].

We have about 292 GB of probably mostly abandoned files right now.

Not that big a deal, though I'm sure Kurt's group will harass us to get rid of stuff at some point if it gets bigger and more expensive
```

(and even $88 a month adds up to over $1,000 a year.)





From what I can tell AWS shows it costs $0.30 a month per GB we store on our EFS drive.





So those abandoned files cost us like $88 a month.





But if we never delete them that cost will just grow over time.

**Comment by ryscher** [comment]
Limit -- delete anything that has been unsubmitted for a year.
