### ISSUE TITLE
Bug: submissions displaying twice (with different statuses) on My Datasets

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#563]
Not sure how often/in what cases this is happening, but here's an example. Perhaps caused by an indexing problem / lag time

**Comment by elizabethdryad** [comment]
![Screen Shot 2019-10-12 at 12 45 09 PM](https://user-images.githubusercontent.com/6784484/67481683-5798b700-f630-11e9-9cf4-43cafd74fb05.png)

**Comment by ryscher** [comment]
I'm not aware of this problem happening any longer.
