### ISSUE TITLE
Investigate / try to improve the deliverability of system emails

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#564]
It is clear from the help desk that many users are not receiving the email notifications sent from the system. (Gmail seems to be sending them to spam, for instance). See if any adjustments can be made to improve this.

**Comment by elizabethdryad** [comment]
Still a problem. When submitters don't receive the system emails, they don't know what's going on with their submissions and email the help desk.

**Comment by ryscher** [comment]
We investigated and didn't come up with any great solutions. But I think the problem has largely been resolved by Google in the meantime.
