### ISSUE TITLE
Monthly report of submission activity

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#573]
Known in old Dryad as the "shopping cart report," this is needed for Elizabeth 1) to report to publisher sponsors on their monthly usage, 2) to monitor payment patterns overall, and 3) to monitor usage/submission volume overall. 

It should be created within the first week of each month and contain all *new* submissions approved in the previous month (not versions).

Info needed:
- submission DOI
- date published
- indication of whether payment was covered by journal, institution, waiver, voucher, or Stripe invoice

If payment was covered by journal, also need:
- journal name
- organization.paymentPlanType (from concept)
- journal.sponsorName (from concept)

Let Elizabeth know if there are questions. Report for October '19 needed by Monday 11/11, if possible.

**Comment by ryscher** [comment]
@elizabethdryad Regarding "date published" -- the old report had a "Payment Date", which in the current system would correspond to "date published or embargoed". Is this what you want? Or do you prefer it to be the date the item is truly "published" i.e., any embargo has expired?

**Comment by elizabethdryad** [comment]
I'd like to keep it the same as it was -- "date the submission was first
approved by a curator," essentially.
