### ISSUE TITLE
Move submissions out of web application processes

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#574]
We do submissions through our web application.  It means if our web application is restarted or if Passenger kills a parent process for the submission/queue then it randomly fails.  More chance of failing if it's a large submission.  In fact it was almost impossible to get a 2.3GB or 10GB submission to go through when Passenger was set to kill processes after so many requests.

It is very hard and frustrating to troubleshoot or reproduce and you have to watch if your process-id got killed.  We might just make our own mini-application to do this.  Or else perhaps we can use ActiveJob https://edgeguides.rubyonrails.org/active_job_basics.html if one of the queueing backends will do it out of process.  It says built-in it is under the web server process.

**Comment by ryscher** [comment]
@sfisher Is this still relevant? Things are much improved with ActiveJob.
