### ISSUE TITLE
Google Drive URLs not working as upload technique

### ISSUE THREAD

**Issue by ecclary** [CDL-Dryad/dryad-product-roadmap#577]
I'm not sure if this is related to file size, but we are receiving many submissions with Google Drive links, rather than a hard copy of the actual data file (some as small as 160 Mb). Curators must download the file, and upload it manually. If these links can't be made functional. we should remove Google Drive as an option for uploading files via URL.

**Comment by ryscher** [comment]
We gave up on dealing with Google's constant changes.
