### ISSUE TITLE
Incommon Metadata for Dryad Production Instance has old info

### ISSUE THREAD

**Issue by marisastrong** [CDL-Dryad/dryad-product-roadmap#579]
Need to update the Incommon Metadata 

Information URL and Logo

        <mdui:InformationURL xml:lang="en">https://dryad-stg.cdlib.org/stash/about</mdui:InformationURL>
     
        <mdui:Logo height="87" width="400" xml:lang="en">https://dash.ucop.edu/images/logo_dash.svg</mdui:Logo>

**Comment by marisastrong** [comment]
- [ ] need logo URL

- [ ] confirm that this URL is correct for Information URL https://datadryad.org/stash/our_mission

**Comment by sfisher** [comment]
I believe this was addressed and haven't heard issues in 4 years.
