### ISSUE TITLE
Items with 'until article appears' embargo display incorrect publication date

### ISSUE THREAD

**Issue by ecclary** [CDL-Dryad/dryad-product-roadmap#580]
For journals that use blackout, we are protecting files from download until the article appears online. The message that displays in the 'Data Files' section was updated to indicate that files will be released when the article is published (issue #505), but the publication date under the author list displays a date 1 year in the future. This is incorrect and confusing to authors. Should this not display the date we approved the submission for the archive, the date the metadata is made available? Or if it is based on the date the files are released, could it display 'unavailable' or some other value until the embargo is lifted? 
![Incorrect-pub-date-displayed](https://user-images.githubusercontent.com/18015884/68687146-c637a900-053a-11ea-9a1f-09bd0c20ede3.png)

**Comment by ryscher** [comment]
We have removed all embargoes of this type.
