### ISSUE TITLE
New journal integrations (email method)

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#585]
We have requests to integrate additional journals using the email method (for publishers using MS systems we are not yet ready to integrate with). Need to decide how we are handling custom submission links first.

**Comment by elizabethdryad** [comment]
-GMS Zeitschrift für Audiologie
-GMS Journal of Arts Therapies

**Comment by ryscher** [comment]
No longer relevant. Memberships have changed much in the meantime.
