### ISSUE TITLE
Update to async download email template

### ISSUE THREAD

**Issue by elopatin-uc3** [CDL-Dryad/dryad-product-roadmap#598]
While working on the removal of CDL recipients from async download email messages, the Merritt team realized that Dryad relays its own email template content to the Merritt Storage service. 

This is a request to remove the following sentence from this template, until a duration (number of days) can be determined by Dryad, regarding how long downloads are to be made available.

Template lives here:
https://github.com/CDL-Dryad/dryad-app/blob/e8f48bfa9841ba92a68f840785edc24964c97c69/stash/stash_engine/app/views/stash_engine/downloads/async_email.txt.erb

Sentence to remove:
Please note that this link will expire in 7 days from the date of this email.

**Comment by ryscher** [comment]
Dryad no longer sends emails related to downloads; the template has been removed from our code.
