### ISSUE TITLE
Update DOI targets at DataCite for file & version-level DOIs from Dryad-classic

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#601]
Dryad classic had special DOIs for each file in a dataset.  I believe version-level was similar.

**Problem description, and links to relevant helpdesk tickets:**

We need to update the target URLs for the file-level and version-level DOIs so that they target the main dataset landing page for the dataset.

**Describe the solution you'd like:**

In a rake task, but some of the code may be in other places, also.

- [x] Need list of all the file-level and version-level DOIs exported from the Dryad classic system.  Ryan said he'd figure out how to get that kind of list.
  - [ ] List should only be items that are pubished.
- [ ] For each DOI in the list, call our update code, but the target would be for the corresponding landing page for the dataset.
  - [ ] Probably need some special update functionality such as exporting the DataCite.xml file from our current code and changing the DOI in it.  Normally we only update only the datasets in our database.
  - [ ] Need to have manual datacite update code outside of items that are in our database since these file-level DOIs are not in our database.
  - [ ] Add delays between updates of datacite metadata so as not to overload DataCite's servers (maybe a second or two), be sure we have generous retries since DataCite will have problems at some point.
  - [ ] Create some way of restarting the script again if it fails out in the middle.  Maybe just as simple as saying "start at item n" so long as the list we're working from is consistent.
- [ ] Run and monitor the updates.  IDK how long-running this task will be, but it might take a long time if we have to update a lot of datasets.

**Comment by ryscher** [comment]
DOIs are available at:
https://v1.datadryad.org/themes/Mirage/docs/all_dois.txt

Note that this includes *all* DOIs from the old system. 
- File DOIs are the ones that have a `/` after the `dryad.*` (e.g., `doi:10.5061/dryad.abc123/4`)
- Versioned DOIs are the ones that have a `.` after the `dryad.*` (e.g., `doi:10.5061/dryad.abc123.2`)
- There are also file-level versioned DOIs. (e.g., `doi:10.5061/dryad.abc123.2/4.2`)

**Comment by ryscher** [comment]
The redirects for all of these should be changed to the "base" DOI, that is, the DOI up to the point  of `dryad.*`, without the file or version indicator.

For the file-level DOIs, I'm wondering if it would be best to retain the existing DOI metadata, since that metadata describes the contents of that specific file.
