### ISSUE TITLE
Emails not going out

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#605]
Daniella reported problems with emails going out.  One she gave me was never published so would've only gotten a submission email.

I searched through the logs for rendering of these email templates which we have in our code.  **The 'submitted' email was never sent during this week.** The others as indicated below.  I think some of these emails were old stuff or were removed from sending.

For emails that are being sent (such as publication ones) and people are not receiving them we need info about the datasets so we can look up to see if items were logged as being sent so we can narrow down if it is a problem with our code or with emails being sent to spam or not arriving across the internet.

```
Week of 12/13/2019
------------------
stash/stash_engine/app/views/stash_engine/user_mailer/dependency_offline.html.erb
- Sent

stash/stash_engine/app/views/stash_engine/user_mailer/embargoed.html.erb
- Sent

stash/stash_engine/app/views/stash_engine/user_mailer/error_report.html.erb
- Sent

stash/stash_engine/app/views/stash_engine/user_mailer/helpdesk_notice.html.erb
- Never sent

stash/stash_engine/app/views/stash_engine/user_mailer/journal_published_notice.html.erb
- Sent

stash/stash_engine/app/views/stash_engine/user_mailer/journal_review_notice.html.erb
- Sent

stash/stash_engine/app/views/stash_engine/user_mailer/large_file_notice.html.erb
- Never sent

stash/stash_engine/app/views/stash_engine/user_mailer/notify_admins.html.erb
- Never sent

stash/stash_engine/app/views/stash_engine/user_mailer/orcid_invitation.html.erb
- Sent

stash/stash_engine/app/views/stash_engine/user_mailer/peer_review.html.erb
- Sent

stash/stash_engine/app/views/stash_engine/user_mailer/published.html.erb
- Sent

stash/stash_engine/app/views/stash_engine/user_mailer/submitted.html.erb
- Never sent
```

**Comment by ryscher** [comment]
`submitted`, modify the logic in stash/stash_engine/app/models/stash_engine/curation_activity.rb#email_status_change_notices

`large_file_notice` is not needed, since we changed the logic for payments, and references to it were removed.
