### ISSUE TITLE
Rename Dryad RDS Instances

### ISSUE THREAD

**Issue by marisastrong** [CDL-Dryad/dryad-product-roadmap#609]
Currently the dryad dbs are defined within the Dash2 RDS instances.  This is confusing to IAS and anyone else since Dash is no longer supported and all infrastructure has been decommissioned.

- [ ] submit ticket to IAS -  rds-uc3-dash2-dev and rds-uc3-dash2-stg can be renamed rds-uc3-dryad-dev and rds-uc3-dryad-stg for consistency.  Same for dash2-prd
- [ ] update config files to reference new names
- [x] requires downtime for production since it is a database change.  Need to schedule accordingly - IAS suggested to do it when we update the SSL certificate authority (which we're still not clear on)

**Comment by ryscher** [comment]
Production database was updated at some point. Other databases still show the 'dash' name, but maybe everyone is accustomed to it by now?

**Comment by ryscher** [comment]
No longer relevant. Instances will be renamed as part of the upcoming technical transition.
