### ISSUE TITLE
Aggregate data usage and data citation by tenant

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#617]
Institutional members want to be able to see an aggregation of data usage counts and citations for the datasets from their institution.

On the admin layer add an icon for metrics, when you click on it show the view and download # and the citation list.

When you download CSV in the admin layer, populate a column with view download and citation lists (could be multiple columns)

---

We do not have any citation data permanently stored, so will need to get it or update it occasionally ahead of time if we want any CSV report to work with any kind of reasonable speed.

- [x] Script to pre-retrieve citations.  30,000 will take some time to update manually.   My best estimate is about a day to run the first time, though maybe later runs will be faster if it doesn't barf because we're hitting their API too hard.
  - [x] Try each of our published/embargoed datasets
  - [x] Populate actual citations into our database
  - [x] Populate citation count into our database
  - [x] Change stats code to retrieve them from database instead of service
  - [x] Make it so cache never gets cleared as right now the database is a cache that gets updated after it is stale
- [x] Put in schedule to run weekly as another long-running task
- [x] UI
  - [x] Create button for showing stats in table
  - [x] Have it lightbox over and show stats.
  - [x] IDK where citations are  I guess we jsut pop them below. or something.
- [x] CSV
  - [x] Not sure of implications for that code, probably need some separate output columns and maybe extra queries for the CSV since it doesn't match the table anymore.
  - [x] Counts of views, downloads, citations and extra mega columns for citations
  - [x] Does it time out with big queries?  Yeah? 🤕 🔫

**Comment by sfisher** [comment]
I tried running the code to retrieve citations and it was running about 25 datasets worth of citation checks per minute.  I believe we have 31,585 datasets embargoed or public.  I believe it will take about 21 hours to run.
