### ISSUE TITLE
Journal names that are manually typed are not captured

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#622]
Since the deploy of the autofill fix, we've been noticing many submissions that still don't have a journal name (even though they may have a manuscript number). 

I tested typing something into the journal name field and then clicking out of the field before the drop-down pops up. The text stays in place, but the journal name field comes in empty.

**Comment by ryscher** [comment]
If the user doesn't click on the autocomplete, the internal data field should still store the last text that the user typed.

**Comment by ryscher** [comment]
For all autocomplete fields (journal name, affiliation, keywords, granting organization), add an indicator when the field value was supplied by the user but *not* clicked from the autocomplete list.
