### ISSUE TITLE
Submission UI bugs

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#624]
- Can’t change values in Related Works or Funder info - you have to add a new line to enter all correct information, then remove the offending line. For Related Works, if you fill in the box before selecting the relation type, the type "cites" is retained no matter what you choose.
- Entries in Related Works and Funder info duplicate when you get to the "Review & Submit" screen
- Email address in required field isn’t always recognized: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/551
- Edits to usage notes field aren’t always saved. If you go to Source and make changes, then click Source again to see the WYSIWYG, the changes you made are not saved.
- Keywords field freezes up regularly. A huge block list of scientific names sometimes appears in the drop-down.

**Comment by ryscher** [comment]
All of these features have been completely rebuilt since this ticket was created.
