### ISSUE TITLE
Allow curators to communicate with submitters within the Dryad system

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#626]
- Currently, curators must communicate with submitters in a separate system (FogBugz), and must manually copy and paste submission information -- and vice versa (FogBugz ticket numbers/links must be manually added to the Activity Log)
- Replicate functionality from the old system where, when changing status to “Author Action Required,” a curator can enter a custom message that is included in an automatic email to the submitter. Store this in message in the activity log. 
- Curators may have suggestions or recommendations that do not require returning the submission. Add option to send submitter a message when publishing as well.
-- Even better: Add a drop down menu that pre-populates text for common reasons we need to return / suggestions we need to make (allow editing for customization)
-- To get really fancy, add a messaging system as part of the user dashboard
- All messages should automatically include the submission title, DOI, and information about how to edit and resubmit once the requested change is complete

**Comment by ryscher** [comment]
This functionality has been moved into Salesforce, and there is a direct connection to Dryad datasets.
