### ISSUE TITLE
Reconsider required fields / layout on "Describe Dataset" page of submission UI

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#628]
Required fields under Basic Information are Title, Author and Abstract. Since the abstract provided is usually the abstract of the associated article, this means we wind up with no descriptive information specific to the dataset. Curators are thus sending a "please provide a ReadMe" email to a large portion of submitters.

Consider how to change field order, required vs. not required, and instructions to capture better dataset description from the outset.

One idea is to create separate abstract fields for the dataset and the article, and require the dataset abstract. Make it clear that this should describe the files they are uploading to Dryad, and encourage a ReadMe file. The article abstract field could only appear if "a manuscript in progress" or "a published article" are selected, not required, and could be populated automatically by integration or importing metadata from Crossref.

**Comment by ryscher** [comment]
We have added a requirement for README file. The distinction between article and dataset abstract may still be an issue, but that can be added in a separate ticket if needed.
