### ISSUE TITLE
Customize curator UI

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#632]
Currently, curation of a dataset requires 4 different views:
- Admin Dashboard (only place where Status of dataset can be accessed)
- Activity Log (only place where history, submitter name can be accessed - unless submitter was last to modify)
- Dataset landing page (only place where files can be downloaded)
- Metadata view (only place where metadata can be edited)

For curators, this requires having a number of browser tabs open and careful management to ensure you're not mixing up datasets.

Consider how to make curator navigation between these views/access to needed information more seamless.

**Comment by ryscher** [comment]
Curation practices have changed drastically since this ticket was created. We will re-analyze the curation process periodically to determine more specific changes.
