### ISSUE TITLE
"You do not have the permission to download"

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#636]
This error appears for some datasets when trying to download the zip for the entire dataset, and it contains large files.

This problem is caused when there are large files (which trigger an asynchronous download), but the dataset has at least one revision that consisted of metadata-only edits. In this case, the latest published resource will have file_view set to false, because we're displaying the (unchanged) files from an earlier resource. But the "download dataset" button is somehow trying to retrieve the latest resource, even though at first glance, it should be getting the latest with file_view=true.

**Comment by sfisher** [comment]
@ryscher Do you know if this is still a problem with the new download by presigned URLs?

**Comment by ryscher** [comment]
I have not seen this error in a long time, and I believe the mechanisms have changed quite a bit due to presigned URLs, so I think this is fine to close.
