### ISSUE TITLE
Data upload failures from Google Drive

### ISSUE THREAD

**Issue by ryaxley** [CDL-Dryad/dryad-product-roadmap#639]
When submitters try to transfer data using Google Drive URLs the uploads fail due to a security or authentication warning page. 

1. File uploads – Direct URLs to individual files on Gdrive return this error "The given URL is invalid. Please check the URL and resubmit." The error message is displayed near a URL on the Upload page, so this error message is easy to overlook. No reason is provided for why the link is invalid. The error needs to be visible and the language needs to clarify the issue.

2. Directory uploads – URLs to Gdrive directories appear to work initially, but the files do not upload. Users typically do not understand whether the data was uploaded or not. There are a growing number of help tickets related to this ambiguity.

Google Drive appears to be a popular choice for our submitters. Until this feature is working correctly, we should consider revising our instructions to only include working methods (FTP, Dropbox).

I have worked around the issue with the following workflow:
1. Requested users email direct URLs to their file archives
2. Downloaded files to FTP server using Gdown (https://pypi.org/project/gdown/) 
3. Reviewed files while on FTP (or locally if necessary)
3. Uploaded files from FTP to Dryad

**Comment by ryscher** [comment]
I think curators have a new process for handling these requests. Any issues they encounter should be in the new spreadsheet of curation needs.
