### ISSUE TITLE
Organize documentation

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#642]
- Organize all dev documentation between Github, Confluence, and Wiki
- Ensure Wiki is updated to point to new documentation as users find that on google first especially for our API

Current status is stored at: https://docs.google.com/spreadsheets/d/1FDRuoThGAQqGUrbSFpiAylnR488MwjOfsyiq7kesHiA/edit?usp=sharing

**Comment by ryscher** [comment]
Not sure why this got moved to Completed... there is still a fair amount of work to be done.

**Comment by ryscher** [comment]
Updates regarding the wiki are completed. 
- All documents from the old wiki have been reviewed. 
- Technical documents that are still needed have been moved into the GitHub documentation. 
- Curators have verified that they no longer need any of the documents on the wiki. 
- Documents with potential historical interest have been archived in s3://dryad-backup/wikiFiles and s3://dryad-backup/wikiExportPDFs
