### ISSUE TITLE
Looks like duplicate names cause problems

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#652]
From an error report.

```
An ActiveRecord::RecordInvalid occurred in authors#update:

  Validation failed: Long name has already been taken

URL        : https://datadryad.org/stash_datacite/authors/update

  * HTTP Method: PATCH

"long_name"=>"US Environmental Protection Agency", "id"=>"", "ror_id"=>"https://ror.org/03fkcxa91"}
```

I'm not sure why this would be, but looks like it's preventing duplicate ROR records from being inserted.  If so, then it should probably associate an existing record instead of inserting another or we need to look at the uniqueness validation that was added for this model.

**Comment by ryscher** [comment]
There are currently four different ROR entries for "Environmental Protection Agency", which are located in four different countries. It looks like the user tried to distinguish by adding "US", but the same set of RORs still show up in the autocomplete.

We will need to relax the validation, but we also need a better way for users to distinguish between similarly-named organizations.

**Comment by ryscher** [comment]
These duplicates can also cause the problem for curators "The change you wanted was rejected...."
