### ISSUE TITLE
Provide a way to differentiate between similar ROR names

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#653]
There are currently four different ROR entries for "Environmental Protection Agency", which are located in four different countries. Users can't tell the difference between them in the autocomplete.

**Comment by ryscher** [comment]
ROR does include some hierarchical information that we could leverage for disambiguation. See https://ror.org/blog/2023-02-27-parents-children-and-other-relationships-in-ror/

**Comment by ryscher** [comment]
Possible disambiguation UI ![image](https://user-images.githubusercontent.com/605143/236930873-c9d3eaec-c968-450e-bbb5-a32dea47cf07.png)

**Comment by ahamelers** [comment]
Also see #215

**Comment by ahamelers** [comment]
@ryscher @sfisher Is there a reason why the "Research facility" lookup is using the ROR API, while the affiliations lookup uses our ROR table? Should the Facility lookup be changed to use the same query source and disambiguation redesign as the affiliations?

**Comment by ahamelers** [comment]
I've gone ahead and used the existing ROR autocomplete for the research facilities as well.

**Comment by ryscher** [comment]
Great. There was no explicit reason for the research facilities being different. I think it was just overlooked.
