### ISSUE TITLE
Validate journal names that are entered correctly but not selected from drop-down

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#654]
We are seeing cases where a journal name is entered in the correct format (matching our concept) but not validated (i.e. has an asterisk) - presumably because they didn't select it from the drop-down. Can this logic be updated so sponsorships get applied correctly and curators don't have to go back in to correct this?

Related: multiple users have reported recently that the journal drop-down list is not coming up for them. One said she was using Safari, so I tested in Safari and did not have a problem.

**Comment by ryscher** [comment]
All autocompletes have been updated to reduce the frequency of this problem.
