### ISSUE TITLE
API broken for listing and downloading individual files

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#655]
Both of these API endpoints fail:
- /versions/{version_id}/files
- /files/{file_upload_id}

Stack trace:
```
NoMethodError (undefined method `download_path' for #<Module:0x00007facdbfb3670>):
  stash/stash_api/app/models/stash_api/file.rb:49:in `add_download!'
  stash/stash_api/app/models/stash_api/file.rb:43:in `basic_links'
```

**Comment by ryscher** [comment]
Strangely, these work on ryan's VM, but not on dev or prod. Is there some interaction with https?

**Comment by sfisher** [comment]
hmm.  I wonder if apache is interfering.  Very weird.
