### ISSUE TITLE
UTF-8 problems with search words (and maybe other fields)

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#656]
We've seen some issues with UTF-8 characters because of the wonky way MySQL handles them.  The UTF-8 character set built in will only handle up to 3 byte codes in MySQL.  In order to get 4-byte codes we need to convert fields to "utf8mb4" which is their special encoding to handle 4-byte ones.

This should be pretty easy to fix by doing a migration to update any UTF-8 fields to UTF8MB4.  We have some examples of this in our old migrations somewhere since we've been through a round or two of this already.

It also has a side effect of making any VARCHAR(255) fields to be only VARCHAR(191) so the maximum number of characters is reduced.  This can lose data if something is between 191 and 255 characters in a VARCHAR field and so sometimes means converting to a TEXT or other type of field without such strict length limitations.

I believe this can be done quickly and easily, but I don't want to interrupt something I'm in the middle of so deferring it and it may fix a couple problems we get occasionally.

 
This is related to #791

**Comment by ryscher** [comment]
This was fixed in 2021.
