### ISSUE TITLE
Report for Tracy and operations

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#663]
From Tracy:

- 'Date submitted'. 
Ryan said 'Creation date' is the date the author created the submission, and I imagine there could be some delay when an author starts working on getting the data into Dryad, and when they submit it to us so that it goes into our curation cue, so that's what I'm thinking about for 'Date submitted'. So that we can see  how long it's in our hands before it's approved.  

- 'Institution'
I know all the records aren't up to date yet, but could we get the ROR/institutional affiliation for each dataset. Just empty column if we don't have it. 

And yes, I can always join on DOI, so however many reports this comes in is fine!

**Comment by tracykteal** [comment]
Thanks @dlowenberg for creating this issue. I tried to outline how I was thinking about using a particular field of data, in case the field name I'm referencing isn't accurate. So, please let me know if there are any questions.

**Comment by tracykteal** [comment]
Right now I have the data from the Admin layer and from the 'shopping cart' report that Ryan has generated. Both have DOIs, so I can join that data together. So new columns could be added to either output, or to a new csv that contains also contains DOIs.

**Comment by tracykteal** [comment]
In the csv we download from the Admin interface, could we also include the 'Journal name' column? I know it's in that shopping cart report, but it would be good to have in that admin csv because it's used at the curation stage. It could be journal name as the full name, or if it's there as a code, e.g. "The American Naturalist" or "amNat"
