### ISSUE TITLE
System sends emails to submitters when curators modify submissions

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#664]
Users should not receive emails when a curator updates a submission. Case in point:

doi:10.5061/dryad.dr7sqv9v8 is being held Private for Peer Review (since December 2019). On 3/12/20 Shavon updated the affiliation metadata, but did not change the status of the submission. This seems to have caused a few things:

- the submitter was sent an automatic email about their data being submitted into PPR. this confused them because they hadn't touched the submission since December, and they wrote to the helpdesk.

- the activity log shows that the submitter made the 3/12 changes, when in fact it was Shavon.

Fogbugz ticket is 50344 in case that helps.

**Comment by ryscher** [comment]
Email notifications have recently been revamped.
