### ISSUE TITLE
Manage server space usage better and do some auto cleanup

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#670]
We use a lot of space on our disks and run out of space at times.  We need to manage this better.

Counter takes a lot of space and combines files from other machines to process.  It also takes lots of processor when it's going.  Long run we should move it off our UI server to somewhere else, I think.

The 48 database backups a day seem a bit extreme to me and each is approaching 200 MB, so I think they take around 9 or 10GB.

The individual cron item logs don't seem rotated.  Most are small, but the stash-notifier.log is huge since that script runs every minute, so it runs 1,440 times a day, even though individual runs aren't that bad.

We probably should look into either getting more space, reducing our usage or else putting some things we think could legitimately grow onto EFS where we have more space.

However dumping stuff on EFS means we pay for usage of space (such as we are for all the abandoned crap people abandon without submitting).  It may also have network speed limitations.

Update: server space upgraded to 100GB

**Comment by ryscher** [comment]
Yes, we need to make sure all of the logs are rotated. I remember creating tickets like this several times, but none of them exist anymore???

But it is definitely *not* extreme to have database backups every 30 minutes. They have saved us from problems several times in the past, including on launch day. At the current 10GB, the cost for storage is $1 per month.

**Comment by ryscher** [comment]
- The volume /dev/mapper/DRYAD-dryad should be expanded. It's only 42GB. I have more space on my phone.
- /apps/dryad/apps/apache/logs/uc3-dryaduix2-prd-2a* -- these files are not rolling over.

**Comment by marisastrong** [comment]
Capturing some items for discussion with IAS here:  https://docs.google.com/document/d/1xm4x6JVTgxzOiKEFas0mgXGlKOOyPKak-vmdYqVAcDo/edit?usp=sharing

**Comment by marisastrong** [comment]
We met with IAS and have decided to move ahead with upping disk space for 2a prd server to 100GB.  Also IAS will be looking into the Nagios alerts to determine where we are alerted for disk space.  Is it 10%, 5%?  IAS will follow up.
