### ISSUE TITLE
Comment on CEDAR metadata editor technical specs

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#671]
please read through the document and add comments or questions throughout the gdoc. No need to read this thinking about "we have so much to do right now" just general feedback on what we would have to change, what they would have to change, if we wanted to use a external metadata editor on our page 1.

https://drive.google.com/file/d/14l-sR2IDV581DANrLLXaGzbh5WuYgWrl/view?usp=sharing

**Comment by ryscher** [comment]
Converted this to a Google docs for easier commenting. It's in our Drive, titled "CEDAREmbeddableMetadataEditor"
