### ISSUE TITLE
Unable to search by institutional affiliation

### ISSUE THREAD

**Issue by devnich** [CDL-Dryad/dryad-product-roadmap#687]
**Bug description:**

The University of California, Merced currently has 36 articles indexed by institutional affiliation (as of 30 Mar 2020). Those articles are visible via a direct link:
https://datadryad.org/search?f%5Bdryad_author_affiliation_name_sm%5D%5B%5D=University+of+California,+Merced

However, there does not appear to be any way to find these articles via the user interface. "University of California, Merced" is not available in the "Institutions" menu, and searching via the search bar appears to execute a full-text search that excludes institutional affiliation.

**Steps to reproduce:**
1. Search for "University of California, Merced" using the search bar. This retrieves 3 articles. Each article contains all the words in the search, indicating that this is a full-text "AND" search. The retrieved set contains articles that do not have University of California, Merced as their primary author affiliation, e.g. https://datadryad.org/stash/dataset/doi:10.6071/M3FH3D

2. Search for "merced" using the search bar. This retrieves 31 articles that contain the word "merced" in the body of the article. The retrieved set includes articles that do not have any institutional affiliation, e.g. https://datadryad.org/stash/dataset/doi:10.6071/M3WC7K

**Expected behavior:**

Searching for "University of California, Merced" should retrieve at least 36 articles, including all articles that list it as an institutional affiliation.

**Comment by dlowenberg** [comment]
Hi Derek, Thanks for filing this. This is not actually a search issue but rather a ROR-issue typing out the UCs. We are familiar and this is being worked on. I am going to close the ticket but will keep you posted as I've mentioned on email.

**Comment by devnich** [comment]
Can you give me the link for the live issue so that I can follow that instead? Thanks.
