### ISSUE TITLE
New Tenant: NIOO - KNAW (Nederlands Instituut Voor Ecologie)

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#708]

**Comment by marisastrong** [comment]
We are receiving an error when trying to communicate with their Login service.  Their [troubleshooting documents](https://wiki.surfnet.nl/pages/viewpage.action?pageId=10132128) indicates we need configure our institution with them.  


I would start with sharing our [attribute metadata file]( https://github.com/CDL-Dryad/dryad/blob/master/documentation/membership/dyrad_attribute_release.xml  ) with their IT/Identity team.   https://github.com/CDL-Dryad/dryad/blob/master/documentation/membership/dyrad_attribute_release.xml
