### ISSUE TITLE
Private for peer review not switching to Submitted after article is accepted in some cases

### ISSUE THREAD

**Issue by tracykteal** [CDL-Dryad/dryad-product-roadmap#709]
**Bug description:**
In the PubUpdater we're seeing some articles that have been published that are still in Private for Peer Review in our system. Doesn't seem to occur that frequently, but just wanted to capture it. 

**Steps to reproduce:**
Screen shots from one example
<img width="1228" alt="Screen Shot 2020-04-07 at 2 37 57 PM" src="https://user-images.githubusercontent.com/889238/79135003-897b1280-7d63-11ea-9541-bf8d9dea8c58.png">
<img width="1222" alt="Screen Shot 2020-04-07 at 2 38 10 PM" src="https://user-images.githubusercontent.com/889238/79135019-8f70f380-7d63-11ea-8085-11f76e738ee5.png">

Another example:
- 10.5061/dryad.pvmcvdnh8

**Expected behavior: **
If a paper is published and we have the data in private for peer review, another mechanism should change its status in our system, rather than us seeing it first in PubUpdater.

**Comment by ryscher** [comment]
It seems like there is some serious miscommunication here?? This is the entire job of the PubUpdater, to *update* datasets in response to article *publication*. What other mechanism should be doing it?

**Comment by sfisher** [comment]
I'm not sure about some of the rest, but have the Curators accepted publication information here?  IDK why, but the curators asked Brian to change the arrow to go the wrong direction and said it made sense to them.

The idea is that if you accept published information it takes the action and overwrites the current information (top) with the published information (button).  But they said they really liked it pointing the opposite direction of the actual flow, so we fulfilled the request.

**Comment by ryscher** [comment]
Note that 10.5061/dryad.jsxksn05d should have moved into curation based on the journal notice on October 18, 2019. This didn't happen due to issue https://github.com/CDL-Dryad/dryad-product-roadmap/issues/661, which has since been resolved. However, the part of the function of the PubUpdater is to catch these issues.

**Comment by ryscher** [comment]
No longer relevant.
