### ISSUE TITLE
New Tenant: Claremont Colleges

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#722]
Consortia of colleges: Pitzer, Scripps, Harvey Mudd, Claremont McKenna, Pomona, Keck Graduate Institute, Claremont Graduate University

Logos: https://cucclaremont.box.com/s/l23dyairy33rj0fyjsdjv4sdkbab8l38

- Set them all up as individual tenants, configure each separately (entity ID, logo)
- In admin view show all schools for admins

**Comment by sfisher** [comment]
OK, I put in the tenants for these eight and here are the screenshots of the logos in this zip file. [logo_screenshots.zip](https://github.com/CDL-Dryad/dryad-product-roadmap/files/4839450/logo_screenshots.zip)


Only 2 of the 8 successfully login with shibboleth for our stage system.  [login_screenshots.zip](https://github.com/CDL-Dryad/dryad-product-roadmap/files/4839441/login_screenshots.zip) .  The ones that work are Harvey Mudd and Pomona College.

These are the entity ids for the other 6 that I found in the shibboleth file.  @marisastrong , Do you know if we have to do anything special with these?

```
Keck Graduate Institute (KGI):     entity_id: https://webauth.kgi.edu/idp/shibboleth
Pitzer College    entity_id: https://webauth.pitzer.edu/idp/shibboleth
Claremont Graduate University    entity_id: https://webauth.cgu.edu/idp/shibboleth
Scripps College     entity_id: https://webauth.scrippscollege.edu/idp/shibboleth
Claremont McKenna College    entity_id: https://webauth.cmc.edu/idp/shibboleth
Claremont College Services (TCCS)    entity_id: https://webauth.cuc.claremont.edu/idp/shibboleth
```

**Comment by sfisher** [comment]
Sounds like these will work in production and likely were not configured to test on stage by these administrators.

```Error Message: SAML 2 SSO profile is not configured for relying party https://dash-stg.cdlib.org/shibboleth```
