### ISSUE TITLE
Allow users to change from ROR to non-ROR affiliations

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#736]
If a user selects a ROR affiliation from the autocomplete, and then later changes their mind, the system currently assumes that this is a typo, and keeps the ROR affiliation.

This can cause problems, since users are not allowed to correct incorrect values. 

We should test it with the restriction removed and see whether it causes fewer problems.

**Comment by LoriEP** [comment]
In addition, if a user selects a ROR affiliation but it is in fact not the correct affiliation for that user (UCD is selected but user meant to select UCSD) and then the user submits, users cannot change the ROR affiliation to UCSD, a developer must do this.
