### ISSUE TITLE
Submission Status: Merritt Error for doi:10.5061/dryad.b2rbnzs8s

### ISSUE THREAD

**Issue by dfagandryad** [CDL-Dryad/dryad-product-roadmap#737]
I edited doi:10.5061/dryad.b2rbnzs8s to delete the existing files and add updated data files. After I saved and exited, the status for the dataset now reads "Merrit Error", and I am unable to do anything with the dataset.

**Comment by sfisher** [comment]
Fixed.  I think this was some weirdness as part of the Merritt outage last night and the status was incorrect since it said errored but the version was OK in Merritt.
