### ISSUE TITLE
Modifications for GET /datasets and GET /datasets/<doi> if superuser

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#74]
What do we hide from the public for a dataset that a superuser and owner could see, but no one else?

- [ ] Publisher

Anything else?

Hide sensitive information in some circumstances, but not in others.

**Comment by daisieh** [comment]
We decided to put publisher/journal in the stash_engine_internal_data table, and I think that all other private metadata will be in there as well, so there shouldn't be any metadata proper that needs to be hidden from the public.

**Comment by sfisher** [comment]
It sounds like this isn't needed by me right now.  I'll close this and re-open if it becomes obvious we need different visibility for showing datasets because of internal data.
