### ISSUE TITLE
API changes for version downloads

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#742]
We need to evaluate how a version download works in the API.  Right now they only really work for small (less than 2 GB items).

They can work for everything, however, we may need to do something like have people handle different download status such as 1) assembling/not ready (check back later) and 2) actually begins downloading since the process is now asyncronous.

**Comment by ryscher** [comment]
Closing this issue -- I believe it has been fixed by #738 and #749.
