### ISSUE TITLE
Acceptance Email not triggering Status change to Submitted from Private for Peer Review

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#752]
**Bug description:**
Dataset submissions are not transitioning from PPR to Submitted when an acceptance email is received even when Journal Name and MS# are included. Note: Integrated Journals only. Noticing a particular spike in this issue with Proceedings of the Royal Society B submissions (RSPB)

**Steps to reproduce:**
See the following five (5) datasets where Journal Name and Manuscript # were provided either by submitter or added by curator either at the time of submission or at a later date, but all entries added prior to acceptance email being received.

- 10.5061/dryad.jwstqjq6b (submitted with Journal Name and MS# (seem to be correct) acceptance email sent 5/18/20 no status change
- 10.5061/dryad.k6djh9w32 (submitted with Journal Name and MS# (seem to be correct) acceptance email sent 5/21/20, no status change 
- 10.5061/dryad.m905qftxx (see below for extensive details)
- 10.5061/dryad.qjq2bvqcg (MS # added later, author moved out of PPR to Submitted, then curator moved back to PPR) 
- 10.5061/dryad.47d7wm39g (Appears Journal Name and MS# added correctly, no curator involvement)  Doesn't seem to fit the assumption that moving an item back and forth (status change from PPR to Curate or Submitted back to PPR) caused this failure of acceptance notice status change
- RSPB example: 10.5061/dryad.3j9kd51fc (acceptance email received on 5/21/20)

 No steps to reproduce except to review the dataset Activity Log and see that the item is stuck in PPR with appropriate Journal Name and MS # included. 
Acceptance emails have been verified for each dataset listed.

**Expected behavior:**
If Journal Name (or ISSN?) and a Manuscript # are properly entered in Dryad at the time of submission, but prior to an Acceptance Email being sent out by the associated journal, at the time of the acceptance email being received by Dryad, the dataset should move from PPR to Submitted.

**Potential Causes**
Common theme seems to be that items are being moved out of PPR in error by authors (ie: no acceptance notice yet) then moved from Submitted back to PPR, maybe to Curation in some cases, but always back to PPR. Once this change occurs, it appears the automated processing of acceptance emails is no longer triggering PPR to Submitted. 

- **In the case of 10.5061/dryad.m905qftxx** (in this particular instance, the MS# was added in after an author had submitted without an MS# and was moved from Submitted to Curation back to PPR but PRIOR to any acceptance email being sent)
- 10.5061/dryad.k6djh9w32 similar case to above (Author removed PPR status and curator moved it back into PPR)
**Question to answer:** If MS#s or Journal Names are added after the initial submission and there is a status change, which results in the movement of the item back into PPR, will the automated system not work?)

**Comment by ryscher** [comment]
Thanks for the detailed description @LoriEP!

The primary problem here was that starting on May 1, the Royal Society changed their emails from plain text to HTML, which prevented them from being processed. In general, we require plain text so the messages can be processed correctly. However, in this case, the HTML was simple enough that I was able to adjust our system to accommodate it. I have now processed the 2500 messages that were being held. 

Note that there is one example above that was not from the Royal Society, doi:10.5061/dryad.qjq2bvqcg. I will investigate this separately.

**Comment by LoriEP** [comment]
Good to know that these were nearly all, with the 1 exception all explained by the RSOS email issue! Sorry I didn't notice that they were all RSOS. @ryscher Thank you for the resolution.

**Comment by ryscher** [comment]
For doi:10.5061/dryad.qjq2bvqcg, the problem was due to the older issue of parsing manuscript numbers (https://github.com/CDL-Dryad/dryad-product-roadmap/issues/507). The original email from the journal was received February 6, but the issue was not corrected until February 24th, so we had an incorrect manuscript number attached to the dataset.

**Comment by ryscher** [comment]
There have been many other journals with errors in processing emails lately, mostly due to HTML junk embedded within the Dryad-readable metadata. I have been able to correct almost all of these, with one notable exception:

Journal of Experimental Botany is sending metadata emails that do not include the standard Dryad fields. It looks like they are including some of the fields we need, but they are using different field names than we require, so nothing is parsing. We will need to discuss this with them.
