### ISSUE TITLE
robots.txt adjustments

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#762]
There is no robots.txt on dryad-stg.cdlib.org, so Google is (incorrectly) indexing some of its pages. 
- [x] Place robots.txt on stage - the contents of the file should be the same as http://dryad-dev.cdlib.org/robots.txt

- [x] On the production server, https://datadryad.org/robots.txt should also exclude /Shibboleth.sso

These updates require coordination with Ashley.

**Comment by marisastrong** [comment]
I added this to Ashley's pivotal queue - https://www.pivotaltracker.com/story/show/173503678

**Comment by ashleygould** [comment]
The work is done. The Pivital ticket is ready for validation.
