### ISSUE TITLE
New Tenant: Texas Tech

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#775]
They are a part of InCommon R&S category. 

Logo: http://www.depts.ttu.edu/_ttu-template/2017/img/dbl__T.svg

**Comment by sfisher** [comment]
Ok.  TTU is set up.

![Screen Shot 2020-07-17 at 4 08 42 PM](https://user-images.githubusercontent.com/105433/87837356-1c868580-c848-11ea-9d20-55e75025baed.png)


![Screen Shot 2020-07-17 at 4 08 56 PM](https://user-images.githubusercontent.com/105433/87837363-201a0c80-c848-11ea-81fe-8c024b907dc0.png)

![Screen Shot 2020-07-17 at 4 09 40 PM](https://user-images.githubusercontent.com/105433/87837370-260fed80-c848-11ea-8340-30178814f14b.png)
