### ISSUE TITLE
Merritt wants to know about our downloads

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#779]
**Problem description, and links to relevant helpdesk tickets:**

The Merritt people said they want to know where downloads are coming from.  We had about 750 so far on 08/Jul/2020.

A grep like this will give us the info about downloads URLs that get hit from our access logs for version download assembly.

```
grep -P '\[08/Jul/2020:\d{2}:\d{2}:\d{2} -0700\] "(GET|POST) /stash/downloads/download_resource' datadryad.org-access_log > 2020-07-08-downloads.txt
```

It didn't appear that any single IP address was monopolizing to a huge extent after combining logs from both servers and sorting.  One IP had about 30 download requests a few more had about 10 and most others were only a few.

A grep like this will show the polling for completion.

```
grep -P '\[09/Jul/2020:\d{2}:\d{2}:\d{2} -0700\] "(GET|POST) /stash/downloads/assembly_status' datadryad.org-access_log > 2020-07-09-downloads.txt
```

You can examine an example at `dryad@uc3-dryaduix2-prd-2a:~/apps/apache/log/2020-07-09-downloads.txt` for example.

I know Ryan said he had seen one instance of excessive polling, but in examining the logs, I'm not seeing any single client polling for status any more than once every 15 seconds, which is how we set up the Javascript progress bar to work.  For longer-to-assemble downloads the frequency decreases to 5% of the estimated time that Merritt gives us starting at the 50% to completion time.  I think the one excessive downloading must've been a rogue bot or something else.  We should investigate if we see it again.

**Describe the solution you'd like:**

I'm not clear what we want from this, so if this needs to turn into a project to throttle downloads or other things, we should add another ticket or expand this one.  It sounds like Merritt is having some troubles with the amount of usage they're getting for the download and assembly service.  May also be related to why submissions were having some issues because of the scale.

**Additional context:**

**Comment by elopatin-uc3** [comment]
Thanks for this ticket @sfisher. I wanted to note this one on our side that is related: https://github.com/CDLUC3/mrt-doc/issues/395

**Comment by ryscher** [comment]
This work was completed.
