### ISSUE TITLE
uc3-dryaduix2-stg-2a.cdlib.org will not correctly start passenger server

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#780]
**Bug description:**

I now cannot get passenger server to start up on uc3-dryaduix2-stg-2a.cdlib.org .  It works fine on the 4 other servers (dev, stg-2c and the two production instances).

**Steps to reproduce:**

Try to start passenger and if you go to pages using stage-2a then you get an error message.  I've tried reinstalling Ruby 2.6.6 and our application and gem libraries multiple times and doesn't seem to correct the problem.

For now I've taken it out of the ALB rotation for stage and we do not get a lot of traffic on stage, but we probably need to fix it to have full stage system.   It seemed to be working after I originally installed it, but now doesn't seem to work.  Needs more troubleshooting and digging through the environment and logs to figure out.  It seems like it is something about the environment on that server.

**Expected behavior: **
It starts up and serves pages.

**Comment by ryscher** [comment]
I didn't mention this in all the commotion today.... when I used the Rails console, it worked fine on stg-2c, but on stg-2a, I got a bundler issue, which came back to the rb-readline problem. So there is definitely something different in the environments for those two machines.

**Comment by sfisher** [comment]
This seems to be a weird bundler issue.  I was able to get it working by uninstalling the system gem rb-readline and then reinstalling the rb-readline gem in the bundle with bundle exec.

From what I understand, the rb-readline gem is a workaround for missing development libraries in Linux or MacOS and if those are installed then readline support is already compiled into Ruby.

I'm going to put in a non-urgent ticket for Ashley and ask her to install the readline libraries on our servers so we don't run into these kind of issues so much in the future.
