### ISSUE TITLE
Other Zenodo errors

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#800]
I'm able to get these corrected through re-submissions except for the following.

stash_engine_zenodo_copies.ids are below.

Error downloading file from Merritt
10, 69, 172, 551, 797, 954

Cannot replicate later until earlier is done
91

http error 400 validation error
238, 417, 400

**Comment by sfisher** [comment]
These are the other errors left in there that aren't the main ones

Error downloading file from Merritt
10, 69, 172, 551, 797, 954

Cannot replicate later until earlier is done
91, 244, 308

http error 400 validation error
238, 417, 400

**Comment by sfisher** [comment]
Moving to more specific tickets.
