### ISSUE TITLE
Error downloading files from Merritt for these items

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#804]
Problem:  This one has a \# sign in a filename.
10.7272/Q6H993DV
identifier_id: 46874
resource_id: 66974
Stash::MerrittDownload::DownloadError
Download: Error downloading file for resource 66974
MerrittError: Merritt couldn't create presigned URL for http://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5t77r2w/2/producer%2FExperiment_KLF2_gfp_B220_DAPI_GFP_CD4_GL7_%233.tif?no_redirect=true
Http status code: 404
file.id 506088

---
Problem: This one has \#README as the filename.
10.5061/dryad.f7m0cfxrq
identifier_id: 39800
resouce_id: 67148
Stash::MerrittDownload::DownloadError
Download: Error downloading file for resource 67148
MerrittError: Merritt couldn't create presigned URL for http://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5dr82dx/7/producer%2F%23README?no_redirect=true
Http status code: 404
file.id 511788

---
Problem: They put \# in every filename they have
10.5061/dryad.ttdz08kv4
identifier_id: 46228
resource_id: 71970
Stash::MerrittDownload::DownloadError
Download: Error downloading file for resource 71970
MerrittError: Merritt couldn't create presigned URL for http://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm59d24z8/3/producer%2FPG_6_p1_f1_%232.avi?no_redirect=true
Http status code: 404
file.id 554877

---
Problem: They put \# in almost every filename
10.5061/dryad.7pvmcvdqm
identifier_id: 48468
resource_id: 73749
Stash::MerrittDownload::DownloadError
Download: Error downloading file for resource 73749
MerrittError: Merritt couldn't create presigned URL for http://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5wb0j83/3/producer%2F%233_MEGA_Bbengalensiis_MgMg.meg?no_redirect=true
Http status code: 404
file.id 571881

---
*FIXED*
Problem: This looks like the deletion--add--delete problem
10.5061/dryad.9s4mw6md1
identifier_id: 49358
resource_id: 74646
Stash::MerrittDownload::DownloadError
Download: Error downloading file for resource 74646
MerrittError: Merritt couldn't create presigned URL for https://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm57m5h36/2/producer%2Fdonation_analysis_osf-2.R?no_redirect=true
Http status code: 404
file.id 581949

**Comment by elopatin-uc3** [comment]
Noting corresponding Merritt ticket: https://github.com/CDLUC3/mrt-doc/issues/426

**Comment by sfisher** [comment]
Thanks, Eric.  I should've noted it here.

**Comment by ryscher** [comment]
All of these files now work.
