### ISSUE TITLE
Get rid of SWORD

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#809]
**Problem description, and links to relevant helpdesk tickets:**

This is one of those tasks that doesn't have any urgency but I think both us and Merritt might be happier about afterward.

SWORD protocol is awkward to work with and the synchronous (waiting) for things to be accepted by Merritt is quite annoying considering it can take a long time for large submissions.

Both us and Merritt have talked about getting rid of it since it's such an awkward service and protocol.

**Describe the solution you'd like:**

- Use some Merritt API to check status or doneness of submissions.
- Better way to find out what errors were.
- Merritt would be happy to get rid of BOTH sword and and OAI-PMH feed (so they've told me).  We only use the OAI-PMH feed to verify that things have actually really gone into Merritt after SWORD accepts the deposits.

**Additional context:**

This is something that has been on the "nice to have" list and "technical debt" list for a while but has never been urgent as long as we can put up with the awkward system we have in place.

**Comment by elopatin-uc3** [comment]
Though we haven't detailed anything out yet, the Merritt team has two tickets in the backlog for this: https://github.com/CDLUC3/mrt-doc/issues/390, https://github.com/CDLUC3/mrt-doc/issues/372

**Comment by sfisher** [comment]
Done.
