### ISSUE TITLE
Migrate UC Merritt Collections into Dryad Collection

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#810]
This is a broad placeholder for a project we may decide to embark on with the Merritt team to simplify management and also make it easier for us to move content around.

**Comment by elopatin-uc3** [comment]
The Merritt team has had a longstanding task to change the primary storage node for these collections from S3 to Minio. This task will of course be moot if we decide to do the work of migrating Merritt collections into the Dryad collection in the near future. Just wanted to mention it.

**Comment by sfisher** [comment]
Done.  All in one collection.
