### ISSUE TITLE
Implementation of OECD in UI: autofill from 42 categories before keywords section

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#811]
- Move under "Basic Information"
- Name "Research Domain" and then an empty box for autofill
- If it's quick, can move Funding up in this section as well
- Autofill drop down from database of 42 categories
- Populate whatever is chosen as the top word in "Keywords" on landing page

For reference: wireframe of where Funding populates is: https://1b1x4w.axshare.com/#id=4rd3fx&p=describe_dataset_v9c&g=1

**Comment by ryscher** [comment]
Looks good, and works fine on my VM. Thanks for adding this feature -- we have needed it for years!
