### ISSUE TITLE
Create FTP account for new curators 

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#831]
**end of sprint**

- Jess Herzog
- Ari Orona
- Nate Jacobs
- Hannah Schubloom

SSH key to be sent over slack

Extra permission for Lori to delete

**Comment by ryscher** [comment]
Lori's delete permission is fixed.

**Comment by sfisher** [comment]
I thought we were getting rid of the FTP server as a workflow type?  Closing and can be reopened if not.
