### ISSUE TITLE
Remove file version (5.21.20) from data package (doi:10.5061/dryad.m0cfxpp10) (NOT URGENT)

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#832]
**Problem description, and links to relevant helpdesk tickets:**

Author wants version of files removed from doi: 10.5061/dryad.m0cfxpp10 for publication date 5/21/20 (May 21, 2020) due to miscommunication about embargo policy.

**Describe the solution you'd like:**

- **Please remove all files from version date 5/21/20**

- Files from version date July 15, 2020 (7/15/20) may remain

- Data from July 15, 2020 (7/15/20) can remain published

**Additional context:**
Not urgent, please complete when resources allow. 
If a file list is needed, please feel free to ask.

**Comment by ryscher** [comment]
I have removed the visibility of the May 21 version.
