### ISSUE TITLE
Special characters, URLs, and deletion

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#833]
Need to talk to Merritt and make sure we are filtering the same way
--

This edge case can make it impossible to curate an item. When a file is uploaded directly, Dryad filters special characters out of the filename. However, when files are uploaded via URL, this processing is performed by Merritt. The result is that Dryad and Merritt may have slight differences in their recorded filenames, and some Dryad/Merritt communication will break. Including making it impossible to delete a file.

Steps to recreate the problem:
1. Create a new submission in Dryad
2. Select the option to "Enter URLs of file locations"
3. Enter a URL that includes a space or other character that must be URL-encoded, such as:
"http://ftp.datadryad.org/InCuration/Zhang/Figure1, S2-source data.xlsx"
4. Complete the Dryad submission.
5. Once Merritt has finished processing the submission, you will be able to see that the filenames are different in the Dryad UI and Merritt UI.
6. Although the file can still be downloaded in the Dryad UI, it cannot be deleted. Any attempt to delete the file through the Dryad UI will result in Merritt producing an error because the filename that is being requested for deletion does not exist as far as Merritt is concerned.

Temporary workaround:
- Go into the Dryad DB and edit the filename to match the name that appears in the Merritt UI.

Related: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/804

**Comment by elopatin-uc3** [comment]
@ryscher when you have a minute, could you provide a link to the method(s) or class in the Dryad codebase that executes character filtering? Just looking to get a better idea of which characters are removed/filtered. Thanks!

**Comment by ryscher** [comment]
Dryad's filename filtering is at 
https://github.com/CDL-Dryad/dryad-app/blob/9db04a72e5c38b288a05bec973463c50d7d7162b/stash/stash_engine/app/models/stash_engine/file_upload.rb#L175

However, @elopatin-uc3, I'm not certain that any changes are required to Merritt in this case. We may be able to do enough on the Dryad end.

**Comment by sfisher** [comment]
I believe the correct thing to do is on the Dryad end and to *urldecode* any filenames from URLs so they are standard filenames, just like the ones that are uploaded by file.

Any filenames should be *urlencoded* when they are sent as part of URLs, obviously.  Most likely the filenames that have spaces in them are currently being urlencoded (twice since they were not decoded the first time).

This is a URL you can enjoy that has (urlencoded) spaces in it.  http://www.ulianka.com/images/animals/Cat%20dog%20Acrylic.jpg .
