### ISSUE TITLE
Deletion of file that never existed in Merritt

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#840]
The resource_ids 59158, 62061 and 80770 are three versions in a series.  The first showed a file called rna.fas that was copied unchanged into version 2 and attempted to delete in version 3.

The weird part is that even though we showed rna.fas in our database, it was never in Merritt (in any version).  See https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5zd39bj .  I removed the delete request and got it to submit successfully to Merritt (since the file didn't exist, anyway).

The first two versions were in Mar/April.  We made some file versioning changes in the last few months to fix some edge cases where people add/remove/add/remove files with the same name repeatedly within a version before submitting.  It may be related to that or I'm not sure what happened.

Anyway, we can watch or try to duplicate, but IDK how this ever came about.  The hard part about this is trying to duplicate the problem at all.

**Comment by ryscher** [comment]
This item has been fixed.
