### ISSUE TITLE
Remove uc3@cdlib.org from bcc on emails (errors, downloads, etc)

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#842]
these are spamming UC3/CDL fresh desk, remove that email alias from any bcc that we are using on emails and just have things go to Ryan, Scott, Daniella (and other devs as applicable)

**Comment by elopatin-uc3** [comment]
Thanks @dlowenberg

**Comment by sfisher** [comment]
I don't think we were BCCing this anywhere.  I searched through all our code and configuration and the uc3@ucop.edu email was only used in one place as a "reply to" email in some places.  Maybe if emails bounced it might go to it.

Anyway, I removed it there.  If this keeps happening then it may be coming from elsewhere and it would be helpful to see what the emails look like that go there so we can track it down.
