### ISSUE TITLE
Erroring downloads for identifier 10.5061/dryad.mkkwh70xd

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#849]
This identifier is having download issues.  This is a dataset that was submitted about the time of the Merritt problems on Friday morning.

identifier_id: 53622

When you look at the resources for this one, there are two different ARKs being returned by Merritt (in the download_uri).  There is one for version 1 and a different one for version 2-4.

The one that is failing downloads is version 4.

More investigations in the Merritt UI.  This shows as two separate objects.  
https://merritt.cdlib.org/m/ark%3A%2F13030%2Fm5bw2v67  (version 1)

and

https://merritt.cdlib.org/m/ark%3A%2F13030%2Fm5s524mq (versions 2-4)

The request is for https://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5s524mq/4/producer%2Fprob4.for?no_redirect=true (which makes sense that it fails because in Merritt there are only 3 versions).

I tracked down the update requests we send to Merritt-Sword and they show updating with the correct DOI and Merritt-sword handles it from there, but it used a different ARK for the update then it gave us for the original request.

It looks like this was a wider problem around the maintenance on Thursday night.

This query helps find mismatched ARKs for the same DOI.

```
SELECT res1.identifier_id, res1.created_at as created1, res1.id as res_id1, SUBSTRING_INDEX(res1.download_uri, 'ark%3A%2F', -1) ark1,
res2.created_at created2, res2.id res_id2, SUBSTRING_INDEX(res2.download_uri, 'ark%3A%2F', -1) ark2, ids.identifier as doi FROM
stash_engine_resources res1
JOIN
stash_engine_resources res2
ON res1.identifier_id = res2.identifier_id
JOIN
stash_engine_identifiers ids
ON res1.identifier_id = ids.id
WHERE res1.download_uri <> res2.download_uri
AND SUBSTRING_INDEX(res1.download_uri, 'ark%3A%2F', -1) <> SUBSTRING_INDEX(res2.download_uri, 'ark%3A%2F', -1)
AND res1.id < res2.id
ORDER BY ids.identifier, res1.created_at;
```

This list of affected items seems to be, these, though I'm primarily concerned about the recent ones right now.
```
identifier_id	created1	res_id1	ark1	created2	res_id2	ark2	doi
32903	2019-09-18 02:09:09	34335	13030%2Fm5cg4wbc	2019-11-19 05:19:59	43578	13030%2Fm5ps32rb	10.5061/dryad.05qfttdz1
53606	2020-09-03 18:51:53	81061	13030%2Fm5907gcj	2020-09-06 15:13:10	81360	13030%2Fm5ms95dr	10.5061/dryad.0rxwdbrxg
53629	2020-09-04 08:50:52	81142	13030%2Fm5q58265	2020-09-04 19:05:19	81247	13030%2Fm5713d1f	10.5061/dryad.12jm63xw3
53619	2020-09-04 02:13:30	81108	13030%2Fm5vx5v4g	2020-09-04 22:29:55	81286	13030%2Fm5fj7vfr	10.5061/dryad.2ngf1vhkw
53575	2020-09-03 13:36:37	80993	13030%2Fm5zp9jqd	2020-09-04 18:40:18	81237	13030%2Fm5gj4wk4	10.5061/dryad.fn2z34trw
38092	2019-11-20 18:53:52	43890	13030%2Fm5fv3swb	2019-11-25 12:25:08	44407	13030%2Fm5qs00fn	10.5061/dryad.kc835
53622	2020-09-04 04:55:05	81120	13030%2Fm5bw2v67	2020-09-06 14:30:41	81358	13030%2Fm5s524mq	10.5061/dryad.mkkwh70xd
35802	2019-10-14 05:58:17	38998	13030%2Fm56f10m5	2019-10-15 00:53:25	39144	13030%2Fm5673kv1	10.5061/dryad.t4b8gthxd
53650	2020-09-04 15:07:58	81195	13030%2Fm5810f85	2020-09-07 23:16:23	81493	13030%2Fm5c58zfz	10.5061/dryad.v15dv41tq
53626	2020-09-04 06:47:12	81129	13030%2Fm53c1btc	2020-09-06 20:18:47	81378	13030%2Fm5005dr3	10.5061/dryad.vx0k6djpr
```

**Comment by LoriEP** [comment]
@sfisher just a note: this error occurred after a curator uploaded a readme for the author. The author already had a file uploaded prior to the curator uploading that readme file on their behalf. The curator had no trouble dl'ing the author uploaded file. I have seen this happen before, same issue, when I uploaded a file for the author after they had already successfully uploaded a different file prior. Just FYI.

**Comment by sfisher** [comment]
Here is a way to get the list of objects that had the their Merritt ARKs change and list them in order by DOI and resource id (version).

```
SELECT ids.identifier, res.identifier_id, res.id, res.download_uri, se_sl.created_at as submitted_at, se_sl.archive_response,
vers.version, vers.merritt_version
FROM stash_engine_resources res
JOIN stash_engine_identifiers ids
ON res.identifier_id = ids.id
JOIN stash_engine_versions vers
ON res.id = vers.resource_id
LEFT JOIN stash_engine_submission_logs se_sl
ON res.id = se_sl.resource_id
WHERE res.identifier_id IN
(SELECT DISTINCT res1.identifier_id FROM
stash_engine_resources res1
JOIN
stash_engine_resources res2
ON res1.identifier_id = res2.identifier_id
WHERE res1.download_uri <> res2.download_uri
AND SUBSTRING_INDEX(res1.download_uri, 'ark%3A%2F', -1) <> SUBSTRING_INDEX(res2.download_uri, 'ark%3A%2F', -1)
AND res1.id < res2.id)
ORDER BY res.identifier_id, res.id;
```

**Comment by sfisher** [comment]
Mark and I fixed all of these manually.
