### ISSUE TITLE
Please associate Alyssa Cirtwill's  ORCID (0000-0002-1772-3868) with prior Dryad email(s)

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#852]
**Request**
Please merge the following email addresses (alyssa.cirtwill@liu.se) (alyssa.cirtwill@gmail.com) with ORCID (0000-0002-1772-3868)

**Comment by sfisher** [comment]
I merged her datasets and activity into the account she is currently using and has that ORCID from her latest login.  (ORCID didn't release the email address to us.)

**Comment by LoriEP** [comment]
Thank you
