### ISSUE TITLE
Lift embargo / figure out why it's 'published' but incognito it's embargoed: 10.5061/dryad.qn3287b

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#862]
Began in the old system, embargo was introduced somewhere, it was published for some period of time, author wrote in yesterday asking for embargo to be lifted (hence curation --> publication on 9/14). Curators can't figure out why it's showing as embargoed even when they publish it.

**Comment by ryscher** [comment]
I have updated this item so it is no longer embargoed. However, I was not able to determine why the embargo wasn't released properly.
