### ISSUE TITLE
Multiple author ORCID changes for doi: 10.5061/dryad.12jm63xvf

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#867]
**Request**

Please add ORCIDs for following authors:
Peter Greasley: 0000-0002-2529-4477
Sofia Tapani: 0000-0001-9049-6350
Björn Carlsson: 0000-0002-3023-9878

**Comment by sfisher** [comment]
Thanks, @LoriEP.  It's updated.
