### ISSUE TITLE
User cannot uncheck PPR checkbox on Review and Submit page

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#869]
**Bug description:**
User's dataset was in Private for Peer Review, when they received the automated reminder that dataset was in PPR, they had no PPR checkbox on the Review and Submit page.

**Steps to reproduce:**
1. Navigate to this doi: 10.5061/dryad.ghx3ffbjq
2. Review Activity Log, see that dataset was in PPR initially 
3. Edit dataset, navigate to page 3 (Review and Submit page)
4. See that there is no PPR checkbox available or visible

**Expected behavior:**
1. If a user can select Private for Peer Review by checking the checkbox, they should be able to uncheck that box later to lift item out of PPR.

FogBugz # 51369

**Comment by LoriEP** [comment]
<img width="1329" alt="Screen Shot 2020-09-17 at 3 41 08 PM" src="https://user-images.githubusercontent.com/11345623/93535653-3f8eed80-f8fc-11ea-8b38-11604c29b6e0.png">

**Comment by ryscher** [comment]
This specific dataset is now published, but the underlying problem remains. The dataset was originally placed in peer review 11/25/2019. Then later, it was associated with a journal that does not allow peer review, on 05/27/2020. So although the user could still edit the dataset, they could not revoke the peer review status.

Options for a solution:
1) Always allow users to see the checkbox if the dataset is in peer review, regardless of the journal settings.
2) When a journal is added, if the current status is not allowed by the journal's settings, force the status to change.

**Comment by LoriEP** [comment]
Another example: 10.5061/dryad.dz08kprw0
