### ISSUE TITLE
Metadata import concerns from JEB

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#872]
10.5061/dryad.r4xgxd29n author wrote in to the journal office saying that they could not get the metadata import to work (MS # JEB-2020-00234.R1)

Just want to confirm that this is not a bug

**Comment by sfisher** [comment]
![Screen Shot 2020-09-18 at 9 03 09 AM](https://user-images.githubusercontent.com/105433/93620107-57af4d00-f98e-11ea-9c42-775cea287afc.png)

It didn't fill in for me, either, if this information about the journal is correct, but IDK the Dryad-v1 state of the information that gets transferred across to fill.

**Comment by ryscher** [comment]
This manuscript is no longer active.
