### ISSUE TITLE
Update/cleanup journal name & ISSN

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#875]
Update 20 datasets where the ISSN references one of the Royal Society journals with ‘London’. Reassign them and remove the ‘London’ entries so they don’t show up in the autocomplete anymore. Double check that no other journals for RS showing up with London or are duplicative

Also, update journal names:
The Auk --> Ornithology
The Condor --> Ornithological Applications

Also, update journal contact from Patricia Morse to general email address amnat@press.uchicago.edu

**Comment by ryscher** [comment]
- Renamed Ornithology journals
- Updated contacts for The American Naturalist
- Merged the Royal Society's "London" journals into the equivalent journals without "London"
- Merged other Royal Society journals that have had name changes over the years (e.g., merged Royal Society of Edinburgh's "Biology" with "Biological Sciences")
