### ISSUE TITLE
Void invoice 10.5061/dryad.3tx95x6bn (Royal Society)

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#882]
Email sent to Ryan already

**Comment by ryscher** [comment]
I have updated the payment information in our database, and asked Tracy to have cxore void the invoice. It appears this dataset was originally submitted with an incorrect journal listing, although I cannot tell which journal it was originally associated with. The dataset was published, and invoice generated, at 2020-8-28 21:17:40 UTC. The journal information was updated shortly afterward, at 2020-8-28 21:23:47 UTC.
