### ISSUE TITLE
Warning error that Related Works doi cannot be verified for dataset: 10.5061/dryad.t4b8gtj07

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#887]
**Bug description:**
Article entered in the Related Works section is throwing a warning for article doi: https://doi.org/10.1371/journal.pone.0036904

**Steps to reproduce:**
View dataset: 10.5061/dryad.t4b8gtj07
Click on edit
Review the Related Works section
See warning for related work (see image also)
<img width="1300" alt="Screen Shot 2020-09-30 at 10 28 56 AM" src="https://user-images.githubusercontent.com/11345623/94719885-9f2bc680-0308-11eb-8e6c-99abd27d51f5.png">

**Expected behavior:**
DOI is resolvable so no warning should be displayed

**Comment by ryscher** [comment]
This has been improved.
