### ISSUE TITLE
Q3 shopping cart report

### ISSUE THREAD

**Issue by tracykteal** [CDL-Dryad/dryad-product-roadmap#897]
It's quarterly invoicing time again. Could I please get the Q3 shopping cart report.

**Comment by ryscher** [comment]
Report is now available at https://docs.google.com/spreadsheets/d/18ASrxeLcTbgf2zssgvSyr48mPQyqTI7cLSONqbA2HxU/edit?usp=sharing

**Comment by tracykteal** [comment]
thanks!
