### ISSUE TITLE
UCSB Dash Instance

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#90]
Ticket for Scott to put up a live production instance of UCSB Dash by the end of the sprint.

Certificates complete confirmed by Jim

Marisa working on Incommon metadata for shib

Data Deposit Agreement text to be included like UC Davis.

Change license to CC0 (from CCBY)

**Comment by marisastrong** [comment]
[ ] Test that shibboleth/Incommon attributes are being returned properly 
Incommon metadata has been approved for stg and prod so should see these changes on the server by 9/26.
[ ] Greg Janee has submitted attribute release form for UCSB IdP
[ ] Certs need to be set up
[ ] Scott has work on the application side

**Comment by marisastrong** [comment]
- [ ] @jimvanderveen setup vhost for stg.dash.ucsb.edu for testing and dash.ucsb.edu in production
