### ISSUE TITLE
Please withdraw dup dataset doi: 10.5061/dryad.dncjsxkw7

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#901]
**Request**
Withdraw doi:10.5061/dryad.dncjsxkw7

**Comment by LoriEP** [comment]
@dfagandryad

**Comment by ryscher** [comment]
I've set the curation status to `withdrawn` and added a note. However, I believe we should also withdraw the copy from Zenodo....not sure whether we have a process for that yet.

**Comment by ryscher** [comment]
I have requested that this be removed from Zenodo.
