### ISSUE TITLE
Please manually waive DPC (fee) for dataset doi: 10.5061/dryad.95x69p8j2

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#919]
**Request:**
Waive fee 
FB 56828

**Comment by sfisher** [comment]
I do not see an invoice for this one the payment type is  'unknown' and payment id isn't set.

Maybe @ryscher will have more insight into waiving a fee that hasn't been charged yet.  Or maybe something needs to be set because the journal is paying?

**Comment by LoriEP** [comment]
Thanks @sfisher, yes I believe @ryscher can manually waive the fee prior to publishing/invoicing. If not, we can wait until it is published and I can follow up on this ticket then.

**Comment by ryscher** [comment]
According to the FogBugz ticket, the waiver is due to a country waiver. I manually set payment_type to 'waiver' and payment_id to 'Brazil'. The dataset will not generate an invoice now.

**Comment by LoriEP** [comment]
Thanks @ryscher
