### ISSUE TITLE
Test login that doesn't require orcid registration for development

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#920]
Doing this for @terrywbrady  and his spin up/down, on-demand docker containers. 

Normally we need to register each servername with ORCID, which takes emailing and a day (or longer).

This allows bypassing the normal ORCID login with a test one, but only in *non-production* environments and only if the environment variable TEST_LOGIN is set in the environment.

**Comment by terrywbrady** [comment]
Thanks @sfisher .  I blocked some time on Monday to test this.  This sounds like it will integrate nicely!
