### ISSUE TITLE
Notes in activity log not consistently logged

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#922]
Activity log is not recording notes left when a curator edits a dataset (on page 3 before submit we require a note to be left), nor is it recording a note left when you change the status from the admin layer and it has a notes option.

Example:
10.25338/B8SW5G -- Tracy curated and made some metadata changes which appear, and dataset acted as normal, but no note was recorded by her

**Comment by sfisher** [comment]
I believe those notes are recorded in a different place as "edit notes" which existed before the curation status notes.
