### ISSUE TITLE
Please change pub date, add ORCID for dataset doi:10.5061/dryad.w0vt4b8n1

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#924]
**Request:**
(1) Change the date for the remaining data file Horton_etal_10.1098rspb.2020.0196.pdf from 'October 26, 2020' to 'March 9, 2020'.
(2) Add an ORCID (https://orcid.org/0000-0002-1006-2358) for the author Maney, Donna L.

FB ticket# 56952

**Comment by sfisher** [comment]
Her orcid is already set:

![Screen Shot 2020-10-26 at 3 36 14 PM](https://user-images.githubusercontent.com/105433/97235872-11c18200-17a1-11eb-96cf-73426b7c2963.png)

![Screen Shot 2020-10-26 at 3 37 45 PM](https://user-images.githubusercontent.com/105433/97235948-3f0e3000-17a1-11eb-9b12-72b76e62eee5.png)

But I set the date for publication to March.

**Comment by LoriEP** [comment]
Thanks @sfisher

**Comment by sfisher** [comment]
You're welcome.  :-)
