### ISSUE TITLE
Please waive DPC for dataset doi: 10.5061/dryad.zs7h44j67

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#927]
**Request:** Please process as country waiver :Brazil 

We will void invoice. FB 57055

**Comment by ryscher** [comment]
This dataset is currently associated with the journal Functional Ecology, which has a payment plan. However, I see in the FogBugz ticket that the author was asking about the journal Oecologia. I applied the country waiver, but should I switch the journal as well?

**Comment by LoriEP** [comment]
In the Internal Data I see it correctly associated with Oecologia with a log date of 7/4/20. That is strange.

**Comment by ryscher** [comment]
Yes, it is correctly associated in the internal data. I don't know why it had Functional Ecology in the payment info. I won't worry about this for now, unless it happens more often.
