### ISSUE TITLE
Please embargo dataset doi:10.5061/dryad.dz08kprw9

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#937]
**Request:** Please place one year embargo on RSPB dataset, published in error.

**Comment by ryscher** [comment]
Applied embargo to published version and two in-progress versions

**Comment by LoriEP** [comment]
@ryscher this dataset is showing as Published (system message says pub date reached)

**Comment by ryscher** [comment]
Sorry about that! I must have neglected to update the year, so the embargo was released the next day. I've corrected it now.
