### ISSUE TITLE
Dataset status 'Published' but data still embargoed 10.5061/dryad.j3tx95xbx

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#945]
**Bug description:**
Dataset doi:10.5061/dryad.j3tx95xbx is set to status 'Published' but data is 'Embargoed'

**Steps to reproduce:**
- Navigate to dataset, see status is = Published, in an incognito mode navigate to dataset and see data is 'Embargoed'

**Expected behavior:**
- Dataset with status 'Published' following embargo should be available 

**Additional dataset to fix:**
10.5061/dryad.bv10m57

**Comment by LoriEP** [comment]
duplicate of other ticket and bug

**Comment by ryscher** [comment]
Data is now viewable/downloadable.
