### ISSUE TITLE
Please merge email addresses associated with Allison Theobold's ORCID (0000-0002-8092-6182)

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#960]
**Request:**

Please associate email address atheobol@calpoly.edu with this ORCID and merge old email address allisontheobold@montana.edu as author no longer has access to it

**Comment by ryscher** [comment]
Author had two accounts with two separate ORCIDs. Both accounts had been used on November 28th, within a minute of each other. Merged them into the account with 0000-0002-8092-6182.
