### ISSUE TITLE
Make checksums available via API

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#962]
Dryad checksums are currently one-way. That is:
- Checksums are validated if they are provided by the depositor. When files are deposited to Dryad through the API and a checksum is provided, Merritt will validate the checksum.  
- Checksums are not provided to data consumers, *unless* a checksum was provided at the time of deposit. When files are deposited through the UI, Dryad does not calculate a checksum. Merritt does calculate a checksum, but this is not propagated back into the Dryad database, and is not available to Dryad's users.

It would be useful for the Merritt checksums to be copied into the Dryad DB, so they could be provided to Dryad data consumers through our normal API calls.

This discrepancy was pointed out by UBC, though I believe it is currently low on their priorities.

**Comment by sfisher** [comment]
Most consumers don't supply digests.  I suspect some would be baffled if asked for one when uploading files or entering URLs.  If this is a priority to include in a UI, then it might be an optional item we add as part of upload reworking.  My guess is that many (most) people uploading wouldn't use it, but maybe some power users might.

We currently do calculate digests when uploading to zenodo.  Under the stash engine files stash/ there are some classes to work with Merritt and to work with Zenodo.  If a digest exists in the database then it is checked against the file digest when downloading.  When the file is uploaded again to zenodo it has digests checked against the digest they provide.  One of the digests is md5 and the other is sha256, I believe, so we have to calculate two different digests.

If we got digests from Merritt it would add another level in the chain, though we're still lacking the initial digest when people upload or when they put in URLs for retrieval, so we don't exactly know if Merritt retrieved it correctly.

I suspect that for some types of corruption, if the author views the files after uploading them they may notice if there are any problems with them and are probably quite rare.

**Comment by ryscher** [comment]
UBC has reiterated their desire for this feature.

**Comment by sfisher** [comment]
Seems like a good API feature and maybe we can get digests for many items easily from S3 or Merritt.  For some items I believe S3 doesn't supply a correct MD5 if it was broken into chunks to upload or for items larger than 5GB.

**Comment by ryscher** [comment]
S3 now has built-in support for checksums: https://aws.amazon.com/blogs/aws/new-additional-checksum-algorithms-for-amazon-s3/

**Comment by ahamelers** [comment]
When we start routinely recording the checksums in our database (#2792), it would make sense to me to remove upload URLs from the file list API entirely (#2990) and add digests there instead
