### ISSUE TITLE
Download dataset produces older files that were never published 

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#965]
**Bug description:**
For dataset 10.5061/dryad.dfn2z34x9 the download dataset button downloads a larger package of data with data files, rather than the only zip file published on September 9, 2020. 

**Steps to reproduce:**
Navigate to dataset
Click on the individual data file 'Reeves_et_al_2020_supplement.zip' from September 9, 2020 review the files 
Then, click on the download dataset button, a larger number of files are downloaded, including the September 9, 2020 zip

**Expected behavior:**
The Download dataset button should download the same data files that are in the Data Files section as there is only one published date for the dataset

**Comment by ryscher** [comment]
The extra files were introduced in early versions of this dataset, but had somehow been lost from the Dryad database, while they were retained in Merritt. I versioned the dataset, and forced Merritt to remove these files in the latest version. I also made the older version invisible to normal users.
