### ISSUE TITLE
Please associate Michael MacDonald with member tenant Montana State University

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#966]
**Request:**
Please update email address macdonald.mik@gmail.com with Montana State U. 

If necessary for shopping cart purposes dataset where sponsor needs to be adjusted 10.5061/dryad.zcrjdfn9b

**Comment by ryscher** [comment]
I merged two "Michael MacDonald" accounts. There is a third "Michael MacDonald", but this appears to be a different person (email address in the UK). I changed the tenant for the merged account to `msu`, and updated the payment information on the dataset. I see that the Stripe invoice has already been voided.

Nitpicky note for myself and @sfisher -- it's confusing that the tenant name for Montana State is `msu`, when the `msu.edu` domain name is Michigan State. Perhaps we should base tenant names on domain names in the future?
