### ISSUE TITLE
User cannot migrate data from v1 account

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#968]
**Request:**
User reports that data migration is not working and they are receiving the following error: "The email address you've validated does not match any that was used in the previous system. Please contact us if you need assistance." but they insist their email address/ORCID has stayed the same. 

User information:
ORCID: 0000-0002-7324-7448
email address: sakh@uab.edu

Perhaps they created duplicate ORCIDs?

**Comment by ryscher** [comment]
Merged 3 accounts:
- kruegersa@cofc.edu
- quooddy@sbcglobal.net
- sakh@uab.edu, 0000-0002-7324-7448

I was able to verify that these are all the same person by comparing dataset titles with the papers listed on the ORCID account.

**Comment by ryscher** [comment]
Perhaps the migration tool is losing effectiveness, since users have not been able to log into the v1 system in over a year, and it is probably difficult for them to remember their old emails.

**Comment by ryscher** [comment]
For future reference: as of 2020-12-01, the migration tool has been used about 90 times in the past two months. 

To see users that have used the migration tool: 

`select id, first_name, last_name, last_login, orcid, updated_at from stash_engine_users where orcid like '%migrated' order by updated_at;`
