### ISSUE TITLE
MIME type differences between Dryad and Merritt

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#969]
Some files get one MIME type in Dryad and a different type in Merritt. This can cause issues when downloading the file.

For example, in 10.5061/dryad.nzs7h44p1, there is a file with the extention `.pzfx`. This file downloads properly from the "Download dataset" button. When you click on the filename, it opens in the browser as a generic XML file. This would be ok, but attempts to save the file will create a file with `.xml` extension, and the original extension is lost, so the file extension needs to be changed before it will open in the software specific to that filetype.

Curators have also noticed this phenomena with `.bam` files.

It appears the problem stems from the MIME type. In Dryad, the example file above has a type of `application/octet-stream`, but in the Merritt UI, it is listed as `application/xml`.

**Comment by LoriEP** [comment]
10.25349/D95C99 (another example, .bam)

**Comment by elopatin-uc3** [comment]
@ryscher @sfisher Let us know if there's anything we can do from the Merritt side for this.

**Comment by sfisher** [comment]
Not sure if still happening.  I know merritt made some changes.  I thought we also sent mime types with the manifest to Merritt?
