### ISSUE TITLE
Logins without setting a tenant

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#97]
If you login with ORCID and don't subsequently choose a tenant, no tenant is stored in the DB. This can cause problems later, e.g., when the same user tries to submit via the API.

**Comment by ryscher** [comment]
This should be set on the login screen when you choose the "none of the above" for your home institution.

**Comment by sfisher** [comment]
Hi Ryan,

Can you give me any steps to duplicate this?  I created another ORCID sandbox account and logged in.

![screen shot 2018-12-11 at 4 44 29 pm](https://user-images.githubusercontent.com/105433/49839556-723da680-fd64-11e8-93a7-b1609ed7e5c8.png)

Right after I did it my user had the tenant_id set.

![screen shot 2018-12-11 at 4 45 09 pm](https://user-images.githubusercontent.com/105433/49839563-841f4980-fd64-11e8-9c38-e3451e8b4b14.png)

I can always keep redirecting users back to this page when this isn't set before they can create any datasets, but I'd like to know why it's not setting.

Does it work on dev for you or is this only on your machine?  Are all the configurations symlinked in?  Which environment is this for (test? development?).

**Comment by ryscher** [comment]
Resolution: verify that the app_config.yml has a default_tenant set.
