### ISSUE TITLE
New page: "Our Advisors"

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#974]
SAC bios and folder with photos https://drive.google.com/drive/u/0/folders/15Y8N39qChLNsgApo2Bn7vo4Ct813DeZL

**Comment by tracykteal** [comment]
SAC bios and folder with photos https://drive.google.com/drive/u/0/folders/1tqy2hFBPDmPheI8yIv0_d1ixKIH6tPgV
