### ISSUE TITLE
Please change Matt Johnson's member tenant and adjust DPC to be sponsored by Texas Tech

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#982]
**Request:** Please update member tenant for matt.johnson@ttu.edu to Texas Tech University and adjust payment on dataset doi: 10.5061/dryad.76hdr7sv3

Dataset is currently embargoed. Cxore can void the invoice.

**Comment by LoriEP** [comment]
This somehow was not put into triage by me. Apologies.

**Comment by sfisher** [comment]
Ok.  I updated his tenant, dataset tenant and changed the billing info in the database.  I updated his email address which was a gmail address.
