### ISSUE TITLE
New Tenant: Macquarie University

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#983]
Logo in email from Shawn Ross, InCommon metadata (https://met.refeds.org/met/entity/urn%3Amace%3Afederation.org.au%3Atestfed%3Amq.edu.au/?federation=edugain )

**Comment by ryscher** [comment]
Done
<img width="475" alt="Screen Shot 2021-01-18 at 10 54 04 AM" src="https://user-images.githubusercontent.com/605143/104938596-4ba7bc00-597d-11eb-9c6e-39d757c3943a.png">
<img width="882" alt="Screen Shot 2021-01-18 at 10 56 32 AM" src="https://user-images.githubusercontent.com/605143/104938611-506c7000-597d-11eb-8ae8-da3107afcfa9.png">
