### ISSUE TITLE
New Tenant: Kyoto University

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#984]
Coordinate with Marisa & Ashley

Logo: https://www.dropbox.com/sh/qqlnlpgjvbddffk/AAAW6VYfwCJvGRfRZkjfBtU7a?dl=0

**Comment by marisastrong** [comment]
added some comments for @ashleygould in the PT https://www.pivotaltracker.com/story/show/176152723 

Kyoto Prod EntityID entityID="https://authidp1.iimc.kyoto-u.ac.jp/idp/shibboleth"
Kyoto Stage EntityID entityID="https://authidp2.iimc.kyoto-u.ac.jp/idp/shibboleth"
